- README.md
Done:
- Update the badge URLs.
- Format the markdown with prettier.
QA: 
- Visit the URLs for the CircleCI badge, they should resolve.
Fixes: #https://github.com/canonical-web-and-design/MAAS-squad/issues/1239.
> Fix CircleCI badge url and format markdown

- ui/.eslintrc.json
- ui/package.json
- yarn.lock
Added [eslint-plugin-no-only-tests](https://www.npmjs.com/package/eslint-plugin-no-only-tests) which prevents us committing tests using `it.only`.
* Change a test to use `it.only`, save the file, run `yarn lint` and it should complain with something along the lines of:
```
12:6  error  it.only not permitted  no-only-tests/no-only-tests
```
> Add eslint-plugin-no-only-tests.

- ui/src/index.js
Turned on react strict mode. You may notice components with `useState` rendering twice now, but that is [by design](https://github.com/facebook/react/issues/15074). 
* Run the app, we shouldn't have any console warnings.
* Do something that makes Dan Abramov sad e.g. render a component using a deprecated lifecycle method like `componentWillUpdate()`, the app should complain in the console.
> Enable react strict mode.

- .circleci/config.yml
Split us circle jobs into separate build steps.
None, CI should pass with distinct steps for `build`, `lint` and `test`.
> Separate circle ci jobs.

- ui/src/app/base/sagas/utils.js
- ui/src/app/base/sagas/utils.test.js
- ui/src/app/base/sagas/websockets.js
- ui/src/app/base/sagas/websockets.test.js
* Provide csrftoken in querystring when opening websocket connection. (No need to hack `protocol.py` now!)
* Revert hacks to `protocol.py`, login and opening the websocket connection should work.
> Open websocket connection with csrftoken from cookie.

- README.md
- ui/README.md
Done:
Add setup instructions for MAAS UI to the README
QA:
- Read through the instructions and confirm they are clear and make sense
- If you don't have MAAS UI setup locally try these instructions and check they work as expected
> Add setup instructions to README

- .circleci/config.yml
Circle provides 2 vCPUs, so set jest max-workers to 2 to [resolve OOM issues](https://discuss.circleci.com/t/babel-7-jest-results-in-timeout/25383/3).
None, CI should pass without errors.
> Set max-workers to 2 for CI.

- ui/src/app/base/sagas/websockets.js
- ui/src/app/base/sagas/websockets.test.js
- ui/src/websocket-client.js
- ui/src/websocket-client.test.js
* Handle `params` passed as an array, unblocking implementation of a config update action.
* Removed error handling code from the client, instead have the caller catch errors.
* In the redux devtools, dispatch an update action with params as an array (note that we don't use `{"name": foo, "value": bar}`). 
e.g.
```
{
type: "WEBSOCKET_SEND",
payload: {
actionType: "UPDATE_CONFIG",
message: {
method: "config.update",
type: 0,
params: [
{ name: "maas_name", value: "foobar" },
{ name: "enable_disk_erasing_on_release", value: false }
]
}
}
}
```
This is an interim branch to unblock others, refactoring to come. The fact that `params` is an overloaded term (it can be a payload, it can be actual params for changing a response e.g. limit), is a detail we should hide in our action implementation.
> Allow params to be passed as array.

- ui/src/app/base/actions.js
- ui/src/app/base/actions.test.js
- ui/src/app/base/sagas/websockets.js
- ui/src/app/base/sagas/websockets.test.js
- ui/src/app/settings/actions/config.js
- ui/src/app/settings/actions/config.test.js
- ui/src/app/settings/actions/repositories.js
- ui/src/app/settings/actions/repositories.test.js
- ui/src/app/settings/actions/users.js
- ui/src/app/settings/actions/users.test.js
- ui/src/app/settings/containers/Settings/Settings.test.js
* The generic `WEBSOCKET_SEND` action type has been removed in favour of flux standard actions (we can now easily see which actions are being dispatched in redux devtools).
* websocket `sendMessage` now listens for any actions which have an RPC method in their payload.
* Move `method` and `type` to the `meta` object in redux actions. See [flux standard actions](https://github.com/redux-utilities/flux-standard-action#meta).
I considered moving knowledge of the RPC methods/metadata into the sagas, but on reflection I think this is okay in the action creators. 
* Load the app, you should see specific redux action types in redux dev tools.
> Use standard redux actions.

- ui/src/app/base/components/ActionButton/ActionButton.js
- ui/src/app/base/components/ActionButton/ActionButton.scss
- ui/src/app/base/components/ActionButton/ActionButton.test.js
- ui/src/app/base/components/ActionButton/__snapshots__/ActionButton.test.js.snap
- ui/src/app/base/components/ActionButton/index.js
- ui/src/app/base/components/Loader/Loader.js
- ui/src/app/base/components/Loader/Loader.scss
- ui/src/app/base/hooks.js
- ui/src/app/settings/actions/config.js
- ui/src/app/settings/actions/config.test.js
- ui/src/app/settings/components/GeneralForm/GeneralForm.js
- ui/src/app/settings/containers/Storage/Storage.js
- ui/src/app/settings/containers/Storage/Storage.test.js
- ui/src/app/settings/containers/StorageForm/StorageForm.js
- ui/src/app/settings/containers/StorageForm/StorageForm.test.js
- ui/src/app/settings/containers/StorageForm/index.js
- ui/src/app/settings/containers/StorageFormFields/StorageFormFields.js
- ui/src/app/settings/containers/StorageFormFields/StorageFormFields.test.js
- ui/src/app/settings/containers/StorageFormFields/index.js
- ui/src/app/settings/proptypes.js
- ui/src/app/settings/reducers/config.js
- ui/src/app/settings/reducers/config.test.js
- ui/src/app/settings/selectors/config.js
- ui/src/app/settings/utils.js
- ui/src/app/settings/utils.test.js
- ui/src/scss/base.scss
- Added save functionality to Storage form
- Reworked Storage form to use FormikField component
- Updated Storage form styling (no title, left-aligned button)
- Added ActionButton component which wraps Button. It takes props to determine whether it's in a loading or success state. It takes an explicit width prop which is a bit crap but I couldn't figure out how to store button width in the hooks world and figured this works fine for now :man_shrugging: 
- Added some hooks that essentially "fake" a delay after clicking Save, even though saving happens almost instantly and therefore saving state is `false`. Success state is simply determined as "saving state moved from true => false" so will probs need some handling for when that happens due to an error.
- Go to Storage and check that the …
> Add save functionality to Storage form + build ActionButton

- ui/src/scss/_settings.scss
Done:
- Update the brand color to #333 (the default). Fixes: https://github.com/canonical-web-and-design/MAAS-squad/issues/1405.
QA:
- Load the settings.
- Check that the nav indicator on the left is #333.
> Update brand colour

- ui/src/app/base/components/Main/Main.js
- ui/src/app/base/components/Main/Main.test.js
Done:
- Disable the settings views if the user is not an admin. Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/52.
QA:
- Log into maas as a non admin.
- Load maas-ui. You should get a message about no permissions.
- Log in again as admin.
- Reload the UI. You should now see the views.
> Limit settings views to admins

- ui/src/app/settings/components/Nav/Nav.js
- ui/src/app/settings/components/Nav/__snapshots__/Nav.test.js.snap
- ui/src/app/settings/components/Routes/Routes.js
- ui/src/app/settings/containers/Configuration/Commissioning/Commissioning.js
- ui/src/app/settings/containers/Configuration/Commissioning/Commissioning.test.js
- ui/src/app/settings/containers/Configuration/Commissioning/index.js
- ui/src/app/settings/containers/Configuration/CommissioningForm/CommissioningForm.js
- ui/src/app/settings/containers/Configuration/CommissioningForm/CommissioningForm.test.js
- ui/src/app/settings/containers/Configuration/CommissioningForm/index.js
- ui/src/app/settings/containers/Configuration/CommissioningFormFields/CommissioningFormFields.js
- ui/src/app/settings/containers/Configuration/CommissioningFormFields/CommissioningFormFields.test.js
- ui/src/app/settings/containers/Configuration/CommissioningFormFields/index.js
- ui/src/app/settings/containers/Configuration/General/General.js
- ui/src/app/settings/containers/Configuration/General/General.test.js
- ui/src/app/settings/containers/Configuration/General/index.js
- ui/src/app/settings/containers/Configuration/index.js
- ui/src/app/settings/selectors/config.js
- ui/src/app/settings/selectors/config.test.js
Create the commissioning form in the configuration section of settings. Fixes [#1385](https://github.com/canonical-web-and-design/MAAS-squad/issues/1385) and [#1409](https://github.com/canonical-web-and-design/MAAS-squad/issues/1409).
- go to `/settings/configuration/commissioning`
- See the commissioning form
- See the save button is disabled
- See if you change the values of either field the save button is enabled
- See if you change the values and save that they persist when you reload the page
> Create settings configuration commissioning form

- ui/src/app/settings/containers/Network/ProxyForm/ProxyForm.js
- Go to /MAAS/settings/network/proxy
- Click External or Peer
- Check that there are no type errors in the console
> Convert http_proxy value to empty string if fetched as null

- ui/src/app/base/sagas/websockets.js
- ui/src/app/base/sagas/websockets.test.js
- ui/src/app/settings/reducers/config.js
- ui/src/app/settings/reducers/config.test.js
* Handle incoming 'sync' websocket messages. (messages with `type: 2` and an `action`)
* No longer update config state on receiving a `type: 1` response.
* Update config state upon receiving a sync message.
* `UPDATE_SUCCESS` now results in setting `saved` in state. The UI should rely on this state, and we'll just assume that the state becomes eventually consistent reliably and quickly. Sync messages tend to follow response messages within milliseconds, so practically this should be fine I think.
* Save a form.
* Check the diff for SUCCESS actions in redux dev tools, ensure item state is not touched.
* Check the diff for SYNC actions, ensure the changed fields value is updated in state.
> Handle type 2 sync messages and update config state

- ui/src/app/base/components/Section/Section.scss
- Remove height of header nav from section height so there isn't a 3rem overflow
- Load a short page and check there is no scrollbar
- Load users page and check that there is a scrollbar
> Remove scrollbar if section content smaller than viewport height

- ui/src/app/base/components/ActionButton/ActionButton.js
- ui/src/app/base/components/ActionButton/ActionButton.test.js
- ui/src/app/base/components/ActionButton/__snapshots__/ActionButton.test.js.snap
- ui/src/app/base/hooks.js
- ui/src/app/settings/containers/Configuration/CommissioningForm/CommissioningForm.js
- ui/src/app/settings/containers/Configuration/GeneralForm/GeneralForm.js
- ui/src/app/settings/containers/Configuration/KernelParametersForm/KernelParametersForm.js
- ui/src/app/settings/containers/Network/DnsForm/DnsForm.js
- ui/src/app/settings/containers/Network/NetworkDiscoveryForm/NetworkDiscoveryForm.js
- ui/src/app/settings/containers/Network/NetworkDiscoveryFormFields/NetworkDiscoveryFormFields.test.js
- ui/src/app/settings/containers/Network/NtpForm/NtpForm.js
- ui/src/app/settings/containers/Network/ProxyForm/ProxyForm.js
- ui/src/app/settings/containers/Network/SyslogForm/SyslogForm.js
- ui/src/app/settings/containers/Storage/StorageForm/StorageForm.js
- ui/src/app/settings/reducers/config.js
- ui/src/app/settings/reducers/config.test.js
- ui/src/app/settings/selectors/config.js
- ui/src/app/settings/selectors/config.test.js
- ActionButton width is now determined by the text, rather than hardcoded.
- Updated instances of ActionButton to remove width prop.
- Timer functions have been moved out of useSettingsSave in hooks.js and in to the ActionButton component itself.
- Removed useSettingsSave hook and replaced with config.saved state.
- Update config reducer so UPDATE_SETTINGS_START sets saved to false.
- Check all the ActionButtons behave as before
- Change one of the ActionButtons to different text
- Check that the button width remains constant from saving to success
> Rewrite ActionButton to control own timeouts + calculate width dynamically

- ui/src/app/settings/selectors/config.js
- ui/src/app/settings/selectors/config.test.js
- ui/src/app/settings/views/Configuration/Commissioning/Commissioning.test.js
- ui/src/app/settings/views/Configuration/CommissioningForm/CommissioningForm.js
- ui/src/app/settings/views/Configuration/CommissioningForm/CommissioningForm.test.js
- ui/src/app/settings/views/Configuration/CommissioningFormFields/CommissioningFormFields.js
- ui/src/app/settings/views/Configuration/CommissioningFormFields/CommissioningFormFields.test.js
Changed the config option from `default_distro_series` to `commissioning_distro_series` for the commissioning form as it was using the incorrect option.
- See that the `default_distro_series` has been changed to `commissioning_distro_series` in the code
- See that the top form field labelled "Default Ubuntu release used for commissioning" still updates when you change it and save.
**Note**: There is a known bug where the second options field doesn't update when the top field changes. This will be fixed in a separate PR.
> Use correct option for commissioning distro series

- ui/src/scss/_patterns_table.scss
- ui/src/scss/_settings.scss
- ui/src/scss/_vanilla-overrides.scss
- ui/src/scss/base.scss
- Updated Vanilla settings to increase density (`$multi = 1`)
- Added a Vanilla overrides file **which we should definitely use**. If we can keep overrides in the same place and to a minimum we should get far less surprising regressions whenever we update Vanilla.
- Go to the users table and check that the density has increased.
- Click around the forms and check that everything looks okay.
> Change Vanilla $multi to 1 + add Vanilla overrides file

- ui/src/app/base/components/FormikField/FormikField.js
- ui/src/app/base/components/FormikField/FormikField.test.js
Done:
- Correctly display the server errors in the user form.
QA:
- Try and add a user with an existing username and click Save
- You should get an error message for the username field.
> Fix user server errors

- ui/src/app/base/sagas/websockets.js
- ui/src/app/base/sagas/websockets.test.js
For payloads with params as an array, ensure each websocket request is committed and blocks on an incoming SYNC message before dispatching the next. This is important for updating dependant config such as `commissioning_distro_series` and `default_min_hwe_kernel` (e.g. changing distro from "Xenial -> Bionic" must be committed before kernel can change from 16.04 -> 18.04).
Unfortunately a bit hard to QA as the only form with dependant config is currently in review, but I would recommend checking out steve's commissioning form branch
```
git checkout -b steverydz-fix-commissioning-form master
git pull https://github.com/steverydz/maas-ui.git fix-commissioning-form
```
and rebasing this on top. Change some config on the commissioning form and ensure you see two UPDATE_CONFIG_SYNCS and no …
> Sequence calls for array params to prevent races for dependant config.

- ui/src/app/settings/actions/general/general.js
- ui/src/app/settings/actions/general/general.test.js
- ui/src/app/settings/actions/general/index.js
- ui/src/app/settings/actions/index.js
- ui/src/app/settings/reducers/general/general.js
- ui/src/app/settings/reducers/general/general.test.js
- ui/src/app/settings/reducers/general/index.js
- ui/src/app/settings/reducers/index.js
- ui/src/app/settings/selectors/config.js
- ui/src/app/settings/selectors/config.test.js
- ui/src/app/settings/selectors/general/general.js
- ui/src/app/settings/selectors/general/general.test.js
- ui/src/app/settings/selectors/general/index.js
- ui/src/app/settings/selectors/index.js
- ui/src/app/settings/views/Configuration/Commissioning/Commissioning.test.js
- ui/src/app/settings/views/Configuration/CommissioningForm/CommissioningForm.js
- ui/src/app/settings/views/Configuration/CommissioningForm/CommissioningForm.test.js
- ui/src/app/settings/views/Configuration/CommissioningFormFields/CommissioningFormFields.js
- ui/src/app/settings/views/Configuration/CommissioningFormFields/CommissioningFormFields.test.js
- ui/src/app/settings/views/Settings.test.js
- ui/src/root-reducer.js
This is carried over from https://github.com/canonical-web-and-design/maas-ui/pull/116
I had some git issues and ended up just making a new PR.
There was some discussion on the previous PR which is worth reviewing.
Updated the settings commissioning form so that the second fields options update when the first option changes. Fixes [#1414](https://github.com/canonical-web-and-design/MAAS-squad/issues/1414)
- Go to `/settings/configuration/commissioning`
- See that the field labelled `Default minimum kernel version` options are related to the above field (i.e. same version number 18.04 etc.)
- Change the field labelled `Default Ubuntu release used for commissioning` and see that the options in the field beneath are updated to reflect the new value
> Fix commissioning form

- ui/src/app/settings/actions/repositories.js
- ui/src/app/settings/actions/repositories.test.js
- ui/src/app/settings/actions/users.js
- ui/src/app/settings/actions/users.test.js
- ui/src/app/settings/reducers/packagerepository.js
- ui/src/app/settings/reducers/packagerepository.test.js
- ui/src/app/settings/reducers/user.js
- ui/src/app/settings/reducers/user.test.js
- ui/src/app/settings/selectors/repositories.js
- ui/src/app/settings/selectors/repositories.test.js
- ui/src/app/settings/views/Repositories/RepositoriesList/RepositoriesList.js
- ui/src/app/settings/views/Repositories/RepositoriesList/RepositoriesList.test.js
- ui/src/app/settings/views/Users/UserForm/UserForm.test.js
- ui/src/app/settings/views/Users/UsersList/UsersList.test.js
- Implemented deleting repos over the api
- Renamed actions to match model names
- `REPOSITORIES` => `PACKAGEREPOSITORY`
- `USERS` => `USER`
- Add some repos at `:5240/MAAS/#/settings/repositories`
- Go to `:8000/MAAS/settings/repositories` and see that you can delete them successfully
- Refresh maas-ui and check back on `:5240/MAAS/#/settings/repositories` to make sure they're gone for real
- Do the same for users just in case the renaming messed something up unexpectedly
> Implement deleting repositories over the API

- package.json
- ui/.gitignore
- ui/README.md
- ui/package.json
* Add new section to README documenting release process.
* Add new yarn script `yarn release`.
* Do a fake release with `yarn release 1.0.0`, and ensure the following:
* Tests pass.
* A tarball called `maas-ui-v1.0.0.tar.gz` is built in `./dist`.
* A git tag "v1.0.0" is created (remember to delete your tag afterwards).
* The app version has been bumped in `package.json`.
> Document release process and add release yarn script.

- ui/src/app/settings/components/Routes/Routes.js
- ui/src/app/settings/selectors/config.js
- ui/src/app/settings/selectors/config.test.js
- ui/src/app/settings/selectors/general/general.js
- ui/src/app/settings/selectors/general/general.test.js
- ui/src/app/settings/views/Configuration/Commissioning/Commissioning.test.js
- ui/src/app/settings/views/Configuration/CommissioningForm/CommissioningForm.test.js
- ui/src/app/settings/views/Configuration/CommissioningFormFields/CommissioningFormFields.js
- ui/src/app/settings/views/Configuration/Deploy/Deploy.js
- ui/src/app/settings/views/Configuration/Deploy/Deploy.test.js
- ui/src/app/settings/views/Configuration/Deploy/index.js
- ui/src/app/settings/views/Configuration/DeployForm/DeployForm.js
- ui/src/app/settings/views/Configuration/DeployForm/index.js
- ui/src/app/settings/views/Configuration/DeployFormFields/DeployFormFields.js
- ui/src/app/settings/views/Configuration/DeployFormFields/DeployFormFields.test.js
- ui/src/app/settings/views/Configuration/DeployFormFields/index.js
Created the component for the configuration settings deploy form.
**Drive by**: 
- Moved the action dispatch for general config in the commissioning form from the `CommissioningForm` component to `Commissioning`.
- Fixed a bug with updating the second value in the commissioning form
- Go to `:5240/MAAS/#/images` and find the **Other images** section near the bottom of the page, select all available images and save
- Go to `:8000/MAAS/settings/configuration/deploy`
- Change the value of **Default operating system used for deployment** and see that the options for **Default OS release used for deployment** are updated
- Change values in both of the fields and save
- Refresh and see that those values persist
- Go to `:5240/MAAS/settings/general` and see that the form fields for the …
> Create settings deploy component

- ui/src/app/settings/components/Routes/Routes.js
Redirect `/settings` to `/settings/configuration/general` which is the first form in the settings navigation. Otherwise `/settings` just shows a blank page. Fixes #147 
Go to `/settings` and see that you are redirected to `/settings/configuration/general`
> Redirect settings base url to first form

- ui/src/app/settings/components/Routes/Routes.js
This reverts commit cf2dd5d63f92ade15a724769600f894840ceec49 because it introduced a bug that redirected every url under `/configuration`.
> Revert "Redirect settings base url to first form (#149)"

- ui/src/app/settings/components/Routes/Routes.js
Add a redirect from `/settings` to `/configuration` so that the user doesn't see a blank screen.
- Go to `/settings` and see that you are redirected to the first configuration section
- Click on all the other headings/links in the navigation and see that you are able to go to those pages
> Add redirect from settings to configuration. Fixes #147

- ui/package.json
- ui/src/app/base/proptypes.js
- ui/src/app/settings/selectors/users.js
- ui/src/app/settings/selectors/users.test.js
- ui/src/app/settings/views/Users/UsersList/UsersList.js
- ui/src/app/settings/views/Users/UsersList/UsersList.test.js
- ui/src/scss/_patterns_button.scss
- ui/src/scss/_patterns_table.scss
- ui/src/scss/base.scss
Done:
- Added toggle between username and full name. Fixes: https://github.com/canonical-web-and-design/maas-squad/issues/1404.
- Added missing user details.
QA:
- View the user list.
- You should see machine count, last login and type for users with those details.
- In the first column click on "Real name", you should see the real name for those users that have one.
> Toggle username

- .github/labeler.yml
- .github/workflows/label.yml
Theoretically this should add a "Maintenance 🔨" label to any PRs touching `package.json` or `yarn.lock`. No idea how we go about testing this 🤷‍♂ 
I guess we land this and retry Update dependency react-redux to v7.1.1?
> Add labeler action

- ui/package.json
- ui/src/app/settings/views/Configuration/GeneralForm/__snapshots__/GeneralForm.test.js.snap
- ui/src/app/settings/views/Images/ThirdPartyDriversForm/__snapshots__/ThirdPartyDriversForm.test.js.snap
- ui/src/app/settings/views/Images/VMWareForm/__snapshots__/VMWareForm.test.js.snap
- ui/src/app/settings/views/Images/WindowsForm/__snapshots__/WindowsForm.test.js.snap
- yarn.lock
Upgrade from react-redux 7.1.0 -> 7.1.1. Normally we would let renovate do this, but it broke some snapshots.
> Upgrade to react-redux 7.1.1 and update snapshots.

- ui/src/app/settings/actions/dhcpsnippet.js
- ui/src/app/settings/actions/dhcpsnippet.test.js
- ui/src/app/settings/actions/index.js
- ui/src/app/settings/actions/subnet.js
- ui/src/app/settings/actions/subnet.test.js
- ui/src/app/settings/components/Routes/Routes.js
- ui/src/app/settings/reducers/dhcpsnippet.js
- ui/src/app/settings/reducers/dhcpsnippet.test.js
- ui/src/app/settings/reducers/index.js
- ui/src/app/settings/reducers/subnet.js
- ui/src/app/settings/reducers/subnet.test.js
- ui/src/app/settings/selectors/dhcpsnippet.js
- ui/src/app/settings/selectors/dhcpsnippet.test.js
- ui/src/app/settings/selectors/index.js
- ui/src/app/settings/selectors/subnet.js
- ui/src/app/settings/selectors/subnet.test.js
- ui/src/app/settings/selectors/users.js
- ui/src/app/settings/views/Dhcp/Dhcp.js
- ui/src/app/settings/views/Dhcp/Dhcp.test.js
- ui/src/app/settings/views/Dhcp/DhcpList/DhcpList.js
- ui/src/app/settings/views/Dhcp/DhcpList/DhcpList.test.js
- ui/src/app/settings/views/Dhcp/DhcpList/__snapshots__/DhcpList.test.js.snap
- ui/src/app/settings/views/Dhcp/DhcpList/index.js
- ui/src/app/settings/views/Dhcp/__snapshots__/Dhcp.test.js.snap
- ui/src/app/settings/views/Dhcp/index.js
- ui/src/root-reducer.js
Done:
- Added actions, selectors and reducers for listing dhcp snippets and subnets. Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/73.
QA:
- Visit /settings/dhcp
- You should see a basic list of dhcp snippets and subnets (if they exist).
> Fetch dhcp snippets and subnets

- ui/src/app/base/actions/controller.js
- ui/src/app/base/actions/controller.test.js
- ui/src/app/base/actions/device.js
- ui/src/app/base/actions/device.test.js
- ui/src/app/base/actions/index.js
- ui/src/app/base/actions/machine.js
- ui/src/app/base/actions/machine.test.js
- ui/src/app/base/reducers/controller.js
- ui/src/app/base/reducers/controller.test.js
- ui/src/app/base/reducers/device.js
- ui/src/app/base/reducers/device.test.js
- ui/src/app/base/reducers/index.js
- ui/src/app/base/reducers/machine.js
- ui/src/app/base/reducers/machine.test.js
- ui/src/app/base/selectors/controller.js
- ui/src/app/base/selectors/controller.test.js
- ui/src/app/base/selectors/device.js
- ui/src/app/base/selectors/device.test.js
- ui/src/app/base/selectors/index.js
- ui/src/app/base/selectors/machine.js
- ui/src/app/base/selectors/machine.test.js
- ui/src/app/settings/views/Dhcp/DhcpList/DhcpList.js
- ui/src/app/settings/views/Dhcp/DhcpList/DhcpList.test.js
- ui/src/app/settings/views/Dhcp/DhcpList/__snapshots__/DhcpList.test.js.snap
- ui/src/root-reducer.js
Done:
- Implement actions, reducers and selectors for machines, controllers and devices. Fixes: #164.
QA:
- Visit /settings/dhcp.
- You should subnets, machines, controllers or devices in brackets after some items.
> Fetch machines, controllers and devices

- ui/src/app/settings/views/Configuration/Commissioning/Commissioning.js
- ui/src/app/settings/views/Configuration/Commissioning/Commissioning.test.js
- ui/src/app/settings/views/Configuration/Deploy/Deploy.js
- ui/src/app/settings/views/Configuration/Deploy/Deploy.test.js
- ui/src/app/settings/views/Configuration/General/General.js
- ui/src/app/settings/views/Configuration/General/General.test.js
- ui/src/app/settings/views/Configuration/KernelParameters/KernelParameters.js
- ui/src/app/settings/views/Configuration/KernelParameters/KernelParameters.test.js
- ui/src/app/settings/views/Images/ThirdPartyDrivers/ThirdPartyDrivers.js
- ui/src/app/settings/views/Images/VMWare/VMWare.js
- ui/src/app/settings/views/Images/VMWare/VMWare.test.js
- ui/src/app/settings/views/Images/Windows/Windows.js
- ui/src/app/settings/views/Images/Windows/Windows.test.js
- ui/src/app/settings/views/Network/DnsForm/DnsForm.js
- ui/src/app/settings/views/Network/DnsForm/DnsForm.test.js
- ui/src/app/settings/views/Network/NetworkDiscoveryForm/NetworkDiscoveryForm.js
- ui/src/app/settings/views/Network/NetworkDiscoveryForm/NetworkDiscoveryForm.test.js
- ui/src/app/settings/views/Network/NtpForm/NtpForm.js
- ui/src/app/settings/views/Network/NtpForm/NtpForm.test.js
- ui/src/app/settings/views/Network/ProxyForm/ProxyForm.js
- ui/src/app/settings/views/Network/ProxyForm/ProxyForm.test.js
- ui/src/app/settings/views/Network/SyslogForm/SyslogForm.js
- ui/src/app/settings/views/Network/SyslogForm/SyslogForm.test.js
- ui/src/app/settings/views/Storage/StorageForm/StorageForm.js
- ui/src/app/settings/views/Storage/StorageForm/StorageForm.test.js
- Explicitly fetch config in components that require it, if it hasn't already been loaded
- Load the app from users
- Navigate to a form that requires config (e.g. General)
- Check that the page actually loads.
> Explicitly fetch config in components that require it.

- ui/.env.development
- ui/README.md
- ui/package.json
- ui/src/app/Routes.js
- ui/src/app/base/sagas/http.js
- ui/src/app/base/sagas/http.test.js
- ui/src/app/base/sagas/index.js
- ui/src/app/settings/actions/index.js
- ui/src/app/settings/actions/scripts/index.js
- ui/src/app/settings/actions/scripts/scripts.js
- ui/src/app/settings/actions/scripts/scripts.test.js
- ui/src/app/settings/components/Nav/Nav.js
- ui/src/app/settings/components/Nav/__snapshots__/Nav.test.js.snap
- ui/src/app/settings/components/Routes/Routes.js
- ui/src/app/settings/reducers/index.js
- ui/src/app/settings/reducers/scripts/index.js
- ui/src/app/settings/reducers/scripts/scripts.js
- ui/src/app/settings/reducers/scripts/scripts.test.js
- ui/src/app/settings/selectors/scripts/index.js
- ui/src/app/settings/selectors/scripts/scripts.js
- ui/src/app/settings/selectors/scripts/scripts.test.js
- ui/src/app/settings/views/Scripts/Scripts.js
- ui/src/app/settings/views/Scripts/Scripts.test.js
- ui/src/app/settings/views/Scripts/__snapshots__/Scripts.test.js.snap
- ui/src/app/settings/views/Users/UserForm/UserForm.test.js
- ui/src/root-reducer.js
- ui/src/root-saga.js
- ui/src/setupProxy.js
* Configure [http-proxy-middleware](https://create-react-app.dev/docs/proxying-api-requests-in-development#configuring-the-proxy-manually) to work around CORS issues when running the dev server.
* Fetch scripts from http API.
* Add basic component, displaying lists of commissioning and testing scripts.
* Upload a commissioning script if you don't have one from old maas.
* Visit /MAAS/scripts/testing and /MAAS/scripts/commissioning - you should see a list of scripts.
* Confirm that scripts are in state.
* As this is using the http api, and we have no push updates, the Scripts component deliberately refetches and refreshes scripts on every load.
> Fetch scripts, add routes and basic component.

- ui/src/app/base/sagas/websockets.js
- ui/src/app/base/sagas/websockets.test.js
- ui/src/app/settings/views/Dhcp/DhcpList/DhcpList.js
Done:
- Updated the websocket saga to prevent rogue useSelector calls to prevent actions from being taken. This may not be the proper fix, but should get things working for now. See: https://github.com/canonical-web-and-design/maas-ui/issues/172. Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/177
QA:
- Open DhcpList.js and add `const blocking = useSelector(state => []);` somewhere near the top.
- Loading /dhcp should display the list of DHCP snippets.
> Use takeEvery to handle sending messages

- ui/package.json
- ui/src/websocket-client.js
- ui/src/websocket-client.test.js
- yarn.lock
* Use reconnecting-websocket with defaults.
* Use `mock-socket` in websocket-client tests as ReconnectingWebsocket requires a mock implementation closer to a real WebSocket. (Tests fail with "No valid WebSocket class provided" otherwise).
* Ensure the app still works (data is fetched, updated, deleted etc).
* Not strictly necessary, but if you'd like to see the library in action:
In websocket-client.js replace:
` this.socket = new ReconnectingWebSocket(websocket_url);`
with:
`this.socket = new ReconnectingWebSocket(websocket_url, [], {debug: true});`
Restart MAAS server, and watch the websocket disconnect, and then reconnect once it is back up.
> Use reconnecting-websocket.

- ui/src/app/base/components/Code/Code.js
- ui/src/app/base/components/Code/__snapshots__/Code.test.js.snap
Done:
- Add copy to clipboard to the Code component. Fixes: https://github.com/canonical-web-and-design/MAAS-squad/issues/1524.
QA:
- Run `./run exec --expose-port 6060 yarn docs`.
- Visit `[multipass]:6060/#/Code`.
- In the "Copyable" example click on the clipboard icon.
- Paste the contents of your clipboard somewhere, it should match the input.
> Add copy to clipboard to the Code component

- ui/src/app/settings/components/Routes/Routes.js
Add the exact property to the redirect in the network section so other views are reachable. Fixes #220
- Go to the settings section
- Click the **Network discovery** link in the side navigation
- See that you are able to get to that view
- Change the URL so you are only going to `/network`
- See that it still redirects to `/network/proxy`
> Fix redirect for network section of settings

- ui/src/app/preferences/actions/index.js
- ui/src/app/preferences/actions/sslkey/index.js
- ui/src/app/preferences/actions/sslkey/sslkey.js
- ui/src/app/preferences/actions/sslkey/sslkey.test.js
- ui/src/app/preferences/components/Routes/Routes.js
- ui/src/app/preferences/reducers/index.js
- ui/src/app/preferences/reducers/sslkey/index.js
- ui/src/app/preferences/reducers/sslkey/sslkey.js
- ui/src/app/preferences/reducers/sslkey/sslkey.test.js
- ui/src/app/preferences/selectors/index.js
- ui/src/app/preferences/selectors/sslkey/index.js
- ui/src/app/preferences/selectors/sslkey/sslkey.js
- ui/src/app/preferences/selectors/sslkey/sslkey.test.js
- ui/src/app/preferences/views/SSHKeyList/SSHKeyList.js
- ui/src/app/preferences/views/SSLKeyList/SSLKeyList.js
- ui/src/app/preferences/views/SSLKeyList/SSLKeyList.scss
- ui/src/app/preferences/views/SSLKeyList/SSLKeyList.test.js
- ui/src/app/preferences/views/SSLKeyList/index.js
- ui/src/root-reducer.js
Done:
- Fetch and list SSL keys. Fixes: https://github.com/canonical-web-and-design/MAAS-squad/issues/1535
QA:
- Add some SSL keys via the old preferences UI (you'll find some examples if you search "BEGIN CERTIFICATE" in the maas code).
- Visit /account/prefs/ssl-keys.
- You should see your keys.
Note: copying to clipboard has not yet been implemented.
> Display a list of SSL keys

- ui/src/app/base/actions/user/user.test.js
- ui/src/app/base/components/Textarea/Textarea.js
- ui/src/app/preferences/actions/sslkey/sslkey.js
- ui/src/app/preferences/actions/sslkey/sslkey.test.js
- ui/src/app/preferences/components/Routes/Routes.js
- ui/src/app/preferences/reducers/sslkey/sslkey.js
- ui/src/app/preferences/reducers/sslkey/sslkey.test.js
- ui/src/app/preferences/selectors/sslkey/sslkey.js
- ui/src/app/preferences/selectors/sslkey/sslkey.test.js
- ui/src/app/preferences/views/SSLKeys/AddSSLKey/AddSSLKey.js
- ui/src/app/preferences/views/SSLKeys/AddSSLKey/AddSSLKey.test.js
- ui/src/app/preferences/views/SSLKeys/AddSSLKey/index.js
- ui/src/app/preferences/views/SSLKeys/SSLKeyFormFields/SSLKeyFormFields.js
- ui/src/app/preferences/views/SSLKeys/SSLKeyFormFields/SSLKeyFormFields.test.js
- ui/src/app/preferences/views/SSLKeys/SSLKeyFormFields/index.js
- ui/src/app/preferences/views/SSLKeys/SSLKeyList/SSLKeyList.js
Done:
- Add a form for adding SSL keys. Fixes: https://github.com/canonical-web-and-design/maas-squad/issues/1508.
QA:
- Visit /account/prefs/ssl-keys.
- Click "Add SSL key".
- Paste a key (search MAAS for "-----BEGIN CERTIFICATE-----").
- Save and you should be redirected back to the list.
- Refresh and the key should be in the list (waiting on API support for sync: https://github.com/canonical-web-and-design/maas-ui/issues/238).
> Add SSL keys form

- ui/src/app/base/actions/scripts/scripts.js
- ui/src/app/base/actions/scripts/scripts.test.js
- ui/src/app/base/sagas/http.js
- ui/src/app/settings/views/Scripts/ScriptsUpload.js
- ui/src/app/settings/views/Scripts/ScriptsUpload.test.js
- ui/src/app/settings/views/Scripts/readScript.js
- ui/src/app/settings/views/Scripts/readScript.test.js
If a script is uploaded without any additional parameters, the server will in fact look for the presence of a metadata header, hence there's no need to parse the yaml clientside other than to check for the presence of the header.
Upload a script with a metadata header, e.g.
```script
#!/bin/bash
echo 'This script is amazing'.
```
Ensure the name and description are set appropriately.
Additionally, upload a normal script, without a metadata header, it should upload correctly as well.
> Allow server to parse metadata if header exists.

- ui/src/app/preferences/actions/sslkey/sslkey.js
- ui/src/app/preferences/actions/sslkey/sslkey.test.js
- ui/src/app/preferences/reducers/sslkey/sslkey.js
- ui/src/app/preferences/reducers/sslkey/sslkey.test.js
- ui/src/app/preferences/views/SSLKeys/SSLKeyList/SSLKeyList.js
- ui/src/app/preferences/views/SSLKeys/SSLKeyList/SSLKeyList.test.js
QA:
- Delete SSL keys from the list. Fixes: https://github.com/canonical-web-and-design/maas-squad/issues/1516.
QA:
- View the list of SSL keys in preferences.
- Click delete and confirm.
- Refresh and the key should be removed (bugs have been filed about API syncing support).
> Delete SSL keys

- ui/src/app/preferences/views/SSLKeys/SSLKeyFormFields/SSLKeyFormFields.js
- ui/src/app/preferences/views/SSLKeys/SSLKeyFormFields/SSLKeyFormFields.scss
Done:
- Update the SSL key field to fit the common formatted size of a SSL key. Fixes: https://github.com/canonical-web-and-design/maas-squad/issues/1567.
QA:
- Visit /account/prefs/ssl-keys/add.
- Paste a SSL key.
- It should fit nicely in the field (see: https://github.com/canonical-web-and-design/maas-squad/issues/1567).
> Fit SSL key field content

- ui/src/app/preferences/views/SSHKeys/SSHKeyList/SSHKeyList.js
- ui/src/app/preferences/views/SSHKeys/SSHKeyList/SSHKeyList.scss
- ui/src/app/preferences/views/SSHKeys/SSHKeyList/SSHKeyList.test.js
Done:
- Extend grouped SSH key borders to the edge of the row. Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/243.
QA:
- Visit /account/prefs/ssh-keys.
- Add an account with multiple keys (e.g. hatch on Launchpad).
- The borders for the group of keys should go past the delete icon.
> Extend SSH key borders

- ui/src/app/base/selectors/licensekeys/licensekeys.js
- ui/src/app/settings/views/LicenseKeys/LicenseKeyList/LicenseKeyList.js
- ui/src/app/settings/views/LicenseKeys/LicenseKeyList/LicenseKeyList.test.js
Display license keys in table
* Visit /settings/license-keys, ensure your license keys are displayed in the table.
* Ensure search works
> Display license keys in table, with search.

- ui/src/app/base/actions/licensekeys/licensekeys.js
- ui/src/app/base/actions/licensekeys/licensekeys.test.js
- ui/src/app/base/reducers/licensekeys/licensekeys.js
- ui/src/app/base/reducers/licensekeys/licensekeys.test.js
- ui/src/app/base/sagas/http.js
- ui/src/app/base/sagas/index.js
- ui/src/app/base/selectors/general/osInfo.js
- ui/src/app/base/selectors/general/osInfo.test.js
- ui/src/app/base/selectors/licensekeys/licensekeys.js
- ui/src/app/settings/components/Routes/Routes.js
- ui/src/app/settings/views/LicenseKeys/LicenseKeyAdd/LicenseKeyAdd.js
- ui/src/app/settings/views/LicenseKeys/LicenseKeyAdd/index.js
- ui/src/app/settings/views/LicenseKeys/LicenseKeyForm/LicenseKeyForm.js
- ui/src/app/settings/views/LicenseKeys/LicenseKeyForm/LicenseKeyForm.test.js
- ui/src/app/settings/views/LicenseKeys/LicenseKeyForm/index.js
- ui/src/app/settings/views/LicenseKeys/LicenseKeyFormFields/LicenseKeyFormFields.js
- ui/src/app/settings/views/LicenseKeys/LicenseKeyFormFields/LicenseKeyFormFields.test.js
- ui/src/app/settings/views/LicenseKeys/LicenseKeyFormFields/index.js
- ui/src/app/settings/views/LicenseKeys/LicenseKeyList/LicenseKeyList.js
- ui/src/app/settings/views/Scripts/ScriptsList.js
- ui/src/root-saga.js
Added form for creating license keys.
1. Ensure you have a fake windows image uploaded (if not see _Creating a fake windows image_).
2. Visit /MAAS/settings/license-keys in maas-ui, click the _add license key_ button, and create a new license key (windows license keys are in the form `XXXXX-XXXXX-XXXXX-XXXXX-XXXXX`.
3. The form should redirect you to the licence key list with a success message. You should see your new key.
1. Ensure you have an amd64 ubuntu image downloaded (via http://maas.local:5240/MAAS/#/images), this is required to populate architecture for the following steps.
2. Create a fake windows image with `dd if=/dev/zero of=windows-dd bs=512 count=10000`
3. Upload the image you've created with `maas {profile} boot-resources create name=windows/win2012 title="Windows Server …
> Add create license key form

- ui/src/app/base/components/FormCard/FormCard.js
- ui/src/app/base/components/FormCard/FormCard.test.js
- ui/src/app/settings/views/Scripts/ScriptsUpload.js
Done:
- Add an option to stack form card headings. Fixes: #210.
QA:
- View /settings/scripts/testing/upload, the heading should be above the drop area.
- View /settings/users/add, the heading should be to the left.
> Stack form card heading

- ui/src/app/preferences/reducers/sslkey/sslkey.js
- ui/src/app/preferences/reducers/sslkey/sslkey.test.js
Done:
- Sync update messages for SSL keys. Fixes: #238.
QA:
- Update your MAAS to the latest master (you might need to syncdb etc.)
- View the SSL keys in your preferences.
- Add a SSL key, the list should update.
- Remove a SSL key, the list should update.
> Sync SSL Keys

- ui/src/app/base/actions/licensekeys/licensekeys.js
- ui/src/app/base/actions/licensekeys/licensekeys.test.js
- ui/src/app/base/reducers/licensekeys/licensekeys.js
- ui/src/app/base/reducers/licensekeys/licensekeys.test.js
- ui/src/app/base/sagas/http.js
- ui/src/app/base/sagas/http.test.js
- ui/src/app/base/sagas/index.js
- ui/src/app/base/selectors/licensekeys/licensekeys.js
- ui/src/app/settings/components/Routes/Routes.js
- ui/src/app/settings/views/LicenseKeys/LicenseKeyEdit/LicenseKeyEdit.js
- ui/src/app/settings/views/LicenseKeys/LicenseKeyEdit/LicenseKeyEdit.test.js
- ui/src/app/settings/views/LicenseKeys/LicenseKeyEdit/index.js
- ui/src/app/settings/views/LicenseKeys/LicenseKeyForm/LicenseKeyForm.js
- ui/src/app/settings/views/LicenseKeys/LicenseKeyForm/LicenseKeyForm.test.js
- ui/src/app/settings/views/LicenseKeys/LicenseKeyFormFields/LicenseKeyFormFields.js
- ui/src/app/settings/views/LicenseKeys/LicenseKeyList/LicenseKeyList.js
- ui/src/root-saga.js
Added form for editing/updating license keys.
1. Ensure you have a fake windows image uploaded (if not see _Creating a fake windows image_).
2. Visit /MAAS/settings/license-keys in maas-ui, click the _add license key_ button, and create a new license key (windows license keys are in the form `XXXXX-XXXXX-XXXXX-XXXXX-XXXXX`).
3. Return to the license key list, click the edit button next to your key.
4. Ensure the edit license key form displays the correct key data. 
5. Edit your key, and click "update license key".
6. The form should redirect you to the licence key list with a success message.
7. Edit your key again, and ensure the new key is reflected in the form.
1. Ensure you have an amd64 ubuntu image downloaded (via http://maas.local:5240/MAAS/#/images), this is required to populate …
> Add license key editing form.

- ui/src/app/settings/views/Configuration/CommissioningFormFields/CommissioningFormFields.js
- Fix bug where changing Ubuntu kernel options while image was downloading would crash the app.
- Start downloading an Ubuntu image.
- Go to `<MAAS-IP>:8000/MAAS/r/settings/configuration/commissioning`
- Check that clicking open the kernel select and selecting any option does not crash the app.
- Wait until the image has finished downloading, and check that the kernel select now has the options for that release.
Fixes #150
> Fix bug where changing Ubuntu kernel options while image was downloading would crash the app.

- ui/src/app/App.js
- ui/src/app/App.test.js
- ui/src/app/settings/views/Settings.js
- ui/src/app/settings/views/Settings.test.js
- Allow non-admins to view everything but settings. Fixes: https://github.com/canonical-web-and-design/maas-squad/issues/1536.
QA:
- Log in as an admin, you should be able to see settings, machines and preferences.
- Log in as a non-admin, you should be able to see machines and preferences but not settings.
> Only restrict settings to admins

- legacy/src/app/controllers/node_details.js
- legacy/src/app/controllers/node_details_networking.js
- legacy/src/app/controllers/node_details_storage.js
- legacy/src/app/controllers/tests/test_node_details.js
- legacy/src/app/controllers/tests/test_node_details_networking.js
- legacy/src/app/directives/pod-details/summary.js
- legacy/src/app/directives/power_parameters.js
- legacy/src/app/directives/script_select.js
- legacy/src/app/entry.js
- legacy/src/app/factories/tests/test_zones.js
- legacy/src/app/partials/add-scripts.html
- legacy/src/app/partials/cards/machine-overview.html
- legacy/src/app/partials/cards/network.html
- legacy/src/app/partials/node-details.html
- legacy/src/app/partials/nodedetails/node-details-summary.html
- legacy/src/app/partials/nodedetails/storage/disks-partitions.html
- legacy/src/app/partials/pod-details.html
- legacy/src/scss/_patterns_button.scss
- legacy/src/scss/tables/_patterns_table-controllers.scss
- Added new changes in launchpad master branch, up to `dc3fd1c40 Show interface members (read-only) in the Network table.` ([Commit in lp](https://git.launchpad.net/maas/commit/?id=dc3fd1c4091e2eda057bd1d9997551e9f052efee))
- Drive-by fixes:
- Machine summary cards get parent classes correctly
- Pod details template loaded correctly
- Check that the machine details pages looks like the current launchpad master (summary, network, storage tabs)
- Check that the pod details summary loads in correctly
- Really the only changes that haven't already been merged in master and need code review are in:
- `legacy/src/app/entry.js`
- `legacy/src/app/directives/pod-details/summary.js`
- `legacy/src/app/partials/pod-details.html`
- `legacy/src/app/partials/nodedetails/node-details-summary.html`
> Sync legacy js files to latest launchpad master branch.

- legacy/src/app/directives/version_reloader.js
- legacy/src/app/entry.js
- legacy/src/app/testing/setup.js
- legacy/src/index.html
Add `SITE_NAME` config value.
Load the app and open the console, the version reloader text (e.g. `Version reloader: Monitoring MAAS "kakariki" version 2.7.0 (8101-g.b3b43022d)`) should reflect your MAAS name.
> Add SITE_NAME config.

- legacy/package.json
- legacy/src/index.html
- legacy/src/scss/_settings.scss
- legacy/webpack.config.js
- yarn.lock
* Add CopyWebpackPlugin to ensure static assets are served correctly by webpack-dev-server, and output correctly to `./dist` on build.
* Correct `build.css` path.
* Run the app, fonts and images should no longer 404.
* run `yarn build`, assets should be output correctly to `./dist`.
> Add CopyWebpackPlugin and serve assets correctly in dev.

- README.md
The setup instructions of this app have been moved to the main README
and whilst the doc no longer exists, the link to it remains in the
README. This PR removes that link to avoid confusion for future
developers.
> Remove dead link to UI setup instructions.

- README.md
The app now runs on port 8400 and also has no redirect to it's root URL
but the instructions in the README don't reflect this. This PR updates
the instructions in the README.
> Update setup info

- ui/src/scss/base.scss
The background colour doesn't extend beyond 100vh so when the content
exceeds that height the background changes from grey to white. By
changing the height to min-height this issue is mitigated. Fixes #331 
Go to the settings section and pick a tab with content that exceeds the height of the page. See that as you scroll beyond the viewport that the grey background extends to the bottom of the page.
> Change root element height to min height

- legacy/package.json
- legacy/src/app/partials/directives/script-runtime.html
- legacy/webpack.config.js
* Configure production build with html, css and js optimisation and hashed assets.
* Configured html-loader to ignore angularjs template tags (e.g. `{$ foo $}` and `{{ bar }}`).
* Fixed a template bug in _script-runtime.html_ which was breaking the minification parser.
* Run `yarn clean-build`
* Run `yarn build`, ensure assets are correctly output to `./dist` and minified.
> Configure production build

- legacy/src/app/entry.js
- legacy/src/app/routes.js
- legacy/src/app/testing/setup.js
Add `CURRENT_USER` config var from the `/users` API.
Ensure /dashboard is accessible to superusers, but not regular users.
Ensure a new regular user gets redirected to intro/user
> Add config from USERS API.

- ui/src/app/settings/views/Network/DnsForm/DnsForm.js
- ui/src/app/settings/views/Network/SyslogForm/SyslogForm.js
@Caleb-Ellis I wasn't able to find a console error on the Network Discovery form unfortunately, are you still able to replicate that?
Add empty string defaults for initial values
Visit DnsForm/SyslogForm/NetworkDisoverForm and ensure there are no console errors.
> Add initial values when undefined for DnsForm and SyslogForm.

- legacy/src/app/bootstrap.js
- legacy/src/app/entry.js
- shared/src/components/Header/Header.js
* Persist config to localStorage after fetching from websocket.
* On load, if config is available from localStorage, fetch from there rather than over network.
* Clear config from localStorage on logout.
1. Load app, config should be persisted to localStorage.
2. Refresh app, config should be loaded from localStorage (you can confirm this by checking that no websocket messages are sent with method `config.list`).
3. Logout, config should be removed from localStorage.
> Use localStorage for persisting config.

- legacy/src/app/entry.js
- legacy/src/index.html
Done:
- Display the maas name in the window title for the legacy app. Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/348.
QA:
- Load a legacy page. The window title should include the maas name (e.g. Machines | [maas name] MAAS).
> MAAS name in window title

- ui/src/app/base/components/ActionButton/ActionButton.js
- Updated ActionButton so that it explicitly sets width *and* height when transitioning to loading, instead of just width on mount. This means that if for some reason the content of the button changes it will actually be the correct height/width as according to Vanilla and will only store the dimensions for the loading => success phase.
- Go to any Settings form, make changes and save. Check that the button dimensions stay consistent.
- Open the inspector and change the button text to something else. Save again and check that the dimensions are consistent.
> Set ActionButton dimensions on loading state transition.

- legacy/.gitignore
- legacy/package.json
- legacy/webpack.config.js
CRA (and hence `ui`) outputs to `./build` by default. To make the projects consistent, we should also build to `./build` in legacy instead of `./dist`.
`cd legacy;yarn build` - production build should output to `./build`.
> Use 'build' instead of 'dist' for legacy build dir for consistency.

- README.md
Added a link to the downloadable Docker client for Mac.
> Update README with Docker on Mac instruction

- legacy/src/app/bootstrap.js
- legacy/src/app/entry.js
- shared/src/components/Header/Header.js
- shared/src/components/Header/Header.test.js
- ui/src/app/App.js
- ui/src/app/settings/selectors/config/config.js
- ui/src/app/settings/selectors/config/config.test.js
- yarn.lock
Done:
- Display the intro skip link in the header. Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/362.
QA:
- Log out of the UI.
- With a local maas, ssh into your maas mulitpass and cd to the maas dir.
- Run `make harness`
- Then inside the shell run:
```python
from maasserver.models import Config, UserProfile
Config.objects.filter(name='completed_intro').update(value=False)
UserProfile.objects.all().update(completed_intro=False)
```
- Reload the ui and log in.
- You should see the intro.
- Click Skip in the header and you should be taken to the second screen.
- Click Skip again and you should see the machine list.
> Add intro skip

- legacy/src/app/entry.js
- ui/src/app/App.js
Guard against a potential race when bootstrapping where `authUser` and `current_user` are undefined.
> Guard against race on bootstrap where no user present.

- legacy/src/app/partials/ipranges.html
Update the docs link for IP ranges in the subnets detail page. Fixes #1635.
- Go to a subnets detail page
- Click the `About IP ranges` link
- See that you are taken to https://maas.io/docs/ip-ranges in a new tab
> Fix broken link in subnets detail page

- legacy/src/app/directives/nodedetails/storage_disks_partitions.js
- legacy/src/app/partials/nodedetails/storage/disks-partitions.html
Add the correct `href` value for the storage settings link in the storage tab of a machine details page. Fixes #389.
- Go to the storage tab on a machine details page
- Click the `Change the default layout in Settings › Storage` link
- See that you are taken to `/MAAS/r/settings/storage`
> Fix broken link to settings in storage tab

- legacy/src/app/directives/dhcp_snippets_table.js
- legacy/src/app/partials/dhcp-snippets-table.html
Add correct `href` values for the links to DHCP snippet settings and DHCP snippets docs on the network tab of a machine detail page. Fixes #396 and #392.
- Go to `/MAAS/#/machines`
- Go to the detail page of a machine that has DHCP snippets (on Karura `actual-swine.maas` qualifies)
- Go to the network tab of the machine
- Click the `About DHCP snippets` link and see that you are taken to https://maas.io/docs/dhcp in a new tab
- Click the `All snippets: Settings > DHCP snippets` link and see that you are taken to  `/MAAS/r/settings/dhcp`
> Fix broken links in network tab

- ui/src/app/settings/components/SettingsTable/SettingsTable.js
- ui/src/app/settings/components/SettingsTable/SettingsTable.test.js
- ui/src/app/settings/views/LicenseKeys/LicenseKeyList/LicenseKeyList.js
- ui/src/app/settings/views/LicenseKeys/LicenseKeyList/LicenseKeyList.test.js
Disable "Add License key" button if no valid licensed operating systems are synced.
* Delete any licensed images should you have one (e.g. a fake Windows server image)
* Visit the license key page in settings. The add button should be disabled and display a tooltip.
fixes #397
> Disable Add License key button if no valid OSes.

- legacy/src/app/bootstrap.js
- legacy/src/app/controllers/nodes_list.js
- legacy/src/app/controllers/tests/test_nodes_list.js
Done:
- Add config for controller registration. Fixes: https://github.com/canonical-web-and-design/MAAS-squad/issues/1618.
QA:
- Log out and back in.
- Visit /MAAS/#/controllers
- Click "Add rack controller"
- Check that the instructions contain a url and secret e.g. `sudo maas-rack register --url http://192.168.1.14:5240/MAAS --secret 96449773da9d65df0f926e4c1068799b`
> Add remaining config

- ui/package.json
Done:
- Disable the sourcemaps for the production CRA build. Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/423
Sizes go from:
3.7M	build/ui
To:
904K	build/ui
QA:
- `yarn build-all`
- There should be no sourcemaps inside build/ui/...
> Disable CRA sourcemaps

- legacy/src/app/bootstrap.js
- legacy/src/app/entry.js
- shared/src/components/Header/Header.js
- shared/src/components/Header/__snapshots__/Header.test.js.snap
- ui/src/app/App.js
- ui/src/app/App.test.js
Done:
- Only display the RSD tab when enabled. Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/382.
QA:
- Run the UI, you probably won't have the RSD option in your header.
- Fake the showRSD option in App.js or entry.js (unless you have a MAAS with RSD).
> Show or hide RSD nav

- legacy/src/scss/tables/_patterns_table-machines.scss
Done:
- Remove hover shadow from machines table. Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/398.
QA:
- View the list of machines (you may need to update your MAAS).
- Hover over a machine, you should see white background, but no shadow.
> Remove machine shadow

- ui/src/app/base/components/SideNav/SideNav.scss
Done:
- Correct left spacing of the side nav. Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/395. Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/391.
QA
- Load the settings.
- Check that the left nav is directly below the Settings title.
- Reduce the size of the screen, the left nav should never overlap the main content.
> Fix side nav spacing

- ui/src/app/base/components/ColumnToggle/ColumnToggle.scss
- ui/src/scss/_vanilla-overrides.scss
Done:
- Update the column toggles to use the new chevron. Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/400.
- Override the table sort to use the new chevron. Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/390.
QA:
- View the scripts list in settings.
- Check that the toggle row chevrons look like:
- Sort the table by clicking on a header label, the sort chevron should be the same.
> Use the new chevron icon

- ui/src/app/settings/views/Scripts/ScriptsList.js
- ui/src/scss/_patterns_table.scss
Done:
- Align the spacing inside expanding rows with the Vanilla pattern. Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/401.
QA:
- View the scripts list in settings and expand a script
- The code block should not have extra space around it, as seen in: https://github.com/canonical-web-and-design/maas-ui/issues/401.
> Remove extra spacing inside expanding rows

- ui/src/app/base/components/ColumnToggle/ColumnToggle.js
- ui/src/app/base/components/ColumnToggle/ColumnToggle.test.js
Done:
- When a row is toggled open then scroll it into view if it collapses a section above it. Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/402.
QA:
- Open the settings scripts section (you need to have some scripts).
- Open a really long script.
- Scroll down and toggle open a script.
- You should get scrolled to the top of that script.
> Scroll a section into view when toggled

- legacy/src/app/entry.js
Done:
- Check that the navigation_options are available before use. Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/447.
QA:
- Load the ui.
- It should fully load and there should not be a console error: `Cannot read property 'rsd' of undefined`.
> Fix rsd config loading

- ui/public/index.html
Add the viewport meta tag so the app responds to the viewport width of mobile browsers rather than defaulting to the desktop view. Fixes: #451.
- Go to any page of the app
- Open the browser developer tools and [emulate a mobile device](https://developers.google.com/web/tools/chrome-devtools/device-mode)
- See that the mobile view is displayed
> Add viewport meta tag

- legacy/src/app/partials/nodes-list.html
Fix the syntax error that was causing a console error every time the group by filter in the machines listing page was used. Fixes: #458.
- On the machines listing page open your browsers dev tools and look at the console
- Use the group by filter and see that there are no related console errors
> Fix console error when using the group by filter

- legacy/src/app/directives/maas_obj_form.js
Added a check for the fields key in the MAAS form directive which was causing an error to be shown in the console. Fixes: #457
- Go to the resource pools tab on the machines listing page
- Open your browser dev tools and make sure the console is visible
- Try editing the pools in the list and see that no error is thrown and displayed in the browser console
> Fix console error when editing resource pool

- legacy/src/app/partials/nodes-list.html
Conditionally render the sibling button to add pool rather than show/hide it to remove the extra right margin. Fixes: #467.
- Go to the resources tab on the machines listing page
- See that the "Add pool" button is aligned to the right of the container
> Fix alignment of add pool button

- legacy/src/scss/_patterns_button.scss
Overridden Vanilla button styles for button links which are in both active and hover states to remove the grey background. Fixes #462.
- Go to the machine summary page
- Click on one of the test links e.g. "Test CPU..."
- See that as you click the background remains the same colour
> Fix button link active state colour

- legacy/src/scss/_patterns_tag-input.scss
Remove default list styles from autocomplete list. Fixes #381
- On the machine list page select all the machines
- Select all machines that can be tagged (tip: select all machines, select tag from the take action menu and update your selection)
- When entering tags into the tag input see that the suggestion list doesn't have the default bulleted list style
> Fix styles for autocomplete list

- legacy/src/app/controllers/add_hardware.js
- legacy/src/app/controllers/tests/test_add_hardware.js
- legacy/src/app/directives/power_parameters.js
- legacy/src/app/partials/nodelist/add-machine.html
- Show required asterisks in "Add machine" dropdown
- Disable save button if one of the required fields is missing
- Add a machine from the machine list
- Check that MAC address is required
- Change the power type and check that required fields show up correctly
- Check the submit button is disabled if some of the required fields are not filled in
Fixes #454
> Display required indicators when adding machine from machine list.

- legacy/src/app/partials/nodelist/add-machine.html
- Explicitly give "Add MAC Address" button an attribute of `type="button"` so it doesn't submit the form on click.
- Open Add Machine dropdown.
- Choose a power type that has some required fields.
- Add another MAC address and see that a browser tooltip doesn't appear below the first required power parameter.
> Stop Add MAC button submitting form prematurely in Add Machine form.

- ui/src/app/base/components/FormikFormButtons/FormikFormButtons.js
- ui/src/app/base/components/FormikFormButtons/__snapshots__/FormikFormButtons.test.js.snap
- ui/src/app/base/components/FormikFormContent/FormikFormContent.js
- ui/src/app/settings/views/Network/ProxyFormFields/ProxyFormFields.js
- ui/src/scss/_vanilla-overrides.scss
- Wrap form fields in a parent div, so the resultant markup of a FormikForm becomes:
``` html
<form>
<div>
...form fields...
</div>
<div>
...buttons...
</div>
</form>
```
This makes it possible to apply `:last-of-type` to the last form field in which to apply `margin-bottom`.
Fixes #464, fixes #465
> Fix form button spacing Vanilla override.

- ui/src/app/base/components/UserForm/UserForm.js
- ui/src/app/base/components/UserForm/UserForm.test.js
- Call Formik resetForm after UserPreferences form submit
- Go to user prefs page
- Change username and check that the nav updates, a notification appears, and the button becomes disabled whenever the text input matches the current username
Fixes #474
> Reset user preference form values on submit.

- ui/src/app/base/components/UserForm/UserForm.js
- ui/src/scss/_vanilla-overrides.scss
Wrap the change password link in a `p-form__group` to give the correct margin between it and the button. Fixes #480.
https://usercontent.irccloud-cdn.com/file/dVj4bw93/user_form.png
- Go to the user preferences page
- See that the gap between "Change password" and the "Save" button matches the screenshot
> Fix change password link spacing

- legacy/src/app/partials/node-details.html
- legacy/src/scss/_patterns_icons.scss
Add icon for disconnected state and replace instances of error icon with disconnected icon when interface is disconnected.
- Go to the network tab
- If no interfaces are disconnected mark one as disconnected
- You should see the new disconnected icon instead of a white cross inside a red circle
> Add disconnected icon

- ui/src/app/base/enum.js
- ui/src/app/machines/views/MachineList/MachineList.js
- ui/src/app/machines/views/MachineList/MachineList.scss
- ui/src/app/machines/views/MachineList/MachineList.test.js
Done:
- Group machines on the machine list by the selected sort. Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/485.
QA:
- View a MAAS with lots of machines (or import some json e.g. https://github.com/huwshimi/maas-ui/blob/99bc5a61170fc377dfa578f5ab7a503b72a0fa90/ui/src/app/settings/views/Machines/MachineList/data.json)
- Click on the different table headers to sort the list.
- The machines should be grouped by the selected sort (or have no grouping for 'name').
> Group machines when sorting

- ui/src/app/machines/views/MachineList/MachineList.js
- ui/src/app/machines/views/MachineList/MachineList.scss
- ui/src/app/machines/views/MachineList/MachineList.test.js
Done:
- Allow hiding of machine groups. Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/491.
QA:
- View /MAAS/r/machines.
- Click the "-" in a group header, it should hide the machines for that group.
- Click the "+" that group should appear again.
> Add machines accordion

- ui/package.json
- ui/src/app/machines/views/MachineList/MachineList.js
- yarn.lock
Pluralise machine counts in the machines table e.g. "1 machine" instead of "1 machines". Fixes #479.
- Go to the machines listing
- See that each group that has multiple machines has a pluralised count e.g. "5 machines"
- See that each group that has only one machine has a singular count e.g. "1 machine"
> Pluralise machine counts in machines table

- legacy/src/app/controllers/node_details.js
- legacy/src/app/controllers/tests/test_node_details.js
In relation to: https://bugs.launchpad.net/maas/+bug/1853568
Added the `script_input` parameter to the data sent when commissioning a machine and running the `internet-connectivity` test script
The simplest way to see this works is to `console.log` the `params` parameter in `callMethod` in the `region.js` file from the legacy app.
- Go to a machine in "New" or "Ready" state
- Select "Commission" from the "Take action" menu
- Select the `internet-connectivity` script
- Commission the machine and see the output in the browser console has a `extra.script_input` property e.g. https://pastebin.canonical.com/p/YNst3xs3Vz/
> Send script_input when commissioning machines

- ui/src/app/App.test.js
- ui/src/app/base/components/UserForm/UserForm.js
- ui/src/app/base/components/UserForm/UserForm.test.js
- ui/src/app/base/proptypes.js
- ui/src/app/base/selectors/user/user.js
- ui/src/app/base/selectors/user/user.test.js
- ui/src/app/preferences/views/Details/Details.test.js
- ui/src/app/settings/views/Users/UserEdit/UserEdit.test.js
- ui/src/app/settings/views/Users/UserForm/UserForm.test.js
- ui/src/app/settings/views/Users/UsersList/UsersList.js
- ui/src/app/settings/views/Users/UsersList/UsersList.test.js
- Removed references to `first_name` param from ui code. As of [this MP](https://code.launchpad.net/~blake-rouse/maas/+git/maas/+merge/375892), `first_name` will no longer be sent through the websocket, so a user's full name is essentially just the `last_name`.
- Go to user prefs and check that the first and last name saves correctly.
- Do the same with add and editing users from the user list in settings.
- Verify in Redux state the only `last_name` is getting updated.
Fixes #476
> Remove instances of first_name param in user objects.

- ui/package.json
- ui/src/app/base/components/Tooltip/Tooltip.js
- ui/src/app/base/components/Tooltip/Tooltip.test.js
- ui/src/app/base/components/Tooltip/__snapshots__/Tooltip.test.js.snap
- ui/src/app/base/components/Tooltip/index.js
- ui/src/app/preferences/views/SSHKeys/SSHKeyFormFields/SSHKeyFormFields.js
- ui/src/app/settings/components/SettingsTable/SettingsTable.js
- ui/src/app/settings/components/SettingsTable/SettingsTable.test.js
- ui/src/app/settings/views/Dhcp/DhcpList/DhcpList.js
- ui/src/app/settings/views/Repositories/RepositoriesList/RepositoriesList.js
- ui/src/app/settings/views/Scripts/ScriptsList.js
- ui/src/app/settings/views/Users/UsersList/UsersList.js
- ui/src/scss/_vanilla-overrides.scss
- yarn.lock
- Added a Tooltip component and replaced all instances of `<span className="p-tooltip">` with it.
- Note there's a weird issue where the tooltip doesn't show when hovering over the *padding* of a disabled button, but it works when hovering over the text/icon. I know it has something to do with disabled buttons disabling all events... but why only the padding?!?
- Check tooltips still work
- /settings/users delete self
- /settings/license-keys button
- /settings/scripts/testing
- /settings/repositories
- /account/prefs/ssh-keys/add SSH upload
Fixes #497
> Add Tooltip component.

- shared/src/components/Footer/Footer.js
- shared/src/components/Footer/__snapshots__/Footer.test.js.snap
Done:
* Point to maas.io/docs not docs.ubuntu.com
* Point release notes at where they'll be
QA:
* Click the docs link in the footer and see that you don't end up bouncing around from ubuntu.com
> Fix doc and release notes links in Footer

- legacy/src/scss/_patterns_navigation.scss
- shared/src/components/Header/Header.js
- shared/src/components/Header/Header.test.js
- shared/src/components/Header/__snapshots__/Header.test.js.snap
- ui/src/app/base/components/ColumnToggle/ColumnToggle.scss
- ui/src/app/base/components/FormCard/FormCard.js
- ui/src/app/base/components/FormCard/FormCard.scss
- ui/src/app/base/components/FormCard/__snapshots__/FormCard.test.js.snap
- ui/src/app/base/components/Section/Section.js
- ui/src/app/base/components/Section/Section.scss
- ui/src/app/base/components/Section/__snapshots__/Section.test.js.snap
- ui/src/app/machines/views/MachineList/MachineList.scss
- ui/src/app/preferences/views/SSLKeys/AddSSLKey/AddSSLKey.scss
- ui/src/scss/_patterns_navigation.scss
- ui/src/scss/_patterns_table-actions.scss
- ui/src/scss/base.scss
- Adopted Vanilla subnav in `Header` component, and added some simple MAAS-specific utilities to show/hide it. Note that because the Vanilla versions are different, there are subtle differences in the Angular and React headers, particularly on mobile view.
- Rewrote sections of the `Header` component to work with the different markup structure of the Vanilla subnav - now internal functions are generally a bit smaller and more modular, e.g. `generateLink()` only ever returns an `<a>` and never an `<li>`, the hardware menu is generated separate to the rest of the links, etc.
- Removed all instances of hardcoded scss values with Vanilla variables (except in the vanilla-overrides file - these should be short-lived anyway).
- Trimmed custom scss.
- In both the React and Angular parts of the …
> Rewrite Header component to utilise Vanilla subnav and remove hardcoded values.

- ui/src/app/base/components/UserForm/UserForm.js
- ui/src/app/base/components/UserForm/UserForm.test.js
- ui/src/app/preferences/views/Details/Details.js
- ui/src/app/preferences/views/Details/Details.test.js
- ui/src/app/settings/components/Routes/Routes.js
- ui/src/app/settings/views/Settings.test.js
- ui/src/app/settings/views/Users/UserEdit/UserEdit.test.js
- ui/src/app/settings/views/Users/UserForm/UserForm.test.js
- ui/src/app/settings/views/Users/UsersList/UsersList.js
- ui/src/app/settings/views/Users/UsersList/UsersList.test.js
Done:
- Disable user modification when using rbac. Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/516.
QA:
- Set up a maas with rbac.
- View the list of users, you should see a message about external auth.
- View your profile details. The form should be disabled.
> Disable modifying users when using external auth

- ui/package.json
- yarn.lock
* Downgrade to CRA 3.2.0 to fix development websocket proxying issue.
* Start the app, it should load immediately.
https://github.com/facebook/create-react-app/issues/8094
> Downgrade to CRA 3.2.0

- legacy/src/app/entry.js
- shared/package.json
- shared/src/components/Footer/Footer.js
- shared/src/components/Footer/Footer.test.js
- shared/src/components/Footer/__snapshots__/Footer.test.js.snap
- ui/src/app/App.js
- Correctly inject the Usabilla script. Fixes: https://github.com/canonical-web-and-design/maas-squad/issues/1718
- View the React app and click "Give feedback" in the footer, it should display the feedback form.
- Do the same for the Angular UI.
> Correctly include the Usabilla script

- legacy/src/app/directives/machines_table.js
Persist "show all" for ungrouped machines.
* Visit /machines
* Select "No grouping"
* Click "Show all machines..."
* Select a machine that was hidden initially
* The machine list should no longer return to the default limit of 5 machines.
Fixes #564.
> Persist show all for all machines when ungrouped.

- ui/src/analytics.js
- ui/src/app/base/components/FormikForm/FormikForm.js
- ui/src/app/base/components/FormikForm/FormikForm.test.js
- ui/src/app/base/components/UserForm/UserForm.js
- ui/src/app/base/hooks.js
- ui/src/app/preferences/views/APIKeys/APIKeyForm/APIKeyForm.js
- ui/src/app/preferences/views/Details/Details.js
- ui/src/app/preferences/views/Details/Details.test.js
- ui/src/app/preferences/views/SSHKeys/AddSSHKey/AddSSHKey.js
- ui/src/app/preferences/views/SSLKeys/AddSSLKey/AddSSLKey.js
- ui/src/app/settings/views/Configuration/CommissioningForm/CommissioningForm.js
- ui/src/app/settings/views/Configuration/DeployForm/DeployForm.js
- ui/src/app/settings/views/Configuration/GeneralForm/GeneralForm.js
- ui/src/app/settings/views/Configuration/KernelParametersForm/KernelParametersForm.js
- ui/src/app/settings/views/Dhcp/DhcpForm/DhcpForm.js
- ui/src/app/settings/views/Images/ThirdPartyDriversForm/ThirdPartyDriversForm.js
- ui/src/app/settings/views/Images/VMWareForm/VMWareForm.js
- ui/src/app/settings/views/Images/WindowsForm/WindowsForm.js
- ui/src/app/settings/views/LicenseKeys/LicenseKeyForm/LicenseKeyForm.js
- ui/src/app/settings/views/Network/DnsForm/DnsForm.js
- ui/src/app/settings/views/Network/NetworkDiscoveryForm/NetworkDiscoveryForm.js
- ui/src/app/settings/views/Network/NtpForm/NtpForm.js
- ui/src/app/settings/views/Network/ProxyForm/ProxyForm.js
- ui/src/app/settings/views/Network/SyslogForm/SyslogForm.js
- ui/src/app/settings/views/Repositories/RepositoryForm/RepositoryForm.js
- ui/src/app/settings/views/Storage/StorageForm/StorageForm.js
- ui/src/app/settings/views/Users/UserForm/UserForm.js
- Send events when forms are saved in settings and preferences.
- Send an event when the GA checkbox is changed.
- This one's a bit tricky to QA, you could add something like: `console.log("send event", eventCategory, eventAction, eventLabel);` in analytics.js and then check that you get events when saving forms and changing whether GA is checked in the General settings.
Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/566.
> Send analytics events when forms are saved.

- ui/package.json
- ui/src/app/base/components/FormikField/FormikField.js
- ui/src/setupTests.js
- yarn.lock
Replace `uuid/v4` with `nanoid` for a modest bundle size saving (~3x smaller).
* Inspect some form elements, they should have unique ids.
Fixes #527
> Replace uuid with nanoid for generated form element ids.

- ui/src/app/base/components/UserForm/UserForm.js
- Correctly validate that passwords match in user forms. Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/579.
- Open the user list and click 'Add user'.
- Enter different passowords in the two password fields.
- You should see an error about passwords needing to match.
> Fix validation that passwords are the same

- ui/src/app/base/components/ColumnToggle/ColumnToggle.scss
- Make the chevron appear in the row toggle. Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/581.
- View testing scripts in settings.
- The script name column cells should show chevrons.
> Fix the display of the chevron

- ui/src/app/base/components/TableDeleteConfirm/TableDeleteConfirm.js
- ui/src/app/base/components/TableDeleteConfirm/__snapshots__/TableDeleteConfirm.test.js.snap
- Fix the spacing in table delete confirmations. Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/582.
- Upen a list in settings e.g. users
- Click delete on a row.
- The buttons and text should be centred vertically.
> Fix spacing in table delete confirmations

- legacy/src/app/partials/node-details.html
- legacy/src/app/partials/nodes-list.html
- Fixed install KVM checkbox in Deploy dropdown not working correctly. I think it was missed in one of the migrations from launchpad to github.
- In the machine list, open the Deploy action dropdown and check that the checkbox is disabled for all OSes that aren't 18.04 or 20.04.
- Check that the form actually sends the information to MAAS (add `console.log(extra)` to `legacy/src/app/factories/nodes.js` L32).
- Do the same on the machine details page.
Fixes #599.
lp#1856772.
> LP: #1856772 - Fix install KVM checkbox.

- legacy/src/app/controllers/node_details.js
- legacy/src/app/controllers/nodes_list.js
- legacy/src/app/controllers/tests/test_node_details.js
- legacy/src/app/controllers/tests/test_nodes_list.js
- legacy/src/app/directives/release_options.js
- legacy/src/app/directives/tests/test_release_options.js
- legacy/src/app/partials/directives/release-options.html
- legacy/src/app/partials/node-details.html
- legacy/src/app/partials/nodes-list.html
- Moved inline markup in release-options directive to its own partial.
- Renamed a few variables to be clearer (maasReleaseOptions => localOptions, erase => enableDiskErasing).
- Config is now explicitly loaded on directive render. Previously, it was assumed that the config had already been loaded, so refreshing on the node details page would return incorrect config values (i.e. nothing). This also means that a spinner will display when the release dropdown is opened.
- Also fixed a bug where `extra` parameters weren't actually getting passed to the websocket handler. LOL
- Select multiple machines and choose Release from the action menu, and check that the checkboxes correctly reflect what's set in Settings > Storage. Note that if "Enable disk erasing" is set to true in Settings, the …
> LP: #1832176 - Fix release-options directive not adopting defaults correctly

- shared/src/components/Footer/Footer.test.js
- shared/src/components/Footer/__snapshots__/Footer.test.js.snap
Mock Date for snapshot tests.
* None, tests should pass.
> Mock Date for snapshots.

- legacy/src/app/entry.js
- shared/src/components/Footer/__snapshots__/Footer.test.js.snap
- shared/src/components/Header/Header.js
- shared/src/components/Header/Header.test.js
- Update the header when the nav changes.
- Correctly match the URL against the hash.
- Load the legacy app.
- Click through a few items in the top nav. The current page should be highlighted.
- Do the same for the React app.
Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/615.
> Correctly highlight the nav item for the legacy app.

- ui/src/app/base/components/FormikField/FormikField.js
- Don't pass type to fields that don't need it.
- Visit /MAAS/r/settings/configuration/commissioning.
- The selects should now show the default browser icon as seen in https://github.com/canonical-web-and-design/maas-ui/issues/617.
- Have a poke around other forms, all should look normal.
Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/617.
> Fix default icon appearing in select elements

- legacy/src/app/bootstrap.js
* Removed usage of local storage for config in angular app
* Log in to create a session cookie and then close the tab (don't log out)
* Log in from a private window, and change the name of the user and then log out
* Open another MAAS tab (you shouldn't need to log in because the session is still valid) and check that the updated name is correctly shown in the top right
* Create a new user
* Log in as them and check that the intro page loads
Fixes #625
> Remove usage of local storage for config in angular app.

- ui/src/app/settings/views/Users/UserForm/UserForm.js
- ui/src/app/settings/views/Users/UserForm/UserForm.test.js
* You can now add admins/edit a user to be an admin
* Check that the MAAS administrator checkbox shows on user add/edit forms if you are logged in as an admin
* Check that it doesn't show up in the user preferences page
Fixes #626
> Fix bug where admins could no longer be added.

- legacy/.babelrc
- legacy/src/app/factories/users.js
* Turned UsersManager.loadItems and UsersManager.reloadItems into async functions that explicitly wait for authUser to load before loading users.
* Made legacy tests compatible with async/await.
* Create a new user, log in as them and go to the SSH keys intro page
* Refresh several times and check that there are never any console errors (the original issue was a race condition that occurred roughly 1 in 4 times for me)
Fixes canonical-web-and-design/MAAS-design#829 .
[lp#1811107](https://bugs.launchpad.net/maas/+bug/1811107)
> LP: #1811107 - Explicitly wait for authUser to load before loading users.

- ui/src/app/machines/views/MachineList/MachineList.js
- ui/src/app/machines/views/MachineList/OwnerColumn/OwnerColumn.js
- ui/src/app/machines/views/MachineList/OwnerColumn/OwnerColumn.test.js
- ui/src/app/machines/views/MachineList/OwnerColumn/__snapshots__/OwnerColumn.test.js.snap
- ui/src/app/machines/views/MachineList/OwnerColumn/index.js
- ui/src/app/machines/views/MachineList/PowerColumn/PowerColumn.js
- ui/src/app/machines/views/MachineList/PowerColumn/__snapshots__/PowerColumn.test.js.snap
- ui/src/scss/_patterns_double-row.scss
- ui/src/scss/base.scss
Add owner/tags column to machine listing.
* ensure owner displays correctly.
* ensure tags display correctly (add tags from machine details | configuration).
This branch is based on #631 and will need to be rebased once that lands.
> Add owner/tags column to machine listing.

- legacy/src/scss/_patterns_icons.scss
* Create `.p-icon--audit` class, which is identical to `.p-icon--information`.
* Go to the event tab of a machine and check that all rows have an icon.
Fixes #653 .
lp#1859626
> LP: #1859626 - Show information icon for audit events.

- legacy/src/app/directives/power_parameters.js
* Added the little red asterisk to the "Power type" field in the power parameters form
* Add a machine from the machine list and check that the form enables only when the required fields are filled in (MAC address and Power type)
Fixes #659
lp#1859087
> LP: #1859087 - Add required indicator for Power type field.

- ui/src/app/base/components/ScriptStatus/ScriptStatus.js
- ui/src/app/base/components/ScriptStatus/ScriptStatus.test.js
- ui/src/app/base/components/ScriptStatus/__snapshots__/ScriptStatus.test.js.snap
- ui/src/app/base/components/ScriptStatus/index.js
- ui/src/app/base/enum.js
- ui/src/app/machines/views/MachineList/DisksColumn/DisksColumn.js
- ui/src/app/machines/views/MachineList/DisksColumn/DisksColumn.test.js
- ui/src/app/machines/views/MachineList/DisksColumn/__snapshots__/DisksColumn.test.js.snap
- ui/src/app/machines/views/MachineList/DisksColumn/index.js
- ui/src/app/machines/views/MachineList/MachineList.js
- ui/src/app/machines/views/MachineList/NameColumn/NameColumn.js
- ui/src/app/machines/views/MachineList/NameColumn/NameColumn.test.js
- ui/src/app/machines/views/MachineList/OwnerColumn/OwnerColumn.js
- ui/src/app/machines/views/MachineList/OwnerColumn/__snapshots__/OwnerColumn.test.js.snap
- ui/src/app/machines/views/MachineList/ZoneColumn/ZoneColumn.js
- ui/src/app/machines/views/MachineList/ZoneColumn/__snapshots__/ZoneColumn.test.js.snap
- ui/src/scss/_patterns_icons.scss
- Added disks column which shows `machine.physical_disk_count`.
- Copied over scriptStatus enum from legacy which just lists out the different statuses a script can be in (failed, passed, running etc).
- Added ScriptStatus component that generates an icon and tooltip given a certain script type's status (e.g. storage tests have failed = return error icon and tooltip "Machine has failed tests", cpu tests are pending = return pending icon without tooltip, etc).
- Added icons for pending, running and timed out tests.
- Small css and markup fixes for other columns.
- Check that the disks column correctly displays the physical_disk_count of the machine
- Check that icons and tooltips display for machines that have storage tests that have failed/timed out/pending/running/no tests
Fixes …
> Add disks column to new machine listing.

- legacy/src/app/controllers/pod_details.js
- legacy/src/app/directives/machines_table.js
- legacy/src/app/partials/nodes-list.html
- legacy/src/app/partials/pod-details.html
* Fixed bug where newly composed machine would not appear in KVM page. I'm not proud of the solution (at all) but I'm not terribly excited about rewriting big chunks of the machine list or pod details controllers. :(
* Improved action feedback of compose machine button
* Compose a machine in a KVM and check that the button becomes disabled with a spinner
* Check that the machine shows up automatically in the list below the pod summary.
Fixes canonical-web-and-design/MAAS-squad#1079
[lp#1859032](https://bugs.launchpad.net/maas/+bug/1859032)
> LP: #1859032 - Fix bug where newly composed machine would not appear in KVM page.

- legacy/src/app/controllers/node_details.js
- legacy/src/app/controllers/tests/test_node_details.js
* Explicitly refresh summary page with with new data from the region by adding another watcher (AngularJS! :shakes fist:)
- Go to a Ready/Allocated machine's network tab
- Edit the name of an interface (or any other field that is also surfaced in the summary)
- Go back to the summary and check that it has updated
- Do the same with multiple browser tabs open, i.e. open the summary on one tab, edit an interface name on another, and check that the first tab automatically updates the name in the summary
Fixes #651 
lp#1859623
> LP: #1859623 - Sync network card in machine summary with region.

- legacy/src/app/controllers/node_details.js
- legacy/src/app/controllers/tests/test_node_details.js
- Added a conditional to the `getPowerEventError()` function so that it only returns if the node is currently in a power error state.
- Go to Machine details > Configuration, change the power configuration to be wrong and click "Save changes".
- Check that an error shows up at the top of the section, e.g. "Error:Failed to get domain: blah".
- Fix the power configuration and save again
- Check that the notification disappears.
Fixes #652 
lp#1850850
> LP: #1850850 - Only show power error notification if node is in error state.

- ui/src/app/base/components/ScriptStatus/ScriptStatus.js
- ui/src/app/base/components/ScriptStatus/ScriptStatus.test.js
- ui/src/app/machines/views/MachineList/CoresColumn/CoresColumn.js
- ui/src/app/machines/views/MachineList/CoresColumn/__snapshots__/CoresColumn.test.js.snap
- Removed the warning icon and tooltip for the None case
- See there are no warning icons in the new machine list for machines that have not run tests
Fixes #665
> Remove warning icon and tooltip if no tests have been run.

- legacy/src/app/partials/node-details.html
- Moved Create bond button GA event from `ng-disabled` attribute to correct `ng-click` attribute
- Go to the network tab of a machine
- Select two interfaces on the same VLAN and check that the "Create bond" button enables
- Check that you can actually create a bond
Fixes #680 
lp#1859849
> LP: #1859849 - Fix "Create bond" button being unresponsive.

- legacy/src/app/controllers/nodes_list.js
- legacy/src/app/directives/notifications.js
- legacy/src/app/directives/tests/test_notifications.js
- legacy/src/app/partials/nodelist/notifications.html
- legacy/src/app/partials/nodes-list.html
- Create notifications for each error when multiple machines have actions performed on them, instead of having them (very) temporarily displayed in the transition dropdown.
- Moved the notifications template to its own partial.
- Added a "Dismiss all" link to notification groups, which dismisses all notifications of a particular category (error, warning, info).
- Select multiple machines and perform an ILLEGAL ACTION on them (on karura there are a bunch of broken machines - try to mark them as fixed)
- Check that you get an error notification for each failure
- Check that you can dismiss notifications individually
- Check that "Dismiss all" works properly
Fixes #647 
lp#1859426
> LP: #1859426 - Group multiple errors from machine list in notifications section.

- legacy/src/app/partials/ipranges.html
- legacy/src/scss/_patterns_button.scss
- legacy/src/scss/_tables.scss
- legacy/src/scss/tables/_patterns_table-ipranges.scss
- Fixed invalid markup in ipranges partial. In development the markup was automagically fixed, but not when running the built files.
- Minor styling fixes (column widths, align buttons right, align form fields)
- Go to the Subnets page and choose a VLAN that has less than 100% available IPs
- Add a valid reserved range (dynamic or not) and see that it gets added properly
- Check that the add and edit forms no longer want you to gouge your eyes out
Fixes #656 
lp#1859630
> LP: #1859630 - Fix invalid markup and styling in ipranges partial.

- ui/src/app/machines/views/MachineList/CoresColumn/CoresColumn.js
- ui/src/app/machines/views/MachineList/CoresColumn/__snapshots__/CoresColumn.test.js.snap
- ui/src/app/machines/views/MachineList/DisksColumn/DisksColumn.js
- ui/src/app/machines/views/MachineList/DisksColumn/__snapshots__/DisksColumn.test.js.snap
- ui/src/app/machines/views/MachineList/FabricColumn/FabricColumn.js
- ui/src/app/machines/views/MachineList/FabricColumn/__snapshots__/FabricColumn.test.js.snap
- ui/src/app/machines/views/MachineList/MachineList.js
- ui/src/app/machines/views/MachineList/MachineList.scss
- ui/src/app/machines/views/MachineList/MachineList.test.js
- ui/src/app/machines/views/MachineList/NameColumn/NameColumn.js
- ui/src/app/machines/views/MachineList/OwnerColumn/OwnerColumn.js
- ui/src/app/machines/views/MachineList/OwnerColumn/__snapshots__/OwnerColumn.test.js.snap
- ui/src/app/machines/views/MachineList/PoolColumn/PoolColumn.js
- ui/src/app/machines/views/MachineList/PoolColumn/__snapshots__/PoolColumn.test.js.snap
- ui/src/app/machines/views/MachineList/PowerColumn/PowerColumn.js
- ui/src/app/machines/views/MachineList/PowerColumn/__snapshots__/PowerColumn.test.js.snap
- ui/src/app/machines/views/MachineList/StatusColumn/StatusColumn.js
- ui/src/app/machines/views/MachineList/StatusColumn/StatusColumn.test.js
- ui/src/app/machines/views/MachineList/StatusColumn/__snapshots__/StatusColumn.test.js.snap
- ui/src/app/machines/views/MachineList/StatusColumn/index.js
- ui/src/app/machines/views/MachineList/ZoneColumn/ZoneColumn.js
- ui/src/app/machines/views/MachineList/ZoneColumn/__snapshots__/ZoneColumn.test.js.snap
- ui/src/scss/base.scss
- Added StatusColumn component that handles the logic of what shows up in the status cell.
- Check that a machine that is deployed just shows the OS + release (only the number + LTS if an Ubuntu release e.g. Ubuntu 18.04 LTS instead of Ubuntu 18.04 LTS Bionic Beaver)
- Check that a machine that is deploying shows `Deploying ${OS + release}`
- Check that if a machine has failed tests and is not new, commissioning or testing, a warning icon and tooltip shows
- Check that when a machine is in a transient state (e.g. deploying), progress text is shown below the status and a spinner shows
Fixes canonical-web-and-design/MAAS-squad#1756
> Add status column to new machine listing.

- ui/src/app/machines/views/MachineList/CoresColumn/CoresColumn.js
- ui/src/app/machines/views/MachineList/ZoneColumn/ZoneColumn.js
- ui/src/app/machines/views/MachineList/ZoneColumn/ZoneColumn.test.js
Add Tooltip for machines with multiple spaces.
Ensure machines with multiple spaces have a tooltip over the `n spaces` count text. e.g. `comic-muskox-thing.maas` on karura.
> Add Tooltip for machines with multiple spaces.

- ui/src/app/base/components/ContextualMenu/ContextualMenu.js
- ui/src/app/base/components/ContextualMenu/ContextualMenu.test.js
- ui/src/app/base/components/ContextualMenu/__snapshots__/ContextualMenu.test.js.snap
- ui/src/app/base/components/ContextualMenu/index.js
- ui/src/app/base/components/TableMenu/TableMenu.js
- ui/src/app/base/components/TableMenu/TableMenu.scss
- ui/src/app/base/components/TableMenu/TableMenu.test.js
- ui/src/app/base/components/TableMenu/__snapshots__/TableMenu.test.js.snap
- ui/src/app/base/components/TableMenu/index.js
- ui/src/app/machines/views/MachineList/OwnerColumn/OwnerColumn.js
- ui/src/app/machines/views/MachineList/OwnerColumn/__snapshots__/OwnerColumn.test.js.snap
- Add a Vanilla contextual menu component.
- Add a table menu component.
- View /r/machines
- In the owner column you should see a contextual menu (this will be updated to appear on hover in a followup).
Fixes https://github.com/canonical-web-and-design/maas-squad/issues/1724.
> Add contextual menu

- ui/src/app/Routes.js
- ui/src/app/base/components/ErrorBoundary/ErrorBoundary.js
- ui/src/app/base/components/ErrorBoundary/ErrorBoundary.test.js
- ui/src/app/base/components/ErrorBoundary/index.js
Add React ErrorBoundary component, and wrap each app section. This is the first step towards implementing sentry reporting.
* Ensure the app still renders as expected.
* Deliberately break a component somewhere in the tree (e.g. drop `throw new Error('foo')` somewhere), and ensure the entire app doesn't crash and is still navigable. Be aware that the webpack devserver will fallback to displaying the full traceback, which you can close by clicking the 'X' in the top right.
> Add ErrorBoundaries around app sections.

- ui/src/app/base/components/ContextualMenu/ContextualMenu.js
- ui/src/app/base/components/ContextualMenu/__snapshots__/ContextualMenu.test.js.snap
- ui/src/app/base/components/TableMenu/TableMenu.scss
- Only calculate styles when the toggle element is visible.
- Click on a contextual menu a bunch of times, it should always appear in the same place (never in the top left of the page).
Fixes https://github.com/canonical-web-and-design/maas-ui/issues/714.
> Fix contextual menu position

- ui/src/app/App.js
- ui/src/app/base/components/Section/Section.js
- ui/src/app/base/components/Section/Section.test.js
- ui/src/app/machines/views/Machines.js
- ui/src/app/machines/views/Machines.test.js
- Added machine count to heading strip if machines have loaded, otherwise a spinner shows.
- Added a placeholder heading to the App.js Section title so that the heading strip wouldn't jump in size once auth user is loaded.
- Open the new machine list and check that a spinner shows while machines are loading
- Check that the heading strip maintains the same height while user loading > machines loading > machines loaded
- Check that a machine count shows when all the machines have loaded
Fixes canonical-web-and-design/MAAS-squad#1725.
> Add machine count to heading strip.

- ui/src/app/machines/views/Machines.js
- ui/src/app/machines/views/Machines.test.js
- Removed machine and resource pool counts from tab strip until they have loaded
- Go to the machine list and check that the tabs says "Machines" and "Resource pools" until they have loaded, at which point they say "X Machines" and "X Resource pools"
Fixes #725
> Remove machine/pool counts until fully loaded.

- ui/src/app/base/components/TableHeader/TableHeader.js
- ui/src/app/base/components/TableHeader/TableHeader.test.js
- ui/src/app/base/components/TableHeader/index.js
- ui/src/app/machines/views/MachineList/GroupSelect/GroupSelect.js
- ui/src/app/machines/views/MachineList/GroupSelect/GroupSelect.test.js
- ui/src/app/machines/views/MachineList/GroupSelect/__snapshots__/GroupSelect.test.js.snap
- ui/src/app/machines/views/MachineList/GroupSelect/index.js
- ui/src/app/machines/views/MachineList/MachineList.js
- ui/src/app/machines/views/MachineList/MachineList.scss
- ui/src/app/machines/views/MachineList/MachineList.test.js
- ui/src/app/machines/views/MachineList/NameColumn/NameColumn.js
- ui/src/app/machines/views/MachineList/NameColumn/NameColumn.test.js
- ui/src/app/machines/views/MachineList/PowerColumn/PowerColumn.js
- ui/src/app/machines/views/MachineList/PowerColumn/__snapshots__/PowerColumn.test.js.snap
- ui/src/app/settings/views/Users/UsersList/UsersList.js
- ui/src/app/settings/views/Users/UsersList/UsersList.test.js
- ui/src/app/utils/groupAsMap.js
- ui/src/app/utils/groupAsMap.test.js
- ui/src/app/utils/index.js
- ui/src/app/utils/simpleSortByKey.js
- ui/src/app/utils/simpleSortByKey.test.js
- ui/src/scss/_patterns_double-row.scss
- ui/src/scss/_patterns_table.scss
- ui/src/scss/_vanilla-overrides.scss
- ui/src/scss/base.scss
- Added a TableHeader component which allows table headers to be clickable to run their own sort functions. Used in MachineList and UserList in settings. This required a bit of custom work to override the default MainTable sort behaviour, so I'm not sure this work should be upstreamed to the component library (if ever). I think once the UX of a generic table between products is finalised we can settle on an implementation, but for now this implements what's in the current angular version.
- Added a GroupSelect component that implements grouping as in the current angular version, plus added options for pool, power state and zone.
- Added placeholder filter dropdown and searchbox.
- Refactored MachineList to better separate grouping, sorting and row generation functions.
- Clicking the FQDN …
> Implement machine list grouping and sorting with double row headers

- ui/src/app/base/actions/machine/machine.js
- ui/src/app/base/actions/machine/machine.test.js
- ui/src/app/machines/views/MachineList/MachineList.test.js
- ui/src/app/machines/views/MachineList/ZoneColumn/ZoneColumn.js
- ui/src/app/machines/views/MachineList/ZoneColumn/ZoneColumn.test.js
- ui/src/app/machines/views/MachineList/ZoneColumn/__snapshots__/ZoneColumn.test.js.snap
- ui/src/app/machines/views/Machines.test.js
- Add a menu to the zone column of the machine list to change the zone.
- Load /r/machines.
- Change the zone using the context menu.
- You should see a spinner and then the zone should change.
Fixes https://github.com/canonical-web-and-design/maas-squad/issues/1719.
> Add menu to change zones

- ui/src/__snapshots__/root-reducer.test.js.snap
- ui/src/app/base/reducers/auth/auth.js
- ui/src/root-reducer.js
- ui/src/root-reducer.test.js
- Set initial state for each reducer on LOGOUT_SUCCESS. Exceptions are auth and status which were causing authentication issues when cleared.
- Log in as an admin and go to the machine list.
- Log out and check that the header is cleared.
- Log in as a user while the url is still at the machine list.
- Check that the list of machines changes.
- Log out and check Redux Devtools that on LOGOUT_SUCCESS the state for everything reset.
Fixes #629
> Clear Redux state on log out.

- ui/src/app/machines/views/MachineList/MachineList.js
- ui/src/app/machines/views/MachineList/MachineList.test.js
- Added an "all machines" checkbox
- Added a selected count for each group
- Check that checking the checkbox in the table header selects all the machines in the list if at least one is not selected. Otherwise if all are selected, it unselects them all.
- Check that the number selected in the group header shows up correctly
Fixes canonical-web-and-design/MAAS-squad#1739
> Add checkbox for selecting/unselecting all machines in list.

- proxy/package.json
- yarn.lock
This also requires manually upgrading `webpack-dev-server` to `3.10.3`. If this QA's okay, and we merge this, we also need to create an issue against `maas-ui` to remove `webpack-dev-server` from `package.json` as soon as `react-scripts` has upgrade to `3.10.3+`.
* Upgraded to `react-scripts 3.3.1`.
* Ensure the app loads immediately, without the long time pause before 'Upgrading to Websocket`.
> Upgrade react-scripts to 3.3.1 

- ui/src/app/App.js
- ui/src/app/base/components/ContextualMenu/ContextualMenu.js
- ui/src/app/base/components/ContextualMenu/__snapshots__/ContextualMenu.test.js.snap
- ui/src/app/base/components/FormCard/FormCard.js
- ui/src/app/base/components/FormCard/FormCard.test.js
- ui/src/app/base/components/TableMenu/TableMenu.js
- ui/src/app/base/components/TableMenu/TableMenu.scss
- ui/src/app/base/components/TableMenu/__snapshots__/TableMenu.test.js.snap
- ui/src/app/machines/components/HeaderStrip/HeaderStrip.js
- ui/src/app/machines/components/HeaderStrip/HeaderStrip.test.js
- ui/src/app/machines/components/HeaderStrip/index.js
- ui/src/app/machines/components/Routes/Routes.js
- ui/src/app/machines/views/AddChassis/AddChassis.js
- ui/src/app/machines/views/AddChassis/AddChassis.test.js
- ui/src/app/machines/views/AddChassis/__snapshots__/AddChassis.test.js.snap
- ui/src/app/machines/views/AddChassis/index.js
- ui/src/app/machines/views/AddMachine/AddMachine.js
- ui/src/app/machines/views/AddMachine/AddMachine.test.js
- ui/src/app/machines/views/AddMachine/__snapshots__/AddMachine.test.js.snap
- ui/src/app/machines/views/AddMachine/index.js
- ui/src/app/machines/views/MachineList/OwnerColumn/__snapshots__/OwnerColumn.test.js.snap
- ui/src/app/machines/views/MachineList/PoolColumn/__snapshots__/PoolColumn.test.js.snap
- ui/src/app/machines/views/MachineList/ZoneColumn/__snapshots__/ZoneColumn.test.js.snap
- ui/src/app/machines/views/Machines.js
- ui/src/app/machines/views/Machines.test.js
- ui/src/app/pools/views/PoolForm/PoolForm.js
- ui/src/app/pools/views/PoolForm/PoolForm.test.js
- ui/src/scss/base.scss
- Refactored `Machines.js`, basically just by extracting out `HeaderStrip` into a separate component.
- Built "Add hardware" dropdown in machine list.
- Added placeholder `AddMachine` and `AddChassis` form components.
- Changed how `ContextualMenu` calculates position - @huwshimi not sure why but before I changed it the dropdown would only render after opening the dropdown twice? Some sort of weird race condition with the `useEffects`.... anyway it seems to work now.
- Tidied up spacing for some Loaders.
- Check that there is an "Add hardware" dropdown in the top-right of the machine list.
- Check that it is not there in the pools tab.
- Check that you are redirected to the Add machine and Add chassis forms when you click the links.
- Check that going to `/machines/cyw` takes you to an …
> Build 'Add hardware' dropdown.

- ui/src/app/base/components/TableActions/TableActions.js
- ui/src/app/base/components/TableActions/TableActions.test.js
- ui/src/app/base/components/TableActions/index.js
- ui/src/app/base/components/TableDeleteConfirm/TableDeleteConfirm.js
- ui/src/app/pools/views/Pools.js
- ui/src/app/preferences/views/APIKeys/APIKeyList/APIKeyList.js
- ui/src/app/preferences/views/SSLKeys/SSLKeyList/SSLKeyList.js
- ui/src/app/settings/views/Dhcp/DhcpList/DhcpList.js
- ui/src/app/settings/views/LicenseKeys/LicenseKeyList/LicenseKeyList.js
- ui/src/app/settings/views/Repositories/RepositoriesList/RepositoriesList.js
- ui/src/app/settings/views/Scripts/ScriptsList.js
- ui/src/app/settings/views/Users/UsersList/UsersList.js
- ui/src/app/settings/views/Users/UsersList/UsersList.scss
- Pulled out the common edit/delete/copy JSX from some tables into new TableActions component.
- Check that the following tables still work as intended (i.e clicking delete button opens delete panel, clicking edit button redirects to edit page, clicking copy button copies to clipboard):
- Settings: Users, licence keys, scripts, DHCP snippets and package repos
- User prefs: API keys, SSH keys and SSL keys 
- Machines: Pools list
Fixes #770
> Refactor table actions into TableActions component.

- RELEASE.md
- package.json
- ui/package.json
* Update release document with details for tracking MAAS releases.
* Bump version on master to `1.0.0` to reflect new process.
n/a
Fixes canonical-web-and-design/MAAS-squad#767
> Update release document and bump maas-ui to 1.0.0.

- ui/src/app/base/actions/machine/machine.js
- ui/src/app/base/actions/machine/machine.test.js
- ui/src/app/base/components/DoubleRow/DoubleRow.js
- ui/src/app/base/components/TableMenu/TableMenu.js
- ui/src/app/base/components/TableMenu/TableMenu.scss
- ui/src/app/base/reducers/machine/machine.js
- ui/src/app/base/reducers/machine/machine.test.js
- ui/src/app/base/selectors/machine/machine.js
- ui/src/app/base/selectors/machine/machine.test.js
- ui/src/app/machines/views/MachineList/MachineList.js
- ui/src/app/machines/views/MachineList/MachineList.test.js
- ui/src/app/machines/views/MachineList/PowerColumn/PowerColumn.js
- ui/src/app/machines/views/MachineList/PowerColumn/PowerColumn.test.js
- ui/src/app/machines/views/MachineList/PowerColumn/__snapshots__/PowerColumn.test.js.snap
- Add the power menu to the machines in the machine list
- In the power column you should see different actions depending on the current power state of the machine.
Fixes https://github.com/canonical-web-and-design/maas-squad/issues/1723.
> Add power menu to machine list

- ui/src/app/base/actions/machine/machine.js
- ui/src/app/base/actions/machine/machine.test.js
- ui/src/app/base/reducers/machine/machine.js
- ui/src/app/machines/views/MachineList/OwnerColumn/OwnerColumn.js
- ui/src/app/machines/views/MachineList/OwnerColumn/OwnerColumn.test.js
- ui/src/app/machines/views/MachineList/OwnerColumn/__snapshots__/OwnerColumn.test.js.snap
- Add actions for owners in the machine list.
- Clean up generation of machine actions.
- Click on the menu for an owner column.
- You should be able to perform different actions.
Fixes https://github.com/canonical-web-and-design/maas-squad/issues/1721.
> Add machine list owner actions

- ui/src/__snapshots__/root-reducer.test.js.snap
- ui/src/app/base/actions/domain/domain.js
- ui/src/app/base/actions/messages/messages.js
- ui/src/app/base/actions/messages/messages.test.js
- ui/src/app/base/actions/status/status.js
- ui/src/app/base/actions/status/status.test.js
- ui/src/app/base/actions/tag/tag.js
- ui/src/app/base/actions/websocket/websocket.js
- ui/src/app/base/reducers/controller/controller.js
- ui/src/app/base/reducers/controller/controller.test.js
- ui/src/app/base/reducers/device/device.js
- ui/src/app/base/reducers/device/device.test.js
- ui/src/app/base/reducers/dhcpsnippet/dhcpsnippet.js
- ui/src/app/base/reducers/domain/domain.js
- ui/src/app/base/reducers/domain/domain.test.js
- ui/src/app/base/reducers/messages/messages.js
- ui/src/app/base/reducers/resourcepool/resourcepool.js
- ui/src/app/base/reducers/service/service.js
- ui/src/app/base/reducers/service/service.test.js
- ui/src/app/base/reducers/status/status.js
- ui/src/app/base/reducers/subnet/subnet.js
- ui/src/app/base/reducers/subnet/subnet.test.js
- ui/src/app/base/reducers/tag/tag.js
- ui/src/app/base/reducers/tag/tag.test.js
- ui/src/app/base/reducers/user/user.js
- ui/src/app/base/reducers/user/user.test.js
- ui/src/app/base/reducers/zone/zone.js
- ui/src/app/base/reducers/zone/zone.test.js
- ui/src/app/utils/redux.js
- ui/src/app/utils/redux.test.js
* Migrate the majority of reducers with the same shape to redux-toolkit, generating 'standard' CRUD reducers using the `createStandardActions` utility.
* Ensure the app works as usual, without console errors.
Fixes canonical-web-and-design/MAAS-design#878
I've created [an additional card in the backlog](https://github.com/canonical-web-and-design/maas-ui/issues/801) with work that remains to fully complete the migration.
> Migrate some reducers to createReducer.

- ui/src/app/base/actions/machine/machine.js
- ui/src/app/base/actions/machine/machine.test.js
- ui/src/app/base/components/TableMenu/TableMenu.js
- ui/src/app/base/components/TableMenu/__snapshots__/TableMenu.test.js.snap
- ui/src/app/base/reducers/machine/machine.js
- ui/src/app/machines/views/MachineList/OwnerColumn/__snapshots__/OwnerColumn.test.js.snap
- ui/src/app/machines/views/MachineList/PoolColumn/__snapshots__/PoolColumn.test.js.snap
- ui/src/app/machines/views/MachineList/PowerColumn/__snapshots__/PowerColumn.test.js.snap
- ui/src/app/machines/views/MachineList/StatusColumn/StatusColumn.js
- ui/src/app/machines/views/MachineList/StatusColumn/StatusColumn.test.js
- ui/src/app/machines/views/MachineList/StatusColumn/__snapshots__/StatusColumn.test.js.snap
- ui/src/app/machines/views/MachineList/ZoneColumn/__snapshots__/ZoneColumn.test.js.snap
- Add the status column actions to the machine list.
- In the status column you should get a menu of different actions depending on the state of the machine.
Fixes https://github.com/canonical-web-and-design/maas-squad/issues/1722.
> Add the status column actions to the machine list

- ui/src/app/base/hooks.js
- ui/src/app/machines/views/MachineList/OwnerColumn/OwnerColumn.js
- ui/src/app/machines/views/MachineList/OwnerColumn/OwnerColumn.test.js
- ui/src/app/machines/views/MachineList/StatusColumn/StatusColumn.js
- ui/src/app/machines/views/MachineList/StatusColumn/StatusColumn.test.js
- ui/src/app/machines/views/MachineList/StatusColumn/__snapshots__/StatusColumn.test.js.snap
- Generate the machine actions using a generic hook.
- Replace action labels with the values from the API.
- Load /r/machines.
- Check that the owner and power columns display the actions as before and display nice text labels.
Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/793.
Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/811.
> Machine actions hook

- ui/src/app/App.test.js
- ui/src/app/base/actions/notification/notification.js
- ui/src/app/base/components/NotificationGroup/NotificationGroup.js
- ui/src/app/base/components/NotificationGroup/NotificationGroup.test.js
- ui/src/app/base/components/NotificationGroup/__snapshots__/NotificationGroup.test.js.snap
- ui/src/app/base/components/NotificationGroup/index.js
- ui/src/app/base/components/NotificationGroupMessage/NotificationGroupMessage.js
- ui/src/app/base/components/NotificationGroupMessage/NotificationGroupMessage.test.js
- ui/src/app/base/components/NotificationGroupMessage/index.js
- ui/src/app/base/components/NotificationList/NotificationList.js
- ui/src/app/base/components/NotificationList/NotificationList.test.js
- ui/src/app/base/components/NotificationList/__snapshots__/NotificationList.test.js.snap
- ui/src/app/base/hooks.js
- ui/src/app/base/selectors/index.js
- ui/src/app/base/selectors/notification/index.js
- ui/src/app/base/selectors/notification/notification.js
- ui/src/app/base/selectors/notification/notification.test.js
- ui/src/app/base/views/NotFound/NotFound.test.js
- ui/src/app/machines/views/Machines.test.js
- ui/src/app/preferences/views/Preferences.test.js
- ui/src/app/settings/views/Settings.test.js
- ui/src/app/utils/capitaliseFirst.js
- ui/src/app/utils/capitaliseFirst.test.js
- ui/src/app/utils/index.js
- ui/src/scss/_patterns_notifications.scss
- ui/src/scss/base.scss
* Add `NotificationGroup` and `NotificationGroupMessage` components for displaying and dismissing serverside notifications.
Note, this is *only* for serverside notifications. Messages generated by the app itself are still handled the same way. If we're going to consolidate our approach for these, it probably needs some UX discussion, as there are some tricky things to consider like - how do timeouts work in the context of a NotificationGroup? My gut feeling is that ephemeral messages like "You successfully added a user", should be handled differently from these serverside notifications. Perhaps what we already have makes the most sense. Something to consider perhaps @lilyvidenova 
* Add a single notification of any type.
* Ensure this displays without a toggle button, a "Dismiss all" …
> Add support for serverside notifications in UI.

- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/ActionFormWrapper.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/ActionFormWrapper.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/index.js
- ui/src/app/machines/components/HeaderStrip/AddHardwareMenu/AddHardwareMenu.js
- ui/src/app/machines/components/HeaderStrip/AddHardwareMenu/AddHardwareMenu.test.js
- ui/src/app/machines/components/HeaderStrip/AddHardwareMenu/index.js
- ui/src/app/machines/components/HeaderStrip/HeaderStrip.js
- ui/src/app/machines/components/HeaderStrip/HeaderStrip.test.js
- ui/src/app/machines/components/HeaderStrip/HeaderStripTabs/HeaderStripTabs.js
- ui/src/app/machines/components/HeaderStrip/HeaderStripTabs/HeaderStripTabs.test.js
- ui/src/app/machines/components/HeaderStrip/HeaderStripTabs/index.js
- ui/src/app/machines/components/HeaderStrip/TakeActionMenu/TakeActionMenu.js
- ui/src/app/machines/components/HeaderStrip/TakeActionMenu/TakeActionMenu.test.js
- ui/src/app/machines/components/HeaderStrip/TakeActionMenu/index.js
- ui/src/app/machines/views/Machines.js
- Split HeaderStrip into smaller components because it was starting to get large. Now it consists of:
- AddHardwareMenu
- TakeActionMenu
- HeaderStripTabs
- ActionFormWrapper (which is bare bones right now, but will house the individual form components for each action type) 
- Built the "update your selection" functionality from the angular machine list, which filters selected machines to only those that can perform the selected action.
- Select a bunch of machines.
- Open the take action menu and pick an action that not all machines can perform.
- Check that a warning shows up that asks you to update your selection.
- Click the "update your selection" link and check that the selected machines are filtered to those that can perform the action.
- Check that the submit label is formatted …
> Refactor HeaderStrip. Implement update selection functionality in machine list.

- ui/src/app/machines/views/MachineList/MachineList.scss
- ui/src/app/machines/views/MachineList/PowerColumn/PowerColumn.js
- ui/src/app/machines/views/MachineList/PowerColumn/__snapshots__/PowerColumn.test.js.snap
- Correctly truncate the power text for small screens or when the action icon is visible.
- Open /r/machines.
- Reduce the size of your screen a bit until some of the power statuses don't have room. They should truncate with an ellipsis.
- Hover of the statuses, the menu chevron should appear and the statuses should further truncate.
Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/809.
> Truncate the power text

- ui/src/app/machines/views/AddMachine/AddMachineForm/AddMachineForm.js
- ui/src/app/machines/views/AddMachine/AddMachineForm/AddMachineForm.test.js
- ui/src/app/machines/views/AddMachine/AddMachineFormFields/AddMachineFormFields.js
- ui/src/app/machines/views/AddMachine/AddMachineFormFields/AddMachineFormFields.test.js
- ui/src/scss/_patterns_forms.scss
- ui/src/scss/base.scss
- Added extra macs button and extra macs fields to add machine form. Getting it to work with FormikField was tricky because of it being an optional field with variable size, so I've opted to instead build a more custom/imperative approach. I don't think this sort of pattern shows up anywhere else in MAAS.
- Go to /r/machines/add
- Check that you can add and remove extra MAC fields
- Submit the form with extra MACs
- Check that the network request includes an array of `extra_macs` and the machine is added successfully
Fixes #794
> Add extra macs fields to add machine form.

- ui/src/app/settings/views/Configuration/GeneralForm/GeneralForm.js
* Changed text for analytics textbox to "Enable analytics to shape improvements to user experience" with helptext of "The analytics used in MAAS are Google Analytics and Sentry Error Tracking."
none
Fixes #828  .
> Improve helptext for settings analytics checkbox.

- README.md
Add status badge for CI github action workflow.
* View the rich diff of the README, badge should be green.
> Add status badge for CI workflow.

- .github/workflows/test.yml
* Drop node 10 from CI runs. dotrun for some time has only used node 12 in the docker image.
* None, tests should pass.
> Only run CI with node 12.

- ui/src/app/base/components/FormCardButtons/FormCardButtons.js
- ui/src/app/base/components/FormCardButtons/FormCardButtons.test.js
- ui/src/app/base/components/FormCardButtons/__snapshots__/FormCardButtons.test.js.snap
- ui/src/app/base/components/FormikForm/FormikForm.js
- ui/src/app/base/components/FormikFormButtons/FormikFormButtons.js
- ui/src/app/base/components/FormikFormButtons/FormikFormButtons.test.js
- ui/src/app/base/components/FormikFormContent/FormikFormContent.js
- ui/src/app/machines/views/AddChassis/AddChassisForm/AddChassisForm.js
- ui/src/app/machines/views/AddMachine/AddMachineForm/AddMachineForm.js
- Add secondary submit props to FormCardButtons to allow another way to submit a form.
- In this case the the secondary submit is the same as the normal one, but the default "redirect on save" behaviour is prevented.
- Go to `/MAAS/r/machines/add` and fill the form in correctly.
- Click "Save and add another" and check that the new machine is added into state, a notification confirms it, and you are not redirected to the machine list.
- Fill in the form again and click "Save machine".
- Check that you are redirected to the machine list, as before.
- Do the same with the "Add chassis" form (`/MAAS/r/machines/chassis/add`)
Fixes #795
> Build "Save and add another" secondary submit in hardware forms.

- legacy/src/app/controllers/add_hardware.js
- legacy/src/app/controllers/tests/test_add_hardware.js
- Replaced leftover jQuery reference in legacy add-chassis http request with native javascript version.
- Go to `/MAAS/#/machines` > Click `Add hardware` > Click `Chassis`
- Fill in the form with a virsh power type (PowerKVM/Virsh)
- Submit the form and check that the network request has a 200 response code.
Fixes #842 
[lp#1864809](https://bugs.launchpad.net/maas/+bug/1864809)
> Remove leftover jQuery reference in add-chassis http request.

- ui/src/app/base/components/FormikForm/FormikForm.js
- ui/src/app/base/components/FormikForm/FormikForm.test.js
- ui/src/app/base/components/FormikFormContent/FormikFormContent.js
- ui/src/app/machines/views/AddChassis/AddChassisForm/AddChassisForm.js
- ui/src/app/machines/views/AddMachine/AddMachineForm/AddMachineForm.js
- ui/src/app/machines/views/AddMachine/AddMachineFormFields/AddMachineFormFields.js
- Reset add machine/chassis form if user successfully submits with the "Save and add another" button.
- Reworded some FormikForm props from `redirectOnSave` to `resetOnSave` (and consequently reversed logic). Seems a bit clearer for me to highlight resetting a form than handling redirects in the form logic.
- Go to `/MAAS/r/machines/add`
- Fill in the fields and add a machine using the "Save and add another" button.
- Check the form resets on successful submit and a notification confirms the machine is added.
- Add another machine using values that will return an error from the backend (i.e. duplicate hostname/MAC, unknown virsh address, etc.)
- Submit the form with "Save and add another"
- Check that an error notification shows up and the form does not get reset.
- Do the same at …
> Reset add machine/chassis form if "add another" button used.

- ui/src/app/base/components/UserForm/UserForm.js
* Removed password length restriction for users
* Check that you can create and log in as a user with a 1 character password, like with the api
Fixes #865
> Remove password length restriction for users.

- legacy/src/app/partials/nodelist/nodes-list-filter.html
- ui/src/app/base/components/ContextualMenu/ContextualMenu.js
- ui/src/app/base/components/ContextualMenu/ContextualMenu.test.js
- ui/src/app/machines/filter-nodes.js
- ui/src/app/machines/views/MachineList/FilterAccordion/FilterAccordion.js
- ui/src/app/machines/views/MachineList/FilterAccordion/FilterAccordion.scss
- ui/src/app/machines/views/MachineList/FilterAccordion/FilterAccordion.test.js
- ui/src/app/machines/views/MachineList/FilterAccordion/__snapshots__/FilterAccordion.test.js.snap
- ui/src/app/machines/views/MachineList/FilterAccordion/index.js
- ui/src/app/machines/views/MachineList/MachineList.js
- ui/src/app/utils/formatBytes.js
- ui/src/app/utils/formatBytes.test.js
- ui/src/app/utils/formatSpeedUnits.js
- ui/src/app/utils/formatSpeedUnits.test.js
- ui/src/app/utils/index.js
- ui/src/app/utils/search.js
- ui/src/app/utils/search.test.js
- Add the filter accordion UI.
- Open the filter accordion and expand different sections, you should see options based on the machines you have.
- Click on some options, your machines should be filtered.
Note: the search box will not be updated with the text until a feature has been added to the react-component lib. This is added in this PR: https://github.com/canonical-web-and-design/react-components/pull/75.
Fixes: https://github.com/canonical-web-and-design/maas-squad/issues/1487.
> Add filter accordion UI

- ui/package.json
- yarn.lock
- Backport connected-react-router to 6.8.0 to fix a security issue in the acorn subdep.
> Upgrade connected-react-router to 6.8.0

- ui/src/app/base/selectors/machine/machine.js
- ui/src/app/machines/filter-nodes.js
- ui/src/app/machines/filter-nodes.test.js
- ui/src/app/machines/search.js
- ui/src/app/machines/search.test.js
- ui/src/app/machines/views/MachineList/MachineList.js
- ui/src/app/utils/search.js
- Clean up DSL destructuring.
- Implement selected filtering.
- Fix DSL bugs.
- Select some machines.
- In the search box search for `in:selected`, you should only see your selected machines.
- In the search box search for `in:!selected`, you should not see your selected machines.
- Check that you can search in other ways according to: https://maas.io/docs/interactive-search
Fixes: https://github.com/canonical-web-and-design/maas-squad/issues/1799.
> Improve search DSL and add selected filtering

- ui/src/app/base/actions/machine/machine.js
- ui/src/app/base/actions/machine/machine.test.js
- ui/src/app/base/components/FormCard/_index.scss
- ui/src/app/base/components/FormCardButtons/FormCardButtons.js
- ui/src/app/base/components/FormikForm/FormikForm.js
- ui/src/app/base/components/FormikFormContent/FormikFormContent.js
- ui/src/app/base/hooks.js
- ui/src/app/base/reducers/machine/machine.js
- ui/src/app/base/reducers/machine/machine.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/ActionForm/ActionForm.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/ActionForm/ActionForm.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/ActionForm/__snapshots__/ActionForm.test.js.snap
- ui/src/app/machines/views/MachineList/PowerColumn/PowerColumn.js
- ui/src/app/utils/index.js
- ui/src/app/utils/kebabToCamelCase.js
- ui/src/app/utils/kebabToCamelCase.test.js
- Updated `ActionForm` to dispatch actions for forms that don't have fields, which are the following:
- Acquire
- Release
- Abort
- Power on
- Power off
- Lock
- Unlock
- Rescue mode
- Exit rescue mode
- Mark broken
- Mark fixed
- Delete (red button)
- Added a string util function `kebabToCamelCase` for converting the websocket method names into our redux action names.
- Select some machines and check that you can successfully perform the above actions, taking note that the delete action should remove the machine from `items` state and `selected` state.
- Check that the delete button is red instead of green.
- Note that errors and progress will be tackled in #881 - this PR merely makes it possible to perform these actions in batch. 
Fixes canonical-web-and-design/MAAS-squad#1783
> Build form components for actions that do not require fields.

- .gitignore
- ui/src/app/machines/filter-nodes.js
- ui/src/app/machines/search.js
- ui/src/app/machines/search.test.js
- ui/src/app/machines/views/MachineList/MachineList.js
- ui/src/app/machines/views/MachineList/MachineList.test.js
- Added utils to converting to and from URL query strings and filters.
- Initialise the search filters from the URL and update the URL when the filters change.
- Load /r/machines.
- Type a search into the search box, the URL should change.
- Select some filters in the filter dropdown, the URL should change.
- Refresh the page, your filters should be restored.
Fixes: https://github.com/canonical-web-and-design/maas-squad/issues/1798.
> Search filter URLs

- ui/package.json
- ui/src/app/machines/views/MachineList/MachineList.js
- ui/src/app/machines/views/MachineList/MachineList.test.js
- yarn.lock
- Persist the grouping type and collapsed groups using local storage.
- Change the grouping (using the Group by... select box).
- Collapse some groups (the "-" minus icon to the right of the group names in the table).
- Refresh the page. The grouping type and collapsed groups should be the same.
Fixes: https://github.com/canonical-web-and-design/maas-squad/issues/1852.
Fixes: https://github.com/canonical-web-and-design/maas-squad/issues/1851.
> Persist grouping

- ui/src/app/pools/views/Pools.js
- ui/src/app/pools/views/Pools.test.js
- Link from pools to the machine list.
- Visit /r/pools.
- Add a pool (using the Add pool button in the top right) and add 1 or more machines to that pool (click on a machine from the machine list and then click on Configuration and change 'Resource pool').
- Add another pool and leave it empty.
- Go back to the pool list and the pool with no machines should have "Empty pool" in the machines column.
- For a pool with machines you should see something like "0 of 1 ready". Click on that link. You should be take to the machine list with only the machines in that pool visible.
Fixes: https://github.com/canonical-web-and-design/maas-squad/issues/1807.
> Link from pools to machines

- ui/src/app/machines/search.js
- ui/src/app/machines/search.test.js
- Correctly match against one character searches.
- Using the search box enter a character that doesn't match many machines (e.g. "q").
- Your machines should be filtered.
Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/868.
> Fix one character search matching

- .circleci/config.yml
- proxy/cypress/integration/login/login.spec.js
- Set up basic, real MAAS using 2.7/edge snap when running cypress in Circle CI.
- Added a non-stubbed test that could only pass if a real MAAS was running (auth errors returned from api and displayed in UI)
- Removed Circle CI tests that have been migrated to GH actions
- Check that tests pass in Circle CI
Fixes #541
> Set up real MAAS when running cypress in Circle CI.

- ui/src/app/base/actions/machine/machine.js
- ui/src/app/base/actions/machine/machine.test.js
- ui/src/app/base/components/FormikForm/FormikForm.js
- ui/src/app/base/components/FormikFormContent/FormikFormContent.js
- ui/src/app/base/hooks.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/ActionFormWrapper.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/DeployForm/DeployForm.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/DeployForm/DeployForm.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/DeployForm/DeployFormFields/index.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/DeployForm/index.js
- Built deploy form in action menu dropdown.
- Select a bunch of machines and choose Deploy from the action dropdown.
- Check that the defaults have been set correctly as per `/MAAS/r/settings/configuration/deploy` and `/MAAS/r/settings/configuration/commissioning`
- Check that only Ubuntu 18.04 enables the checkbox for KVM host
- Remove all SSH keys associated with the user and check that the deploy form shows a warning about logging in.
Fixes canonical-web-and-design/MAAS-squad#1781
> Build deploy form in action menu dropdown.

- ui/src/app/machines/views/MachineList/MachineList.js
- Identify each machine table row with the machine id. This allows React to know how to manipulate the DOM nodes. In this case it fixes a Chrome repaint issue when the content changes.
- First make sure you can reproduce the issue on master.
- Run maas-ui on master, then load /r/machines in Chrome.
- Create two machines. Give one the tags "tagA" and "tag B" and the other machine just "tagA".
On the machine list change to no grouping.
In the search box type "tagB" then delete the "B". You should see a broken border in one of the cells, something like this: https://user-images.githubusercontent.com/18423198/77896527-5a977380-7270-11ea-81a2-fea592626a29.png.
- Now switch to this branch and repeat the search steps: In the search box type "tagB" then delete the "B".
- This time you should not …
> Uniquely identify machine rows

- ui/src/index.js
Log the maas-ui version to console when the app starts.
We don't want to expose the maas-ui version to users in the app (they should be reporting just the MAAS version), but it's helpful for debugging production builds.
* Start the app, and open the console. You should see `@maas-ui/ui 1.1.0`.
> Log maas-ui version to console when app starts.

- legacy/src/app/controllers/nodes_list.js
- legacy/src/app/partials/nodes-list.html
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.js
- Fixed styling regression of SSH key warning in deploy form.
- Fixed link to account prefs ssh keys page
- Log in as a user without ssh keys (or remove them from your user)
- Go to legacy machine list, and try to deploy a machine from the action dropdown
- Check that a warning shows up about SSH keys, and is styled correctly
- Check that the link takes you to the React SSH keys page
Fixes #926
> Fix legacy deploy form styling.

- package.json
- ui/package.json
- ui/src/app/machines/views/MachineList/FilterAccordion/FilterAccordion.js
- ui/src/app/machines/views/MachineList/FilterAccordion/__snapshots__/FilterAccordion.test.js.snap
- yarn.lock
- Persist the last opened filter in the machine filter dropdown.
- Open the filters dropdown and expand a filter to see the values.
- Click off the dropdown so it closes.
- Open the dropdown again. The previously opened filter should be open again.
Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/924.
> Persist filter menu state

- legacy/src/app/entry.js
* Fix recursive header rendering by ensuring routeChangeSuccess handler is only setup once on app init.
Note: only relevant changes are 368, 389, the rest prettier touched. 
* Load the app, and click between _angular_ routes for 20s or so. The app should not get progressively slower and crawl to a standstill.
Fixes #872
> Fix recursive header rendering.

- .github/workflows/test.yml
- Don't install the Cypress binary for GitHub actions CI. This should speed up `yarn install` which currently takes about 1m 40s.
- None, CI should pass.
Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/894.
> Don't install the Cypress binary for GitHub actions CI

- ui/src/index.js
- Disable the thunk middleware that we don't use.
- Check that everything works as before.
Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/939.
> Disable thunk middleware

- ui/src/app/machines/views/MachineList/_index.scss
- Force the last machine row to calculate its height.
- First try to replicate this on master (should be broken in Chrome and Firefox):
- - Go to /r/machines.
- - Use the search box to filter the machine.
- - Sometimes the last line will get slightly cut off. Try to replicate this consistently.
- Now checkout my branch and repeat the steps above.
- This time the last row shouldn't get cut off.
Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/935.
> Fix the last machine row cutting off the content

- ui/src/app/App.js
- ui/src/app/base/actions/status/status.js
- ui/src/app/base/sagas/websockets.js
- ui/src/app/base/sagas/websockets.test.js
- ui/src/app/machines/views/MachineList/MachineList.js
- To deal with multiple components requesting the same data at once the loaded models are stored in the saga module.
- Drive-by to disconnect from the websocket when logging out.
- View /r/machines.
- In your network tab check the websocket for machine.list. You should only see one.
- Log out and back in, your models should load again.
> Manage the list of loaded models in the saga module

- legacy/src/app/directives/call_to_action.js
- legacy/src/app/partials/directives/cta.html
- legacy/src/app/partials/pods-list.html
- Disabled/enabled Take Action and Add KVM buttons based on machine selection.
- When no KVMs are selected, check that Take action is displayed and disabled. Check that a tooltip shows on hover.
- When a KVM is selected, check that the Take action button is enabled and the Add KVM button is disabled.
Fixes canonical-web-and-design/MAAS-squad#1870
> Disable/enable Take Action and Add KVM buttons based on machine selection.

- ui/package.json
- ui/src/app/base/components/ContextualMenu/ContextualMenu.js
- ui/src/app/base/components/FormikField/FormikField.js
- ui/src/setupTests.js
- yarn.lock
- Replace our nanoid dependency with the import provided by Redux Toolkit.
- None, CI should pass.
Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/954.
> Use nanoid from Redux Toolkit

- ui/src/app/base/actions/machine/machine.js
- ui/src/app/base/actions/machine/machine.test.js
- ui/src/app/base/actions/packagerepository/packagerepository.js
- ui/src/app/base/actions/packagerepository/packagerepository.test.js
- ui/src/app/base/reducers/machine/machine.js
- ui/src/app/base/reducers/machine/machine.test.js
- ui/src/app/base/sagas/websockets.js
- ui/src/app/base/sagas/websockets.test.js
- ui/src/app/machines/components/HeaderStrip/HeaderStripTabs/HeaderStripTabs.js
- ui/src/app/machines/views/MachineList/MachineList.js
- ui/src/app/machines/views/MachineList/MachineList.test.js
- ui/src/app/settings/views/Repositories/RepositoryForm/RepositoryForm.test.js
- ui/src/app/utils/redux.js
- ui/src/app/utils/redux.test.js
- ui/src/websocket-client.js
- ui/src/websocket-client.test.js
- Add support for batch loading via the websocket API.
- Batch load the machine list.
- Your machines should get loaded in lots of 25.
Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/919.
Fixes: https://github.com/canonical-web-and-design/MAAS-squad/issues/1871.
> Batch load machines

- ui/src/app/machines/components/HeaderStrip/AddHardwareMenu/AddHardwareMenu.js
- ui/src/app/machines/components/HeaderStrip/AddHardwareMenu/AddHardwareMenu.test.js
- ui/src/app/machines/components/HeaderStrip/HeaderStrip.js
- ui/src/app/machines/components/HeaderStrip/HeaderStrip.test.js
* Disable Add hardware toggle when machines are selected.
* Visit `/r/machines` and select a machine, the Add Hardware toggle should be disabled. Unselect all machines and the toggle should be enabled.
Fixes canonical-web-and-design/MAAS-design#883.
> Disable Add hardware toggle when machines are selected.

- legacy/src/app/partials/directives/error_overlay.html
- legacy/src/app/partials/domain-details.html
- legacy/src/app/partials/domains-list.html
- legacy/src/app/partials/fabric-details.html
- legacy/src/app/partials/networks-list.html
- legacy/src/app/partials/node-details.html
- legacy/src/app/partials/nodes-list.html
- legacy/src/app/partials/pod-details.html
- legacy/src/app/partials/space-details.html
- legacy/src/app/partials/zones-list.html
- Fixed inconsistent header strip sizes in angular pages.
- Navigate between angular pages (and react pages if you want) and check that the header strip does not change height, with the exception of pages with tab strips (e.g. machine list, node details).
- Reload the page and check that the transition from Loading... > Connecting... > Page title does not change the header height.
Fixes #961
> Fix inconsistent header strip sizes in angular pages.

- legacy/src/app/partials/nodelist/add-machine.html
- Fixed form validation for extra MACs fields when adding new machine.
- Go to angular machine list > Add hardware > Machine and add extra macs
- Type into the macs fields and check that they validate correctly (just a red border in Vanilla 2.0.1)
Fixes #905
> Fix form validation when adding machine with multiple MACs.

- legacy/src/app/controllers/pod_details.js
- legacy/src/app/partials/pod-details.html
- Changed label for power address if pod is a LXD host (Virsh => LXD URL)
- Fixed copy to clipboard for power address
- Removed speed input from compose form
- Removed "Minimum" from cores and RAM labels in compose form
- Check that the details page matches the [design](https://app.zeplin.io/project/5e538f1156434564ebb73903/screen/5e8da399f373c323bccb4ede)
- Check that the compose form matches the [design](https://app.zeplin.io/project/5e538f1156434564ebb73903/screen/5e8de1424d7d1d22638dcaa4)
- Check that you can still compose machines
Fixes canonical-web-and-design/MAAS-squad#1877
Fixes #686
> Update pod details page to new design.

- ui/src/app/machines/views/MachineList/MachineList.js
- ui/src/app/pools/views/Pools.js
- ui/src/app/pools/views/Pools.test.js
- ui/src/app/utils/formatErrors.js
- ui/src/app/utils/formatErrors.test.js
- ui/src/app/utils/index.js
- Disabled delete button for pools that contain at least one machine.
- Show resourcepool errors in state in a notification on the pool list
- Go to `/r/pools` and check that resource pools with machines in them have disabled delete buttons that have a tooltip on hover
- Remove the `deleteDisabled` prop from `<TableActions>` in `Pools.js`
- Attempt to delete a pool that you otherwise couldn't and check that a an error notification shows up that you can clear
Fixes #918
> Prevent user from deleting pools that contain machines.

- legacy/src/app/controllers/node_details.js
- legacy/src/app/controllers/tests/test_node_details.js
- legacy/src/app/factories/nodes.js
- legacy/src/app/factories/tests/test_nodes.js
- legacy/src/app/partials/cards/machine-overview.html
- legacy/src/scss/grids/_patterns_machine-overview.scss
Waiting on backend engineers for info on:
- Machine title changed from "Overview" to "Machine Status", unless the machine is a VM then it becomes "Virtual Machine Status".
- If the machine has a pod host a "Host" section is added to the summary card with a link to it.
- Check that the page matches the [design](https://app.zeplin.io/project/5e538f1156434564ebb73903/screen/5e8da39ae67405b8ca0ee3a3)
- Check that the machine details title is "Virtual Machine Status" for VMs, and "Machine Status" for normal machines
- Check that machines with a pod have a link to it.
Fixes canonical-web-and-design/MAAS-squad#1867
Fixes canonical-web-and-design/MAAS-squad#1868
Fixes canonical-web-and-design/MAAS-squad#1869
> Update machine details page with VM/KVM data.

- ui/src/app/base/actions/machine/machine.js
- ui/src/app/base/actions/machine/machine.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/ActionFormWrapper.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/CommissionForm/CommissionForm.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/CommissionForm/CommissionForm.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/CommissionForm/CommissionFormFields/CommissionFormFields.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/CommissionForm/CommissionFormFields/index.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/CommissionForm/index.js
Add commissioning global take action form.
* Select 1 or more commissionable machines (e.g. "new"), and select commission from the global take action menu.
* Select some options from the form.
* Ensure the redux action and websocket request matches the options you've provided.
* Ensure your machine(s) are moved to the "commissioning" state.
Fixes canonical-web-and-design/MAAS-squad#1779.
> Add commissioning form.

- .circleci/config.yml
- ui/src/app/base/components/Login/Login.js
- ui/src/app/base/components/Login/Login.test.js
- ui/src/app/base/reducers/status/status.js
- ui/src/app/base/reducers/status/status.test.js
- ui/src/app/base/selectors/status/status.js
- ui/src/app/base/selectors/status/status.test.js
- Added warning to login page if no users detected.
- Create a MAAS using the latest edge snap but don't create an admin
- Try to log in and check that a message shows up asking you to create an admin
- Click Retry and check that the page is refreshed as normal
- Create an admin using `sudo maas createadmin` and then click the Retry button again
- Check that the Login page shows up
Fixes #969 
https://code.launchpad.net/~ack/maas/+git/maas/+merge/382269
> Add warning to login page if no users detected.

- ui/src/app/base/actions/resourcepool/resourcepool.js
- ui/src/app/base/actions/resourcepool/resourcepool.test.js
- ui/src/app/base/sagas/actions.js
- ui/src/app/base/sagas/actions.test.js
- ui/src/app/base/sagas/index.js
- ui/src/app/base/sagas/websockets.js
- ui/src/app/base/sagas/websockets.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/SetPoolForm/SetPoolForm.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/SetPoolForm/SetPoolFormFields/SetPoolFormFields.js
- ui/src/root-saga.js
- Set up the websocket channel to receive additional messages.
- Handle creating a pool and attaching machines to it.
Note: Errors and saving state will be handled by https://github.com/canonical-web-and-design/maas-ui/issues/984 and https://github.com/canonical-web-and-design/maas-ui/issues/881.
- Visit the machine list. Select machines and choose "Set resource pool..." from the take action menu.
- Change the radiobutton to "Create pool".
- Enter a new pool name and submit the form.
- Your selected machines should be attached to the new pool.
Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/928.
> Create a pool and attach machines to it

- legacy/package.json
- legacy/src/app/partials/node-details.html
- legacy/src/app/partials/nodes-list.html
- yarn.lock
- Reverted jquery from 3.5.0 to 3.4.1. The issue could have been [this breaking change](https://github.com/jquery/jquery/issues/4665).
- Checkout master, clean your node_modules (`yarn clean-all` or `dotrun clean`) and run
- Confirm that node details, devices list, and controllers list are all broken with warning icons.
- Checkout this branch and clean your node_modules and run again
- Confirm that the node details, devices list and controllers list look normal
Fixes #977
> Revert jquery to 3.4.1

- legacy/src/app/controllers/node_details_networking.js
- legacy/src/app/partials/node-details.html
- Added guards to a few node details networking functions.
- Removed a bit of broken markup (which actually might have been the cause of all the errors - angular templating tracebacks have never been very helpful)
- This one is hard to QA because I couldn't reliably reproduce the errors. I did get the `type is not defined` one a couple of times, each after marking an interface as connected or disconnected. So I'm not sure... click around on all the different buttons, add/delete interfaces, bridges, bonds... and check that you don't get any errors in the console?
Fixes #892 
Fixes #893
> Add guards to node details networking functions.

- renovate.json
Exclude jquery from renovate grouping.
n/a
Fixes #989
> Exclude jquery from renovate grouping.

- legacy/src/app/controllers/node_details.js
- legacy/src/app/controllers/tests/test_node_details.js
- legacy/src/app/filters/format_bytes.js
- legacy/src/app/filters/tests/test_format_bytes.js
- legacy/src/app/partials/cards/numa.html
- legacy/src/scss/_patterns_numa.scss
- Converted NUMA core list into core ranges (e.g. "0, 1, 2, 3, 5, 6, 8" => "0-3, 5-6, 8").
- Rounded NUMA memory values to four significant figures.
- Improved null/zero cases for NUMA values, e.g. "0" => "0 B", "0 disk" => "0 disks".
- Open `node_details.js` and replace lines 473-479 with [this pastebin](https://pastebin.canonical.com/p/HBSn4GYYbm/).
- Go to the details page of any machine which now has fake data for 4 NUMA nodes.
- Check that the NUMA card matches the [design](https://camo.githubusercontent.com/8d85d6a881645a4fd7cbad80eb42eb16a8f53ee5/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3561663937363732346235383036626332626433303836302f61633134303163382d313464632d343031662d613839332d626634326237306538613361)
- Check that the null cases read better. …
> Fix NUMA card styling errors.

- ui/src/app/machines/views/MachineList/MachineList.js
Remove redundant loader on machine listing, as we already have a loading component in the header.
* View the machine listing, there should only be one "loading..." spinner.
Fixes #974
> Remove redundant loader on machine listing.

- ui/src/scss/_patterns_icons.scss
- Fixed bug where lock icon was a grey power icon instead of a padlock.
- Ran padlock svg through svgo and converted to background-image css that doesn't rely on the ubuntu asset server
- Lock a machine and check that a padlock icon shows up next to it
Fixes #996
> Fix lock icon background-image to be a padlock.

- shared/src/components/Footer/Footer.js
I noticed today that Usabilla thinks MAAS 2.8 is 2.7 today on bolla, which made me think we weren't using the version string supplied by the app @lilyvidenova. Turns out the version string we supply was broken anyway (we would have been sending you the literal string `"${version}"`)! I suspect there might be something to tweak in the message template on Usabilla once this lands @lilyvidenova?
Also possible that you may need us to supply a "friendly" version string (just major and minor numbers, e.g. "2.8"). If so, please create an issue for it @lilyvidenova and we can try to fix that for the release.
Fix invalid interpolated version string for usabilla.
> Fix invalid interpolated version string for usabilla.

- ui/src/app/base/reducers/machine/machine.js
- ui/src/app/base/reducers/machine/machine.test.js
- ui/src/app/base/selectors/general/machineActions.js
- ui/src/app/base/selectors/machine/machine.js
- ui/src/app/base/selectors/machine/machine.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/ActionForm/ActionForm.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/ActionForm/ActionForm.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/ActionForm/__snapshots__/ActionForm.test.js.snap
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/CommissionForm/CommissionForm.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/CommissionForm/CommissionForm.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/DeployForm/DeployForm.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/DeployForm/DeployForm.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/SetPoolForm/SetPoolForm.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/SetPoolForm/SetPoolForm.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/SetPoolForm/SetPoolFormFields/SetPoolFormFields.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/SetZoneForm/SetZoneForm.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/SetZoneForm/SetZoneForm.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/TagForm/TagForm.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/TagForm/TagForm.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/TagForm/TagFormFields/TagFormFields.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/TestForm/TestForm.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/TestForm/TestForm.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/TestForm/TestFormFields/TestFormFields.test.js
- Display processing state for remaining actions in the take action menu.
- Open the machine list.
- Select some machines and use the take action menu to do different actions.
- Each action should show the processing status of the machines.
Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/1010.
> Take action statuses

- ui/src/__snapshots__/root-reducer.test.js.snap
- ui/src/app/App.test.js
- ui/src/app/base/actions/general/general.js
- ui/src/app/base/actions/general/general.test.js
- ui/src/app/base/components/DeprecationNotices/DeprecationNotices.js
- ui/src/app/base/components/DeprecationNotices/DeprecationNotices.test.js
- ui/src/app/base/components/DeprecationNotices/index.js
- ui/src/app/base/components/NotificationList/NotificationList.js
- ui/src/app/base/components/NotificationList/NotificationList.test.js
- ui/src/app/base/components/Section/Section.js
- ui/src/app/base/reducers/general/general.js
- ui/src/app/base/reducers/general/general.test.js
- ui/src/app/base/selectors/general/deprecationNotices.js
- ui/src/app/base/selectors/general/deprecationNotices.test.js
- ui/src/app/base/selectors/general/index.js
- ui/src/app/base/selectors/general/version.js
- ui/src/app/base/selectors/general/version.test.js
- ui/src/app/base/views/NotFound/NotFound.test.js
- ui/src/app/machines/views/Machines.js
- ui/src/app/machines/views/Machines.test.js
- ui/src/app/utils/index.js
- ui/src/app/utils/isVersionNewer.js
- ui/src/app/utils/isVersionNewer.test.js
- Added actions, reducers and selectors for fetching deprecation notices.
- Display deprecation notices in state at the top of NotificationList.
- Run this branch on bolla and check that a deprecation notice shows up at the top of the section.
Fixes #1008
> Add deprecation notices to NotificationList.

- ui/src/app/settings/views/Scripts/ScriptsUpload/ScriptsUpload.js
* Fixes incorrect props on FormCardButtons in ScriptsUpload.
@Caleb-Ellis @huwshimi we need to take extra care when removing props from components. For internal components, changing the API is fine, but we also need to check every usage of those components to ensure all of the call points are updated.
* Visit r/settings/scripts/commissioning/upload
* The submit button should render correctly and have an "Upload script" label.
> Fix props on FormCardButtons in ScriptsUpload.

- ui/package.json
* Enable [production react profiling](https://gist.github.com/bvaughn/25e6233aeb1b4f0cdb8d8366e54a3977) temporarily in production. 
I've created a [corresponding issue](https://github.com/canonical-web-and-design/MAAS-squad/issues/1887) for disabling profile before release.
> Enable production react profiling.

- legacy/src/app/directives/machines_table.js
- legacy/src/app/routes.js
- ui/src/app/machines/views/MachineList/MachineListTable/MachineListTable.js
This will be reverted, but I'd like to have parity on the machine listing for production performance profiling on bolla.
> Enable legacy machine listing route

- ui/src/app/base/components/TagSelector/TagSelector.js
- ui/src/app/base/components/TagSelector/TagSelector.test.js
- ui/src/app/base/components/TagSelector/__snapshots__/TagSelector.test.js.snap
- ui/src/app/base/components/TagSelector/_index.scss
- ui/src/app/base/reducers/machine/machine.js
- ui/src/app/base/reducers/machine/machine.test.js
- ui/src/app/base/reducers/resourcepool/resourcepool.js
- ui/src/app/base/reducers/resourcepool/resourcepool.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/MachinesProcessing/MachinesProcessing.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/MachinesProcessing/MachinesProcessing.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/OverrideTestForm/OverrideTestForm.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/OverrideTestForm/OverrideTestForm.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/SetPoolForm/SetPoolForm.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/SetPoolForm/SetPoolForm.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/SetPoolForm/SetPoolFormFields/SetPoolFormFields.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/TagForm/TagForm.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/TagForm/TagFormFields/TagFormFields.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/TestForm/TestForm.js
- ui/src/app/utils/redux.js
- Handle errors for the take action menu forms
- Using the take action menu do a bunch of actions that will fail, you should get errors displayed.
Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/984.
Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/1001.
> Handle errors in the take action forms

- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/ActionFormWrapper.js
- ui/src/app/machines/views/MachineList/MachineListTable/FabricColumn/FabricColumn.js
- ui/src/app/machines/views/MachineList/MachineListTable/FabricColumn/__snapshots__/FabricColumn.test.js.snap
- ui/src/app/machines/views/MachineList/MachineListTable/MachineListTable.js
- ui/src/app/machines/views/MachineList/MachineListTable/MachineListTable.test.js
- ui/src/app/machines/views/MachineList/MachineListTable/NameColumn/NameColumn.js
- ui/src/app/machines/views/MachineList/MachineListTable/NameColumn/NameColumn.test.js
- ui/src/app/machines/views/MachineList/MachineListTable/NameColumn/__snapshots__/NameColumn.test.js.snap
- ui/src/app/machines/views/MachineList/MachineListTable/PoolColumn/PoolColumn.js
- ui/src/app/machines/views/MachineList/MachineListTable/PoolColumn/PoolColumn.test.js
- ui/src/app/machines/views/MachineList/MachineListTable/ZoneColumn/ZoneColumn.js
- ui/src/app/machines/views/MachineList/MachineListTable/ZoneColumn/ZoneColumn.test.js
- ui/src/scss/_patterns_buttons.scss
- Disabled all machine checkbox if there are not machines in the list.
- Removed all instances of machine list checkboxes being disabled.
- Filter out zone and pool in-table actions if they can't be performed on the machine.
- Removed `p-button--link is-inline` margin so the "Update your selection" text doesn't look weird.
- Removed extra "." in override failed test message.
- Fixed wonky fabric test failed tooltip.
- Lock a machine
- Check that the in-table action for pool and zone have a message saying you can't change them
- Check that you can still select the machine and unlock it from the in-table action and global action menu.
- Select a bunch of machines that aren't all "Failed testing" and choose "Override failed testing" from the global take action menu.
- Check that the "Update …
> Fix machine list checkbox behaviour.

- ui/src/app/machines/views/MachineList/_index.scss
- Add indentation to machine rows that are in a group.
- Check the grouped machine borders are indented.
Fixes #1027
> Add indentation to grouped machine borders.

- ui/src/app/machines/views/MachineList/MachineListControls/MachineListControls.js
- ui/src/app/machines/views/MachineList/MachineListControls/MachineListControls.test.js
- Fixed regression in debounce PR where URL would not update when filters from the accordion were selected.
- Select/unselect some filters from the accordion and check that the URL is updated accordingly.
Fixes #1028
> Fix filter accordion URL update regression.

- ui/src/app/machines/views/MachineList/_index.scss
Setting an element with display table properties to `position: relative;` in Chrome is invalid. But, works in FF. 
* Run the UI in Chrome
* See that the borders render in the correct place
* Check it in FF and other browsers
* See that they continue to work
Fixes https://github.com/canonical-web-and-design/maas-ui/issues/1034
> Fix the table row borders in Chrome

- ui/src/app/base/components/DoubleRow/DoubleRow.js
- ui/src/app/machines/views/MachineList/MachineListTable/FabricColumn/FabricColumn.js
- ui/src/app/machines/views/MachineList/MachineListTable/FabricColumn/__snapshots__/FabricColumn.test.js.snap
- ui/src/app/machines/views/MachineList/MachineListTable/NameColumn/NameColumn.js
- ui/src/app/machines/views/MachineList/MachineListTable/NameColumn/__snapshots__/NameColumn.test.js.snap
- ui/src/app/machines/views/MachineList/MachineListTable/OwnerColumn/OwnerColumn.js
- ui/src/app/machines/views/MachineList/MachineListTable/OwnerColumn/__snapshots__/OwnerColumn.test.js.snap
- ui/src/app/machines/views/MachineList/MachineListTable/PoolColumn/PoolColumn.js
- ui/src/app/machines/views/MachineList/MachineListTable/PoolColumn/__snapshots__/PoolColumn.test.js.snap
- ui/src/app/machines/views/MachineList/MachineListTable/PowerColumn/PowerColumn.js
- ui/src/app/machines/views/MachineList/MachineListTable/PowerColumn/__snapshots__/PowerColumn.test.js.snap
- ui/src/app/machines/views/MachineList/MachineListTable/ZoneColumn/ZoneColumn.js
- ui/src/app/machines/views/MachineList/MachineListTable/ZoneColumn/__snapshots__/ZoneColumn.test.js.snap
- ui/src/app/machines/views/MachineList/_index.scss
- Add tooltips to the cell content in the machine list.
- View the machine list.
- Resize the window to different sizes and look for content that gets truncated.
- Check that the top and bottom rows of the cell content have tooltips .
Fixes: https://github.com/canonical-web-and-design/MAAS-squad/issues/1913.
> Add tooltips to truncated content

- legacy/src/app/controllers/pod_details.js
- legacy/src/app/controllers/pods_list.js
- legacy/src/app/partials/pod-details.html
- legacy/src/app/partials/pods-list.html
- Added LXD radio option to Add KVM form, so you can choose between virsh and LXD.
- Driveby - remove ability to select more than one storage pool when composing machines from LXD pod.
- Driveby - increase delay when hackily updating pod machine list with newly composed machine. When testing composing machines from a LXD pod it wouldn't show up sometimes
- Go to /kvm and select Add KVM from the top right
- Check that the form matches the [design](https://app.zeplin.io/project/5e538f1156434564ebb73903/screen/5ea30125603bc7b154e36085), noting that the copy will be added later.
- Go to /rsd and check that the form there remains as before.
- Go to the bolla lxd pod and compose machine
- Check that you can only choose one storage pool.
- Compose a machine and check that the pod machine list …
> Add LXD radio option to Add KVM form.

- legacy/package.json
- legacy/src/app/entry.js
- package.json
- proxy/package.json
- shared/package.json
- ui/package.json
- ui/src/app/App.js
* Rename packages to correctly use the `@canonical` org.
None, should build.
> Use @canonical org for package names.

- ui/src/app/base/actions/machine/machine.js
- ui/src/app/base/actions/machine/machine.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/CommissionForm/CommissionForm.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/CommissionForm/CommissionForm.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/CommissionForm/CommissionFormFields/CommissionFormFields.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/CommissionForm/CommissionFormFields/CommissionFormFields.test.js
- Added URL field to Commissioning form when selecting internet-test scripts.
- Select some machines and choose Commission from the action menu
- Choose an internet-connectivity script from Tests
- Check that a URL field for that test shows up below the script selector
- Submit the form and check that the network request includes:
``` json
{ "script_input": { "the-name-of-the-script": { "url" : "the-url-you-used" } } }
```
Fixes #1031
> Add URL field to Commissioning form when selecting internet-test scripts.

- legacy/package.json
- package.json
- ui/package.json
Set public access in publishConfig. 
Making running:
`yarn publish`
equivalent to 
`yarn publish --access public`
> Set public access in publishConfig.

- legacy/src/app/controllers/node_details_networking.js
- legacy/src/app/partials/node-details.html
- Fixed some incorrect markup that was making the edit form unusable if the machine had a tag.
- Fixed some incorrect logic that prevented link speeds and interface speeds to be updated in the dit interface form.
- Go to http://bolla.internal:5240/MAAS/#/machine/t4kwcq?area=network and try to edit the first interface. When you submit the form you should get an error about tags.
- Try to edit the link and interface speeds on the second interface. The form should submit but the values should not be updated.
- Pull this branch and attempt to do the same things on the same machine. Also try to add and remove tags. Everything should work.
Fixes #852 
[#1864241](https://bugs.launchpad.net/maas/+bug/1864241)
> Fix edit interface form not being able to edit tags/speeds.

- legacy/src/app/controllers/pods_list.js
- legacy/src/app/controllers/tests/test_pods_list.js
- legacy/src/app/partials/pods-list.html
- legacy/src/scss/tables/_patterns_table-pods.scss
- Added OS info to LXD pods in pod list
- Go to the pod list and check that LXD pods show the OS info, and the KVM pods should show "Unknown"
Fixes #1003
> Add OS info to LXD pods in pod list.

- ui/src/app/machines/search.js
- ui/src/app/machines/search.test.js
- Don't store the in:selected/!selected state in the URL.
- Go to the machine list and type in:selected in the search box. It should not be reflected in the URL.
Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/1057.
> Don't persist the selected state in the URL

- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/ActionForm/ActionForm.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/ActionForm/ActionForm.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/CommissionForm/CommissionForm.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/DeployForm/DeployForm.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/OverrideTestForm/OverrideTestForm.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/SetPoolForm/SetPoolForm.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/SetZoneForm/SetZoneForm.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/TagForm/TagForm.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/TestForm/TestForm.js
- ui/src/app/machines/components/HeaderStrip/HeaderStrip.js
- ui/src/app/machines/components/HeaderStrip/HeaderStrip.test.js
- ui/src/app/machines/search.js
- ui/src/app/machines/search.test.js
- ui/src/app/machines/views/MachineList/MachineList.js
- ui/src/app/machines/views/MachineList/MachineList.test.js
- ui/src/app/machines/views/MachineList/MachineListControls/MachineListControls.js
- ui/src/app/machines/views/MachineList/MachineListControls/MachineListControls.test.js
- ui/src/app/machines/views/MachineList/MachineListTable/MachineListTable.js
- ui/src/app/machines/views/MachineList/MachineListTable/MachineListTable.test.js
- ui/src/app/machines/views/Machines.js
- ui/src/app/machines/views/Machines.test.js
- Filter selected machines when opening a take action form.
- Select a machine that can be commissioned.
- Using the take action menu open the form.
- The machine list should now be filtered by in:selected.
- Submit the form.
- The machine should transition to commissioning but the update-your-selection warning should not appear (like https://user-images.githubusercontent.com/17980375/80403010-c0e6d480-88b6-11ea-813b-8917aa9eb479.png).
- Click the machine, group or all machines checkbox, the machine list should no longer be filtered
Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/1042.
Fixes: https://github.com/canonical-web-and-design/MAAS-squad/issues/1897.
> Filter select when taking action

- ui/src/app/base/components/FormCardButtons/FormCardButtons.js
- ui/src/app/base/components/Section/Section.js
- ui/src/app/base/components/Section/__snapshots__/Section.test.js.snap
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/ActionForm/__snapshots__/ActionForm.test.js.snap
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.js
- ui/src/app/machines/components/HeaderStrip/HeaderStrip.js
- ui/src/app/machines/components/HeaderStrip/TakeActionMenu/TakeActionMenu.js
- ui/src/app/machines/views/MachineList/MachineListControls/FilterAccordion/_index.scss
- ui/src/app/machines/views/MachineList/MachineListTable/MachineListTable.js
- ui/src/scss/_utilities.scss
- ui/src/scss/_vanilla-overrides.scss
- Fixed various styling errors on small screens
- Moved deploy KVM link inline with checkbox
- Increased margins underneath action form buttons
- Open deploy form and check that there is more space underneath the submit button
- Check that the KVM link is inline with the checkbox
- Resize to small screen and check that:
- the machine list header checkbox isn't wrapped
- the filter accordion is full width
- when you open the take action menu the tab chevron doesn't show up on top
Fixes canonical-web-and-design/MAAS-squad#1888
Fixes canonical-web-and-design/MAAS-squad#1889
Fixes canonical-web-and-design/MAAS-squad#1893
Fixes canonical-web-and-design/MAAS-squad#1895
Fixes canonical-web-and-design/MAAS-squad#1896
> Improve machine list page styling on smaller screens.

- ui/src/app/base/components/ContextualMenu/ContextualMenu.js
- ui/src/app/base/components/ContextualMenu/ContextualMenuDropdown/ContextualMenuDropdown.js
- ui/src/app/base/components/ContextualMenu/ContextualMenuDropdown/ContextualMenuDropdown.test.js
- ui/src/app/base/components/ContextualMenu/ContextualMenuDropdown/__snapshots__/ContextualMenuDropdown.test.js.snap
- ui/src/app/base/components/ContextualMenu/ContextualMenuDropdown/index.js
- ui/src/app/base/components/ContextualMenu/__snapshots__/ContextualMenu.test.js.snap
- ui/src/app/base/hooks.js
- Update the position of contextual menus when the window is resized.
- View the machine list.
- Click on the take action menu or an in table action menu.
- Resize your window.
- The menu should adjust it's position.
Fixes: https://github.com/canonical-web-and-design/maas-squad/issues/1909.
> Move contextual menus when the window is resized

- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/OverrideTestForm/OverrideTestForm.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/OverrideTestForm/OverrideTestForm.test.js
- Updated warning text to describe why machines could be in Failed testing with 0 failed tests.
- Updated form spacing.
- Choose some failed testing machines that have 0 failed tests.
- Check that the message displayed is different and the suppress tests checkbox does not show.
Fixes canonical-web-and-design/MAAS-squad#1902
> Update OverrideFailedTestForm formatting and warning text.

- ui/src/app/machines/components/HeaderStrip/HeaderStrip.js
- ui/src/app/machines/views/Machines.test.js
- Close action form when navigating away from /machines
- Select some machines and choose an action
- Click to somewhere else that still shows the machine header (e.g. pools, add machine)
- Check that the action form closes
Fixes canonical-web-and-design/MAAS-squad#1906
> Close action form when navigating away from /machines.

- ui/src/app/machines/components/HeaderStrip/HeaderStrip.js
- ui/src/app/machines/components/HeaderStrip/HeaderStrip.test.js
- Exploration related to https://github.com/canonical-web-and-design/MAAS-squad/issues/1891 and https://github.com/canonical-web-and-design/MAAS-squad/issues/1894
- Changed machines count to read:
- None selected: "Y machines available"
- Some selected: "X of Y machines selected" - this is a link that filters to selected when clicked
- All selected: "All machines selected"
- See that the text next to machines reads "Y machines available"
- Select some machines and check that the text is now a "button" link that reads "X of Y machines selected"
- Click the button and check the machine list is filtered to selected machines
- Remove filter, select all machines and check that the text reads "All machines selected"
Fixes canonical-web-and-design/MAAS-squad#1891
Fixes …
> Combine available and selected machine strings.

- ui/package.json
- ui/src/app/base/components/Section/_index.scss
- ui/src/scss/_vanilla-overrides.scss
- yarn.lock
- Upgrade to Vanilla 2.10.1.
- Fixed sidebar overlapping issue.
- Removed Vanilla override for https://github.com/canonical-web-and-design/vanilla-framework/issues/3027.
- Have a poke around and make sure everything looks OK.
- Visit /MAAS/r/settings/users/add
- Check that the selected sidebar item doesn't overlap the card shadow.
> Upgrade Vanilla to 2.10.1

- ui/src/app/base/hooks.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/ActionForm/ActionForm.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/ActionForm/ActionForm.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/ActionForm/__snapshots__/ActionForm.test.js.snap
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/ActionFormWrapper.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/ActionFormWrapper.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/CommissionForm/CommissionForm.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/CommissionForm/CommissionForm.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/CommissionForm/CommissionFormFields/CommissionFormFields.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/DeployForm/DeployForm.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/DeployForm/DeployForm.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/OverrideTestForm/OverrideTestForm.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/OverrideTestForm/OverrideTestForm.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/SetPoolForm/SetPoolForm.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/SetPoolForm/SetPoolForm.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/SetPoolForm/SetPoolFormFields/SetPoolFormFields.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/SetZoneForm/SetZoneForm.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/SetZoneForm/SetZoneForm.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/TagForm/TagForm.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/TagForm/TagForm.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/TagForm/TagFormFields/TagFormFields.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/TestForm/TestForm.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/TestForm/TestForm.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/TestForm/TestFormFields/TestFormFields.test.js
- Prevent the "update your selection" notice from appearing once machines have begun to be processed. This was causing a bug as when the machines begin to be changed they can change the allowable actions from that machine, resulting in that machine being shown.
- Selecting a number of new machines (at least 5).
- Using the take action menu select "Commission" and submit the form.
- The machines should transition to commissioning and the "update your selection" warning should not appear.
- You might have to do this a few times (you can abort once they transition to commissioning) to be satisfied this is fixed.
Fixes: https://github.com/canonical-web-and-design/MAAS-squad/issues/1897.
> Fix processing state

- ui/src/app/machines/views/MachineList/MachineListTable/MachineListTable.js
- ui/src/app/machines/views/MachineList/MachineListTable/MachineListTable.test.js
- ui/src/scss/_patterns_forms.scss
- Added a new state to machine list checkboxes that indicates whether some (but not all) machines in a group are selected.
- Changed the checkbox functionality so that it actually makes sense with the new state, i.e. if a checkbox is checked (mixed or not) unchecking it will also uncheck all the machines in that group.
- Select some machines in different groups and check that the checkboxes indicate whether some or all machines in groups are selected.
Fixes canonical-web-and-design/MAAS-squad#1907
> Add mixed selection state to machine list checkboxes.

- ui/src/app/base/components/TagSelector/_index.scss
- Added margin back to tag selector input, subtracted it from tag selector dropdown.
- Select some machines and choose "Tag" from the action dropdown
- Resize screen to small and check there is space between the tag selector and the submit button
Fixes canonical-web-and-design/MAAS-squad#1910
> Fix tag selector margin.

- ui/src/app/base/selectors/controller/controller.js
- ui/src/app/base/selectors/device/device.js
- ui/src/app/base/selectors/dhcpsnippet/dhcpsnippet.js
- ui/src/app/base/selectors/general/osInfo.js
- ui/src/app/base/selectors/general/version.js
- ui/src/app/base/selectors/licensekeys/licensekeys.js
- ui/src/app/base/selectors/machine/machine.js
- ui/src/app/base/selectors/notification/notification.js
- ui/src/app/base/selectors/packagerepository/packagerepository.js
- ui/src/app/base/selectors/resourcepool/resourcepool.js
- ui/src/app/base/selectors/scriptresults/scriptresults.js
- ui/src/app/base/selectors/scripts/scripts.js
- ui/src/app/base/selectors/subnet/subnet.js
- ui/src/app/base/selectors/user/user.js
- ui/src/app/preferences/selectors/token/token.js
- Update all selectors that are fetching and manipulating state to use `createSelector`.
- This resulted in an up to about 50ms improvement on the first render of the machine list and went from 11 rerenders to 4.
- These should all be internal changes to the selectors so the tests should pass, but you could poke around the machine list/prefs/settings to make sure everything works.
Fixes: https://github.com/canonical-web-and-design/maas-squad/issues/1872.
> Use createSelector for all selectors that can use it

- legacy/src/app/directives/pod_parameters.js
- Changed LXD KVM password input to type="password".
- Go to /kvm and open the Add KVM form
- Select LXD type and check that the password input has `type="password"`
Fixes canonical-web-and-design/MAAS-squad#1920
[lp#1876921](https://bugs.launchpad.net/maas/+bug/1876921)
> Change LXD KVM password input to type="password".

- legacy/package.json
- legacy/src/app/controllers/node_details_networking.js
- legacy/src/app/partials/directives/release-options.html
- legacy/src/app/partials/node-details.html
- legacy/src/app/partials/nodes-list.html
- package.json
- ui/package.json
- yarn.lock
- Backported https://github.com/canonical-web-and-design/maas-ui/pull/1062 and https://github.com/canonical-web-and-design/maas-ui/pull/1063
- Bump version to 0.2.10
- Run this branch using karura (not bolla)
- Check that you can edit tags and link speeds on edit interface forms
- Check that the machine details and device/controller lists are not just warning icons
Fixes #1071
> Release 0.2.10

- legacy/src/app/partials/script-results-list.html
- Fixed incorrect markup in script history expanding cell. I'm fairly certain it's the cause of this bug that only happens in production: https://bugs.launchpad.net/maas/+bug/1877685
- See that the code is right. Once this is merged and bolla is updated we can check if the bug was actually fixed.
[lp#1877685](https://bugs.launchpad.net/maas/+bug/1877685)
> Fix markup in script history expanding cell.

- legacy/package.json
- legacy/src/app/controllers/master.js
- legacy/src/app/controllers/pods_list.js
- root/package.json
- ui/src/app/App.js
- ui/src/app/machines/views/MachineList/MachineListTable/NameColumn/NameColumn.js
- ui/src/app/machines/views/MachineList/MachineListTable/NameColumn/__snapshots__/NameColumn.test.js.snap
- ui/src/index.js
- yarn.lock
* Ensure Machine Listing -> Machine Details links do not trigger a full page refresh.
* Fix issue where react router is unable to observe changes to `window.history.pushState` by listening for singleSPA popstate events, and manually calling `history.replace`. The way this manifest previously, navigating from an angularjs route to a react route would always load the last react route in memory before the app was unmounted, regardless of the actual route.
* Driveby fix for intermittent crash on pods list.
* Upgrade to singlespa 5.5.0.
* Bootstrap both maas-ui-legacy and maas-ui (e.g. navigate to /MAAS/#/devices and /MAAS/r/machines).
* Ensure navigating away from machine listing and back again does not refetch machines (state is preserved).
* Click a node from the machine listing and ensure …
> Fix machine details links and routing.

- ui/src/single-spa-entry.js
* Add root `ErrorBoundary`. In actual practice, the user is very unlikely to see this as we _already_ implement ErrorBoundaries further up the component hierarchy, which are more likely to catch first, but this does suppress the annoying warning from singleSpaReact.
* Load the app, the error boundary warnings should no longer appear.
Fixes canonical-web-and-design/MAAS-squad#2002
> Add root error boundary.

- .circleci/config.yml
- Fixed how `maas init` works in the latest version of the MAAS snap, where `mode` is now a positional argument.
- Cypress tests should pass. At the very least, MAAS should get init-ed
> Fix maas init in CircleCI.

- ui/src/app/machines/views/AddMachine/AddMachineFormFields/AddMachineFormFields.js
- ui/src/app/utils/formatMacAddress.js
- ui/src/app/utils/formatMacAddress.test.js
- ui/src/app/utils/index.js
- Auto-format the MAC address field in the Add machine form.
- Go to /MAAS/r/machines/add
- Type into the MAC address field and check that separators are spliced in automatically
Fixes #1112
> Auto-format MAC address field.

- legacy/src/app/controllers/pod_details.js
- legacy/src/app/controllers/tests/test_node_details_storage.js
- legacy/src/app/controllers/tests/test_pod_details.js
- legacy/src/app/directives/maas_obj_form.js
- legacy/src/app/directives/tests/test_maas_obj_form.js
- legacy/src/app/filters/format_bytes.js
- legacy/src/app/filters/tests/test_format_bytes.js
- legacy/src/app/partials/pod-details.html
- Improved validation of compose machine form
- Improved `maasObjErrors` notification styling
- Hide "Compose" button if compose form is open
- Changed formatBytes for GB to return 3 significant figures with truncated zeroes, i.e. a value of 7620000000 bytes will return "7.62 GB" instead of "8 GB", 7600000000 bytes will return "7.6 GB" instead of "8 GB"
- Go to a KVM details page and open the compose form
- Check that the Compose button disappears
- Check that the form can be submitted by default (unless there is less than 8GB free on the first storage pool, in which case drop the request lower)
- Check that the form is disabled if you request too many or 0 cores
- Check that the form is disabled if you request too much or 0 RAM
- Check that the form is disabled if you request 0 storage …
> Fix KVM details QA issues.

- root/package.json
- root/src/index.ejs
- root/webpack.common.js
- root/webpack.dev.js
- root/webpack.prod.js
- yarn.lock
* Only set publicPath in dev, and make `root-application.js` relative for production.
* Split root webpack config for dev/prod.
* Ensure app works in development.
> Make root app relative.

- package.json
- ui/config-overrides.js
- ui/package.json
- ui/src/app/App.js
- ui/src/index.js
- yarn.lock
* Use `style-loader` rather than `mini-css-extract-plugin` (the CRA default) in production. This is required as we no longer have a static file to serve the extracted css build from with singlespa.
Sorry, not that easy. In a MAAS VM/Container from your `maas` root directory...
```
git config --file=.gitmodules submodule.src/maasui/src.url https://github.com/squidsoup/maas-ui.git
git config --file=.gitmodules submodule.src/maasui/src.branch fix-prod-css-react
git submodule sync
git submodule update --init --recursive --remote
cd src/maasui/
make
```
(from root), run MAAS. You should see the react app with css rendering correctly.
> Use style-loader in production build.

- legacy/src/app/controllers/pod_details.js
- legacy/src/app/controllers/tests/test_pod_details.js
- legacy/src/app/partials/pod-details.html
- legacy/src/scss/_patterns_option-selector.scss
- Fixed interface constraint logic in VM host compose form.
- Slightly updated subnet list styling to be less space-y.
- Go to the KVM details page of a KVM that has attached VLANs (e.g. bolla LXD) and open the machine compose dropdown.
- Confirm that you can still compose a machine with default interface constraints. Check the websocket request has `params.interfaces : ""`.
- Open the compose dropdown again and add a couple of custom interface constraints. Check that the first available subnet is already selected by default, and the IP address field has a placeholder saying "Leave empty to auto-assign"
- For the first interface just select a subnet, and for the second select a subnet and enter an IP address.
- Submit the form and check that the websocket request correctly adheres to [the …
> Fix interface constraint construction in VM host compose form.

- ui/src/app/App.js
* Call `history.replace` on full path requested, not just subpath used for comparison in the singleSpa `popstate` handler.
* Ensure links from angular -> react preserve the full path, rather than redirecting to the subroute.
> Redirect to full route requested, not subpath.

- legacy/src/app/controllers/pod_details.js
- legacy/src/app/controllers/tests/test_pod_details.js
- legacy/src/app/directives/pod_parameters.js
- legacy/src/app/directives/tests/test_pod_parameters.js
- legacy/src/app/partials/pod-details.html
- Backend now provides core, memory and storage defaults for pod types. Now they're being used in the VM compose form - the form is autofilled with defaults, and clearing them displays the default as a placeholder.
- Added overcommit sliders for LXD hosts.
- Tidied up websocket request preprocessor. It was originally sending a bunch of irrelevant garbage - now it's a bit more explicit what's actually being sent.
- Changed memory help text from GiB to MiB - it seemed weird for the form value (and the backend) to be in MiB and to have to calculate from MiB to GiB and back, when we could just use MiB.
- **Note:** Something has happened with bolla and now I can't seem to compose machines or edit configuration for either the LXD or virsh host - the requests just hang until they time out. This …
> Autofill VM compose form with defaults + add overcommit sliders for LXD hosts.

- package.json
- ui/config-overrides.js
- ui/package.json
- ui/src/index.js
- yarn.lock
- Load the UI styles from a stylesheet in production.
- In a local MAAS run the following:
```shell
git config --file=.gitmodules submodule.src/maasui/src.url https://github.com/huwshimi/maas-ui.git
git config --file=.gitmodules submodule.src/maasui/src.branch external-ui-css
git submodule sync
git submodule update --init --recursive --remote
make clean-ui
make ui
```
You may have to use `SKIP_PREFLIGHT_CHECK=true make ui` like I did.
Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/1157.
> External prod stylesheet

- shared/src/components/Header/Header.js
- Don't append the tag manager script if it already exists
- Run the app in dev or production.
- If in dev you'll need to remove `!debug` from this line: https://github.com/canonical-web-and-design/maas-ui/blob/master/shared/src/components/Header/Header.js#L40.
- Switch between the react and angular apps a few times.
- Inspect the header.
- You should only see one script tag for google tag manager.
Fixes https://github.com/canonical-web-and-design/maas-ui/issues/1163.
> Fix duplicate tag manager scripts

- ui/src/app/Routes.js
- ui/src/app/base/selectors/pod/pod.js
- ui/src/app/base/selectors/pod/pod.test.js
- ui/src/app/kvm/views/KVM.js
- ui/src/app/kvm/views/KVMDetails/KVMDetails.js
- ui/src/app/kvm/views/KVMDetails/KVMDetails.test.js
- ui/src/app/kvm/views/KVMDetails/index.js
- ui/src/app/kvm/views/KVMList/KVMList.js
- ui/src/app/kvm/views/KVMList/KVMList.test.js
- ui/src/app/kvm/views/KVMList/index.js
- ui/src/scss/_patterns_tabs.scss
- Added wrapper components:
- KVM, which at the moment just handles routing between list and details
- KVMList, a basic Vanilla table with links to details
- KVMDetails, a headerstrip with tabs between composed machines and configuration 
- Added routes KVM react pages
- Go to /MAAS/r/kvm and check that the list of pod names is correct
- Click on the links and check that they take you to the pod details pages
- Check you can go between composed machines count and configuration tabs
- Navigate directly to /MAAS/r/kvm, /MAAS/r/kvm/<pod.id> and /MAAS/r/kvm/<pod.id>/edit and check that the pages load properly
Fixes canonical-web-and-design/MAAS-squad#1946
> Set up routes and wrapper components for KVM react rebuild.

- legacy/src/app/entry.js
- legacy/src/app/routes.js
- legacy/src/app/services/tests/test_region.js
- root/src/root-application.js
Add redirect for legacy hash-based routes, with a fall through to the machine listing.
* Visit a deprecated route such as `/MAAS/#/controllers`, you should be redirected to `/MAAS/l/controllers`. 
* Visit an invalid route such as `/MAAS/l/foo`, you should be redirected to the machine listing.
> Add hashroute redirect with machine listing fallthrough.

- ui/src/app/machines/views/Machines.js
- ui/src/app/machines/views/Machines.test.js
- ui/src/app/pools/views/Pools.js
- ui/src/app/pools/views/Pools.test.js
- When clicking on the link to the machines in a pool the filters were not being updated.
- Visit the pool page.
- Click the link to view the machines in the pool.
- The machine list should appear with only the machines in the pool (and the filter should be in the search box).
Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/1181.
https://bugs.launchpad.net/maas-ui/+bug/1881247
> Update the filters when clicking on a pool link

- package.json
- proxy/package.json
- proxy/ui.js
- ui/package.json
- ui/src/index.js
- yarn.lock
- Run the UI in standalone mode for dev.
- Run `dotrun ui` or `yarn ui`.
- Load the url as you normally wood.
- You should see the react app.
> Run the ui as a standalone app

- ui/src/app/base/components/Meter/Meter.js
- ui/src/app/base/components/Meter/Meter.test.js
- ui/src/app/base/components/Meter/__snapshots__/Meter.test.js.snap
- ui/src/app/base/components/Meter/_index.scss
- ui/src/app/base/components/Meter/index.js
- ui/src/app/kvm/views/KVMList/KVMList.js
- ui/src/app/kvm/views/KVMList/KVMList.test.js
- ui/src/app/utils/formatBytes.js
- ui/src/app/utils/formatBytes.test.js
- ui/src/app/utils/formatSpeedUnits.js
- ui/src/scss/index.scss
- Built Meter component and used it in the KVM list table. In the near future we'll do the same thing we did with the machine list and use MainTable with individual cell components. For now I'm just using a basic implementation to show how the meter looks.
- Updated `formatBytes` util to be able to handle binary units (e.g. "MiB", "GiB" etc).
- Go to /MAAS/r/kvm and check that the table shows simple meter components with the used v free cpu/memory/storage.
- Add this Row below the KVMList Row in KVMList.js to see some different ways you can use the component:
``` js
<Row>
<Col size="6">
<h4>Default</h4>
<Meter data={[{ key: "default", value: 1 }]} max={3} />
<h4>Over</h4>
<Meter data={[{ key: "default-over", value: 3 }]} max={1} />
<h4>Labels</h4>
<Meter
data={[
{ key: "default-label-1", …
```
> Build Meter component and use in KVM list table.

- legacy/src/app/partials/node-details.html
Add `p-strip` to the container of the storage content
* Go to a machine
* Click storage
* See there is a little more space top and bottom of the storage tables
| Before  | After |
| ------------- | ------------- |
| ![Screenshot_2020-06-02 MAAS UI](https://user-images.githubusercontent.com/1413534/83514562-c645c900-a4cb-11ea-823c-94137c39db47.png)  | ![Screenshot_2020-06-02 Machines bolla MAAS](https://user-images.githubusercontent.com/1413534/83514572-cd6cd700-a4cb-11ea-8b87-d5bf1e29919d.png)  |
> Apply some padding the to storage view

- legacy/src/app/controllers/pods_list.js
- legacy/src/app/partials/pods-list.html
- Added Beta label to LXD option when adding VM host.
- Added a link to VM host docs to "Add KVM" form
- Go to /MAAS/l/kvm and click "Add KVM"
- Check that "virsh" is selected by default, and next to "LXD" is a Beta label
- Check that the link takes you to the correct docs page about VM hosting
Fixes #1187
> Add Beta label to LXD option when adding VM host.

- root/src/scss/_settings.scss
- ui/src/app/base/components/Section/Section.js
- ui/src/app/base/components/Section/__snapshots__/Section.test.js.snap
- Hardcoded fix from https://github.com/canonical-web-and-design/vanilla-framework/pull/3106 in root css
- Increased Section sidebar width to col-3 and removed flex styling as it was removing gutter widths
- Go to /MAAS/r/settings and check that you can see the hover/active state on the sidebar nav items.
- Do the same at /MAAS/r/account/prefs
Fixes #1175
> Fix settings sidebar looking disabled.

- legacy/src/app/partials/layout.html
- legacy/webpack.common.js
- legacy/webpack.dev.js
- legacy/webpack.prod.js
- package.json
- root/.eslintrc
- root/src/index.ejs
- root/src/root-application.js
- root/webpack.common.js
- root/webpack.dev.js
- root/webpack.prod.js
- ui/package.json
- ui/src/index.js
- yarn.lock
- Add hashes to the built file names to help with updating caches.
- Load css files in the single-spa template to improve app loading.
- Run `dotrun`, the app should load normally for the react/angular apps.
- In a local MAAS run the following:
```shell
git config --file=.gitmodules submodule.src/maasui/src.url https://github.com/huwshimi/maas-ui.git
git config --file=.gitmodules submodule.src/maasui/src.branch build-hashes
git submodule sync
git submodule update --init --recursive --remote
make clean-ui
make ui
```
You may have to use `SKIP_PREFLIGHT_CHECK=true make ui` like I did.
- The app should load normally for the react/angular apps.
- There should also be a small improvement to the content flash when switching between apps.
> Build hashes

- legacy/src/app/controllers/master.js
- legacy/src/app/controllers/node_details.js
- legacy/src/app/directives/error_overlay.js
- legacy/src/app/services/error.js
- yarn.lock
- Hide the error overlay when navigating away.
- Visit an entity url that doesn't exist, e.g. /MAAS/l/device/bob.
- You should see an error screen.
- In the header click on another angular route.
- The error screen should close and you should see the page you clicked on.
Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/1185.
https://bugs.launchpad.net/maas/+bug/1881555
> Hide the error overlay when navigating away

- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/OverrideTestForm/OverrideTestForm.js
- ui/src/app/machines/views/MachineList/MachineListTable/FabricColumn/FabricColumn.js
- ui/src/app/machines/views/MachineList/MachineListTable/FabricColumn/__snapshots__/FabricColumn.test.js.snap
- ui/src/app/machines/views/MachineList/MachineListTable/NameColumn/NameColumn.js
- ui/src/app/machines/views/MachineList/MachineListTable/NameColumn/__snapshots__/NameColumn.test.js.snap
- ui/src/app/machines/views/MachineList/MachineListTable/ZoneColumn/ZoneColumn.js
- ui/src/app/machines/views/MachineList/MachineListTable/ZoneColumn/__snapshots__/ZoneColumn.test.js.snap
- ui/src/app/settings/views/Dhcp/DhcpTarget/DhcpTarget.js
- ui/src/app/settings/views/Dhcp/DhcpTarget/__snapshots__/DhcpTarget.test.js.snap
- Fixed a couple of remaining relative links in the react codebase
- For each case check the link takes you to the right place and the page does not refresh:
- Machine list > Machine FQDN should take you to `/MAAS/l/machine/<system_id>`,
- Machine list > Machine MAC should take you to `/MAAS/l/machine/<system_id>`,
- Machine list > Machine Zone should take you to `/MAAS/l/zone/<zone_id>`,
- Machine list > Machine Fabric should take you to `/MAAS/l/fabric/<fabric_id>`,
- Settings > DHCP snippets "Applies to" field of node snippets should take you to the right place
Fixes #1197 
https://bugs.launchpad.net/maas/+bug/1881954
> Fix remaining relative links in react codebase.

- legacy/src/app/partials/zones-list.html
- Fixed AZs heading tooltip. I think `.p-tooltip--btm-left` must have been deprecated then removed in a previous version of vanilla.
- Go to /MAAS/l/zones and check that hovering over the question mark icon shows a tooltip
Fixes #1199 
[lp#1881262](https://bugs.launchpad.net/maas/+bug/1881262)
> Fix AZs heading tooltip.

- legacy/src/app/controllers/networks_list.js
- legacy/src/app/controllers/node_details.js
* Set DHCP status to "Relayed via ##" instead of "No DHCP" when DHCP is relayed, both in the node and the network pages
In a machine with two fabrics (e.g. fabric-0 and fabric-1) with a different subnet each:
* Enable DHCP in fabric-0's vlan page
* Enable DHCP relay in fabric-1's vlan page
* /MAAS/#/networks?by=fabric should show "Relayed via fabric-0.untagged" for fabric-1 instead of "No DHCP"
* After deploying a machine with an interface on fabric-1, the machine should show "Relayed via fabric-0.untagged" instead of "No DHCP" in /MAAS/#/machine/$id
Fixes #1173 .
lp#1879979
> Fix DHCP status for DHCP relay (#1173)

- legacy/src/app/partials/node-details.html
- Fixed (added? It didn't seem to exist at all) remove device interface expanded panel.
- Go to the network tab of a device
- Add an interface with a random MAC address
- Click the actions dropdown for that interface, select "Remove Physical..." and check that the expanded panel shows
- Check that you can successfully cancel and perform the action
Fixes #1191
> Fix remove device interface expanded panel.

- ui/src/app/settings/views/Scripts/ScriptsList/ScriptsList.js
scripts history order is descending now.
so slice(0) access latest one
now, it shows always the oldest one after script created. even if script is updated with cli
* Itemised list of what was changed by this PR.
* Steps for QA.
Fixes # .
Related Launchpad maas issue in the form `lp#1879986`.
> scripts history order is descending now.

- legacy/src/scss/_patterns_cores-chart.scss
- Fixed cores chart when number of cores is above 32 and background changes to little dots. Now the dots file is found at the right place.
- Go to /MAAS/#/kvm and check the cores chart works when a KVM has more than 32 cores (bolla-kvm has 8 cores with 10x overcommit = 80 cores) 
Fixes #1202
[lp#1881892](https://bugs.launchpad.net/maas/+bug/1881892)
Before:
After:
> 2.7: Fix cores chart when over 32 cores.

- legacy/src/app/controllers/master.js
- root/src/index.ejs
- Fixed legacy window titles.
- Renamed root title from "MAAS UI" to "MAAS". I don't think we use "MAAS UI" anywhere else so may as well keep it consistent.
- Navigate around the legacy angular pages and check that the window title updates correctly.
Fixes #1204
> Fix legacy window titles.

- ui/src/app/base/components/FormCardButtons/FormCardButtons.js
- ui/src/app/base/components/FormCardButtons/FormCardButtons.test.js
- ui/src/app/base/components/FormikForm/FormikForm.js
- ui/src/app/base/components/FormikFormContent/FormikFormContent.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/ActionForm/ActionForm.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/ActionForm/ActionForm.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/ActionForm/__snapshots__/ActionForm.test.js.snap
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/CommissionForm/CommissionForm.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/CommissionForm/CommissionForm.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/DeployForm/DeployForm.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/DeployForm/DeployForm.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/OverrideTestForm/OverrideTestForm.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/OverrideTestForm/OverrideTestForm.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/SetPoolForm/SetPoolForm.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/SetPoolForm/SetPoolForm.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/SetZoneForm/SetZoneForm.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/SetZoneForm/SetZoneForm.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/TagForm/TagForm.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/TagForm/TagForm.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/TestForm/TestForm.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/TestForm/TestForm.test.js
- ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/utils/index.js
- ui/src/app/machines/components/HeaderStrip/hooks.js
- Added processing labels underneath action forms after the action is submitted. Originally the plan was to build [design #4](https://app.zeplin.io/project/5ec29f2c86bde54724294779/screen/5ec55a4901aaac48362d04a2) but it wasn't clear how to handle errors, so instead we've gone with [design #2](https://app.zeplin.io/project/5ec29f2c86bde54724294779/screen/5ec29f5940b7c5315462141b).
- Select a bunch of machines and perform an action.
- Check that a processing label shows up underneath the action button, indicating how many machine actions have received an OK from the server.
Fixes #1148 
The copy of the processing labels can be found in the JS snippet below. The message is slightly different for 1 vs multiple machines, e.g. "Tagging machine..." vs "Tagging 1 of 4 machines...". Also I've …
> Add processing labels to machine list action forms.

- ui/src/app/base/components/TableDeleteConfirm/TableDeleteConfirm.js
- ui/src/app/base/components/TableDeleteConfirm/__snapshots__/TableDeleteConfirm.test.js.snap
- ui/src/app/settings/views/Scripts/ScriptsUpload/ScriptsUpload.js
- ui/src/app/settings/views/Scripts/ScriptsUpload/ScriptsUpload.test.js
Add application/x-shellscript mimetype to fileupload accept.
To be backported to 2.8 branch.
Upload a shellscript (from a linux desktop) e.g. MAAS/r/settings/scripts/testing/upload
Fixes #1217 
[lp#1882313](https://bugs.launchpad.net/maas/+bug/1882313)
> Add application/x-shellscript mimetype to fileupload accept.

- ui/src/app/settings/views/Scripts/ScriptsUpload.js
- ui/src/app/settings/views/Scripts/ScriptsUpload.test.js
* Accept script uploads with mimetype application/x-shellscript. (This is a backport of https://github.com/canonical-web-and-design/maas-ui/pull/1223)
Upload a shellscript (from a linux desktop) e.g. MAAS/r/settings/scripts/testing/upload
Fixes #1217
lp#1882313
> Accept script uploads with mimetype application/x-shellscript.

- legacy/src/app/partials/node-details.html
- Renamed "Containers" tab to "Instances" to generalise the fact that LXD can host both containers and VMs.
- Go to the machine details page of a machine with devices (there should be at least one in a `make sampledata`'d local MAAS)
- Check that there is a tab that says "Instances" instead of "Containers"
Fixes #1218 
[lp#1881664](https://bugs.launchpad.net/maas/+bug/1881664)
> Rename "Containers" tab in machine details page to "Instances".

- ui/src/app/base/reducers/machine/machine.js
- ui/src/app/base/reducers/machine/machine.test.js
- ui/src/app/utils/redux.js
- ui/src/app/utils/redux.test.js
In the event that the server erroneously attempts to create an entity that already exists in state (e.g. a machine), ensure that the entity is updated in state instead.
Point maas-ui at a local maas snap. Restart the maas service (`sudo snap restart maas.supervisor`), wait a bit and you should not see duplicate machines in the machine list.
Relevant issue #1211 (will not close until websocket fix has landed).
[lp#1881275](https://bugs.launchpad.net/maas-ui/+bug/1881275) (note, while this change should effectively fix this bug, the UI still needs to refresh state when the websocket disconnects which will be addressed in a later branch).
> Update state entity on CREATE_<MODEL>_NOTIFY if exists.

- legacy/src/app/bootstrap.js
- ui/src/app/base/reducers/status/status.js
- ui/src/app/base/reducers/status/status.test.js
- ui/src/app/base/sagas/websockets.js
- ui/src/app/base/sagas/websockets.test.js
- ui/src/index.js
- ui/src/root-saga.js
- ui/src/websocket-client.js
- ui/src/websocket-client.test.js
- Connect to an existing websocket connection in the React client.
- Load a react page with the network details open in the dev tools.
- Switch between the react and angular clients a few times.
- The app should not reopen a websocket for the react client (it will for the angular client).
First half of: https://github.com/canonical-web-and-design/maas-ui/issues/1203.
> Fix multiple react websockets

- legacy/src/app/partials/node-events.html
The node events full history view has misleading text, suggesting that all events are within the last 1 day by default. Instead it should display an event total, and make it clear that the page is showing events for the last n days.
n/a, but if it helps understand the problem to see it in context, have a look at a machine's "full history" page e.g. MAAS/l/machine/machine-id/events
Fixes canonical-web-and-design/MAAS-design#911
> Fix wording on node events "full history" view.

- legacy/src/app/controllers/pod_details.js
Filter spaces without subnets on pod details, to prevent empty headings displaying in the subnet dropdown.
* Compose a machine, add an interface, and click the subnet dropdown - you shouldn't see any space headings without subnets.
Fixes canonical-web-and-design/MAAS-design#917
> Only display spaces on pod details with assigned subnets.

- ui/src/app/base/components/FormCard/FormCard.js
- ui/src/app/base/components/FormCard/FormCard.test.js
- ui/src/app/base/components/FormCard/__snapshots__/FormCard.test.js.snap
- ui/src/app/base/components/Section/Section.js
- ui/src/app/base/components/Section/__snapshots__/Section.test.js.snap
- ui/src/app/base/components/TableDeleteConfirm/TableDeleteConfirm.js
- ui/src/app/base/components/TableDeleteConfirm/__snapshots__/TableDeleteConfirm.test.js.snap
- ui/src/app/base/constants.js
- ui/src/app/base/sagas/websockets.js
- ui/src/app/settings/views/Dhcp/DhcpFormFields/DhcpFormFields.js
- Fixed col sizes in form cards.
- Put col sizes into a constants file so we hopefully don't get regressions like this again. Ideally we should be using these constants wherever we have a Col component but for now I've just used them wherever a sidebar might be present.
- Go to settings, see that the add user form card and delete user expanded rows look good.
Fixes canonical-web-and-design/maas-design#907
Also updated DHCP snippets form:
> Fix form card column sizes.

- legacy/src/app/controllers/node_details.js
- legacy/src/app/controllers/node_details_networking.js
- legacy/src/app/controllers/tests/test_networks_list.js
- legacy/src/app/controllers/tests/test_node_details.js
- legacy/src/app/controllers/tests/test_node_details_networking.js
- legacy/src/app/partials/cards/network.html
- legacy/src/app/partials/node-details.html
- legacy/src/scss/tables/_patterns_table-network-summary.scss
- legacy/src/scss/tables/_patterns_table-subnets.scss
- Building on top of #1195 - only show "Relayed" in machine summary and network tables, alongside a tooltip to show the full info (e.g. "Relayed via fabric-name.vlan-name")
- Add tests for changes to getDHCPStatus.
- Go to the details page of a machine that has an interface with DHCP relayed via a different vlan (e.g. ace-guinea in bolla: `/MAAS/l/machine/xahhr7`).
- Check that in the Network card under DHCP it says "Relayed" and if you hover over the information icon it shows a tooltip with the fabric/VLAN DHCP is being relayed via.
- Go to the network tab of the same machine and check that the same is shown in the summary there.
- Try editing and adding another interface and check that it still shows up correctly (because of how terrible `node-details.html` is the code for the tooltip …
> Add tooltip for interface DHCP relay info + improve table styling.

- legacy/src/app/controllers/node_details_networking.js
- legacy/src/app/controllers/tests/test_node_details_networking.js
- legacy/src/app/partials/node-details.html
- Filter out duplicate alias members from interface list.
- Go to the networking page of a New, Allocated or Ready machine.
- Add a physical interface.
- Create a bridge from that interface.
- Add an alias of the bridge.
- Check that the physical interface only shows up once in the list, and that the alias does not show
Fixes #1219 
[lp#1881804](https://bugs.launchpad.net/maas/+bug/1881804)
> Filter out duplicate alias members from interface list.

- legacy/src/app/directives/boot_images.js
- legacy/src/app/directives/tests/test_boot_images.js
- legacy/src/app/enum.js
- legacy/src/app/partials/boot-images.html
- legacy/src/app/partials/intro-user.html
- legacy/src/app/partials/intro.html
- Updated images page to allow selecting architectures on a per-release basis. Originally, selecting releases and architectures would download every possible combination.
- Disable release/arch combinations that are unsupported.
- Rearranged markup in boot_images.html to make a bit more sense.
- Run a local MAAS using [this branch](https://code.launchpad.net/~ltrager/maas/+git/maas/+merge/385331), which updates the websocket handler to allow for per-release selections.
- Go to /MAAS/l/images and check that you can select architectures per release, and the table below displays the summary correctly.
- Check that 20.04/i386 is disabled with a tooltip.
- Click "Save selection" and check that the downloads start correctly.
- Check that once the downloads are complete you can also remove them …
> Update images page to allow selecting architectures on a per-release basis.

- ui/src/app/base/reducers/user/user.js
- ui/src/app/base/sagas/websockets.js
- ui/src/root-reducer.js
- ui/src/root-reducer.test.js
- Clear the redux store when the websocket gets disconnected.
- Load the react ui.
- Restart your maas server.
- the ui should reconnect and the data in the redux store should be reset (except for auth and status).
See: https://github.com/canonical-web-and-design/maas-ui/issues/1222.
See: https://github.com/canonical-web-and-design/maas-ui/issues/1211.
> Clear the redux store when disconnected

- legacy/src/app/controllers/master.js
- ui/src/app/App.js
- Close both websockets when logging out.
- Log into the app with the network details open in dev tools.
- Navigate to the ui and legacy apps and you should see two websocket connections.
- Log out from ui and both connections should get closed.
- Log in again and navigate to ui and legacy.
- Log out from legacy.
- You should log out and be redirected to the login screen and there should be no connections in the network tab.
> Close both websockets when logging out

- legacy/src/app/directives/boot_images.js
- legacy/src/app/directives/tests/test_boot_images.js
- legacy/src/app/partials/boot-images.html
- Reverted images page to use checkboxes instead of radio buttons, but added some functionality for highlighting unsupported architectures.
- Go to the images page and check that the radio buttons are now checkboxes.
- Select 20.04 LTS and check that the i386 checkbox is disabled.
- Select more than one release and check that the i386 checkbox is enabled with a warning.
- Select i386 and check that the table of images does not include 20.04/i386
- Leave i386 checked, and uncheck all non-20.04 releases and see that the i386 checkbox becomes disabled and unchecked automatically.
- Uncheck 20.04 and check two other releases and see that the i386 checkbox is enabled with no warning
- Check that you can still download/remove images successfully. 
Fixes #1241
> Revert Images page to checkboxes, but add warning for unsupported arches.

- root/src/index.ejs
- root/src/root-application.js
- Fix redirects that land at old legacy # urls
- Run `dotrun`, the app should load normally for the react/angular apps.
- In a local MAAS run the following:
```shell
git config --file=.gitmodules submodule.src/maasui/src.url https://github.com/huwshimi/maas-ui.git
git config --file=.gitmodules submodule.src/maasui/src.branch fix-hash-redirects
git submodule sync
git submodule update --init --recursive --remote
make clean-ui
make ui
```
You may have to use `SKIP_PREFLIGHT_CHECK=true make ui` like I did.
- Visit <url of your maas >/MAAS/#/kvm a few times **using Firefox**. You should get redirected to /l/kvm.
Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/1240.
https://bugs.launchpad.net/maas/+bug/1883132
> Fix # redirects

- shared/src/components/Header/Header.js
- shared/src/components/Header/Header.test.js
- Highlight the subnets nav item.
- Click on the subnets item in the main nav, it should stay highlighted.
- Click on other items, they should still highlight.
> Fix subnets hightlight

- legacy/src/app/controllers/node_details_networking.js
- legacy/src/app/controllers/tests/test_node_details_networking.js
- legacy/src/app/partials/node-details.html
- Fixed edit bond form not saving some values correctly.
- Driveby fix for disconnected icon on "Create bond" form
- Go to the network details of a New machine and create a bond by combining two interfaces on the same VLAN. Make sure to change the bond mode, hash policy, LACP rate and link monitoring.
- Check that the bond is created successfully, then open the edit bond form.
- Change the values for bond mode, hash policy, LACP rate and link monitoring and save
- Reopen the edit bond form and check that the values were saved correctly.
Fixes #1193
> Fix edit bond form not saving all values.

- legacy/src/app/controllers/node_details_networking.js
* Add guard for `nic.members` before checking for `nic.members.length`
* Add alias to a single NIC
* Add alias to a bond
* Add alias to a bridge
Fixes #1248  .
> Fix nic.members not existing for non-aggregate interfaces. (#1248)

- ui/src/app/base/selectors/pod/pod.js
- ui/src/app/base/selectors/pod/pod.test.js
- ui/src/app/kvm/views/KVMList/KVMListTable/KVMListTable.js
- ui/src/app/kvm/views/KVMList/KVMListTable/KVMListTable.test.js
- ui/src/app/kvm/views/KVMList/KVMListTable/NameColumn/NameColumn.js
- ui/src/app/kvm/views/KVMList/KVMListTable/OSColumn/OSColumn.js
- ui/src/app/kvm/views/KVMList/KVMListTable/OSColumn/OSColumn.test.js
- ui/src/app/kvm/views/KVMList/KVMListTable/PoolColumn/PoolColumn.js
- ui/src/app/kvm/views/KVMList/KVMListTable/PowerColumn/PowerColumn.js
- ui/src/app/kvm/views/KVMList/KVMListTable/PowerColumn/PowerColumn.test.js
- ui/src/app/kvm/views/KVMList/KVMListTable/TypeColumn/TypeColumn.js
- ui/src/app/kvm/views/KVMList/KVMListTable/VMsColumn/VMsColumn.js
- ui/src/app/machines/views/MachineList/MachineListTable/PowerColumn/PowerColumn.js
- ui/src/app/machines/views/MachineList/MachineListTable/StatusColumn/StatusColumn.js
- ui/src/app/utils/getPowerIcon.js
- ui/src/app/utils/getPowerIcon.test.js
- ui/src/app/utils/getStatusText.js
- ui/src/app/utils/getStatusText.test.js
- ui/src/app/utils/index.js
- Built KVM table Power and OS cells.
- Converted the other cells (except for the Meters) to use the DoubleRow component to be consistent with the MachineListTable.
- Note that the secondary row text is slightly misaligned in the DoubleRow component - it should be exactly aligned with the Meter labels. I initially tried to fix it in this PR but it ended up breaking the MachineList rows, so I'll look into it as a follow up.
- Also note that making the table responsive will be handled in canonical-web-and-design/MAAS-squad#2025 so the OS text is likely to get truncated at the moment.
- Go to /MAAS/r/kvm
- Check that the Power and OS text matches what you see on /MAAS/l/kvm
Fixes canonical-web-and-design/MAAS-squad#2022
> Build KVM table Power and OS cells.

- RELEASE.md
* Update release docs to reflect that we no longer ship a tarball with the release on github.
* Add note about adding the MAAS release to the title of releases (e.g. `v0.1.2 [2.7]`)
n/a
> Update release docs.

- ui/src/app/machines/views/AddMachine/AddMachineForm/AddMachineForm.js
- ui/src/app/machines/views/AddMachine/AddMachineFormFields/AddMachineFormFields.js
- ui/src/app/machines/views/AddMachine/AddMachineFormFields/AddMachineFormFields.test.js
- Added a test on to https://github.com/canonical-web-and-design/maas-ui/pull/1272
- Go to http://0.0.0.0:8400/MAAS/r/machines/add
- Focus on the mac address field and blur it while its empty
- You should get validation error that the mac address is required
- Check the power type to IPMI
- See that the required asterisk has …
> Conditionally require mac address when adding a machine

- ui/src/app/base/selectors/pod/pod.test.js
- ui/src/app/base/selectors/pod/pod.ts
- ui/src/app/base/types.ts
- ui/src/app/kvm/views/KVMList/KVMListTable/KVMListTable.test.tsx
- ui/src/app/kvm/views/KVMList/KVMListTable/KVMListTable.tsx
- ui/src/app/kvm/views/KVMList/KVMListTable/PowerColumn/PowerColumn.tsx
- Added sorting to KVMListTable. A bit of extra work was required to be able to sort by things that aren't parameters of the KVMs themselves (power, OS, resource pool).
- Added types for Controller, ControllerState, Machine, MachineState and TestStatus.
- Go to /MAAS/r/kvm and check that you can sort by every table header. …
> Add sorting to KVMListTable.

- .circleci/config.yml
Cypress tests in CI are currently broken due to the deprecation of a number of flags for database initialisation with `maas init` in 2.8.
- Replace deprecated db init flags with `--database-uri` when setting up MAAS for cypress.
- none, cypress should pass.
> Use database-uri flag with maas init for cypress setup.

- ui/src/app/App.js
- ui/src/app/base/components/FormCardButtons/FormCardButtons.js
- ui/src/app/base/components/SideNav/SideNav.js
- ui/src/app/base/hooks.js
- ui/src/app/kvm/views/KVMDetails/KVMDetails.tsx
- ui/src/app/machines/components/HeaderStrip/HeaderStrip.js
- ui/src/app/machines/components/HeaderStrip/HeaderStripTabs/HeaderStripTabs.js
- ui/src/app/machines/views/Machines.js
- Replace custom instances of `useHistory` and `useLocation` with hooks provided by `react-router-dom`.
- App should still work, check machine listing, settings etc.
> Replace custom useHistory and useLocation implementation

- legacy/src/app/controllers/pods_list.js
- legacy/src/app/partials/pods-list.html
- ui/src/app/base/selectors/pod/pod.test.js
- ui/src/app/base/selectors/pod/pod.ts
- ui/src/app/kvm/views/KVMList/KVMListHeader/KVMListHeader.tsx
- ui/src/app/kvm/views/KVMList/KVMListTable/KVMListTable.tsx
- Added `pod.kvm` and `pod.rsd` selectors.
- Fixed available/selected counts in legacy KVM/RSD pages.
- Run a MAAS that has some KVMs and RSDs. By default, a `make sampledata`'d MAAS should have 3 of each.
- Go to /MAAS/r/kvm and check that the count next to the KVM title is correct (e.g. "1 of 3 VM hosts selected").
- Check the …
> Add selectors for KVM/RSD pods. 

- ui/src/app/base/actions/pod/pod.test.ts
- ui/src/app/base/actions/pod/pod.ts
- ui/src/app/base/components/FormikForm/FormikForm.tsx
- ui/src/app/base/reducers/pod/pod.test.ts
- ui/src/app/base/reducers/pod/pod.ts
- ui/src/app/base/types.ts
- ui/src/app/kvm/views/KVMList/AddKVMForm/AddKVMForm.tsx
- ui/src/app/kvm/views/KVMList/KVMListHeader/KVMActionFormWrapper/DeleteForm/DeleteForm.test.js
- ui/src/app/kvm/views/KVMList/KVMListHeader/KVMActionFormWrapper/DeleteForm/DeleteForm.tsx
- ui/src/app/kvm/views/KVMList/KVMListHeader/KVMActionFormWrapper/DeleteForm/index.ts
- ui/src/app/kvm/views/KVMList/KVMListHeader/KVMActionFormWrapper/KVMActionFormWrapper.test.tsx
- ui/src/app/kvm/views/KVMList/KVMListHeader/KVMActionFormWrapper/KVMActionFormWrapper.tsx
- ui/src/app/kvm/views/KVMList/KVMListHeader/KVMActionFormWrapper/RefreshForm/RefreshForm.test.js
- ui/src/app/kvm/views/KVMList/KVMListHeader/KVMActionFormWrapper/RefreshForm/RefreshForm.tsx
- ui/src/app/kvm/views/KVMList/KVMListHeader/KVMActionFormWrapper/RefreshForm/index.ts
- ui/src/app/kvm/views/KVMList/KVMListHeader/KVMActionFormWrapper/index.ts
- ui/src/app/kvm/views/KVMList/KVMListHeader/KVMListActionMenu/KVMListActionMenu.test.tsx
- ui/src/app/kvm/views/KVMList/KVMListHeader/KVMListActionMenu/KVMListActionMenu.tsx
- ui/src/app/kvm/views/KVMList/KVMListHeader/KVMListHeader.test.tsx
- ui/src/app/kvm/views/KVMList/KVMListHeader/KVMListHeader.tsx
- ui/src/app/utils/redux.js
- ui/src/app/utils/redux.test.js
- Added delete and refresh forms to KVM list page.
- Note that for now the forms close immediately after submit. The processing labels (e.g. "1 of 6 KVMs refreshing") and showing the spinner will be handled as a [separate issue](https://github.com/canonical-web-and-design/maas-ui/issues/1300) because it requires a large-ish change to the pod reducer. …
> Build KVMList action forms.

- ui/src/app/base/hooks.js
- ui/src/app/base/types.ts
- ui/src/app/kvm/views/KVMList/KVMListTable/KVMListTable.tsx
- ui/src/app/machines/views/MachineList/MachineListTable/MachineListTable.js
- Added `useTableSort` hook to handle sorting for machine and KVM lists. The end result is less duplicated code, and (I think) a nicer api e.g. instead of `const sortedMachines = [...machines].sort(machineSort(currentSort))` you would write `const sortedMachines = sortRows(machines)`.
- Check that the machine and KVM lists still …
> Add useTableSort hook to handle sorting for machine and KVM lists.

- legacy/src/app/partials/node-details.html
- removed checkbox in pxe details table and converted to icon 
- Run MAAS v2.7.1 with Maas UI 2.7
- Create local VM
- Attach virsh VM to MAAS instance
- Navigate to Machines tab 
- Click the VM machine you have added above
- Click Network tab
- PXE column now shows an icon with a check mark no clickable checkboxes or hidden …
> change radio button to icon for pxe boot interface column (#1164)

- legacy/src/app/partials/node-details.html
Note: this was proposed against 2.7 and has been reviewed.
https://github.com/canonical-web-and-design/maas-ui/pull/1322
- removed checkbox in pxe details table and converted to icon 
- Run MAAS v2.7.1 with Maas UI 2.7
- Create local VM
- Attach virsh VM to MAAS instance
- Navigate to Machines tab 
- Click the VM machine you …
> Change radio button to icon for pxe boot interface column

- ui/src/app/base/types.ts
- ui/src/testing/factories.ts
- Add `Node` and `SimpleNode` types to simplify `Device`, `Machine` and `Controller` types.
- Update test factories to reflect changes to types.
- Add a few new types, `ModelRef`, `Vlan`, `Device` and `NodeStatus`.
Note: I wasn't able to find a way to extend a test factory from multiple types, so had to abandon the `DeviceMachineNode` type in favour of some duplication between `Device` and `Machine` types.
- …
> Hoist shared properties to SimpleNode and Node types.

- ui/src/app/machines/views/MachineList/MachineListHeader/ActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.tsx
- ui/src/app/machines/views/MachineList/MachineListHeader/ActionFormWrapper/DeployForm/DeployFormFields/UserDataField/UserDataField.test.tsx
- ui/src/app/machines/views/MachineList/MachineListHeader/ActionFormWrapper/DeployForm/DeployFormFields/UserDataField/UserDataField.tsx
- ui/src/app/machines/views/MachineList/MachineListHeader/ActionFormWrapper/DeployForm/DeployFormFields/UserDataField/index.ts
- Add support for selecting or dropping a cloud-init script and parsing the script into the textarea.
- Choose a deployable machine in the machine list and open the deploy form.
- Choose the cloud-init option.
- Select or drop different files on the textarea. You should see either the script contents or appropriate errors.
Fixes: https://github.com/canonical-web-and-design/maas-squad/issues/2034.
> Add uploading of init-scripts.

- proxy/cypress/integration/machines/add.spec.ts
-Skip failing add machine test until it can be debugged.
Fixes: # .
In general, please propose fixes against *master* rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. Please apply backport labels to the PR …
> Skip failing add machine test.

- .github/workflows/test.yml
- HACKING.md
- README.md
- ui/.betterer.results
- Block CI on betterer.
- Add 'project conventions' section to HACKING.
- Update 'build with' section to include link to TypeScript.
- Manually update betterer snapshot.
- n/a
Fixes: n/a
In general, please propose fixes against *master* rather than release branches (e.g. …
> Block CI on betterer

- .vscode/settings.json
- ui/.betterer.results
- Add vs code workspace config for betterer extension
- Remove js file count test, as it [appears to be failing](https://github.com/phenomnomnominal/betterer/issues/149) when run in the extension context. This test isn't as valuable as having immediate feedback in the IDE for "stricter compilation", so I think dropping it isn't a huge loss. …
> Add vscode betterer config

- ui/.betterer.results
- ui/src/app/preferences/selectors/sshkey/sshkey.test.js
- ui/src/app/preferences/selectors/sslkey/sslkey.test.js
- ui/src/app/preferences/selectors/token/token.test.js
- ui/src/app/store/sshkey/types.ts
- ui/src/app/store/sslkey/types.ts
- ui/src/app/store/token/types.ts
- ui/src/testing/factories/index.ts
- ui/src/testing/factories/sshkey.ts
- ui/src/testing/factories/sslkey.ts
- ui/src/testing/factories/state.ts
- ui/src/testing/factories/token.ts
- Add types and factories for sshkey, sslkey and token.
Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/1354.
> Add types for preferences models

- ui/src/app/machines/views/MachineList/MachineListHeader/ActionFormWrapper/CommissionForm/CommissionForm.js
- Changed the form schema for `CommissioningForm` to remove mandatory testing scripts
- From machine list, select a machine to commission
- In the comissioning form, remove the default smartctl-validate test
- Should be able to submit the form.
#1374 
Fixes LP#1884278
> Test scripts aren't mandatory.

- .circleci/config.yml
- Changed cypress MAAS snap from latest/edge to 2.8/edge for the 2.8 branch,
- `test_cypress` should pass
> Change cypress MAAS snap from latest/edge to 2.8/edge

- .github/workflows/test.yml
- @squidsoup squashed stdout for the betterer CI job when redirecting, this fixes it.
Fixes: # .
In general, please propose fixes against *master* rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. Please …
> Preserve stdout for betterer in CI.

- ui/.betterer.results
- ui/src/app/base/selectors/dhcpsnippet/dhcpsnippet.test.js
- ui/src/app/base/selectors/licensekeys/licensekeys.js
- ui/src/app/base/selectors/licensekeys/licensekeys.test.js
- ui/src/app/base/selectors/packagerepository/packagerepository.test.js
- ui/src/app/base/selectors/scripts/scripts.test.js
- ui/src/app/settings/selectors/config/config.test.js
- ui/src/app/store/config/types.ts
- ui/src/app/store/dhcpsnippet/types.ts
- ui/src/app/store/licensekeys/types.ts
- ui/src/app/store/packagerepository/types.ts
- ui/src/app/store/scripts/types.ts
- ui/src/testing/factories/config.ts
- ui/src/testing/factories/dhcpsnippet.ts
- ui/src/testing/factories/index.ts
- ui/src/testing/factories/licensekeys.ts
- ui/src/testing/factories/packagerepository.ts
- ui/src/testing/factories/scripts.ts
- ui/src/testing/factories/state.ts
- Add types and factories for dhcpsnippets, licensekeys, packagerepositories scripts and config.
Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/1355.
> Add types and factories for settings models

- ui/.betterer.results
- ui/src/app/base/selectors/domain/domain.test.js
- ui/src/app/base/selectors/service/service.test.js
- ui/src/app/base/selectors/status/status.test.js
- ui/src/app/base/selectors/subnet/subnet.test.js
- ui/src/app/base/selectors/tag/tag.test.js
- ui/src/app/base/selectors/zone/zone.test.js
- ui/src/app/store/dhcpsnippet/types.ts
- ui/src/app/store/domain/types.ts
- ui/src/app/store/scriptresults/types.ts
- ui/src/app/store/service/types.ts
- ui/src/app/store/status/types.ts
- ui/src/app/store/subnet/types.ts
- ui/src/app/store/tag/types.ts
- ui/src/testing/factories/domain.ts
- ui/src/testing/factories/index.ts
- ui/src/testing/factories/resourcepool.ts
- ui/src/testing/factories/scriptresults.ts
- ui/src/testing/factories/service.ts
- ui/src/testing/factories/state.ts
- ui/src/testing/factories/subnet.ts
- ui/src/testing/factories/tag.ts
- ui/src/testing/factories/zone.ts
- Create types and factories for domain, resourcepool, scriptresults, service, status, subnet, tag and zone.
Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/1360.
> Create types and factories for remaining models

- ui/.betterer.results
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMSummary.tsx
- ui/src/app/machines/views/MachineList/MachineListTable/MachineListTable.js
- ui/src/app/machines/views/MachineList/MachineListTable/MachineListTable.test.js
- ui/src/app/machines/views/MachineList/MachineListTable/NameColumn/NameColumn.js
- ui/src/app/machines/views/MachineList/MachineListTable/NameColumn/NameColumn.test.js
- ui/src/app/machines/views/MachineList/MachineListTable/NameColumn/__snapshots__/NameColumn.test.js.snap
- ui/src/app/machines/views/MachineList/MachineListTable/OwnerColumn/OwnerColumn.js
- ui/src/app/machines/views/MachineList/MachineListTable/OwnerColumn/OwnerColumn.test.js
- ui/src/app/machines/views/MachineList/MachineListTable/PoolColumn/PoolColumn.js
- ui/src/app/machines/views/MachineList/MachineListTable/PoolColumn/PoolColumn.test.js
- ui/src/app/machines/views/MachineList/MachineListTable/PowerColumn/PowerColumn.js
- ui/src/app/machines/views/MachineList/MachineListTable/PowerColumn/PowerColumn.test.js
- ui/src/app/machines/views/MachineList/MachineListTable/StatusColumn/StatusColumn.js
- ui/src/app/machines/views/MachineList/MachineListTable/StatusColumn/StatusColumn.test.js
- ui/src/app/machines/views/MachineList/MachineListTable/ZoneColumn/ZoneColumn.js
- ui/src/app/machines/views/MachineList/MachineListTable/ZoneColumn/ZoneColumn.test.js
- Added `showActions` prop to MachineListTable (default=true) which determines whether checkboxes and in-table actions will show
- Added MachineListTable to KVM summary page (with showActions=false).
- I was going to convert some files to TS but it would have required converting the machines selector file to TS too. I'll tackle that as a separate ticket. …
> Add MachineListTable to KVM summary page.

- shared/src/components/Header/Header.js
- shared/src/components/Header/__snapshots__/Header.test.js.snap
- ui/.betterer.results
- ui/src/app/base/components/Meter/Meter.test.tsx
- ui/src/app/base/components/Meter/Meter.tsx
- ui/src/app/base/components/Meter/__snapshots__/Meter.test.tsx.snap
- ui/src/app/base/components/Meter/_index.scss
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMSummary.tsx
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMSummaryStorage/KVMSummaryStorage.test.tsx
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMSummaryStorage/KVMSummaryStorage.tsx
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMSummaryStorage/index.ts
- ui/src/app/kvm/views/KVMList/KVMListTable/CPUColumn/CPUColumn.test.tsx
- ui/src/app/kvm/views/KVMList/KVMListTable/CPUColumn/CPUColumn.tsx
- ui/src/app/kvm/views/KVMList/KVMListTable/RAMColumn/RAMColumn.test.tsx
- ui/src/app/kvm/views/KVMList/KVMListTable/RAMColumn/RAMColumn.tsx
- ui/src/app/kvm/views/KVMList/KVMListTable/StorageColumn/StorageColumn.test.tsx
- ui/src/app/kvm/views/KVMList/KVMListTable/StorageColumn/StorageColumn.tsx
- ui/src/app/kvm/views/KVMList/KVMListTable/_index.scss
- ui/src/app/store/pod/types.ts
- ui/src/app/utils/chunk.test.ts
- ui/src/app/utils/chunk.ts
- ui/src/app/utils/index.ts
- ui/src/scss/_breakpoint-widths.scss
- ui/src/scss/_patterns_cards.scss
- ui/src/scss/_patterns_lists.scss
- ui/src/scss/index.scss
- ui/src/testing/factories/index.ts
- ui/src/testing/factories/nodes.ts
- Added storage cards to KVM summary page. I've done it mostly according to [the design](https://app.zeplin.io/project/5e538f1156434564ebb73903/screen/5ec783846b27e649abd0406a), except I've made it 3 per row instead of 4 otherwise the mount paths + storage meter get really cramped near the medium breakpoint.
- Updated the Meter component to only accept a single `label` prop, instead of having a label per datum. I think how we plan to use meter labels is too varied, so it's easier to just have complete control over how the label looks from a single JSX element.
- Changed the Header component to route to /r/kvm instead of /l/kvm
- Fixed a css bug that prevented the VMs header rendering
- …
> Add "Storage" section to KVM summary page.

- ui/src/app/machines/views/MachineList/MachineListHeader/ActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.tsx
- Added cloud-init docs link to the deploy form.
- From the machine list check a deployable machine.
- Click deploy in the take action menu.
- Next to the cloud-init option there should be a read more link which should take you to the docs.
Fixes: https://github.com/canonical-web-and-design/MAAS-squad/issues/2038.
> Added cloud-init docs link

- legacy/src/app/directives/machines_table.js
- Fixed a bug where if a parentNode did not exist when clicking on the machine list, a console error would occur
- Go to the angular version of a pod details page
- Click somewhere in the window and drag the cursor outside the browser window
- Let go of the click
- There should be no console error
Fixes #1401
> Fix angular machine list parentClasses bug.

- ui/src/app/machines/views/MachineList/MachineListHeader/ActionFormWrapper/DeployForm/DeployForm.tsx
- ui/src/app/machines/views/MachineList/MachineListHeader/ActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.test.tsx
- ui/src/app/machines/views/MachineList/MachineListHeader/ActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.tsx
- Disable and add an error message to the deploy form if no OSes/releases are detected in state.
- Spin up a new MAAS and do not download any images when prompted to. I don't think this will work if you try to delete all the images from an existing MAAS, as MAAS prevents users from deleting the default commissioning/deployment …
> Add error message to deploy form if no images have been downloaded.

- ui/src/app/base/actions/pod/pod.test.ts
- ui/src/app/base/actions/pod/pod.ts
- ui/src/app/base/components/ActionForm/ActionForm.tsx
- ui/src/app/base/components/FormikForm/FormikForm.tsx
- ui/src/app/base/components/TableActions/TableActions.js
- ui/src/app/base/reducers/pod/pod.test.ts
- ui/src/app/base/reducers/pod/pod.ts
- ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/ComposeForm.test.js
- ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/ComposeForm.tsx
- ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/ComposeFormFields/ComposeFormFields.test.tsx
- ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/ComposeFormFields/ComposeFormFields.tsx
- ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/InterfacesTable/InterfacesTable.test.tsx
- ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/InterfacesTable/InterfacesTable.tsx
- ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/InterfacesTable/_index.scss
- ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/InterfacesTable/index.ts
- ui/src/app/kvm/views/KVMDetails/KVMDetails.tsx
- ui/src/app/store/pod/types.ts
- ui/src/app/store/subnet/selectors.test.ts
- ui/src/app/store/subnet/selectors.ts
- ui/src/scss/_vanilla-overrides.scss
- ui/src/scss/index.scss
- ui/src/testing/factories/index.ts
- ui/src/testing/factories/nodes.ts
- Added interfaces table to KVM compose form, which is used to construct the interface constraints string.
- Updated warning styling for cores and memory fields
- Go to the KVM details page of a KVM and open the Compose dropdown.
- Check that there is an Interfaces section.
- Click "Define (optional)" and define some interface …
> Add interfaces table to KVM compose form.

- legacy/src/app/controllers/node_details_networking.js
- legacy/src/app/partials/node-details.html
- Updated check for interfaces to include VLAN in node details table. 
ssh ubuntu@<provisioner of maas instances|segmaas>
sudo snap install --channel=2.7/stable maas
sudo maas init
-- fill out questions
sudo apt-get install net-tools qemu-kvm  
in a seperate terminal on your laptop 
$ sshuttle -r ubuntu@<new ip giving to maas …
> add vlan check to displaying disconnected-icon (#1429)

- legacy/src/app/entry.js
- ui/src/app/base/components/ErrorBoundary/ErrorBoundary.js
- Add `maas.version` tag to Sentry reports as per https://docs.sentry.io/platforms/javascript/
n/a
n/a
n/a
In general, please propose fixes against *master* rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. Please apply …
> Add maas.version tag to Sentry reports.

- ui/src/app/base/components/TagSelector/TagSelector.js
- ui/src/app/base/components/TagSelector/_index.scss
- ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/ComposeForm.test.js
- ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/ComposeForm.tsx
- ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/ComposeFormFields/ComposeFormFields.tsx
- ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/InterfacesTable/InterfacesTable.test.tsx
- ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/InterfacesTable/InterfacesTable.tsx
- ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/InterfacesTable/_index.scss
- ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/StorageTable/StorageTable.test.tsx
- ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/StorageTable/StorageTable.tsx
- ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/StorageTable/_index.scss
- ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/StorageTable/index.ts
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMSummaryStorage/KVMSummaryStorage.tsx
- ui/src/scss/_patterns_forms.scss
- ui/src/scss/_vanilla-overrides.scss
- ui/src/scss/index.scss
- Added Storage configuration section to KVM compose form.
- Updated TagSelector so it can be properly styled without a label
- Rich select to be added in https://github.com/canonical-web-and-design/maas-squad/issues/2061
- Go to the KVM list and select a LXD KVM
- Open the compose dropdown and check that there is a "Storage …
> Add Storage configuration section to KVM compose form.

- ui/src/app/base/components/ContextualMenu/ContextualMenu.js
- ui/src/app/base/components/TableMenu/_index.scss
- ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/ComposeFormFields/ComposeFormFields.test.tsx
- ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/InterfacesTable/InterfacesTable.test.tsx
- ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/InterfacesTable/InterfacesTable.tsx
- ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/InterfacesTable/SubnetSelect/SubnetSelect.test.tsx
- ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/InterfacesTable/SubnetSelect/SubnetSelect.tsx
- ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/InterfacesTable/SubnetSelect/_index.scss
- ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/InterfacesTable/SubnetSelect/index.ts
- ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/InterfacesTable/_index.scss
- ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/StorageTable/StorageTable.test.tsx
- ui/src/app/machines/views/MachineList/MachineListControls/FilterAccordion/__snapshots__/FilterAccordion.test.js.snap
- ui/src/app/machines/views/MachineList/MachineListTable/OwnerColumn/__snapshots__/OwnerColumn.test.js.snap
- ui/src/app/machines/views/MachineList/MachineListTable/PoolColumn/__snapshots__/PoolColumn.test.js.snap
- ui/src/app/machines/views/MachineList/MachineListTable/PowerColumn/__snapshots__/PowerColumn.test.js.snap
- ui/src/app/machines/views/MachineList/MachineListTable/StatusColumn/__snapshots__/StatusColumn.test.js.snap
- ui/src/app/machines/views/MachineList/MachineListTable/ZoneColumn/__snapshots__/ZoneColumn.test.js.snap
- ui/src/scss/_patterns_contextual-menu.scss
- ui/src/scss/index.scss
- Built SubnetSelect component similar to the angular version
- Go to the KVM compose form
- Define an interface
- Click the Subnet dropdown and check that it shows information about the fabric, VLAN and PXE boot status associated with that subnet
Fixes canonical-web-and-design/MAAS-squad#2061
> Build SubnetSelect component for KVM compose form.

- legacy/src/app/controllers/node_details.js
- legacy/src/app/directives/nodedetails/deploy_options.js
- legacy/src/app/directives/nodedetails/user_data_upload.js
- legacy/src/app/directives/os_select.js
- legacy/src/app/directives/tests/test_os_select.js
- legacy/src/app/entry.js
- legacy/src/app/partials/directives/os-select.html
- legacy/src/app/partials/node-details.html
- legacy/src/app/partials/nodedetails/deploy-options.html
* Add support for cloud-init to deploy form on machine details view.
* Fix styles to make deploy form better aligned with the react version on machine list.
*Note*: the **actual** diff is not that large, `node-details.html` has been reformatted here (curious that prettier missed that earlier...). Apologies for the heart attack. …
> ✨ (legacy): Add cloud-init support to legacy.

- ui/src/app/base/components/NotificationList/NotificationList.test.tsx
- ui/src/app/store/notification/selectors.test.ts
- ui/src/app/store/notification/selectors.ts
- Filter notifications to remove release notifications if the option is turned off.
- [A local edge snap MAAS](/HACKING.md#snap-deployment) (this will not usually have machines)
- Create a release notification:
```shell
maas $PROFILE notifications create ident='release_notification' category='info' users=true admins=true message='<strong>We’ve released MAAS 2.8.</strong> This version supports LXD VM hosts, faster UI and many bug fixes. Find out <a href="https://maas.io/docs/release-notes">what’s new in 2.8</a>.'
```
- If you dismiss …
> Filter out notifications if they are disabled

- ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/StorageTable/PoolSelect/PoolSelect.test.tsx
- ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/StorageTable/PoolSelect/PoolSelect.tsx
- ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/StorageTable/PoolSelect/_index.scss
- ui/src/app/kvm/views/KVMList/KVMListTable/CPUColumn/CPUColumn.test.tsx
- ui/src/app/kvm/views/KVMList/KVMListTable/CPUColumn/CPUColumn.tsx
- ui/src/app/kvm/views/KVMList/KVMListTable/CPUColumn/CPUPopover/CPUPopover.test.tsx
- ui/src/app/kvm/views/KVMList/KVMListTable/CPUColumn/CPUPopover/CPUPopover.tsx
- ui/src/app/kvm/views/KVMList/KVMListTable/CPUColumn/CPUPopover/_index.scss
- ui/src/app/kvm/views/KVMList/KVMListTable/RAMColumn/RAMColumn.test.tsx
- ui/src/app/kvm/views/KVMList/KVMListTable/RAMColumn/RAMColumn.tsx
- ui/src/app/kvm/views/KVMList/KVMListTable/RAMColumn/RAMPopover/RAMPopover.test.tsx
- ui/src/app/kvm/views/KVMList/KVMListTable/RAMColumn/RAMPopover/RAMPopover.tsx
- ui/src/app/kvm/views/KVMList/KVMListTable/RAMColumn/RAMPopover/_index.scss
- ui/src/app/kvm/views/KVMList/KVMListTable/StorageColumn/StorageColumn.test.tsx
- ui/src/app/kvm/views/KVMList/KVMListTable/StorageColumn/StorageColumn.tsx
- ui/src/app/kvm/views/KVMList/KVMListTable/StorageColumn/StoragePopover/StoragePopover.test.tsx
- ui/src/app/kvm/views/KVMList/KVMListTable/StorageColumn/StoragePopover/StoragePopover.tsx
- ui/src/app/kvm/views/KVMList/KVMListTable/StorageColumn/StoragePopover/_index.scss
- ui/src/app/utils/formatBytes.ts
- ui/src/scss/_patterns_icons.scss
- ui/src/scss/_patterns_tables.scss
- Updated KVM list popovers to the [latest design](https://app.zeplin.io/project/5f281ffc1be00d31ed6bc3a4/screen/5f28494c9dd2f2206894f93a)
- Updated popover language (and code) so "assigned" is now "allocated", and "unassigned" is now "free".
- Used common styling between this popover and the storage pool select dropdown
- Go to …
> Update KVM list popovers to latest design.

- ui/src/app/base/components/NotificationGroup/Notification/Notification.test.tsx
- ui/src/app/base/components/NotificationGroup/Notification/Notification.tsx
- ui/src/app/base/components/NotificationGroup/Notification/__snapshots__/Notification.test.tsx.snap
- ui/src/app/base/components/Switch/Switch.tsx
- ui/src/app/base/components/Switch/__snapshots__/Switch.test.tsx.snap
- Update the opt-out menu to show the value from the API, and send the updated value.
- [A local edge snap MAAS](/HACKING.md#snap-deployment) (this will not usually have machines)
- Create a release notification:
```shell
maas $PROFILE notifications create ident='release_notification' category='info' users=true admins=true message='<strong>We’ve released MAAS 2.8.</strong> This version supports LXD VM hosts, faster UI and many bug fixes. Find out <a href="https://maas.io/docs/release-notes">what’s new in 2.8</a>.'
```
- If you …
> Update opt-out menu to send API request

- ui/src/app/App.js
- Fix user intro route. Some recent refactoring inadvertently redirected the UI to a non existent react route (r/user/intro), instead of the correct legacy route (l/user/intro), which caused an infinite redirect loop of death. :skull: :fire:
In a clean focal container:
-  sudo snap install …
> fix(legacy): Correctly redirect to legacy for user intro.

- ui/src/app/base/components/Switch/Switch.tsx
- ui/src/app/kvm/components/KVMResourcesCard/KVMResourcesCard.test.tsx
- ui/src/app/kvm/components/KVMResourcesCard/KVMResourcesCard.tsx
- ui/src/app/kvm/components/KVMResourcesCard/_index.scss
- ui/src/app/kvm/components/KVMResourcesCard/index.ts
- ui/src/app/kvm/views/KVMDetails/KVMDetailsHeader/KVMDetailsHeader.tsx
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMAggregateResources/KVMAggregateResources.tsx
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMAggregateResources/index.ts
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMNumaResources/KVMNumaResources.tsx
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMNumaResources/_index.scss
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMNumaResources/index.ts
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMStorage/KVMStorage.test.tsx
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMStorage/KVMStorage.tsx
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMStorage/index.ts
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMSummary.test.tsx
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMSummary.tsx
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMSummaryStorage/index.ts
- ui/src/scss/_patterns_buttons.scss
- ui/src/scss/_patterns_grids.scss
- ui/src/scss/_patterns_switches.scss
- ui/src/scss/_patterns_typography.scss
- ui/src/scss/_settings.scss
- ui/src/scss/_utilities.scss
- ui/src/scss/index.scss
- Added a few sass mixins (small bold header, thin button and grid placeholder).
- Added the switch that toggles the aggregated and NUMA resources views.
- Set up responsive grid layouts for the aggregated and NUMA resources views
- Created scaffolding components using baked in data for now.
- I wouldn't worry too much about the …
> Set up scaffolding components and grid layouts for KVM resources cards.

- legacy/src/app/partials/nodedetails/deploy-options.html
- ui/src/app/machines/views/MachineList/MachineListHeader/ActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.tsx
- Fix the spacing around the deploy options.
- Visit the machine list, check a deployable machine and open the deploy form via the take action menu.
- Check that there is a nice amount of space between the two checkbox options.
- Reduce the size of your window until the labels wrap onto a new line. The wrapping text should be indented to match the label (and clear the checkbox).
- Now visit a deployable machine's details page and open the deploy …
> fix(ui): adjust spacing around deploy options

- legacy/src/app/partials/node-details.html
- Pass checkTestParameterValues and setDefaultValues to commissioning scripts selector
- Go to a ready machine details
- Click the Action menu and select Commission
- You should see the script called set_scale.sh
- Remove that and see there are no console errors
- Add the script back again and check it works with no errors
- Do all the above on bolla and see there are errors
Fixes: #1477 
lp#1891924
In general, please propose fixes against *master* rather than release branches (e.g. 2.7), unless the fix …
> fix(legacy): Pass operational functions to commissioning scripts selector

- scripts/lp-bugs-to-gh-issues.py
- Create a temp file with the contents of the environment variable: LAUNCHPAD_CREDENTIALS
- Pass that file as the credentials when initialising a Launchpad session
- Check the code
> fix(scripts): Authenticate with Launchpad via credentials file

- ui/src/app/base/components/Meter/Meter.test.tsx
- ui/src/app/base/components/Meter/Meter.tsx
- ui/src/app/base/components/Meter/__snapshots__/Meter.test.tsx.snap
- ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/StorageTable/PoolSelect/PoolSelect.tsx
- ui/src/app/kvm/components/KVMMeter/KVMMeter.test.tsx
- ui/src/app/kvm/components/KVMMeter/KVMMeter.tsx
- ui/src/app/kvm/components/KVMMeter/__snapshots__/KVMMeter.test.tsx.snap
- ui/src/app/kvm/components/KVMMeter/_index.scss
- ui/src/app/kvm/components/KVMMeter/index.ts
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMStorage/KVMStorage.test.tsx
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMStorage/KVMStorage.tsx
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMStorage/_index.scss
- ui/src/app/kvm/views/KVMList/KVMListTable/CPUColumn/CPUColumn.tsx
- ui/src/app/kvm/views/KVMList/KVMListTable/RAMColumn/RAMColumn.tsx
- ui/src/app/kvm/views/KVMList/KVMListTable/StorageColumn/StorageColumn.tsx
- ui/src/app/kvm/views/KVMList/KVMListTable/StorageColumn/StoragePopover/StoragePopover.tsx
- ui/src/scss/_patterns_typography.scss
- ui/src/scss/_utilities.scss
- ui/src/scss/index.scss
- Built redesigned KVM storage cards.
- Built KVMMeter component which just wraps Meter with some specific styling for total/allocated/free data. We should be able to use it in other parts of the KVM resources summary.
- Removed `key` prop from Meter data. It was only used because the component maps over the data array - all it needs to be is a unique string so it probably didn't need to be included in the prop.
- …
> feat(ui): Build redesigned KVM storage cards.

- ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/StorageTable/PoolSelect/PoolSelect.tsx
- ui/src/app/kvm/components/KVMMeter/KVMMeter.tsx
- ui/src/app/kvm/components/KVMMeter/__snapshots__/KVMMeter.test.tsx.snap
- ui/src/app/kvm/components/KVMResourcesCard/KVMResourcesCard.tsx
- ui/src/app/kvm/components/KVMResourcesCard/_index.scss
- ui/src/app/kvm/views/KVMList/KVMListTable/CPUColumn/CPUPopover/CPUPopover.tsx
- ui/src/app/kvm/views/KVMList/KVMListTable/RAMColumn/RAMPopover/RAMPopover.tsx
- ui/src/app/kvm/views/KVMList/KVMListTable/StorageColumn/StoragePopover/StoragePopover.tsx
- ui/src/scss/_patterns_icons.scss
- Updated KVM details RAM tables to match [design](https://app.zeplin.io/project/5f1a24be5ee8af8723f4e7fa/screen/5f36a6fd1124de23d57b637b).
- Changed the icon class names for the little coloured circles (`p-icon--requested`, `p-icon--allocated` etc.) to just `p-circle--{colour}` because the meaning of the colour is no longer consistent. e.g. in the KVM compose form a green circle is "requested storage" but in the KVM details page a green circle is "allocated hugepage".
- …
> feat(ui): Improve styling of KVM details RAM tables.

- ui/src/app/base/components/Meter/Meter.test.tsx
- ui/src/app/base/components/Meter/Meter.tsx
- ui/src/app/kvm/components/KVMMeter/KVMMeter.tsx
- ui/src/app/kvm/components/KVMMeter/__snapshots__/KVMMeter.test.tsx.snap
- ui/src/app/kvm/components/KVMMeter/_index.scss
- ui/src/app/kvm/components/KVMResourcesCard/KVMResourcesCard.test.tsx
- ui/src/app/kvm/components/KVMResourcesCard/KVMResourcesCard.tsx
- ui/src/app/kvm/components/KVMResourcesCard/__snapshots__/KVMResourcesCard.test.tsx.snap
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMAggregateResources/KVMAggregateResources.test.tsx
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMAggregateResources/KVMAggregateResources.tsx
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMNumaResources/KVMNumaResources.tsx
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMStorage/KVMStorage.tsx
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMSummary.tsx
- Added meters for aggregate CPU and VFs, and NUMA CPU and VFs.
- Used real data for aggregate RAM and CPU, and fake data for aggregate VFs, aggregate interfaces and all NUMA data.
- Removed the "snap to base2 width" functionality of the Meter component. If we want the meter to have pixel perfect separators, that should now be handled by setting the width of the container (which is the case in the KVM list).
- …
> Add CPU and VFs meters to KVM resources page.

- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMNumaResources/KVMNumaResources.test.tsx
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMNumaResources/KVMNumaResources.tsx
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMStorage/KVMStorage.test.tsx
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMStorage/KVMStorage.tsx
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMSummary.tsx
- Built expanding dropdowns for KVM NUMA and storage cards.
- Truncation is set at 3 for both, regardless of screen size. We can look into making that number a bit more dynamic as a follow up if it's considered important.
- Open `KVMSummary.tsx` and change the variable `fakeNumas` to include more than 3 "nodes".
- Open …
> feat(ui): Build expanding dropdowns for KVM NUMA and storage cards.

- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMSummary.test.tsx
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMSummary.tsx
- ui/src/scss/_utilities.scss
Add a copyable code component containing a Pod's IP address to the pod details page.
- Add a copyable code component containing a Pod's IP address to the pod details page.
- Navigate to the details page for a pod.
- There should be a code box at the top with the ip address, à la: https://app.zeplin.io/project/5f1a24be5ee8af8723f4e7fa/screen/5f315c75b688551f4783d49b
Fixes: canonical-web-and-design/MAAS-squad#2071.
> feat(ui): add a copyable ip address to pod details

- ui/.betterer.results
- ui/src/app/machines/views/MachineList/MachineListTable/MachineListTable.js
- ui/src/app/machines/views/MachineList/MachineListTable/MachineListTable.test.js
- yarn.lock
Adds a new prop, `hideColumns` to `MachineListTable`, which takes an array of column names.
e.g. <MachineListTable hiddenColumns={['power', 'zone']} />
Note: the 'fqdn' column will not be hidden unless `showActions` is false.
I *haven't* migrated `MachineListTable` to ts here, as this is probably the largest component in the project, and should be tackled in a separate branch. …
> feat(ui): teach MachineListTable to hide columns

- ui/src/app/kvm/components/KVMMeter/KVMMeter.tsx
- ui/src/app/kvm/components/KVMMeter/__snapshots__/KVMMeter.test.tsx.snap
- ui/src/app/kvm/components/KVMResourcesCard/KVMResourcesCard.test.tsx
- ui/src/app/kvm/components/KVMResourcesCard/KVMResourcesCard.tsx
- ui/src/app/kvm/components/KVMResourcesCard/__snapshots__/KVMResourcesCard.test.tsx.snap
- ui/src/app/kvm/components/KVMResourcesCard/_index.scss
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMAggregateResources/KVMAggregateResources.tsx
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMNumaResources/KVMNumaResources.test.tsx
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMNumaResources/KVMNumaResources.tsx
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMNumaResources/_index.scss
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMSummary.tsx
- ui/src/scss/_patterns_buttons.scss
- ui/src/scss/_settings.scss
- ui/src/scss/_utilities.scss
- Updated NUMA view to use latest [4-col design](https://app.zeplin.io/project/5f1a24be5ee8af8723f4e7fa/screen/5f3d3e51af976f14aa6cff34). If the pod has >2 NUMA nodes it will show the 4-col design, otherwise it will show a wider version to fill up the empty space.
- Added a placeholder RAM chart to get an idea of the spacing.
- Updated the fake NUMA data to include instances where VFs, hugepage or VMs are missing, which should be possible with real data.
- Serving with …
> feat(ui): Update NUMA view to 4-col design + handle cases of absent data.

- ui/src/app/base/components/NotificationGroup/Notification/Notification.tsx
- ui/src/app/base/components/NotificationGroup/Notification/__snapshots__/Notification.test.tsx.snap
- ui/src/app/base/components/NotificationList/__snapshots__/NotificationList.test.tsx.snap
- ui/src/scss/_patterns_notifications.scss
- Update the new release notification to show the settings link on the right.
- Create a new release notification (instructions are here: https://github.com/canonical-web-and-design/MAAS-squad/issues/2065#issue-669660220).
- Check that the "See settings" link is aligned right (next to the X).
> feat(ui): right align release notification settings link

- ui/src/app/kvm/components/KVMResourcesCard/KVMResourcesCard.tsx
- ui/src/app/kvm/components/KVMResourcesCard/__snapshots__/KVMResourcesCard.test.tsx.snap
- ui/src/app/kvm/components/KVMResourcesCard/_index.scss
- ui/src/app/machines/views/MachineList/MachineListTable/MachineListTable.js
- Add machine list modal to kvm node contextual menu dropdown.
- Add `paginateLimit` prop to MachineListTable.
Note: this list is not filtered by numa node, as we're using fake data currently.
@amylily1011 I've left this with pagination enabled, and I think it actually feels reasonable, let me know your thoughts. An open question for the core team is how many machines can be associated with any given NUMA node? Is there a realistic range, and a theoretical maximum? 
- Serving …
> feat(ui): add mini machine list to kvm node contextual menus.

- legacy/src/app/partials/dashboard.html
- Removed `p-text--small` class
Fixes issue from #1599 
- On a MAAS with discoveries, go to the dashboard, click on 'Clear all discoveries' and observe the text
> fix(legacy): don't use text--small

- legacy/src/app/controllers/node_details_networking.js
- legacy/src/app/partials/node-details.html
Enable Open vSwitch support for bridge interfaces in Network Details.
- Add a new interface to a deployed machine.
- Create a bridge, and select Open vSwitch as the bridge type
- You should see a bridge created with the "Open vSwitch"
Fixes: canonical-web-and-design/maas-squad#2090 …
> feat(legacy): enable OVS bridge interface type

- ui/src/app/base/components/ContextualMenu/ContextualMenu.js
- ui/src/app/base/components/ContextualMenu/ContextualMenu.test.js
- ui/src/app/base/components/ContextualMenu/ContextualMenuDropdown/ContextualMenuDropdown.js
- ui/src/app/kvm/components/KVMResourcesCard/KVMResourcesCard.tsx
- ui/src/app/kvm/components/KVMResourcesCard/__snapshots__/KVMResourcesCard.test.tsx.snap
- ui/src/app/kvm/components/KVMResourcesCard/_index.scss
- ui/src/app/machines/views/MachineList/MachineListTable/MachineListTable.js
- ui/src/app/machines/views/MachineList/_index.scss
- Added "auto" position prop to ContextualMenu.
- Gave class names to MachineList cells.
- Added Power col to VMs dropdown.
- Go to KVM details and check that the VMs dropdown shows to the left or right of the toggle depending on where it sits in the viewport.
Fixes #1590
> feat(ui): improve responsiveness of KVM VM dropdowns

- .github/workflows/test.yml
Previously, the betterer ci job would always pass as we returned the exit code of tee, rather than the exit code of the betterer command piped to tee. Setting `pipefail` ensures we return the correct exit code.
> The exit status of a pipeline is the exit status of the last command in the pipeline, unless the pipefail option is enabled (see The Set Builtin). If pipefail is enabled, the pipeline’s return status is the value of the last (rightmost) command to exit with a non-zero status, or zero if all commands exit successfully. If the reserved word ‘!’ precedes the pipeline, the exit status is the logical negation of the exit status as described above. The shell waits for all commands in the pipeline to terminate before returning a value. …
> fix(ci): ensure betterer returns exit code

- ui/.betterer.results
- ui/src/__snapshots__/root-reducer.test.js.snap
- ui/src/app/base/actions/device/device.js
- ui/src/app/base/actions/device/index.js
- ui/src/app/base/actions/index.ts
- ui/src/app/base/reducers/device/device.js
- ui/src/app/base/reducers/device/index.js
- ui/src/app/base/reducers/index.ts
- ui/src/app/settings/views/Dhcp/DhcpForm/DhcpForm.js
- ui/src/app/settings/views/Dhcp/DhcpForm/DhcpForm.test.js
- ui/src/app/settings/views/Dhcp/DhcpList/DhcpList.js
- ui/src/app/store/device/actions.test.ts
- ui/src/app/store/device/index.ts
- ui/src/app/store/device/reducers.test.ts
- ui/src/app/store/device/slice.ts
- ui/src/root-reducer.js
Migrate `device` to slice.
- visit dhcp form, ensure devices are still fetched.
Fixes: canonical-web-and-design/MAAS-design#921 …
> refactor(ui): add device slice

- ui/.betterer.results
- ui/src/app/Routes.tsx
- ui/src/app/base/actions/machine/machine.js
- ui/src/app/base/actions/machine/machine.test.js
- ui/src/app/base/reducers/machine/machine.js
- ui/src/app/base/reducers/machine/machine.test.js
- ui/src/app/machines/views/MachineDetails/MachineDetails.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineDetails.tsx
- ui/src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.tsx
- ui/src/app/machines/views/MachineDetails/MachineHeader/__snapshots__/MachineHeader.test.tsx.snap
- ui/src/app/machines/views/MachineDetails/MachineHeader/index.ts
- ui/src/app/machines/views/MachineDetails/MachineSummary/MachineSummary.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/MachineSummary.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/__snapshots__/MachineSummary.test.tsx.snap
- ui/src/app/machines/views/MachineDetails/MachineSummary/index.ts
- ui/src/app/machines/views/MachineDetails/__snapshots__/MachineDetails.test.tsx.snap
- ui/src/app/machines/views/MachineDetails/index.ts
- ui/src/app/machines/views/MachineList/MachineListHeader/ActionFormWrapper/OverrideTestForm/OverrideTestForm.js
- ui/src/app/machines/views/MachineList/MachineListHeader/ActionFormWrapper/OverrideTestForm/OverrideTestForm.test.js
- ui/src/app/machines/views/MachineList/MachineListTable/NameColumn/NameColumn.js
- ui/src/app/machines/views/MachineList/MachineListTable/NameColumn/__snapshots__/NameColumn.test.js.snap
- ui/src/app/settings/views/Dhcp/DhcpTarget/DhcpTarget.js
- ui/src/app/settings/views/Dhcp/DhcpTarget/DhcpTarget.test.js
- ui/src/app/settings/views/Dhcp/DhcpTarget/__snapshots__/DhcpTarget.test.js.snap
- Added routing for the machine details and added basic page structure.
- Go to the machine list and click on a machine.
- You should navigate to the machine details route and see the fqdn.
Fixes: canonical-web-and-design/MAAS-squad#2101
> feat(ui): added the machine details route

- ui/src/app/base/selectors/general/powerTypes.js
- ui/src/app/base/selectors/general/powerTypes.test.js
- ui/src/app/machines/views/AddChassis/AddChassisForm/AddChassisForm.js
- Add hardcoded list of power types that can be used with the `add_chassis` http method. The list was taken from [here](https://git.launchpad.net/maas/tree/src/maasserver/api/machines.py?h=2.8#n2520).
- Open the Add Chassis form and try to add a chassis with each power type.
- You should not get any errors about invalid power …
> 2.8: correctly filter list of power types for use in Add Chassis form

- ui/src/app/kvm/components/KVMMeter/KVMMeter.test.tsx
- ui/src/app/kvm/components/KVMMeter/KVMMeter.tsx
- ui/src/app/kvm/components/KVMResourcesCard/KVMResourcesCard.test.tsx
- ui/src/app/kvm/components/KVMResourcesCard/KVMResourcesCard.tsx
- ui/src/app/kvm/components/KVMResourcesCard/__snapshots__/KVMResourcesCard.test.tsx.snap
- ui/src/app/kvm/components/KVMResourcesCard/index.ts
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMAggregateResources/KVMAggregateResources.tsx
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMNumaResources/KVMNumaResources.test.tsx
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMNumaResources/KVMNumaResources.tsx
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMStorage/KVMStorage.tsx
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMSummary.tsx
- ui/src/app/store/pod/types.ts
- ui/src/app/utils/formatBytes.test.ts
- ui/src/app/utils/formatBytes.ts
- ui/src/testing/factories/index.ts
- ui/src/testing/factories/nodes.ts
- Removed all fake data from NUMA view and aggregate view.
- Populated NUMA view with API data. Next will be to populate the aggregate view using the same data.
- Check that the values listed on the NUMA view match what's given by the API. Note that master websocket API is currently sending fake NUMA data that has absurdly small …
> feat(ui): Replace fake NUMA data with API data.

- ui/src/app/kvm/components/KVMResourcesCard/KVMResourcesCard.tsx
- ui/src/app/kvm/components/KVMResourcesCard/__snapshots__/KVMResourcesCard.test.tsx.snap
- ui/src/scss/_patterns_buttons.scss
- Fixed bug where bespoke double row/sortable headers had different colours. Now `#111` is the default, and `#666` is the exception (as in the case of the KVM RAM tables)
- Updated hover colour to match Vanilla's sortable table headers
- Go to /r/kvm and check that both rows of the table header are `#111`
Fixes #1625
> fix(ui): fix inconsistent table header colours

- legacy/src/app/controllers/master.js
- root/src/index.ejs
- root/src/root-application.js
- root/src/scss/base.scss
- ui/src/index.js
- Handle errors when loading single-spa apps.
- Load maas-ui at a legacy url e.g. /MAAS/l/images (without having first visited a React url).
- Stop your proxy/single-spa server.
- Click on a React URL in the header.
- You should see a nice error message on the page.
Fixes: canonical-web-and-design/maas-ui#1618
> fix(root): handle network errors from single-spa

- ui/src/app/App.js
- Remove custom route handing in App on popState. This was required to work around a bug (see comment in diff), which no longer appears to be present, but also introduced the bug in question here. This has been removed.
- Reproduce steps in bug (visit react route, visit angular route, visit user prefs). Ensure no , appears in …
> fix(ui): remove routing hack

- .github/workflows/test.yml
- Cache and restore node_modules for ci runs.
- Split lint, test and build into separate jobs so that they run in parallel.
- The jobs should pass in CI and you should see each job listed separately.
> Yarn cache/parallel jobs

- root/src/index.ejs
- Add a message to the root template to warn users if JavaScript is disabled.
- Disable JavaScript in your browser (might be in your devtools settings).
- Load the ui. You should see a warning.
Fixes: canonical-web-and-design/maas-ui#1522
> feat(root): display a message when JavaScript is disabled

- root/src/root-application.js
- Don't show a warning if the mount is slow unless it takes longer than 30 seconds.
- Load a legacy page (refresh if you've navigated from a react view).
- You shouldn't see a warning in the console from single-spa.
> fix(root): don't show slow mount warnings for 30 seconds

- legacy/src/app/partials/node-details.html
- legacy/src/scss/tables/_patterns_double-row.scss
- In the network table in machine details long fabric names have been truncated.
- Edit a fabric name to be really long.
- Navigate to the machine details of a machine that uses that fabric.
- Click on the network tab and you should see the truncated fabric name.
Fixes: canonical-web-and-design/maas-ui#1572
> fix(legacy): truncate long fabric names in machine details

- ui/src/app/kvm/components/KVMActionFormWrapper/DeleteForm/DeleteForm.tsx
- ui/src/app/kvm/components/KVMActionFormWrapper/RefreshForm/RefreshForm.tsx
- ui/src/app/kvm/views/KVMList/KVMListHeader/KVMListHeader.tsx
- ui/src/app/kvm/views/KVMList/KVMListTable/KVMListTable.tsx
- ui/src/app/store/pod/selectors.test.ts
- ui/src/app/store/pod/selectors.ts
- Created separate selectors for selected KVMs and selected RSDs. Also renamed some variables ithe KVM components to be clearer in this regard.
- Check that the KVM list and details pages still load the data correctly.
- Check that you can select/unselect properly in the KVM list
Fixes #1633
Related Launchpad maas issue in the …
> Separate out selected KVM and RSD selectors

- legacy/src/app/directives/maas_obj_form.js
- legacy/src/app/directives/power_parameters.js
- legacy/src/app/directives/tests/test_maas_obj_form.js
- legacy/src/app/partials/nodes-list.html
- Updated forms to use unique ids so that there aren't duplicate ids on the page.
There should be no duplicate console warnings for any of the following:
- Visit devices. 
- Add device and supply an IP address (need to change ip assignment for the field to appear).
- Visit controllers.
- View a controller and open the Configuration tab. Click edit for 'Power …
> fix(legacy): fixed duplicate form ids

- legacy/src/app/controllers/node_details.js
- Fix the routing when navigating back/forward between tabs for the node details.
- Load a machine/controller or device details page.
- Click on a few tabs.
- Use your browser to navigate forward/back. The tabs and URL should change as you navigate.
Fixes: canonical-web-and-design/maas-ui#1504
> fix(legacy): fix the back button for node details tabs

- ui/src/app/kvm/components/KVMResourcesCard/KVMResourcesCard.test.tsx
- ui/src/app/kvm/components/KVMResourcesCard/KVMResourcesCard.tsx
- ui/src/app/kvm/components/KVMResourcesCard/_index.scss
- Don't display hugepage RAM row(s) if it doesn't actually exist.
- Fixed a FF alignment bug.
- Go to the KVM details page of bolla using Firefox
- Check that there is no row for hugepages
- Check that the table headers don't take up half the height of the cell
Fixes canonical-web-and-design/MAAS-squad#2120
Related Launchpad …
> fix(ui): only show hugepage RAM in table if it exists

- ui/.betterer.results
- ui/src/app/Routes.js
- ui/src/app/kvm/utils.ts
- ui/src/app/kvm/views/KVMList/KVMListHeader/KVMListHeader.tsx
- ui/src/app/kvm/views/KVMList/KVMListTable/_index.scss
- ui/src/app/rsd/components/RSDActionFormWrapper/DeleteForm/DeleteForm.test.tsx
- ui/src/app/rsd/components/RSDActionFormWrapper/DeleteForm/DeleteForm.tsx
- ui/src/app/rsd/components/RSDActionFormWrapper/DeleteForm/index.ts
- ui/src/app/rsd/components/RSDActionFormWrapper/RSDActionFormWrapper.test.tsx
- ui/src/app/rsd/components/RSDActionFormWrapper/RSDActionFormWrapper.tsx
- ui/src/app/rsd/components/RSDActionFormWrapper/RefreshForm/RefreshForm.test.tsx
- ui/src/app/rsd/components/RSDActionFormWrapper/RefreshForm/RefreshForm.tsx
- ui/src/app/rsd/components/RSDActionFormWrapper/RefreshForm/index.ts
- ui/src/app/rsd/components/RSDActionFormWrapper/index.ts
- ui/src/app/rsd/views/RSD.tsx
- ui/src/app/rsd/views/RSDList/RSDList.tsx
- ui/src/app/rsd/views/RSDList/RSDListHeader/RSDListActionMenu/RSDListActionMenu.test.tsx
- ui/src/app/rsd/views/RSDList/RSDListHeader/RSDListActionMenu/RSDListActionMenu.tsx
- ui/src/app/rsd/views/RSDList/RSDListHeader/RSDListActionMenu/index.ts
- ui/src/app/rsd/views/RSDList/RSDListHeader/RSDListHeader.test.tsx
- ui/src/app/rsd/views/RSDList/RSDListHeader/RSDListHeader.tsx
- ui/src/app/rsd/views/RSDList/RSDListHeader/index.ts
- ui/src/app/rsd/views/RSDList/RSDListTable/RSDListTable.test.tsx
- ui/src/app/rsd/views/RSDList/RSDListTable/RSDListTable.tsx
- ui/src/app/rsd/views/RSDList/RSDListTable/_index.scss
- ui/src/app/rsd/views/RSDList/RSDListTable/index.ts
- ui/src/app/rsd/views/RSDList/index.ts
- ui/src/scss/_utilities.scss
- ui/src/scss/index.scss
- The RSD components have mostly been copied over from the KVM components, with minor changes where necessary. I originally tried to just have a single component `Pod` that could be given a prop `type="rsd"` or `type="kvm"` but the amount of inline conditionals in the component got pretty out of hand. So I think this is a cleaner option that can be refactored after the fact if necessary.
- For now the "Add RSD" button takes you to the form on the machine list but I'll create a component for that next. …
> feat(ui): Build RSD list in React

- ui/.betterer.results
- ui/src/app/rsd/views/RSDList/AddRSDForm/AddRSDForm.test.tsx
- ui/src/app/rsd/views/RSDList/AddRSDForm/AddRSDForm.tsx
- ui/src/app/rsd/views/RSDList/AddRSDForm/AddRSDFormFields/AddRSDFormFields.tsx
- ui/src/app/rsd/views/RSDList/AddRSDForm/AddRSDFormFields/index.ts
- ui/src/app/rsd/views/RSDList/AddRSDForm/index.ts
- ui/src/app/rsd/views/RSDList/RSDList.tsx
- Built AddRSDForm component, which is essentially the AddKVMForm component with the `rsd` type preselected.
- Go to /r/rsd and click the "Add RSD" button
- Check that you are redirected to /r/rsd/add and the Add RSD form shows
- Fill in the fields and click Save
- Check that the websocket request matches [the …
> feat(ui): Build AddRSDForm component for RSD list

- ui/.betterer.results
- ui/src/app/base/actions/machine/machine.js
- ui/src/app/base/actions/machine/machine.test.js
- ui/src/app/base/components/ActionForm/ActionForm.tsx
- ui/src/app/base/hooks.js
- ui/src/app/machines/views/MachineList/MachineListHeader/ActionFormWrapper/ActionFormWrapper.tsx
- ui/src/app/machines/views/MachineList/MachineListHeader/ActionFormWrapper/FieldlessForm/FieldlessForm.js
- ui/src/app/machines/views/MachineList/MachineListHeader/ActionFormWrapper/FieldlessForm/FieldlessForm.test.js
- ui/src/app/machines/views/MachineList/MachineListHeader/ActionFormWrapper/FieldlessForm/__snapshots__/FieldlessForm.test.js.snap
- ui/src/app/machines/views/MachineList/MachineListHeader/ActionFormWrapper/MarkBrokenForm/MarkBrokenForm.test.tsx
- ui/src/app/machines/views/MachineList/MachineListHeader/ActionFormWrapper/MarkBrokenForm/MarkBrokenForm.tsx
- ui/src/app/machines/views/MachineList/MachineListHeader/ActionFormWrapper/MarkBrokenForm/MarkBrokenFormFields/MarkBrokenFormFields.tsx
- ui/src/app/machines/views/MachineList/MachineListHeader/ActionFormWrapper/MarkBrokenForm/MarkBrokenFormFields/_index.scss
- ui/src/app/machines/views/MachineList/MachineListHeader/ActionFormWrapper/MarkBrokenForm/MarkBrokenFormFields/index.ts
- ui/src/app/machines/views/MachineList/MachineListHeader/ActionFormWrapper/MarkBrokenForm/index.ts
- ui/src/app/machines/views/MachineList/MachineListTable/StatusColumn/StatusColumn.js
- ui/src/app/machines/views/MachineList/MachineListTable/StatusColumn/StatusColumn.test.js
- ui/src/app/machines/views/MachineList/MachineListTable/StatusColumn/__snapshots__/StatusColumn.test.js.snap
- ui/src/scss/_patterns_forms.scss
- ui/src/scss/index.scss
A description can now be provided when marking a machine broken,
which now displays the text under status on the machine listing.
designs:
https://app.zeplin.io/project/5e6a623cde850113ba28d75b/screen/5e7d035047a0278e20c0aa72
- Select a few allocated machines, and select the mark broken action.
- Add a description and mark …
> feat(ui): add description field for marking machine broken

- shared/src/components/Header/Header.js
- shared/src/components/Header/Header.test.js
- Match sub-urls to the header section so that the nav is highlighted correctly.
- Click on each nav item in the header and then click on a details page.
- Each page should be highlighted in the header with the correct section.
Fixes: canonical-web-and-design/maas-ui#873
> fix(header): highlight nav for sub urls

- legacy/src/app/partials/intro.html
- legacy/src/app/partials/nodes-list.html
- legacy/src/app/partials/vlan-details.html
- ui/.betterer.results
- ui/src/app/base/components/FormCard/_index.scss
- ui/src/app/base/components/FormCardButtons/FormCardButtons.js
- ui/src/app/base/components/FormikForm/FormikForm.tsx
- ui/src/app/base/components/FormikFormContent/FormikFormContent.js
- ui/src/app/machines/views/AddChassis/AddChassisForm/AddChassisForm.js
- ui/src/app/machines/views/AddMachine/AddMachineForm/AddMachineForm.js
- ui/src/app/settings/components/SettingsTable/SettingsTable.js
- ui/src/app/settings/components/SettingsTable/_index.scss
- ui/src/app/settings/views/Dhcp/DhcpList/DhcpList.js
- Add a number of help links to forms and lists.
- Visit each of the pages from https://github.com/canonical-web-and-design/maas-ui/issues/861 and check that the help links appear as per the screenshot.
Fixes: canonical-web-and-design/maas-ui#861
> feat: add docs links

- ui/src/app/machines/views/MachineList/MachineListHeader/ActionFormWrapper/ActionFormWrapper.tsx
- ui/src/app/machines/views/MachineList/MachineListHeader/ActionFormWrapper/MarkBrokenForm/MarkBrokenForm.tsx
- Adding missing `markingBrokenSelected` selector to the mark broken form, which determines when to close the form on success.
- Wrapped `ActionFormWrapper`'s `actionDisabled` logic in a `useEffect` so that it only updates when the relevant bits of state change.
- Select a few machines and choose "Mark broken" from the action …
> fix(ui): correctly determine when to display machine list non-actionable warning

- legacy/src/app/directives/pod-details/kvm_storage_dropdown.js
- Added some undefined object guards to KVM `poolOverCapacity` function
- N/A
Fixes #1705
> fix(legacy): add undefined object guards to KVM poolOverCapacity function

- ui/.betterer.results
- ui/.betterer.ts
Betterer's "migrate js files to ts" test was counting all files, including dist etc. which lead to inconsistent counts. We really only care about the files in src.
- Run `yarn betterer` before and after a build to confirm the count is consistent. Confirm your count doesn't deviate from this PR's count (449).
Fixes: # .
Related …
> fix(ci): betterer js counts only src dir

- ui/.betterer.results
- ui/src/app/kvm/components/PodResourcesCard/_index.scss
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMSummary.test.tsx
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMSummary.tsx
- ui/src/app/machines/views/MachineList/MachineListTable/MachineListTable.js
- ui/src/app/machines/views/MachineList/_index.scss
- ui/src/scss/_utilities.scss
- Hide NUMA toggle if no numa data present
- Adjust VM dropdown padding
- Fix VM dropdown FQDN focus state
- Improve alignment of RAM table with the rest of the data
- Stack NUMA toggle on small screens
- Go to a KVM details page and open a VM dropdown
- Check that the padding is slightly tighter and the focus state on FQDN does …
> fix(ui): address SR-IOV/NUMA design feedback issues

- ui/.betterer.results
- ui/src/analytics.js
- ui/src/app/base/components/ActionForm/ActionForm.test.tsx
- ui/src/app/base/components/FormikForm/FormikForm.test.js
- ui/src/app/base/components/FormikForm/FormikForm.tsx
- ui/src/app/base/components/UserForm/UserForm.test.js
- ui/src/app/base/hooks.js
- ui/src/app/kvm/components/PodStorage/PodStorage.test.tsx
- ui/src/app/kvm/components/PodStorage/PodStorage.tsx
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMNumaResources/KVMNumaResources.test.tsx
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMNumaResources/KVMNumaResources.tsx
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMSummary.test.tsx
- ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMSummary.tsx
- ui/src/app/machines/views/MachineList/MachineListHeader/ActionFormWrapper/DeployForm/DeployForm.test.tsx
- ui/src/app/machines/views/MachineList/MachineListHeader/ActionFormWrapper/DeployForm/DeployForm.tsx
- ui/src/app/machines/views/MachineList/MachineListHeader/ActionFormWrapper/SetPoolForm/SetPoolForm.test.js
- ui/src/app/machines/views/MachineList/MachineListHeader/ActionFormWrapper/SetPoolForm/SetPoolFormFields/SetPoolFormFields.test.js
- ui/src/app/machines/views/MachineList/MachineListHeader/ActionFormWrapper/SetZoneForm/SetZoneForm.test.js
- ui/src/app/rsd/views/RSDDetails/RSDSummary/RSDSummary.test.tsx
- ui/src/app/settings/views/Configuration/GeneralForm/GeneralForm.tsx
Refactors the useSendAnalytics hook into three hooks, which removes the need to check for analyticsEnabled in calling code:
sendAnalytics - sends a google analytics event if window.ga defined.
useSendAnalytics - wraps sendAnalytics and sends an event if the analyticsEnabled setting is true. Now returns a function, allowing this to be used for callbacks (e.g. in an onClick handler)
useSendAnalyticsWhen - wraps useSendAnalytics and provides an additional sendCondition param.
Additionally, fixes some remaining tests that weren't setting update state with `rootStateFactory`.
- [A local snap …
> Refactor useSendAnalytics 

- ui/src/app/settings/views/Scripts/ScriptsUpload/ScriptsUpload.js
- ui/src/app/settings/views/Scripts/ScriptsUpload/ScriptsUpload.test.js
Removes mimetype checks for file uploads.
See #1731
* Ensure uploading a script from Settings, and deploying a machine with user data works as expeced.
Backport https://github.com/canonical-web-and-design/maas-ui/pull/1731
Fix lp#1896179
In general, please propose fixes …
> fix(ui): remove mimetype checks for file uploads

- legacy/src/app/factories/domains.js
- legacy/src/app/factories/tests/test_domains.js
* Call `domain.delete_address_record` rather than `domain.deleteresource` to ensure only that specific record is deleted.
- Select a domain from /dns
- create a DNS record like "test" A "1.2.3.4"
- create a DNS record like "test" AAAA "2001::1"
- select one of those and select "remove record"
- ensure only the selected record is …
> fix(legacy): call delete_address_record when removing dns resources

- ui/src/app/machines/views/MachineList/MachineListHeader/ActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.test.tsx
- ui/src/app/machines/views/MachineList/MachineListHeader/ActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.tsx
- Explicitly clear kernel selection when changing the OS or release in the deploy form.
- Open the deploy form for a machine
- Change the OS/release to Ubuntu 18.04, then select a non-default kernel (e.g. "ga-18.04")
- Change the release to Ubuntu 20.04
- Check that the form submits successfully, i.e. there is no error about the …
> fix(ui): clear kernel selection on OS/release change in deploy form

- ui/src/app/base/components/Meter/Meter.tsx
- ui/src/app/base/hooks.js
- ui/src/app/machines/views/Machines.js
- ui/src/app/settings/views/Configuration/GeneralForm/GeneralForm.tsx
- Replace hooks with those migrated to react-components.
- Visit the kvm page. Resizing the window should update the segment widths.
- Visit the machine list and set some filters. Clicking on the pools tab should clear the filters in the URL.
- Go to the general settings. Enabling/disabling analytics should refresh the page.
Fixes: …
> refactor(ui): use hooks from react-components

- legacy/src/app/controllers/master.js
- ui/src/app/App.js
- Generate full paths for the header nav links.
- Visit a react URL and hover a link to a legacy page, it should show the correct path.
- Visit an angular URL and hover a link to a react page, it should show the correct path.
Fixes: canonical-web-and-design/maas-ui#1737
> fix(legacy, ui): fix nav links to have full paths

- integration/cypress/integration/machines/add.spec.ts
- Use a more reliable method for getting the success message when adding a machine in the cypress
test.
No QA.
Fixes: canonical-web-and-design/maas-ui#1342.
> test(cypress): improve the cypress machine add test

- legacy/src/app/controllers/node_details.js
- legacy/src/app/partials/cards/controller.html
- legacy/src/app/partials/cards/machine-overview.html
- shared/src/index.js
- shared/src/utils.js
- shared/src/utils.test.js
- Show the full power type name on controller and machine details
- Visit a machine and controller summary. Both should display the full power type name (specifically IPMI should be capitalised).
Fixes: canonical-web-and-design/maas-ui#987
> fix(legacy): show the full power type name

- legacy/src/app/directives/notifications.js
- legacy/src/app/directives/tests/test_notifications.js
- legacy/src/app/partials/nodelist/notifications.html
- ui/src/app/base/components/NotificationGroup/NotificationGroup.test.tsx
- ui/src/app/base/components/NotificationGroup/NotificationGroup.tsx
- Don't display the dismiss all link if no notifications in the group can be dismissed.
- Create some notifications that can and can't be dismissed.
- On both a react and angular page check that the dismiss all link is hidden for any groups that have no dismissible notifications.
Fixes: canonical-web-and-design/maas-ui#1287
> fix(notifications): fix dismiss all link appearing when none can be dismissed

- ui/package.json
- yarn.lock
- Updated react-components to 0.13.0 which fixes a duplicate slider ID bug
- Go to a KVM config page (e.g. `/MAAS/r/kvm/123/edit`)
- Check that there is no warning in the console about duplicate ids
Fixes #1708
> chore(deps): update react-components to 0.13.0

- shared/src/components/Footer/Footer.js
- shared/src/components/Footer/__snapshots__/Footer.test.js.snap
The offline docs are not provided by the MAAS itself. This change links to the offline docs from the
footer links. This change does not include all docs links across the UI.
Fixes https://github.com/canonical-web-and-design/MAAS-squad/issues/2125
**Two ways**
- Build a new maas …
> docs(shared): update the docs lnks in the footer to the offline docs

- legacy/webpack.prod.js
- ui/package.json
- Minimise the legacy js.
- Remove the profiler from ui.
None, CI should build the files.
> build(legacy, ui): minimise legacy and remove profile from ui

- legacy/src/app/directives/boot_images.js
- legacy/src/app/directives/tests/test_boot_images.js
- Preselect default commissioning release when using custom image source, as opposed to only selecting bionic amd64 (which is still used as a fallback if commissioning release is unset).
- Go to /MAAS/r/settings/configuration/commissioning and change the default Ubuntu release
- Go to /MAAS/l/images and choose "Custom".
- Use …
> fix(legacy): preselect default commissioning release when using custom image source

- ui/src/app/settings/views/Configuration/CommissioningForm/CommissioningForm.tsx
- ui/src/app/settings/views/Configuration/CommissioningFormFields/CommissioningFormFields.tsx
- Add validation for IPMI username configuration (3-16 characters, no spaces)
- Use paragraph styling for "MAAS generated IPMI user privilege level" to ensure it doesn't render in italics
- Visit settings | configuration | commissioning
- Ensure only IPMI usernames with no spaces and between 3-16 characters can be saved
Fixes: …
> fix(ui): add validation for ipmi username config

- legacy/src/app/controllers/node_details.js
- legacy/src/app/controllers/tests/test_node_details.js
- legacy/src/app/partials/cards/machine-overview.html
- Show a VM as "NUMA-aligned on X" if its host has only one NUMA node, even if that VM has not specifically been pinned to a node (because it's already implied).
- Using bolla (which has only one NUMA node), go to the Machine details page of one of its VMs.
- Check that the summary says it's `NUMA aligned on node 0 of bolla` …
> fix(legacy): show VM as NUMA-aligned if its host has only one NUMA node

- shared/src/components/Footer/Footer.js
- Remove the hardcoded offline docs prefix and use the basename from the env var.
- Load the ui and click on (or inspect) the offline docs link in the footer, it should start with "/MAAS".
Fixes: canonical-web-and-design/maas-ui#1762
> fix(footer): prefix the offline docs with the provided basename

- legacy/src/app/partials/cards/network.html
- On the machine network summary, only apply `overflow: visible` to interfaces that are relayed because those are the only ones that need an `[i]` tooltip. 
- Go to the machine details summary of a machine that has a relayed VLAN (e.g. `fun-mammal` on bolla).
- Check that the tooltip in the DHCP column still works, next to …
> fix(legacy): correctly truncate network summary DHCP column

- legacy/src/app/controllers/node_details.js
- legacy/src/app/controllers/tests/test_node_details.js
- legacy/src/app/services/manager.js
- Only fetch a single machine on machine details, rather than every machine.
- Ensure the machine details loads, and that all features continue to work as expected (network, storage, logs etc)
Fixes: # . …
> fix(legacy): only fetch the current machine on machine details

- integration/cypress/integration/kvm/list.spec.ts
- integration/cypress/integration/legacy/azs.spec.ts
- integration/cypress/integration/legacy/controllers.spec.ts
- integration/cypress/integration/legacy/devices.spec.ts
- integration/cypress/integration/legacy/dns.spec.ts
- integration/cypress/integration/legacy/images.spec.ts
- integration/cypress/integration/legacy/subnets.spec.ts
- integration/cypress/integration/preferences/base.spec.ts
- integration/cypress/integration/settings/base.spec.ts
- integration/cypress/integration/settings/users/add.spec.ts
- integration/cypress/integration/settings/users/list.spec.ts
- legacy/src/app/partials/images.html
- legacy/src/app/partials/nodes-list.html
- Added integration tests that check that the heading and navigation highlight is correct for Devices,
Controllers, KVM, Images, DNS, AZs, Subnets and user preferences.
- Using a test MAAS, run a local UI server with `yarn start` (make sure username/pw is admin/test, otherwise edit the cypress login util)
- In a separate …
> test(legacy,ui): add simple integration smoke tests for all pages in the navigation

- integration/cypress/integration/pools/list.spec.ts
- Add cypress tests for devices and pools
- Run cypress tests locally, should pass.
Fixes: https://github.com/canonical-web-and-design/MAAS-squad/issues/2229
In general, please propose fixes against *master* rather than release branches (e.g. 2.7), unless the fix is only …
> test(ui): add cypress tests for devices and pools

- ui/src/scss/_vanilla-overrides.scss
- Add hotfix for react-components bug that was causing `.u-hide` not to work on expanding tables. We can remove it once the issue is fixed upstream.
- Navigate to a settings table, /MAAS/r/settings/dhcp
- Check that the table headers are properly aligned with the cell contents
Fixes #1767
> fix(ui): fix expanding table header misalignment

- .github/workflows/cypress.yml
- integration/cypress.json
- integration/cypress/integration/base/header.spec.ts
- integration/cypress/integration/login/login.spec.ts
- integration/cypress/integration/utils.ts
- legacy/src/app/controllers/master.js
- ui/src/app/App.js
- In the Cypress tests, the intro is skipped by setting a cookie. This allowed access to the rest of the app but did not update the navigation. This was only apparent on fresh MAAS installs that had not yet completed the setup or user intros.
- Fixed screenshot upload and removed video upload
- Checkout master, run the UI (`yarn start`) and run Cypress in separate terminals (`yarn cypress-open`).
- Click "Run all specs" in the Cypress interactive runner and confirm that the tests regarding navigation all fail, except for user preferences.
- Checkout this branch
- Create a new user and update the `integration/cypress.json` env variables with their credentials.
- Run all Cypress specs and check that all of the tests regarding navigation pass. There will be some failed tests due to MAAS …
> fix(cypress): fix cypress tests rendering incorrect navigation on new MAAS installs

- legacy/src/scss/_patterns_navigation.scss
- legacy/src/scss/build.scss
- Restore the legacy navigation css so that it looks correct when the hardware menu is shown.
- Navigate to a legacy page.
- Resize your window until the hardware menu is shown.
- Check that the items in the menu don't also appear in the main nav.
Fixes https://github.com/canonical-web-and-design/maas-ui/issues/1799
> fix(legacy): fix the legacy navigation css

- integration/cypress/integration/base/header.spec.ts
- We don't currently have a method for adding RSDs in our Cypress CI setup (fake or real), so the test has been removed as it will otherwise always fail.
- No QA
> fix(cypress): remove header RSD test

- ui/.betterer.results
- ui/src/app/App.test.tsx
- ui/src/app/App.tsx
- ui/src/testing/factories/state.ts
- When using external auth return to the external auth login screen after logging out.
- Update App to typescript.
- Setup your maas to use external auth (ask me).
- Log in and then log out, you should be returned to the external auth login screen.
Fixes: canonical-web-and-design/maas-ui#1794.
> fix(ui): return to the correct login screen when logging out with external auth

- ui/.betterer.results
- ui/src/__snapshots__/root-reducer.test.js.snap
- ui/src/app/base/actions/machine/machine.js
- ui/src/app/base/actions/machine/machine.test.js
- ui/src/app/base/reducers/machine/machine.js
- ui/src/app/base/reducers/machine/machine.test.js
- ui/src/app/machines/components/ActionFormWrapper/CommissionForm/CommissionForm.test.tsx
- ui/src/app/machines/components/ActionFormWrapper/DeployForm/DeployForm.test.tsx
- ui/src/app/machines/components/ActionFormWrapper/FieldlessForm/FieldlessForm.test.js
- ui/src/app/machines/components/ActionFormWrapper/MarkBrokenForm/MarkBrokenForm.test.tsx
- ui/src/app/machines/components/ActionFormWrapper/OverrideTestForm/OverrideTestForm.test.js
- ui/src/app/machines/components/ActionFormWrapper/SetPoolForm/SetPoolForm.test.js
- ui/src/app/machines/components/ActionFormWrapper/SetZoneForm/SetZoneForm.test.js
- ui/src/app/machines/components/ActionFormWrapper/TagForm/TagForm.test.js
- ui/src/app/machines/components/ActionFormWrapper/TestForm/TestForm.test.js
- ui/src/app/machines/hooks.tsx
- ui/src/app/machines/views/MachineDetails/MachineDetails.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineDetails.tsx
- ui/src/app/store/machine/selectors.test.ts
- ui/src/app/store/machine/selectors.ts
- ui/src/app/store/machine/types.ts
- ui/src/testing/factories/state.ts
- Added action/selectors/reducers for setting active machines. Setting a machine as active lets the server know to send all the data of that machine whenever it is updated, otherwise it only sends the data required for the machine list.
- Updated machine reducer tests to use the test factories
- Navigate to a machine details …
> feat(ui): add action/selector/reducer for setting active machines.

- ui/package.json
- ui/src/app/base/components/ScriptStatus/ScriptStatus.js
- ui/src/app/machines/views/MachineList/MachineListTable/NameColumn/NameColumn.js
- ui/src/scss/_patterns_double-row.scss
- ui/src/scss/_vanilla-overrides.scss
- yarn.lock
- Fix the trunction of some content in the machine list.
- Upgrade react-components. 
- Remove a Vanilla override.
- View the machine list.
- Reduce your window width until the fabric names are being cut off. They should truncate with ellipsis.
- Reduce your window width again until the ip addresses are being cut off. They should truncate with ellipsis.
- …
> fix(ui): fix the truncation in the machine table

- ui/.betterer.results
- ui/package.json
- ui/src/app/machines/views/MachineDetails/MachineDetails.tsx
- ui/src/app/machines/views/MachineDetails/MachineNotifications/MachineNotifications.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineNotifications/MachineNotifications.tsx
- ui/src/app/machines/views/MachineDetails/MachineNotifications/index.ts
- ui/src/app/machines/views/MachineDetails/MachineSummary/_index.scss
- ui/src/app/store/machine/utils.test.tsx
- ui/src/app/store/machine/utils.ts
- ui/src/testing/factories/index.ts
- ui/src/testing/factories/nodes.ts
- yarn.lock
- Add notifications and warnings to the machine details.
- Add hooks for different machine states.
- There are a number of different states to make these notifications appear, I recommend using sampledata which shows most of these notifications or modify `MachineNotifications` to make all the notifications active.
Fixes: …
> feat(ui): add the machine details notifications

- ui/.betterer.results
- ui/src/app/machines/views/MachineDetails/MachineSummary/MachineSummary.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/NetworkCard/NetworkCard.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/NetworkCard/NetworkCard.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/NetworkCard/NetworkCardTable/NetworkCardTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/NetworkCard/NetworkCardTable/NetworkCardTable.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/NetworkCard/NetworkCardTable/index.ts
- ui/src/app/machines/views/MachineDetails/MachineSummary/NetworkCard/_index.scss
- ui/src/app/machines/views/MachineDetails/MachineSummary/NetworkCard/index.ts
- ui/src/app/machines/views/MachineDetails/MachineSummary/_index.scss
- ui/src/app/store/machine/types.ts
- ui/src/app/utils/formatSpeedUnits.js
- ui/src/scss/_patterns_grids.scss
- ui/src/scss/index.scss
- ui/src/testing/factories/index.ts
- ui/src/testing/factories/nodes.ts
- Rebuilt Network card in React. Currently missing the test bit.
- Go to the machine details page and check that the network card matches the old angular design and looks good on all screen sizes.
- Check that the interfaces group correctly (by vendor, then product, then version).
- Check that the DHCP relay tooltip works as …
> feat(ui): build the machine details network card

- ui/src/app/base/components/Section/_index.scss
- ui/src/app/base/components/SectionHeader/SectionHeader.test.tsx
- ui/src/app/base/components/SectionHeader/SectionHeader.tsx
- ui/src/app/base/components/SectionHeader/__snapshots__/SectionHeader.test.tsx.snap
- ui/src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.tsx
- ui/src/app/store/machine/selectors.test.ts
- ui/src/app/store/machine/selectors.ts
- Show the power and locked status to the machine details header.
- Go to a machine's details. The power state should be in the header.
- View a locked machine, there should be a lock icon in the header.
Fixes: canonical-web-and-design/maas-squad#2103.
> feat(ui): add the machine's power and locked status

- ui/.betterer.results
- ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/MemoryCard/MemoryCard.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/MemoryCard/MemoryCard.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/MemoryCard/index.ts
- ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/OverviewCard.tsx
-add memory card to machine details overview
* Ensure the memory card renders as expected.
* Ensure links in the results list take you to the testing tab.
* With a machine with no memory tests run, ensure the "Test memory..." link opens the testing take action button with the appropriate memory tests selected.
Fixes: # .
Related …
> feat(ui): add memory card to machine details overview

- ui/.betterer.results
- ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/OverviewCard.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/StorageCard/StorageCard.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/StorageCard/StorageCard.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/StorageCard/index.ts
- add storage card to machine details overview
* Ensure the storage card renders as expected.
* Ensure links in the results list take you to the testing tab.
* With a machine with no storage tests run, ensure the "Test storage..." link opens the testing take action button with the appropriate memory tests selected.
Fixes: # . …
> feat(ui): add storage card to machine details overview

- ui/.betterer.results
- ui/src/app/base/hooks.js
- ui/src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.tsx
- Added a power actions dropdown next to the power status of the machine. Originally I was going to add "Check power" to the take action menu, but it was a bit awkward because the rest of the actions lived in `general.machineActions` and required a particular shape. Besides, this was considered the ideal solution in https://github.com/canonical-web-and-design/MAAS-squad/issues/2104#issuecomment-686404038
- …
> feat(ui): add power actions to machine details header

- ui/.betterer.results
- ui/src/app/base/enum.ts
- ui/src/app/machines/components/ActionFormWrapper/TestForm/TestForm.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/MachineSummary.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/NetworkCard/NetworkCard.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/NetworkCard/NetworkCard.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/CpuCard/CpuCard.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/CpuCard/CpuCard.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/MemoryCard/MemoryCard.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/StorageCard/StorageCard.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/TestResults/TestResults.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/TestResults/TestResults.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/TestResults/index.ts
- move overview test results to TestResults component
- Ensure overview cards still render correctly, open appropriate testing modals and link to testing tab.
Fixes: #1837 
In general, please propose fixes against *master* rather than release branches (e.g. 2.7), unless the …
> refactor(ui): move overview test results to TestResults component

- legacy/src/app/partials/domain-details.html
- Use correct key for address record TTL
- Edit the TTL for an address record.
- Ensure it is saved correctly.
Fixes: # .
In general, please propose fixes against *master* rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. …
> fix(legacy): correctly set ttl for address records

- ui/src/app/base/components/FormikForm/FormikForm.test.js
- ui/src/app/base/components/FormikForm/FormikForm.tsx
- ui/src/app/base/components/FormikFormButtons/FormikFormButtons.js
- ui/src/app/base/components/FormikFormButtons/FormikFormButtons.test.js
- ui/src/app/base/components/FormikFormContent/FormikFormContent.js
- ui/src/app/base/components/FormikFormContent/FormikFormContent.test.js
- ui/src/app/base/components/SectionHeader/SectionHeader.tsx
- ui/src/app/base/components/UserForm/UserForm.js
- ui/src/app/base/reducers/machine/machine.js
- ui/src/app/base/reducers/machine/machine.test.js
- ui/src/app/machines/components/ActionFormWrapper/FieldlessForm/__snapshots__/FieldlessForm.test.js.snap
- ui/src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.tsx
- ui/src/app/machines/views/MachineDetails/MachineHeader/MachineName/MachineName.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineHeader/MachineName/MachineName.tsx
- ui/src/app/machines/views/MachineDetails/MachineHeader/MachineName/__snapshots__/MachineName.test.tsx.snap
- ui/src/app/machines/views/MachineDetails/MachineHeader/MachineName/_index.scss
- ui/src/app/machines/views/MachineDetails/MachineHeader/MachineName/index.ts
- ui/src/app/machines/views/MachineDetails/MachineHeader/MachineNameFields/MachineNameFields.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineHeader/MachineNameFields/MachineNameFields.tsx
- ui/src/app/machines/views/MachineDetails/MachineHeader/MachineNameFields/__snapshots__/MachineNameFields.test.tsx.snap
- ui/src/app/machines/views/MachineDetails/MachineHeader/MachineNameFields/index.ts
- ui/src/app/settings/views/Users/UserForm/UserForm.tsx
- ui/src/scss/_utilities.scss
- ui/src/scss/index.scss
- Add the form for editing the machine name from the machine details header.
- View a locked machine and click on the machine name, nothing should happen.
- View a machine you can edit and click on the machine name, the form should appear.
- Edit the machine name or domain and click Save, it should save the details.
Fixes: …
> feat(ui): edit machine name from the details header

- shared/src/utils.js
- ui/.betterer.results
- ui/src/app/machines/views/MachineDetails/MachineSummary/NetworkCard/NetworkCard.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/CpuCard/CpuCard.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/DetailsCard/DetailsCard.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/DetailsCard/DetailsCard.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/DetailsCard/index.ts
- ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/MemoryCard/MemoryCard.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/OverviewCard.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/StorageCard/StorageCard.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/TestResults/TestResults.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/TestResults/TestResults.tsx
- ui/src/app/store/machine/types.ts
- ui/src/app/store/machine/utils.ts
- ui/src/app/store/utils/selectors.ts
- add machine summary details card
- Ensure the details card renders as expected
- Ensure links to the configuration tab render with edit permissions (admin)
Fixes:  canonical-web-and-design/MAAS-squad#2108 …
> ui(feat): add machine summary details card

- legacy/src/app/directives/maas_obj_form.js
- legacy/src/app/partials/domain-details.html
maas-obj-form apparently doesn't support dynamic keys. 
- use ng-if rather than dynamic maas-obj-form key
- visit /domains
- ensure you can create an A record with a TTL without error
- ensure you can create a non-A record (e.g. TXT) with a TTL without error
Fixes: # .
In …
> fix(legacy): use ng-if rather than dynamic maas-obj-form key

- ui/.betterer.results
- ui/src/app/machines/views/MachineDetails/MachineSummary/NetworkCard/NetworkCard.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/NumaCard/NumaCard.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/OverviewCard.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/StatusCard/StatusCard.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/StorageCard/StorageCard.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/_index.scss
- ui/src/app/machines/views/MachineDetails/MachineSummary/SummaryNotifications/SummaryNotifications.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/SummaryNotifications/SummaryNotifications.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/SystemCard/SystemCard.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/TestResults/TestResults.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/_index.scss
- ui/src/scss/_utilities.scss
- Improved general spacing in summary tab
- Changed the spinners to (hopefully) be less jarring
- Fixed a small bug where the notifications would render before architectures had loaded, causing a flash of an error notification if bootstrapping the app from the details page.
- Check that the react summary tab looks basically the …
> feat(ui): improve summary tab styling

- legacy/src/app/controllers/node_details.js
- legacy/src/app/controllers/tests/test_node_details.js
- legacy/src/app/partials/nodedetails/deploy-options.html
- legacy/src/app/services/osblacklist.js
- ui/src/app/machines/components/ActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.test.tsx
- ui/src/app/machines/components/ActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.tsx
- Updated deploy forms (legacy details + react list) to allow choosing Ubuntu 20.04 LTS when registering as a KVM host.
- Go to the machine list and choose "Deploy" from the action menu
- Check that choosing Ubuntu 18.04 or 20.04 enables the KVM checkbox
- Check that choosing anything else disables the checkbox and unchecks it …
> feat(ui): allow Ubuntu 20.04 LTS to be deployed as a KVM host

- ui/.betterer.results
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AvailableStorageTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AvailableStorageTable.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/index.ts
- ui/src/app/machines/views/MachineDetails/MachineStorage/FilesystemsTable/FilesystemsTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/FilesystemsTable/FilesystemsTable.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/MachineStorage.tsx
- ui/src/app/store/machine/types.ts
- ui/src/testing/factories/nodes.ts
- built available disks and partitions list in machine storage tab. It's almost the same as the angular version, only the Boot column is now an icon instead of a radio button, and instead of having empty cells if the column isn't relevant I've made them dashes (e.g `—`)
- Check that the react available disks and partitions list …
> feat(ui): build available disks and partitions list

- legacy/src/app/services/managerhelper.js
- legacy/src/app/services/region.js
- legacy/src/app/services/tests/test_managerhelper.js
- Catch websocket errors from managers and pass them to the error service.
Fixes: canonical-web-and-design/maas-ui#1850.
Fixes: canonical-web-and-design/maas-ui#1874.
> Backport to 2.9: fix for websocket errors when closed

- legacy/src/app/services/managerhelper.js
- legacy/src/app/services/region.js
- legacy/src/app/services/tests/test_managerhelper.js
- Catch websocket errors from managers and pass them to the error service.
Fixes: canonical-web-and-design/maas-ui#1850.
Fixes: canonical-web-and-design/maas-ui#1874.
> Backport to 2.8: fix for websocket errors when closed 

- ui/.betterer.results
- ui/src/app/machines/views/MachineDetails/MachineStorage/MachineStorage.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/MachineStorage.tsx
- added footer links to machine storage tab + analytics event when clicking on the docs link
- Go to the storage tab of a machine and check that the two links at the bottom are the same as in the angular version (except the react docs link doesn't need to redirect)
Fixes canonical-web-and-design/MAAS-squad#2159
> feat(ui): add footer links to machine storage tab

- ui/src/app/App.js
- ui/src/app/App.test.js
- ui/src/app/base/hooks.js
- Backport the fix for showing the correct loging page when logging out with external auth (from https://github.com/canonical-web-and-design/maas-ui/pull/1796).
- Connect your ui to a maas using external auth.
- Login in and then log out, you should see the external auth login page.
- Connect your ui to a maas that is NOT using external auth.
- Login in and …
> Show the correct login page when logging out with external auth.

- ui/.betterer.results
- ui/src/app/base/hooks.js
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AvailableStorageTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/FilesystemsTable/FilesystemsTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/FilesystemsTable/FilesystemsTable.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/MachineStorage.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/UsedStorageTable/UsedStorageTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/UsedStorageTable/UsedStorageTable.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/UsedStorageTable/index.ts
- ui/src/app/machines/views/MachineDetails/MachineStorage/types.ts
- ui/src/app/machines/views/MachineDetails/MachineStorage/utils.test.ts
- ui/src/app/machines/views/MachineDetails/MachineStorage/utils.ts
- ui/src/app/store/machine/constants.ts
- Built used disks and partitions list in machine storage tab.
- Refactored a few common elements into utils, and created a helper function to separate machine storage data into disparate bits while only iterating through the disks array once
- Check that the react used disks and partitions list shows the same data as the …
> feat(ui): build used disks and partitions list in machine storage tab

- ui/.betterer.results
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AvailableStorageTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AvailableStorageTable.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/BootStatus/BootStatus.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/BootStatus/BootStatus.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/BootStatus/index.ts
- ui/src/app/machines/views/MachineDetails/MachineStorage/FilesystemsTable/FilesystemsTable.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/MachineStorage.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/NumaNodes/NumaNodes.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/NumaNodes/NumaNodes.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/NumaNodes/index.ts
- ui/src/app/machines/views/MachineDetails/MachineStorage/TagLinks/TagLinks.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/TagLinks/TagLinks.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/TagLinks/index.ts
- ui/src/app/machines/views/MachineDetails/MachineStorage/TestStatus/TestStatus.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/TestStatus/TestStatus.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/TestStatus/index.ts
- ui/src/app/machines/views/MachineDetails/MachineStorage/UsedStorageTable/UsedStorageTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/UsedStorageTable/UsedStorageTable.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/utils.test.ts
- ui/src/app/machines/views/MachineDetails/MachineStorage/utils.ts
- Created common components between storage tables
- `BootStatus`
- `NumaNodes`
- `TagLinks`
- `TestStatus`
- Moved a couple of formatting utils out of `MachineStorage` and into `utils`
- Check that the storage tab still shows the correct information for filesystems, available disks and partitions, and used disks and partitions …
> refactor(ui): create common components between storage tables

- ui/.betterer.results
- ui/src/app/machines/views/MachineDetails/MachineStorage/CacheSetsTable/CacheSetsTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/CacheSetsTable/CacheSetsTable.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/CacheSetsTable/index.ts
- ui/src/app/machines/views/MachineDetails/MachineStorage/MachineStorage.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/MachineStorage.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/types.ts
- ui/src/app/machines/views/MachineDetails/MachineStorage/utils.test.ts
- ui/src/app/machines/views/MachineDetails/MachineStorage/utils.ts
- Built cache sets list in machine storage tab
- Go to a machine that already has cache sets (e.g. `casual-emu` on bolla), or add one in the legacy storage tab of a ready machine
- Check that a table "Available cache sets" shows with the same data as the angular version
Fixes canonical-web-and-design/MAAS-squad#2264
> feat(ui): build cache sets list in machine storage tab

- ui/.betterer.results
- ui/src/app/machines/views/MachineDetails/MachineStorage/DatastoresTable/DatastoresTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/DatastoresTable/DatastoresTable.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/DatastoresTable/__snapshots__/DatastoresTable.test.tsx.snap
- ui/src/app/machines/views/MachineDetails/MachineStorage/DatastoresTable/index.ts
- ui/src/app/machines/views/MachineDetails/MachineStorage/MachineStorage.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/MachineStorage.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/types.ts
- ui/src/app/machines/views/MachineDetails/MachineStorage/utils.test.ts
- ui/src/app/machines/views/MachineDetails/MachineStorage/utils.ts
- Added datastores list to machine storage, which should only appear if the machine has its storage layout set to "vmfs6"
- Change a machine's storage layout to VMFS6 using the angular client (fun-mammal on bolla already has this layout)
- Check that a datastore table shows instead of a filesystems table
- Check that the data is …
> feat(ui): build vmfs6 datastores list in machine storage tab

- legacy/src/app/directives/code_lines.js
- Fixed machine logs missing new lines when copied manually
- Go to the logs page of a machine in legacy
- Copy some of the lines manually (i.e. highlighting some text and pressing  `CTRL+C`)
- Paste into a text editor and check that the newlines copy over correctly
- Click the copy button in the top-right corner of the code …
> fix(legacy): fix machine logs missing new lines when copied manually

- ui/.betterer.results
- ui/src/__snapshots__/root-reducer.test.js.snap
- ui/src/app/base/sagas/websockets.js
- ui/src/app/base/sagas/websockets.test.js
- ui/src/app/machines/views/MachineDetails/MachineTests/MachineTests.tsx
- ui/src/app/store/noderesult/index.ts
- ui/src/app/store/noderesult/reducers.test.ts
- ui/src/app/store/noderesult/selectors.test.tsx
- ui/src/app/store/noderesult/selectors.ts
- ui/src/app/store/noderesult/slice.ts
- ui/src/app/store/noderesult/types.ts
- ui/src/app/store/root/types.ts
- ui/src/root-reducer.js
- ui/src/testing/factories/index.ts
- ui/src/testing/factories/noderesult.ts
- ui/src/testing/factories/state.ts
- Add noderesult slice (note, scriptResults slice will be removed in a followup PR)
- Add a `nocache` meta param, which prevents allows `list` methods to be optionally called repeatedly
- visit the machine details testing tab
- ensure nodeResults for that machine appear in redux state
- visit the machine details testing tab for …
> Add noderesult slice

- ui/.betterer.results
- ui/src/app/machines/views/MachineDetails/MachineStorage/ChangeStorageLayout/ChangeStorageLayout.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/FilesystemsTable/AddSpecialFilesystem/AddSpecialFilesystem.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/FilesystemsTable/AddSpecialFilesystem/AddSpecialFilesystem.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/FilesystemsTable/AddSpecialFilesystem/index.ts
- ui/src/app/machines/views/MachineDetails/MachineStorage/FilesystemsTable/FilesystemsTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/FilesystemsTable/FilesystemsTable.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/MachineStorage.tsx
- ui/src/app/store/machine/actions.test.ts
- ui/src/app/store/machine/slice.ts
- ui/src/app/store/machine/types.ts
- ui/src/testing/factories/state.ts
- Built AddSpecialFilesystem form
- Go to the machine storage tab of a machine with editable storage
- Check there is an "Add special filesystem" button
- Click it, fill in the form and submit
- Check that the form closes and the special filesystem is added to the filesystems list
- Note that the form does not handle errors yet, …
> feat(ui): build form for adding special filesystems

- legacy/src/app/partials/node-details.html
- Remove conditional that hides the storage tab if a controller is new
- Check that you can see the storage details of a new controller
Fixes #1290 
https://bugs.launchpad.net/maas/+bug/1874356
> fix(legacy): show storage tab for new controllers

- ui/src/app/store/machine/actions.test.ts
- ui/src/app/store/machine/slice.ts
- ui/src/app/store/machine/types.ts
- ui/src/testing/factories/state.ts
- Copied storage delete actions from legacy `NodesManager` and `MachinesManager` to machine slice
- N/A
Fixes canonical-web-and-design/MAAS-squad#2273
> feat(ui): add storage delete actions to machine slice

- ui/src/app/store/machine/actions.test.ts
- ui/src/app/store/machine/slice.ts
- ui/src/app/store/machine/types.ts
- ui/src/testing/factories/state.ts
- Copied storage update actions from legacy `NodesManager` and `MachinesManager` to machine slice
- N/A
Fixes canonical-web-and-design/MAAS-squad#2272
> feat(ui): add storage update actions to machine slice

- ui/.betterer.results
- ui/src/app/base/components/TableMenu/TableMenu.js
- ui/src/app/base/components/TableMenu/__snapshots__/TableMenu.test.js.snap
- ui/src/app/base/components/TableMenu/_index.scss
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AddPartition/AddPartition.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AddPartition/AddPartition.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AddPartition/index.ts
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AddPartitionFields/AddPartitionFields.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AddPartitionFields/AddPartitionFields.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AddPartitionFields/index.ts
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AvailableStorageTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AvailableStorageTable.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/FilesystemsTable/FilesystemsTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/FilesystemsTable/FilesystemsTable.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/MachineStorage.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/types.ts
- ui/src/app/machines/views/MachineDetails/MachineStorage/utils.test.ts
- ui/src/app/machines/views/MachineDetails/MachineStorage/utils.ts
- ui/src/app/machines/views/MachineList/MachineListTable/OwnerColumn/__snapshots__/OwnerColumn.test.js.snap
- ui/src/app/machines/views/MachineList/MachineListTable/PoolColumn/__snapshots__/PoolColumn.test.js.snap
- ui/src/app/machines/views/MachineList/MachineListTable/PowerColumn/__snapshots__/PowerColumn.test.js.snap
- ui/src/app/machines/views/MachineList/MachineListTable/StatusColumn/__snapshots__/StatusColumn.test.tsx.snap
- ui/src/app/machines/views/MachineList/MachineListTable/ZoneColumn/__snapshots__/ZoneColumn.test.js.snap
- ui/src/app/store/machine/slice.ts
- Added `actions` parameter to normalised storage devices, which will house the actions that a storage device can perform (similar to how `machine.actions` works)
- Added util for determining whether a storage device can be partitioned
- Added `AddPartition` form
- Go to the storage tab of a "Ready" or "Allocated" machine
- …
> feat(ui): build add partition form in machine storage

- ui/src/app/base/components/TableMenu/TableMenu.js
- ui/src/app/machines/views/MachineDetails/MachineStorage/ActionConfirm/ActionConfirm.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/ActionConfirm/ActionConfirm.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/ActionConfirm/index.ts
- ui/src/app/machines/views/MachineDetails/MachineStorage/DatastoresTable/DatastoresTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/DatastoresTable/__snapshots__/DatastoresTable.test.tsx.snap
- ui/src/app/machines/views/MachineDetails/MachineStorage/FilesystemsTable/AddSpecialFilesystem/AddSpecialFilesystem.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/FilesystemsTable/AddSpecialFilesystem/AddSpecialFilesystem.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/FilesystemsTable/FilesystemsTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/FilesystemsTable/FilesystemsTable.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/MachineStorage.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/types.ts
- ui/src/app/machines/views/MachineDetails/MachineStorage/utils.test.ts
- ui/src/app/machines/views/MachineDetails/MachineStorage/utils.ts
- ui/src/app/store/machine/slice.ts
- Added ability to remove filesystems
- Built `ActionConfirm` component which should be able to be used for the rest of the delete/remove/unmount actions.
- Add a filesystem to a partition
- Add a special filesystem
- Check that you can remove them both from the action …
> feat(ui): add ability to remove filesystems

- .github/labeler.yml
> fix: prevent labeller from removing code and qa needed labels

- ui/src/app/machines/views/MachineList/MachineListTable/NameColumn/NameColumn.js
- ui/src/app/machines/views/MachineList/MachineListTable/NameColumn/__snapshots__/NameColumn.test.js.snap
- ui/src/app/settings/views/Dhcp/DhcpTarget/DhcpTarget.js
- ui/src/app/settings/views/Dhcp/DhcpTarget/DhcpTarget.test.js
- ui/src/app/settings/views/Dhcp/DhcpTarget/__snapshots__/DhcpTarget.test.js.snap
Machine listing links on master were pointing to the new dev version of machine details, which made for a bit of a broken experience for users on the edge snap.
- From the machine list, click a machine name. 
- Ensure the link navigates to the legacy machine details.
In …
> fix(ui): revert machine list links

- ui/src/app/machines/views/MachineDetails/MachineStorage/utils-new.test.ts
- ui/src/app/machines/views/MachineDetails/MachineStorage/utils-new.ts
- Added a temporary `utils-new.ts` file to storage which will eventually replace the current `utils.ts` file once all the tables have been refactored
- No QA because these aren't used anywhere yet.
Fixes canonical-web-and-design/MAAS-squad#2278
> refactor(ui): refactor storage utils to be more composable

- ui/.betterer.results
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AddPartition/AddPartition.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AddPartition/AddPartition.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AddPartitionFields/AddPartitionFields.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AvailableStorageTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AvailableStorageTable.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/BootStatus/BootStatus.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/BootStatus/BootStatus.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/MachineStorage.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/NumaNodes/NumaNodes.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/NumaNodes/NumaNodes.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/UsedStorageTable/UsedStorageTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/UsedStorageTable/UsedStorageTable.tsx
- Refactored Available/Used disks and partitions tables to no longer use the `separateStorageData` util, which flattened the data hierarchy.
- Go to the storage tab of a ready or allocated machine
- Check that the data in the available and used disks and partitions tables remains the same
- Check that changing the storage layout …
> refactor(ui): maintain disk/partition hierarchy in storage tables

- ui/src/app/machines/views/MachineDetails/MachineNetwork/MachineNetwork.tsx
- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTable.tsx
- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/index.ts
- Add the network table component with headers.
- Visit a machine details page and go to the network tab.
- You should see the the table headers.
Fixes: canonical-web-and-design/MAAS-squad#2285.
> feat(ui): add network table component

- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AvailableStorageTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AvailableStorageTable.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/utils-new.test.ts
- ui/src/app/machines/views/MachineDetails/MachineStorage/utils-new.ts
- Added ability to remove disks, partitions and volume groups from the "Available disks and partitions" table
- Updated `formatType()` util to be able to return a type in sentence form
- Fixed a bug where available partitions were ending up in the used table
- In the angular client go to the storage tab of a machine in ready or …
> feat(ui): add ability to remove disks, partitions and volume groups

- ui/.betterer.results
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AvailableStorageTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AvailableStorageTable.tsx
- Added checkboxes to the available disks and partitions table
- Go to the machine details page of a machine in ready or allocated state
- Check that you can check individual disk checkboxes
- Check that you can check all checkboxes via the header checkbox
Fixes canonical-web-and-design/MAAS-squad#2286
> feat(ui): add checkboxes to available disks and partitons table

- ui/.betterer.results
- ui/src/app/machines/views/MachineDetails/MachineStorage/FilesystemsTable/FilesystemsTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/FilesystemsTable/FilesystemsTable.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/MachineStorage.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/utils-new.ts
- ui/src/app/store/machine/slice.ts
- Refactored filesystems table to no longer use the `separateStorageData` util.
- Go to the storage tab of a ready or allocated machine
- Change the storage layout and check that the filesystems update correctly (you can use the angular version for reference)
- Check that you can still add special filesystems
- Check that you …
> refactor(ui): refactor filesystems table to use new utils

- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AvailableStorageTable.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/FilesystemsTable/FilesystemsTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/FilesystemsTable/FilesystemsTable.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/utils.test.ts
- ui/src/app/machines/views/MachineDetails/MachineStorage/utils.ts
- ui/src/app/store/machine/actions.test.ts
- ui/src/app/store/machine/slice.ts
- Added ability to unmount filesystems from the filesystems table.
- Go to the storage tab of a machine in Ready or Allocated state
- Change the storage layout to "LVM" which will create a partition and logical volume (a type of virtual disk)
- Check that you can unmount each filesystem, which puts them back into  "Available …
> feat(ui): add ability to unmount filesystems

- ui/.betterer.results
- ui/src/app/base/enum.ts
- ui/src/app/machines/views/MachineDetails/MachineTests/MachineTests.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineTests/MachineTests.tsx
- ui/src/app/machines/views/MachineDetails/MachineTests/MachineTestsTable/MachineTestsTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineTests/MachineTestsTable/MachineTestsTable.tsx
- ui/src/app/machines/views/MachineDetails/MachineTests/MachineTestsTable/__snapshots__/MachineTestsTable.test.tsx.snap
- ui/src/app/machines/views/MachineDetails/MachineTests/MachineTestsTable/index.ts
- ui/src/app/machines/views/MachineDetails/MachineTests/__snapshots__/MachineTests.test.tsx.snap
- ui/src/testing/factories/noderesult.ts
Add initial table of testing results
Note, a number of features are not working in this branch:
1. actions
2. supressing tests
3. links to logs
4. status icons
5. block device headings render as ids rather than the full string
- Visit the machine details testing tab
- Ensure testing results are rendered correctly in tables under …
> feat(ui): add table of testing results

- ui/.betterer.results
- ui/src/app/machines/views/MachineDetails/MachineStorage/ActionConfirm/ActionConfirm.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AddPartition/AddPartition.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AvailableStorageTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AvailableStorageTable.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/EditPartition/EditPartition.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/EditPartition/EditPartition.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/EditPartition/index.ts
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/EditPartitionFields/EditPartitionFields.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/EditPartitionFields/EditPartitionFields.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/EditPartitionFields/index.ts
- ui/src/app/machines/views/MachineDetails/MachineStorage/ChangeStorageLayout/ChangeStorageLayout.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/FilesystemsTable/AddSpecialFilesystem/AddSpecialFilesystem.tsx
- Added `EditPartition` and `EditPartitionFields` components. I originally wanted to make a generic `PartitionForm` component that housed the bits shared between the add and edit forms, but I think the differences ended up being large enough to warrant separate components. …
> feat(ui): add edit partition functionality

- ui/.betterer.results
- ui/src/app/machines/views/MachineDetails/MachineTests/MachineTests.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineTests/MachineTests.tsx
- ui/src/app/store/noderesult/selectors.test.tsx
- ui/src/app/store/noderesult/selectors.ts
- add testing result selectors to noderesult selectors
- Visit the machine details testing tab, results should render as expected
Fixes: # . …
> refactor(ui): add testing result selectors to noderesult selectors

- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTable.tsx
- ui/src/app/store/machine/types.ts
- ui/src/app/store/machine/utils.test.tsx
- ui/src/app/store/machine/utils.ts
- ui/src/testing/factories/nodes.ts
- Add the PXE column to the network tab of a machine details page.
- View the machine details network tab.
- You should see a green tick icon for boot interfaces in the PXE column.
Fixes: #1952.
> feat(ui): add PXE column to network tab

- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTable.tsx
- ui/src/app/store/machine/utils.test.tsx
- ui/src/app/store/machine/utils.ts
- ui/src/scss/_patterns_icons.scss
- Add the column for link speed to the network tab of machine details.
- Go to the network tab in machine details.
- You should see the link/interface speed column.
- Clicking on the table headers should now also sort the rows.
Fixes: #1953.
> feat(ui): add link speed column to the network tab

- legacy/src/app/controllers/master.js
- Fix the links in the header so that navigating from one legacy page to another works.
- Navigate to a legacy page.
- Click on another legacy link in the header.
- It should navigate to that page.
Fixes: #1967.
> fix(legacy): fix navigating from legacy to legacy via the header

- legacy/src/app/directives/script_select.js
Ensure user commissioning scripts are selected by default, and noauto scripts are excluded
- Open the commissioning panel for a machine from machine details. User defined scripts should be selected by default, with the exception of scripts tagged 'noauto'.
Fixes: # .
In …
> fix(legacy): ensure user commissioning scripts are selected by default

- ui/src/app/machines/views/MachineDetails/MachineStorage/DatastoresTable/DatastoresTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/DatastoresTable/DatastoresTable.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/MachineStorage.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/utils.test.ts
- ui/src/app/machines/views/MachineDetails/MachineStorage/utils.ts
- Added ability to remove datastores from the datastores list
- Change the storage layout of a machine to VMFS6 and check that a Datastores table appears
- Open the action menu of the datastore and click "Remove datastore" and confirm
- Check that the datastore is removed and placed back into Available disks and partitions
Fixes …
> feat(ui): Add ability to remove datastores

- ui/src/app/machines/views/MachineDetails/MachineStorage/CacheSetsTable/CacheSetsTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/CacheSetsTable/CacheSetsTable.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/MachineStorage.tsx
- Added ability to remove cache sets
- Go to the angular storage tab and change the storage layout to blank
- Select a disk and click "Create cache set"
- Go to the react version of the storage tab and check that there is a cache sets table
- Open the action menu of the cache set and click "Remove cache set" and confirm
- Check …
> feat(ui): add ability to remove cache sets

- ui/src/app/machines/hooks.test.tsx
- ui/src/app/machines/hooks.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/ActionConfirm/ActionConfirm.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/ActionConfirm/ActionConfirm.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AddPartition/AddPartition.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AddPartition/AddPartition.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AvailableStorageTable.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/EditPartition/EditPartition.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/EditPartition/EditPartition.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/CacheSetsTable/CacheSetsTable.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/ChangeStorageLayout/ChangeStorageLayout.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/ChangeStorageLayout/ChangeStorageLayout.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/DatastoresTable/DatastoresTable.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/FilesystemsTable/AddSpecialFilesystem/AddSpecialFilesystem.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/FilesystemsTable/AddSpecialFilesystem/AddSpecialFilesystem.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/FilesystemsTable/FilesystemsTable.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/MachineStorage.tsx
- Added `useMachineDetailsForm` hook which returns the saving, saved and error state for a single machine performing a single action. It's slightly different to `useMachineActionForm` because it doesn't handle multiple machines processing.
- Added error messages to storage forms
- Go to the storage tab of a ready or allocated …
> feat(ui): add error handling to machine storage forms

- ui/.betterer.results
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AvailableStorageTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/BootStatus/BootStatus.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/BootStatus/BootStatus.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/CacheSetsTable/CacheSetsTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/MachineStorage.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/UsedStorageTable/UsedStorageTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/utils.test.ts
- ui/src/app/machines/views/MachineDetails/MachineStorage/utils.ts
- ui/src/app/store/machine/types.ts
- ui/src/testing/factories/nodes.ts
- Added an enum for disk types and replaced instances of disk type strings with it 
- Shouldn't need a QA - just need tests to pass
Fixes #1986
> refactor(ui): add enum for disk types

- ui/.betterer.results
- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTable.tsx
- ui/src/app/store/machine/types.ts
- ui/src/app/store/machine/utils.test.tsx
- ui/src/app/store/machine/utils.ts
- ui/src/testing/factories/nodes.ts
- Add the column to display the interface type and numa node on the network tab of the machine
details.
- Go to the network tab in machine details.
- You should see the type/numa node column. The details will appear bit different to the legacy page as the rows don't yet account for the bond/bridge hierarchy.
Fixes: #1954.
> feat(ui): add type/numa column to the network tab

- ui/src/app/base/components/LegacyLink/LegacyLink.tsx
- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTable.tsx
- ui/src/app/settings/views/Users/UserForm/UserForm.test.tsx
- ui/src/app/store/vlan/types.ts
- ui/src/app/store/vlan/utils.test.ts
- ui/src/app/store/vlan/utils.ts
- Add the fabric and vlan column to the network table in machine details.
- Go the the network tab for a machine.
- You should see fabric/vlan details with links to the correct pages.
Fixes: #1955.
> feat(ui): add the fabric column to the network tab

- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AvailableStorageTable.tsx
- ui/src/app/store/machine/utils/index.ts
- ui/src/app/store/machine/utils/storage.test.ts
- ui/src/app/store/machine/utils/storage.ts
- Updated selected state handling in available storage table.
- Now the entire storage device object is set in selected state. This is for the actions to come later which will need to know about more than just the id and type.
- Added a `useEffect` which keeps the selected state from becoming stale, e.g. for when a disk is updated or deleted …
> refactor(ui): update selected state handling in available storage table

- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTable.tsx
- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/SubnetColumn/SubnetColumn.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/SubnetColumn/SubnetColumn.tsx
- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/SubnetColumn/index.ts
- ui/src/app/store/machine/types.ts
- ui/src/app/store/subnet/utils.test.ts
- ui/src/app/store/subnet/utils.ts
- ui/src/testing/factories/index.ts
- ui/src/testing/factories/nodes.ts
- Add the subnet details to the network table in machine details.
- Visit the network tab in machine details.
- You should see subnet details.
Fixes: #1956.
> feat(ui): add subnet column to the network tab

- ui/src/app/machines/components/ActionFormWrapper/OverrideTestForm/OverrideTestForm.js
- ui/src/app/machines/components/ActionFormWrapper/OverrideTestForm/OverrideTestForm.test.js
- ui/src/app/store/scriptresult/selectors.test.tsx
- ui/src/app/store/scriptresult/selectors.ts
- ui/src/app/store/scriptresult/types.ts
- Update the override test form to only override the failed tests.
- Open the override failed testing form from the machine list of machine details.
- It should allow you to override them.
Fixes: #2006.
> fix(ui): override failed testing scripts only

- ui/src/app/machines/components/ActionFormWrapper/OverrideTestForm/OverrideTestForm.js
- ui/src/app/machines/components/ActionFormWrapper/OverrideTestForm/OverrideTestForm.test.js
- Request script results that haven't already been loaded In the override failed test form.
- Go to the machine list, check a machine with failed tests and open the form to override the failed tests.
- The form should show the number of failed tests.
- Cancel the form, uncheck the first machine and check a second machine with failed tests and open the form …
> fix(ui): correctly request script results from the override form

- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/IPColumn/IPColumn.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/IPColumn/IPColumn.tsx
- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/IPColumn/index.ts
- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTable.tsx
- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/SubnetColumn/SubnetColumn.tsx
- ui/src/app/store/machine/types.ts
- ui/src/app/store/machine/utils/hooks.ts
- ui/src/app/store/machine/utils/index.ts
- ui/src/app/store/machine/utils/networking.test.ts
- ui/src/app/store/machine/utils/networking.ts
- ui/src/app/store/scriptresult/selectors.test.tsx
- ui/src/app/store/scriptresult/selectors.ts
- ui/src/app/store/scriptresult/types.ts
- ui/src/app/store/utils/selectors.ts
- ui/src/testing/factories/nodes.ts
- Add the column to display the ip and status to the network tab.
- Visit the network tab in machine details.
- You should see ip/status data that matches the legacy network table.
Fixes: #1957.
> feat(ui): add the ip column to the network table

- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTable.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/NetworkCard/NetworkCardTable/NetworkCardTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/NetworkCard/NetworkCardTable/NetworkCardTable.tsx
- ui/src/app/store/fabric/utils.test.ts
- ui/src/app/store/fabric/utils.ts
- ui/src/app/store/vlan/utils.test.ts
- ui/src/app/store/vlan/utils.ts
- Add the DHCP details to the network table in machine details.
- Visit the network tab in machine details for a few machines.
- You should see the DHCP column and the data should be the same as legacy.
Fixes: #1958.
> feat(ui): add the DHCP column to the machine network tab

- ui/src/app/machines/views/MachineDetails/MachineDetails.tsx
- ui/src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.tsx
- ui/src/app/machines/views/MachineDetails/MachinePCIDevices/MachinePCIDevices.tsx
- ui/src/app/machines/views/MachineDetails/MachinePCIDevices/index.ts
- ui/src/app/machines/views/MachineDetails/MachineUSBDevices/MachineUSBDevices.tsx
- ui/src/app/machines/views/MachineDetails/MachineUSBDevices/index.ts
- Added "PCI devices" and "USB" tabs to machine summary
- Go to the machine details page of a machine
- Check there are tabs for "PCI devices" and "USB"
- Check that the URL updates correctly when navigating to them
Fixes canonical-web-and-design/MAAS-squad#2296
> feat(ui): build PCI and USB devices tabs

- legacy/src/app/controllers/master.js
- legacy/src/app/partials/layout.html
- legacy/src/scss/_patterns_status-bar.scss
- legacy/src/scss/build.scss
- shared/src/components/StatusBar/StatusBar.test.tsx
- shared/src/components/StatusBar/StatusBar.tsx
- shared/src/components/StatusBar/index.ts
- shared/src/index.ts
- ui/src/app/App.tsx
- ui/src/scss/_patterns_status-bar.scss
- ui/src/scss/index.scss
- Built StatusBar component, which at the moment only displays the MAAS major+minor version
- Navigate to some legacy and react pages and check that there is a status bar at the bottom of the page that shows the MAAS version
- Check that it matches the [design](https://app.zeplin.io/project/5f9af2ae43654ab5edbcfd29/screen/5fd0a9e …
> feat(shared): build StatusBar component

- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTable.tsx
- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTableActions/NetworkTableActions.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTableActions/NetworkTableActions.tsx
- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTableActions/index.ts
- ui/src/app/store/machine/utils/hooks.test.tsx
- ui/src/app/store/machine/utils/hooks.ts
- ui/src/app/store/machine/utils/index.ts
- Add an action menu to the network table in machine details.
- Visit the network tab in machine details for a deployed machine.
- You should see an active action menu.
- Visit the network tab in machine details for a failed machine.
- You should see a disabled action menu.
Fixes: #2016.
> feat(ui): add action menu to the network tab

- legacy/src/app/controllers/master.js
- shared/src/components/Footer/Footer.test.tsx
- shared/src/components/Footer/Footer.tsx
- shared/src/components/Footer/__snapshots__/Footer.test.tsx.snap
- shared/src/components/StatusBar/StatusBar.test.tsx
- shared/src/components/StatusBar/StatusBar.tsx
- ui/src/app/App.tsx
- Moved MAAS name and version from footer to status bar
- Check that the status bar shows the MAAS name and full version in both legacy and react apps
- Check that the footer does not show the MAAS name or version
Fixes #2028
> feat(ui): move MAAS name and version from footer to status bar

- ui/src/app/machines/views/MachineDetails/MachineSummary/MachineSummary.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/SystemCard/SystemCard.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/SystemCard/__snapshots__/SystemCard.test.tsx.snap
- ui/src/app/machines/views/MachineDetails/MachineSummary/WorkloadCard/WorkloadCard.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/WorkloadCard/WorkloadCard.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/WorkloadCard/index.ts
- ui/src/app/machines/views/MachineDetails/MachineSummary/_index.scss
- ui/src/app/store/machine/types.ts
- ui/src/testing/factories/nodes.ts
- Added workload annotations card to machine summary page
- Go to a machine that has an owner (e.g. in "Allocated", "Deployed" status) and no workload annotations
- Check that a message displays about there being no annotations
- Add some workload annotations. In the browser dev tools console, run:
``` js
websocket = new …
```
> feat(ui): add workload annotations card to machine summary

- ui/src/app/App.tsx
- Only render status bar if required props have loaded
- Navigate to any react page and check that there is no error in the console about `maasName` being required but undefined.
> fix(ui): only render status bar if required props have loaded

- ui/src/app/machines/views/MachineDetails/MachineDetails.tsx
- ui/src/app/machines/views/MachineDetails/MachinePCIDevices/MachinePCIDevices.test.tsx
- ui/src/app/machines/views/MachineDetails/MachinePCIDevices/MachinePCIDevices.tsx
- ui/src/app/machines/views/MachineDetails/MachineUSBDevices/MachineUSBDevices.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineUSBDevices/MachineUSBDevices.tsx
- Added prompt for user to commission the machine if there is no PCI or USB device info. At the moment this is always the case because the websocket api has not been implemented yet.
- Go to the PCI devices tab of a machine
- Check that you are prompted to commission the machine
- Click "Commission" and check that the Commission …
> feat(ui): prompt user to commission machine if PCI/USB info unavailable

- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTable.tsx
- ui/src/app/store/machine/types.ts
- ui/src/app/store/machine/utils/index.ts
- ui/src/app/store/machine/utils/networking.test.ts
- ui/src/app/store/machine/utils/networking.ts
- Display member interface rows correctly in the network table.
- View the network tab for a few machines both the react and legacy clients.
- The bond/bridge members should say "Bonded physical" or "Bridged physical" and not have most columns.
- Note: the table ordering has not yet been implemented (issue: …
> feat(ui): add member interface rows

- shared/src/components/StatusBar/StatusBar.test.tsx
- shared/src/components/StatusBar/StatusBar.tsx
- ui/src/app/App.tsx
- ui/src/app/base/components/StatusBar/StatusBar.test.tsx
- ui/src/app/base/components/StatusBar/StatusBar.tsx
- ui/src/app/base/components/StatusBar/index.ts
- ui/src/app/store/machine/types.ts
- ui/src/testing/factories/nodes.ts
- Added last commissioning timestamp to the status bar if viewing machine details
- Create a new machine (can be fake, just add one with manual power type) and go to its details page
- The machine should start commissioning by default. Check that the status bar says that commissioning is in progress.
- Abort the action and check …
> feat(ui): add last commissioning timestamp to status bar of active machine

- shared/package.json
----
- Bumped maas-ui/maas-ui-shared to 2.0.1
- None
Fixes: # . …
> fix(shared): release shared 2.0.1

- integration/package.json
- package.json
----
- Bumped integration to 2.0.1
- Bumped dependency on shared to 2.0.1
In general, please propose fixes against *master* rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. Please apply backport labels to …
> fix(integration): bump version and dependencies to 2.0.1

- ui/src/app/base/components/Placeholder/Placeholder.test.tsx
- ui/src/app/base/components/Placeholder/Placeholder.tsx
- ui/src/app/base/components/Placeholder/__snapshots__/Placeholder.test.tsx.snap
- ui/src/app/base/components/Placeholder/_index.scss
- ui/src/app/base/components/Placeholder/index.ts
- ui/src/app/machines/views/MachineDetails/MachinePCIDevices/MachinePCIDevices.test.tsx
- ui/src/app/machines/views/MachineDetails/MachinePCIDevices/MachinePCIDevices.tsx
- ui/src/app/machines/views/MachineDetails/MachineUSBDevices/MachineUSBDevices.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineUSBDevices/MachineUSBDevices.tsx
- ui/src/scss/index.scss
- Added Placeholder component, which replaces any given text with a grey bar that has a "shine" animation.
- Implemented the Placeholder component in the PCI and USB tables
- Navigate to the PCI or USB tab of a machine
- Check that grey placeholder blocks show briefly while the data is loading
Fixes …
> feat(ui): add Placeholder component and use in PCI/USB tables

- ui/src/app/base/enum.ts
- ui/src/app/machines/views/MachineDetails/MachinePCIDevices/MachinePCIDevices.test.tsx
- ui/src/app/machines/views/MachineDetails/MachinePCIDevices/MachinePCIDevices.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/NumaCard/__snapshots__/NumaCard.test.tsx.snap
- ui/src/app/store/machine/types.ts
- ui/src/app/store/nodedevice/selectors.ts
- ui/src/testing/factories/nodes.ts
- Built PCI devices table as per [design](https://app.zeplin.io/project/5f9af2ae43654ab5edbcfd29/screen/5fd0a9eee9fc0650e2ecbf94) (there are some minor details like the group title borders and cell widths that I'll address later)
- Commission a machine if it hasn't been commissioned in the last week or so in order to gather info …
> feat(ui): build PCI devices table

- ui/src/app/machines/views/MachineDetails/MachineUSBDevices/MachineUSBDevices.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineUSBDevices/MachineUSBDevices.tsx
- Built USB devices table, which is largely a copy+paste job from the [PCI devices table PR](https://github.com/canonical-web-and-design/maas-ui/pull/2046). I'll extract the common elements in [this issue](https://github.com/canonical-web-and-design/maas-squad/issues/2311) - for now I'm just getting everything working.
- This is …
> feat(ui): build USB devices table

- ui/.betterer.results
- ui/src/__snapshots__/root-reducer.test.js.snap
- ui/src/app/machines/views/MachineDetails/MachineTests/MachineTestsTable/MachineTestsTable.tsx
- ui/src/app/machines/views/MachineDetails/MachineTests/MachineTestsTable/__snapshots__/MachineTestsTable.test.tsx.snap
- ui/src/app/store/scriptresult/reducers.test.ts
- ui/src/app/store/scriptresult/slice.ts
- ui/src/app/store/scriptresult/types.ts
- ui/src/testing/factories/index.ts
- ui/src/testing/factories/scriptResult.ts
- ui/src/testing/factories/state.ts
- Add 'show previous tests' take action item
- Add script result history reducer to root of scriptresult store
- Visit testing details for a machine with test results.
- Select 'show previous tests' from the take action menu
- Check the redux store and ensure the script result history is reduced correctly
Related Launchpad maas …
> feat(ui): add script result history reducer

- ui/src/app/machines/views/MachineDetails/MachinePCIDevices/MachinePCIDevices.test.tsx
- ui/src/app/machines/views/MachineDetails/MachinePCIDevices/MachinePCIDevices.tsx
- ui/src/app/machines/views/MachineDetails/MachineUSBDevices/MachineUSBDevices.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineUSBDevices/MachineUSBDevices.tsx
- ui/src/app/machines/views/MachineDetails/NodeDevices/NodeDevices.test.tsx
- ui/src/app/machines/views/MachineDetails/NodeDevices/NodeDevices.tsx
- ui/src/app/machines/views/MachineDetails/NodeDevices/index.ts
- Extracted the common elements in `MachinePCIDevices` and `MachineUSBDevices` and created a `NodeDevices` component.
- Check that PCI and USB tabs still work as before
- If a machine has been commissioned PCI devices should show up
- Otherwise, a warning should prompt the user to commission their machine
Fixes …
> refactor(ui): extract NodeDevice component from commonalities in PCI/USB components

- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/IPColumn/IPColumn.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/IPColumn/IPColumn.tsx
- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTable.tsx
- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/SubnetColumn/SubnetColumn.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/SubnetColumn/SubnetColumn.tsx
- ui/src/app/store/machine/utils/index.ts
- ui/src/app/store/machine/utils/networking.test.ts
- ui/src/app/store/machine/utils/networking.ts
- ui/src/app/store/subnet/utils.test.ts
- ui/src/app/store/subnet/utils.ts
- Move the data manipulation to utils and use it in the table to set the sortable data.
- View the react network tab for a few machines.
- You should be able to sort the table by all the headers (the node/bridge interfaces will be made to keep their order in #1946.
Fixes: #2011.
> feat(ui): make the network table sortable

- ui/src/app/machines/views/MachineDetails/NodeDevices/NodeDevices.tsx
- ui/src/app/machines/views/MachineDetails/NodeDevices/_index.scss
- ui/src/scss/index.scss
- Made table a bit more responsive with better cell widths at different breakpoints
- Table rows are now grouped properly
- Go to the PCI tab of a machine
- Check that the table looks ok at all viewport sizes
- Check that the table rows are grouped correctly
Fixes canonical-web-and-design/MAAS-squad#2312
> feat(ui): improve styling of PCI/USB device tables

- ui/src/app/machines/search.js
- ui/src/app/machines/search.test.js
- ui/src/app/machines/views/MachineList/MachineList.test.js
- ui/src/app/machines/views/MachineList/MachineListControls/FilterAccordion/FilterAccordion.js
- ui/src/app/machines/views/MachineList/MachineListControls/FilterAccordion/FilterAccordion.test.js
- ui/src/app/machines/views/Machines.test.js
- ui/src/app/store/machine/types.ts
- ui/src/app/utils/search.js
- ui/src/app/utils/search.test.js
- ui/src/testing/factories/nodes.ts
- Added ability to filter machines by workload annotation. It works differently to the rest of the filters so it introduces a bit of bespoke code. I think this is ok for now - at some point the search/filter functionality is going to be replaced with the new Vanilla pattern at which point the whole thing is going to have a major rewrite anyway. …
> feat(ui): add ability to filter machines by workload annotation

- legacy/src/app/partials/node-details.html
- ui/src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/NetworkCard/NetworkCard.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/DetailsCard/DetailsCard.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/SummaryNotifications/SummaryNotifications.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/TestResults/TestResults.tsx
- ui/src/app/machines/views/MachineDetails/NodeDevices/NodeDevices.test.tsx
- ui/src/app/machines/views/MachineDetails/NodeDevices/NodeDevices.tsx
- ui/src/app/machines/views/MachineList/MachineListTable/NameColumn/NameColumn.js
- ui/src/app/machines/views/MachineList/MachineListTable/NameColumn/__snapshots__/NameColumn.test.js.snap
- ui/src/app/settings/views/Dhcp/DhcpTarget/DhcpTarget.js
- ui/src/app/settings/views/Dhcp/DhcpTarget/DhcpTarget.test.js
- ui/src/app/settings/views/Dhcp/DhcpTarget/__snapshots__/DhcpTarget.test.js.snap
- Update the machine details tabs to route between the legacy/react clients as needed.
- Navigate to the machine list.
- Click on a machine, you should be taken to the react summary.
- click on on the different tabs: you should end up on the react client for summary, pci and usb devices and you should end up on the legacy page …
> feat(all): route between clients for machine detail tabs

- ui/.betterer.results
- ui/src/app/base/hooks.ts
- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTable.tsx
- ui/src/app/store/machine/utils/index.ts
- ui/src/app/store/machine/utils/networking.test.ts
- ui/src/app/store/machine/utils/networking.ts
- Keep bond and bridge rows in groups when sorting the network table.
- View the network tab for a machine with bond and bridges (sampledata has these).
- the bond and bridge rows should have the parents/children next to each other.
- Sort the table by a different column, the groups should stay together.
Fixes: #1946.
> feat(ui): group bonds and bridges in the network table

- ui/src/app/machines/search.js
- ui/src/app/machines/search.test.js
- ui/src/app/machines/views/MachineDetails/MachineSummary/WorkloadCard/WorkloadCard.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/WorkloadCard/WorkloadCard.tsx
- Added filter links to workload annotations card
- Go to the machine summary of a machine that has workload annotations (on bolla `comic-toucan` and `sure-cod` have them, otherwise follow the steps in [this PR](https://github.com/canonical-web-and-design/maas-ui/pull/2014) to add some)
- Check that clicking one of the workload …
> feat(ui): add filter links to workload annotations card

- ui/src/app/machines/views/MachineDetails/NodeDevices/NodeDevices.test.tsx
- ui/src/app/machines/views/MachineDetails/NodeDevices/NodeDevices.tsx
- Only load node devices once when navigating to PCI/USB tabs
- Go to the PCI tab of a machine and check that the loading placeholder rows show up
- Navigate away and then back
- The data should load instantly, i.e. the placeholder rows should not show
Fixes canonical-web-and-design/MAAS-squad#2317
> fix(ui): only load node devices once when navigating to PCI/USB tabs

- ui/.betterer.results
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/BulkActions/CreateRaid/CreateRaid.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/BulkActions/CreateRaid/CreateRaid.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/BulkActions/CreateRaid/CreateRaidFields/CreateRaidFields.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/BulkActions/CreateRaid/CreateRaidFields/CreateRaidFields.tsx
- ui/src/app/store/machine/constants.ts
- Added storage devices table to Create RAID form
- Added ability to choose from RAID 0/1/5/6/10 devices when creating a RAID
- Go to the storage tab of a machine in Ready or Allocated state.
- Create 2 partitions of different sizes.
- Select the partitions and click "Create RAID".
- RAID 0 should be selected by default. Note …
> feat(ui): add ability to create RAID 1/5/6/10 devices

- ui/src/app/machines/views/MachineDetails/MachineStorage/ActionConfirm/ActionConfirm.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/ActionConfirm/ActionConfirm.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AvailableStorageTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AvailableStorageTable.tsx
- ui/src/app/store/machine/slice.ts
- ui/src/app/store/machine/utils/index.ts
- ui/src/app/store/machine/utils/storage.test.ts
- ui/src/app/store/machine/utils/storage.ts
- Added ability to create cache sets. I've decided not to follow the same design as the legacy storage tab, in which creating cache sets is handled as a bulk action despite the fact that you can only perform it on a single storage device.
- Go to the storage tab of a Ready or Allocated machine that has an unpartitioned disk.
- …
> feat(ui): add ability to create cache sets

- ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/InterfacesTable/SubnetSelect/_index.scss
- Fixed some broken width interpolation in KVM compose form. Turns out nesting `#{}`s doesn't work out too well.
- Go to the details page of a KVM that has available subnets (e.g. bolla)
- Open the Compose form from the action menu
- Define an interface
- Click the Subnet dropdown and check that the widths line up with the table …
> fix(ui): fix broken width interpolation in KVM compose form

- ui/.betterer.results
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AvailableStorageTable.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/BulkActions/BulkActions.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/BulkActions/BulkActions.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/BulkActions/CreateDatastore/CreateDatastore.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/BulkActions/CreateDatastore/CreateDatastore.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/BulkActions/CreateDatastore/index.ts
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/BulkActions/CreateRaid/CreateRaid.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/DatastoresTable/DatastoresTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/DatastoresTable/DatastoresTable.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/MachineStorage.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/MachineStorage.tsx
- ui/src/app/store/machine/actions.test.ts
- ui/src/app/store/machine/slice.ts
- ui/src/app/store/machine/types.ts
- ui/src/app/store/machine/utils/index.ts
- ui/src/app/store/machine/utils/storage.test.ts
- ui/src/app/store/machine/utils/storage.ts
- ui/src/testing/factories/nodes.ts
- Added the ability to create datastores
- Made the datastores table dependent on the storage layout, since it's possible to be in VMFS6 storage layout without any datastores
- Change the storage layout to VMFS6
- If the machine only has one disk, remove the datastore that …
> feat(ui): add ability to create datastores

- ui/.betterer.results
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AvailableStorageTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AvailableStorageTable.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/CreateBcache/CreateBcache.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/CreateBcache/CreateBcache.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/CreateBcache/CreateBcacheFields/CreateBcacheFields.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/CreateBcache/CreateBcacheFields/index.ts
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/CreateBcache/index.ts
- ui/src/app/store/machine/slice.ts
- ui/src/app/store/machine/types.ts
- ui/src/app/store/machine/utils/index.ts
- ui/src/app/store/machine/utils/storage.test.ts
- ui/src/app/store/machine/utils/storage.ts
- Added ability to create bcaches. Like with cachesets, I've changed this from the angular client because you can only perform the action on a single storage device.
- Go to the storage tab of a Ready or Allocated machine.
- Create 3 partitions.
- If there is a cache set already, delete it.
- Check that the action dropdowns for …
> feat(ui): add ability to create bcaches

- ui/src/app/base/components/GroupCheckbox/GroupCheckbox.test.tsx
- ui/src/app/base/components/GroupCheckbox/GroupCheckbox.tsx
- ui/src/app/base/components/GroupCheckbox/__snapshots__/GroupCheckbox.test.tsx.snap
- ui/src/app/base/components/GroupCheckbox/index.ts
- ui/src/app/kvm/views/KVMList/KVMListTable/KVMListTable.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AvailableStorageTable.tsx
- ui/src/app/machines/views/MachineList/MachineListTable/MachineListTable.js
- ui/src/app/rsd/views/RSDList/RSDListTable/RSDListTable.tsx
- Dedupe the checkbox for selecting everything in a table.
- Make sure you can use the group checkbox and top/all checkbox to select/deselect the rows.
- Make sure selecting some rows makes the top checkboxe turn into a dash.
- Do the same for the RSD and KVM lists.
- Navigate to the storage tab for a machine and make sure the …
> refactor(ui): move group checkbox to shared component

- ui/src/app/machines/views/MachineDetails/MachineDetails.tsx
- ui/src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.tsx
- ui/src/app/machines/views/MachineDetails/MachineInstances/MachineInstances.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineInstances/MachineInstances.tsx
- ui/src/app/machines/views/MachineDetails/MachineInstances/index.ts
- Build the machine details instances table
- Point your this branch as Karura
- Go to the machine "grand-amoeba"
- Switch to Instances tab
- Check it matches http://karura.internal:5240/MAAS/l/machine/qt7e3e?area=instances
Fixes: https://github.com/canonical-web-and-design/MAAS-squad/issues/2214
> feat(ui) machine details instances table

- ui/.betterer.results
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AvailableStorageTable.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/BulkActions/BulkActions.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/BulkActions/BulkActions.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/BulkActions/CreateDatastore/CreateDatastore.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/BulkActions/CreateDatastore/CreateDatastore.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/BulkActions/UpdateDatastore/UpdateDatastore.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/BulkActions/UpdateDatastore/UpdateDatastore.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/BulkActions/UpdateDatastore/UpdateDatastoreFields/UpdateDatastoreFields.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/BulkActions/UpdateDatastore/UpdateDatastoreFields/index.ts
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/BulkActions/UpdateDatastore/index.ts
- ui/src/app/store/machine/actions.test.ts
- ui/src/app/store/machine/slice.ts
- ui/src/app/store/machine/utils/index.ts
- ui/src/app/store/machine/utils/storage.test.ts
- ui/src/app/store/machine/utils/storage.ts
- Added "Add to existing datastore" to VMFS6 bulk actions
- Go to the storage tab of a machine with at least 2 disks, and is in Ready or Allocated state. (If you set the MAAS to karura you can find one at http://0.0.0.0:8400/MAAS/r/machine/8qcbef/storage).
- Change the storage layout to VMFS6, which will automatically partition …
> feat(ui): allow adding storage to existing datastores

- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AvailableStorageTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AvailableStorageTable.tsx
- ui/src/app/store/machine/utils/index.ts
- ui/src/app/store/machine/utils/storage.test.ts
- ui/src/app/store/machine/utils/storage.ts
- Added "Set boot disk" to the list of actions a disk can do
- Go to the storage tab of a machine with at least 2 disks, and is in Ready or Allocated state. (If you set the MAAS to karura you can find one at http://0.0.0.0:8400/MAAS/r/machine/8qcbef/storage).
- Check that the boot disk does not have the "Set boot disk" action.
- …
> feat(ui): add ability to set boot disk from machine storage tab

- ui/src/app/machines/views/MachineDetails/NodeDevices/_index.scss
- Fixed a bug where pseudo-element borders were not showing up in the node devices table in Chrome
- Using Chrome, open up the PCI devices tab of a machine with PCI devices
- Check that the table borders show up correctly
> fix(ui): fix node device table borders in Chrome

- shared/src/components/StatusBar/StatusBar.tsx
- ui/src/app/base/components/StatusBar/StatusBar.tsx
- made MAAS and machine name bold in status bar
- Go to the details page of a machine
- Check that the MAAS name and the machine's name are bolded in the status bar
> feat(shared): make MAAS and machine name bold in status bar

- ui/.betterer.results
- ui/src/app/base/hooks.ts
- ui/src/app/machines/views/MachineDetails/MachineTests/MachineTestsTable/MachineTestsTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineTests/MachineTestsTable/MachineTestsTable.tsx
- ui/src/app/machines/views/MachineDetails/MachineTests/MachineTestsTable/__snapshots__/MachineTestsTable.test.tsx.snap
- ui/src/app/store/scriptresult/types.ts
- Add metrics to script results (testing) tab
- Find a machine with script result *results* (😞) e.g. [7z result for fun-mammal](/MAAS/r/machine/feeaq4/tests) on bolla.
Fixes: canonical-web-and-design/MAAS-squad#2208
In general, please propose fixes against *master* rather …
> feat(ui): add metrics to script results view

- ui/src/app/base/components/GroupCheckbox/GroupCheckbox.test.tsx
- ui/src/app/base/components/GroupCheckbox/GroupCheckbox.tsx
- ui/src/app/base/components/RowCheckbox/RowCheckbox.test.tsx
- ui/src/app/base/components/RowCheckbox/RowCheckbox.tsx
- ui/src/app/base/components/RowCheckbox/__snapshots__/RowCheckbox.test.tsx.snap
- ui/src/app/base/components/RowCheckbox/index.ts
- ui/src/app/kvm/views/KVMList/KVMListTable/KVMListTable.tsx
- ui/src/app/kvm/views/KVMList/KVMListTable/NameColumn/NameColumn.test.tsx
- ui/src/app/kvm/views/KVMList/KVMListTable/NameColumn/NameColumn.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AvailableStorageTable.tsx
- ui/src/app/machines/views/MachineList/MachineListTable/MachineListTable.js
- ui/src/app/machines/views/MachineList/MachineListTable/NameColumn/NameColumn.js
- ui/src/app/machines/views/MachineList/MachineListTable/NameColumn/NameColumn.test.js
- ui/src/app/machines/views/MachineList/MachineListTable/NameColumn/__snapshots__/NameColumn.test.js.snap
- ui/src/app/rsd/views/RSDList/RSDListTable/RSDListTable.tsx
- ui/src/app/utils/generateCheckboxHandlers.ts
- ui/src/app/utils/someInArray.ts
- Move the row checkboxes to a shared component.
- View the machine, rsd and kvm lists. The checkboxes should work as before.
- Navigate to the storage tab for a machine with available storage. The checkboxes should work in that table too.
Working towards: canonical-web-and-design/maas-squad#2284
> refactor(ui): row checkboxes shared component

- ui/src/app/base/components/GroupCheckbox/GroupCheckbox.test.tsx
- ui/src/app/base/components/GroupCheckbox/GroupCheckbox.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AvailableStorageTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AvailableStorageTable.tsx
- Added `disabled` prop to GroupCheckbox so you can disable it in more ways than just there being no items in the group
- Go to the storage tab of a machine that is neither Ready nor Allocated, i.e. it's storage can't be edited
- Check that the checkbox in the available storage table header is disabled
> feat(ui): add disabled prop to GroupCheckbox

- ui/src/app/machines/views/MachineDetails/ActionConfirm/ActionConfirm.test.tsx
- ui/src/app/machines/views/MachineDetails/ActionConfirm/ActionConfirm.tsx
- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTableActions/NetworkTableActions.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTableActions/NetworkTableActions.tsx
- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTableConfirmation/NetworkTableConfirmation.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTableConfirmation/NetworkTableConfirmation.tsx
- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/types.ts
- ui/src/app/store/machine/actions.test.ts
- ui/src/app/store/machine/slice.ts
- ui/src/app/store/machine/types.ts
- ui/src/testing/factories/state.ts
- Add the ability to mark an interface as connected or disconnected.
- View a machine that can have the network edited (eg a new machine).
- The menus for non-physical interfaces should not have the mark connected/disconnected options.
- On a physical interface use the menu to mark the interface as connected/disconnected.
- The interface should update with …
> feat(ui): add mark as connected/disconnected menu items

- ui/.betterer.results
- ui/src/app/base/components/DoubleRow/DoubleRow.tsx
- ui/src/app/base/components/TableMenu/TableMenu.tsx
- ui/src/app/machines/views/MachineDetails/MachineNetwork/MachineNetwork.tsx
- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTable.tsx
- ui/src/app/machines/views/MachineList/MachineListTable/OwnerColumn/__snapshots__/OwnerColumn.test.js.snap
- ui/src/app/machines/views/MachineList/_index.scss
- Add checkboxes to the network table in machine details.
- Visit the network tab in machine details for a new or ready machine.
- Check that there are checkboxes and that they work as expected.
- Visit a deployed machine and check that the checkboxes are disabled.
Fixes: canonical-web-and-design/maas-squad#2284.
> feat(ui): add network table checkboxes

- .github/workflows/upload.yml
- package.json
- Add build artifact upload workflow, stored by sha.
- Artifacts can be retrieved via the [artifact API](https://docs.github.com/en/rest/reference/actions#artifacts).
n/a
Fixes: # .
In general, please propose fixes against *master* rather than release branches (e.g. 2.7), …
> ci: add build artifact upload workflow

- ui/.betterer.results
- ui/src/app/machines/views/MachineDetails/MachineDetails.tsx
- ui/src/app/machines/views/MachineDetails/MachineTests/MachineTestsDetails/MachineTestsDetails.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineTests/MachineTestsDetails/MachineTestsDetails.tsx
- ui/src/app/machines/views/MachineDetails/MachineTests/MachineTestsDetails/__snapshots__/MachineTestsDetails.test.tsx.snap
- ui/src/app/machines/views/MachineDetails/MachineTests/MachineTestsDetails/index.ts
- ui/src/app/machines/views/MachineDetails/MachineTests/MachineTestsTable/MachineTestsTable.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineTests/MachineTestsTable/MachineTestsTable.tsx
- ui/src/app/machines/views/MachineDetails/MachineTests/MachineTestsTable/__snapshots__/MachineTestsTable.test.tsx.snap
- Add view for script result details
- Display script result details
- Visit the tests tab for a machine with script results
- Follow the "view details" link, you should be taken to /machine/:id/tests/:scriptResultId/details and see script results rendered
Fixes: # .
In …
> feat(ui): add tests details view

- ui/src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.tsx
- ui/src/app/machines/views/MachineDetails/NodeDevices/NodeDevices.test.tsx
- ui/src/app/machines/views/MachineDetails/NodeDevices/NodeDevices.tsx
- Update storage links to point to React version
- Go to a machine's details page
- Click "Storage" in the tab strip and check that it takes you to the React version (with `/r/` in the url)
> feat(ui): link to React version of machine storage tab

- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/EditPhysicalDisk/EditPhysicalDisk.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/EditPhysicalDisk/EditPhysicalDisk.tsx
- ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/EditPhysicalDisk/EditPhysicalDiskFields/EditPhysicalDiskFields.tsx
- Added FilesystemFields to the EditPhysicalDisk form for non-boot disks
- Go to the storage tab of a machine with at least 2 disks, and is in Ready or Allocated state. (If you set the MAAS to karura you can find one at http://0.0.0.0:8400/MAAS/r/machine/8qcbef/storage).
- Open the "Edit physical disk" form for the boot disk and …
> fix(ui): show form fields for mounting non-boot physical disks

- ui/src/app/machines/components/ActionFormWrapper/ActionFormWrapper.tsx
- ui/src/app/machines/components/ActionFormWrapper/TestForm/TestForm.test.tsx
- ui/src/app/machines/components/ActionFormWrapper/TestForm/TestForm.tsx
- ui/src/app/machines/components/TakeActionMenu/TakeActionMenu.tsx
- ui/src/app/machines/views/MachineDetails/MachineDetails.tsx
- ui/src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.tsx
- ui/src/app/machines/views/MachineDetails/MachineNetwork/MachineNetwork.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineNetwork/MachineNetwork.tsx
- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkActions/NetworkActions.test.tsx
- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkActions/NetworkActions.tsx
- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkActions/__snapshots__/NetworkActions.test.tsx.snap
- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkActions/index.ts
- ui/src/app/machines/views/MachineDetails/MachinePCIDevices/MachinePCIDevices.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/MachineSummary.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/NetworkCard/NetworkCard.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/CpuCard/CpuCard.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/MemoryCard/MemoryCard.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/OverviewCard.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/StorageCard/StorageCard.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/TestResults/TestResults.tsx
- ui/src/app/machines/views/MachineDetails/MachineSummary/index.ts
- ui/src/app/machines/views/MachineDetails/MachineUSBDevices/MachineUSBDevices.tsx
- ui/src/app/machines/views/MachineDetails/NodeDevices/NodeDevices.tsx
- ui/src/app/machines/views/MachineDetails/NodeDevices/NodeDevicesWarning/NodeDevicesWarning.tsx
- ui/src/app/machines/views/MachineDetails/types.ts
- ui/src/app/machines/views/MachineList/MachineListHeader/MachineListHeader.tsx
- Add a button to validate the network in the machine details network tab.
- As a drive-by the types for the selected action were moved to a types file instead of living in the summary component.
- Visit a machine where you can edit the network (NOT new, ready, failed testing, allocated or broken).
- Click the "Validate network …
> feat(ui): add network validation to network tab

- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTable.tsx
- ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/_index.scss
- ui/src/scss/_breakpoint-widths.scss
- ui/src/scss/_patterns_tables.scss
- ui/src/scss/index.scss
- Set the breakpoints for the network table.
- Fix the double headers so they appear on two rows.
- Inset the parent interface borders.
- View the network tab in machine details.
- Resize your browser up and down. The table should look OK at all sizes.
- Check that the double headers appear on two rows.
- Find a machine with (or create) an interface with a …
> feat(ui): make the network table responsive
