ui/src/app/base/components/TableActions/TableActions.js
ui/src/app/base/components/TableActions/TableActions.test.js
ui/src/app/machines/views/MachineDetails/MachineNetwork/DHCPTable/DHCPTable.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/DHCPTable/DHCPTable.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/DHCPTable/_index.scss
ui/src/app/machines/views/MachineDetails/MachineNetwork/DHCPTable/index.ts
ui/src/app/machines/views/MachineDetails/MachineNetwork/MachineNetwork.tsx
ui/src/app/store/dhcpsnippet/selectors.test.ts
ui/src/app/store/dhcpsnippet/selectors.ts
ui/src/app/store/dhcpsnippet/types.ts
ui/src/scss/index.scss

- Display the DHCP snippets in the machine network tab.
- Go to the DHCP settings (/MAAS/r/settings/dhcp).
- Add a snippet and set the type to a machine.
- Go to the new network tab for the machine you added the DHCP snippet to.
- You should see a DHCP table that includes your new DHCP snippet.
Fixes: #1888.

feat(ui): add the DHCP snippets table to machine details

---

ui/src/app/machines/views/MachineDetails/NodeDevices/NodeDevicesWarning/NodeDevicesWarning.test.tsx
ui/src/app/machines/views/MachineDetails/NodeDevices/NodeDevicesWarning/NodeDevicesWarning.tsx

- Add a message to the PCI/USB tab if the machine is commissioning and no node devices have been discovered yet
- Go the PCI tab of a machine that has not been commissioned recently (so it has no PCI/USB devices). Alternatively, you can add a machine with manual power type.
- Commission the machine from the action menu and check …

fix(ui): add message to PCI/USB tab if machine is commissioning

---

ui/.betterer.results
ui/src/app/base/components/TableActionsDropdown/TableActionsDropdown.test.tsx
ui/src/app/base/components/TableActionsDropdown/TableActionsDropdown.tsx
ui/src/app/base/components/TableActionsDropdown/index.ts
ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AvailableStorageTable.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/BulkActions/BulkActions.test.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/BulkActions/BulkActions.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/StorageDeviceActions/StorageDeviceActions.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/StorageDeviceActions/index.ts
ui/src/app/machines/views/MachineDetails/MachineStorage/CacheSetsTable/CacheSetsTable.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/DatastoresTable/DatastoresTable.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/FilesystemsTable/FilesystemsTable.tsx

- Created `TableActionsDropdown` component, which is an extension of `TableMenu` but used specifically for the actions cell.
- Moved storage action code out of `AvailableStorageTable` and into new `StorageDeviceActions` component.
- Converted storage action strings into enums. 
- Click around the storage tab of a Ready or …

refactor(ui): create generic TableActionsDropdown component and use in storage

---

ui/.betterer.results
ui/src/__snapshots__/root-reducer.test.js.snap
ui/src/app/machines/views/MachineDetails/MachineTests/MachineTestsDetails/MachineTestsDetails.test.tsx
ui/src/app/machines/views/MachineDetails/MachineTests/MachineTestsDetails/MachineTestsDetails.tsx
ui/src/app/machines/views/MachineDetails/MachineTests/MachineTestsDetails/MachineTestsDetailsLogs.test.tsx
ui/src/app/machines/views/MachineDetails/MachineTests/MachineTestsDetails/MachineTestsDetailsLogs.tsx
ui/src/app/store/scriptresult/reducers.test.ts
ui/src/app/store/scriptresult/selectors.ts
ui/src/app/store/scriptresult/slice.ts
ui/src/app/store/scriptresult/types.ts
ui/src/testing/factories/state.ts

- add tabbed script result log output
Discovered that multiline support is currently [broken for `Code` in some states atm](https://github.com/canonical-web-and-design/react-components/issues/386) while working on this branch, which is why `copyable` is not set.
- Visit the testing tab for a machine with script result output …

feat(ui): display script result logs

---

ui/src/app/machines/views/MachineDetails/ActionConfirm/ActionConfirm.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTableActions/NetworkTableActions.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTableActions/NetworkTableActions.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTableConfirmation/NetworkTableConfirmation.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTableConfirmation/NetworkTableConfirmation.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/types.ts

- Display a warning when trying to edit a physical interface that is disconnected.
- Find a physical interface that is disconnected (or use the action menu to mark it as disconnected).
- Using the action menu click edit.
- It should show a warning.
- Click the button and it should mark it as connected.
Fixes: #2330.

feat(ui): display a warning when trying to edit a disconnected interface

---

ui/src/app/base/components/ArchitectureSelect/ArchitectureSelect.test.tsx
ui/src/app/base/components/ArchitectureSelect/ArchitectureSelect.tsx
ui/src/app/base/components/ArchitectureSelect/__snapshots__/ArchitectureSelect.test.tsx.snap
ui/src/app/base/components/ArchitectureSelect/index.ts
ui/src/app/base/components/DomainSelect/DomainSelect.test.tsx
ui/src/app/base/components/DomainSelect/DomainSelect.tsx
ui/src/app/base/components/DomainSelect/__snapshots__/DomainSelect.test.tsx.snap
ui/src/app/base/components/DomainSelect/index.ts
ui/src/app/base/components/FormikField/FormikField.tsx
ui/src/app/base/components/MinimumKernelSelect/MinimumKernelSelect.test.tsx
ui/src/app/base/components/MinimumKernelSelect/MinimumKernelSelect.tsx
ui/src/app/base/components/MinimumKernelSelect/__snapshots__/MinimumKernelSelect.test.tsx.snap
ui/src/app/base/components/MinimumKernelSelect/index.ts
ui/src/app/base/components/ResourcePoolSelect/ResourcePoolSelect.test.tsx
ui/src/app/base/components/ResourcePoolSelect/ResourcePoolSelect.tsx
ui/src/app/base/components/ResourcePoolSelect/__snapshots__/ResourcePoolSelect.test.tsx.snap
ui/src/app/base/components/ResourcePoolSelect/index.ts
ui/src/app/base/components/ZoneSelect/ZoneSelect.test.tsx
ui/src/app/base/components/ZoneSelect/ZoneSelect.tsx
ui/src/app/base/components/ZoneSelect/__snapshots__/ZoneSelect.test.tsx.snap
ui/src/app/base/components/ZoneSelect/index.ts
ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/ComposeFormFields/ComposeFormFields.tsx
ui/src/app/kvm/components/PodConfiguration/PodConfigurationFields/PodConfigurationFields.tsx
ui/src/app/kvm/views/KVMList/AddKVMForm/AddKVMFormFields/AddKVMFormFields.tsx
ui/src/app/machines/components/ActionFormWrapper/SetPoolForm/SetPoolFormFields/SetPoolFormFields.js
ui/src/app/machines/components/ActionFormWrapper/SetZoneForm/SetZoneForm.js
ui/src/app/machines/views/AddChassis/AddChassisFormFields/AddChassisFormFields.js
ui/src/app/machines/views/AddMachine/AddMachineFormFields/AddMachineFormFields.js

- Created common form Select components that are used in a few places. Each of them do the same thing - load the relevant items into state and turn them into a select. These will also be used in the machine configuration tab (and likely devices and controllers)
- `ArchitectureSelect`
- `DomainSelect`
- `MinimumKernelSelect`
- `ResourcePoolSelect`
- `ZoneSelect`  …

refactor(ui): refactor some common form Select components

---

legacy/src/app/partials/node-details.html
ui/src/app/machines/views/MachineDetails/MachineDetails.tsx
ui/src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.tsx
ui/src/app/machines/views/MachineDetails/MachineSummary/TestResults/TestResults.tsx
ui/src/app/machines/views/MachineDetails/MachineTests/MachineTestsDetails/MachineTestsDetails.test.tsx
ui/src/app/machines/views/MachineDetails/MachineTests/MachineTestsDetails/MachineTestsDetails.tsx

- Changed tests tab over to React link
- Fixed links to React tabs from the angular tabs
- Go to the machine summary of a machine that has run at least one test
- Click the "View results" link for a test type and check that it takes you to the React version of the Tests tab
- Check that the machine details tabs take you to the …

fix(all): fix machine details tab links in legacy and react

---

ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/ComposeForm.tsx
ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/StorageTable/PoolSelect/PoolSelect.tsx
ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/StorageTable/StorageTable.test.tsx
ui/src/app/kvm/components/PodStorage/PodStorage.tsx
ui/src/app/kvm/views/KVMList/KVMListTable/StorageColumn/StoragePopover/StoragePopover.tsx
ui/src/app/store/pod/types.ts

- Updated `BasePod` type so that `storage_pools` and `default_storage_pool` are optional, to match the api
- Handle cases where `pod.storage_pools` is undefined
- Check that the KVM list still loads and you can still compose machines
- betterer should pass without needing to update
Related: #2081 …

fix(ui): handle pods with undefined storage pools

---

ui/src/app/machines/filter-nodes.js
ui/src/app/machines/filter-nodes.test.js
ui/src/app/machines/search.test.js
ui/src/app/machines/views/MachineDetails/MachineHeader/MachineName/__snapshots__/MachineName.test.tsx.snap
ui/src/app/store/machine/selectors.test.ts
ui/src/testing/factories/model.ts
ui/src/testing/factories/nodes.ts

- Fix free searches that start with a number that were erroneously being converted to numbers.
- Add (or edit) some machines with names that start with a number.
- On the machine list type in the start of the name, it should filter the machines.
Fixes: #2152.

fix(ui): fix machine searches that start with a number

---

ui/src/app/machines/filter-nodes.js
ui/src/app/machines/filter-nodes.test.js
ui/src/app/machines/search.test.js
ui/src/app/store/machine/selectors.test.ts
ui/src/testing/factories/model.ts
ui/src/testing/factories/nodes.ts

- Fix free searches that start with a number that were erroneously being converted to numbers.
- Add (or edit) some machines with names that start with a number.
- On the machine list type in the start of the name, it should filter the machines.
Fixes: #2152.

fix machine searches that start with a number

---

legacy/src/app/services/manager.js
legacy/src/app/services/tests/test_manager.js

- Always add the loaded machine to the store when fetching a single machine for machine details.
- Visit a machine details page.
- Click on DNS in the header and navigate to one of the domains.
- From the list of resources click a machine (if there is no machine you might need to add one or look in another domain).
- The machine details should load.
- Do this …

fix(legacy): fix race condition when loading machine details

---

ui/.betterer.results
ui/src/app/base/components/FormikField/FormikField.tsx
ui/src/app/base/components/TagField/TagField.test.tsx
ui/src/app/base/components/TagField/TagField.tsx
ui/src/app/base/components/TagField/index.ts
ui/src/app/base/components/TagSelector/TagSelector.tsx
ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/StorageTable/StorageTable.tsx
ui/src/app/kvm/components/PodConfiguration/PodConfigurationFields/PodConfigurationFields.tsx
ui/src/app/machines/components/ActionFormWrapper/TagForm/TagForm.js
ui/src/app/machines/components/ActionFormWrapper/TagForm/TagForm.test.js
ui/src/app/machines/components/ActionFormWrapper/TagForm/TagFormFields/TagFormFields.js
ui/src/app/machines/views/MachineDetails/MachineConfiguration/MachineForm/MachineFormFields/MachineFormFields.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AddLogicalVolume/AddLogicalVolumeFields/AddLogicalVolumeFields.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/BulkActions/CreateRaid/CreateRaidFields/CreateRaidFields.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/CreateBcache/CreateBcacheFields/CreateBcacheFields.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/EditDisk/EditDiskFields/EditDiskFields.tsx

- Dedupe all the tag field components.
- Make sure the existing tag fields work as before e.g. in the machine tag form, storage form, pod config etc.
Fixes: #2165.

refactor(ui): create shared tag component

---

ui/src/app/machines/views/MachineDetails/MachineSummary/MachineSummary.test.tsx
ui/src/app/machines/views/MachineDetails/MachineSummary/MachineSummary.tsx
ui/src/app/machines/views/MachineDetails/MachineSummary/WorkloadCard/WorkloadCard.tsx

- Removed paragraph text from workload card
- Made workload card only show for deployed or allocated machines
- Go to a machine that is deployed/allocated and has workload annotations and check that they display fine.
- Go to a machine that is deployed/allocated and does not have workload annotations. Check that there is simply …

fix(ui): only show workloads card for allocated/deployed machines

---

ui/src/app/base/sagas/http.js

- Fixed a bug where stale state was being stored in the legacy app (`window.CONFIG`), causing an infinite redirect loop if the legacy and react apps had different values for `user.completed_intro`. The fix is pretty rudimentary (trigger a refresh on logout) but at least it's consistent - feel like messing with the legacy websocket code might backfire. …

fix(ui): fix infinite redirect of death when switching user

---

ui/src/app/base/sagas/http.js

Backport of #2178 
- Fixed a bug where stale state was being stored in the legacy app (`window.CONFIG`), causing an infinite redirect loop if the legacy and react apps had different values for `user.completed_intro`. The fix is pretty rudimentary (trigger a refresh on logout) but at least it's consistent - feel like messing with the legacy websocket code might backfire. …

fix(ui): fix infinite redirect of death when switching user (#2178)

---

ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/StorageTable/StorageTable.test.tsx
ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/StorageTable/StorageTable.tsx

- Removed the conditional that prevented LXD pods from composing machines with multiple disks
- Go to the KVM details page of a LXD KVM.
- Choose "Compose" from the "Take action" menu and check that the "Add disk" button is not disabled
- Add one or more disks then click compose
- Check that the machine is created with the …

feat(ui): allow LXD pods to compose machines with multiple disks

---

legacy/src/app/controllers/node_details.js
legacy/src/app/controllers/tests/test_node_details.js
legacy/src/app/services/manager.js
legacy/src/app/services/tests/test_manager.js
ui/src/app/machines/filter-nodes.js
ui/src/app/machines/filter-nodes.test.js
ui/src/app/machines/search.test.js

- Only fetch a single machine on machine details, rather than every machine.
- Always add the loaded machine to the store when fetching a single machine for machine details.
- Fix free searches that start with a number that were erroneously being converted to numbers.
- Use a dev maas to create a heap of machines:
```
make harness
from …
```

Backport loading machine details fixes to 2.8

---

ui/.betterer.results
ui/src/app/machines/views/MachineDetails/MachineCommissioning/MachineCommissioningTable/MachineCommissioningTable.test.tsx
ui/src/app/machines/views/MachineDetails/MachineCommissioning/MachineCommissioningTable/MachineCommissioningTable.tsx
ui/src/app/machines/views/MachineDetails/MachineTests/MachineTestsTable/MachineTestsTable.test.tsx
ui/src/app/machines/views/MachineDetails/MachineTests/MachineTestsTable/MachineTestsTable.tsx

- Added analytics for:
- Viewing previous tests
- View metrics
- Suppressing script results
- Unsuppressing script results
- N/A
Fixes canonical-web-and-design/MAAS-squad#2194

feat(ui): add analytics to commissioning and testing tabs

---

legacy/src/app/directives/script_select.js
legacy/src/app/partials/node-details.html
ui/src/app/base/components/TagSelector/TagSelector.js
ui/src/app/base/components/TagSelector/TagSelector.test.js
ui/src/app/base/selectors/scripts/scripts.js
ui/src/app/base/selectors/scripts/scripts.test.js
ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/CommissionForm/CommissionForm.js
ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/CommissionForm/CommissionFormFields/CommissionFormFields.js

- In the legacy and react commissioning forms, the preselected scripts are now all the scripts that do not explicitly have the `noauto` tag.
- In the react commissioning form `default` scripts are now disabled. It's not possible to do this in the angular form without a major rewrite of the script selector code, which relies on `ng-tags-input`. Anyway, the api runs the default scripts regardless of whether they're included in the form submission.
- Added a loading spinner to the react form, otherwise it looked kinda jarring having the preselected scripts pop in suddenly.
- [A local snap …

Correctly preselect commissioning scripts that don't have 'noauto' tag

---

root/report.20210218.124724.4180.0.001.json
ui/.betterer.results
ui/src/app/base/components/VLANSelect/VLANSelect.test.tsx
ui/src/app/base/components/VLANSelect/VLANSelect.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/AddInterface/AddInterface.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/AddInterface/AddInterface.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/AddInterface/AddInterfaceFormFields/AddInterfaceFormFields.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/AddInterface/AddInterfaceFormFields/AddInterfaceFormFields.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/AddInterface/AddInterfaceFormFields/index.ts
ui/src/app/machines/views/MachineDetails/MachineNetwork/AddInterface/index.ts
ui/src/app/machines/views/MachineDetails/MachineNetwork/AddInterface/types.ts
ui/src/app/machines/views/MachineDetails/MachineNetwork/MachineNetwork.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/MachineNetwork.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkActions/NetworkActions.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkActions/NetworkActions.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkActions/__snapshots__/NetworkActions.test.tsx.snap
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTable.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTable.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/types.ts

- Add a form to create physical interfaces to the networking tab.
- Find a machine with editable network.
- Click "Add interface" above the table.
- Fill out the details and submit. The interface should be created.
Fixes: #2151.

feat(ui): add the create physical interface form

---

ui/src/app/machines/components/ActionFormWrapper/CommissionForm/CommissionForm.test.tsx
ui/src/app/machines/components/ActionFormWrapper/CommissionForm/CommissionForm.tsx
ui/src/app/machines/components/ActionFormWrapper/TestForm/TestForm.tsx
ui/src/app/machines/views/MachineList/MachineListTable/MachineListTable.js
ui/src/app/settings/views/Scripts/ScriptsList/ScriptsList.test.tsx
ui/src/app/settings/views/Scripts/ScriptsList/ScriptsList.tsx

- Remove script fetch from machine list table because it already gets fetched from the components that need them 
- Only fetch scripts if they have not been fetched before
- Open your browser's network tab
- Select some machines and open the test or commissioning action form
- Check that an http request is made to …

fix(ui): only fetch scripts if they have not been fetched before

---

ui/src/app/machines/views/MachineDetails/MachineNetwork/EditInterface/EditInterface.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/EditInterface/EditInterface.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/EditInterface/index.ts
ui/src/app/machines/views/MachineDetails/MachineNetwork/InterfaceFormTable/InterfaceFormTable.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/InterfaceFormTable/InterfaceFormTable.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/InterfaceFormTable/index.ts
ui/src/app/machines/views/MachineDetails/MachineNetwork/MachineNetwork.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/MachineNetwork.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NameColumn/NameColumn.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTable.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTable.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/PXEColumn/PXEColumn.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/PXEColumn/PXEColumn.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/PXEColumn/index.ts
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/SpeedColumn/SpeedColumn.tsx
ui/src/app/store/machine/selectors.test.ts
ui/src/app/store/machine/selectors.ts
ui/src/app/store/machine/utils/index.ts
ui/src/app/store/machine/utils/networking.test.ts
ui/src/app/store/machine/utils/networking.ts

- Display a table of the interfaces being edited on the edit form.
- Go to the network tab for a machine.
- On a physical interface row open the action menu and click "Edit physical".
- you should see a form card and a table showing the interface.
Fixes: #2200.

feat(ui): display interface table on edit form

---

ui/.betterer.results
ui/src/app/base/hooks.test.ts
ui/src/app/base/hooks.ts
ui/src/app/machines/views/MachineDetails/MachineNetwork/AddInterface/AddInterface.tsx

- Add a hook to scroll to the add interface when it is displayed.
- View the network tab for a machine.
- Add a few interfaces or resize your window so that the table fills the screen.
- Click the add interfaces button. The window should scroll down to the form.
Fixes: #2170.

feat(ui): scroll to the interface form when opened

---

ui/src/app/base/actions/auth/auth.js
ui/src/app/base/actions/auth/auth.test.js
ui/src/app/base/components/UserForm/UserForm.js
ui/src/app/base/reducers/auth/auth.js
ui/src/app/base/reducers/auth/auth.test.js
ui/src/app/settings/views/Scripts/ScriptsList/ScriptsList.test.js
ui/src/app/settings/views/Users/UserForm/UserForm.js
ui/src/app/settings/views/Users/UserForm/UserForm.test.js

- Backport changes to allow admins to update users' passwords (see: https://github.com/canonical-web-and-design/maas-ui/pull/1806).
- As an admin change a user's password from /settings/user.
- Confirm that the password has changed correctly by logging in as that user with the new password. …

Backport changes to allow admins to update users' passwords.

---

ui/.betterer.results
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTableActions/NetworkTableActions.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTableActions/NetworkTableActions.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTableConfirmation/NetworkTableConfirmation.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/types.ts
ui/src/app/store/machine/utils/hooks.test.tsx
ui/src/app/store/machine/utils/hooks.ts
ui/src/app/store/machine/utils/index.ts
ui/src/app/store/machine/utils/networking.test.ts
ui/src/app/store/machine/utils/networking.ts
ui/src/app/store/vlan/selectors.test.ts
ui/src/app/store/vlan/selectors.ts

- Add an item to the row menu in the network table to add an alias or VLAN.
- View both the react and legacy network details for a machine.
- Open the menu for different rows and you should see an item for adding an alias or a vlan in the same cases as the legacy page.
Fixes: #2215.

feat(ui): add menu item for adding an alias or VLAN

---

ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTableActions/NetworkTableActions.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTableActions/NetworkTableActions.tsx

- Correctly check the interface type so that alises can't mark a connection as connected/disconnected.
- Open the network tab for a machine.
- Open the action menu on an alias row. There should be no mark connected/disconnected action.
Fixes: #2255.

fix(ui): aliases shouldn't have mark connection action

---

ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/ComposeFormFields/ComposeFormFields.test.tsx
ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/StorageTable/StorageTable.test.tsx
ui/src/app/kvm/components/KVMActionFormWrapper/KVMActionFormWrapper.test.tsx
ui/src/app/kvm/components/PodConfiguration/PodConfiguration.tsx
ui/src/app/kvm/components/PodConfiguration/PodConfigurationFields/PodConfigurationFields.test.tsx
ui/src/app/kvm/views/KVMDetails/KVMSummary/KVMSummary.tsx
ui/src/app/kvm/views/KVMList/KVMListTable/TypeColumn/TypeColumn.test.tsx
ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/DetailsCard/DetailsCard.test.tsx
ui/src/app/store/pod/selectors.test.ts
ui/src/app/store/pod/selectors.ts
ui/src/app/store/pod/types.ts
ui/src/app/store/pod/utils.ts
ui/src/testing/factories/nodes.ts

- Added selectors for:
- getting all virsh pods (will have its own table)
- getting all LXD pods
- grouping LXD pods by LXD server (for the KVM list)
- getting all LXD pods in a given LXD server (for calculating the overall resource usage of a LXD server)
- Added pod type enum since behaviour for LXD and virsh pods is becoming increasingly divergent …

feat(ui): add selectors for grouping/getting pods by LXD address

---

ui/.betterer.results
ui/src/app/base/components/DynamicSelect/DynamicSelect.test.tsx
ui/src/app/base/components/DynamicSelect/DynamicSelect.tsx
ui/src/app/base/components/DynamicSelect/index.ts
ui/src/app/base/components/FabricSelect/FabricSelect.tsx
ui/src/app/base/components/SubnetSelect/SubnetSelect.test.tsx
ui/src/app/base/components/SubnetSelect/SubnetSelect.tsx
ui/src/app/base/components/VLANSelect/VLANSelect.test.tsx
ui/src/app/base/components/VLANSelect/VLANSelect.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/AddInterface/AddInterface.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkFields/NetworkFields.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkFields/NetworkFields.tsx
ui/src/app/utils/index.ts
ui/src/app/utils/toFormikNumber.test.ts
ui/src/app/utils/toFormikNumber.ts

- Add a component to handle select boxes with dynamically updating values.
- View the network tab for a machine.
- Click add interface
- Fill out the network fields and save
- An interface should be added with the correct network details
Fixes: #2264.

feat(ui): add a component to handle selects with dynamic values

---

integration/cypress/integration/base/footer.spec.ts
shared/src/components/Footer/Footer.tsx
shared/src/components/Footer/__snapshots__/Footer.test.tsx.snap

lp#1913323
-------
- Link to /docs/ instead of a named HTML file therein
- Click local documentation and ensure you get to the index page of the local docs
lp#1913323

docs(shared): link to docs root instead of named file

---

ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTableActions/NetworkTableActions.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTableActions/NetworkTableActions.tsx
ui/src/scss/_vanilla-overrides.scss

- Add a tooltip when adding an alias or vlan is disabled.
- Go to the network tab of a machine.
- Create (or edit) a physical interface and choose a subnet then set the IP mode to be unconfigured and submit.
- Now visit the legacy page of the interface and using the row's action menu add VLANs until it won't let you add any more.
- Go back to the react page …

feat(ui): add disabled alias or vlan action tooltips

---

ui/src/app/base/components/FormCardButtons/FormCardButtons.test.tsx
ui/src/app/base/components/FormCardButtons/FormCardButtons.tsx
ui/src/app/base/components/FormikForm/FormikForm.tsx
ui/src/app/base/components/FormikFormContent/FormikFormContent.tsx

- Add the ability to disable and provide a tooltip for the secondary submit button in the formik form.
N/A
Fixes: #2280.

feat(ui): add disabled an tooltip props for secondary button in formik form

---

ui/src/app/store/machine/utils/networking.test.ts
ui/src/app/store/machine/utils/networking.ts

- Update the name generation utility to generate names for aliases and VLANs.
N/A
Fixes: #2282.

feat(ui): add generation of alias and VLAN names

---

ui/src/app/machines/views/MachineDetails/MachineNetwork/AddInterface/AddInterface.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/EditPhysicalForm/EditPhysicalForm.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkFields/NetworkFields.tsx

- Reuse the network validation and default values between the forms.
N/A
Fixes: #2281.

refactor(ui): share validation and types for network fields between the forms

---

ui/.betterer.results
ui/src/app/machines/views/MachineDetails/MachineNetwork/AddAliasOrVlan/AddAliasOrVlan.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/AddAliasOrVlan/AddAliasOrVlan.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/AddAliasOrVlan/AddAliasOrVlanFields/AddAliasOrVlanFields.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/AddAliasOrVlan/AddAliasOrVlanFields/AddAliasOrVlanFields.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/AddAliasOrVlan/AddAliasOrVlanFields/index.ts
ui/src/app/machines/views/MachineDetails/MachineNetwork/AddAliasOrVlan/index.ts
ui/src/app/machines/views/MachineDetails/MachineNetwork/AddAliasOrVlan/types.ts
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTable.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTableConfirmation/NetworkTableConfirmation.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTableConfirmation/NetworkTableConfirmation.tsx

- Add a form for creating aliases or vlans from the network table.
- View the network tab for a machine.
- Using the row menus open the add vlan or add alias form.
- Fill out the details and submit the form via the "create another" button (if it's enabled)
- The vlan/alias should be created.
- Submit the form using the green button. The form should close when …

feat(ui): add alias or vlan form

---

legacy/src/app/partials/node-details.html

- Fix the machine details header so that the tabs display and forms aren't broken
- View the machine details page for a machine.
- You should see the summary, storage, config etc. tabs in the details header.
- Open the commission form via the take action menu and submit.
- The form should close and you should see the tabs again …

Fix machine details header

---

ui/src/app/base/components/GroupCheckbox/GroupCheckbox.test.tsx
ui/src/app/base/components/GroupCheckbox/GroupCheckbox.tsx
ui/src/app/base/components/RowCheckbox/RowCheckbox.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/MachineNetwork.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NameColumn/NameColumn.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTable.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTable.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/types.ts
ui/src/app/utils/generateCheckboxHandlers.test.ts
ui/src/app/utils/generateCheckboxHandlers.ts

- Update the selected state of the network checkboxes to store the nic and link ids.
- View the network details for a machine.
- If it doesn't already have an alias then create one.
- Tick the checkboxes for different machine types. It should tick them correctly.
- Use the header checkbox to check/uncheck them all. That should also work correctly.
Fixes: …

fix(ui): update network checkboxes to handle links and nics

---

ui/src/app/store/machine/utils/networking.test.ts
ui/src/app/store/machine/utils/networking.ts

- Correctly check interfaces for bond or bridge children.
- View the legacy network tab for a machine.
- Add a physical interface.
- Use the physical interface's action menu to open the VLAN form and submit.
- Tick the checkbox for the physical interface and click the 'Create bridge' button and submit the form.
- Switch to the react network tab.
- You should …

fix(ui): fix interfaces with multiple children

---

ui/src/app/base/components/SwitchField/SwitchField.test.tsx
ui/src/app/base/components/SwitchField/SwitchField.tsx
ui/src/app/base/components/SwitchField/__snapshots__/SwitchField.test.tsx.snap
ui/src/app/base/components/SwitchField/index.ts

- Add a component for handling switches in forms. This follows the same shape as the inputs, selectors etc. in react components: https://github.com/canonical-web-and-design/react-components/blob/master/src/components/Input/Input.js.
N/A
Fixes: #2319.

feat(ui): add a switch form component

---

ui/src/app/machines/views/MachineDetails/MachineSummary/WorkloadCard/WorkloadCard.tsx

- Replaced placeholder docs link for workload annotations
- Go to the machine details page of an Allocated or Deployed machine
- Click the "Read more" link in the Workloads card
- Check that it takes you to a discourse page (which is currently empty, but will have content by 2.10 release)
Fixes …

feat(ui): add link to workload annotations discourse page

---

ui/src/app/machines/views/MachineDetails/MachineNetwork/BridgeForm/BridgeForm.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/BridgeForm/BridgeForm.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/BridgeForm/index.ts
ui/src/app/machines/views/MachineDetails/MachineNetwork/InterfaceFormTable/InterfaceFormTable.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/InterfaceFormTable/InterfaceFormTable.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/MachineNetwork.tsx

- Added a component to display the bridge table.
- Navigate to the react network tab for a machine.
- Select an interface and click the "Create bridge" button.
- A table should appear displaying the selected interface's details.
Fixes: #2307.

feat(ui): add the bridge form table

---

ui/src/app/machines/views/MachineDetails/MachineNetwork/BondForm/BondForm.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/BondForm/BondForm.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/BondForm/index.ts
ui/src/app/machines/views/MachineDetails/MachineNetwork/BridgeForm/BridgeForm.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/BridgeForm/BridgeForm.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/EditInterface/EditInterface.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/InterfaceFormTable/InterfaceFormTable.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/InterfaceFormTable/InterfaceFormTable.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/MachineNetwork.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTable.tsx
ui/src/app/utils/simpleSortByKey.ts
ui/src/scss/_patterns_tables.scss

- Add a table for managing the interfaces in a bond.
- View the react network tab for a machine.
- Create three physical interfaces with the same VLAN.
- Tick two of the interfaces and click "Create bond".
- You should see a table with the two interfaces you selected.
- Click "Edit bond members". You should see the third interface (and possibly others if …

feat(ui): add bond form table

---

ui/src/app/store/pod/types.ts
ui/src/testing/factories/nodes.ts

- Added types and test factories for pod.resources, which follows the shape seen [here](https://pastebin.canonical.com/p/VJCMtcBdVw/)
- N/A
Fixes #2345

feat(ui): add types and test factories for pod.resources

---

ui/src/app/machines/components/ActionFormWrapper/DeployForm/DeployForm.tsx
ui/src/app/machines/components/ActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.test.tsx
ui/src/app/machines/components/ActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.tsx
ui/src/app/store/general/selectors/osInfo.test.ts
ui/src/app/store/general/selectors/osInfo.ts
ui/src/app/store/general/types.ts

- Fix the selectors and components that fetch osinfo so that they can handle no data.
- Load the react network tab in machine details.
- Click 'Machines' in the header.
- The machine list should load without falling over.
Fixes: #2348.

fix(ui): fix race condition when loading osinfo

---

ui/src/app/store/general/utils/powerTypes.test.ts
ui/src/app/store/general/utils/powerTypes.ts

- Added proxmox field names to the add_chassis parameter map
- Make sure you're running the UI using `yarn start` not `yarn ui` because `add_chassis` is an http method
- Open the add chassis form from the machine list and choose Proxmox
- Submit the form without a password or token and check that you get an error
- Submit the …

fix(ui): add proxmox field names to add_chassis parameter map

---

ui/src/app/base/components/FormikForm/FormikForm.tsx
ui/src/app/base/components/FormikFormContent/FormikFormContent.test.tsx
ui/src/app/base/components/FormikFormContent/FormikFormContent.tsx

- Update the non-field error handling to show errors from keys that don't match form fields.
- Pass the `submitDisabled` prop through the form.
Check that the existing errors work:
- Visit the react network tab for a machine.
- Click "Add interface".
- Enter a mac address that is already in use.
- Submit the form. An error should be displayed below the mac …

feat(ui): show errors from non field keys

---

ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkActions/NetworkActions.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkActions/NetworkActions.tsx

- Update the network table action to only allow physical interfaces for a bond.
- View the react network tab.
- Tick a physical interfaces and alias that have the same VLAN.
- The 'Add bond' button should be disabled with a tooltip.
- Tick two physical interfaces that have the same VLAN.
- The 'Add bond' button should not be disabled.
Fixes: #2325.

feat(ui): only allow physical bond interfaces

---

ui/src/app/machines/views/MachineDetails/MachineNetwork/EditAliasOrVlanForm/EditAliasOrVlanForm.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/EditBridgeForm/EditBridgeForm.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/EditInterface/EditInterface.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTable.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTableConfirmation/NetworkTableConfirmation.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/TypeColumn/TypeColumn.tsx
ui/src/app/store/machine/utils/networking.test.ts
ui/src/app/store/machine/utils/networking.ts

- Display the Open vSwitch label for bridges.
- Open the react network tab for a machine.
- Create a physical interface if there isn't one.
- Tick the physical interface and click "Create bridge".
- Selected "Open vSwitch" for the bridge type and submit.
- When the bridge appears check that the type is displayed as "Open vSwitch".
- Open the action menu for …

feat(ui): show Open vSwitch labels

---

ui/.betterer.results
ui/src/app/machines/views/MachineDetails/MachineNetwork/AddBondForm/AddBondForm.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/AddBondForm/AddBondForm.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/AddBondForm/index.ts
ui/src/app/machines/views/MachineDetails/MachineNetwork/BondForm/BondFormFields/BondFormFields.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/BondForm/BondFormFields/BondFormFields.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/BondForm/ToggleMembers/ToggleMembers.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/BondForm/ToggleMembers/ToggleMembers.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/BondForm/ToggleMembers/index.ts
ui/src/app/machines/views/MachineDetails/MachineNetwork/BondForm/index.ts
ui/src/app/machines/views/MachineDetails/MachineNetwork/BondForm/types.ts
ui/src/app/machines/views/MachineDetails/MachineNetwork/BondForm/utils.test.ts
ui/src/app/machines/views/MachineDetails/MachineNetwork/BondForm/utils.ts
ui/src/app/machines/views/MachineDetails/MachineNetwork/InterfaceFormTable/InterfaceFormTable.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/InterfaceFormTable/InterfaceFormTable.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/MachineNetwork.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkFields/NetworkFields.tsx

- Extract parts of the bond form to be reused in the edit bond form.
- Create a bond in the new network tab, it should not have any errors.
Fixes: #2364.

refactor(ui): make parts of bond form reusable

---

ui/src/app/machines/views/MachineDetails/MachineNetwork/BondForm/ToggleMembers/ToggleMembers.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/BondForm/ToggleMembers/ToggleMembers.tsx

- Add analytics to the bond forms when users edit the bond members.
N/A
Fixes: #2185.

feat(ui): add analytics for editing bond members

---

ui/src/app/machines/views/MachineDetails/MachineNetwork/AddBondForm/AddBondForm.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/BondForm/BondFormFields/BondFormFields.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/BondForm/BondFormFields/BondFormFields.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/BondForm/types.ts
ui/src/app/machines/views/MachineDetails/MachineNetwork/BondForm/utils.test.ts
ui/src/app/machines/views/MachineDetails/MachineNetwork/BondForm/utils.ts
ui/src/testing/factories/nodes.ts

- Provide a way to use a mac address from a bond member in the bond forms.
- View the react network tab in machine details.
- Add two physical interfaces with the same VLAN.
- Tick the interfaces and click 'Create bond'.
- In the advanced options choose to either use a nic's MAC address or manually provide an address.
- Save and the mac should be set …

feat(ui): prefill mac address from member

---

ui/.betterer.results
ui/src/__snapshots__/root-reducer.test.js.snap
ui/src/app/kvm/views/KVMList/AddKVM/AddLxd/AddLxd.test.tsx
ui/src/app/kvm/views/KVMList/AddKVM/AddLxd/AddLxd.tsx
ui/src/app/kvm/views/KVMList/AddKVM/AddLxd/AddLxdFields/AddLxdFields.tsx
ui/src/app/store/pod/reducers.test.ts
ui/src/app/store/pod/selectors.test.ts
ui/src/app/store/pod/selectors.ts
ui/src/app/store/pod/slice.ts
ui/src/app/store/pod/types.ts
ui/src/testing/factories/index.ts
ui/src/testing/factories/nodes.ts
ui/src/testing/factories/state.ts

- Added `projects` key to pod state, which maps LXD server address to their projects
- Added actions/reducers/selectors for fetching projects
- Updated AddLXD form so that it first fetches projects before being able to add the KVM.
- Go to the KVM list and click "Add KVM"
- Select LXD type and check that the submit button says …

feat(ui): add ability to fetch LXD projects

---

ui/.betterer.results
ui/src/app/base/components/FormikFormContent/FormikFormContent.tsx
ui/src/app/base/hooks.ts
ui/src/app/machines/views/MachineDetails/MachineNetwork/BondForm/utils.test.ts
ui/src/app/machines/views/MachineDetails/MachineNetwork/BondForm/utils.ts
ui/src/app/machines/views/MachineDetails/MachineNetwork/EditBondForm/EditBondForm.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/EditBondForm/EditBondForm.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/EditBondForm/index.ts
ui/src/app/machines/views/MachineDetails/MachineNetwork/EditInterface/EditInterface.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/EditInterface/EditInterface.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/MachineNetwork.tsx
ui/src/app/utils/arrayItemsEqual.test.ts
ui/src/app/utils/arrayItemsEqual.ts
ui/src/app/utils/index.ts

- Add a form for editing bonds.
- View the react network tab for a machine with a bond (or create a bond by adding two physical interfaces on the same VLAN and then clicking 'Create bond').
- Add another physical interface on the same vlan as the bond.
- Use the row action menu to open the edit bond form.
- The green save button should be disabled.
- Click …

feat(ui): edit bond form

---

legacy/src/app/partials/node-details.html
ui/src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.tsx
ui/src/app/machines/views/MachineDetails/MachineSummary/NetworkCard/NetworkCard.tsx
ui/src/app/machines/views/MachineDetails/NodeDevices/NodeDevices.test.tsx
ui/src/app/machines/views/MachineDetails/NodeDevices/NodeDevices.tsx

- Enable navigating to the react network tab in machine details.
- Navigate to the summary tab of a machine.
- Click the tab for network, you should be taken to the /r/ network route.
- Navigate back to summary and click the link at the top or bottom of the network card, you should be taken to the /r/ network route.
- Click on the events tab, it should take …

feat(ui): enable the network route

---

ui/src/app/base/sagas/websockets.js
ui/src/app/base/sagas/websockets.test.js
ui/src/app/settings/views/Configuration/Commissioning/Commissioning.test.js
ui/src/app/settings/views/Configuration/Deploy/Deploy.test.js
ui/src/app/settings/views/Repositories/RepositoryForm/RepositoryForm.test.js
ui/src/app/store/general/actions.test.ts
ui/src/app/store/general/slice.ts

- Don't request general data if it has already been requested.
- Open your browsers network tab.
- Load the machine list.
- Click on Settings in the main nav.
- Find the websocket and clear the messages.
- Click on the machine list again.
- You should not see a bunch of general requests.
Fixes: #2213.

fix(ui): fix general websocket caching

---

legacy/src/app/partials/node-details.html

- Fix the route for the network tab in device details.
- Navigate to the details page for a device.
- Click on the "Network" tab.
- You should navigate to `/MAAS/l/device/[system_id]?area=network`
Fixes: #2384.

fix(legacy): fix device network tab route

---

ui/.betterer.results
ui/src/app/base/components/FormCard/FormCard.tsx
ui/src/app/kvm/views/KVMList/AddKVM/AddKVM.tsx
ui/src/app/kvm/views/KVMList/AddKVM/AddLxd/AddLxd.test.tsx
ui/src/app/kvm/views/KVMList/AddKVM/AddLxd/AddLxd.tsx
ui/src/app/kvm/views/KVMList/AddKVM/AddLxd/AddLxdFields/index.ts
ui/src/app/kvm/views/KVMList/AddKVM/AddLxd/AuthenticateForm/AuthenticateForm.test.tsx
ui/src/app/kvm/views/KVMList/AddKVM/AddLxd/AuthenticateForm/AuthenticateForm.tsx
ui/src/app/kvm/views/KVMList/AddKVM/AddLxd/AuthenticateForm/AuthenticateFormFields/AuthenticateFormFields.tsx
ui/src/app/kvm/views/KVMList/AddKVM/AddLxd/AuthenticateForm/AuthenticateFormFields/index.ts
ui/src/app/kvm/views/KVMList/AddKVM/AddLxd/AuthenticateForm/index.ts
ui/src/app/kvm/views/KVMList/AddKVM/AddLxd/SelectProjectForm/SelectProjectForm.test.tsx
ui/src/app/kvm/views/KVMList/AddKVM/AddLxd/SelectProjectForm/SelectProjectForm.tsx
ui/src/app/kvm/views/KVMList/AddKVM/AddLxd/SelectProjectForm/SelectProjectFormFields/SelectProjectFormFields.tsx
ui/src/app/kvm/views/KVMList/AddKVM/AddLxd/SelectProjectForm/SelectProjectFormFields/index.ts
ui/src/app/kvm/views/KVMList/AddKVM/AddLxd/SelectProjectForm/index.ts
ui/src/app/kvm/views/KVMList/AddKVM/AddLxd/index.ts

- Added project selection step to Add LXD KVM form
- Split `AddLxd` into two separate forms: `AuthenticateForm` and `SelectProjectForm`
- Go to the KVM list and click Add KVM
- Authenticate to an LXD server (bolla LXD at `10.1.238.1:8443` will work)
- Check that projects are successfully fetched and you are taken to the next …

feat(ui): add project selection step to Add LXD KVM form

---

ui/.betterer.results
ui/src/app/machines/views/MachineDetails/MachineNetwork/EditPhysicalForm/EditPhysicalFields/EditPhysicalFields.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/EditPhysicalForm/EditPhysicalFields/EditPhysicalFields.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/EditPhysicalForm/EditPhysicalFields/index.ts
ui/src/app/machines/views/MachineDetails/MachineNetwork/EditPhysicalForm/EditPhysicalForm.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/EditPhysicalForm/EditPhysicalForm.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/EditPhysicalForm/types.ts

- Update the edit physical interface form to show a warning instead of error when the link speed is
higher than the interface speed.
- Go to a machine's network tab.
- Open the action menu for a physical interface and click 'Edit ...'.
- Change the link speed to be higher than the interface speed.
- You should see a warning.
- Click save and it should let you …

fix(ui): make link speed a warning instead of error

---

ui/src/app/base/components/FormikForm/FormikForm.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/AddInterface/AddInterface.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/AddInterface/AddInterface.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/MachineNetwork.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/MachineNetwork.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkActions/NetworkActions.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NameColumn/NameColumn.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTable.tsx

- Centre align the PXE header in the network table.
- Indent mac addresses when there is a checkbox.
- Fix the space above the network table.
- Disable the save button when opening the add interface form.
- View the network tab for a machine.
- Check that there is a sensible amount of space between the add buttons and the interface table.
- Click 'Add …

fix(ui): network tab UX review fixes

---

ui/src/app/kvm/views/KVMList/AddKVM/AddLxd/SelectProjectForm/SelectProjectForm.test.tsx
ui/src/app/kvm/views/KVMList/AddKVM/AddLxd/SelectProjectForm/SelectProjectForm.tsx
ui/src/app/kvm/views/KVMList/AddKVM/AddLxd/SelectProjectForm/SelectProjectFormFields/SelectProjectFormFields.test.tsx
ui/src/app/kvm/views/KVMList/AddKVM/AddLxd/SelectProjectForm/SelectProjectFormFields/SelectProjectFormFields.tsx

- Changed project select dropdown to list of radio buttons.
- Projects already in use are now disabled with a link to the existing pod.
- User is now redirected to details page on save.
- Go to the KVM list and click Add KVM
- Authenticate to an LXD server (bolla LXD at `10.1.238.1:8443` will work)
- Select the existing project …

feat(ui): improve LXD project selection step in KVM form

---

legacy/src/app/partials/node-details.html

- Remove the options from the test form are only supposed to appear when commissioning.
- Go to the controller list and tick a controller that can be tested and using take action menu to open the test form.
- You should only see one checkbox for "Allow SSH acces...".
- Click on the controller to view the details and open the test form again.
- You should only …

fix(legacy): remove irrelevant testing options

---

ui/src/app/kvm/views/KVMList/LxdTable/LxdTable.tsx
ui/src/app/kvm/views/KVMList/LxdTable/_index.scss
ui/src/app/kvm/views/KVMList/VMsColumn/VMsColumn.test.tsx
ui/src/app/kvm/views/KVMList/VMsColumn/VMsColumn.tsx
ui/src/app/store/pod/types.ts
ui/src/testing/factories/nodes.ts

- Added LXD version to KVM list
- Go to the KVM list and check that LXD KVMs show the version
- If the version is empty that means it hasn't been refreshed since `version` was added to the pod model
Fixes #2398

feat(ui): add LXD version to KVM list

---

ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AddLogicalVolume/AddLogicalVolume.test.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AddLogicalVolume/AddLogicalVolume.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AddPartition/AddPartition.test.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AddPartition/AddPartition.tsx

- Use the available disk space as the default value for the sizes in the storage forms.
- View the storage tab for a machine.
- In the available storage table click 'Add partition'
- The form should open and the size field should match the disk's free space.
- Click 'Add partition'.
- Tick the new partition and click 'Create volume group' and submit.
- Open …

feat(ui): default sizes to the available disk space

---

ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/FilesystemFields/FilesystemFields.test.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/FilesystemFields/FilesystemFields.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/FilesystemsTable/AddSpecialFilesystem/AddSpecialFilesystem.test.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/FilesystemsTable/AddSpecialFilesystem/AddSpecialFilesystem.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/FilesystemsTable/FilesystemsTable.tsx
ui/src/app/store/machine/types.ts
ui/src/app/store/machine/utils/storage.test.ts
ui/src/app/store/machine/utils/storage.ts

- correctly filter filesystem select options to those that are supported by the machine, and that use storage if from the storage device list, or do not use storage if adding a special filesystem
- Click "Add special filesystem" and check that the filesystem options are …

fix(ui): correctly filter filesystem select options in machine storage tab

---

ui/src/app/kvm/views/KVMDetails/CoreResources/CoreResources.test.tsx
ui/src/app/kvm/views/KVMDetails/CoreResources/CoreResources.tsx
ui/src/app/kvm/views/KVMDetails/CoreResources/__snapshots__/CoreResources.test.tsx.snap
ui/src/app/kvm/views/KVMDetails/CoreResources/_index.scss
ui/src/app/kvm/views/KVMDetails/CoreResources/index.ts
ui/src/app/kvm/views/KVMDetails/LxdProject/LxdProject.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectResourcesCard/ProjectResourcesCard.test.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectResourcesCard/ProjectResourcesCard.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectResourcesCard/_index.scss
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectResourcesCard/index.ts
ui/src/app/kvm/views/KVMDetails/RamResources/RamResources.test.tsx
ui/src/app/kvm/views/KVMDetails/RamResources/RamResources.tsx
ui/src/app/kvm/views/KVMDetails/RamResources/__snapshots__/RamResources.test.tsx.snap
ui/src/app/kvm/views/KVMDetails/RamResources/_index.scss
ui/src/app/kvm/views/KVMDetails/RamResources/index.ts
ui/src/app/kvm/views/KVMDetails/StorageResources/StorageResources.tsx
ui/src/app/kvm/views/KVMDetails/StorageResources/_index.scss
ui/src/app/kvm/views/KVMDetails/StorageResources/index.ts
ui/src/scss/index.scss

- Created `RamResources` and `CoreResources` components which have mostly been lifted from `PodResourcesCard`, with some changes to work with the new data structure. The plan is to create all the resource sections as individual components then remove `PodResourcesCard`.
- Added `ProjectResourcesCard` to the projects tab, which currently includes the project's RAM and Core data. …

feat(ui): Add RAM and Cores info to LXD project tab

---

ui/src/app/machines/views/MachineDetails/MachineDetails.tsx
ui/src/app/machines/views/MachineDetails/MachineLogs/MachineLogs.test.tsx
ui/src/app/machines/views/MachineDetails/MachineLogs/MachineLogs.tsx
ui/src/app/machines/views/MachineDetails/MachineLogs/index.ts

- Add a component to hold the logs tab.
- Go to machine details.
- Click on Logs.
- You should see "Logs"
Fixes: https://github.com/canonical-web-and-design/maas-squad/issues/2362.

feat(ui): add the base logs tab

---

ui/src/app/machines/views/MachineDetails/MachineDetails.tsx
ui/src/app/machines/views/MachineDetails/MachineLogs/EventLogs/EventLogs.test.tsx
ui/src/app/machines/views/MachineDetails/MachineLogs/EventLogs/EventLogs.tsx
ui/src/app/machines/views/MachineDetails/MachineLogs/EventLogs/index.ts
ui/src/app/machines/views/MachineDetails/MachineLogs/MachineLogs.tsx

- Add a component to hold the event log.
- Visit the react logs tab for a machine.
- You should see sub tabs for events and installation output.
- Clicking on either tab should change the url.
- Clicking on the events log tab should display "Events"
Fixes: canonical-web-and-design/maas-squad#2370

feat(ui): add the events tab component

---

ui/src/app/kvm/views/KVMDetails/LxdProject/LxdProject.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/ProjectVMs.test.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/ProjectVMs.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsActionBar/VMsActionBar.test.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsActionBar/VMsActionBar.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsActionBar/__snapshots__/VMsActionBar.test.tsx.snap
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsActionBar/_index.scss
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsActionBar/index.ts
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsTable/VMsTable.test.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsTable/VMsTable.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsTable/index.ts
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/index.ts
ui/src/scss/_utilities.scss
ui/src/scss/index.scss

- Built non-interactive project VM action bar
- Added placeholder component for VMs table
- Go to the project tab of a LXD KVM
- Check that there is an action bar. Nothing happens when you click anything (...yet)
- Check that it looks alright on all screen sizes
Fixes #2232

feat(ui): Build project VM action bar scaffolding.

---

ui/.betterer.results
ui/src/app/machines/views/MachineDetails/MachineLogs/InstallationOutput/InstallationOutput.test.tsx
ui/src/app/machines/views/MachineDetails/MachineLogs/InstallationOutput/InstallationOutput.tsx
ui/src/app/machines/views/MachineDetails/MachineLogs/InstallationOutput/index.ts
ui/src/app/machines/views/MachineDetails/MachineLogs/MachineLogs.tsx

- Fetch and display the installation output in the logs tab.
- View the React logs tab for a deployed machine and click on the 'Installation output' sub-tab.
- The log should load (note: if you view the log for a machine that doesn't have one it shows a spinner, which will get addressed in https://github.com/canonical-web-and-design/maas-squad/issues/2375). …

feat(ui): display the installation output

---

ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/ProjectVMs.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsTable/NameColumn/NameColumn.test.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsTable/NameColumn/NameColumn.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsTable/NameColumn/index.ts
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsTable/StatusColumn/StatusColumn.test.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsTable/StatusColumn/StatusColumn.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsTable/StatusColumn/index.ts
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsTable/VMsTable.test.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsTable/VMsTable.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsTable/_index.scss
ui/src/app/machines/filter-nodes.test.ts
ui/src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.test.tsx
ui/src/app/machines/views/MachineDetails/MachineSummary/SummaryNotifications/SummaryNotifications.test.tsx
ui/src/app/machines/views/MachineDetails/MachineSummary/SummaryNotifications/SummaryNotifications.tsx
ui/src/app/machines/views/MachineList/MachineListTable/StatusColumn/StatusColumn.tsx
ui/src/app/store/machine/types.ts
ui/src/app/store/machine/utils/index.ts
ui/src/app/store/machine/utils/status.test.ts
ui/src/app/store/machine/utils/status.ts
ui/src/app/utils/getPowerIcon.test.ts
ui/src/scss/index.scss
ui/src/testing/factories/nodes.ts

- Built VMs table with column data for Name, Status, RAM, Storage and Resource pool (includes sorting).
- The remaining columns will require a bit more effort because they need to cross-reference `pod.resources`, so I'll do those as a follow-up ([GH issue](https://github.com/canonical-web-and-design/maas-ui/issues/2408))
- Go to …

feat(ui): first pass at building LXD project VM table

---

ui/src/app/base/validation.ts
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsTable/CoresColumn/CoresColumn.test.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsTable/CoresColumn/CoresColumn.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsTable/CoresColumn/index.ts
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsTable/HugepagesColumn/HugepagesColumn.test.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsTable/HugepagesColumn/HugepagesColumn.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsTable/HugepagesColumn/index.ts
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsTable/IPColumn/IPColumn.test.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsTable/IPColumn/IPColumn.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsTable/IPColumn/index.ts
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsTable/NameColumn/NameColumn.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsTable/VMsTable.tsx
ui/src/app/store/machine/types.ts
ui/src/app/store/pod/selectors.test.ts
ui/src/app/store/pod/selectors.ts
ui/src/testing/factories/index.ts
ui/src/testing/factories/nodes.ts

- Added remaining columns to the LXD VM table. The only thing that's missing is the name of the interface associated with an ip address, which I'll bring up with the core team.
- Go to the project tab of a LXD KVM and compose some machines with pinned/unpinned cores and hugepages backed/not backed.
- Check that the data in the …

feat(ui): add ips, hugepages and cores columns to LXD VM table

---

ui/src/app/machines/views/MachineDetails/MachineLogs/DownloadMenu/DownloadMenu.test.tsx
ui/src/app/machines/views/MachineDetails/MachineLogs/DownloadMenu/DownloadMenu.tsx
ui/src/app/machines/views/MachineDetails/MachineLogs/DownloadMenu/_index.scss
ui/src/app/machines/views/MachineDetails/MachineLogs/DownloadMenu/index.ts
ui/src/app/machines/views/MachineDetails/MachineLogs/MachineLogs.tsx
ui/src/scss/index.scss

- Add a component for downloading logs.
- Visit the React logs tab for a machine (visit machine details and change the URL from '/summary' to '/logs').
- You should see a download button to the right of the event/output sub-tabs.
- Clicking on the download button should show links, but they don't yet work.
Fixes: canonical-web-and-design/maas-squad#2219.

feat(ui): download log component

---

ui/src/app/machines/views/MachineDetails/MachineLogs/EventLogs/EventLogs.tsx
ui/src/app/machines/views/MachineDetails/MachineLogs/EventLogs/EventLogsTable/EventLogsTable.test.tsx
ui/src/app/machines/views/MachineDetails/MachineLogs/EventLogs/EventLogsTable/EventLogsTable.tsx
ui/src/app/machines/views/MachineDetails/MachineLogs/MachineLogs.tsx
ui/src/scss/_utilities.scss

- Add a searchbox and filter the events in the logs tab.
- Visit the React logs tab for a machine (visit machine details and change the URL from '/summary' to '/logs').
- Type something in the search box. It should filter the results.
Fixes: canonical-web-and-design/maas-squad#2218.

feat(ui): search events

---

ui/.betterer.results
ui/package.json
ui/src/app/machines/views/MachineDetails/MachineLogs/DownloadMenu/DownloadMenu.test.tsx
ui/src/app/machines/views/MachineDetails/MachineLogs/DownloadMenu/DownloadMenu.tsx
ui/src/app/machines/views/MachineDetails/MachineLogs/InstallationOutput/InstallationOutput.test.tsx
ui/src/app/machines/views/MachineDetails/MachineLogs/InstallationOutput/InstallationOutput.tsx
ui/src/app/machines/views/MachineDetails/MachineLogs/MachineLogs.tsx
ui/src/app/machines/views/MachineDetails/MachineLogs/hooks.test.tsx
ui/src/app/machines/views/MachineDetails/MachineLogs/hooks.ts
yarn.lock

- Add downloading of installation output to the logs tab.
- View a new machine.
- Go to the React logs tab (change /summary in the URL to /logs).
- There should be no "Installation output" in the download selector.
- Go to the React logs tab of a deployed machine.
- There should be an "Installation output" download. Click it and it should download a file …

feat(ui): download installation output

---

package.json

- Make it so that Cypress doesn't install when building the app.
N/A build should pass in CI.
Fixes: #2430.

build(all): don't install Cypress when building

---

ui/.betterer.results
ui/src/app/base/components/ArrowPagination/ArrowPagination.test.tsx
ui/src/app/base/components/ArrowPagination/ArrowPagination.tsx
ui/src/app/base/components/ArrowPagination/index.ts
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsActionBar/VMsActionBar.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsActionBar/__snapshots__/VMsActionBar.test.tsx.snap
ui/src/app/machines/views/MachineDetails/MachineLogs/EventLogs/EventLogs.test.tsx
ui/src/app/machines/views/MachineDetails/MachineLogs/EventLogs/EventLogs.tsx
ui/src/app/machines/views/MachineDetails/MachineLogs/EventLogs/EventLogsTable/EventLogsTable.test.tsx
ui/src/app/machines/views/MachineDetails/MachineLogs/EventLogs/EventLogsTable/EventLogsTable.tsx
ui/src/app/store/event/slice.ts

- Paginate the event log and fetch additional events.
- View the React logs tab for a machine (change /summary to /logs).
- You should see < > arrows to the right of the search box.
- Use those to navigate forward and back through the events.
- As you navigate forward it'll load more events if they exist.
Fixes: canonical-web-and-design/maas-squad#2372.

feat(ui): paginate the event log

---

ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsTable/IPColumn/IPColumn.tsx
ui/src/app/store/machine/types.ts

- Updated `BaseMachine` type to correctly reflect what parameters are optional, e.g. if no boot interface is set a few things are missing.
- In a LXD pod, compose a new machine or go to the machine details page of an existing one that can have its network edited
- Remove all of its interfaces
- Go to the project details page of …

fix(ui): correctly type machine parameters

---

ui/src/app/kvm/components/PodMeter/PodMeter.test.tsx
ui/src/app/kvm/components/PodMeter/PodMeter.tsx
ui/src/app/kvm/components/PodMeter/_index.scss
ui/src/app/kvm/components/PodStorage/PodStorage.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectResourcesCard/ProjectResourcesCard.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectResourcesCard/_index.scss
ui/src/app/kvm/views/KVMDetails/RamResources/_index.scss
ui/src/app/kvm/views/KVMDetails/StorageResources/StorageResources.test.tsx
ui/src/app/kvm/views/KVMDetails/StorageResources/StorageResources.tsx
ui/src/app/kvm/views/KVMDetails/StorageResources/__snapshots__/StorageResources.test.tsx.snap
ui/src/app/kvm/views/KVMDetails/StorageResources/_index.scss
ui/src/app/store/pod/selectors.test.ts
ui/src/app/store/pod/selectors.ts

- Built the initial version of the project storage section. Follow ups will include #2415 and #2432
- Added a selector to get a pod's storage pools sorted by default then id
- Go to the project tab of a LXD KVM
- Check that the storage section of the card matches the [design](https://github.com/canonical-web-and-design/maas-ui/is …

feat(ui): add storage section to project resources card

---

ui/.betterer.results
ui/src/app/machines/views/MachineDetails/MachineLogs/EventLogs/EventLogs.test.tsx
ui/src/app/machines/views/MachineDetails/MachineLogs/EventLogs/EventLogs.tsx
ui/src/scss/_patterns_forms.scss

- Add a page size selector and persist the size to local storage
- View the react logs page for a machine.
- There should be a "Show" selector next to the pagination buttons.
- Change the selector and the number of events should change.
- Refresh your window and the number should be restored.
Fixes: canonical-web-and-design/maas-squad#2373.

feat(ui): page size selector

---

ui/src/app/machines/views/MachineDetails/MachineLogs/EventLogs/EventLogs.test.tsx
ui/src/app/machines/views/MachineDetails/MachineLogs/EventLogs/EventLogs.tsx
ui/src/scss/_vanilla-overrides.scss

- Display a back to top link when there are at least 50 events.
- Go to the react logs tab for a machine.
- Make sure your page size selector is set to 25.
- There should be no back-to-top link at the bottom of the event list.
- Change the page size selector to show 50 or more events.
- There should no be a back-to-top link at the bottom of the event list.
- …

feat(ui): link back to top

---

ui/src/app/base/components/SectionHeader/SectionHeader.tsx
ui/src/app/base/components/SectionHeader/__snapshots__/SectionHeader.test.tsx.snap
ui/src/app/kvm/views/KVMDetails/KVMDetailsHeader/KVMDetailsHeader.test.tsx
ui/src/app/kvm/views/KVMDetails/KVMDetailsHeader/KVMDetailsHeader.tsx
ui/src/app/kvm/views/KVMDetails/KVMDetailsHeader/_index.scss
ui/src/app/kvm/views/KVMDetails/KVMResources/KVMResources.test.tsx
ui/src/app/kvm/views/KVMDetails/KVMResources/KVMResources.tsx
ui/src/app/kvm/views/KVMDetails/StorageResources/StorageResources.tsx
ui/src/app/kvm/views/KVMDetails/StorageResources/__snapshots__/StorageResources.test.tsx.snap
ui/src/scss/index.scss

- Updated KVM details header to include power address. Right now this is bespoke to `KVMDetailsHeader`. Originally I was going to update the `SectionHeader` component to allow a subtitle and "sidetext", but it seems like every instance `SectionHeader` uses a different set of props and it's getting a bit out of hand. I think this will all be removed when the application layout is applied anyway.
- [Building in a …

feat(ui): show KVM power address in section header

---

legacy/src/app/directives/pod-details/kvm_storage_dropdown.js
legacy/src/app/factories/nodes.js

- Remove optional chaining that isn't supported in 2.7.
- Run `CYPRESS_INSTALL_BINARY=0 yarn install && yarn build && yarn serve`.
- It should start without any errors about optional chaining in babel.
Fixes: #2444.

Remove optional chaining

---

ui/.betterer.results
ui/src/app/App.tsx
ui/src/app/base/file-context.test.ts
ui/src/app/base/file-context.ts
ui/src/app/base/sagas/websockets.js
ui/src/app/base/sagas/websockets.test.js
ui/src/app/machines/views/MachineDetails/MachineLogs/DownloadMenu/DownloadMenu.test.tsx
ui/src/app/machines/views/MachineDetails/MachineLogs/DownloadMenu/DownloadMenu.tsx
ui/src/app/store/machine/actions.test.ts
ui/src/app/store/machine/slice.ts
ui/src/app/store/machine/types.ts
ui/src/app/store/utils/slice.ts
ui/src/scss/_vanilla-overrides.scss
ui/src/testing/factories/state.ts

- Fetch machine summary files and storing them in the React context and allow downloading the files.
- View the React logs tab for a commissioned or deployed machine (change /summary to /logs).
- Open the download menu to the right of the sub-tabs.
- Click the YAML and XML items and the files should download.
Fixes: canonical-web-and-design/maas-ui#2426. …

feat(ui): download machine output

---

ui/.betterer.results
ui/src/app/base/sagas/http.js
ui/src/app/base/sagas/http.test.js
ui/src/app/machines/views/MachineDetails/MachineLogs/DownloadMenu/DownloadMenu.test.tsx
ui/src/app/machines/views/MachineDetails/MachineLogs/DownloadMenu/DownloadMenu.tsx
ui/src/app/store/scriptresult/types.ts

- Fetch and download the curtin logs.
- Visit this machine on bolla: http://projects.local:8400/MAAS/r/machine/mbfgbq/logs
- In the download menu there should be a `curtin-logs.tar` entry.
- Click it and it should download a tar file.
- Visit the React logs tab for a different machine (change /summary to /logs).
- Open the download menu and there shouldn't be …

feat(ui): download curtin logs

---

ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/ComposeForm.tsx
ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/ComposeFormFields/ComposeFormFields.test.tsx
ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/ComposeFormFields/ComposeFormFields.tsx
ui/src/app/store/pod/utils.test.ts
ui/src/app/store/pod/utils.ts

- Improved validation of VM compose core pinning
- Go to a KVM details page and open the Compose VM form
- Switch to pinning cores and check that help text shows which core indices are available
- Enter a core index that is unavailable and check that an error shows (you may need to blur the field)
- Enter duplicate core values …

feat(ui): improve validation of VM compose core pinning

---

ui/src/app/machines/views/MachineDetails/MachineLogs/DownloadMenu/DownloadMenu.tsx

- Add analytics to the logs download menu.
Fixes: canonical-web-and-design/maas-squad#2191.

feat(ui): add analytics when files are downloaded

---

ui/src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.tsx
ui/src/app/machines/views/MachineDetails/MachineSummary/SummaryNotifications/SummaryNotifications.tsx
ui/src/app/machines/views/MachineList/MachineListTable/StatusColumn/StatusColumn.tsx
ui/src/app/machines/views/MachineList/MachineListTable/StatusColumn/__snapshots__/StatusColumn.test.tsx.snap

- Update the URLs to navigate to the React logs tab.
- Navigate to the machine list.
- In the status column open the menu in one of the rows and click "See logs". It should take you to the new logs tab.
- Click on another tab and then click back on the "Logs" tab and it should show you the React tab.
Fixes: #2440.

feat(ui): enable logs URL

---

ui/src/app/machines/views/MachineDetails/MachineTests/MachineTestsDetails/MachineTestsDetails.test.tsx
ui/src/app/machines/views/MachineDetails/MachineTests/MachineTestsDetails/MachineTestsDetails.tsx
ui/src/app/machines/views/MachineDetails/MachineTests/MachineTestsDetails/__snapshots__/MachineTestsDetails.test.tsx.snap
ui/src/app/machines/views/MachineDetails/MachineTests/MachineTestsTable/TestHistory/TestHistory.test.tsx
ui/src/app/machines/views/MachineDetails/MachineTests/MachineTestsTable/TestHistory/TestHistory.tsx
ui/src/app/machines/views/MachineDetails/MachineTests/MachineTestsTable/index.scss
ui/src/app/store/scriptresult/reducers.test.ts
ui/src/app/store/scriptresult/selectors.test.tsx
ui/src/app/store/scriptresult/selectors.ts
ui/src/app/store/scriptresult/slice.ts

- Link to details for script history and fetch the results.
- Navigate to machine details and then commissioning or tests.
- Open the action menu for a result and click "view previous tests".
- There should be a "View log" link next to each result.
- Click "View log" and it should load the results.
Fixes: #2312.

feat(ui): display script history details

---

ui/src/app/machines/views/MachineDetails/MachineTests/MachineTestsTable/MachineTestsTable.tsx
ui/src/app/machines/views/MachineDetails/MachineTests/MachineTestsTable/ScriptRunTime/ScriptRunTime.test.tsx
ui/src/app/machines/views/MachineDetails/MachineTests/MachineTestsTable/ScriptRunTime/ScriptRunTime.tsx
ui/src/app/machines/views/MachineDetails/MachineTests/MachineTestsTable/ScriptRunTime/index.ts
ui/src/app/store/scriptresult/types.ts

- Add a component to display the elapsed time of scripts.
- Go to an LXD pod and compose a machine.
- Go to the machine details for the new machine and click on comissioning.
- Wait a while and you should see the scripts update and there should be elapsed times for some of them.
Fixes: #2311.

feat(ui): display script elapsed time

---

ui/src/app/machines/views/MachineDetails/MachineTests/MachineTests.test.tsx
ui/src/app/machines/views/MachineDetails/MachineTests/MachineTests.tsx
ui/src/app/store/scriptresult/types.ts

- Display names for tested devices where they exist.
- Find a machine that has run storage and network tests (or using the take action menu to run some).
- For storage and network test groups you should see (for most, not all tests) the device name (something like `/dev/vda` for storage and `ens4 (52:54:00:57:e2:ac)` for network), but not names like "null" or …

fix(ui): fix test device names

---

ui/src/app/base/components/ArrowPagination/ArrowPagination.test.tsx
ui/src/app/base/components/ArrowPagination/ArrowPagination.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/ProjectVMs.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsActionBar/VMsActionBar.test.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsActionBar/VMsActionBar.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsTable/VMsTable.test.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsTable/VMsTable.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/index.ts

- Paginated the LXD VMs table
- Open `ProjectVMs.tsx` and change the constant `VMS_PER_PAGE` to something low like 2 or 3.
- Go to the project tab of a LXD KVM and check that you can change the VMs table page by clicking the chevrons
- Check that the page bounds are correct
Fixes #2233

feat(ui): paginate LXD VMs table

---

ui/src/app/kvm/components/PodAggregateResources/PodAggregateResources.tsx
ui/src/app/kvm/views/KVMDetails/KVMDetails.test.tsx
ui/src/app/kvm/views/KVMDetails/KVMDetails.tsx
ui/src/app/kvm/views/KVMDetails/KVMResources/KVMNumaResources/KVMNumaResources.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/LxdProject.test.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/LxdProject.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/ProjectVMs.test.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/ProjectVMs.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsActionBar/VMsActionBar.test.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsActionBar/VMsActionBar.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsTable/VMsTable.test.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsTable/VMsTable.tsx
ui/src/app/kvm/views/KVMDetails/LxdResources/ProjectResourcesCard/ProjectResourcesCard.tsx
ui/src/app/kvm/views/KVMDetails/index.ts
ui/src/app/store/pod/selectors.test.ts
ui/src/app/store/pod/selectors.ts

- Added search to the LXD VM table
- Updated the `getVMs` pod selector to take the podId instead of the entire pod object
- Go to the "Project" tab of a LXD KVM
- Enter search terms in the search bar and check that the VMs get filtered accordingly (it uses the same search DSL as the machine list)
- Check that filtering to 0 VMs …

feat(ui): add search to LXD VM table

---

ui/src/scss/_vanilla-overrides.scss

- Fix focused active tabs and sidebar navigation links so that the highlighted item is shown.
- Go to machine details.
- Click on a tab. The active tab should be highlighted with a border.
- Go to settings (in the main nav).
- Click on a link in the sidebar. The active link should be highlighted with a border on the left.
Fixes: #2024.

fix(ui): fix active tab and navigation highlights

---

ui/src/app/kvm/views/KVMDetails/LxdResources/LxdResources.test.tsx
ui/src/app/kvm/views/KVMDetails/LxdResources/LxdResources.tsx
ui/src/app/kvm/views/KVMDetails/LxdResources/NumaResources/NumaResources.test.tsx
ui/src/app/kvm/views/KVMDetails/LxdResources/NumaResources/NumaResources.tsx
ui/src/app/kvm/views/KVMDetails/LxdResources/NumaResources/NumaResourcesCard/NumaResourcesCard.test.tsx
ui/src/app/kvm/views/KVMDetails/LxdResources/NumaResources/NumaResourcesCard/NumaResourcesCard.tsx
ui/src/app/kvm/views/KVMDetails/LxdResources/NumaResources/NumaResourcesCard/_index.scss
ui/src/app/kvm/views/KVMDetails/LxdResources/NumaResources/NumaResourcesCard/index.ts
ui/src/app/kvm/views/KVMDetails/LxdResources/NumaResources/_index.scss
ui/src/app/kvm/views/KVMDetails/LxdResources/NumaResources/index.ts
ui/src/app/kvm/views/KVMDetails/LxdResources/OverallResourcesCard/OverallRam/OverallRam.tsx
ui/src/app/kvm/views/KVMDetails/LxdResources/OverallResourcesCard/OverallRam/__snapshots__/OverallRam.test.tsx.snap
ui/src/app/kvm/views/KVMDetails/VfResources/VfResources.tsx
ui/src/scss/index.scss

- Rebuilt KVM NUMA cards using resources data instead of the now defunct numa_pinning data
- Go to the Resources tab of a LXD KVM
- Check that you can toggle the NUMA view on and off
- Open `NumaResources.tsx` and change line 28 so that between 2-4 and nodes show, e.g. `const numaNodes = [...resources.numa, ...resources.numa, …

feat(ui): rebuild KVM NUMA cards using resources data

---

ui/src/app/base/sagas/http.js
ui/src/app/base/sagas/http.test.js
ui/src/app/machines/views/MachineDetails/MachineLogs/DownloadMenu/DownloadMenu.test.tsx
ui/src/app/machines/views/MachineDetails/MachineLogs/InstallationOutput/InstallationOutput.test.tsx
ui/src/app/machines/views/MachineDetails/MachineLogs/hooks.test.tsx
ui/src/app/machines/views/MachineDetails/MachineLogs/hooks.ts
ui/src/app/store/scriptresult/selectors.test.tsx
ui/src/app/store/scriptresult/selectors.ts
ui/src/app/store/scriptresult/types.ts

- Fix the installation log so that the correct script result is selected.
- Point your local UI to Bolla.
- Visit /MAAS/r/machine/mbfgbq/logs/installation-output
- You should see the installation output.
- Open the download menu and download the curtin logs and the installation output.
- Both files should contain what you expect.
Fixes: #2471.

fix(ui): correctly select the installation log

---

ui/src/app/machines/views/MachineDetails/MachineCommissioning/MachineCommissioning.test.tsx
ui/src/app/machines/views/MachineDetails/MachineCommissioning/MachineCommissioning.tsx
ui/src/app/machines/views/MachineDetails/MachineTests/MachineTests.test.tsx
ui/src/app/machines/views/MachineDetails/MachineTests/MachineTests.tsx
ui/src/app/store/scriptresult/reducers.test.ts
ui/src/app/store/scriptresult/slice.ts

- Refetch testing and commissioning scripts when the testing/commissioning status changes.
- Go to machine details for a new/un-commissioned machine.
- Go to the commissioning tab.
- Use the take action menu to start commissioning.
- The list of scripts should update as commissioning happens.
- Go to the tests tab.
- Use the take action menu to start some tests.
- The tests tables should update as the tests run.
Fixes: #2314.

fix(ui): refetch testing and commissioning scripts

---

ui/src/app/kvm/views/KVMList/AddKVM/AddKVM.tsx
ui/src/app/kvm/views/KVMList/AddKVM/KvmTypeSelect/KvmTypeSelect.tsx

- made LXD the default host type when adding a new KVM
- Go to the KVM list and click "Add KVM" (or go straight to /MAAS/r/kvm/add)
- Check that LXD is first in the list and selected by default
Fixes #2466

feat(ui): make LXD the default host type when adding KVM

---

ui/src/app/base/components/ActionForm/ActionForm.tsx
ui/src/app/machines/components/ActionFormWrapper/ActionFormWrapper.test.tsx
ui/src/app/machines/components/ActionFormWrapper/ActionFormWrapper.tsx
ui/src/app/machines/components/ActionFormWrapper/CommissionForm/CommissionForm.tsx
ui/src/app/machines/components/ActionFormWrapper/DeployForm/DeployForm.tsx
ui/src/app/machines/components/ActionFormWrapper/FieldlessForm/FieldlessForm.js
ui/src/app/machines/components/ActionFormWrapper/MarkBrokenForm/MarkBrokenForm.tsx
ui/src/app/machines/components/ActionFormWrapper/OverrideTestForm/OverrideTestForm.js
ui/src/app/machines/components/ActionFormWrapper/ReleaseForm/ReleaseForm.tsx
ui/src/app/machines/components/ActionFormWrapper/SetPoolForm/SetPoolForm.js
ui/src/app/machines/components/ActionFormWrapper/SetZoneForm/SetZoneForm.js
ui/src/app/machines/components/ActionFormWrapper/TagForm/TagForm.js
ui/src/app/machines/components/ActionFormWrapper/TestForm/TestForm.tsx

- Fix a race condition when action forms are saved.
- Select a couple of machines that can be commissioned.
- Use the take action menu to start commissioning.
- Wait about 30 seconds and you shouldn't end up with the warning about updating your selection.
- Use the take action menu to abort commissioning.
- Wait about 30 seconds and …

fix(ui): fix closing action forms

---

ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsTable/StatusColumn/StatusColumn.tsx
ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/StatusCard/StatusCard.test.tsx
ui/src/app/machines/views/MachineList/MachineListTable/StatusColumn/StatusColumn.tsx
ui/src/app/store/machine/utils/hooks.test.tsx
ui/src/app/store/machine/utils/hooks.ts

- updated OS hook to show the full Ubuntu release by default, unless a flag is specifically passed to hide the title
- also updated it to not render until the os's have loaded, otherwise there'd be a flash of the unformatted version.
- Go to /MAAS/r/machine/fbknqx/summary and check that the Ubuntu release includes the title …

fix(ui): show full Ubuntu release in machine summary page

---

legacy/src/app/routes.js

- Update legacy links to redirect to the react machine details.
- Visit some legacy machine details urls e.g. /MAAS/l/machine/834see?area=logs and you should get redirected to the new tab.
Fixes: #2107.

feat(legacy): redirect to new machine details

---

ui/.betterer.results
ui/src/app/machines/components/ActionFormWrapper/DeployForm/DeployForm.test.tsx
ui/src/app/machines/components/ActionFormWrapper/DeployForm/DeployForm.tsx
ui/src/app/machines/components/ActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.test.tsx
ui/src/app/machines/components/ActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.tsx

- Added radio buttons to the deploy form to allow either LXD or libvirt VM hosts
- Open the network tab in the browser console check that the websocket connection can be found
- Open the Deploy form for a machine and submit the form without checking the "Deploy KVM" checkbox
- Check that the websocket request does not include …

feat(ui): allow either LXD or libvirt when deploying machine as VM host

---

ui/src/app/kvm/components/KVMActionFormWrapper/KVMActionFormWrapper.test.tsx
ui/src/app/kvm/components/KVMActionFormWrapper/KVMActionFormWrapper.tsx
ui/src/app/kvm/views/KVMDetails/KVMDetails.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsActionBar/VMsActionBar.test.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsActionBar/VMsActionBar.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsActionBar/_index.scss
ui/src/app/machines/components/ActionFormWrapper/ActionFormWrapper.tsx
ui/src/app/machines/components/TakeActionMenu/TakeActionMenu.test.tsx
ui/src/app/machines/components/TakeActionMenu/TakeActionMenu.tsx
ui/src/app/machines/components/TakeActionMenu/_index.scss
ui/src/scss/index.scss

- added machine action forms to LXD VM table
- Go to the Project tab of a LXD KVM
- Select at least one VM and click the "bin" icon
- Check that the delete form shows up, and you can close it by clicking "Cancel" or by deselecting all the selected machines
- Select some VMs and click the "menu" icon
- Check that the dropdown …

feat(ui): add machine action forms to LXD VM table

---

ui/src/app/store/pod/selectors.ts

- Fixed KVM page crashing when navigating to KVM details page (only seems to happen with a `make sampledata` MAAS though, not sure why...)
- Using a `make sampledata` MAAS, navigate to any KVM details page and check that the app doesn't crash
Fixes #2506

fix(ui): fix KVM page crashing when trying to sort storage pools

---

ui/.betterer.results
ui/src/app/machines/components/TakeActionMenu/TakeActionMenu.test.tsx
ui/src/app/machines/components/TakeActionMenu/TakeActionMenu.tsx

- Fixed take action menu being unusable in machine details (forgot to rename a couple of variables :grimacing:) 
- Go to any machine details page
- Check that the take action menu is not disabled and that you can perform actions as normal
- Check the machine list and LXD VM list as well
Fixes #2511

fix(ui): fix disabled machine details action menu

---

legacy/src/app/directives/controller_image_status.js
legacy/src/app/partials/nodes-list.html
legacy/src/scss/_patterns_icons.scss
ui/src/scss/index.scss

- Merge the image columns in the controller list.
- Go to the controller list.
- The image sync and status columns should be merged.
- For controllers that are synced you should see a tick icon.
Fixes: #2492.

feat(legacy): merge image columns

---

ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/StorageTable/StorageTable.test.tsx
ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/StorageTable/StorageTable.tsx

- VM compose storage table is now validated on render
- Open the Compose form for a KVM with less than 8GB of space and check that an error shows up by default
Fixes #2338

fix(ui): validate VM compose storage on render

---

legacy/src/app/controllers/node_details.js
legacy/src/app/controllers/tests/test_node_details.js

- Remove the machine model setup from node details.
- View the controller and device details pages. They should display without issue.
Fixes: #2541.

refactor(legacy): remove machine setup

---

ui/src/app/machines/views/MachineDetails/MachineDetails.test.tsx
ui/src/app/machines/views/MachineDetails/MachineDetails.tsx

- Display a message if a machine can not be found.
- Try to view the machine details for a machine that does not exist e.g. `/MAAS/r/machine/notamachine/summary`.
- You should see a message.
Fixes: #2195.

fix(ui): display a message if a machine does not exist

---

ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/ComposeForm.tsx
ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/ComposeFormFields/ComposeFormFields.test.tsx
ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/InterfacesTable/InterfacesTable.test.tsx
ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/InterfacesTable/InterfacesTable.tsx
ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/InterfacesTable/SubnetSelect/SubnetSelect.test.tsx
ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/InterfacesTable/SubnetSelect/SubnetSelect.tsx
ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/InterfacesTable/SubnetSelect/_index.scss
ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/InterfacesTable/_index.scss

- Made "Subnet" a required field in the VM compose interface table
- Added validation for when there's multiple interfaces that at least one is connected to a PXE bootable network
- Open the VM compose form and choose to define interfaces
- Check that the Subnet select shows an error by default, urging the user to select a …

fix(ui): fix KVM compose interface constraint validation

---

ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/StatusCard/StatusCard.test.tsx
ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/StatusCard/StatusCard.tsx
ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/_index.scss
ui/src/app/machines/views/MachineList/MachineListTable/StatusColumn/StatusColumn.tsx
ui/src/app/utils/breakLines.test.ts
ui/src/app/utils/breakLines.ts
ui/src/app/utils/index.ts

- Display the broken message in a tooltip in the machine list.
- Display the broken message in the machine summary.
Add a util for adding newlines to text for the tooltip.
- Mark a machine as broken.
- Go to the machine list and hover the message, it should appear in a tooltip.
- Go to the machine's summary and the message should appear below the status. …

feat(ui): improve display of broken messages

---

legacy/src/app/directives/power_parameters.js
legacy/src/app/directives/tests/test_power_parameters.js

- Always display power password fields with type="password", regardless of whether it's being edited.
- Go to the legacy machine details page of a machine that can have its power configuration edited (e.g. `grown-krill` on bolla)
- Change the power type to something that uses a password and check that the password field stays as …

fix(legacy): always display power password fields with type="password"

---

ui/src/app/kvm/views/KVMDetails/KVMResources/OverallResourcesCard/OverallCores/OverallCores.tsx
ui/src/app/kvm/views/KVMDetails/KVMResources/OverallResourcesCard/OverallCores/__snapshots__/OverallCores.test.tsx.snap
ui/src/app/kvm/views/KVMDetails/KVMResources/OverallResourcesCard/OverallRam/OverallRam.tsx
ui/src/app/kvm/views/KVMDetails/KVMResources/OverallResourcesCard/OverallRam/__snapshots__/OverallRam.test.tsx.snap
ui/src/app/kvm/views/KVMList/CPUColumn/CPUColumn.test.tsx
ui/src/app/kvm/views/KVMList/CPUColumn/CPUColumn.tsx
ui/src/app/kvm/views/KVMList/CPUColumn/CPUPopover/CPUPopover.test.tsx
ui/src/app/kvm/views/KVMList/CPUColumn/CPUPopover/CPUPopover.tsx
ui/src/app/kvm/views/KVMList/CPUColumn/CPUPopover/__snapshots__/CPUPopover.test.tsx.snap
ui/src/app/kvm/views/KVMList/RAMColumn/RAMColumn.test.tsx
ui/src/app/kvm/views/KVMList/RAMColumn/RAMColumn.tsx
ui/src/app/kvm/views/KVMList/RAMColumn/RAMPopover/RAMPopover.test.tsx
ui/src/app/kvm/views/KVMList/RAMColumn/RAMPopover/RAMPopover.tsx
ui/src/app/kvm/views/KVMList/RAMColumn/RAMPopover/__snapshots__/RAMPopover.test.tsx.snap

- Fixed KVM list resource usage, taking resource over-commit into account
- Changed the colours for the Overall charts so that Project is blue and Others is green. I think this makes more sense because it's consistent with everywhere else that uses blue to mean the resources used by the VM host itself.
- Go to the KVM list and …

fix(ui): fix KVM list resource usage calculations

---

proxy/package.json
proxy/scripts/ready.js
proxy/scripts/start.js
proxy/scripts/ui.js
yarn.lock

- Display message when loading clients in the console.
- Run `dotrun` or `yarn start`.
- At the start you should see a red message about waiting for the clients to load.
- After all the clients have started you should see a message with the URL to load.
- Visiting that URL should show you the app.
- Run `dotrun ui` or `yarn ui`.
- Shortly you should see a …

feat(proxy): dev console messages

---

ui/src/app/base/components/NotificationGroup/Notification/Notification.test.tsx
ui/src/app/base/components/NotificationGroup/Notification/Notification.tsx
ui/src/app/base/components/NotificationGroup/Notification/__snapshots__/Notification.test.tsx.snap
ui/src/app/base/components/NotificationList/NotificationList.test.tsx
ui/src/app/base/components/NotificationList/__snapshots__/NotificationList.test.tsx.snap
ui/src/app/store/notification/selectors.test.ts
ui/src/app/store/notification/selectors.ts
ui/src/app/store/notification/types.ts
ui/src/app/store/notification/utils.test.ts
ui/src/app/store/notification/utils.ts
ui/src/app/store/utils/identifiers.ts
ui/src/app/store/utils/index.ts
ui/src/scss/_patterns_notifications.scss
ui/src/testing/factories/notification.ts

- Handle upgrade notifications in the React client.
- Cleanup of notification types.
- SSH to bolla.
- Log in to the MAAS CLI (`maas login [PROFILE_NAME] http://localhost:5240/MAAS/`).
- To make the following commands easer run `export PROFILE_NAME=[PROFILE_NAME_FROM_LOGIN]`.
- Run:
```
maas $PROFILE_NAME notifications create ident='upgrade_version_issue' category='warning' users=true admins=true dismissable=false message='MAAS 2.9.3 is available but multiple controller versions are detected. <a href="/MAAS/l/controllers">Review controllers.</a>.'
```
- Then run:
```
maas $PROFILE_NAME …
```

feat(ui): add upgrade notifications

---

ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/ComposeForm.tsx
ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/ComposeFormFields/ComposeFormFields.test.tsx
ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/ComposeFormFields/ComposeFormFields.tsx
ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/StorageTable/StorageTable.test.tsx
ui/src/app/utils/formatBytes.test.ts
ui/src/app/utils/formatBytes.ts

- Updated VM compose validation to use pod.resources data instead of the (now incorrect for LXD VM hosts) pod hints.
- Open the Compose form for a LXD VM host and check that the help text for free RAM and free cores matches what's shown in the charts below.
Fixes #2562

fix(ui): use pod.resources for VM compose validation

---

ui/src/app/kvm/views/KVMList/AddKVM/AddLxd/SelectProjectForm/SelectProjectFormFields/SelectProjectFormFields.tsx

- added help text to the "Add LXD project" form
- Go to bolla and click "Add KVM"
- Use any name and any existing LXD address and click "Authenticate"
- Check that there is help text under the "Add new project" field
Fixes canonical-web-and-design/MAAS-squad#2384

fix(ui): add help text to Add LXD project form

---

ui/.betterer.results
ui/src/app/kvm/views/KVMList/LxdTable/LxdTable.test.tsx
ui/src/app/kvm/views/KVMList/LxdTable/LxdTable.tsx

- added sorting to LXD project list, which simultaneously fixed a bug where the order of the LXD pods depended on when they were loaded into state
- Go to the KVM list and check that you can sort LXD groups as well as the projects within the groups
Fixes canonical-web-and-design/MAAS-squad#2406

feat(ui): add sorting to LXD project list

---

legacy/src/app/partials/nodes-list.html
legacy/src/scss/_patterns_filter.scss
ui/src/scss/_vanilla-overrides.scss

- Fixed a couple of minor QA issues in the devices pages:
- removed internal scrollbar from device filter dropdown (also hotfixed in the React machine list)
- added "is-required" class to required fields in "Add device" form. This form has bigger issues with validation but fixing it in angular is a huge pain. Same goes for the Edit interface form - would be more work than it's worth fixing it now, will just get it right when we migrate the pages to React.
- Serving with …

fix(legacy): devices list QA fixes

---

legacy/src/app/controllers/nodes_list.js
legacy/src/app/controllers/tests/test_nodes_list.js
legacy/src/app/partials/nodes-list.html
legacy/src/scss/tables/_patterns_table-controllers.scss
ui/src/app/store/controller/types.ts

- Add the VLAN column to the controller table.
- Update controller types.
- Connect your UI to Bolla.
- Load the controllers list.
- You should see a VLAN column and it should display HA/non-HA counts (if available).
Fixes: #2489.
Fixes: #2576.

feat(legacy): add controller VLANs column

---

ui/src/app/kvm/components/KVMActionFormWrapper/KVMActionFormWrapper.tsx

- Used scroll hook to scroll to top when KVM action form renders
- Go to a LXD project page and scroll down a bit
- Check that the window scrolls to the top when you click any of the buttons in the VM table'saction toolbar

feat(ui): scroll to top when opening KVM action form

---

ui/src/app/base/components/ActionForm/ActionForm.tsx
ui/src/app/base/components/DhcpForm/DhcpForm.tsx
ui/src/app/base/components/DhcpForm/types.ts
ui/src/app/base/components/FormikForm/FormikForm.tsx
ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/ComposeForm.tsx
ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/ComposeFormFields/ComposeFormFields.test.tsx
ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/ComposeFormFields/ComposeFormFields.tsx

- Validate cores + memory on mount for VM compose form
- Go to the details page for a KVM that has less than 1024 MiB memory and/or 0 cores available
- Check that an error shows for memory and/or cores
- Delete some VMs so that you have more than 1024MiB memory and/or at least 1 core
- Check that no errors show
Fixes …

fix(ui): validate available cores + memory on VM compose form render

---

legacy/src/app/controllers/nodes_list.js
legacy/src/app/controllers/tests/test_nodes_list.js
legacy/src/app/partials/nodes-list.html

- Display the origin for deb installs in the controller list.
- There is no easy way to QA this so the data will need to be faked for now.
- Open `legacy/src/app/controllers/nodes_list.js`.
- Go to line 855 and replace the function with:
```typescript
$scope.getVersions = function (controller) {
return {
origin: "ppa:maas/3.0-next",
cohortTooltip: null, …
```

feat(legacy): display the origin for debs

---

legacy/src/app/controllers/nodes_list.js
legacy/src/app/controllers/tests/test_nodes_list.js
legacy/src/app/partials/nodes-list.html

- Prevent the action form from being submitted when a zone hasn't been selected.
- Go to the controller list.
- Tick a controller and open the set zone form.
- The submit button should be disabled.
- Choose a zone and the button should become enabled.
- Do the same for the device list.
Fixes: #2607.

fix(legacy): fix error when no zone is selected

---

legacy/src/app/controllers/nodes_list.js
legacy/src/app/controllers/tests/test_nodes_list.js

- Fix the controller list from entering an infinite loop when unselecting all controllers.
- Go to the controller list.
- Use the check-all checkbox to select all controllers.
- Open the set zone form.
- Select a zone and submit.
- Open the delete form and then cancel.
- Untick the check-all checkbox and there should not be any errors in your console.
Fixes: …

fix(legacy): fix infinite loop when unselecting controllers

---

ui/src/scss/_patterns_table-actions.scss

- Correctly space buttons in the settings list pages.
- Go to 'Page repos' in Settings.
- There should be space between the search box and the two 'Add ...' buttons.
- Click on some other list pages in settings and the search box/add button spaces should look OK.
Fixes: #2586.

fix(ui): fix spacing between settings buttons

---

shared/src/components/Header/HardwareMenu/HardwareMenu.tsx

- Fix an error when clicking on the header logo when the hardware menu is open.
- Open a legacy page.
- Resize your window so that the hardware menu shows in the header.
- Open the hardware menu.
- Click on the MAAS logo in the header.
- The hardware menu should close and there shouldn't be an error in your console.
Fixes: #2599.

fix(shared): fix error when closing menu

---

ui/src/app/machines/views/MachineDetails/MachineNetwork/DHCPTable/DHCPTable.tsx

- Display a message in the machine DHCP table when no DHCP snippets are applied.
- Go to the network tab in machine details.
- If there are no DHCP snippets applied to the machine there should be a message saying so under the table.
Fixes: #2619.

feat(ui): display a message when a machine has no DHCP snippets

---

ui/src/app/base/components/GroupCheckbox/GroupCheckbox.test.tsx
ui/src/app/base/components/GroupCheckbox/GroupCheckbox.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTable.tsx
ui/src/app/utils/generateCheckboxHandlers.test.ts
ui/src/app/utils/generateCheckboxHandlers.ts

- Show the all-ticked states in the header checkbox in the machine network tab.
- Go to the network tab for a machine.
- Check some of the interfaces. The table header checkbox should show the mixed state [-].
- Tick all the interfaces. The header checkbox should be ticked.
Fixes: #2618.

fix(ui): fix network table header checkbox

---

ui/src/app/machines/components/ActionFormWrapper/ActionFormWrapper.tsx

- When a machine action form opens then scroll to the top.
- Open machine details for a machine that hasn't yet had tests run (e.g. a new machine).
- Scroll down and click "Test network...".
- You should get scrolled to the open form at the top.
Fixes: #2622.

feat(ui): scroll to action forms when they open

---

legacy/src/app/controllers/vlan_details.js
legacy/src/app/partials/fabric-details.html
legacy/src/app/partials/networks-list.html
legacy/src/app/partials/space-details.html
legacy/src/app/partials/subnet-details.html
legacy/src/app/partials/vlan-details.html

- Fixed a few oddly formatted tooltips
- Fixed undefined spaces linking to a non-existent page
- Fixed console error when clicking "Enable DHCP" for a subnet with no available ranges
- Fixed links to old machine details page
- Changed "Delete space" button to red
- Point the UI to bolla and go to `/MAAS/l/networks?by=space`
- …

fix(legacy): fix subnets pages QA issues

---

legacy/src/app/controllers/node_details.js
legacy/src/app/controllers/tests/test_node_details.js
ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/DetailsCard/DetailsCard.test.tsx
ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/DetailsCard/DetailsCard.tsx
ui/src/app/store/pod/types.ts
ui/src/app/store/pod/utils.ts
ui/src/testing/factories/index.ts
ui/src/testing/factories/nodes.ts

- Removed all instances of `pod.numa_pinning` from the codebase
- Removed `getPodNumaID` util which only works when the `pod` is active with the new `resources` structure. I think this is okay, because the NUMA-alignment message was added before we even had the KVM NUMA node view. Now it's much easier to see NUMA resource usage. …

fix(ui): remove old pod.numa_pinning utils + types

---

ui/src/app/machines/views/MachineDetails/MachineTests/MachineTestsTable/index.scss

- Fix the padding around the previous tests table.
- Go to the tests tab for a machine that has run tests multiple times.
- Use the row action menu for a test result to open the previous tests.
- The table of previous tests should line up with the parent results.
Fixes: #2625.

fix(ui): fix the alignment of previous tests

---

legacy/src/app/controllers/nodes_list.js
legacy/src/app/controllers/tests/test_nodes_list.js
legacy/src/app/partials/nodes-list.html

- Display the number of VLANs for each controller in the controller list.
- Go to the list of controllers.
- In the VLAN column there should be a total VLAN count for each controller.
- Click on the count and it should take you to the VLANs tab in the controller details page.
Fixes: #2589.

feat(legacy): display controller VLAN counts

---

ui/src/app/machines/views/MachineDetails/MachineStorage/FilesystemsTable/FilesystemsTable.test.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/FilesystemsTable/FilesystemsTable.tsx

- Disable the action menus in the filesystems table when the machine is not ready or allocated.
- Find (or set up) a machine that is not ready or allocated and has an entry in the 'Filesystems' table (in the storage tab of machine details).
- Check that the action menu is disabled for the filesystem row.
Fixes: #2630.

fix(ui): disable filesystems action menu when not editable

---

ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AddLogicalVolume/AddLogicalVolume.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AddPartition/AddPartition.tsx
ui/src/app/store/machine/utils/storage.ts
ui/src/app/utils/formatBytes.test.ts
ui/src/app/utils/formatBytes.ts

- Updated formatBytes to be able to change rounding direction. Removed toPrecision which was a bit
too unreliable and inconsistent.
- Go to the storage tab of a Ready or Allocated machine (e.g. /MAAS/r/machine/bx7taq/storage on bolla)
- Create a partition of size 1001MB
- Check that the free space correctly rounds down
- Open …

fix(ui): round free storage values down in machine details

---

ui/src/single-spa-entry.js

- Fix updating the url when the React app loads so that it doesn't remove the querystring.
- Click on AZs in the header.
- In the machines column click one of the numbers.
- You should get taken to the machine list and the zone should be filtered.
Fixes: #2614.

fix(ui): fix loading urls with querystrings

---

ui/.betterer.results
ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/ComposeForm.tsx
ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/StorageTable/PoolSelect/PoolSelect.test.tsx
ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/StorageTable/PoolSelect/PoolSelect.tsx
ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/StorageTable/StorageTable.tsx

- Round free storage values down in KVM compose form
- Updated `PoolSelect` to do all calculations in bytes rather than GB, and only convert to GB for the display
- This is probably easiest to QA on bolla using the `another` VM host (/MAAS/r/kvm/337/project), otherwise you need to use a KVM that has a storage pool with available …

fix(ui): round free storage values down in KVM compose form

---

ui/package.json
ui/src/app/settings/views/Scripts/ScriptsList/ScriptsList.test.tsx
ui/src/app/settings/views/Scripts/ScriptsList/ScriptsList.tsx

- Correctly parse script creation date in settings
- Go to Settings > Testing scripts and check that the scripts have an uploaded date (i.e. they're not all "Never")
- Upload a script and check that the uploaded date is displayed as the current time in your timezone.
Fixes #2642

fix(ui): correctly parse script creation date in settings

---

ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/InterfacesTable/InterfacesTable.test.tsx
ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/InterfacesTable/InterfacesTable.tsx
ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/InterfacesTable/SubnetSelect/SubnetSelect.test.tsx
ui/src/app/store/subnet/selectors.test.ts
ui/src/app/store/subnet/selectors.ts

- Preselect first PXE network when defining composed VM interface
- Go to a KVM details page and open the Compose VM form
- Click the button to define an interface
- Check that the first available PXE network (i.e. one with a green tick) is preselected
Fixes #2647

fix(ui): preselect first PXE network when defining composed VM interface

---

ui/src/app/kvm/views/KVMDetails/KVMDetails.test.tsx
ui/src/app/kvm/views/KVMDetails/KVMDetailsHeader/KVMDetailsHeader.test.tsx
ui/src/app/kvm/views/KVMDetails/KVMDetailsHeader/KVMDetailsHeader.tsx
ui/src/app/kvm/views/KVMDetails/StorageResources/StorageResources.tsx
ui/src/app/kvm/views/KVMList/LxdTable/LxdTable.tsx
ui/src/app/kvm/views/KVMList/StorageColumn/StorageColumn.test.tsx
ui/src/app/kvm/views/KVMList/StorageColumn/StorageColumn.tsx
ui/src/app/kvm/views/KVMList/VMsColumn/VMsColumn.test.tsx
ui/src/app/kvm/views/KVMList/VMsColumn/VMsColumn.tsx
ui/src/app/kvm/views/KVMList/VirshTable/VirshTable.test.tsx
ui/src/app/kvm/views/KVMList/VirshTable/VirshTable.tsx
ui/src/app/kvm/views/KVMList/VirshTable/_index.scss
ui/src/app/store/pod/types.ts
ui/src/testing/factories/index.ts
ui/src/testing/factories/nodes.ts

- Removed all instances of `pod.composed_machines_count`, `pod.available`, `pod.used` and `pod.total` and replaced with equivalents found in the `pod.resources` field.
- Go to the KVM list and check that the VM and storage cells are unchanged
- Check that you can still sort KVMs by VM count and storage
- Go to a KVM details page …

feat(ui): replace legacy pod websocket fields with 'resources' equivalents

---

legacy/src/app/controllers/subnet_details.js
legacy/src/app/controllers/tests/test_subnet_details.js
legacy/src/app/factories/general.js
legacy/src/app/factories/subnets.js
legacy/src/app/factories/tests/test_general.js
legacy/src/app/factories/tests/test_subnets.js
legacy/src/app/partials/subnet-details.html
legacy/src/scss/tables/_base_tables.scss

- Added ability to disable boot architectures per subnet (default is all enabled).
- Added `p-table__row--interactive` class modifier for the different hover/selected states.
- Go to a subnet details page
- Open the action menu and choose "Edit boot architectures"
- Check that you can change which of the boot architectures are …

feat(legacy): allow disabling boot architectures in subnet details

---

ui/src/app/store/machine/utils/index.ts
ui/src/app/store/machine/utils/networking.ts
ui/src/app/store/machine/utils/storage.test.ts
ui/src/app/store/machine/utils/storage.ts
ui/src/app/utils/getNextName.test.ts
ui/src/app/utils/getNextName.ts
ui/src/app/utils/index.ts

- Refactor storage and network utils to find the next name in the sequence.
- Go to the network tab in machine details.
- Create some interfaces and they should get named appropriately.
- Go to the storage tab.
- Create some interfaces and they should get named appropriately.
Fixes: #2188.

refactor(ui): create util for generating next names

---

ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTable.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/_index.scss
ui/src/app/machines/views/MachineDetails/NodeDevices/NodeDevices.tsx
ui/src/app/machines/views/MachineDetails/NodeDevices/_index.scss
ui/src/app/machines/views/MachineList/MachineListTable/MachineListTable.js
ui/src/app/machines/views/MachineList/_index.scss
ui/src/scss/_patterns_tables.scss
ui/src/scss/_truncated-border.scss

- Update the machine and network lists to use the trucated border mixin.
- The borders for machines inside a group should be indented by the width of the parent checkbox.
- Click on a machine and go to the network tab.
- Create a bond (or find a machine with a bond).
- The borders for the bond interfaces should be indented by the …

refactor(ui): use the trancated border mixin for all tables

---

scripts/lp-bugs-to-gh-issues.py

- Extended `scripts/lp-bugs-to-gh-issues.py` to close LP bugs when GH issue is closed.
- from `lp-shell`
```
In [2]: len(p.searchTasks(status=["New", "Confirmed", "Triaged"], tags=["ui"], status_upstream='resolved_upstream'))
Out[2]: 29   
In [3]: for task in p.searchTasks(status=["New", "Confirmed", "Triaged"], tags=["ui"], status_upstream='resolved_upstream'):                                  
...:     task.status = 'Fix Committed'                                     
...:     task.lp_save()
```

feat(scripts): Mark LP bugs as Fix Committed when GH issue is closed

---

legacy/src/app/controllers/subnet_details.js
legacy/src/app/controllers/tests/test_subnet_details.js
legacy/src/app/partials/subnet-details.html
legacy/src/scss/tables/_base_tables.scss

- In the subnet details edit boot architecture form:
- Made entire arch row clickable.
- Made boot arch table sortable.
- Added link to boot arch discourse page.
- Go to a subnet details page and click "Take action" > "Edit boot architectures"
- Check that there is a "More info" link that takes you to the boot architectures …

fix(legacy): QA fixes for subnet boot architectures form

---

ui/.betterer.results
ui/src/__snapshots__/root-reducer.test.js.snap
ui/src/app/store/discovery/actions.test.ts
ui/src/app/store/discovery/index.ts
ui/src/app/store/discovery/reducers.test.ts
ui/src/app/store/discovery/selectors.test.ts
ui/src/app/store/discovery/selectors.ts
ui/src/app/store/discovery/slice.ts
ui/src/app/store/discovery/types.ts
ui/src/app/store/root/types.ts
ui/src/app/store/utils/slice.ts
ui/src/root-reducer.js
ui/src/testing/factories/discovery.ts
ui/src/testing/factories/index.ts
ui/src/testing/factories/state.ts

- Added discovery model to store (slice, selectors, types), including actions for deleting and clearing
- This can't really be QA'd properly until the dashboard/network discovery page is being worked on for real. In the mean time you could just pick a component to add `import { actions as discoveryActions } from …

feat(ui): add discovery model to store

---

ui/src/app/store/config/selectors.ts
ui/src/app/store/config/slice.ts
ui/src/app/store/config/types.ts
ui/src/testing/factories/config.ts

- Added correct return types for each config selector
- Check that intellisense correctly identifies the type of config items (e.g. in ReleaseForm.tsx, check that enableErase, quickErase and secureErase have a type of `boolean` instead of `string | number | boolean | null`
Fixes #2714

fix(ui): correctly type config values

---

ui/src/app/zones/views/Zones.tsx
ui/src/app/zones/views/ZonesList/ZonesList.tsx
ui/src/app/zones/views/ZonesList/index.ts
ui/src/app/zones/views/ZonesListHeader/ZonesListHeader.tsx
ui/src/app/zones/views/ZonesListHeader/index.ts
ui/src/app/zones/views/ZonesListTitle/ZonesListTitle.tsx
ui/src/app/zones/views/ZonesListTitle/index.ts

- Add ZonesListHeader component
- Run `yarn ui` and go to: http://0.0.0.0:8400/MAAS/r/zones
- Check the header and tooltip are visible

Add header component

---

ui/src/app/domains/views/DomainsList/DomainListHeader/DomainListHeader.test.tsx
ui/src/app/domains/views/DomainsList/DomainListHeader/DomainListHeader.tsx
ui/src/app/domains/views/DomainsList/DomainListHeader/index.ts
ui/src/app/domains/views/DomainsList/DomainsList.tsx

- Add the header to the DomainsList page
go to http://0.0.0.0:8400/MAAS/r/domains and check that the header is present and displays the number of domains
Fixes: https://github.com/canonical-web-and-design/app-squad/issues/37

Add domainList header component

---

ui/src/app/domains/views/DomainsList/DomainsList.test.tsx
ui/src/app/domains/views/DomainsList/DomainsList.tsx
ui/src/app/domains/views/DomainsList/DomainsTable/DomainsTable.tsx
ui/src/app/domains/views/DomainsList/DomainsTable/index.ts

- Adds a basic domains table component and renders it on domains listing page
- basic table of the domains should be rendered
Fixes: canonical-web-and-design/app-squad#35

Add basic table to domains listing

---

ui/src/app/Routes.tsx
ui/src/app/images/urls.ts
ui/src/app/images/views/ImageList/ImageList.test.tsx
ui/src/app/images/views/ImageList/ImageList.tsx
ui/src/app/images/views/ImageList/index.ts
ui/src/app/images/views/Images.tsx

- Add the components for the Images view and routes.
- Go to /MAAS/r/images.
- You should see the basic images component.
Fixes: canonical-web-and-design/app-squad#77.

feat(ui): add Images view and route components

---

ui/src/app/Routes.tsx
ui/src/app/dashboard/urls.ts
ui/src/app/dashboard/views/Dashboard.tsx

Changed the root dashboard route to `index` as it makes more sense
- Go to 
- Check that the page loads
Fixes https://github.com/canonical-web-and-design/app-squad/issues/110

Rename root dashboard route to index

---

ui/src/app/domains/views/DomainsList/DomainsTable/DomainsTable.test.tsx
ui/src/app/domains/views/DomainsList/DomainsTable/DomainsTable.tsx

- Add sorting to domains table
- run `yarn start`
- you should be able to sort the table
Fixes: canonical-web-and-design/app-squad#41

Add sorting to domains table

---

ui/src/__snapshots__/root-reducer.test.js.snap
ui/src/app/base/sagas/websockets.js
ui/src/app/base/sagas/websockets.test.js
ui/src/app/images/views/ImageList/ImageList.tsx
ui/src/app/store/bootresource/actions.test.ts
ui/src/app/store/bootresource/index.ts
ui/src/app/store/bootresource/reducers.test.ts
ui/src/app/store/bootresource/slice.ts
ui/src/app/store/bootresource/types/base.ts
ui/src/app/store/bootresource/types/enum.ts
ui/src/app/store/bootresource/types/index.ts
ui/src/app/store/bootresource/types/responses.ts
ui/src/app/store/root/types.ts
ui/src/app/store/utils/slice.ts
ui/src/root-reducer.js
ui/src/testing/factories/bootresource.ts
ui/src/testing/factories/index.ts
ui/src/testing/factories/state.ts

- Add the slice for the boot resource model.
- Go to the React images page.
- Open the redux state in the dev tools.
- You should see bootresources with loaded data. 
Fixes: canonical-web-and-design#issues/75.

feat(ui): add boot resources slice

---

ui/src/app/base/components/PowerTypeFields/PowerTypeFields.tsx
ui/src/app/base/types.ts
ui/src/app/kvm/components/KVMActionFormWrapper/RefreshForm/RefreshForm.tsx
ui/src/app/machines/components/ActionFormWrapper/FieldlessForm/FieldlessForm.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/ChangeStorageLayout/ChangeStorageLayout.tsx

- Added `AnyObject` and `EmptyObject` type aliases, since `Record<string, unknown>` kind of makes no sense at all.
- N/A

feat(ui): add type aliases for any and empty objects

---

ui/src/app/base/components/FormikForm/FormikForm.tsx
ui/src/app/base/components/FormikFormButtons/FormikFormButtons.tsx
ui/src/app/base/components/FormikFormButtons/index.ts
ui/src/app/base/components/FormikFormContent/FormikFormContent.tsx
ui/src/app/machines/views/AddChassis/AddChassisForm/AddChassisForm.js
ui/src/app/machines/views/AddMachine/AddMachineForm/AddMachineForm.js
ui/src/app/machines/views/MachineDetails/MachineConfiguration/MachineForm/MachineForm.tsx
ui/src/app/machines/views/MachineDetails/MachineConfiguration/PowerForm/PowerForm.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/AddAliasOrVlan/AddAliasOrVlan.tsx

- Updated `FormikForm`'s `secondarySubmit` prop to not always run `onSubmit`. It also includes formik context so you can use all of Formik's functions in `secondarySubmit` (including `submitForm`).
- Updated the `onCancel` prop to follow the same format, so now all the button functions have the shape `(values, formikContext) => {}`
- Driveby - added `className` prop to `FormikFormContent`
- [Building in a …

refactor(ui): update Formik secondarySubmit to not also run onSubmit

---

ui/src/app/images/views/ImageList/ImageList.tsx
ui/src/app/images/views/ImageList/ImageListHeader/ImageListHeader.test.tsx
ui/src/app/images/views/ImageList/ImageListHeader/ImageListHeader.tsx
ui/src/app/images/views/ImageList/ImageListHeader/index.ts
ui/src/app/store/bootresource/selectors.test.ts
ui/src/app/store/bootresource/selectors.ts

- Add the basic images header component and polling selector.
- Visit the React images page.
- You should see the basic header and the loading state (while loading).
Fixes: canonical-web-and-design/app-squad#78.

feat(ui): add the images header

---

ui/.betterer.results
ui/src/app/domains/views/DomainsList/DomainListHeader/DomainListHeader.tsx
ui/src/app/domains/views/DomainsList/DomainListHeaderForm/DomainListHeaderForm.test.tsx
ui/src/app/domains/views/DomainsList/DomainListHeaderForm/DomainListHeaderForm.tsx
ui/src/app/domains/views/DomainsList/DomainListHeaderForm/index.ts

- Add the collapsible form to the DNS header
- Add a domain and watch the number of domains go up :chart_with_upwards_trend: 
Fixes: https://github.com/canonical-web-and-design/app-squad/issues/38
We went for a simpler approach for the for layout 
@Caleb-Ellis said he would look at it as a part of his refactor and I'll update this component when it's done
Betterer is giving me a hard time :(

Add form to Domain header

---

ui/src/app/Routes.tsx
ui/src/app/domains/urls.ts
ui/src/app/domains/views/DomainDetails/DomainDetails.tsx
ui/src/app/domains/views/DomainDetails/index.ts
ui/src/app/domains/views/Domains.tsx
ui/src/app/domains/views/DomainsList/DomainsTable/DomainsTable.test.tsx
ui/src/app/domains/views/DomainsList/DomainsTable/DomainsTable.tsx

- Adds basic details view for domain
- Links from details table to domain details view
- `yarn start`
- go to http://0.0.0.0:8400/MAAS/r/domain/0
- name of 'maas' domain should be rendered in page header
- all domains in the table should have linked names
- clicking on names should open …

Domain details view

---

ui/src/app/utils/argPath.ts

- Add docs to the generated URL function so that it's easier to use.
- Open `ui/src/app/Routes.tsx`.
- Hover a URL function e.g. `machineURLs.machine.index` on line 71. You should see a tooltip with the function args.
Fixes: #2756.

docs(ui): document the url function

---

ui/.betterer.results
ui/src/app/domains/views/DomainsList/DomainsTable/DomainsTable.test.tsx
ui/src/app/domains/views/DomainsList/DomainsTable/DomainsTable.tsx
ui/src/app/store/domain/actions.test.ts
ui/src/app/store/domain/reducers.test.ts
ui/src/app/store/domain/slice.ts

1 - added `(default)` to the default domain name
2 - added the set default confirmation in an expandable row
3 - added the contextual menu to expand the row 
go to the table http://0.0.0.0:8400/MAAS/r/domains and switch around the default domain
Fixes: https://github.com/canonical-web-and-design/app-squad/issues/40
The background of the expanded row should be white (probably an artifact of yarn UI vs yarn start)
The alignment is a bit wonky there but we tried every "simple" solution and this was the best we could come up with without touching FormikForm component

Add "set default" action to the domain table

---

ui/src/app/base/components/Switch/Switch.tsx
ui/src/app/base/components/Switch/index.ts
ui/src/app/base/components/SwitchField/SwitchField.tsx
ui/src/app/images/views/ImageList/ImageList.test.tsx
ui/src/app/images/views/ImageList/ImageList.tsx
ui/src/app/images/views/ImageList/ImageListHeader/ImageListHeader.test.tsx
ui/src/app/images/views/ImageList/ImageListHeader/ImageListHeader.tsx
ui/src/app/store/config/selectors.test.ts
ui/src/app/store/config/selectors.ts
ui/src/app/utils/index.ts
ui/src/app/utils/unindentString.test.ts
ui/src/app/utils/unindentString.ts
ui/src/scss/_utilities.scss

- Added automatic sync toggle to images page
- Go to /MAAS/r/images
- Check that you can change the value of the automatic images sync toggle
- Check that when the toggle is off, a warning shows below
Fixes canonical-web-and-design/app-squad#79

feat(ui): add automatic sync toggle to images page

---

ui/.betterer.results
ui/src/app/base/components/TableConfirm/TableConfirm.test.tsx
ui/src/app/base/components/TableConfirm/TableConfirm.tsx
ui/src/app/base/components/TableConfirm/__snapshots__/TableConfirm.test.tsx.snap
ui/src/app/base/components/TableConfirm/index.ts
ui/src/app/base/components/TableDeleteConfirm/TableDeleteConfirm.test.tsx
ui/src/app/base/components/TableDeleteConfirm/TableDeleteConfirm.tsx
ui/src/app/base/components/TableDeleteConfirm/__snapshots__/TableDeleteConfirm.test.tsx.snap
ui/src/app/base/constants.ts
ui/src/app/domains/views/DomainsList/DomainsTable/DomainsTable.test.tsx
ui/src/app/domains/views/DomainsList/DomainsTable/DomainsTable.tsx
ui/src/app/pools/views/Pools.js
ui/src/app/pools/views/Pools.test.js
ui/src/app/preferences/views/SSHKeys/SSHKeyList/SSHKeyList.test.js
ui/src/app/preferences/views/SSLKeys/SSLKeyList/SSLKeyList.test.js
ui/src/app/settings/views/Dhcp/DhcpList/DhcpList.test.js
ui/src/app/settings/views/Repositories/RepositoriesList/RepositoriesList.test.js
ui/src/app/settings/views/Scripts/ScriptsList/ScriptsList.test.tsx
ui/src/app/settings/views/Users/UsersList/UsersList.test.js
ui/src/app/store/domain/reducers.test.ts
ui/src/app/store/domain/slice.ts
ui/src/app/store/domain/types/actions.ts
ui/src/app/store/domain/types/index.ts
ui/src/testing/factories/state.ts

- Add a new table confirm component. 
- Update the domain table to use the new component. 
- Domain improvements from review.
- Go to /r/domains.
- Check that the domain confirmation has a white background.
- Check that you can change the default domain.

feat(ui): add new table confirm component

---

ui/.betterer.results
ui/src/app/base/components/FormikFormContent/index.ts
ui/src/app/images/views/ImageList/ImageList.test.tsx
ui/src/app/images/views/ImageList/ImageList.tsx
ui/src/app/images/views/ImageList/UbuntuImages/CustomSourceForm/CustomSourceForm.test.tsx
ui/src/app/images/views/ImageList/UbuntuImages/CustomSourceForm/CustomSourceForm.tsx
ui/src/app/images/views/ImageList/UbuntuImages/CustomSourceForm/CustomSourceFormFields/CustomSourceFormFields.test.tsx
ui/src/app/images/views/ImageList/UbuntuImages/CustomSourceForm/CustomSourceFormFields/CustomSourceFormFields.tsx
ui/src/app/images/views/ImageList/UbuntuImages/CustomSourceForm/CustomSourceFormFields/index.ts
ui/src/app/images/views/ImageList/UbuntuImages/CustomSourceForm/index.ts
ui/src/app/images/views/ImageList/UbuntuImages/UbuntuImages.test.tsx
ui/src/app/images/views/ImageList/UbuntuImages/UbuntuImages.tsx
ui/src/app/images/views/ImageList/UbuntuImages/index.ts
ui/src/app/store/bootresource/actions.test.ts
ui/src/app/store/bootresource/selectors.test.ts
ui/src/app/store/bootresource/selectors.ts
ui/src/app/store/bootresource/slice.ts
ui/src/app/store/bootresource/types/actions.ts

- Added custom source form to images page
- Go to /MAAS/r/images and check that changing the source type radio to "Custom" shows the custom source form
- Enter a random url and submit the form - check that an error shows above the form
- Click "Show advanced" and enter some values, then click "Hide advanced" then "Show advanced" …

feat(ui): add custom source form to images page

---

ui/src/__snapshots__/root-reducer.test.js.snap
ui/src/app/domains/views/DomainDetails/DomainDetails.tsx
ui/src/app/store/domain/actions.test.ts
ui/src/app/store/domain/reducers.test.ts
ui/src/app/store/domain/slice.ts
ui/src/app/store/domain/types/base.ts
ui/src/testing/factories/state.ts
yarn.lock

- Add action/reducers to get domain details
- Add action/reducers to set domain as active
- Fix error handling reducers and test related to bug https://bugs.launchpad.net/maas/+bug/1931654
- Drive by: update yarn.lock
- `yarn start`
- open redux developer tools
- go to http://localhost:8400/MAAS/r/domain/3
- make sure domain …

Add domain details actions/reducers

---

ui/src/app/Routes.tsx
ui/src/app/intro/urls.ts
ui/src/app/intro/views/Intro.tsx
ui/src/app/intro/views/MaasIntro/MaasIntro.tsx
ui/src/app/intro/views/MaasIntro/index.ts
ui/src/app/intro/views/UserIntro/UserIntro.tsx
ui/src/app/intro/views/UserIntro/index.ts
ui/src/app/intro/views/index.ts
yarn.lock

- Added routes and placeholder components for the `/intro` and `/intro/user` pages
- Go to /MAAS/r/intro and check that the `MaasIntro` component renders
- Go to /MAAS/r/intro/user and check that the `UserIntro` component renders
Fixes canonical-web-and-design/app-squad#88

feat(ui): set up routes for intro pages

---

ui/src/app/images/components/UbuntuImageSelect/ArchSelect/ArchSelect.test.tsx
ui/src/app/images/components/UbuntuImageSelect/ArchSelect/ArchSelect.tsx
ui/src/app/images/components/UbuntuImageSelect/ArchSelect/index.ts
ui/src/app/images/components/UbuntuImageSelect/ReleaseSelect/ReleaseSelect.test.tsx
ui/src/app/images/components/UbuntuImageSelect/ReleaseSelect/ReleaseSelect.tsx
ui/src/app/images/components/UbuntuImageSelect/ReleaseSelect/index.ts
ui/src/app/images/components/UbuntuImageSelect/UbuntuImageSelect.test.tsx
ui/src/app/images/components/UbuntuImageSelect/UbuntuImageSelect.tsx
ui/src/app/images/components/UbuntuImageSelect/index.ts
ui/src/app/images/views/ImageList/UbuntuImages/DefaultSource/DefaultSource.test.tsx
ui/src/app/images/views/ImageList/UbuntuImages/DefaultSource/DefaultSource.tsx
ui/src/app/images/views/ImageList/UbuntuImages/DefaultSource/index.ts
ui/src/app/images/views/ImageList/UbuntuImages/UbuntuImages.test.tsx
ui/src/app/images/views/ImageList/UbuntuImages/UbuntuImages.tsx
ui/src/app/store/bootresource/selectors.test.ts
ui/src/app/store/bootresource/selectors.ts
ui/src/app/store/bootresource/types/actions.ts
ui/src/app/store/bootresource/types/index.ts
ui/src/app/store/bootresource/utils.test.ts
ui/src/app/store/bootresource/utils.ts
ui/src/app/utils/simpleSortByKey.test.ts
ui/src/app/utils/simpleSortByKey.ts

- Added image release/arch select form fields, though the form is not yet submittable.
- Created `UbuntuImageSelect` component which can hopefully be reused for the custom source images as well
- Go to /MAAS/r/images and check that a spinner shows while images are being fetched.
- Once fetched, check that the initial radio/arch …

feat(ui): add image release/arch select form fields

---

ui/src/app/base/components/NotificationGroup/Notification/Notification.tsx
ui/src/app/settings/views/Settings.test.tsx
ui/src/app/settings/views/Settings.tsx
ui/src/app/store/auth/selectors.test.ts
ui/src/app/store/auth/selectors.ts

- Added `authSelectors.isAdmin` selector for determining if the currently logged in user is an admin
- Converted `Settings.js` to TypeScript
- N/A, tests should pass
Fixes #2783

feat(ui): add selector for determining if user is an admin

---

shared/src/components/Header/Header.tsx
ui/src/app/zones/views/ZoneDetails/ZoneDetails.test.tsx
ui/src/app/zones/views/ZoneDetails/ZoneDetails.tsx
ui/src/app/zones/views/ZoneDetails/ZoneDetailsForm/ZoneDetailsForm.tsx
ui/src/app/zones/views/ZoneDetails/ZoneDetailsHeader/ZoneDetailsHeader.tsx
ui/src/app/zones/views/ZoneDetails/ZoneDetailsHeader/ZonesDetailsHeader.test.tsx
ui/src/app/zones/views/ZonesList/ZonesList.tsx
ui/src/app/zones/views/ZonesList/ZonesListForm/ZonesListForm.tsx

- Updated zones list and details pages with page titles
- Added check for default zone, to prevent it being deleted on details page
- Updated "AZs" link in top nav to point to react version, rather than legacy version
- Added `isAdmin` checks to the edit and delete zone actions on the details page 
- Check out this branch, visit http://0.0.0.0:8400/MAAS/r/zones
- Click "default" in the table, see that its details page doesn't show a "Delete AZ" button in the header
- Click "AZs" in the top nav, see that you are taken back to the table list at /r/zones, not /l/zones
- Click any of the other zones in the table, see that their details page _does_ have the "Delete AZ" button in the header
- For admin checks, see that the tests pass

Zone polish

---

ui/src/app/images/components/UbuntuImageSelect/ArchSelect/ArchSelect.test.tsx
ui/src/app/images/components/UbuntuImageSelect/ArchSelect/ArchSelect.tsx
ui/src/app/images/components/UbuntuImageSelect/ImagesTable/ImagesTable.test.tsx
ui/src/app/images/components/UbuntuImageSelect/ImagesTable/ImagesTable.tsx
ui/src/app/images/components/UbuntuImageSelect/ImagesTable/_index.scss
ui/src/app/images/components/UbuntuImageSelect/ImagesTable/index.ts
ui/src/app/images/components/UbuntuImageSelect/UbuntuImageSelect.test.tsx
ui/src/app/images/components/UbuntuImageSelect/UbuntuImageSelect.tsx
ui/src/app/images/types.ts
ui/src/app/images/views/ImageList/UbuntuImages/DefaultSource/DefaultSource.test.tsx
ui/src/app/images/views/ImageList/UbuntuImages/DefaultSource/DefaultSource.tsx
ui/src/scss/index.scss

- Built Ubuntu images table, that reflects the current selections in the release/arch form fields
- Changed the shape of the form data to be an array of shallow objects instead of following the shape that the `saveUbuntu` api expects. It's a million times easier to manage on the component side, and we can munge the data into the right shape at the end instead. …

feat(ui): build Ubuntu images table

---

ui/src/app/images/views/ImageList/ImageListHeader/ImageListHeader.test.tsx
ui/src/app/images/views/ImageList/ImageListHeader/ImageListHeader.tsx
ui/src/app/store/bootresource/selectors.test.ts
ui/src/app/store/bootresource/selectors.ts

- Add the rack and region image import statuses to the images header.
- I'm not sure if you can reliably QA this. You need the rack and region to be importing. I tried updating the images list and on one try it did start importing, but I'm not sure if I fluked that.
- If you can get the images to be importing you should see the status in the header
Fixes: …

feat(ui): rack and region import statuses

---

ui/src/app/base/sagas/websockets.test.ts
ui/src/app/base/sagas/websockets.ts

- Removed unnecessary getters and setters for websocket maps.
- Load the ui and make sure the machine list data can be loaded.

refactor(ui): removed unnecessary getters and setters

---

ui/.betterer.results
ui/src/app/base/components/FormikFormButtons/FormikFormButtons.tsx
ui/src/app/images/views/ImageList/UbuntuImages/DefaultSource/DefaultSource.test.tsx
ui/src/app/images/views/ImageList/UbuntuImages/DefaultSource/DefaultSource.tsx

- Added submit handler for the image selection form in order to save the selected Ubuntu images
- Added a secondary submit handler for when images are downloading and you want it to stop
- Go to /MAAS/r/images
- Check and uncheck some checkboxes (if using bolla, don't remove all the arches for 20.04 LTS which is the default …

feat(ui): make image selection form submittable

---

ui/src/app/images/components/UbuntuImageSelect/ArchSelect/ArchSelect.test.tsx
ui/src/app/images/components/UbuntuImageSelect/ArchSelect/ArchSelect.tsx
ui/src/app/images/components/UbuntuImageSelect/UbuntuImageSelect.test.tsx

- Disabled the last checked checkbox if the selected release is the default commissioning release
- Go to /MAAS/r/images and select the default commissioning release on the left
- Unselect checkboxes until there's one left
- Check that the last checkbox becomes disabled with a tooltip message
- Select a different release and …

feat(ui): prevent removing last image of default commissioning release

---

ui/.betterer.results
ui/src/app/domains/views/DomainDetails/DomainDetailsHeader/AddRecordDomainForm/AddRecordDomainForm.test.tsx
ui/src/app/domains/views/DomainDetails/DomainDetailsHeader/AddRecordDomainForm/AddRecordDomainForm.tsx
ui/src/app/domains/views/DomainDetails/DomainDetailsHeader/AddRecordDomainForm/index.ts
ui/src/app/domains/views/DomainDetails/DomainDetailsHeader/DomainDetailsHeader.tsx
ui/src/app/store/domain/actions.test.ts
ui/src/app/store/domain/slice.ts

- Added the form allowing you to add records to your domains in the domain header
Go to http://0.0.0.0:8400/MAAS/r/domain/36 and add some records! 
Go wild, see if you can add a SRV one (I couldn't figure out the rules)
Fixes: https://github.com/canonical-web-and-design/app-squad/issues/44

Add "Add record" form to details header

---

integration/cypress/integration/base/header.spec.ts

- Updated the Cypress header test to use the new zones url
- N/A - Cypress tests should pass

test(cypress): fix header test pointing to legacy zones url

---

ui/.betterer.results
ui/src/app/domains/views/DomainDetails/DomainSummary/DomainSummary.tsx
ui/src/app/domains/views/DomainDetails/DomainSummary/DomainsSummary.test.tsx
ui/src/app/domains/views/DomainsList/DomainListHeaderForm/DomainListHeaderForm.tsx

- Added domain summary form to domain details page
- `yarn start`
- click on any domain
- on details page click on "Edit" button next to domain summary
- edit fields, click cancel or save
- form should work as expected
Fixes: canonical-web-and-design/app-squad#47

Add domain summary form

---

ui/src/app/dashboard/views/DiscoveriesList/DiscoveriesList.test.tsx
ui/src/app/dashboard/views/DiscoveriesList/DiscoveriesList.tsx
ui/src/app/store/discovery/selectors.test.ts
ui/src/app/store/discovery/selectors.ts

- Updated the discovery search function to search multiple values
- Added test for search function
- Visit http://192.168.0.3:8400/MAAS/r/dashboard
- Search "28", see that the table updates with 3 results, all last seen on the 28th of September
- Search other terms, see that you get relevant results

Add discoveries search bar

---

ui/src/app/domains/views/DomainDetails/DomainDetails.tsx
ui/src/app/domains/views/DomainDetails/DomainNotFoundHeader/DomainNotFoundHeader.test.tsx
ui/src/app/domains/views/DomainDetails/DomainNotFoundHeader/DomainNotFoundHeader.tsx
ui/src/app/domains/views/DomainDetails/DomainNotFoundHeader/index.ts
ui/src/app/domains/views/DomainDetails/DomainsDetails.test.tsx

- Add domain not found header to the domain detail page if the domain doesn't exist
go to http://0.0.0.0:8400/MAAS/r/domain/123456789
check that it's showing the correct header
Legacy : 
New and improved :sparkles:

Add domain not found header

---

ui/src/app/domains/views/DomainDetails/DomainDetails.tsx
ui/src/app/domains/views/DomainDetails/DomainDetailsHeader/AddRecordDomainForm/AddRecordDomainForm.test.tsx
ui/src/app/domains/views/DomainDetails/DomainDetailsHeader/AddRecordDomainForm/AddRecordDomainForm.tsx
ui/src/app/domains/views/DomainDetails/DomainDetailsHeader/AddRecordDomainForm/AddRecordFields/AddRecordFields.tsx
ui/src/app/domains/views/DomainDetails/DomainDetailsHeader/AddRecordDomainForm/AddRecordFields/index.ts
ui/src/app/domains/views/DomainDetails/DomainDetailsHeader/DeleteDomainForm/DeleteDomainForm.test.tsx
ui/src/app/domains/views/DomainDetails/DomainDetailsHeader/DeleteDomainForm/DeleteDomainForm.tsx
ui/src/app/domains/views/DomainDetails/DomainDetailsHeader/DomainDetailsHeader.test.tsx
ui/src/app/domains/views/DomainDetails/DomainDetailsHeader/DomainDetailsHeader.tsx
ui/src/app/domains/views/DomainDetails/DomainNotFoundHeader/DomainNotFoundHeader.test.tsx
ui/src/app/domains/views/DomainDetails/DomainNotFoundHeader/DomainNotFoundHeader.tsx
ui/src/app/store/domain/actions.test.ts
ui/src/app/store/domain/slice.ts
ui/src/app/store/domain/types/actions.ts
ui/src/app/store/domain/types/index.ts

- Updated Domain components to use an `id` prop instead of parsing it from the url in each component. This will make it easier if, for example, we want to render a component somewhere other than `/domain/{id}`.
- Separated `createRecord` action into two separate actions `createAddressRecord` and `createDNSData` (and typed params) to closer match the websocket api.
- Fixed a bug where TTL would not save for A and AAAA records.
- Added some help text for each record type.
- Go to /MAAS/r/domains and click "Add record"
- Check that you can successfully add each record type with TTL saved
- Check that you can still delete a domain that has no records

Add record updates

---

ui/src/app/base/sagas/websockets.test.ts
ui/src/app/base/sagas/websockets.ts
ui/src/app/images/views/ImageList/ImageList.test.tsx
ui/src/app/images/views/ImageList/ImageList.tsx
ui/src/app/images/views/ImageList/ImageListHeader/ImageListHeader.tsx
ui/src/app/store/bootresource/actions.test.ts
ui/src/app/store/bootresource/reducers.test.ts
ui/src/app/store/bootresource/slice.ts
ui/src/websocket-client.ts

- Add the ability to poll an action using the websocket.
- Visit /r/images and open the redux tools to see the dispatches.
- You should see some start polling actions.
- Wait 10 seconds and you should see the next poll happen.
- Click on Settings in the header and you should see the stop polling actions.
- Wait 10 seconds and …

feat(ui): add websocket polling

---

ui/src/app/base/hooks.test.ts
ui/src/app/base/hooks.ts
ui/src/app/images/views/ImageList/ImageListHeader/ImageListHeader.tsx

- Only show the polling state in the images header on the first load.
- Go to /r/images.
- You should see the loading state in the header.
- Wait 10 seconds and the poll will happen again, but you should not see it in the header.

feat(ui): only show the polling state on the first load

---

ui/src/app/dashboard/views/DiscoveriesList/DiscoveriesList.test.tsx
ui/src/app/dashboard/views/DiscoveriesList/DiscoveriesList.tsx
ui/src/app/dashboard/views/DiscoveriesList/_index.scss
ui/src/scss/index.scss

- Add CSS to make the discovery table responsive.
- Cleanup discovery table and test.
- View the dashboard.
- Resize your window, check that the columns look OK at each size.
Fixes: canonical-web-and-design/app-squad#127.

feat(ui): clean up and make discovery table responsive

---

ui/src/app/dashboard/views/DiscoveriesList/DiscoveriesList.test.tsx
ui/src/app/dashboard/views/DiscoveriesList/DiscoveriesList.tsx

- Add an action menu to the discovery rows.
- Visit /r/dashboard.
- You should see a spinner while the discoveries are loading.
- There should be an action menu for each row which shows the actions.
Fixes: canonical-web-and-design/app-squad#129.

feat(ui): add a discovery row menu

---

ui/src/app/dashboard/views/DashboardHeader/DashboardHeader.test.tsx
ui/src/app/dashboard/views/DashboardHeader/DashboardHeader.tsx

- Add the discovery count to the dashboard tab.
- Check that the number of discoveries is shown in the discovery tab in the dashboard header.
Fixes: canonical-web-and-design/app-squad#131.

feat(ui): show discovery count

---

ui/src/app/dashboard/views/DiscoveriesList/DiscoveriesList.test.tsx
ui/src/app/dashboard/views/DiscoveriesList/DiscoveriesList.tsx

- Add the action to delete a discovery.
- Open the action menu and click delete and then confirm.
- The discovery should get deleted.
Fixes: canonical-web-and-design/app-squad#70.

feat(ui): delete discovery

---

ui/.betterer.results
ui/src/app/dashboard/views/DashboardConfigurationForm/DashboardConfigurationSubnetForm/DashboardConfigurationSubnetForm.test.tsx
ui/src/app/dashboard/views/DashboardConfigurationForm/DashboardConfigurationSubnetForm/DashboardConfigurationSubnetForm.tsx
ui/src/app/settings/views/Network/NetworkDiscoveryForm/NetworkDiscoveryForm.test.tsx
ui/src/app/settings/views/Network/NetworkDiscoveryForm/NetworkDiscoveryForm.tsx
ui/src/app/settings/views/Network/NetworkDiscoveryForm/NetworkDiscoveryFormFields/NetworkDiscoveryFormFields.test.tsx
ui/src/app/settings/views/Network/NetworkDiscoveryForm/NetworkDiscoveryFormFields/NetworkDiscoveryFormFields.tsx
ui/src/app/settings/views/Network/NetworkDiscoveryForm/NetworkDiscoveryFormFields/index.ts
ui/src/app/settings/views/Network/NetworkDiscoveryForm/types.ts
ui/src/app/store/config/selectors.ts
ui/src/app/store/config/types/enum.ts
ui/src/app/store/config/types/index.ts

- Update the dashboard config forms to be disabled when network discovery is disabled.
- Added an enum for the network discovery states.
- Migrated the config form to typescript.
- Go to /r/dashboard and click on the config tab.
- Disable network discovery and save.
- The interval time and subnet form should be disabled.
Fixes: …

feat(ui): disable forms when network discovery is off

---

ui/src/app/dashboard/views/Dashboard.test.tsx
ui/src/app/dashboard/views/Dashboard.tsx

- Show a notification when discovery is disabled.
- Go to the config tab and disable discovery and save.
- You should see a warning on both tabs.
Fixes: canonical-web-and-design/app-squad#128.

feat(ui): disabled discovery warning

---

ui/src/app/kvm/views/KVMDetails/KVMDetails.test.tsx
ui/src/app/kvm/views/KVMDetails/KVMDetailsHeader/KVMDetailsHeader.test.tsx
ui/src/app/kvm/views/KVMDetails/KVMDetailsHeader/KVMDetailsHeader.tsx
ui/src/app/kvm/views/KVMDetails/StorageResources/StorageResources.tsx
ui/src/app/kvm/views/KVMList/LxdTable/LxdTable.tsx
ui/src/app/kvm/views/KVMList/StorageColumn/StorageColumn.test.tsx
ui/src/app/kvm/views/KVMList/StorageColumn/StorageColumn.tsx
ui/src/app/kvm/views/KVMList/VMsColumn/VMsColumn.test.tsx
ui/src/app/kvm/views/KVMList/VMsColumn/VMsColumn.tsx
ui/src/app/kvm/views/KVMList/VirshTable/VirshTable.test.tsx
ui/src/app/kvm/views/KVMList/VirshTable/VirshTable.tsx
ui/src/app/kvm/views/KVMList/VirshTable/_index.scss
ui/src/app/store/pod/types.ts
ui/src/testing/factories/index.ts
ui/src/testing/factories/nodes.ts

feat(ui): replace legacy pod websocket fields with 'resources' equivalents (backport 3.0)

---

legacy/src/app/controllers/nodes_list.js
legacy/src/app/controllers/tests/test_nodes_list.js
legacy/src/app/partials/nodes-list.html
legacy/src/scss/tables/_patterns_table-controllers.scss
ui/src/app/store/controller/types.ts

Backport: https://github.com/canonical-web-and-design/maas-ui/pull/2616
QA:
- Point your UI to Bolla.
- Visit the controllers page.
- In the status column there should be an (i) icon. Hovering it should show the error.
- In the upgrade column it should read "Up-to-date".

feat(legacy): display snap upgrade errors

---

ui/src/app/base/components/FormikFormButtons/FormikFormButtons.test.tsx
ui/src/app/base/components/FormikFormButtons/FormikFormButtons.tsx
ui/src/app/base/components/FormikFormContent/FormikFormContent.test.tsx
ui/src/app/base/components/FormikFormContent/FormikFormContent.tsx
ui/src/app/images/views/ImageList/UbuntuImages/CustomSource/CustomSourceConnect/CustomSourceConnect.test.tsx
ui/src/app/machines/components/ActionFormWrapper/FieldlessForm/__snapshots__/FieldlessForm.test.tsx.snap

- Update the formik form to not call onSuccess on the first render.
- Allow submit label to be generated with a function.
- Go to /r/domains.
- Click on a domain.
- Add a record.
- When the record is created the form should close.
Fixes: canonical-web-and-design/app-squad/issues/138.

feat(ui): don't call form onSuccess on first render

---

ui/.betterer.results
ui/src/app/dashboard/views/DiscoveriesList/DiscoveriesList.tsx
ui/src/app/dashboard/views/DiscoveryAddForm/DiscoveryAddForm.test.tsx
ui/src/app/dashboard/views/DiscoveryAddForm/DiscoveryAddForm.tsx
ui/src/app/dashboard/views/DiscoveryAddForm/DiscoveryAddFormFields/DiscoveryAddFormFields.test.tsx
ui/src/app/dashboard/views/DiscoveryAddForm/DiscoveryAddFormFields/DiscoveryAddFormFields.tsx
ui/src/app/dashboard/views/DiscoveryAddForm/DiscoveryAddFormFields/index.ts
ui/src/app/dashboard/views/DiscoveryAddForm/index.ts
ui/src/app/dashboard/views/DiscoveryAddForm/types.ts
ui/src/app/store/subnet/selectors.ts
ui/src/app/utils/preparePayload.ts
ui/src/scss/_utilities.scss

- Add discovery form for creating devices/interfaces.
- Visit /r/dashboard.
- Open the action menu for a discovery and click "Add discovery".
- Try adding a device (don't choose a parent, this doesn't currently work: https://bugs.launchpad.net/maas/+bug/1933408).
- Repeat the process, but this time create an interface.
Fixes: …

feat(ui): add discovery form

---

ui/src/app/base/components/TableActions/TableActions.js
ui/src/app/base/components/TableConfirm/TableConfirm.test.tsx
ui/src/app/base/components/TableConfirm/TableConfirm.tsx
ui/src/app/base/components/TableConfirm/__snapshots__/TableConfirm.test.tsx.snap
ui/src/app/base/components/TableDeleteConfirm/TableDeleteConfirm.tsx
ui/src/app/images/components/ImagesTable/DeleteImageConfirm/DeleteImageConfirm.test.tsx
ui/src/app/images/components/ImagesTable/DeleteImageConfirm/DeleteImageConfirm.tsx
ui/src/app/images/components/ImagesTable/DeleteImageConfirm/index.ts
ui/src/app/images/components/ImagesTable/ImagesTable.test.tsx
ui/src/app/images/components/ImagesTable/ImagesTable.tsx
ui/src/app/images/components/ImagesTable/_index.scss
ui/src/app/images/views/ImageList/OtherImages/OtherImagesSelect/OtherImagesSelect.test.tsx
ui/src/app/images/views/ImageList/OtherImages/OtherImagesSelect/OtherImagesSelect.tsx

- Added delete action for images
- Updated bootresource action reducers to handle success responses (which are identical to the poll success response)
- Go to /MAAS/r/images
- Check that images that have already been downloaded or are in the process of being downloaded (i.e. they exist in `bootresource.resources`) have a bin …

feat(ui): add delete action to images table

---

ui/src/app/store/event/reducers.test.ts
ui/src/app/store/event/slice.ts

- Append new events to the store instead of overwriting them when a new batch is fetched.
- Go to the logs tab for a machine.
- Change the number of events per page to 200.
- Click the arrow to the next page.
- The new events should get loaded and when they do you should be able to go back or forwards.
Fixes: #2824.

fix(ui): don't overwrite events when fetching

---

ui/src/app/machines/views/MachineDetails/NodeDevices/NodeDevices.tsx
ui/src/app/machines/views/MachineDetails/NodeDevices/_index.scss

- Moved "Product ID" into "Product" column in PCI/USB tables
- Go to the PCI or USB tab of a machine's details page and check that there is a double row column for Product and Product ID
Fixes #2765

feat(ui): convert PCI table product columns to a double row

---

ui/src/app/images/views/ImageList/GeneratedImages/GeneratedImages.test.tsx
ui/src/app/images/views/ImageList/GeneratedImages/GeneratedImages.tsx
ui/src/app/images/views/ImageList/GeneratedImages/index.ts
ui/src/app/images/views/ImageList/ImageList.tsx

- Added Genereted images table to images page. Generated images were deprecated in MAAS 2.2 but they might still exist for some MAASes. In the legacy code they are handled identically to Custom images, so I've basically just copy+pasted those components and reused here with a different selector.
- We can "simulate" there being …

feat(ui): build generated images table

---

ui/src/app/base/components/FilterAccordion/FilterAccordion.test.tsx
ui/src/app/base/components/FilterAccordion/FilterAccordion.tsx
ui/src/app/machines/views/MachineList/MachineListControls/MachinesFilterAccordion/MachinesFilterAccordion.tsx
ui/src/app/utils/search/filter-handlers.test.ts
ui/src/app/utils/search/filter-handlers.ts
ui/src/app/utils/search/filter-items.ts

- Update the FilterAccordion component to work with models other than machines.
- Connect your UI to Bolla.
- Open the machine list.
- Open the filter accordion and click on a workload.
- The list should get filtered (there should be one machine with workload annotations).
Fixes: canonical-web-and-design/app-squad#135.

feat(ui): update FilterAccordion to work with any model

---

ui/src/app/dashboard/views/DiscoveriesList/DiscoveriesFilterAccordion/DiscoveriesFilterAccordion.test.tsx
ui/src/app/dashboard/views/DiscoveriesList/DiscoveriesFilterAccordion/DiscoveriesFilterAccordion.tsx
ui/src/app/dashboard/views/DiscoveriesList/DiscoveriesFilterAccordion/index.ts
ui/src/app/dashboard/views/DiscoveriesList/DiscoveriesList.tsx
ui/src/app/store/discovery/selectors.test.ts
ui/src/app/store/discovery/selectors.ts
ui/src/app/store/discovery/utils/index.ts
ui/src/app/store/discovery/utils/search.test.ts
ui/src/app/store/discovery/utils/search.ts
ui/src/app/utils/search/filter-items.ts

- Add a dropdown to filter discoveries on the dashboard.
- Visit /r/dashboard.
- Use the filter dropdown to change some filters.
- You should see the filters appear in the search box and the list should update.
Fixes: canonical-web-and-design/app-squad#68.

feat(ui): add discovery filtering

---

ui/src/app/dashboard/views/Dashboard.test.tsx
ui/src/app/dashboard/views/Dashboard.tsx

- Limit the dashboard to admins only.
- Visit /r/dashboard as an admin. It should load as normal.
- Visit /r/dashboard as a non admin. It should show a message.
Fixes: canonical-web-and-design/app-squad#147.

feat(ui): admin only dashboard

---

ui/.betterer.results
ui/src/app/images/components/UbuntuImageSelect/ArchSelect/ArchSelect.tsx
ui/src/app/images/components/UbuntuImageSelect/ReleaseSelect/ReleaseSelect.tsx
ui/src/app/images/components/UbuntuImageSelect/UbuntuImageSelect.test.tsx
ui/src/app/images/components/UbuntuImageSelect/UbuntuImageSelect.tsx
ui/src/app/images/views/ImageList/SyncedImages/ChangeSource/ChangeSource.tsx
ui/src/app/images/views/ImageList/SyncedImages/ChangeSource/FetchImagesForm/FetchImagesForm.test.tsx
ui/src/app/images/views/ImageList/SyncedImages/ChangeSource/FetchImagesForm/FetchImagesForm.tsx
ui/src/app/images/views/ImageList/SyncedImages/ChangeSource/FetchedImages/FetchedImages.test.tsx
ui/src/app/images/views/ImageList/SyncedImages/ChangeSource/FetchedImages/FetchedImages.tsx
ui/src/app/images/views/ImageList/SyncedImages/SyncedImages.test.tsx
ui/src/app/images/views/ImageList/SyncedImages/SyncedImages.tsx
ui/src/app/images/views/ImageList/SyncedImages/UbuntuImages/UbuntuImages.test.tsx
ui/src/app/images/views/ImageList/SyncedImages/UbuntuImages/UbuntuImages.tsx
ui/src/app/store/bootresource/types/actions.ts
ui/src/app/store/bootresource/types/index.ts

- Built FetchedImages table which is used to sync images with a different source
- Go to /MAAS/r/images and click "Change source"
- Use a source type that's different to the current selection and click "Connect"
- Check that an image selection table shows
- Select an image and click "Update selection"
- It might take a while but …

feat(ui) build fetched images table

---

ui/.betterer.results
ui/src/app/images/components/ImagesTable/ImagesTable.tsx
ui/src/app/images/components/NonUbuntuImageSelect/NonUbuntuImageSelect.test.tsx
ui/src/app/images/components/NonUbuntuImageSelect/NonUbuntuImageSelect.tsx
ui/src/app/images/components/NonUbuntuImageSelect/index.ts
ui/src/app/images/views/ImageList/SyncedImages/OtherImages/OtherImagesSelect/index.ts
ui/src/app/images/views/ImageList/SyncedImages/SyncedImages.tsx
ui/src/app/images/views/ImageList/SyncedImages/UbuntuCoreImages/UbuntuCoreImages.test.tsx
ui/src/app/images/views/ImageList/SyncedImages/UbuntuCoreImages/UbuntuCoreImages.tsx
ui/src/app/images/views/ImageList/SyncedImages/UbuntuCoreImages/index.ts

- Made `OtherImagesSelect` work with both Other images and Ubuntu Core images
- Built UbuntuCoreImages component
- We need to fake Ubuntu Core images being available from the configured source. Open `app/store/bootresource/selectors.ts` and make the following edits:
- On line 12:
``` typescript
import { …
```

feat(ui): build ubuntu core images table

---

ui/src/app/base/components/TableActions/TableActions.test.tsx
ui/src/app/base/components/TableActions/TableActions.tsx
ui/src/app/images/components/ImagesTable/ImagesTable.test.tsx
ui/src/app/images/components/ImagesTable/ImagesTable.tsx
ui/src/app/images/components/ImagesTable/_index.scss
ui/src/app/images/components/NonUbuntuImageSelect/NonUbuntuImageSelect.tsx
ui/src/app/images/components/UbuntuImageSelect/UbuntuImageSelect.tsx
ui/src/app/images/views/ImageList/SyncedImages/ChangeSource/FetchedImages/FetchedImages.test.tsx
ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/StorageTable/StorageTable.tsx
ui/src/app/settings/views/Scripts/ScriptsList/ScriptsList.tsx

- Added a "clear" button to the images table so you don't need to select the correct release
- Updated the css so that the architecture column never gets hidden
- Converted TableActions to TypeScript
- Go to /MAAS/r/images and select some new Ubuntu images
- Check that you can clear those selections from the table
- Resize the …

fix(ui): keep arch column and allow clearing selection in images table

---

ui/src/app/images/components/ImagesTable/DeleteImageConfirm/DeleteImageConfirm.tsx
ui/src/app/images/views/ImageList/ImageList.tsx
ui/src/app/images/views/ImageList/SyncedImages/ChangeSource/FetchedImages/FetchedImages.tsx
ui/src/app/images/views/ImageList/SyncedImages/OtherImages/OtherImages.tsx
ui/src/app/images/views/ImageList/SyncedImages/UbuntuCoreImages/UbuntuCoreImages.tsx
ui/src/app/images/views/ImageList/SyncedImages/UbuntuImages/UbuntuImages.tsx
ui/src/app/store/bootresource/actions.test.ts
ui/src/app/store/bootresource/slice.ts

- Updated bootresource `poll` action to be able to only poll once
- Dispatch on-off poll action after image action success (i.e. save synced images, delete image)
- Go to /MAAS/r/images and open Redux devtools
- Perform an action like deleting an image or saving a sync selection
- Check that once the `actionSuccess` action is …

fix(ui): explicitly poll server after image action success

---

ui/src/app/base/components/DynamicSelect/DynamicSelect.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/AddBondForm/AddBondForm.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/AddBondForm/AddBondForm.tsx

- Fix selecting the correct VLAN when adding a bond.
- Open the network tab for a machine (at the time of writing 'top owl' on Bolla is set up correctly)
- If not using 'top owl' then create two interfaces with the same VLAN, but make sure that the VLAN isn't the default (i.e. choose a fabric that has - multiple VLANs and choose a VLAN that is not the first …

fix(ui): select correct VLAN when creating a bond

---

ui/src/app/intro/views/UserIntro/UserIntro.test.tsx
ui/src/app/intro/views/UserIntro/UserIntro.tsx

- Set up the form for the user intro.
- Log in as a non admin.
- Visit /MAAS/r/intro/user
- You should see a SSH key card and a continue button.
- Log in as an admin.
- You should see the SSH key and successfully set up card and the continue button.
- In another tab add some SSH keys in your profile.
- In the intro the continue button should now be enabled.
- …

feat(ui): add basic user intro form

---

ui/.betterer.results
ui/src/app/intro/views/MaasIntro/ConnectivityCard/ConnectivityCard.test.tsx
ui/src/app/intro/views/MaasIntro/ConnectivityCard/ConnectivityCard.tsx
ui/src/app/intro/views/MaasIntro/ConnectivityCard/index.ts
ui/src/app/intro/views/MaasIntro/MaasIntro.test.tsx
ui/src/app/intro/views/MaasIntro/MaasIntro.tsx
ui/src/app/intro/views/MaasIntro/MaasIntroFields/index.ts
ui/src/app/intro/views/MaasIntro/NameCard/NameCard.test.tsx
ui/src/app/intro/views/MaasIntro/NameCard/NameCard.tsx
ui/src/app/intro/views/MaasIntro/NameCard/index.ts
ui/src/app/intro/views/MaasIntro/types.ts
ui/src/app/store/packagerepository/selectors.test.ts
ui/src/app/store/packagerepository/selectors.ts

- Added the connectivity card to the MAAS intro form
- Go to /MAAS/r/intro and check that there is a connectivity card
- Remove the Ubuntu archive URL and check that an error icon shows in the card title
- Reenter the URL and check that you can successfully submit the form
Fixes canonical-web-and-design/app-squad#90

feat(ui): add connectivity card to MAAS intro form

---

ui/src/app/images/components/ImagesTable/ImagesTable.test.tsx
ui/src/app/images/components/ImagesTable/ImagesTable.tsx
ui/src/app/images/views/ImageList/SyncedImages/ChangeSource/ChangeSource.tsx
ui/src/app/images/views/ImageList/SyncedImages/ChangeSource/FetchImagesForm/FetchImagesForm.tsx
ui/src/app/images/views/ImageList/SyncedImages/SyncedImages.test.tsx
ui/src/app/images/views/ImageList/SyncedImages/SyncedImages.tsx
ui/src/app/intro/urls.ts
ui/src/app/intro/views/ImagesIntro/ImagesIntro.test.tsx
ui/src/app/intro/views/ImagesIntro/ImagesIntro.tsx
ui/src/app/intro/views/ImagesIntro/index.ts
ui/src/app/intro/views/Intro.tsx
ui/src/app/intro/views/MaasIntro/MaasIntro.tsx

- Added images section to intro flow
- Driveby fix to prevent clear the last commissioning image in the table
- Start a new `make start` MAAS or `make clean+db` an existing one to get the DB free of image data
- Go to /MAAS/r/intro/images and check that the continue button is disabled
- Fetch images from a source and check that …

feat(ui): add images section to intro flow

---

ui/src/app/intro/urls.ts
ui/src/app/intro/views/ImagesIntro/ImagesIntro.tsx
ui/src/app/intro/views/Intro.tsx
ui/src/app/intro/views/MaasIntro/ConnectivityCard/ConnectivityCard.tsx
ui/src/app/intro/views/MaasIntro/NameCard/NameCard.tsx
ui/src/app/intro/views/MaasIntroSuccess/MaasIntroSuccess.test.tsx
ui/src/app/intro/views/MaasIntroSuccess/MaasIntroSuccess.tsx
ui/src/app/intro/views/MaasIntroSuccess/index.ts
ui/src/app/intro/views/UserIntro/UserIntro.tsx

- Added a success page to the MAAS intro flow, which redirects to either the user intro, dashboard or machine list depending on the auth user status
- Go to /MAAS/r/intro/success and check that a successful set up card shows up
- Check that you can navigate back to the images page and from the images page navigate to the success …

feat(ui): add success page to MAAS intro flow

---

ui/.betterer.results
ui/src/app/base/components/SSHKeyForm/SSHKeyForm.test.tsx
ui/src/app/base/components/SSHKeyForm/SSHKeyForm.tsx
ui/src/app/base/components/SSHKeyForm/SSHKeyFormFields/SSHKeyFormFields.tsx
ui/src/app/base/components/SSHKeyList/SSHKeyList.test.tsx
ui/src/app/base/components/SSHKeyList/SSHKeyList.tsx
ui/src/app/intro/views/UserIntro/UserIntro.test.tsx
ui/src/app/intro/views/UserIntro/UserIntro.tsx
ui/src/app/preferences/views/SSHKeys/AddSSHKey/AddSSHKey.tsx

- Add the ssh key form and table to the user intro.
- Go to /MAAS/r/account/prefs/ssh-keys and remove any keys you have.
- Visit /MAAS/r/intro/user.
- You should see the SSH key form.
- Add an SSH key.
- The SSH key table should appear and the continue button should become enabled.
- You should be able to remove SSH keys from the SSH table.
Fixes: …

feat(ui): add ssh key form to user intro

---

shared/src/components/Header/Header.test.tsx
shared/src/components/Header/Header.tsx
ui/src/app/App.tsx
ui/src/app/base/components/TableConfirm/TableConfirm.tsx
ui/src/app/intro/views/MaasIntro/MaasIntro.test.tsx
ui/src/app/intro/views/MaasIntro/MaasIntro.tsx

- Added a skip button + confirmation to the initial MAAS intro page
- Removed skip and user preferences links from header in react app
- Go to /MAAS/r/intro and check that you can skip straight to the user intro
Fixes canonical-web-and-design/app-squad#120

feat(ui): add ability to skip initial MAAS setup

---

ui/src/app/base/components/TableConfirm/TableConfirm.tsx
ui/src/app/intro/views/MaasIntro/MaasIntro.tsx
ui/src/app/intro/views/UserIntro/UserIntro.test.tsx
ui/src/app/intro/views/UserIntro/UserIntro.tsx

- Add a skip button and confirmation to the user intro.
- Update the main intro to now show the user intro if it has already been completed.
- Create a new user.
- Visit /MAAS/r/intro/user.
- Click "Skip user setup" and you should see a confirmation.
- Confirm and the intro should close.
Fixes: canonical-web-and-design/app-squad#167.

feat(ui): add user intro skip

---

ui/src/app/intro/views/IncompleteCard/IncompleteCard.test.tsx
ui/src/app/intro/views/IncompleteCard/IncompleteCard.tsx
ui/src/app/intro/views/IncompleteCard/__snapshots__/IncompleteCard.test.tsx.snap
ui/src/app/intro/views/IncompleteCard/index.ts
ui/src/app/intro/views/Intro.test.tsx
ui/src/app/intro/views/Intro.tsx
ui/src/app/intro/views/MaasIntro/MaasIntro.test.tsx

- Display a message if the user logs in before the intro is complete.
- Create a non-admin and log in.
- Visit /MAAS/r/intro
- You should see a message instead of the intro.
- Log in as an admin and visit /MAAS/r/intro
- You should see the intro as normal.
Fixes: canonical-web-and-design/app-squad#158.

feat(ui): display non-admin intro message

---

ui/src/app/base/components/Section/Section.tsx
ui/src/app/images/views/ImageList/SyncedImages/ChangeSource/ChangeSource.tsx
ui/src/app/images/views/ImageList/SyncedImages/SyncedImages.test.tsx
ui/src/app/images/views/ImageList/SyncedImages/SyncedImages.tsx
ui/src/app/intro/components/IntroCard/IntroCard.test.tsx
ui/src/app/intro/components/IntroCard/IntroCard.tsx
ui/src/app/intro/components/IntroCard/index.ts
ui/src/app/intro/components/IntroSection/IntroSection.test.tsx
ui/src/app/intro/components/IntroSection/IntroSection.tsx
ui/src/app/intro/components/IntroSection/index.ts
ui/src/app/intro/hooks.test.tsx
ui/src/app/intro/hooks.ts
ui/src/app/intro/views/ImagesIntro/ImagesIntro.tsx
ui/src/app/intro/views/IncompleteCard/IncompleteCard.test.tsx
ui/src/app/intro/views/IncompleteCard/IncompleteCard.tsx
ui/src/app/intro/views/IncompleteCard/__snapshots__/IncompleteCard.test.tsx.snap
ui/src/app/intro/views/MaasIntro/ConnectivityCard/ConnectivityCard.tsx
ui/src/app/intro/views/MaasIntro/MaasIntro.tsx
ui/src/app/intro/views/MaasIntro/NameCard/NameCard.tsx
ui/src/app/intro/views/MaasIntroSuccess/MaasIntroSuccess.tsx
ui/src/app/intro/views/UserIntro/UserIntro.test.tsx
ui/src/app/intro/views/UserIntro/UserIntro.tsx

- Create components to capture shared display and behaviour of intro screens.
- Create a new user and visit the user intro.
- The intro should appear unchanged.
Fixes: canonical-web-and-design/app-squad#165.

feat(ui): create reusable intro components

---

ui/.betterer.results
ui/src/app/images/views/ImageList/SyncedImages/OtherImages/OtherImages.tsx
ui/src/app/images/views/ImageList/SyncedImages/SyncedImages.tsx
ui/src/app/intro/views/ImagesIntro/ImagesIntro.tsx
ui/src/app/intro/views/Intro.test.tsx
ui/src/app/intro/views/Intro.tsx

- Add redirects to the correct part of the intro or exit.
- Fix spacing after images form.
- Create a new admin user and rest the main intro: `maas $PROFILE maas set-config name=completed_intro value=false`.
- Visit /MAAS/r/intro/user and you should end up /MAAS/r/intro.
- Click the skip button and confirm.
- Visit /MAAS/r/intro …

feat(ui): add intro redirects

---

ui/.betterer.results
ui/src/app/base/components/ActionForm/ActionForm.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsActionBar/VMsActionBar.tsx
ui/src/app/machines/components/ActionFormWrapper/ActionFormWrapper.tsx
ui/src/app/machines/components/TakeActionMenu/TakeActionMenu.test.tsx
ui/src/app/machines/components/TakeActionMenu/TakeActionMenu.tsx
ui/src/app/machines/views/MachineList/MachineListHeader/MachineListHeader.test.tsx
ui/src/app/machines/views/types.ts

- Rewrote `TakeActionMenu` to not rely on the API for the display, which will be required for the clone form that works inverse to the api
- Check that the take action menu still works as before:
- Action links are grouped and ordered the same
- Counts are correct
- Trying to perform an action that not all selected machines can …

Decouple machine take action menu from API

---

ui/src/app/base/components/ActionForm/ActionForm.tsx
ui/src/app/machines/components/ActionFormWrapper/ActionFormWrapper.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneForm.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/CloneFormFields.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/index.ts
ui/src/app/machines/components/ActionFormWrapper/CloneForm/index.ts
ui/src/app/machines/components/TakeActionMenu/TakeActionMenu.tsx
ui/src/app/machines/utils.test.ts
ui/src/app/machines/utils.ts
ui/src/app/store/machine/index.ts
ui/src/app/store/machine/selectors.ts
ui/src/app/store/machine/slice.ts
ui/src/app/store/machine/types/base.ts
ui/src/app/store/types/node.ts
ui/src/testing/factories/state.ts

- Built basic clone form with regular, unfiltered select and no validation. Form is currently unsubmittable until the API is ready.
- Select some machines from the machine list and check that you can open the Clone form.
- Go to a machine details page and check that you can open the Clone form.
Fixes …

feat(ui): add basic clone form

---

ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneForm.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/CloneFormFields.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/SourceMachineSelect/SourceMachineSelect.test.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/SourceMachineSelect/SourceMachineSelect.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/SourceMachineSelect/_index.scss
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/SourceMachineSelect/index.ts
ui/src/app/store/machine/selectors.test.ts
ui/src/app/store/machine/selectors.ts
ui/src/scss/index.scss

- Built dynamic source machine select in cloning form
- From the machine list select some machines and select "Clone from..." from the action menu
- Check that the source machine select matches [the design](https://app.zeplin.io/project/60e32f0e5c4c0f13e711d590/screen/6107cdc190beaf14f03906fd)
- Check that you can filter …

feat(ui): build source machine select in cloning form

---

ui/src/app/base/components/LabelledList/_index.scss
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/CloneFormFields.test.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/CloneFormFields.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/SourceMachineSelect/SourceMachineDetails/SourceMachineDetails.test.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/SourceMachineSelect/SourceMachineDetails/SourceMachineDetails.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/SourceMachineSelect/SourceMachineDetails/__snapshots__/SourceMachineDetails.test.tsx.snap
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/SourceMachineSelect/SourceMachineDetails/index.ts
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/SourceMachineSelect/SourceMachineSelect.test.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/SourceMachineSelect/SourceMachineSelect.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/SourceMachineSelect/_index.scss
ui/src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.tsx

- Fetch full machine details when selecting a source machine in the cloning form
- Show a placeholder list while details are loading
- Moved Redux store interactions up from `SourceMachineSelect` to `CloneFormFields` because the selected machine details will need to be made available to all the form fields
- Select a machine and …

feat(ui): fetch full machine details from machine cloning form

---

ui/src/app/base/components/Placeholder/Placeholder.test.tsx
ui/src/app/base/components/Placeholder/Placeholder.tsx
ui/src/app/base/components/Placeholder/__snapshots__/Placeholder.test.tsx.snap
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/SourceMachineSelect/SourceMachineDetails/SourceMachineDetails.test.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/SourceMachineSelect/SourceMachineDetails/SourceMachineDetails.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/SourceMachineSelect/SourceMachineDetails/__snapshots__/SourceMachineDetails.test.tsx.snap

- Updated `Placeholder` component to show real content when loaded
- Open the clone form and select a source machine
- Check that the placeholder content shows while the machine details are loading
- Go to a PCI devices tab of a machine has them
- Check that the placeholder content shows while the PCI devices are loading
Fixes …

feat(ui): update Placeholder to show real content when loaded

---

ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/CloneFormFields.test.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/CloneFormFields.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/SourceMachineSelect/SourceMachineSelect.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/SourceMachineSelect/_index.scss
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/_index.scss
ui/src/scss/index.scss

- Added styling for the clone form tables/cards
- Open the clone form and check that it matches [the design when no source is selected](https://app.zeplin.io/project/60e32f0e5c4c0f13e711d590/screen/6107cdc217980210cde2b201)
- Check that checking a checkbox increases the opacity of the table
Fixes …

feat(ui): set up clone form table styling

---

ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/CloneFormFields.test.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/CloneFormFields.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/CloneStorageTable/CloneStorageTable.test.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/CloneStorageTable/CloneStorageTable.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/CloneStorageTable/index.ts
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/_index.scss
ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AvailableStorageTable.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/NumaNodes/NumaNodes.tsx

- Added machine storage table to cloning form
- Select a couple of machines and open the clone form
- Select a source machine and check that placeholder content shows in the storage table while the machine details are loading
- Check that once the details are loaded the storage table looks like [the …

feat(ui): add storage table to cloning form

---

ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/CloneFormFields.test.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/CloneFormFields.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/CloneNetworkTable/CloneNetworkTable.test.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/CloneNetworkTable/CloneNetworkTable.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/CloneNetworkTable/index.ts
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/CloneStorageTable/CloneStorageTable.test.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/CloneStorageTable/CloneStorageTable.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/SourceMachineSelect/SourceMachineSelect.test.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/SourceMachineSelect/SourceMachineSelect.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/_index.scss

- Added machine network table to cloning form
- Select a couple of machines and open the clone form
- Select a source machine and check that placeholder content shows in the network table while the machine details are loading
- Check that once the details are loaded the network table looks like [the …

feat(ui): add network table to cloning form

---

ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/SourceMachineSelect/SourceMachineSelect.test.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/SourceMachineSelect/SourceMachineSelect.tsx

- Added an error notification to the clone form if all machines in the list have been selected
- Select all machines in the machine list and open the clone form
- Check that an error shows in the source machine select as per [the design](https://app.zeplin.io/project/60e32f0e5c4c0f13e711d590/screen/610bedecd41b0366218330b3)
- …

feat(ui): add warning to clone form if no source machines available

---

ui/.betterer.results
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneForm.test.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneForm.tsx
ui/src/app/store/machine/actions.test.ts
ui/src/app/store/machine/reducers.test.ts
ui/src/app/store/machine/slice.ts
ui/src/app/store/machine/types/actions.ts
ui/src/app/store/machine/types/index.ts

- Added clone action to machine slice
- Open the clone form from the machine list and submit the form
- Check that Redux actions are dispatched and a response from the API is recorded (either `cloneSuccess` or `cloneError`). Ignore the unformatted errors for now as they'll be handled in follow-ups.
- Do the same from a machine …

feat(ui): add clone action to machine slice

---

ui/src/app/base/components/ActionForm/ActionForm.tsx
ui/src/app/base/components/FormikForm/FormikForm.tsx
ui/src/app/base/components/FormikFormButtons/FormikFormButtons.test.tsx
ui/src/app/base/components/FormikFormButtons/FormikFormButtons.tsx
ui/src/app/base/components/FormikFormButtons/_index.scss
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneForm.tsx
ui/src/app/machines/components/ActionFormWrapper/FieldlessForm/__snapshots__/FieldlessForm.test.tsx.snap
ui/src/app/machines/views/AddChassis/AddChassisForm/AddChassisForm.js
ui/src/app/machines/views/AddMachine/AddMachineForm/AddMachineForm.js
ui/src/app/machines/views/MachineDetails/MachineHeader/MachineName/__snapshots__/MachineName.test.tsx.snap
ui/src/app/machines/views/MachineDetails/MachineHeader/MachineNameFields/MachineNameFields.tsx
ui/src/app/machines/views/MachineDetails/MachineHeader/MachineNameFields/__snapshots__/MachineNameFields.test.tsx.snap
ui/src/scss/index.scss

- Added help text to the clone form
- Updated `FormikFormButtons` to be able to put anything in the "help" area
- Updated `FormikFormButtons` to use custom classes - seemed like there was too much styling logic happening in the JS
- Fixed up some wonky styling on the machine edit name form thing - think a Vanilla update might have changed how inline forms work …

feat(ui): add help text to clone form

---

ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneForm.test.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneForm.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/CloneFormFields.tsx

- Added validation to clone form
- Select a machine and open the clone form
- Check that the network and storage checkboxes are disabled and the submit button is disabled
- Select a source machine and check that the network and storage checkboxes are enabled, but the submit button is still disabled
- Tick one of either network …

feat(ui): add validation to clone form

---

ui/src/app/base/components/ErrorBoundary/ErrorBoundary.test.tsx
ui/src/app/base/components/ErrorBoundary/ErrorBoundary.tsx

- migrate ErrorBoundary to TypeScript.
N/A

refactor(ui): migrate ErrorBoundary to TypeScript

---

ui/.betterer.results
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneForm.test.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneForm.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/CloneFormFields.test.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/CloneFormFields.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneResults/CloneResults.test.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneResults/CloneResults.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneResults/index.ts

- Added clone completion section to the clone form
- Go to the machine list and select some machines
- Open the clone form and submit the form
- Check that once the action is complete the form is replaced with a section showing how many machines were successfully cloned to. An error notification should show if any errors …

feat(ui): add clone completion section to clone form

---

ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneFormFields/_index.scss
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneResults/CloneResults.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneResults/_index.scss
ui/src/scss/index.scss

- Improved responsiveness of the clone form
- Converted error notification into a table
- Select some machines and open the clone form
- Resize the viewport and check that it looks good on all screen sizes
- Submit the form with errors to get to the results page
- Again resize the viewport and check that it looks good on all …

feat(ui): improve responsiveness of clone form

---

ui/src/app/App.tsx
ui/src/index.tsx

- Fixed ordered of CSS when using `yarn ui`
__Check that the styles are correct in development__
- Load the app in standalone React mode (`yarn ui`)
- Open up a production deployment of the same MAAS (e.g. bolla)
- Check that the UI is exactly the same between the two versions
__Check that the styles are correct in production__ …

fix(ui): fix ordering of CSS in standalone React mode

---

legacy/src/app/directives/dhcp_snippets_table.js
legacy/src/app/directives/tests/test_dhcp_snippets_table.js
legacy/src/app/partials/dhcp-snippets-table.html

- Backport of https://github.com/canonical-web-and-design/maas-ui/pull/3006
- Run the full app with `yarn start`
- Go to /MAAS/r/settings/dhcp/add and add a DHCP snippet for a device, controller or subnet
- Go to the details page of the device/controller/subnet you added a DHCP snippet for
- Click the edit button for the DHCP …

fix(legacy): fix legacy edit DHCP snippets enabled value (3.0 backport #3006)

---

legacy/src/app/directives/dhcp_snippets_table.js
legacy/src/app/directives/tests/test_dhcp_snippets_table.js
legacy/src/app/partials/dhcp-snippets-table.html

- Backport of https://github.com/canonical-web-and-design/maas-ui/pull/3006
- Run the full app with `yarn start`
- Go to /MAAS/r/settings/dhcp/add and add a DHCP snippet for a device, controller or subnet
- Go to the details page of the device/controller/subnet you added a DHCP snippet for
- Click the edit button for the DHCP …

fix(legacy): fix legacy edit DHCP snippets enabled value (2.9 backport #3006)

---

ui/src/app/base/components/SectionHeader/SectionHeader.test.tsx
ui/src/app/base/components/SectionHeader/SectionHeader.tsx
ui/src/app/domains/views/DomainDetails/DomainDetailsHeader/DomainDetailsHeader.tsx
ui/src/app/kvm/views/KVMDetails/KVMDetailsHeader/KVMDetailsHeader.tsx
ui/src/app/kvm/views/KVMList/KVMListHeader/KVMListHeader.tsx
ui/src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.tsx

- Removed subtitle and buttons from `SectionHeader` if there is any `headerContent` present (i.e. a form is open)
- Go to the machine list, select some machines and open a form
- Check that there is no subtitle and no buttons present in the header
- Check the same thing in a few other places (machine details, KVM, AZs, domains, …

feat(ui): hide header subtitle and buttons if form is open

---

ui/src/app/base/types.ts
ui/src/app/kvm/components/KVMHeaderForms/KVMHeaderForms.tsx
ui/src/app/kvm/types.ts
ui/src/app/kvm/views/KVMDetails/KVMDetails.tsx
ui/src/app/kvm/views/KVMDetails/KVMDetailsHeader/KVMDetailsHeader.test.tsx
ui/src/app/kvm/views/KVMDetails/KVMDetailsHeader/KVMDetailsHeader.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/LxdProject.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/ProjectVMs.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsActionBar/VMsActionBar.tsx
ui/src/app/machines/components/ActionFormWrapper/ActionFormWrapper.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneForm.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneResults/CloneResults.test.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneResults/CloneResults.tsx
ui/src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.tsx
ui/src/app/machines/views/MachineList/MachineList.tsx
ui/src/app/machines/views/MachineList/MachineListHeader/MachineListHeader.tsx

- Added filtering to clone results table
- Go to the machine list, select some machines and select "Clone from" from the action menu
- Choose a source with incompatible networking/storage and submit the form
- Check that you can filter the machine list by clicking the "Show" link, and that opening the link in a new tab will also …

feat(ui): add ability to filter machines by clone error

---

ui/src/app/kvm/components/KVMHeaderForms/AddKVM/AddLxd/SelectProjectForm/SelectProjectFormFields/SelectProjectFormFields.test.tsx
ui/src/app/kvm/components/KVMHeaderForms/AddKVM/AddLxd/SelectProjectForm/SelectProjectFormFields/SelectProjectFormFields.tsx
ui/src/app/kvm/views/KVMDetails/KVMConfiguration/KVMConfiguration.test.tsx
ui/src/app/kvm/views/KVMDetails/KVMConfiguration/KVMConfiguration.tsx
ui/src/app/kvm/views/KVMDetails/KVMConfiguration/KVMConfigurationFields/KVMConfigurationFields.test.tsx
ui/src/app/kvm/views/KVMDetails/KVMConfiguration/KVMConfigurationFields/KVMConfigurationFields.tsx
ui/src/app/kvm/views/KVMDetails/KVMDetailsHeader/KVMDetailsHeader.test.tsx
ui/src/app/kvm/views/KVMDetails/KVMDetailsHeader/KVMDetailsHeader.tsx
ui/src/app/kvm/views/KVMDetails/KVMResources/KVMResources.test.tsx
ui/src/app/kvm/views/KVMDetails/KVMResources/KVMResources.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/LxdProject.test.tsx
ui/src/app/kvm/views/KVMDetails/LxdProject/LxdProject.tsx
ui/src/app/kvm/views/KVMList/LxdTable/LxdTable.test.tsx
ui/src/app/kvm/views/KVMList/NameColumn/NameColumn.test.tsx
ui/src/app/kvm/views/KVMList/NameColumn/NameColumn.tsx
ui/src/app/store/pod/selectors.test.ts
ui/src/app/store/pod/selectors.ts
ui/src/app/store/pod/types/base.ts
ui/src/app/store/pod/types/index.ts
ui/src/testing/factories/index.ts
ui/src/testing/factories/nodes.ts

- Updated pod object to use new power_parameters shape
- Updated pod types
- Removed password field for LXD KVMs
- Go to /MAAS/r/kvm and check that LXD KVMs are grouped properly
- Check you can add a LXD KVM successfully
- Go to the KVM config page and check that the power address fills in correctly
- Check there is no password …

feat(ui): update pod to use new power_parameters shape

---

ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/CloneForm/CloneFormFields/SourceMachineSelect/_index.scss
ui/src/app/machines/utils.test.ts
ui/src/app/machines/utils.ts

- Validate destination machine status is either Ready or Failed testing before cloning
- Go to the machine list and select a bunch of machines including some that are Ready/Failed testing and some that are not
- Attempt to open the clone form and check that you get a prompt to change the selection
- Check that the remaining …

fix(ui): validate destination machine status before cloning

---

ui/src/app/base/components/FormCard/FormCard.tsx
ui/src/app/base/components/LabelledList/_index.scss
ui/src/app/kvm/views/KVMDetails/KVMConfiguration/AuthenticationCard/AuthenticationCard.test.tsx
ui/src/app/kvm/views/KVMDetails/KVMConfiguration/AuthenticationCard/AuthenticationCard.tsx
ui/src/app/kvm/views/KVMDetails/KVMConfiguration/AuthenticationCard/_index.scss
ui/src/app/kvm/views/KVMDetails/KVMConfiguration/AuthenticationCard/index.ts
ui/src/app/kvm/views/KVMDetails/KVMConfiguration/KVMConfiguration.tsx
ui/src/app/store/pod/types/base.ts
ui/src/app/store/pod/types/index.ts
ui/src/app/store/pod/utils.ts
ui/src/scss/index.scss
ui/src/testing/factories/index.ts
ui/src/testing/factories/nodes.ts
yarn.lock

- Added Authentication card to LXD VM hosts that use certificate authentication
- Go to the config page of a LXD VM host that uses certificate authentication (e.g. "test" on bolla)
- Check that the "Authentication" card matches the [design](https://app.zeplin.io/project/610abd78c381eeafb70f5b43/screen/6127d59b0c2b43b325928375) …

feat(ui): add Authentication card to VM host config

---

ui/src/app/base/components/Stepper/Stepper.test.tsx
ui/src/app/base/components/Stepper/Stepper.tsx
ui/src/app/base/components/Stepper/__snapshots__/Stepper.test.tsx.snap
ui/src/app/base/components/Stepper/_index.scss
ui/src/app/base/components/Stepper/index.ts
ui/src/app/kvm/components/KVMHeaderForms/AddKVM/AddLxd/AddLxd.tsx
ui/src/app/kvm/components/KVMHeaderForms/AddKVM/AddLxd/AuthenticationForm/AuthenticationForm.tsx
ui/src/scss/index.scss

- Built `Stepper` component, which is just a horizontal version of `.p-stepped-list` with an extra bit of styling to show a tick instead of a number
- Used `Stepper` in the `AddLxd` form
- Go to the KVM list and click "Add KVM"
- Check that there is a stepped list on top of the form
- Fill in the first part of the form and click …

feat(ui): build Stepper component

---

ui/src/app/base/components/AuthenticationFields/AuthenticationFields.test.tsx
ui/src/app/base/components/AuthenticationFields/AuthenticationFields.tsx
ui/src/app/base/components/AuthenticationFields/index.ts
ui/src/app/base/components/PowerTypeFields/PowerTypeFields.test.tsx
ui/src/app/base/components/PowerTypeFields/PowerTypeFields.tsx
ui/src/app/kvm/components/KVMHeaderForms/AddKVM/AddLxd/AddLxd.tsx
ui/src/app/kvm/components/KVMHeaderForms/AddKVM/AddLxd/AuthenticationForm/AuthenticationForm.tsx
ui/src/app/kvm/components/KVMHeaderForms/AddKVM/AddLxd/CredentialsForm/CredentialsFormFields/CredentialsFormFields.tsx
ui/src/app/machines/views/MachineDetails/MachineConfiguration/PowerForm/PowerFormFields/PowerFormFields.tsx
ui/src/app/store/general/slice.ts
ui/src/scss/index.scss

- Added `AuthenticationFields` component and used in both "Add machine > LXD" and "Add KVM > LXD" forms
- Go to the machine list and click "Add hardware > Machine"
- Select LXD as the power type and check that there is a radio button section for authentication (upload functionality to be handled separately)
- Check that you can …

feat(ui): add customised auth fields for LXD power type

---

ui/src/app/base/components/FormikFormContent/FormikFormContent.test.tsx
ui/src/app/base/components/FormikFormContent/FormikFormContent.tsx
ui/src/app/kvm/components/KVMHeaderForms/AddKVM/AddLxd/AddLxd.test.tsx
ui/src/app/kvm/components/KVMHeaderForms/AddKVM/AddLxd/AddLxd.tsx
ui/src/app/kvm/components/KVMHeaderForms/AddKVM/AddLxd/AuthenticationForm/AuthenticationForm.test.tsx
ui/src/app/kvm/components/KVMHeaderForms/AddKVM/AddLxd/AuthenticationForm/AuthenticationForm.tsx
ui/src/app/kvm/components/KVMHeaderForms/AddKVM/AddLxd/AuthenticationForm/AuthenticationFormFields/AuthenticationFormFields.tsx
ui/src/app/kvm/components/KVMHeaderForms/AddKVM/AddLxd/CredentialsForm/CredentialsForm.test.tsx
ui/src/app/kvm/components/KVMHeaderForms/AddKVM/AddLxd/CredentialsForm/CredentialsForm.tsx
ui/src/app/kvm/components/KVMHeaderForms/AddKVM/AddLxd/SelectProjectForm/SelectProjectFormFields/SelectProjectFormFields.tsx
ui/src/app/store/pod/actions.test.ts
ui/src/app/store/pod/reducers.test.ts
ui/src/app/store/pod/slice.ts
ui/src/app/store/pod/types/actions.ts
ui/src/app/store/pod/types/index.ts
ui/src/app/utils/index.ts
ui/src/app/utils/splitCertificateName.test.ts
ui/src/app/utils/splitCertificateName.ts

- Added `pollLxdServer` to pod slice, which continuously checks authentication status with a LXD server
- Moved `setStep` functionality out of `AddLxd` and in to the individual step components. Having it all handled in the parent was a bit too inconsistent.
- Go to the KVM list and click "Add KVM"
- Enter some details, make sure …

feat(ui): add ability to poll LXD server for authentication status

---

ui/src/app/kvm/components/KVMHeaderForms/AddKVM/AddLxd/AuthenticationForm/AuthenticationForm.tsx
ui/src/app/kvm/components/KVMHeaderForms/AddKVM/AddLxd/CredentialsForm/CredentialsForm.test.tsx
ui/src/app/kvm/components/KVMHeaderForms/AddKVM/AddLxd/CredentialsForm/CredentialsForm.tsx

- Fixed a race condition where the generated certificate was not getting cleared in time when reverting from the Authentication step to the Credentials step.
- Go to the KVM list and click Add KVM
- Enter bogus details, including a malformed LXD address
- Click "Use trust password", enter anything then click "Check …

fix(ui): prevent advancing "Add LXD" steps if errors are present

---

ui/src/app/base/components/ScriptStatus/ScriptStatus.test.tsx
ui/src/app/base/components/ScriptStatus/ScriptStatus.tsx
ui/src/app/machines/views/MachineList/MachineListTable/PowerColumn/PowerColumn.test.tsx
ui/src/app/machines/views/MachineList/MachineListTable/PowerColumn/PowerColumn.tsx
ui/src/app/machines/views/MachineList/MachineListTable/PowerColumn/__snapshots__/PowerColumn.test.tsx.snap

- Added a tooltip to the power column if a machine power is in error state
- Driveby fix in `ScriptStatus`, where if the given children was the number `0` it wouldn't be inline since it's falsy
- If your MAAS doesn't have a machine in error state, edit a machine's power config with incorrect credentials
- Go to the machine list …

feat(ui): add tooltip to power column if machine power is in error state

---

ui/src/app/base/components/PowerTypeFields/BasePowerField/BasePowerField.test.tsx
ui/src/app/base/components/PowerTypeFields/BasePowerField/BasePowerField.tsx
ui/src/app/base/components/PowerTypeFields/BasePowerField/index.ts
ui/src/app/base/components/PowerTypeFields/LXDPowerFields/LXDPowerFields.test.tsx
ui/src/app/base/components/PowerTypeFields/LXDPowerFields/LXDPowerFields.tsx
ui/src/app/base/components/PowerTypeFields/LXDPowerFields/index.ts
ui/src/app/base/components/PowerTypeFields/PowerTypeFields.test.tsx
ui/src/app/base/components/PowerTypeFields/PowerTypeFields.tsx
ui/src/app/machines/views/MachineDetails/MachineConfiguration/PowerForm/PowerFormFields/PowerFormFields.tsx

- Created two subcomponents from `PowerTypeFields`
- `BasePowerField` which generates a field directly from the API
- `LXDPowerFields` which customises power fields specifically for LXD
- Check that nothing has changed
- Adding a LXD machine shows authentication radios
- Editing a LXD machine shows textareas for certificate and …

feat(ui): split PowerTypeFields into subcomponents that allow for customisation

---

.github/ISSUE_TEMPLATE/cypress-failure.md
.github/workflows/cypress.yml

- Create a new issue when Cypress fails in CI.
N/A
Fixes: #3052.

ci(ui): create an issue when Cypress fails

---

.github/ISSUE_TEMPLATE/cypress-failure.md
.github/workflows/cypress.yml

- Create a new issue when Cypress fails in CI.
N/A
Fixes: #3052.

ci(ui): create an issue when Cypress fails (#3073) - backport 3.0

---

.github/ISSUE_TEMPLATE/cypress-failure.md
.github/workflows/cypress.yml

- Create a new issue when Cypress fails in CI.
N/A
Fixes: #3052.

ci(ui): create an issue when Cypress fails (#3073) - backport 2.9

---

ui/src/app/base/components/SectionHeader/SectionHeader.tsx
ui/src/app/kvm/urls.ts
ui/src/app/kvm/views/KVM.tsx
ui/src/app/kvm/views/KVMDetails/KVMDetailsHeader/KVMDetailsHeader.tsx
ui/src/app/kvm/views/KVMList/KVMList.test.tsx
ui/src/app/kvm/views/KVMList/KVMList.tsx
ui/src/app/kvm/views/KVMList/KVMListHeader/KVMListHeader.test.tsx
ui/src/app/kvm/views/KVMList/KVMListHeader/KVMListHeader.tsx

- Update the KVM list to display the LXD and Virsh tables on different tabs.
- Click on LXD in the header.
- If you have LXD pods it should redirect to /kvm/lxd.
- You should see the LXD table.
- If there are Virsh pods there should also be a virsh tab.
- Clicking on the Virsh tab should dispaly the Virsh table.
Fixes: canonical-web-and-design/app-squad#286.

feat(ui): move lxd and virsh tables to tabs

---

ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsTable/VMsTable.tsx

- Replace AZs with tags.
- Combine ram and storage columns.
- Rename "Name" to "VM name".
- Rename "Resource pool" column to "Pool".
- Go to a LXD kvm details page.
- On the project tab go down to the list of kvms.
- Check that the last column header has "Pool" and "Tag".
- Check that the tags are shown below the pool for the vm rows.
- Check that the Ram and …

feat(ui): update vm table columns

---

ui/src/app/kvm/views/KVMDetails/KVMResources/ProjectResourcesCard/ProjectResourcesCard.tsx
ui/src/app/kvm/views/KVMDetails/KVMResources/ProjectResourcesCard/_index.scss
ui/src/app/kvm/views/KVMDetails/VmResources/VmResources.tsx
ui/src/app/kvm/views/KVMDetails/VmResources/_index.scss

- Move total vms to a link under the resources card.
- Go to the resources tab in a LXD kvm's details.
- The "Total VMs" link should be below the "default" card.
- Toggle to view by numa node.
- The total vms link should be inside the card.
Fixes: canonical-web-and-design/app-squad#299.

feat(ui): make total vms a link

---

ui/src/app/base/components/CertificateDetails/CertificateDetails.tsx
ui/src/app/base/components/CertificateDetails/_index.scss
ui/src/app/kvm/views/KVMDetails/KVMSettings/AuthenticationCard/UpdateCertificate/UpdateCertificateFields/UpdateCertificateFields.tsx
ui/src/scss/_patterns_forms.scss
ui/src/scss/index.scss

- Fixed textarea styling in LXD certificate form (forgot to update class)
- Go to the config of a LXD KVM
- Click Update certificate and generate a new certificate
- Check that the private key textarea looks right
Fixes #3087

fix(ui): fix textarea styling in update LXD certificate form

---

ui/src/app/kvm/components/KVMHeaderForms/AddKVM/AddLxd/CredentialsForm/CredentialsFormFields/CredentialsFormFields.tsx

- Added `datalist` to LXD address input
- Go to the KVM list and click "Add KVM"
- Check that you can select an existing LXD address from the dropdown or create a new one
Fixes canonical-web-and-design/app-squad#251

feat(ui): use datalist for LXD address select

---

ui/src/app/kvm/components/LXDHostToolbar/LXDHostToolbar.test.tsx
ui/src/app/kvm/components/LXDHostToolbar/LXDHostToolbar.tsx
ui/src/app/kvm/components/LXDHostToolbar/_index.scss

- Update the host toolbar to be responsive to the content and screen size.
- Visit /LXD.
- Click on a cluster.
- Click on a hostname in the table.
- Check that the toolbar (the "VMs on ..." row) looks OK at different screen sizes.
Fixes: canonical-web-and-design/app-squad#10.

feat(ui): make the LXD toolbar responsive

---

ui/src/app/kvm/components/StorageResources/StorageCards/StorageCards.tsx
ui/src/app/kvm/components/StorageResources/StorageCards/_index.scss
ui/src/app/kvm/components/StorageResources/StorageResources.test.tsx
ui/src/app/kvm/components/StorageResources/StorageResources.tsx
ui/src/app/kvm/components/StorageResources/_index.scss

- Updated KVM storage cards to [latest design](https://www.figma.com/file/QNQ3ZsYLR0tamnFzCo8VP6/%5B21.10%5D-LXD-Clusters?node-id=340%3A8982). I have made some slight changes though:
- Allocated shows the value instead of the percentage. I think the bar at bottom already provides a visual representation of the allocated ratio, so the actual byte value seems more useful here.
- The bar does not sit butt up against the bottom of the summary card. I think that might have been a mistake in the design wireframe.
- I've made the minimum aspect ratio of the cards higher than what's shown in the design, so you can only fit two cards in the space before it snaps to a smaller card size. Doing otherwise would mean a lot of the content would get truncated.
To run this branch you will need access to …

feat(ui): update KVM storage cards to latest design

---

integration/cypress/integration/base/header.spec.ts

- Update header Cypress test to point to LXD KVM list
- N/A
Fixes #3203

fix(cypress): fix KVM list redirect location

---

ui/src/app/kvm/components/KVMHeaderForms/DeleteForm/DeleteForm.test.tsx
ui/src/app/kvm/components/KVMHeaderForms/DeleteForm/DeleteForm.tsx
ui/src/app/kvm/hooks.test.tsx
ui/src/app/kvm/hooks.tsx
ui/src/app/kvm/views/LXDClusterDetails/LXDClusterDetails.test.tsx
ui/src/app/kvm/views/LXDClusterDetails/LXDClusterDetails.tsx
ui/src/app/kvm/views/LXDSingleDetails/LXDSingleDetails.test.tsx
ui/src/app/kvm/views/LXDSingleDetails/LXDSingleDetails.tsx
ui/src/app/kvm/views/VirshDetails/VirshDetails.tsx

- Update the cluster and pod detail views to display a not-found message if the id is invalid.
- Redirect from the delete form when the cluster/pod is deleted.
- Visit /MAAS/r/kvm/virsh/9999.
- You should see a not-found message.
- Visit /MAAS/r/kvm/lxd/9999.
- You should see a not-found message.
- Visit /MAAS/r/kvm/lxd/cluster/9999.
- You should see a …

feat(ui): handle cluster/pod 404s and redirects when deleting

---

ui/src/app/kvm/components/LXDHostVMs/LXDHostVMs.tsx

- Changed LXD host VMs title from "VMs on {pod.name}" to "VMs on this host"
- Go to the VMs tab of a LXD host and check that the toolbar title is "VMs on this host"
Fixes canonical-web-and-design/app-squad#411

feat(ui): change the title of the LXD host VMs toolbar to be generic

---

ui/src/app/kvm/components/CPUColumn/CPUColumn.test.tsx
ui/src/app/kvm/components/CPUColumn/CPUColumn.tsx
ui/src/app/kvm/components/CPUColumn/CPUPopover/CPUPopover.test.tsx
ui/src/app/kvm/components/CPUColumn/CPUPopover/CPUPopover.tsx
ui/src/app/kvm/components/RAMColumn/RAMColumn.test.tsx
ui/src/app/kvm/components/RAMColumn/RAMColumn.tsx
ui/src/app/kvm/components/RAMColumn/RAMPopover/RAMPopover.test.tsx
ui/src/app/kvm/components/RAMColumn/RAMPopover/RAMPopover.tsx
ui/src/app/kvm/components/StorageColumn/StorageColumn.test.tsx
ui/src/app/kvm/components/StorageColumn/StorageColumn.tsx
ui/src/app/kvm/views/KVMList/LxdTable/LxdKVMHostTable/LxdKVMHostTable.tsx
ui/src/app/store/pod/utils.ts
ui/src/app/store/vmcluster/types/base.ts
ui/src/app/store/vmcluster/types/index.ts
ui/src/testing/factories/vmcluster.ts

- Updated vmcluster types to match latest shape
- Included `allocated_other` data for clusters in the LXD KVM list, which meant that a lot of type-checking could be removed from the column components
- Added `allocated_other` for storage, which was missing. There's currently a bug in the API where we only get back the total allocated_other across all pools, but not the allocated_other for each pool. https://bugs.launchpad.net/maas/+bug/1949418
- Serving with …

feat(ui): include allocated_other for cluster rows in LXD KVM list

---

ui/src/app/kvm/hooks.test.tsx
ui/src/app/kvm/hooks.tsx
ui/src/app/kvm/views/LXDClusterDetails/LXDClusterSettings/LXDClusterSettings.test.tsx
ui/src/app/kvm/views/LXDClusterDetails/LXDClusterSettings/LXDClusterSettings.tsx
ui/src/app/kvm/views/LXDSingleDetails/LXDSingleSettings/AuthenticationCard/AuthenticationCard.test.tsx
ui/src/app/kvm/views/LXDSingleDetails/LXDSingleSettings/AuthenticationCard/AuthenticationCard.tsx
ui/src/app/kvm/views/LXDSingleDetails/LXDSingleSettings/AuthenticationCard/UpdateCertificate/UpdateCertificate.test.tsx
ui/src/app/kvm/views/LXDSingleDetails/LXDSingleSettings/AuthenticationCard/UpdateCertificate/UpdateCertificate.tsx
ui/src/app/kvm/views/LXDSingleDetails/LXDSingleSettings/LXDSingleSettings.tsx

- Added AuthenticationCard to LXDClusterSettings, using the cluster's first host as the canary
- Using bolla, navigate to http://0.0.0.0:8400/MAAS/r/kvm/lxd/cluster/22/edit
- Check that an Authentication card shows
- Generate a new certificate and check that the change persists (the certificate data that is shown is for karura, …

feat(ui): add authentication card to cluster settings

---

ui/src/app/kvm/views/LXDClusterDetails/LXDClusterHostSettings/LXDClusterHostSettings.tsx
ui/src/app/kvm/views/LXDClusterDetails/LXDClusterSettings/LXDClusterSettings.tsx

- Set the window title when viewing the cluster settings or a cluster host's settings.
- Go to a cluster and click on the cluster settings tab.
- Check that the window title is something like "lxd-cluster settings".
- Go to the VM hosts tab and click on a VM host.
- Under the host's name click the settings link.
- Check that the window title is something like …

fix(ui): set the window title for cluster settings

---

ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AvailableStorageTable.tsx

- Add titles on hover for storage columns that get truncated.
- Go to the storage tab in machine details.
- Find the 'Available disks and partitions' table.
- Check that the name, serial, model and firmware data displays a title when hovered.
Fixes: #3180.

feat(ui): display hover titles for storage columns

---

ui/src/app/kvm/components/KVMHeaderForms/ComposeForm/ComposeForm.tsx
ui/src/app/kvm/components/KVMHeaderForms/ComposeForm/ComposeFormFields/ComposeFormFields.test.tsx
ui/src/app/kvm/components/KVMHeaderForms/ComposeForm/ComposeFormFields/ComposeFormFields.tsx
ui/src/app/utils/arrayFromRangesString.test.ts
ui/src/app/utils/arrayFromRangesString.ts

- Show a warning instead of an error when trying to pin to an already pinned core when composing a VM
- Fixed some bad sorting in `arrayFromRangesString` util which would put `10` before `2`
- Go to the details page of a LXD KVM and click "Add virtual machine"
- Choose to pin cores and enter "2-10" into the field and check that …

fix(ui): allow pinning to already pinned core when composing VM

---

integration/cypress/integration/preferences/base.spec.ts
integration/cypress/integration/settings/base.spec.ts
ui/src/app/base/components/SectionHeader/SectionHeader.test.tsx
ui/src/app/base/components/SectionHeader/SectionHeader.tsx

- Fixed a bug where two disparate DOM elements had the same `data-test` attribute, which caused Cypress to target the wrong element.
- Open `integration/cypress.json` and edit the login details for the MAAS you're connected to
- Run `yarn ui` in one window and `yarn cypress-open` in another
- Run the Cypress tests for …

fix(cypress): fix duplicate data-test attr causing Cypress failures

---

ui/src/app/settings/views/Configuration/KernelParametersForm/KernelParametersForm.tsx

- Removed explicit type cast causing causing a Formik error in KernelParametersForm
- Using a MAAS that has no global kernel parameters set, go to `/MAAS/r/settings/configuration/kernel-parameters` and check you don't get an error in the console
Fixes #3222

fix(ui): fix possible null value being passed to KernelParametersForm

---

ui/src/app/kvm/components/LXDHostVMs/LXDHostVMs.test.tsx
ui/src/app/kvm/components/LXDHostVMs/LXDHostVMs.tsx

- Display the name of the host in the VM list when viewing a single LXD host.
- Go to /KVM and click on a single host.
- In the VMs tab the title should read "VMs on this host".
- Go back to the KVM list and click on a cluster.
- Click the name of a host.
- The title should now read "VMs on [host-name]".
Fixes: #3248.

fix(ui): display the host title for single hosts

---

ui/src/app/kvm/components/KVMHeaderForms/ComposeForm/StorageTable/StorageTable.test.tsx
ui/src/app/kvm/components/KVMHeaderForms/ComposeForm/StorageTable/StorageTable.tsx

- Updated the compose form to only show a warning if the boot disk is below 8GB.
- Go to a LXD cluster or single host and open the compose form.
- Scroll down to 'Storage configuration' and click 'Add disk'.
- Change the size on both disks to be less than 8GB.
- You should see size warning on the first disk but not the second.
- Change the boot radio button …

feat(ui): only warn if the boot disk is below 8GB

---

ui/src/app/kvm/components/KVMHeaderForms/ComposeForm/StorageTable/PoolSelect/PoolSelect.tsx
ui/src/app/kvm/components/KVMStorageCards/KVMStorageCards.test.tsx
ui/src/app/kvm/components/KVMStorageCards/KVMStorageCards.tsx
ui/src/app/kvm/components/LXDVMsSummaryCard/LXDVMsSummaryCard.tsx
ui/src/app/kvm/components/StorageColumn/StorageColumn.tsx
ui/src/app/kvm/components/StorageColumn/StoragePopover/StoragePopover.test.tsx
ui/src/app/kvm/components/StorageColumn/StoragePopover/StoragePopover.tsx
ui/src/app/kvm/components/StorageResources/StorageCards/StorageCards.tsx
ui/src/app/kvm/components/StorageResources/StorageMeter/StorageMeter.tsx
ui/src/app/kvm/components/StorageResources/StorageMeter/__snapshots__/StorageMeter.test.tsx.snap
ui/src/app/kvm/components/StorageResources/StorageResources.tsx
ui/src/app/kvm/utils.test.ts
ui/src/app/kvm/utils.ts
ui/src/app/kvm/views/KVMList/LxdTable/LxdKVMHostTable/LxdKVMHostTable.tsx
ui/src/app/kvm/views/LXDSingleDetails/LXDSingleResources/LXDSingleResources.tsx
ui/src/app/kvm/views/VirshDetails/VirshResources/VirshResources.tsx
ui/src/app/store/pod/selectors.test.ts
ui/src/app/store/pod/selectors.ts
ui/src/app/store/pod/types/base.ts
ui/src/testing/factories/nodes.ts

- Re-implemented KVM storage pool sorting using `pod.resources.storage_pools` as opposed to `pod.storage_pools` 
- Removed `pod.getSortedPools` selector as we want sorting to work across pods and clusters
- Go to the LXD KVM list and hover over the storage column and check that single hosts show a "default" pool but clusters do …

fix(ui): re-add KVM storage pool sorting with resources endpoint

---

ui/src/app/machines/views/MachineDetails/MachineStorage/ChangeStorageLayout/ChangeStorageLayout.tsx
ui/src/app/store/machine/types/enum.ts

- Added "custom" option to ChangeStorageLayout dropdown
- Go to the Storage tab of a Ready machine
- Click "Change storage layout"
- Check that "Custom" is an option. Click it and submit the form.
- You should get an error. I've been trying to find out how to format a custom commissioning script to test this for real but it's …

feat(ui): add "custom" option to ChangeStorageLayout dropdown

---

ui/src/app/kvm/components/KVMHeaderForms/AddLxd/AddLxd.test.tsx
ui/src/app/kvm/components/KVMHeaderForms/AddLxd/AuthenticationForm/AuthenticationForm.tsx
ui/src/app/kvm/components/KVMHeaderForms/AddLxd/SelectProjectForm/SelectProjectForm.tsx
ui/src/app/kvm/components/KVMHeaderForms/AddVirsh/AddVirsh.tsx
ui/src/app/kvm/components/KVMHeaderForms/ComposeForm/InterfacesTable/InterfacesTable.test.tsx
ui/src/app/kvm/components/KVMHeaderForms/ComposeForm/InterfacesTable/InterfacesTable.tsx
ui/src/app/kvm/components/KVMHeaderForms/DeleteForm/DeleteForm.test.tsx
ui/src/app/kvm/components/KVMHeaderForms/DeleteForm/DeleteForm.tsx
ui/src/app/kvm/components/KVMHeaderForms/RefreshForm/RefreshForm.test.tsx
ui/src/app/kvm/components/KVMHeaderForms/RefreshForm/RefreshForm.tsx
ui/src/app/kvm/components/LXDVMsTable/LXDVMsTable.tsx
ui/src/app/kvm/components/LXDVMsTable/VMsTable/VMsTable.test.tsx
ui/src/app/kvm/components/LXDVMsTable/VMsTable/VMsTable.tsx
ui/src/app/kvm/hooks.tsx
ui/src/app/kvm/views/KVMList/KVMListHeader/KVMListHeader.test.tsx
ui/src/app/kvm/views/KVMList/KVMListHeader/KVMListHeader.tsx
ui/src/app/kvm/views/KVMList/LxdTable/LxdKVMHostTable/LxdKVMHostTable.test.tsx
ui/src/app/kvm/views/KVMList/LxdTable/LxdKVMHostTable/LxdKVMHostTable.tsx
ui/src/app/kvm/views/LXDClusterDetails/LXDClusterDetailsHeader/LXDClusterDetailsHeader.tsx
ui/src/app/kvm/views/LXDClusterDetails/LXDClusterHosts/LXDClusterHosts.tsx
ui/src/app/kvm/views/LXDClusterDetails/LXDClusterSettings/LXDClusterSettings.tsx
ui/src/app/kvm/views/LXDClusterDetails/LXDClusterVMs/LXDClusterVMs.tsx
ui/src/app/kvm/views/LXDSingleDetails/LXDSingleDetailsHeader/LXDSingleDetailsHeader.tsx
ui/src/app/kvm/views/LXDSingleDetails/LXDSingleSettings/DangerZoneCard/DangerZoneCard.tsx
ui/src/app/kvm/views/LXDSingleDetails/LXDSingleSettings/LXDSingleSettings.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/DeployForm/DeployForm.test.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.test.tsx

- Update the host labels from "VM host" to "KVM host".
- This could probably just have a code review, but you could have a poke around the LXD area to make sure everything says "KVM host" instead of "VM host".
Fixes: canonical-web-and-design/app-tribe#506.

feat(ui): change "VM host" to "KVM host"

---

ui/src/app/kvm/views/LXDClusterDetails/LXDClusterDetails.test.tsx
ui/src/app/kvm/views/LXDClusterDetails/LXDClusterDetails.tsx

- Display a 404 message when a KVM host is not found.
- Visit a URL for a KVM host in a cluster that does not exist e.g. /MAAS/r/kvm/lxd/cluster/[valid-cluster-id]/vms/999
- You should see a "not found" message.
Fixes: #3265.

fix(ui): display a 404 message when a KVM host is not found

---

shared/src/components/Header/Header.tsx
shared/src/components/Header/__snapshots__/Header.test.tsx.snap

- make logout link accessible via keyboard (ideally the `a` tag should be replaced with a `button`, but this works as an incremental improvement and is valid HTML)
https://user-images.githubusercontent.com/7452681/141143566-e817c3a9-9993-4e4f-801b-9357bfef9c18.mp4
https://user-images.githubusercontent.com/7452681/141143578-4758dce6-caf4-45ae-9cca-b274f81be338.mp4 …

make logout link accessible via keyboard

---

ui/src/app/zones/views/ZonesList/ZonesListHeader/ZonesListTitle/ZonesListTitle.tsx

- enlarge Availability zones tooltip
- make it accessible via keyboard
- go to `/MAAS/r/zones` and make sure all looks correct
Fixes: # . …

enlarge Availability zones tooltip

---

ui/src/app/settings/views/Users/UsersList/UsersList.tsx
ui/src/app/settings/views/Users/UsersList/_index.scss

- fix Users table email truncation issue
- enlarge table email column
- add break-word to email
- Go to `MAAS/r/settings/users` and make sure emails wrap to multiple lines and are displayed in full
Fixes: # .
In general, please propose fixes against *master* rather than …

fix Users table email truncation

---

ui/src/app/domains/views/DomainDetails/ResourceRecords/ResourceRecords.tsx
ui/src/app/domains/views/DomainsList/DomainsTable/DomainsTable.tsx

- fix spaced out dns tables
Fixes: # .
In general, please propose fixes against *master* rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. Please apply backport labels to the PR (e.g. "Backport 2.7") for the …

fix spaced out dns tables

---

legacy/src/app/factories/spaces.js
legacy/src/app/factories/tests/test_spaces.js

- Handle deleting a space when the space is in edit mode.
- Click 'Subnets' in the header.
- Change the grouping to 'Spaces'.
- Use the take action menu to add a space.
- Click on the space you created.
- In the space summary click 'Edit'.
- In the header click 'Delete space' and then confirm.
- You should be taken back to the subnets list and the space …

fix(legacy): fix deleting a space when the edit form is open

---

ui/src/app/devices/views/DeviceDetails/DeviceConfiguration/DeviceConfiguration.tsx
ui/src/app/devices/views/DeviceDetails/DeviceConfiguration/index.ts
ui/src/app/devices/views/DeviceDetails/DeviceDetails.tsx
ui/src/app/devices/views/DeviceDetails/DeviceNetwork/DeviceNetwork.tsx
ui/src/app/devices/views/DeviceDetails/DeviceNetwork/index.ts
ui/src/app/devices/views/DeviceDetails/DeviceSummary/DeviceSummary.tsx
ui/src/app/devices/views/DeviceDetails/DeviceSummary/index.ts
ui/src/app/devices/views/DeviceDetails/index.ts
ui/src/app/devices/views/DeviceList/DeviceList.tsx
ui/src/app/devices/views/DeviceList/index.ts
ui/src/app/devices/views/Devices.tsx

- Added placeholder components for the device list and each device details tab
- Navigate to `/MAAS/r/devices` and check that a list of devices is fetched and shown
- Check that you can click on the device names and be taken to the correct urls
Fixes canonical-web-and-design/app-tribe#517

feat(ui): add placeholder device view components

---

ui/src/app/store/device/types/base.ts
ui/src/app/store/device/types/index.ts
ui/src/app/store/device/utils.test.ts
ui/src/app/store/device/utils.ts
ui/src/testing/factories/index.ts
ui/src/testing/factories/nodes.ts

- Added a util for determining whether a device is `BaseDevice` or `DeviceDetails` type
- Added test factories for `DeviceDetails` and `DeviceNetworkInterface`
- N/A
Fixes canonical-web-and-design/app-tribe#515

feat(ui): add util for determining whether device is BaseDevice or DeviceDetails type

---

eslint/common.js
integration/.eslintrc.js
root/.eslintrc
shared/.eslintrc.json
ui/.eslintrc.js

- create common eslint configuration files that can be shared across workspaces
Fixes: # .
In general, please propose fixes against *master* rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. Please apply backport labels to …

add common eslint config

---

integration/cypress/integration/login/login.spec.ts
integration/cypress/support/index.js
integration/package.json
shared/src/components/Header/Header.tsx
shared/src/components/Header/__snapshots__/Header.test.tsx.snap
ui/src/app/base/components/Login/Login.tsx
yarn.lock

- Add [cypress axe](https://github.com/component-driven/cypress-axe)
- improve login page accessibility
- fix accessibility issues
- add cypress-axe a11y violations test
Fixes: # .
In general, please propose fixes against *master* rather than release branches …

Fix login page a11y issues, add cypress-axe

---

integration/cypress/tsconfig.json
ui/src/app/domains/views/DomainDetails/ResourceRecords/ResourceRecords.test.tsx
ui/src/app/domains/views/DomainDetails/ResourceRecords/ResourceRecords.tsx

- add spinner for domain resources loading state
- add cypress-axe types
- go to `/MAAS/r/domains`
- select a domain from the list that contains some records
- verify the loading spinner has been shown
Fixes: # .
In general, please propose fixes against *master* rather than …

add loading spinner for domain resources loading state

---

ui/src/app/machines/views/MachineList/_index.scss

- remove redundant whitespace from tooltip
- set whitespace to `normal` (tooltip white space setting was conflicting with p-list)
- fix works on both Firefox and Chrome
Fixes: # .
In general, please propose fixes against *master* rather than release branches …

remove redundant whitespace from tooltip

---

root/src/index.ejs

- add missing html lang attribute that causes accessibility test failure
Fixes: #3305 .
In general, please propose fixes against *master* rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. Please apply backport labels to the …

add missing html lang attribute

---

ui/src/app/base/components/ModelListSubtitle/ModelListSubtitle.test.tsx
ui/src/app/base/components/ModelListSubtitle/ModelListSubtitle.tsx
ui/src/app/base/components/ModelListSubtitle/index.ts
ui/src/app/devices/components/DeviceHeaderForms/AddDeviceForm/AddDeviceForm.tsx
ui/src/app/devices/components/DeviceHeaderForms/AddDeviceForm/index.ts
ui/src/app/devices/components/DeviceHeaderForms/DeviceHeaderForms.test.tsx
ui/src/app/devices/components/DeviceHeaderForms/DeviceHeaderForms.tsx
ui/src/app/devices/components/DeviceHeaderForms/index.ts
ui/src/app/devices/constants.ts
ui/src/app/devices/types.ts
ui/src/app/devices/utils.ts
ui/src/app/devices/views/DeviceList/DeviceList.tsx
ui/src/app/devices/views/DeviceList/DeviceListHeader/DeviceListHeader.test.tsx
ui/src/app/devices/views/DeviceList/DeviceListHeader/DeviceListHeader.tsx
ui/src/app/devices/views/DeviceList/DeviceListHeader/index.ts
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/FieldlessForm/FieldlessForm.tsx
ui/src/app/machines/components/TakeActionMenu/TakeActionMenu.tsx
ui/src/app/machines/utils.ts
ui/src/app/machines/views/MachineList/MachineListHeader/MachineListHeader.tsx
ui/src/app/store/utils/index.ts
ui/src/app/store/utils/node.ts

- Built initial devices list header component
- Set up constants and types for the device header forms
- Add placeholder Add device form
- Extracted machine list header subtitle into `ModelListSubtitle` component and reused in the device list header
- Moved `getActionTitle` machine util into a common node util folder and reused in device list header …

feat(ui): build initial devices list header component

---

ui/src/app/dashboard/views/DiscoveryAddForm/DiscoveryAddFormFields/DiscoveryAddFormFields.tsx
ui/src/app/devices/views/DeviceList/DeviceList.tsx
ui/src/app/devices/views/DeviceList/DeviceListTable/DeviceListTable.test.tsx
ui/src/app/devices/views/DeviceList/DeviceListTable/DeviceListTable.tsx
ui/src/app/devices/views/DeviceList/DeviceListTable/_index.scss
ui/src/app/devices/views/DeviceList/DeviceListTable/index.ts
ui/src/app/store/device/utils.test.ts
ui/src/app/store/device/utils.ts
ui/src/scss/index.scss

- Built device list table, without sorting or selected state
- I've updated the design slightly from the legacy version so it's a bit more aligned with the machine list (used double rows, added tags and zone data)
- Go to /MAAS/r/devices
- Check that a table of devices renders and the data is correct
- Check that you can click a …

feat(ui) build device list table

---

ui/src/app/devices/views/DeviceList/DeviceListTable/DeviceListTable.test.tsx
ui/src/app/devices/views/DeviceList/DeviceListTable/DeviceListTable.tsx

- Added sorting to devices list
- Navigate to /MAAS/r/devices and check that the table is sorted by FQDN by default
- Click on the table headers and check that sorting works as expected
Fixes canonical-web-and-design/app-squad#528

feat(ui): add sorting to devices list

---

ui/src/app/devices/views/DeviceDetails/DeviceDetails.tsx
ui/src/app/devices/views/DeviceDetails/DeviceDetailsHeader/DeviceDetailsHeader.test.tsx
ui/src/app/devices/views/DeviceDetails/DeviceDetailsHeader/DeviceDetailsHeader.tsx
ui/src/app/devices/views/DeviceDetails/DeviceDetailsHeader/index.ts

- Built initial `DeviceDetailsHeader` component
- Go to /MAAS/r/devices and click on device name
- Check that you are taken to the device details page and you can navigate between the tabs properly.
- Note that the subtitle will always show a spinner as we don't currently have the `device.get` action implemented, so devices in …

feat(ui): build device details header component

---

ui/src/app/machines/views/MachineDetails/MachineNetwork/DHCPTable/DHCPTable.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/DHCPTable/DHCPTable.tsx

- display loading spinner for dhcp snippets within the table
- go to Machines/Network, e.g. /MAAS/r/machine/7c7ya3/network 
- make sure the loading text and spinner are displayed within the table during loading
Fixes: # . …

improve loading state for dhcp snippets

---

root/src/index.ejs
root/src/scss/base.scss
ui/src/app/base/components/SectionHeader/SectionHeader.tsx

fix loading title inconsistency
- add aria-label for improved accessibility (hiding multiple elements in the spinner that are irrelevant)
- Go to the login page
- Make sure there are no inconsistencies in the Loading component as described in https://github.com/canonical-web-and-design/maas-ui/issues/3274 throughout the loading …

fix loading title inconsistency

---

ui/src/app/base/components/FilterAccordion/FilterAccordion.tsx
ui/src/app/dashboard/views/DiscoveriesList/DiscoveriesFilterAccordion/DiscoveriesFilterAccordion.test.tsx
ui/src/app/dashboard/views/DiscoveriesList/DiscoveriesFilterAccordion/DiscoveriesFilterAccordion.tsx
ui/src/app/dashboard/views/DiscoveriesList/DiscoveriesList.test.tsx
ui/src/app/dashboard/views/DiscoveriesList/DiscoveriesList.tsx
ui/src/app/machines/views/MachineList/MachineList.test.tsx
ui/src/app/machines/views/MachineList/MachineListControls/MachinesFilterAccordion/MachinesFilterAccordion.test.tsx
ui/src/app/machines/views/MachineList/MachineListControls/MachinesFilterAccordion/MachinesFilterAccordion.tsx
ui/src/app/machines/views/MachineList/MachineListTable/MachineListTable.tsx

- set machines filter to disabled on loading
- display loading spinner within machines and discovery lists
- go to machines list and verify that filters button is disabled and loading text displayed when loading
Fixes: # . …

set machines filter to disabled and display spinner within table on loading

---

ui/src/app/dashboard/views/DiscoveryAddForm/DiscoveryAddFormFields/DiscoveryAddFormFields.tsx
ui/src/app/devices/components/DeviceHeaderForms/AddDeviceForm/AddDeviceForm.test.tsx
ui/src/app/devices/components/DeviceHeaderForms/AddDeviceForm/AddDeviceForm.tsx
ui/src/app/devices/components/DeviceHeaderForms/AddDeviceForm/AddDeviceInterfaces/AddDeviceInterfaces.test.tsx
ui/src/app/devices/components/DeviceHeaderForms/AddDeviceForm/AddDeviceInterfaces/AddDeviceInterfaces.tsx
ui/src/app/devices/components/DeviceHeaderForms/AddDeviceForm/AddDeviceInterfaces/index.ts
ui/src/app/devices/components/DeviceHeaderForms/AddDeviceForm/types.ts
ui/src/app/devices/components/DeviceHeaderForms/DeviceHeaderForms.test.tsx
ui/src/app/store/device/types/actions.ts

- Built "Add device" form in the device list header
- It's a little different from the legacy version - I've added a zone select and a name field for each interface. There's more fields we *could* add, but those two stood out as being particularly weird to be omitted. 
- Go to /MAAS/r/devices and click "Add device"
- Check that …

feat(ui): build "Add device" form

---

ui/src/app/devices/components/DeviceHeaderForms/AddDeviceForm/AddDeviceForm.tsx
ui/src/app/devices/components/DeviceHeaderForms/AddDeviceForm/AddDeviceInterfaces/AddDeviceInterfaces.tsx
ui/src/app/devices/components/DeviceHeaderForms/AddDeviceForm/AddDeviceInterfaces/_index.scss
ui/src/scss/_patterns_forms.scss
ui/src/scss/index.scss

- Made "Add device" interfaces table responsive
- Go to /MAAS/r/devices and click "Add device"
- Add some interfaces and resize the viewport to be smaller
- Check that the table looks alright for different viewport sizes and number of interfaces
Fixes canonical-web-and-design/app-tribe#555

feat(ui): make add device interfaces table responsive

---

ui/src/app/devices/views/DeviceList/DeviceList.tsx
ui/src/app/devices/views/DeviceList/DeviceListHeader/DeviceListHeader.test.tsx
ui/src/app/devices/views/DeviceList/DeviceListHeader/DeviceListHeader.tsx
ui/src/app/devices/views/DeviceList/DeviceListTable/DeviceListTable.test.tsx
ui/src/app/devices/views/DeviceList/DeviceListTable/DeviceListTable.tsx
ui/src/app/store/device/actions.test.ts
ui/src/app/store/device/slice.ts

- Added `setSelected` action to device slice
- Added checkboxes to device list
- Go to /MAAS/r/devices and check that the "Add device" button is enabled and the "Take action" button is disabled
- Check some checkboxes
- Check that the header subtitle updates with the selected count, the "Add device" button becomes disabled and …

feat(ui): add checkboxes to device list

---

ui/src/app/base/components/DebounceSearchBox/DebounceSearchBox.test.tsx
ui/src/app/base/components/DebounceSearchBox/DebounceSearchBox.tsx
ui/src/app/base/components/DebounceSearchBox/_index.scss
ui/src/app/base/components/DebounceSearchBox/index.ts
ui/src/app/devices/views/DeviceList/DeviceList.tsx
ui/src/app/devices/views/DeviceList/DeviceListControls/DeviceListControls.tsx
ui/src/app/devices/views/DeviceList/DeviceListHeader/DeviceListHeader.test.tsx
ui/src/app/devices/views/DeviceList/DeviceListHeader/DeviceListHeader.tsx
ui/src/app/devices/views/DeviceList/DeviceListTable/DeviceListTable.tsx
ui/src/app/machines/views/MachineList/MachineList.tsx
ui/src/app/machines/views/MachineList/MachineListControls/MachineListControls.test.tsx
ui/src/app/machines/views/MachineList/MachineListControls/MachineListControls.tsx
ui/src/scss/index.scss

- Create `DebounceSearchBox` component for use in the node list pages (or anywhere that needs a searchbox that runs a function after a bit of time)
- Go to /MAAS/r/devices and type into the search box
- Check that the devices get filtered after a second
- Select a device and check that the subtitle turns into a link that filters …

feat(ui): build devices searchbox

---

ui/src/app/base/components/IpAssignmentSelect/IpAssignmentSelect.test.tsx
ui/src/app/base/components/IpAssignmentSelect/IpAssignmentSelect.tsx
ui/src/app/base/components/IpAssignmentSelect/index.ts
ui/src/app/dashboard/views/DiscoveryAddForm/DiscoveryAddFormFields/DiscoveryAddFormFields.tsx
ui/src/app/devices/components/DeviceHeaderForms/AddDeviceForm/AddDeviceInterfaces/AddDeviceInterfaces.tsx

- Created `IpAssignmentSelect` component and used in the add discovery and device forms
- Check that you can still add a discovery and device as before, using the IP assignment select
Fixes canonical-web-and-design/app-tribe#554

feat(ui): build IP assignment select component

---

ui/src/app/base/components/DomainSelect/DomainSelect.tsx
ui/src/app/base/components/NodeName/NodeName.test.tsx
ui/src/app/base/components/NodeName/NodeName.tsx
ui/src/app/base/components/NodeName/NodeNameFields/NodeNameFields.test.tsx
ui/src/app/base/components/NodeName/NodeNameFields/NodeNameFields.tsx
ui/src/app/base/components/NodeName/NodeNameFields/__snapshots__/NodeNameFields.test.tsx.snap
ui/src/app/base/components/NodeName/NodeNameFields/index.ts
ui/src/app/base/components/NodeName/__snapshots__/NodeName.test.tsx.snap
ui/src/app/base/components/NodeName/_index.scss
ui/src/app/base/components/NodeName/index.ts
ui/src/app/base/hooks.test.tsx
ui/src/app/base/hooks.ts
ui/src/app/machines/views/MachineDetails/MachineConfiguration/MachineForm/MachineForm.tsx
ui/src/app/machines/views/MachineDetails/MachineConfiguration/PowerForm/PowerForm.tsx
ui/src/app/machines/views/MachineDetails/MachineConfiguration/PowerForm/PowerFormFields/PowerFormFields.tsx
ui/src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.test.tsx
ui/src/app/machines/views/MachineDetails/MachineHeader/MachineName/MachineName.test.tsx
ui/src/app/machines/views/MachineDetails/MachineHeader/MachineName/MachineName.tsx
ui/src/app/machines/views/MachineDetails/MachineHeader/MachineNameFields/index.ts
ui/src/app/machines/views/MachineDetails/MachineStorage/StorageNotifications/StorageNotifications.tsx
ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/DetailsCard/DetailsCard.tsx
ui/src/app/machines/views/MachineDetails/MachineSummary/SummaryNotifications/SummaryNotifications.tsx
ui/src/app/store/machine/utils/hooks.test.tsx
ui/src/app/store/machine/utils/hooks.ts
ui/src/app/store/machine/utils/index.ts
ui/src/scss/index.scss

- Update the machine name for to be reusable by devices.
- Go to the details page for a machine.
- Click on the name in the header.
- Enter a new name and domain and submit the form.
- The form should close and the machine's name and domain should update.
Fixes: canonical-web-and-design/app-tribe#553.

feat(ui): make the machine name form reusable

---

ui/src/app/App.tsx
ui/src/app/base/sagas/http.test.ts
ui/src/app/base/sagas/http.ts

- display loading consistently until user data has fully loaded
- dispatch `status/websocketConnect` from `loginSaga` and `externalLoginSaga`
- display loading consistently until logout has finished
- do not dispatch `status/websocketDisconnect` separately from the component - it already happens in the `logoutSaga` https://github.com/canonical-web-and-design/maas-ui/blob/c8c0b3f596e2e9fe4bf2dca9ce38e466c5e9da90/ui/src/app/base/sagas/http.ts#L312-L325
The loading process consists of multiple actions (REST API, WebSocket) which are dispatched from react components which re-render before dispatching the next action. This makes the UI flash between Login/Error components when the App is in the intermediary state (authenticated, but not yet connected).
*User is authenticated, but …

fix(ui): fix flashing error messages on login/logout

---

ui/src/app/utils/breakLines.test.ts
ui/src/app/utils/breakLines.ts

- fix Uncaught Type error for null machine `status_message` 
- fix breakLines behaviour for null text value
https://pastebin.canonical.com/p/9XMPk5xQkP/
https://pastebin.canonical.com/p/tmF4SwWdbc/
- if the machine on http://bolla.internal:5240/MAAS/r/ is still in the same state state that causes the UI to break - verify that the error no longer occurs
- otherwise, manually add/update a machine with the state below (`"status_message": null,`) to verify there's no runtime error
[Example machine that's causing the runtime error (text is null)](https://pastebin.canonical.com/p/GH56Vpk2jq/)

fix(ui): handle machine null status_message

---

ui/src/app/base/components/DomainSelect/DomainSelect.tsx
ui/src/app/base/components/NodeName/NodeNameFields/NodeNameFields.tsx
ui/src/app/base/components/NodeName/NodeNameFields/__snapshots__/NodeNameFields.test.tsx.snap
ui/src/app/base/components/NodeName/_index.scss
ui/src/app/devices/views/DeviceDetails/DeviceDetailsHeader/DeviceDetailsHeader.test.tsx
ui/src/app/devices/views/DeviceDetails/DeviceDetailsHeader/DeviceDetailsHeader.tsx
ui/src/app/devices/views/DeviceDetails/DeviceDetailsHeader/DeviceName/DeviceName.test.tsx
ui/src/app/devices/views/DeviceDetails/DeviceDetailsHeader/DeviceName/DeviceName.tsx
ui/src/app/devices/views/DeviceDetails/DeviceDetailsHeader/DeviceName/index.ts

- Add the device name form to the device details header.
- Go to details page for a device.
- Click the device name in the header and the form should appear.
- Change the name and domain and submit.
- The device name should update.
Fixes: canonical-web-and-design/app-tribe#557.

feat(ui): add the device name form

---

ui/src/app/machines/views/MachineList/MachineListTable/StatusColumn/StatusColumn.tsx
ui/src/app/store/machine/types/base.ts
ui/src/app/store/types/node.ts

- Updated `BaseNode` type to include the possibility of `status_message: null`
- Fixed machine status column using the updated type
- N/A
Fixes #3365

fix(ui): update base node status_message type

---

ui/src/app/devices/components/DeviceHeaderForms/AddDeviceForm/AddDeviceInterfaces/AddDeviceInterfaces.tsx
ui/src/app/devices/views/DeviceDetails/DeviceDetails.test.tsx
ui/src/app/devices/views/DeviceDetails/DeviceDetails.tsx

- Set active device when viewing device details
- Go to /MAAS/r/devices
- Click on a device, and check that a loading spinner shows in the header initially before disappearing
- Check in Redux DevTools that the device was successfully set as active
Fixes canonical-web-and-design/app-tribe#558

feat(ui): set active device when viewing details

---

ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AvailableStorageTable.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/CacheSetsTable/CacheSetsTable.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/DatastoresTable/DatastoresTable.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/FilesystemsTable/FilesystemsTable.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/MachineStorage.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/UsedStorageTable/UsedStorageTable.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/_index.scss
ui/src/scss/_patterns_tables.scss
ui/src/scss/_utilities.scss
ui/src/scss/_vanilla-overrides.scss
ui/src/scss/index.scss

- use the [responsive table pattern](https://vanillaframework.io/docs/base/tables#responsive) (`.p-table--mobile-card`) for tables in the Machine Storage section
- remove unsupported `u-align--center` (only `u-align--right` works by default in mobile card pattern, otherwise there are alignement issues on mobile)
- add vanilla overrides for p-table--mobile-card to accomodate for negative margin that's caused by our altered defaults in `_settings.scss` (`$multi: 1`)
- add extra margin to machine-storage__subtitle for better spacing
- add `.u-break-spaces` utility class to allow wrapping text in tables to the next line where needed
- opened issues on Vanilla framework related to workarounds I had to use:
- https://github.com/canonical-web-and-design/vanilla-framework/issues/4162
- …

fix(ui): fix machine storage tables on small screens

---

integration/README.md

- update deprecated homebrew install syntax 
https://formulae.brew.sh/cask/xquartz

update integration README.md

---

ui/src/app/devices/views/DeviceDetails/DeviceDetails.tsx
ui/src/app/devices/views/DeviceDetails/DeviceNetwork/DeviceNetwork.test.tsx
ui/src/app/devices/views/DeviceDetails/DeviceNetwork/DeviceNetwork.tsx

- Add the DHCP table
- Setup the network state.
- Go to the /r/devices and click on a device.
- In the network tab you should see a DHCP table with no snippets.
- Go to the DHCP settings and add a snippet to the device you visited.
- Go back to the network tab for the device and you should see the snippet in the table.
Fixes: …

feat: add the DHCP table to the devices network tab

---

ui/src/app/devices/views/DeviceDetails/DeviceNetwork/DeviceNetwork.tsx

- Add the actions row to the device network tab.
- Go to the network tab for a device.
- You should see a button to add an interface.
- Clicking the button should show some placeholder text.
Fixes: canonical-web-and-design/app-tribe#567.

feat(ui): add the device network actions row

---

ui/src/app/base/components/ActionForm/ActionForm.test.tsx
ui/src/app/base/components/ActionForm/ActionForm.tsx
ui/src/app/base/hooks/base.test.tsx
ui/src/app/base/hooks/base.ts
ui/src/app/kvm/components/KVMHeaderForms/ComposeForm/ComposeForm.tsx
ui/src/app/kvm/components/KVMHeaderForms/DeleteForm/DeleteForm.test.tsx
ui/src/app/kvm/components/KVMHeaderForms/DeleteForm/DeleteForm.tsx
ui/src/app/kvm/components/KVMHeaderForms/RefreshForm/RefreshForm.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/ActionFormWrapper.test.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/ActionFormWrapper.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/CloneForm/CloneForm.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/CommissionForm/CommissionForm.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/DeployForm/DeployForm.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/FieldlessForm/FieldlessForm.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/MarkBrokenForm/MarkBrokenForm.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/OverrideTestForm/OverrideTestForm.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/ReleaseForm/ReleaseForm.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/SetPoolForm/SetPoolForm.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/SetZoneForm/SetZoneForm.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagForm.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TestForm/TestForm.tsx
ui/src/app/machines/types.ts

- Removed some workarounds in `ActionForm` to get the machine batched actions to work. Now the form remains rendered if an action has started as opposed to being 100% locked to the processing machines in state. This change could also lead us to better handle errors returned from the API, like with the clone form that has a results page that lists the different errors for the different machines.
- Updated `useProcessing` hook to return completed state and added tests. Note we don't actually use the `onComplete` or `onError` functions in the hook anymore, but it could still be useful so I've kept them in.
- [A development …

refactor(ui): improve action form composability

---

ui/src/app/base/components/node/NodeActionFormWrapper/NodeActionFormWrapper.test.tsx
ui/src/app/base/components/node/NodeActionFormWrapper/NodeActionFormWrapper.tsx
ui/src/app/base/components/node/NodeActionFormWrapper/index.ts
ui/src/app/devices/components/DeviceHeaderForms/DeviceActionFormWrapper/DeviceActionFormWrapper.test.tsx
ui/src/app/devices/components/DeviceHeaderForms/DeviceActionFormWrapper/DeviceActionFormWrapper.tsx
ui/src/app/devices/components/DeviceHeaderForms/DeviceActionFormWrapper/index.ts
ui/src/app/devices/components/DeviceHeaderForms/DeviceHeaderForms.tsx
ui/src/app/devices/views/DeviceDetails/DeviceDetailsHeader/DeviceDetailsHeader.tsx
ui/src/app/devices/views/DeviceList/DeviceListHeader/DeviceListHeader.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/ActionFormWrapper.tsx
ui/src/app/store/device/selectors.ts

- Refactored machine `ActionFormWrapper` to be able to be used across node types and implemented for devices
- Check that the machine action forms still work as before 
- A warning shows if not all machines can perform the action
- The form shows if they can
- Unselecting all machines closes the form
- Check that the device …

refactor(ui): make ActionFormWrapper reusable across node types

---

ui/src/app/store/device/reducers.test.ts
ui/src/app/store/device/slice.ts

- Updated the device slice to handle creating/deleting statuses
- Go to /MAAS/r/devices and create a couple of devices
- Check that the Redux store is updated with a status key for each of them
- Select the newly created devices and open the Delete form
- Delete the devices and check that processing message counts down and …

fix(ui): correctly handle device create/delete notify actions

---

integration/cypress/integration/base/footer.spec.ts
integration/cypress/integration/base/header.spec.ts
integration/cypress/integration/dashboard/dashboard.spec.ts
integration/cypress/integration/domains/list.spec.ts
integration/cypress/integration/images/list.spec.ts
integration/cypress/integration/kvm/list.spec.ts
integration/cypress/integration/legacy/controllers.spec.ts
integration/cypress/integration/legacy/devices.spec.ts
integration/cypress/integration/legacy/subnets.spec.ts
integration/cypress/integration/login/login.spec.ts
integration/cypress/integration/machines/add.spec.ts
integration/cypress/integration/machines/list.spec.ts
integration/cypress/integration/pools/list.spec.ts
integration/cypress/integration/preferences/base.spec.ts
integration/cypress/integration/settings/base.spec.ts
integration/cypress/integration/settings/users/add.spec.ts
integration/cypress/integration/settings/users/list.spec.ts
integration/cypress/integration/zones/list.spec.ts

- remove redundant `clearCookies` in `afterEach` hook
- initally I planned to move state reset from `afterEach` to `beforeEach` hook to follow best practices:
**[Resetting the state in afterEach hook is an anti-pattern](https://docs.cypress.io/guides/references/best-practices#Using-after-or-afterEach-hooks)**
- [cypress clears cookies automatically before each test](https://docs.cypress.io/api/commands/clearcookies) - so there's no need to do this manually

remove redundant clearCookies in afterEach hook

---

ui/src/app/base/components/node/networking/SubnetColumn/SubnetColumn.tsx
ui/src/app/devices/views/DeviceDetails/DeviceNetwork/DeviceNetwork.tsx
ui/src/app/devices/views/DeviceDetails/DeviceNetwork/DeviceNetworkTable/DeviceNetworkTable.test.tsx
ui/src/app/devices/views/DeviceDetails/DeviceNetwork/DeviceNetworkTable/DeviceNetworkTable.tsx
ui/src/app/devices/views/DeviceDetails/DeviceNetwork/DeviceNetworkTable/_index.scss
ui/src/app/devices/views/DeviceDetails/DeviceNetwork/DeviceNetworkTable/index.ts
ui/src/app/machines/views/MachineDetails/MachineNetwork/InterfaceFormTable/InterfaceFormTable.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTable.tsx
ui/src/scss/index.scss

- Add a table to display the interfaces for a device.
- Visit the network tab for a device.
- You should see the interfaces listed and the data should be the same as the legacy version (note: there are a couple of additions to make it consistent with what we show for machines).
Fixes: canonical-web-and-design/app-tribe#574.

feat(ui): display the device interfaces

---

ui/src/app/kvm/components/KVMHeaderForms/ComposeForm/ComposeForm.tsx
ui/src/app/kvm/components/KVMHeaderForms/DeleteForm/DeleteForm.tsx
ui/src/app/kvm/components/KVMHeaderForms/RefreshForm/RefreshForm.tsx

- Added missing "Cancel" buttons in KVM forms
- Go to a KVM's details page and open each of the "Compose", "Refresh" and "Delete" forms
- There should be a cancel button that closes the form for each of them
Fixes #3415

fix(ui): re-add removed KVM form cancel buttons

---

ui/src/app/devices/views/DeviceDetails/DeviceNetwork/AddInterface/AddInterface.test.tsx
ui/src/app/devices/views/DeviceDetails/DeviceNetwork/AddInterface/AddInterface.tsx
ui/src/app/devices/views/DeviceDetails/DeviceNetwork/AddInterface/AddInterfaceFields/AddInterfaceFields.test.tsx
ui/src/app/devices/views/DeviceDetails/DeviceNetwork/AddInterface/AddInterfaceFields/AddInterfaceFields.tsx
ui/src/app/devices/views/DeviceDetails/DeviceNetwork/AddInterface/AddInterfaceFields/index.ts
ui/src/app/devices/views/DeviceDetails/DeviceNetwork/AddInterface/index.ts
ui/src/app/devices/views/DeviceDetails/DeviceNetwork/DeviceNetwork.tsx

- Built "Add interface" form for devices
- Go to the network tab of a device in the React rebuild
- Click "Add interface"
- Add some valid form values and check that you can successfully add an interface
- Reopen the form, this time choose "Static" IP assignment, any subnet, then enter a bogus IP address
- The API error should …

feat(ui): build device add interface form

---

ui/src/app/devices/views/DeviceDetails/DeviceNetwork/DeviceNetworkTable/DeviceNetworkTable.tsx
ui/src/app/devices/views/DeviceDetails/DeviceNetwork/DeviceNetworkTable/RemoveInterface/RemoveInterface.test.tsx
ui/src/app/devices/views/DeviceDetails/DeviceNetwork/DeviceNetworkTable/RemoveInterface/RemoveInterface.tsx
ui/src/app/devices/views/DeviceDetails/DeviceNetwork/DeviceNetworkTable/RemoveInterface/index.ts

- Added table action menu to devices table
- Added delete device interface confirmation
- Go to the network tab for a device
- Click the action dropdown for an interface and select "Remove Physical"
- Confirm by clicking "Remove" and check that the interface is deleted successfully
Fixes canonical-web-and-design/app-tribe#542 …

feat(ui): build device delete interface form

---

integration/.gitignore
integration/README.md
integration/cypress.json
integration/package.json

- enable local cypress configuration
- remove fixed baseUrl from npm scripts
- move the default baseUrl to cypress.json
- add description to README
Fixes: #594 .

enable local cypress configuration

---

ui/src/single-spa-entry.js

- Backport the fix for loading the UI in Safari to 3.0 (3.1 PR here: https://github.com/canonical-web-and-design/maas-ui/pull/3220).
- Run the app with `yarn start, so that you are viewing the site with single-spa.
- Open the ui in Safari, it should load.
- Double check that it still works in Firefox/Chrome.
Fixes: canonical-web-and-design/maas-ui#3426.

fix(single-spa): fix maas in Safari for 3.0

---

ui/src/app/devices/views/DeviceDetails/DeviceNetwork/AddInterface/AddInterface.tsx
ui/src/app/devices/views/DeviceDetails/DeviceNetwork/AddInterface/AddInterfaceFields/index.ts
ui/src/app/devices/views/DeviceDetails/DeviceNetwork/InterfaceForm/InterfaceForm.test.tsx
ui/src/app/devices/views/DeviceDetails/DeviceNetwork/InterfaceForm/InterfaceForm.tsx
ui/src/app/devices/views/DeviceDetails/DeviceNetwork/InterfaceForm/InterfaceFormFields/InterfaceFormFields.test.tsx
ui/src/app/devices/views/DeviceDetails/DeviceNetwork/InterfaceForm/InterfaceFormFields/InterfaceFormFields.tsx
ui/src/app/devices/views/DeviceDetails/DeviceNetwork/InterfaceForm/InterfaceFormFields/index.ts
ui/src/app/devices/views/DeviceDetails/DeviceNetwork/InterfaceForm/index.ts

- Update the device interface form to be reusable for adding and editing interfaces.
- Go to /r/devices.
- Click on a device and then go to the network tab.
- You should be able to add interfaces as you could previously.
Fixes: canonical-web-and-design/app-tribe#603.

refactor(ui): make the device interface form reusable

---

.github/workflows/test.yml
.github/workflows/upload.yml

- Update Node.js in CI from v12.x to v16.x, which is required for a few failing dependency updates
- CI should pass

ci(all): use Node.js v16 in CI

---

ui/src/app/devices/views/DeviceDetails/DeviceNetwork/DeviceNetworkTable/DeviceNetworkTable.test.tsx
ui/src/app/devices/views/DeviceDetails/DeviceNetwork/DeviceNetworkTable/DeviceNetworkTable.tsx
ui/src/app/devices/views/DeviceDetails/DeviceNetwork/DeviceNetworkTable/_index.scss

- Split the ip address and mode columns in the device interfaces table.
- Go to a device's details page and click on the network tab.
- Check that the ip address and mode are in separate columns.
Fixes: canonical-web-and-design/app-tribe#605.

feat(ui): split ip address and mode column

---

ui/src/app/devices/views/DeviceDetails/DeviceNetwork/EditInterface/EditInterface.tsx
ui/src/app/devices/views/DeviceDetails/DeviceNetwork/EditInterface/EditInterfaceTable/EditInterfaceTable.test.tsx
ui/src/app/devices/views/DeviceDetails/DeviceNetwork/EditInterface/EditInterfaceTable/EditInterfaceTable.tsx
ui/src/app/devices/views/DeviceDetails/DeviceNetwork/EditInterface/EditInterfaceTable/index.ts

- Add a table to the edit interface form to display the interface's details.
- Go to a device's details.
- Click on the network tab.
- Open the row menu for an interface and click on "Edit physical".
- You should see a table above the form fields that contains the interface's details.
Fixes: canonical-web-and-design/app-tribe#604.

feat(ui): add the edit interface form table

---

legacy/package.json
legacy/webpack.dev.js
root/package.json
root/webpack.dev.js

- Followed [this migration guide](https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md) to update our webpack configs to be compatible with v4.
- Run the whole app with `yarn start`
- Check that the app runs properly, i.e. you can successfully navigate to both ui and legacy pages
- Run `yarn ui` and check …

fix(all): fix webpack-dev-server config

---

legacy/webpack.dev.js

- fix the webpack dev server websocket port
- Run the full client with `yarn start`.
- Check that you can load legacy and React urls in Firefox and Chrome.

fix(legacy): fix the webpack dev server websocket port

---

legacy/webpack.dev.js
shared/src/components/Header/Header.tsx

- Update the analytics page change events to work without a listener so that it can be used with React Router v6.
- Open `shared/src/components/Header/Header.tsx`.
- Insert `debug = false;` at line 92.
- Run the full client with `yarn start`.
- Visit `/MAAS/r/settings/configuration/general` and check that analytics is enabled.
- In your browser console run …

refactor(shared): handle page change events without a listener

---

ui/src/app/Routes.tsx
ui/src/app/dashboard/views/Dashboard.tsx
ui/src/app/devices/views/Devices.tsx
ui/src/app/images/views/Images.tsx
ui/src/app/kvm/views/KVM.tsx
ui/src/app/machines/views/MachineDetails/MachineLogs/MachineLogs.tsx
ui/src/app/zones/views/Zones.tsx

- Update the urls to map routes instead of using paths as React Router v6 doesn't support an array.
- Check that you can visit the list, details and tabs for: devices, domains, zones and kvm.
- Check that you can view the logs and events sub-tabs in machine details. 
Fixes: #3463.

refactor(ui): use a map instead of an array of paths

---

ui/src/app/base/components/PowerTypeFields/BasePowerField/BasePowerField.test.tsx
ui/src/app/base/components/PowerTypeFields/BasePowerField/BasePowerField.tsx
ui/src/app/store/general/types/base.ts
ui/src/app/store/general/types/enum.ts
ui/src/app/store/general/utils/powerTypes.ts
ui/src/app/store/types/node.ts

- Added support for `multiple_choice` power fields, which currently only exist for the `ipmi` power type
- Go to the machine list and click "Add machine"
- Change the power type to IPMI and check that you see a list of checkboxes for workaround flags
- Fill in the required fields, check some workaround flags and submit the form …

feat(ui): add support for multiple choice power fields

---

ui/src/app/Routes.tsx
ui/src/app/controllers/constants.ts
ui/src/app/controllers/types.ts
ui/src/app/controllers/urls.ts
ui/src/app/controllers/utils.ts
ui/src/app/controllers/views/ControllerList/ControllerList.test.tsx
ui/src/app/controllers/views/ControllerList/ControllerList.tsx
ui/src/app/controllers/views/ControllerList/ControllerListControls/ControllerListControls.test.tsx
ui/src/app/controllers/views/ControllerList/ControllerListControls/ControllerListControls.tsx
ui/src/app/controllers/views/ControllerList/ControllerListControls/index.ts
ui/src/app/controllers/views/ControllerList/ControllerListHeader/ControllerListHeader.test.tsx
ui/src/app/controllers/views/ControllerList/ControllerListHeader/ControllerListHeader.tsx
ui/src/app/controllers/views/ControllerList/ControllerListHeader/index.ts
ui/src/app/controllers/views/ControllerList/index.ts
ui/src/app/controllers/views/Controllers.tsx

**Note: this has all been copied and pasted from devices.**
- Set up the view for displaying a list of controllers.
- Visit /r/controllers.
- The page should load the controllers view (with no content except the search box).
Fixes: canonical-web-and-design/app-tribe#608.

feat(ui): set up controller list

---

shared/package.json
shared/setup-jest.js

- remove all remaining enzyme dependencies from maas-ui-shared
Fixes: #3460 .
In general, please propose fixes against *master* rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. Please apply backport labels …

refactor(deps): remove enzyme from maas-ui-shared

---

ui/src/__snapshots__/root-reducer.test.ts.snap
ui/src/app/base/sagas/websockets.test.ts
ui/src/app/base/sagas/websockets.ts
ui/src/app/settings/views/Configuration/CommissioningForm/CommissioningForm.test.tsx
ui/src/app/settings/views/Network/DnsForm/DnsForm.test.tsx
ui/src/app/settings/views/Network/NetworkDiscoveryForm/NetworkDiscoveryForm.test.tsx
ui/src/app/settings/views/Network/NtpForm/NtpForm.test.tsx
ui/src/app/settings/views/Network/SyslogForm/SyslogForm.test.tsx
ui/src/app/settings/views/Storage/StorageForm/StorageForm.test.tsx
ui/src/app/store/config/actions.test.ts
ui/src/app/store/config/slice.ts
ui/src/app/store/controller/actions.test.ts
ui/src/app/store/controller/reducers.test.ts
ui/src/app/store/controller/selectors.test.ts
ui/src/app/store/controller/selectors.ts
ui/src/app/store/controller/slice.ts
ui/src/app/store/controller/types/base.ts
ui/src/app/store/controller/types/enum.ts
ui/src/app/store/utils/slice.ts
ui/src/testing/factories/index.ts
ui/src/testing/factories/state.ts
ui/src/websocket-client.ts

- Add support for checking images with polling to the controllers slice.
- Add support for multiple polling events for the same endpoint to the websocket client.
Fixes: canonical-web-and-design/app-tribe#611.

feat(ui): add check_images handlers to the controller slice

---

ui/src/app/controllers/components/ControllerStatus/ControllerStatus.test.tsx
ui/src/app/controllers/components/ControllerStatus/ControllerStatus.tsx
ui/src/app/controllers/components/ControllerStatus/index.ts
ui/src/app/controllers/components/ImageStatus/ImageStatus.test.tsx
ui/src/app/controllers/components/ImageStatus/ImageStatus.tsx
ui/src/app/controllers/components/ImageStatus/index.ts
ui/src/app/controllers/views/ControllerList/ControllerListTable/ControllerListTable.tsx
ui/src/app/controllers/views/ControllerList/ControllerListTable/StatusColumn/StatusColumn.test.tsx
ui/src/app/controllers/views/ControllerList/ControllerListTable/StatusColumn/StatusColumn.tsx
ui/src/app/controllers/views/ControllerList/ControllerListTable/StatusColumn/index.ts
ui/src/app/store/controller/selectors.test.ts
ui/src/app/store/controller/selectors.ts

- Add the controller and image statuses to the controller table.
- Visit /r/controllers
- Check that there is content in the status column that matches the legacy view.
- Check that the image sync status is show in the images column.
Fixes: canonical-web-and-design/app-tribe#617.

feat(ui): add controller statuses

---

ui/src/app/controllers/components/ControllerHeaderForms/ControllerActionFormWrapper/ControllerActionFormWrapper.test.tsx
ui/src/app/controllers/components/ControllerHeaderForms/ControllerActionFormWrapper/ControllerActionFormWrapper.tsx
ui/src/app/controllers/components/ControllerHeaderForms/ControllerActionFormWrapper/index.ts
ui/src/app/controllers/components/ControllerHeaderForms/ControllerHeaderForms.test.tsx
ui/src/app/controllers/components/ControllerHeaderForms/ControllerHeaderForms.tsx
ui/src/app/controllers/components/ControllerHeaderForms/index.ts
ui/src/app/controllers/views/ControllerList/ControllerListHeader/ControllerListHeader.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/ActionFormWrapper.tsx
ui/src/app/store/utils/node/base.ts

- Add the header forms to the controller list.
- Visit /r/controllers.
- Tick some controllers and use the take action to perform actions on the controllers (except override failed testing which will be done in a followup: https://github.com/canonical-web-and-design/app-tribe/issues/618).
Fixes: canonical-web-and-design/app-tribe#613.

feat(ui): add controller header forms

---

ui/src/app/controllers/components/ControllerHeaderForms/AddController/AddController.test.tsx
ui/src/app/controllers/components/ControllerHeaderForms/AddController/AddController.tsx
ui/src/app/controllers/components/ControllerHeaderForms/AddController/index.ts
ui/src/app/controllers/components/ControllerHeaderForms/ControllerHeaderForms.test.tsx
ui/src/app/controllers/components/ControllerHeaderForms/ControllerHeaderForms.tsx
ui/src/app/store/config/selectors.test.ts
ui/src/app/store/config/selectors.ts

- Add instructions for adding a controller.
- Visit the controllers list.
- Click on "Add controller".
- You should see instructions on how to add a controller.
- Click "Close" and the header should close.
Fixes: canonical-web-and-design/app-tribe#612.

feat(ui): add controller instructions

---

integration/package.json
root/src/index.ejs
yarn.lock

- add testid to root spinner to fix flaky cypress tests
- update cypress to 9.2.1

test: add testid to root spinner

---

ui/src/app/controllers/components/ControllerHeaderForms/ControllerActionFormWrapper/ControllerActionFormWrapper.tsx

- Use the fieldless form for overriding failed testing for controllers.
- Go to the controller list and tick a machine that has failed testing.
- Use the take action menu to open the override failed testing and submit. It should work.
Fixes: https://github.com/canonical-web-and-design/app-tribe/issues/618.

feat(ui): add controller override testing

---

ui/src/app/controllers/components/ControllerStatus/ControllerStatus.test.tsx
ui/src/app/controllers/components/ControllerStatus/ControllerStatus.tsx
ui/src/app/store/service/types/base.ts
ui/src/app/store/service/types/enum.ts
ui/src/app/store/service/types/index.ts
ui/src/testing/factories/service.ts

- Added an enum for the possible service statuses
- Used enum for determining controller status tooltip
- Go to the controller list for bolla and check that the status tooltip matches what's shown in the legacy details page
Fixes #3499

fix(ui): fix incorrect status tooltip

---

ui/src/app/controllers/components/ImageStatus/ImageStatus.tsx
ui/src/app/controllers/views/ControllerList/ControllerListTable/ControllerListTable.tsx
ui/src/app/controllers/views/ControllerList/ControllerListTable/VLANsColumn/VLANsColumn.tsx
ui/src/app/controllers/views/ControllerList/ControllerListTable/_index.scss
ui/src/app/store/controller/types/index.ts

- Improved responsiveness of controller list by dropping columns at certain breakpoints. I initially tried to make the responsive card work but there's too much data to cram in, and since all of it exists in the details page I think it's fine to drop columns here.
- Go to the React controller list and check that the data is …

fix(ui): improve responsiveness of controller list

---

integration/cypress/integration/legacy/subnets.spec.ts
legacy/src/app/partials/networks-list.html
ui/src/app/Routes.tsx
ui/src/app/subnets/urls.ts
ui/src/app/subnets/views/Subnets.tsx
ui/src/app/subnets/views/SubnetsList.tsx

Subnets React page setup
- add cypress tests for the main subnets view
- based on user journeys descriptions - more in [MAAS Subnets React migration plan - User Journeys](https://docs.google.com/document/d/1Vlih_9RyfNKKwLeBXS6tnRnNZTTR1BtXG_MHHC-Bi1s/edit#heading=h.h5ndvhge2k7u)
- fix "Group by" label (`cypress-testing-library` reported this,  HTML`for` attribute was pointing to the `name` attribute instead of the `id`) - a good example how user-centric testing (and `byRole` queries) help identify UI bugs
- add "Subnets" aria-label to table - describes it for screen readers and allowis to target specifically in tests
https://docs.google.com/document/d/1Vlih_9RyfNKKwLeBXS6tnRnNZTTR1BtXG_MHHC-Bi1s/edit#heading=h.faeke7zfhcfj
- Manually enter `/MAAS/r/networks` URL and verify "Subnets" h1 …

refactor(ui): setup Subnets React page

---

integration/cypress/integration/subnets/add.spec.ts
integration/cypress/integration/utils.ts
ui/.eslintrc.js
ui/src/app/base/components/ArchitectureSelect/__snapshots__/ArchitectureSelect.test.tsx.snap
ui/src/app/base/components/DomainSelect/__snapshots__/DomainSelect.test.tsx.snap
ui/src/app/base/components/FormikField/FormikField.tsx
ui/src/app/base/components/FormikField/__snapshots__/FormikField.test.tsx.snap
ui/src/app/base/components/MinimumKernelSelect/__snapshots__/MinimumKernelSelect.test.tsx.snap
ui/src/app/base/components/NodeName/NodeNameFields/__snapshots__/NodeNameFields.test.tsx.snap
ui/src/app/base/components/ResourcePoolSelect/__snapshots__/ResourcePoolSelect.test.tsx.snap
ui/src/app/base/components/ZoneSelect/__snapshots__/ZoneSelect.test.tsx.snap
ui/src/app/store/fabric/types/actions.ts
ui/src/app/store/space/types/actions.ts
ui/src/app/subnets/enum.ts
ui/src/app/subnets/types.ts
ui/src/app/subnets/views/FormActions/FormActions.tsx
ui/src/app/subnets/views/FormActions/components/AddFabric.test.tsx
ui/src/app/subnets/views/FormActions/components/AddFabric.tsx
ui/src/app/subnets/views/FormActions/components/AddSpace.test.tsx
ui/src/app/subnets/views/FormActions/components/AddSpace.tsx
ui/src/app/subnets/views/FormActions/index.ts
ui/src/app/subnets/views/SubnetsList.tsx

migrate subnets header, add fabric, add space to React
- add aria-label to FormikField (there was no label associated with an input element)
- add cypress tests for adding a fabric (1 using legacy, 1 new UI)
- reported an issue with ContextualMenu and incorrect tab order https://github.com/canonical-web-and-design/react-components/issues/687
I made a suggestion for a few changes that's been approved by design in the [planning doc](https://docs.google.com/document/d/1Vlih_9RyfNKKwLeBXS6tnRnNZTTR1BtXG_MHHC-Bi1s/edit#heading=h.wqx5o7fcpb6i)
- Add heading to the form (closer to https://vanillaframework.io/docs/layouts/application#panels-example)
- Add auto-focus on first form input for better accessibility
- go to `MAAS/r/networks?by=fabric` to verify the new UI

refactor(ui): subnets header, add fabric, add space

---

ui/src/app/Routes.tsx
ui/src/app/base/hooks/urls.test.tsx
ui/src/app/controllers/views/ControllerList/ControllerList.test.tsx
ui/src/app/controllers/views/Controllers.tsx
ui/src/app/dashboard/views/Dashboard.tsx
ui/src/app/devices/views/DeviceDetails/DeviceDetails.tsx
ui/src/app/devices/views/DeviceList/DeviceList.test.tsx
ui/src/app/devices/views/Devices.tsx
ui/src/app/domains/views/Domains.tsx
ui/src/app/domains/views/DomainsList/DomainsList.tsx
ui/src/app/images/views/Images.tsx
ui/src/app/intro/views/Intro.tsx
ui/src/app/kvm/views/KVM.tsx
ui/src/app/kvm/views/LXDClusterDetails/LXDClusterDetails.tsx
ui/src/app/kvm/views/LXDSingleDetails/LXDSingleDetails.tsx
ui/src/app/kvm/views/VirshDetails/VirshDetails.tsx
ui/src/app/machines/views/MachineDetails/MachineCommissioning/MachineCommissioning.test.tsx
ui/src/app/machines/views/MachineDetails/MachineDetails.tsx
ui/src/app/machines/views/MachineDetails/MachineLogs/MachineLogs.tsx
ui/src/app/machines/views/MachineDetails/MachineTests/MachineTests.test.tsx
ui/src/app/machines/views/MachineDetails/MachineTests/MachineTestsDetails/MachineTestsDetails.test.tsx
ui/src/app/machines/views/Machines.test.tsx
ui/src/app/machines/views/Machines.tsx
ui/src/app/settings/components/Routes/Routes.tsx
ui/src/app/settings/views/Scripts/ScriptsUpload/ScriptsUpload.test.tsx
ui/src/app/zones/views/Zones.tsx

- Update the routes to wrap the content in a `component` prop.
- Load the UI and have a poke around the React pages. They should load as expected.
Fixes: #3507.

refactor(ui): wrap routes in component prop

---

ui/src/__snapshots__/root-reducer.test.ts.snap
ui/src/app/store/fabric/actions.test.ts
ui/src/app/store/fabric/reducers.test.ts
ui/src/app/store/fabric/selectors.test.ts
ui/src/app/store/fabric/selectors.ts
ui/src/app/store/fabric/slice.ts
ui/src/app/store/fabric/types/base.ts
ui/src/app/store/space/actions.test.ts
ui/src/app/store/space/reducers.test.ts
ui/src/app/store/space/selectors.test.ts
ui/src/app/store/space/selectors.ts
ui/src/app/store/space/slice.ts
ui/src/app/store/space/types/base.ts
ui/src/app/store/subnet/actions.test.ts
ui/src/app/store/subnet/reducers.test.ts
ui/src/app/store/subnet/selectors.test.ts
ui/src/app/store/subnet/selectors.ts
ui/src/app/store/subnet/slice.ts
ui/src/app/store/subnet/types/base.ts
ui/src/app/store/vlan/actions.test.ts
ui/src/app/store/vlan/reducers.test.ts
ui/src/app/store/vlan/selectors.test.ts
ui/src/app/store/vlan/selectors.ts
ui/src/app/store/vlan/slice.ts
ui/src/app/store/vlan/types/base.ts
ui/src/testing/factories/state.ts

- Added `get` and `setActive` actions+reducers+selectors to fabric+space+subnet+vlan models
- N/A
Fixes canonical-web-and-design/app-tribe#635

feat(ui): add get and set_active actions to networking models

---

integration/cypress/integration/subnets/add.spec.ts
ui/src/app/base/components/FabricSelect/FabricSelect.test.tsx
ui/src/app/base/components/FabricSelect/FabricSelect.tsx
ui/src/app/base/components/SpaceSelect/SpaceSelect.test.tsx
ui/src/app/base/components/SpaceSelect/SpaceSelect.tsx
ui/src/app/base/components/SpaceSelect/index.ts
ui/src/app/store/vlan/types/actions.ts
ui/src/app/subnets/views/FormActions/FormActions.tsx
ui/src/app/subnets/views/FormActions/components/AddFabric.tsx
ui/src/app/subnets/views/FormActions/components/AddSpace.tsx
ui/src/app/subnets/views/FormActions/components/AddVlan.test.tsx
ui/src/app/subnets/views/FormActions/components/AddVlan.tsx

migrate Subnets / add VLAN to React
- add SpaceSelect component
- wrap forms in .col-6
- add cypress test
**design changes:**
- change input fields order (set VID input before Name input as it’s required)
- add help text to VID (Numeric value between 1 and 4094)
- go to `/MAAS/r/networks?by=fabric` and verify adding a VLAN works …

refactor: subnets add VLAN

---

ui/src/app/base/components/TagField/TagField.test.tsx
ui/src/app/base/components/TagField/TagField.tsx
ui/src/app/base/components/TagIdField/TagIdField.test.tsx
ui/src/app/base/components/TagIdField/TagIdField.tsx
ui/src/app/base/components/TagIdField/index.ts
ui/src/app/base/components/TagLinks/TagLinks.tsx
ui/src/app/base/components/TagNameField/TagNameField.test.tsx
ui/src/app/base/components/TagNameField/TagNameField.tsx
ui/src/app/base/components/TagNameField/index.ts
ui/src/app/devices/views/DeviceDetails/DeviceConfiguration/DeviceConfiguration.tsx
ui/src/app/devices/views/DeviceDetails/DeviceNetwork/InterfaceForm/InterfaceFormFields/InterfaceFormFields.tsx
ui/src/app/kvm/components/KVMConfigurationCard/KVMConfigurationCardFields/KVMConfigurationCardFields.tsx
ui/src/app/kvm/components/KVMHeaderForms/ComposeForm/StorageTable/StorageTable.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagFormFields/TagFormFields.tsx
ui/src/app/machines/views/MachineDetails/MachineConfiguration/MachineForm/MachineFormFields/MachineFormFields.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/AddAliasOrVlan/AddAliasOrVlanFields/AddAliasOrVlanFields.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/AddAliasOrVlan/AddAliasOrVlanFields/AddAliasOrVlanFields.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/AddInterface/AddInterface.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/BondForm/BondFormFields/BondFormFields.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/BridgeFormFields/BridgeFormFields.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/EditAliasOrVlanForm/EditAliasOrVlanForm.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/EditAliasOrVlanForm/EditAliasOrVlanForm.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/EditPhysicalForm/EditPhysicalFields/EditPhysicalFields.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AddLogicalVolume/AddLogicalVolumeFields/AddLogicalVolumeFields.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/BulkActions/CreateRaid/CreateRaidFields/CreateRaidFields.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/CreateBcache/CreateBcacheFields/CreateBcacheFields.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/EditDisk/EditDiskFields/EditDiskFields.tsx

- Create components for handling tags as ids or strings.
- Update the config forms for machines and devices to handle tag ids instead of names.
- Go to the config tab for a machine that has tags.
- You should see the tag names and clicking on a tag should take you to the search list with the tag name in the search box.
- Go back to the config tab and click …

fix(ui): handle tags in machine and device config

---

integration/cypress/integration/subnets/add.spec.ts

- fix vlan cypress test https://github.com/canonical-web-and-design/maas-ui/runs/4849631853?check_suite_focus=true
Fixes: # . …

test: fix vlan cypress test

---

ui/src/app/base/components/FilterAccordion/FilterAccordion.test.tsx
ui/src/app/base/components/FilterAccordion/FilterAccordion.tsx
ui/src/app/controllers/views/ControllerList/ControllerList.tsx
ui/src/app/dashboard/views/DiscoveriesList/DiscoveriesFilterAccordion/DiscoveriesFilterAccordion.tsx
ui/src/app/devices/views/DeviceList/DeviceListControls/DeviceFilterAccordion/DeviceFilterAccordion.test.tsx
ui/src/app/devices/views/DeviceList/DeviceListControls/DeviceFilterAccordion/DeviceFilterAccordion.tsx
ui/src/app/kvm/components/LXDHostVMs/LXDHostVMs.tsx
ui/src/app/kvm/views/LXDClusterDetails/LXDClusterHosts/LXDClusterHosts.tsx
ui/src/app/kvm/views/LXDClusterDetails/LXDClusterVMs/LXDClusterVMs.tsx
ui/src/app/machines/views/MachineList/MachineList.tsx
ui/src/app/machines/views/MachineList/MachineListControls/MachinesFilterAccordion/MachinesFilterAccordion.test.tsx
ui/src/app/machines/views/MachineList/MachineListControls/MachinesFilterAccordion/MachinesFilterAccordion.tsx
ui/src/app/store/controller/selectors.test.ts
ui/src/app/store/controller/selectors.ts
ui/src/app/store/controller/utils/search.test.ts
ui/src/app/store/controller/utils/search.ts
ui/src/app/store/device/selectors.test.ts
ui/src/app/store/device/selectors.ts
ui/src/app/store/device/utils/search.test.ts
ui/src/app/store/device/utils/search.ts
ui/src/app/store/machine/selectors.test.ts
ui/src/app/store/machine/selectors.ts
ui/src/app/store/machine/utils/search.test.ts
ui/src/app/store/machine/utils/search.ts
ui/src/app/store/pod/selectors.ts
ui/src/app/store/tag/utils.test.ts
ui/src/app/store/tag/utils.ts
ui/src/app/store/vmcluster/selectors.ts
ui/src/app/utils/search/filter-items.test.ts
ui/src/app/utils/search/filter-items.ts

- Update the node filters to handle tag ids.
- Visit the machine list and filter dropdown and click on a filter.
- The machine list should update to show the correct machines.
- Repeat the same in the device list.
- Go to a controller config tab and click on a tag.
- You should get taken to the controller list which should be …

fix(ui): fix filtering nodes by tag

---

ui/src/app/kvm/components/LXDVMsTable/VMsTable/VMsTable.test.tsx
ui/src/app/kvm/components/LXDVMsTable/VMsTable/VMsTable.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/CloneForm/CloneFormFields/SourceMachineSelect/SourceMachineSelect.test.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/CloneForm/CloneFormFields/SourceMachineSelect/SourceMachineSelect.tsx

- Update the cluster vms table and clone form source select to display tag names instead of id.
- Go to the vms tab for a LXD cluster. There should be tag names, not ids.
- Go to the machine list and tick some machines and open the clone form.
- The list of machines should display tags not tag ids.
Fixes: canonical-web-and-design/app-tribe#639.

fix(ui): fix tag names in the vms table and clone form

---

ui/src/app/store/subnet/types/base.ts
ui/src/app/store/subnet/types/enum.ts
ui/src/app/store/subnet/types/index.ts
ui/src/app/store/subnet/utils.test.ts
ui/src/app/store/subnet/utils.ts
ui/src/app/store/vlan/types/base.ts
ui/src/app/store/vlan/types/index.ts
ui/src/app/store/vlan/utils.test.ts
ui/src/app/store/vlan/utils.ts
ui/src/app/subnets/views/SubnetDetails/SubnetDetailsHeader/SubnetDetailsHeader.test.tsx
ui/src/app/subnets/views/SubnetDetails/SubnetDetailsHeader/SubnetDetailsHeader.tsx
ui/src/app/subnets/views/VLANDetails/VLANDetailsHeader/VLANDetailsHeader.test.tsx
ui/src/app/subnets/views/VLANDetails/VLANDetailsHeader/VLANDetailsHeader.tsx
ui/src/testing/factories/index.ts
ui/src/testing/factories/subnet.ts
ui/src/testing/factories/vlan.ts

- Added types and utils for subnet and VLAN details
Fixes canonical-web-and-design/app-tribe#638

feat(ui): add types and utils for detailed subnets and VLANs

---

ui/package.json
ui/src/app/base/components/FormikFormContent/FormikFormContent.tsx
yarn.lock

- add formik-devtools-extension https://www.npmjs.com/package/formik-devtools-extension
- it can make easier to debug issues with forms
- Install the extension using instructions here: https://www.npmjs.com/package/formik-devtools-extension
- open formik devtools via chrome/firefox developer tools
- Go to …

add formik-devtools-extension

---

ui/src/app/Routes.tsx
ui/src/app/machines/views/MachineList/MachineListHeader/MachineListHeader.test.tsx
ui/src/app/machines/views/MachineList/MachineListHeader/MachineListHeader.tsx
ui/src/app/machines/views/Machines.test.tsx
ui/src/app/machines/views/Machines.tsx
ui/src/app/tags/urls.ts
ui/src/app/tags/views/Tags.test.tsx
ui/src/app/tags/views/Tags.tsx
yarn.lock

- Set up the basic tags view.
- Visit the machine list.
- There should be a new tab that shows the number of tags.
- Clicking on the tab should show the tags content (just "Tags" for now).
Fixes: canonical-web-and-design/app-tribe#680.

feat(ui): add tags view

---

ui/src/__snapshots__/root-reducer.test.ts.snap
ui/src/app/store/root/types.ts
ui/src/app/store/staticroute/action.test.ts
ui/src/app/store/staticroute/index.ts
ui/src/app/store/staticroute/reducers.test.ts
ui/src/app/store/staticroute/selectors.test.ts
ui/src/app/store/staticroute/selectors.ts
ui/src/app/store/staticroute/slice.ts
ui/src/app/store/staticroute/types/actions.ts
ui/src/app/store/staticroute/types/base.ts
ui/src/app/store/staticroute/types/enum.ts
ui/src/app/store/staticroute/types/index.ts
ui/src/app/subnets/views/SubnetDetails/SubnetDetails.test.tsx
ui/src/app/subnets/views/SubnetDetails/SubnetDetails.tsx
ui/src/root-reducer.ts
ui/src/testing/factories/index.ts
ui/src/testing/factories/state.ts
ui/src/testing/factories/staticroute.ts

- Added the `staticroute` model to the React app including slice, selectors and types
- Go to a subnet's details page in React (e.g. `/MAAS/r/subnet/18`)
- Open Redux DevTools and check that static routes are fetched and added to state
Fixes canonical-web-and-design/app-tribe#679

feat(ui): add staticroute slice and selectors

---

ui/src/app/subnets/views/SpaceDetails/SpaceDetails.test.tsx
ui/src/app/subnets/views/SpaceDetails/SpaceDetails.tsx
ui/src/app/subnets/views/SpaceDetails/SpaceSummary/SpaceSummary.test.tsx
ui/src/app/subnets/views/SpaceDetails/SpaceSummary/SpaceSummary.tsx

- build subnets space summary in React
- go to space details page, e.g. `/MAAS/r/space/1` and verify information within space summary is displayed correctly
Fixes: # .
In general, please propose fixes against *master* rather than release branches (e.g. 2.7), unless the fix is …

refactor: build subnets space summary

---

integration/cypress.json
integration/cypress/integration/subnets/add.spec.ts

- remove redundant cypress test (already testing if a newly added VLAN is displayed the subnets table in the [next test](https://github.com/canonical-web-and-design/maas-ui/blob/f6eef046fd51d08f2c07ff85366daeded0e43a46/integration/cypress/integration/subnets/add.spec.ts#L94-L97))
- increase default command timeout from 4 seconds to 6 seconds to reduce flakiness …

test: remove redundant cypress test

---

ui/src/app/base/sagas/websockets.test.ts
ui/src/app/base/sagas/websockets.ts
ui/src/app/store/bootresource/actions.test.ts
ui/src/app/store/bootresource/slice.ts
ui/src/websocket-client.ts

- Update fetch and poll for bootresource to handle non-json responses.
- Click Images in the header.
- Check that the page loads and shows a list of images and there are no errors in the console.
Fixes: #3554.
https://bugs.launchpad.net/maas/+bug/1959183

fix(ui): handle non-json bootresource responses

---

ui/src/app/subnets/urls.ts
ui/src/app/subnets/views/SubnetsList/SubnetsTable/components.tsx
ui/src/app/subnets/views/SubnetsList/SubnetsTable/utils.test.tsx

- Use react-router `Link` component for subnets table routes to prevent app reload
- Go to `/MAAS/r/networks`
- Click on a few links for a fabric/VLAN/space/subnet
- Check that the app does not reload

fix(ui): fix subnets table routes

---

ui/src/app/subnets/views/VLANDetails/VLANDetails.tsx
ui/src/app/subnets/views/VLANDetails/VLANDetailsHeader/VLANDetailsHeader.test.tsx
ui/src/app/subnets/views/VLANDetails/VLANDetailsHeader/VLANDetailsHeader.tsx

- Add the VLAN title and delete button.
- Go to the React version of VLAN details, you should see a title.
- Go to a VLAN that is the default for a fabric, you should not see a delete button.
- Go to a VLAN that is not the default for a fabric, you should see a delete button.
- Log in as a non admin and go to a VLAN that is not the default for a fabric, you …

feat(ui): display the VLAN title and delete button

---

ui/src/app/store/controller/selectors.test.ts
ui/src/app/store/controller/selectors.ts
ui/src/app/store/vlan/types/base.ts
ui/src/app/subnets/views/VLANDetails/VLANDetails.test.tsx
ui/src/app/subnets/views/VLANDetails/VLANDetails.tsx
ui/src/app/subnets/views/VLANDetails/VLANDetailsHeader/VLANDetailsHeader.tsx
ui/src/app/subnets/views/VLANDetails/VLANSummary/VLANSummary.test.tsx
ui/src/app/subnets/views/VLANDetails/VLANSummary/VLANSummary.tsx

- Added the summary section to the VLAN details page
- Go to the React version of a VLAN details page
- Check that the details shown match up with those shown in the legacy version
- Check that the links for fabric/space/controllers take you to the right places
Fixes canonical-web-and-design/app-tribe#666

feat(ui): build VLAN summary

---

ui/src/app/subnets/views/VLANDetails/VLANDetailsHeader/VLANDeleteForm/VLANDeleteForm.test.tsx
ui/src/app/subnets/views/VLANDetails/VLANDetailsHeader/VLANDeleteForm/VLANDeleteForm.tsx
ui/src/app/subnets/views/VLANDetails/VLANDetailsHeader/VLANDeleteForm/index.ts
ui/src/app/subnets/views/VLANDetails/VLANDetailsHeader/VLANDetailsHeader.tsx

- Add a form to the VLAN details header to delete the VLAN.
- Visit the react VLAN details for a VLAN that is not the default (you might need to add a new VLAN).
- In the header click "Delete VLAN" and then confirm.
- The VLAN should get deleted.
Fixes: canonical-web-and-design/app-tribe#665.

feat(ui): add a form to delete a VLAN

---

ui/src/app/base/components/FabricLink/FabricLink.test.tsx
ui/src/app/base/components/FabricLink/FabricLink.tsx
ui/src/app/base/components/FabricLink/index.ts
ui/src/app/base/components/SpaceLink/SpaceLink.test.tsx
ui/src/app/base/components/SpaceLink/SpaceLink.tsx
ui/src/app/base/components/SpaceLink/index.ts
ui/src/app/base/components/SubnetLink/SubnetLink.test.tsx
ui/src/app/base/components/SubnetLink/SubnetLink.tsx
ui/src/app/base/components/SubnetLink/index.ts
ui/src/app/base/components/VLANLink/VLANLink.test.tsx
ui/src/app/base/components/VLANLink/VLANLink.tsx
ui/src/app/base/components/VLANLink/index.ts
ui/src/app/subnets/views/VLANDetails/VLANSummary/VLANSummary.tsx

- Built helper components for each of fabric, space, subnet and VLANs that simply, given an ID:
- returns a spinner if that model type is loading
- handles when a model with that ID does not exist
- returns a link to the React details page of that model instance
- Go to the React details page of a VLAN and check that the fabric …

feat(ui): add helper components for rendering network model links

---

ui/src/app/base/components/DHCPTable/DHCPTable.test.tsx
ui/src/app/base/components/DHCPTable/DHCPTable.tsx
ui/src/app/devices/views/DeviceDetails/DeviceNetwork/DeviceNetwork.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/MachineNetwork.tsx
ui/src/app/store/dhcpsnippet/selectors.test.ts
ui/src/app/store/dhcpsnippet/selectors.ts
ui/src/app/store/subnet/selectors.test.ts
ui/src/app/store/subnet/selectors.ts
ui/src/app/subnets/components/DHCPSnippets/DHCPSnippets.test.tsx
ui/src/app/subnets/components/DHCPSnippets/DHCPSnippets.tsx
ui/src/app/subnets/views/SubnetDetails/SubnetDetails.tsx
ui/src/app/subnets/views/VLANDetails/VLANDetails.tsx

- Update the DHCP snippet table to handle subnets.
- Add the DHCP snippets table to subnet and vlan details.
- Go to Settings -> DHCP snippets.
- Add a DHCP snippet to a subnet.
- Go to the React subnet details for that subnet. You should see a table with the DHCP snippet you added.
- Go to the subnet's VLAN details. You should see a table with the DHCP …

feat(ui): add DHCP snippets table to subnet and vlan details

---

ui/src/app/base/components/DhcpForm/DhcpForm.test.tsx
ui/src/app/base/components/DhcpForm/DhcpForm.tsx

- Fix the DHCP snippet form to only close if the create/update action was successful.
- Create a DHCP snippet in settings and target it to a subnet (it'll need to be a real one).
- Go to the subnet details page and the DHCP snippets table should show the snippet you created.
- Click the edit button and change the subnet to another subnet that isn't real.
- …

fix(ui): close the dhcp form on success

---

ui/src/app/subnets/views/VLANDetails/VLANDetails.tsx
ui/src/app/subnets/views/VLANDetails/VLANSubnets/VLANSubnets.test.tsx
ui/src/app/subnets/views/VLANDetails/VLANSubnets/VLANSubnets.tsx
ui/src/app/subnets/views/VLANDetails/VLANSubnets/_index.scss
ui/src/scss/index.scss

- Built Subnets on this VLAN table in VLAN details page
- I've updated it a bit by removing the "Space" column since it's a VLAN-specific piece of data (i.e. every subnet in the table will be in the same space, so its inclusion is redundant). In its place I've added a few columns of extra data.
- Go to the React details page of …

feat(ui): build Subnets in this VLAN table

---

ui/src/app/base/components/VisuallyHidden/VisuallyHidden.test.tsx
ui/src/app/base/components/VisuallyHidden/VisuallyHidden.tsx
ui/src/app/base/components/VisuallyHidden/_index.scss
ui/src/app/base/components/VisuallyHidden/index.ts
ui/src/app/base/hooks/base.test.tsx
ui/src/app/base/hooks/base.ts
ui/src/app/subnets/views/SpaceDetails/SpaceSummary/SpaceSummary.tsx
ui/src/app/subnets/views/VLANDetails/VLANSummary/VLANSummary.tsx

- add `VisuallyHidden` component (Visually Hidden is used when an element needs to be available to assistive technology, but otherwise hidden)
- add `useId` hook
Fixes: # .
In general, please propose fixes against *master* rather than release branches (e.g. …

add VisuallyHidden and useId utils

---

ui/src/app/subnets/views/FabricDetails/FabricDetailsHeader/FabricDetailsHeader.test.tsx
ui/src/app/subnets/views/FabricDetails/FabricDetailsHeader/FabricDetailsHeader.tsx

- Add button and confirmation panel to delete a fabric.
- Go to `MAAS/r/networks?by=fabric`
- Create a test fabric and delete it
- Make sure it works as expected.
Fixes https://github.com/canonical-web-and-design/app-tribe/issues/642 …

refactor: button to delete fabric

---

ui/src/app/base/components/DHCPTable/DHCPTable.tsx
ui/src/app/base/components/TitledSection/TitledSection.test.tsx
ui/src/app/base/components/TitledSection/TitledSection.tsx
ui/src/app/base/components/TitledSection/index.ts
ui/src/app/base/hooks/base.test.tsx
ui/src/app/devices/views/DeviceDetails/DeviceNetwork/DeviceNetwork.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/MachineNetwork.tsx
ui/src/app/subnets/components/DHCPSnippets/DHCPSnippets.tsx
ui/src/app/subnets/components/ReservedRanges/ReservedRanges.tsx
ui/src/app/subnets/views/FabricDetails/FabricSummary/FabricSummary.tsx
ui/src/app/subnets/views/FabricDetails/FabricVLANs/FabricVLANs.tsx
ui/src/app/subnets/views/SpaceDetails/SpaceSubnets/SpaceSubnets.tsx
ui/src/app/subnets/views/SpaceDetails/SpaceSummary/SpaceSummary.tsx
ui/src/app/subnets/views/SubnetDetails/StaticRoutes/StaticRoutes.tsx
ui/src/app/subnets/views/SubnetDetails/SubnetSummary/SubnetSummary.tsx
ui/src/app/subnets/views/SubnetDetails/UsedIPs/SubnetUsedIPs.tsx
ui/src/app/subnets/views/SubnetDetails/Utilisation/SubnetUtilisation.tsx
ui/src/app/subnets/views/VLANDetails/DHCPStatus/DHCPStatus.tsx
ui/src/app/subnets/views/VLANDetails/VLANSubnets/VLANSubnets.tsx
ui/src/app/subnets/views/VLANDetails/VLANSummary/VLANSummary.tsx

- Add a reusable titled section component.
- Updated subnet views to use the new component.
- Go to details pages for the react subnets models.
- You should see the section titles as before.
Fixes: canonical-web-and-design/app-tribe#718.

feat(ui): add reusable titled component to subnets

---

ui/src/app/store/subnet/selectors.test.ts
ui/src/app/store/subnet/selectors.ts
ui/src/app/subnets/views/FabricDetails/FabricDetails.test.tsx
ui/src/app/subnets/views/FabricDetails/FabricDetails.tsx
ui/src/app/subnets/views/FabricDetails/FabricDetailsHeader/FabricDeleteForm/FabricDeleteForm.test.tsx
ui/src/app/subnets/views/FabricDetails/FabricDetailsHeader/FabricDeleteForm/FabricDeleteForm.tsx
ui/src/app/subnets/views/FabricDetails/FabricDetailsHeader/FabricDeleteForm/index.ts
ui/src/app/subnets/views/FabricDetails/FabricDetailsHeader/FabricDetailsHeader.test.tsx
ui/src/app/subnets/views/FabricDetails/FabricDetailsHeader/FabricDetailsHeader.tsx
ui/src/app/subnets/views/VLANDetails/VLANDetailsHeader/VLANDeleteForm/VLANDeleteForm.test.tsx
ui/src/app/subnets/views/VLANDetails/VLANDetailsHeader/VLANDeleteForm/VLANDeleteForm.tsx
ui/src/app/subnets/views/VLANDetails/VLANDetailsHeader/VLANDetailsHeader.test.tsx
ui/src/app/subnets/views/VLANDetails/VLANDetailsHeader/VLANDetailsHeader.tsx

- Update the delete fabric form to use `FormikForm`. Also handles the case where a fabric can't be deleted because subnets are attached.
- Go to `/MAAS/r/networks` and go to the details page of a fabric without any subnets
- Click "Delete fabric", submit the form and check that a spinner shows in the submit button.
- Check that …

fix(ui): update delete fabric form

---

ui/src/app/base/components/ControllerLink/ControllerLink.test.tsx
ui/src/app/base/components/ControllerLink/ControllerLink.tsx
ui/src/app/base/components/FabricLink/FabricLink.test.tsx
ui/src/app/base/components/FabricLink/FabricLink.tsx
ui/src/app/base/components/SpaceLink/SpaceLink.test.tsx
ui/src/app/base/components/SpaceLink/SpaceLink.tsx
ui/src/app/base/components/SubnetLink/SubnetLink.test.tsx
ui/src/app/base/components/SubnetLink/SubnetLink.tsx
ui/src/app/base/components/VLANLink/VLANLink.test.tsx
ui/src/app/base/components/VLANLink/VLANLink.tsx
ui/src/app/controllers/views/ControllerList/ControllerListTable/ControllerListTable.tsx
ui/src/app/subnets/views/FabricDetails/FabricSummary/FabricSummary.tsx
ui/src/app/subnets/views/VLANDetails/DHCPStatus/DHCPStatus.test.tsx
ui/src/app/subnets/views/VLANDetails/DHCPStatus/DHCPStatus.tsx
ui/src/app/subnets/views/VLANDetails/VLANDetails.test.tsx
ui/src/app/subnets/views/VLANDetails/VLANDetails.tsx
ui/src/app/subnets/views/VLANDetails/VLANDetailsHeader/VLANDetailsHeader.tsx
ui/src/app/subnets/views/VLANDetails/VLANSummary/VLANControllers/VLANControllers.tsx
ui/src/app/subnets/views/VLANDetails/VLANSummary/VLANSummary.tsx

- Built DHCP status section in VLAN details. I've updated the design a little bit so that "High availability" is shown as a boolean instead of only showing when it's true, and also some of the model names are now links.
- Go to the VLAN details page of a VLAN with/without DHCP (MAAS, external, relayed) and check that the text …

feat(ui): build VLAN DHCP status section

---

ui/src/app/store/vlan/selectors.test.ts
ui/src/app/store/vlan/selectors.ts
ui/src/app/subnets/views/FabricDetails/FabricVLANs/FabricVLANs.test.tsx
ui/src/app/subnets/views/FabricDetails/FabricVLANs/FabricVLANs.tsx
ui/src/app/subnets/views/FabricDetails/FabricVLANs/_index.scss
ui/src/scss/index.scss

- Updated the fabric VLANs table in a few ways
- Show a spinner while data is loading
- Group rows by VLAN.
- Change text for a VLAN with no subnets from "Unconfigured" to "No subnets" to be a bit more accurate
- Go to a React fabric details page and check that the VLAN and Space cells aren't duplicated for each subnet
- Check …

feat(ui): improve UX of fabric VLANs table

---

ui/src/app/subnets/views/FabricDetails/EditFabric/EditFabric.test.tsx
ui/src/app/subnets/views/FabricDetails/EditFabric/EditFabric.tsx
ui/src/app/subnets/views/FabricDetails/EditFabric/index.tsx
ui/src/app/subnets/views/FabricDetails/FabricSummary/FabricController/FabricController.test.tsx
ui/src/app/subnets/views/FabricDetails/FabricSummary/FabricController/FabricControllers.tsx
ui/src/app/subnets/views/FabricDetails/FabricSummary/FabricController/index.tsx
ui/src/app/subnets/views/FabricDetails/FabricSummary/FabricSummary.test.tsx
ui/src/app/subnets/views/FabricDetails/FabricSummary/FabricSummary.tsx

- Add a form to edit a fabric on the fabric details summary section.
- Go to the React Fabric details page.
- In the summary section there should be an Edit button. Click it.
- The edit form should appear.
- Change some details and click save. The form should close.
Fixes: …

refactor: edit fabric form

---

ui/src/app/store/subnet/selectors.ts
ui/src/app/subnets/views/SpaceDetails/SpaceDetails.tsx
ui/src/app/subnets/views/SpaceDetails/SpaceSubnets/SpaceSubnets.test.tsx
ui/src/app/subnets/views/SpaceDetails/SpaceSubnets/SpaceSubnets.tsx

- build subnets on this space table
- Go to a space that has subnets, e.g. `MAAS/r/space/1` and verify everything works correctly
Fixes: # . …

refactor: subnets on this space

---

ui/src/app/base/components/Definition/Definition.tsx
ui/src/app/subnets/views/SubnetDetails/SubnetDetails.tsx
ui/src/app/subnets/views/SubnetDetails/SubnetSummary/SubnetSummary.test.tsx
ui/src/app/subnets/views/SubnetDetails/SubnetSummary/SubnetSummary.tsx

- Update subnet details to display definition labels above the content.
- Conditionally display tooltips.
- Go to a React subnets details page.
- You should see the labels above the content (as opposed to the angular version where the labels are to the left).

Update subnet details to display definition labels above the content.

---

ui/src/app/subnets/views/SubnetDetails/SubnetDetails.tsx
ui/src/app/subnets/views/SubnetDetails/SubnetDetailsHeader/SubnetActionForms/components/DeleteSubnet/DeleteSubnet.test.tsx
ui/src/app/subnets/views/SubnetDetails/Utilisation/SubnetUtilisation.test.tsx
ui/src/app/subnets/views/SubnetDetails/Utilisation/SubnetUtilisation.tsx

- Utilisation section on subnet pages
- Go to a subnet page
- Check the utilisation section is populated
Fixes: https://github.com/canonical-web-and-design/app-tribe/issues/656
In general, please propose fixes against *master* rather than release branches (e.g. 2.7), unless …

refactor: subnet utilisation section

---

ui/src/app/store/vlan/selectors.test.ts
ui/src/app/store/vlan/selectors.ts
ui/src/app/store/vlan/types/actions.ts
ui/src/app/subnets/views/VLANDetails/ConfigureDHCP/ConfigureDHCP.test.tsx
ui/src/app/subnets/views/VLANDetails/ConfigureDHCP/ConfigureDHCP.tsx
ui/src/app/subnets/views/VLANDetails/ConfigureDHCP/ConfigureDHCPFields/ConfigureDHCPFields.tsx
ui/src/app/subnets/views/VLANDetails/ConfigureDHCP/ConfigureDHCPFields/index.ts
ui/src/app/subnets/views/VLANDetails/ConfigureDHCP/index.ts
ui/src/app/subnets/views/VLANDetails/DHCPStatus/DHCPStatus.test.tsx
ui/src/app/subnets/views/VLANDetails/DHCPStatus/DHCPStatus.tsx
ui/src/app/subnets/views/VLANDetails/VLANDetails.tsx

- This branch builds out the basic functionality of configuring DHCP with rack controllers or via a relay. Extra parameters for reserved ranges will come after.
- Go to the VLAN details page of a VLAN with subnets
- Click "Configure DHCP"
- Check that changing some values and submitting the form successfully updates DHCP for …

feat(ui): first pass at building DHCP configuration form

---

ui/src/app/store/iprange/selectors.test.ts
ui/src/app/store/iprange/selectors.ts
ui/src/app/subnets/components/ReservedRanges/ReservedRanges.test.tsx
ui/src/app/subnets/components/ReservedRanges/ReservedRanges.tsx
ui/src/app/subnets/components/ReservedRanges/_index.scss
ui/src/app/subnets/views/SubnetDetails/SubnetDetails.tsx
ui/src/app/subnets/views/SubnetsList/_index.scss
ui/src/app/subnets/views/VLANDetails/VLANDetails.tsx
ui/src/scss/index.scss

- Add the reserved ranges table to the subnets and vlans details pages.
- Using the angular client go to a subnet and add some reserved ranges, do the same for a VLAN.
- Visit the subnet and vlan details for the subnet and VLAN you added the reserved ranges to.
- You should see the reserved ranges table with the same data as the angular client.
Fixes: …

feat(ui): add reserved ranges table

---

ui/src/app/subnets/views/FabricDetails/EditFabric/EditFabric.tsx
ui/src/app/subnets/views/FabricDetails/FabricSummary/FabricController/FabricControllers.tsx
ui/src/app/subnets/views/FabricDetails/FabricSummary/FabricSummary.tsx
ui/src/app/subnets/views/FabricDetails/FabricVLANs/FabricVLANs.test.tsx
ui/src/app/subnets/views/FabricDetails/FabricVLANs/FabricVLANs.tsx
ui/src/app/subnets/views/FabricDetails/FabricVLANs/_index.scss
ui/src/app/subnets/views/SpaceDetails/SpaceSubnets/SpaceSubnets.tsx

- Added aria-labels to VLANs on this fabric table.
- Updated fabric controllers to use system_id instead of the whole controller object.
- Go to the fabric details page of a fabric that has rack controllers and check that it renders properly
- Go to the fabric details page of a fabric that has multiple VLANs with subnets
- …

fix(ui): small fixes in networking details pages

---

ui/src/app/subnets/components/ReservedRangeForm/ReservedRangeForm.test.tsx
ui/src/app/subnets/components/ReservedRangeForm/ReservedRangeForm.tsx
ui/src/app/subnets/components/ReservedRangeForm/index.ts
ui/src/app/subnets/components/ReservedRanges/ReservedRanges.test.tsx
ui/src/app/subnets/components/ReservedRanges/ReservedRanges.tsx

- Add a form to edit reserved ranges.
- Visit the react details page for a subnet or VLAN with reserved and dynamic ranges (or add some).
- Click the edit icon for a reserved range and the form should appear and you should be able to change the Purpose field.
- Change some values and confirm and the range should get updated.
- Click the edit icon for a …

feat(ui): edit reserved ranges

---

ui/src/app/store/iprange/utils.test.ts
ui/src/app/store/iprange/utils.ts
ui/src/app/subnets/components/ReservedRanges/ReservedRanges.tsx
ui/src/app/subnets/views/VLANDetails/ConfigureDHCP/ConfigureDHCP.test.tsx
ui/src/app/subnets/views/VLANDetails/ConfigureDHCP/ConfigureDHCP.tsx
ui/src/app/subnets/views/VLANDetails/ConfigureDHCP/ConfigureDHCPFields/ConfigureDHCPFields.tsx
ui/src/app/subnets/views/VLANDetails/ConfigureDHCP/DHCPReservedRanges/DHCPReservedRanges.test.tsx
ui/src/app/subnets/views/VLANDetails/ConfigureDHCP/DHCPReservedRanges/DHCPReservedRanges.tsx
ui/src/app/subnets/views/VLANDetails/ConfigureDHCP/DHCPReservedRanges/index.ts

- Added Reserved dynamic range table to Configure DHCP form
- Shows a list of ranges if they exists, otherwise
- Renders `extra` form fields in table cells
- Go to the VLAN details page of a VLAN that does not have any DHCP enabled and has no reserved IP ranges
- Click "Configure DHCP" and check that a table shows, allowing you …

feat(ui): add reserved ranges table/form to Configure DHCP section

---

ui/src/app/subnets/components/ReservedRangeForm/ReservedRangeForm.test.tsx
ui/src/app/subnets/components/ReservedRangeForm/ReservedRangeForm.tsx
ui/src/app/subnets/components/ReservedRanges/ReservedRanges.test.tsx
ui/src/app/subnets/components/ReservedRanges/ReservedRanges.tsx
ui/src/app/subnets/views/VLANDetails/VLANDetails.tsx

- Add forms for reserving ranges to the reserved ranges form.
- Got to a VLAN without any subnets.
- Above the reserved ranges table the "Reserve range" button should be disabled and there should be a warning.
- Go to a subnet or VLAN that has a subnet.
- Click "Reserve range" and then choose "Reserve range".
- A form should …

feat(ui): add forms for reserving ranges

---

ui/src/app/subnets/views/VLANDetails/ConfigureDHCP/ConfigureDHCP.test.tsx
ui/src/app/subnets/views/VLANDetails/ConfigureDHCP/ConfigureDHCP.tsx
ui/src/app/subnets/views/VLANDetails/ConfigureDHCP/ConfigureDHCPFields/ConfigureDHCPFields.tsx
ui/src/app/subnets/views/VLANDetails/ConfigureDHCP/DHCPReservedRanges/DHCPReservedRanges.test.tsx
ui/src/app/subnets/views/VLANDetails/ConfigureDHCP/DHCPReservedRanges/DHCPReservedRanges.tsx

- Improved validation of Configure DHCP form
- Validates that either a rack controller or relay VLAN must be defined
- Validates that if a subnet is selected for the dynamic range, it must have at least one free IP address
- Go to the details page of a VLAN that has no rack controllers and click "Configure DHCP"
- Check that the …

fix(ui): improve validation of Configure DHCP form.

---

ui/src/app/subnets/views/SubnetDetails/StaticRoutes/StaticRoutes.test.tsx
ui/src/app/subnets/views/SubnetDetails/StaticRoutes/StaticRoutes.tsx
ui/src/app/subnets/views/SubnetDetails/SubnetDetails.tsx

- Show static routes table for a subnet.
I added the delete and confirmation panel based on the pattern that was build in the section below (Reserved ranges). But since there will be some changes to do, we can deal with those in the corresponding issue https://github.com/canonical-web-and-design/app-tribe/issues/660
- Go to a …

refactor: static routes section

---

ui/src/app/store/subnet/hooks.test.tsx
ui/src/app/store/subnet/hooks.ts
ui/src/app/store/subnet/utils.test.ts
ui/src/app/store/subnet/utils.ts
ui/src/app/subnets/views/SpaceDetails/SpaceDetailsHeader/SpaceDelete/SpaceDelete.tsx
ui/src/app/subnets/views/SubnetDetails/SubnetDetailsHeader/SubnetActionForms/components/DeleteSubnet/DeleteSubnet.test.tsx
ui/src/app/subnets/views/SubnetDetails/SubnetDetailsHeader/SubnetActionForms/components/DeleteSubnet/DeleteSubnet.tsx

- Update the delete subnet utils to be hooks.
- Go to a subnet whose VLAN has DHCP enabled.
- Use the take action menu to open the delete form.
- There should be an error that it can't be deleted and the delete button should be disabled.
- Go to a subnet whose VLAN has DHCP disabled.
- Use the take action menu to open the delete form.
- You should be able to …

refactor(ui): turn subnet utils into hooks

---

ui/src/app/base/hooks/base.test.tsx
ui/src/app/base/hooks/base.ts
ui/src/app/base/hooks/index.ts
ui/src/app/subnets/views/Subnets.tsx

- Added a hook to scroll to the top of the window when `pathname` changes and used in Subnets pages
- Go to the React Subnets pages
- Click around between the list and fabric/space/subnet/VLAN details pages and check that the window is scrolled to the top on every URL change
Fixes canonical-web-and-design/app-tribe#726

feat(ui): add useScrollToTop hook

---

ui/src/app/base/components/FormikField/FormikField.tsx
ui/src/app/store/user/selectors.ts
ui/src/app/subnets/views/SubnetDetails/StaticRoutes/AddStaticRouteForm/AddStaticRouteForm.test.tsx
ui/src/app/subnets/views/SubnetDetails/StaticRoutes/AddStaticRouteForm/AddStaticRouteForm.tsx
ui/src/app/subnets/views/SubnetDetails/StaticRoutes/AddStaticRouteForm/index.ts
ui/src/app/subnets/views/SubnetDetails/StaticRoutes/StaticRoutes.test.tsx
ui/src/app/subnets/views/SubnetDetails/StaticRoutes/StaticRoutes.tsx
ui/src/app/subnets/views/SubnetDetails/SubnetDetails.tsx

- subnets add static route form
- refactor SubnetDetails logic so that child elements always receive a valid subnet id, otherwise display ModelNotFound component
- add `useId` to `FormikField`
- Go to any subnet and add a static route. Verify all works correctly.
Fixes: # . …

refactor: subnets add static route form

---

ui/src/app/subnets/views/SubnetDetails/SubnetSummary/SubnetSpace/SubnetSpace.test.tsx
ui/src/app/subnets/views/SubnetDetails/SubnetSummary/SubnetSpace/SubnetSpace.tsx
ui/src/app/subnets/views/SubnetDetails/SubnetSummary/SubnetSpace/index.ts
ui/src/app/subnets/views/SubnetDetails/SubnetSummary/SubnetSummary.tsx
ui/src/app/subnets/views/SubnetDetails/SubnetSummary/SubnetSummaryForm/SubnetSummaryForm.test.tsx
ui/src/app/subnets/views/SubnetDetails/SubnetSummary/SubnetSummaryForm/SubnetSummaryFormFields/SubnetSummaryFormFields.test.tsx
ui/src/app/subnets/views/SubnetDetails/SubnetSummary/SubnetSummaryForm/SubnetSummaryFormFields/SubnetSummaryFormFields.tsx

- Minor improvements to subnet summary and edit form
- Render the space in the edit form
- Handle setting the VLAN based on the selected fabric's default VLAN ID
- Added help text and placeholders
- Go to the details page of a subnet and click "Edit"
- Check that there are placeholders for the fields, and the DNS field has help …

fix(ui): minor improvements to subnet summary edit form

---

ui/src/app/subnets/components/ReservedRangeForm/ReservedRangeForm.test.tsx
ui/src/app/subnets/components/ReservedRangeForm/ReservedRangeForm.tsx
ui/src/app/subnets/components/ReservedRanges/ReservedRanges.tsx
ui/src/app/subnets/components/ReservedRanges/_index.scss

- update reserved ranges layout
-  update edit form layout to fin in a row
- update label to “comment” to be consistent with the API
- fix table widths using flex (width was ignored)
- edit form displays in a single column (current limitation of the MainTable component)
- Go to a subnet view with reserved ranges
- verify …

fix(ui): reserved ranges layout

---

ui/src/app/store/subnet/types/enum.ts
ui/src/app/subnets/views/SubnetDetails/SubnetDetails.tsx
ui/src/app/subnets/views/SubnetDetails/UsedIPs/SubnetUsedIPs.test.tsx
ui/src/app/subnets/views/SubnetDetails/UsedIPs/SubnetUsedIPs.tsx
ui/src/app/subnets/views/SubnetDetails/UsedIPs/_index.scss
ui/src/scss/index.scss

- Used IPs table for subnets
- Check that the used IPs section is populated (subnet with id=11 has some content) or alternatively an empty message is displayed.
Fixes https://github.com/canonical-web-and-design/app-tribe/issues/661

refactor: subnet used IPs

---

ui/src/app/store/subnet/utils.ts
ui/src/app/subnets/views/SubnetDetails/StaticRoutes/AddStaticRouteForm/AddStaticRouteForm.tsx
ui/src/app/subnets/views/SubnetDetails/StaticRoutes/EditStaticRouteForm/EditStaticRouteForm.test.tsx
ui/src/app/subnets/views/SubnetDetails/StaticRoutes/EditStaticRouteForm/EditStaticRouteForm.tsx
ui/src/app/subnets/views/SubnetDetails/StaticRoutes/EditStaticRouteForm/index.ts
ui/src/app/subnets/views/SubnetDetails/StaticRoutes/StaticRoutes.test.tsx
ui/src/app/subnets/views/SubnetDetails/StaticRoutes/StaticRoutes.tsx
ui/src/app/subnets/views/SubnetDetails/StaticRoutes/_index.scss
ui/src/scss/index.scss

-  build subnets edit static route form
- add responsive static routes table
- update static routes table layout widths
- move `getIsDestinationForSource` to utils
(displayed in a single column - MainTable's current limitation)
Fixes: # . …

feat(ui): build subnets edit static route form

---

ui/src/app/subnets/components/ReservedRangeForm/ReservedRangeForm.tsx
ui/src/app/subnets/components/ReservedRanges/ReservedRanges.test.tsx
ui/src/app/subnets/components/ReservedRanges/ReservedRanges.tsx
ui/src/app/subnets/components/ReservedRanges/_index.scss

- Display a subnet column when the reserved ranges table is displayed for a VLAN.
- Go to a subnet details page and scroll down to the reserved ranges table.
- There should be no subnet column on the left hand side.
- Go to a VLAN details page and scroll down to the reserved ranges table.
- There should be a subnet column on the left hand side.
Fixes: …

feat(ui): display a subnet column for VLAN reserved ranges

---

ui/src/app/subnets/views/FormActions/components/AddVlan.tsx

- Remove requirement to define a space when adding a VLAN
- Go to `/MAAS/r/networks` and click "Add" > "VLAN"
- Check that you can add a VLAN without defining a space

fix(ui): allow adding VLANs without a space

---

ui/src/app/subnets/components/ReservedRangeForm/ReservedRangeForm.test.tsx
ui/src/app/subnets/views/SubnetDetails/SubnetDetailsHeader/SubnetActionForms/components/DeleteSubnet/DeleteSubnet.test.tsx
ui/src/app/subnets/views/SubnetDetails/SubnetSummary/SubnetSummary.test.tsx
ui/src/app/subnets/views/VLANDetails/VLANSummary/VLANSummary.test.tsx

- use `not.toBeInTheDocument()` assertions instead of `toHaveLength(0)`
- this is done for consistency with other tests, but also `not.toBeInTheDocument()` is more meaningful
https://testing-library.com/docs/guide-disappearance/#nottobeinthedocument
Fixes: # . …

refactor: use not.toBeInTheDocument assertions

---

integration/cypress/integration/accessibility/accessibility.spec.ts
integration/cypress/integration/base/header.spec.ts

- update cypress tests to use the new networks path
Fixes: # . …

test: update cypress networks path

---

ui/src/app/subnets/views/VLANDetails/ConfigureDHCP/ConfigureDHCPFields/ConfigureDHCPFields.tsx

- Fixed validation of VLAN DHCP configuration form
- Go to the details page of a VLAN configured with DHCP provided from a rack controller
- Uncheck "MAAS provides DHCP" and then recheck it
- The form should not be disabled
Fixes #3629

fix(ui): fix validation of VLAN DHCP configuration form

---

ui/src/app/base/components/ActionForm/ActionForm.tsx
ui/src/app/base/components/node/NodeActionFormWrapper/NodeActionFormWrapper.tsx
ui/src/app/machines/views/MachineList/MachineListTable/OwnerColumn/OwnerColumn.test.tsx
ui/src/app/store/general/selectors/machineActions.test.ts
ui/src/app/store/utils/node/base.ts

- use consistent naming for machine allocation action (under take action button you can "Acquire" a machine(s) but under status the machine is "Allocated")
- Select any ready machine from the list and click "Take action" to reveal the dropdown menu.
- Verify consistent naming is used ("allocate" instead of "acquire")
Fixes: …

fix(ui): use consistent naming for machine allocation action

---

ui/src/__mocks__/nanoid.ts
ui/src/app/machines/views/MachineList/MachineListTable/OwnerColumn/__snapshots__/OwnerColumn.test.tsx.snap
ui/src/app/machines/views/MachineList/MachineListTable/PoolColumn/__snapshots__/PoolColumn.test.tsx.snap
ui/src/app/machines/views/MachineList/MachineListTable/PowerColumn/__snapshots__/PowerColumn.test.tsx.snap
ui/src/app/machines/views/MachineList/MachineListTable/StatusColumn/__snapshots__/StatusColumn.test.tsx.snap
ui/src/app/machines/views/MachineList/MachineListTable/ZoneColumn/__snapshots__/ZoneColumn.test.tsx.snap

- fix nanoid mock to return unique ids (`nanoid` is used by react-components)
- use `mock-nanoid-N` convention to make it easier to identify in snapshots / debug
Fixes: # .
In general, please propose fixes against *master* rather than release branches (e.g. …

test: fix nanoid mock to return unique ids

---

ui/src/app/kvm/components/KVMConfigurationCard/KVMConfigurationCard.test.tsx
ui/src/app/kvm/components/KVMConfigurationCard/KVMConfigurationCard.tsx
ui/src/app/store/pod/types/actions.ts

- Allow changing KVM values to initial after first submit
- Rewrite KVM config tests to use RTL
- Go to the config page of a KVM and check that the submit button is disabled
- Change a value (like CPU overcommit) and check that the submit button becomes enabled
- Submit the form
- After success, change the value back to the …

fix(ui): fix KVM config form disabled submit button after initial submit

---

ui/src/app/kvm/components/KVMHeaderForms/AddLxd/AuthenticationForm/AuthenticationForm.test.tsx
ui/src/app/kvm/components/KVMHeaderForms/AddLxd/AuthenticationForm/AuthenticationForm.tsx
ui/src/app/store/pod/reducers.test.ts
ui/src/app/store/pod/slice.ts

- Fixed bug where user is unable to add a LXD host with a trust password
- Fixed bug where adding certificate trust after submitting the authentication form would send the user to the start of the Add LXD host wizard.
- QAing this for real will require setting up a local LXD server with a trust password, which you can do so by …

fix(ui): include cert and key values when adding LXD host with a trust password

---

ui/src/app/base/components/PowerTypeFields/PowerTypeFields.tsx
ui/src/app/machines/components/MachineHeaderForms/AddMachine/AddMachineForm/AddMachineForm.test.tsx
ui/src/app/machines/components/MachineHeaderForms/AddMachine/AddMachineForm/AddMachineForm.tsx
ui/src/app/machines/components/MachineHeaderForms/AddMachine/AddMachineFormFields/AddMachineFormFields.tsx
ui/src/app/machines/components/MachineHeaderForms/AddMachine/types.ts
ui/src/app/store/machine/types/actions.ts

- Handle `PowerTypeFields` validation on power type change asynchronously, which means selecting "Manual" no longer requires field blur to validate
- Fixed incorrect types for machine create/update actions
- Converted `AddMachineForm.test.tsx` to RTL
- Go to the machine list and click "Add hardware > Machine"
- Choose a …

fix(ui): correctly handle add machine form validation asynchronously

---

integration/cypress/integration/machines/list.spec.ts
ui/src/app/base/components/FilterAccordion/FilterAccordion.tsx
ui/src/app/base/components/FilterAccordion/_index.scss
ui/src/app/base/components/NonBreakingSpace/NonBreakingSpace.test.tsx
ui/src/app/base/components/NonBreakingSpace/NonBreakingSpace.tsx
ui/src/app/base/components/NonBreakingSpace/index.ts
ui/src/app/machines/constants.ts
ui/src/app/machines/views/MachineList/MachineList.tsx
ui/src/app/machines/views/MachineList/MachineListControls/HiddenColumnsSelect/HiddenColumnsSelect.test.tsx
ui/src/app/machines/views/MachineList/MachineListControls/HiddenColumnsSelect/HiddenColumnsSelect.tsx
ui/src/app/machines/views/MachineList/MachineListControls/HiddenColumnsSelect/index.ts
ui/src/app/machines/views/MachineList/MachineListControls/MachineListControls.test.tsx
ui/src/app/machines/views/MachineList/MachineListControls/MachineListControls.tsx
ui/src/app/machines/views/MachineList/MachineListTable/MachineListTable.test.tsx
ui/src/app/machines/views/MachineList/MachineListTable/MachineListTable.tsx
ui/src/app/machines/views/MachineList/MachineListTable/NameColumn/NameColumn.tsx
ui/src/app/machines/views/MachineList/MachineListTable/NameColumn/__snapshots__/NameColumn.test.tsx.snap
ui/src/app/machines/views/MachineList/_index.scss

- refactor machine table to allow hiding columns
- add a mock generating unique ids for nanoid (used by react-components, otherwise testing-library can't find correct labels and test fails)
- refactor table to use colspan instead of empty columns
- add fallback to non-breaking space to keep equal height of all rows
- View the …

refactor(ui): allow hidden machine table columns

---

ui/.eslintrc.js
ui/package.json
ui/src/app/base/hooks/base.test.tsx
ui/src/app/subnets/views/FabricDetails/FabricSummary/FabricSummary.test.tsx
ui/src/app/subnets/views/FormActions/components/AddFabric.test.tsx
ui/src/app/subnets/views/FormActions/components/AddSubnet.test.tsx
ui/src/app/subnets/views/FormActions/components/AddVlan.test.tsx
ui/src/app/subnets/views/SpaceDetails/SpaceDetails.test.tsx
ui/src/app/subnets/views/SpaceDetails/SpaceSummary/SpaceSummary.test.tsx
ui/src/app/subnets/views/SubnetDetails/StaticRoutes/AddStaticRouteForm/AddStaticRouteForm.test.tsx
ui/src/app/subnets/views/SubnetDetails/StaticRoutes/StaticRoutes.test.tsx
yarn.lock

- add eslint plugin testing library helping follow testing-library best practices
- fix all violations of following eslint rules:
- [await-async-utils](https://github.com/testing-library/eslint-plugin-testing-library/blob/main/docs/rules/await-async-utils.md) - Ensure that promises returned by async utils are handled properly.
- [render-result-naming-convention](https://github.com/testing-library/eslint-plugin-testing-library/blob/main/docs/rules/render-result-naming-convention.md) - This rule aims to ensure the return value from render is named properly.
- [A local snap …

test: add eslint-plugin-testing-library

---

shared/src/components/Footer/Footer.tsx
shared/src/components/Header/Header.tsx
shared/src/components/StatusBar/StatusBar.tsx
ui/src/app/App.tsx
ui/src/app/base/components/Login/Login.tsx
ui/src/app/base/components/Section/Section.tsx
ui/src/app/base/components/Section/__snapshots__/Section.test.tsx.snap
ui/src/app/controllers/views/ControllerList/ControllerListTable/ControllerListTable.tsx
ui/src/app/devices/views/DeviceList/DeviceListTable/DeviceListTable.tsx
ui/src/app/intro/views/IncompleteCard/__snapshots__/IncompleteCard.test.tsx.snap
ui/src/scss/_patterns_links.scss

- fix "skip link" by using a consistent content id globally and [vanillaframwork.io skip link](https://vanillaframework.io/docs/patterns/links#skip-link)
- ensure all content is contained within landmarks - [region rule](https://dequeuniversity.com/rules/axe/4.3/region?application=axeAPI)
- fix all violations on:
- "Controllers" page (/controllers)
- "My preferences" page (/account/prefs/details)
- "Devices" page (/devices)
- Use the `Tab` key to navigate between elements.
- The first element on the page should be the skip link which allows you to skip the navigation bar and go straight to the main content.
- [A development …

fix: skip link, contain all content by landmarks

---

ui/src/app/Routes.tsx
ui/src/app/machines/views/MachineList/MachineListHeader/MachineListHeader.tsx
ui/src/app/machines/views/Machines.tsx
ui/src/app/tags/urls.ts
ui/src/app/tags/views/TagDetails/TagDetails.test.tsx
ui/src/app/tags/views/TagDetails/TagDetails.tsx
ui/src/app/tags/views/TagDetails/index.ts
ui/src/app/tags/views/Tags.test.tsx
ui/src/app/tags/views/Tags.tsx

- Add the tag details page.
- Visit /r/tag/1 (or change the id if that doesn't exist).
- You should see the tag details.
Fixes: canonical-web-and-design/app-tribe#705.

feat(ui): display tag details

---

ui/src/app/tags/views/TagList/TagList.test.tsx
ui/src/app/tags/views/TagList/TagList.tsx
ui/src/app/tags/views/TagList/index.ts
ui/src/app/tags/views/Tags.test.tsx
ui/src/app/tags/views/Tags.tsx

- Add the tag table.
- Visit the tag list (machines -> tags).
- You should see a list of tags.
- Clicking links in the "Applied to" column should take you to a filtered node list.
Fixes: canonical-web-and-design/app-tribe#699.

feat(ui): tag table

---

ui/src/app/base/components/ActionBar/ActionBar.tsx
ui/src/app/base/components/SegmentToggle/SegmentToggle.test.tsx
ui/src/app/base/components/SegmentToggle/SegmentToggle.tsx
ui/src/app/base/components/SegmentToggle/_index.scss
ui/src/app/base/components/SegmentToggle/index.ts
ui/src/app/store/tag/selectors.test.ts
ui/src/app/store/tag/selectors.ts
ui/src/app/tags/views/TagList/TagList.test.tsx
ui/src/app/tags/views/TagList/TagList.tsx
ui/src/app/tags/views/TagList/TagListControls/TagListControls.test.tsx
ui/src/app/tags/views/TagList/TagListControls/TagListControls.tsx
ui/src/app/tags/views/TagList/TagListControls/index.ts
ui/src/app/tags/views/TagList/TagTable/TagTable.test.tsx
ui/src/app/tags/views/TagList/TagTable/TagTable.tsx
ui/src/app/tags/views/TagList/TagTable/index.ts
ui/src/app/tags/views/TagList/constants.ts
ui/src/app/tags/views/TagList/index.ts
ui/src/scss/index.scss

- Add a segmented button component.
- Add the action bar to Tags to sort, filter and search.
- Add pagination to the table.
- Visit the tags tab under machines.
- Check that you can filter by automatic or manual tags.
- Check that you can search tags.
- Check that you can change the order of the name and updated columns.
- Check that you can paginate the …

Add tag sort, filter, search and pagination

---

ui/src/app/store/tag/actions.test.ts
ui/src/app/store/tag/reducers.test.ts
ui/src/app/store/tag/slice.ts
ui/src/app/store/tag/types/actions.ts
ui/src/app/store/tag/types/index.ts
ui/src/testing/factories/state.ts

- Add actions and reducers to the tag slice to support create, update and delete.
N/A code changes only.
Fixes: canonical-web-and-design/app-tribe#712.

feat(ui): add tag create, update and delete actions

---

ui/src/app/base/components/ActionForm/ActionForm.test.tsx
ui/src/app/base/components/ActionForm/ActionForm.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagForm.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagFormFields/TagFormFields.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/_index.scss
ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/_index.scss
ui/src/scss/_pseudo-border.scss
ui/src/scss/index.scss

- Set up the three column layout in the tag form. Includes placeholder states that will be replaced
with proper content.
- Tick some machines and use the take action menu to open the tag form.
- The form should have three columns.
- Resizing your window should rearrange the columns in sensible ways.
Fixes: …

feat(ui): tag form three column layout

---

ui/.eslintrc.js
ui/src/app/base/hooks/base.test.tsx
ui/src/app/subnets/components/ReservedRangeForm/ReservedRangeForm.test.tsx
ui/src/app/subnets/components/ReservedRanges/ReservedRanges.test.tsx
ui/src/app/subnets/views/FabricDetails/FabricSummary/FabricSummary.test.tsx
ui/src/app/subnets/views/FormActions/components/AddSubnet.test.tsx
ui/src/app/subnets/views/FormActions/components/AddVlan.test.tsx
ui/src/app/subnets/views/SpaceDetails/SpaceSummary/SpaceSummary.test.tsx
ui/src/app/subnets/views/SubnetDetails/StaticRoutes/AddStaticRouteForm/AddStaticRouteForm.test.tsx
ui/src/app/subnets/views/SubnetDetails/StaticRoutes/StaticRoutes.test.tsx
ui/src/app/subnets/views/SubnetDetails/SubnetDetailsHeader/SubnetActionForms/components/EditBootArchitectures/EditBootArchitectures.test.tsx
ui/src/app/subnets/views/SubnetDetails/SubnetDetailsHeader/SubnetActionForms/components/MapSubnet/MapSubnet.test.tsx
ui/src/app/subnets/views/SubnetDetails/SubnetDetailsHeader/SubnetDetailsHeader.test.tsx
ui/src/app/subnets/views/SubnetDetails/SubnetSummary/SubnetSummary.test.tsx
ui/src/app/subnets/views/SubnetDetails/SubnetSummary/SubnetSummaryForm/SubnetSummaryForm.test.tsx
ui/src/app/subnets/views/SubnetDetails/SubnetSummary/SubnetSummaryForm/SubnetSummaryFormFields/SubnetSummaryFormFields.test.tsx
ui/src/app/subnets/views/SubnetDetails/SubnetUsedIPs/SubnetUsedIPs.test.tsx
ui/src/app/subnets/views/VLANDetails/ConfigureDHCP/ConfigureDHCP.test.tsx
ui/src/app/subnets/views/VLANDetails/ConfigureDHCP/DHCPReservedRanges/DHCPReservedRanges.test.tsx
ui/src/app/subnets/views/VLANDetails/EditVLAN/EditVLAN.test.tsx
ui/src/app/subnets/views/VLANDetails/VLANDetailsHeader/VLANDetailsHeader.test.tsx
ui/src/app/tags/views/TagList/TagTable/TagTable.test.tsx

- refactor [subnets/views/VLANDetails/ConfigureDHCP/ConfigureDHCP.test.tsx](https://github.com/canonical-web-and-design/maas-ui/compare/master...petermakowski:fix-testing-library-warnings?expand=1#diff-b9c3100dfc2b02c23bb0052d39511a69f801e78573b52cd2e644f99c6730b817) to use userEvent and test the component the way the user would use it (e.g. `userEvent.tab()` instead of `fireEvent.blur()`)
- refactor to not use `waitFor` to wrap around user interactions, and move it to to expect assertions instead (`testing-library/no-wait-for-side-effects` rule)
- enable `testing-library/prefer-explicit-assert` (using explicit assertions is something that we already try to do anyway)
- enable `prefer-presence-queries`
- disable `testing-library/prefer-find-by` as it tends to conflict with …

test: cleanup subnet tests

---

integration/cypress/integration/accessibility/accessibility.spec.ts
integration/cypress/support/commands.ts
integration/cypress/support/index.ts

- add waitForPageToLoad cypress command
- use more reliable cypress queries for detecting appearance/disappearance
Fixes: (https://github.com/canonical-web-and-design/app-tribe/issues/756) …

add waitForPageToLoad cypress command

---

ui/src/app/base/components/NodeActionMenu/NodeActionMenu.test.tsx
ui/src/app/base/components/NodeActionMenu/NodeActionMenu.tsx
ui/src/app/machines/views/MachineList/MachineListHeader/MachineListHeader.test.tsx
ui/src/app/machines/views/MachineList/MachineListHeader/MachineListHeader.tsx

- Add a new label to the tag action when it is first seen.
- Visit the machine list.
- Tick a/some machines.
- Open the take action menu.
- The tag action should have "(NEW)" label next to it.
- Click on the tag action and then press cancel.
- Open the take action menu again and the "(NEW)" label should not be visible.
Fixes: …

feat(ui): display new label for tag action

---

integration/.env
integration/cypress/constants.ts
integration/cypress/percy/percy.spec.ts
integration/cypress/support/index.ts
integration/cypress/tsconfig.json
integration/package.json
integration/percy.sh
yarn.lock

- Add percy.io integration (it's meant to be run locally as-needed to assist with QA) 
- you can see example screenshots here: https://percy.io/vanilla-framework/maas-ui/
This has been discussed with and approved by Vanilla team on Mattermost https://chat.canonical.com/canonical/pl/1amds538hfdfup71a1hg433n7y …

Add percy integration

---

integration/cypress/integration/subnets/subnets.spec.ts
ui/src/app/subnets/views/SubnetsList/SubnetsTable/FabricTable/FabricTable.tsx
ui/src/app/subnets/views/SubnetsList/SubnetsTable/SpaceTable/SpaceTable.tsx
ui/src/app/subnets/views/SubnetsList/SubnetsTable/SubnetsTable.test.tsx
ui/src/app/subnets/views/SubnetsList/SubnetsTable/constants.ts
ui/src/app/subnets/views/SubnetsList/SubnetsTable/hooks.ts
ui/src/app/subnets/views/SubnetsList/SubnetsTable/utils.test.tsx
ui/src/app/subnets/views/SubnetsList/SubnetsTable/utils.tsx
yarn.lock

- add pagination to subnets table
- refactor to use the `localeCompare` alphanumeric sort via common `simpleSortByKey` util function
- add additional tests for subnets tables
It's obvious what's changed by looking at tests, but adding for clarity
- Go to `/networks` and verify the table behaves correctly (e.g. when …

feat: add pagination to subnets table

---

ui/src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.test.tsx
ui/src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.tsx

- Display a spinner when waiting for the machine details to load.
- Visit the machine list
- Reload so that the data in redux is fresh.
- Click on a machine
- You should get the machine details and it should not display an error.
Fixes: #3671.

fix(ui): fix loading machine details

---

ui/src/app/base/components/PowerTypeFields/IPMIPowerFields/IPMIPowerFields.test.tsx
ui/src/app/base/components/PowerTypeFields/IPMIPowerFields/IPMIPowerFields.tsx
ui/src/app/base/components/PowerTypeFields/IPMIPowerFields/index.ts
ui/src/app/base/components/PowerTypeFields/PowerTypeFields.tsx

- Created a custom component for IPMI power fields which handles the "None" workaround flag
- Go to the machine list and click "Add hardware > Machine"
- Select "IPMI" as the power type and check there is no "None" workaround flag
- Unselect all workaround flags and submit the form
- Check that the action that gets dispatched …

fix(ui): handle "None" workaround flag for IPMI power field

---

ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagForm.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagFormChanges/TagFormChanges.test.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagFormChanges/TagFormChanges.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagFormChanges/index.ts
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagFormFields/TagFormFields.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagList/TagList.test.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagList/TagList.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagList/index.ts
ui/src/app/store/machine/utils/common.test.ts
ui/src/app/store/machine/utils/common.ts
ui/src/app/store/machine/utils/index.ts
ui/src/app/store/tag/selectors.test.ts
ui/src/app/store/tag/selectors.ts
ui/src/scss/_vanilla-overrides.scss
ui/src/testing/factories/tag.ts

- Add the existing manual and automatic tags on the selected machines in the tag form in the machine list.
- Go to the machine list and select some machines. I've created an automatic tag so if you select all machines, or one of the machines attached to the tag (http://bolla.internal:5240/MAAS/r/tag/74) you'll see automatic tags in the form.
- Use the take …

feat(ui): display manual and automatic tags in the tag form

---

ui/src/app/machines/views/MachineDetails/MachineCommissioning/MachineCommissioning.tsx
ui/src/app/store/machine/types/base.ts
ui/src/testing/factories/nodes.ts

- Moved `commissioning_status` from `BaseMachine` to `MachineDetails`. It looks like the other params (`cpu_speed` and `commissioning_start_time`) were already in the right place, even though they were technically wrong before.
- N/A
Fixes #3691

fix(ui): Update machine types with latest shapes

---

ui/src/app/machines/views/MachineList/MachineListTable/MachineListTable.tsx
ui/src/app/store/machine/selectors.test.ts
ui/src/app/store/machine/selectors.ts
ui/src/app/tags/components/TagsHeader/AddTagForm/AddTagForm.test.tsx
ui/src/app/tags/components/TagsHeader/DeleteTagForm/DeleteTagForm.test.tsx
ui/src/app/tags/components/TagsHeader/DeleteTagForm/DeleteTagForm.tsx
ui/src/app/tags/components/TagsHeader/DeleteTagForm/DeleteTagFormWarnings/DeleteTagFormWarnings.test.tsx
ui/src/app/tags/components/TagsHeader/DeleteTagForm/DeleteTagFormWarnings/DeleteTagFormWarnings.tsx
ui/src/app/tags/components/TagsHeader/TagHeaderForms/TagHeaderForms.test.tsx
ui/src/app/tags/components/TagsHeader/TagHeaderForms/TagHeaderForms.tsx
ui/src/app/tags/components/TagsHeader/TagsHeader.test.tsx
ui/src/app/tags/types.ts
ui/src/app/tags/urls.ts
ui/src/app/tags/views/TagDetails/TagDetails.tsx
ui/src/app/tags/views/TagList/TagList.tsx
ui/src/app/tags/views/TagList/TagTable/TagTable.tsx
ui/src/app/tags/views/TagMachines/TagMachines.test.tsx
ui/src/app/tags/views/TagMachines/TagMachines.tsx
ui/src/app/tags/views/TagMachines/index.ts
ui/src/app/tags/views/Tags.tsx

- Display the list of deployed machines with a tag.
- Create a tag with opts and add it to a deployed machine (it's a little hard to do that at the moment - you could do it with the CLI or set the definition when creating the tag to `//lshw:description[text() = "Computer"]` and it should get added to some machines).
- Click delete for the tag you just …

feat(ui): tagged machines list

---

ui/src/app/tags/components/DefinitionField/DefinitionField.test.tsx
ui/src/app/tags/components/DefinitionField/DefinitionField.tsx
ui/src/app/tags/components/TagsHeader/AddTagForm/AddTagForm.test.tsx
ui/src/app/tags/components/TagsHeader/AddTagForm/AddTagForm.tsx

- Add analytics to the add tag form for valid/invalid xpaths.
N/A
Fixes: canonical-web-and-design/app-tribe#754.

feat(ui): add xpath analytics

---

integration/cypress.json
integration/cypress/integration/accessibility/accessibility.spec.ts
integration/cypress/integration/login/login.spec.ts
integration/cypress/integration/subnets/add.spec.ts
integration/cypress/support/commands.ts

- Fix cypress failures
- increase the default command timeout and retries for the accessibility tests
- update logout link selector (broke after upgrading to Vanilla 3)
- update subnets table selectors
Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/3352 …

Fix cypress failures

---

ui/src/app/subnets/enum.ts
ui/src/app/subnets/types.ts
ui/src/app/subnets/urls.ts
ui/src/app/subnets/views/FabricDetails/FabricDetails.tsx
ui/src/app/subnets/views/FabricDetails/FabricDetailsHeader/FabricDeleteForm/FabricDeleteForm.tsx
ui/src/app/subnets/views/SpaceDetails/SpaceDetails.tsx
ui/src/app/subnets/views/SpaceDetails/SpaceDetailsHeader/SpaceDelete/SpaceDelete.tsx
ui/src/app/subnets/views/SubnetDetails/SubnetDetails.tsx
ui/src/app/subnets/views/SubnetsList/SubnetsControls/SubnetsControls.tsx
ui/src/app/subnets/views/SubnetsList/SubnetsList.test.tsx
ui/src/app/subnets/views/SubnetsList/SubnetsList.tsx
ui/src/app/subnets/views/SubnetsList/SubnetsTable/SubnetsTable.test.tsx
ui/src/app/subnets/views/SubnetsList/SubnetsTable/SubnetsTable.tsx
ui/src/app/subnets/views/VLANDetails/VLANDetails.tsx
ui/src/testing/utils.tsx

- add search query to url params
- add `renderWithBrowserRouter`, `getUrlParam` test helper utils
- Go to `MAAS/r/networks` and try various search text and group by options
Fixes: canonical-web-and-design/app-tribe#771 . …

feat(subnets): add search query to url params

---

ui/src/app/base/components/FormikFormButtons/FormikFormButtons.test.tsx

- migrate FormikFormButtons.test to testing-library
Fixes: #3712
In general, please propose fixes against *master* rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. Please apply backport labels to the PR …

migrate FormikFormButtons.test to testing-library

---

ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.tsx

- fix: deploy input options misaligned
- add meaningful docs link labels (per new [Zeplin spec](https://zpl.io/O0M0kJX))
- using bolla.internal MAAS go to `MAAS/r/machine/7c7ya3/summary` and verify that labels are displayed in a single line 
Fixes: canonical-web-and-design/maas-ui#3716  …

fix: deploy input options misaligned

---

ui/package.json
ui/src/app/base/components/ArchitectureSelect/__snapshots__/ArchitectureSelect.test.tsx.snap
ui/src/app/base/components/DomainSelect/__snapshots__/DomainSelect.test.tsx.snap
ui/src/app/base/components/FormikField/__snapshots__/FormikField.test.tsx.snap
ui/src/app/base/components/MinimumKernelSelect/__snapshots__/MinimumKernelSelect.test.tsx.snap
ui/src/app/base/components/NodeName/NodeNameFields/__snapshots__/NodeNameFields.test.tsx.snap
ui/src/app/base/components/NodeName/__snapshots__/NodeName.test.tsx.snap
ui/src/app/base/components/ResourcePoolSelect/__snapshots__/ResourcePoolSelect.test.tsx.snap
ui/src/app/base/components/TagSelector/__snapshots__/TagSelector.test.tsx.snap
ui/src/app/base/components/ZoneSelect/__snapshots__/ZoneSelect.test.tsx.snap
ui/src/app/images/views/ImageList/SyncedImages/ChangeSource/FetchImagesForm/FetchImagesForm.test.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagChip/TagChip.test.tsx
ui/src/app/machines/views/MachineList/MachineListTable/NameColumn/__snapshots__/NameColumn.test.tsx.snap
ui/src/scss/_vanilla-overrides.scss
yarn.lock

- Upgrade to react-components to 0.34.0.
- Remove vanilla override for chips.
- Go to the machine list, select some machines that have tags and open the tag form.
- Check that the chips appear evenly spaced in the rows.

feat(ui): upgrade react-components to 0.34.0

---

ui/src/app/tags/components/TagsHeader/DeleteTagForm/DeleteTagForm.test.tsx
ui/src/app/tags/components/TagsHeader/DeleteTagForm/DeleteTagForm.tsx

- Displays a confirmation message when a tag is successfully deleted
- Go to the tag list and delete a tag
- Check that a notification shows up to confirm it was deleted
Fixes canonical-web-and-design/app-tribe#769

feat(ui): display a confirmation message when tag successfully deleted

---

ui/src/app/tags/components/TagsHeader/AddTagForm/AddTagForm.test.tsx
ui/src/app/tags/components/TagsHeader/AddTagForm/AddTagForm.tsx
ui/src/app/tags/constants.ts
ui/src/app/tags/views/TagUpdate/TagUpdate.test.tsx
ui/src/app/tags/views/TagUpdate/TagUpdate.tsx

- Show a confirmation when adding a new automatic tag
- Go to the tag list and click "Create tag"
- Do not enter a definition and submit the form
- Check that you do not see a notification
- Open the create tag form again, this time entering a definition before submitting the form
- Check that a notification appears
Fixes …

feat(ui): show a confirmation when adding a new automatic tag

---

ui/src/app/machines/views/MachineDetails/MachineConfiguration/MachineConfiguration.tsx
ui/src/app/machines/views/MachineDetails/MachineConfiguration/TagForm/TagForm.test.tsx
ui/src/app/machines/views/MachineDetails/MachineConfiguration/TagForm/TagForm.tsx
ui/src/app/machines/views/MachineDetails/MachineConfiguration/TagForm/index.ts

- Added read-only "Tags" section to machine config tab (actual form to come later)
- Go to the Configuration tab of a machine
- Check that there is a "Tags" section that shows a list of tags links
- Check that the tag links filter the machine list appropriately
Fixes canonical-web-and-design/app-tribe#709

feat(ui): build read-only machine tags section in config tab

---

ui/src/app/base/components/TagSelector/TagSelector.test.tsx
ui/src/app/base/components/TagSelector/TagSelector.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagForm.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagFormChanges/TagFormChanges.test.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagFormChanges/TagFormChanges.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagFormFields/TagFormFields.test.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagFormFields/TagFormFields.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/hooks.test.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/hooks.ts
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/types.ts

- Display added tags in the machine list tag form.
- Visit the machine list and select some machines and open the tag form.
- Click on the text input and choose some tag.
- The chosen tags should appear as green items in the change list.
- Clicking Dismiss should remove them.
- Submit the form and then reopen the tag form and the newly added tags should …

feat(ui): add tags to machines

---

shared/src/components/StatusBar/StatusBar.test.tsx
shared/src/components/StatusBar/StatusBar.tsx
ui/src/app/base/components/StatusBar/StatusBar.test.tsx
ui/src/app/base/components/StatusBar/StatusBar.tsx
ui/src/app/store/machine/types/base.ts
ui/src/testing/factories/nodes.ts
ui/src/testing/utils.tsx

- add sync information to the statusbar - more details in https://github.com/canonical-web-and-design/app-tribe/issues/783
- adjust statusbar columns to allow for more space for status
- add `enable_hw_sync`, `last_sync`, `next_sync` to `MachineDetails`
- add `renderWithMockStore` helper util
- deploy a machine with hardware sync enabled, e.g. via maas CLI: `machine deploy [node-id] enable_hw_sync=True`
- view the machine in the UI and verify that sync information is displayed correctly (both fields can read "Never")
- [A local snap MAAS](/HACKING.md#snap-deployment) (this will not usually …

[Periodic hardware sync] -  machine details - add statusbar sync information

---

ui/src/app/base/components/node/TestForm/TestFormFields/TestFormFields.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/CommissionForm/CommissionFormFields/CommissionFormFields.tsx

- Remove required from the tag selector components as the required prop was being spread on the field used to search for tags (or in this case scripts).
- Go to the machine list and tick a machine that can be commissioned.
- Open the commission form and submit. It should not show a warning about the testing scripts being required.
- Now tick a machine that …

fix(ui): fix required tag selectors

---

ui/src/app/base/components/PowerTypeFields/PowerTypeFields.tsx
ui/src/app/machines/views/MachineDetails/MachineConfiguration/PowerForm/PowerForm.test.tsx
ui/src/app/machines/views/MachineDetails/MachineConfiguration/PowerForm/PowerForm.tsx
ui/src/app/machines/views/MachineDetails/MachineConfiguration/PowerForm/PowerFormFields/PowerFormFields.tsx
ui/src/app/store/general/utils/index.ts
ui/src/app/store/general/utils/powerTypes.test.ts
ui/src/app/store/general/utils/powerTypes.ts
ui/src/app/store/machine/utils/common.test.ts
ui/src/app/store/machine/utils/common.ts
ui/src/app/store/machine/utils/index.ts

- Center power config form
- Created common utils for machine power type functions
- Go to the config tab of a machine and check that the form is centered
- Check that you can still submit the form successfully as before.
Fixes canonical-web-and-design/app-tribe#746

feat(ui): center machine power form and create utils for common functions

---

ui/src/app/base/types.ts
ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/StatusCard/StatusCard.test.tsx
ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/StatusCard/StatusCard.tsx
ui/src/app/store/machine/types/base.ts
ui/src/testing/factories/nodes.ts

- add machine feature status
- refactor StatusCard.test.tsx to testing library
---
- **Note:** Tooltip's behaviour will be improved in https://github.com/canonical-web-and-design/react-components/issues/697
- using bolla, go to `machine/xxn6s7/summary`
- if this doesn't work, in file …

[Hardware sync] add machine feature status 

---

ui/src/app/settings/views/Configuration/DeployForm/DeployForm.tsx
ui/src/app/settings/views/Configuration/DeployForm/types.ts
ui/src/app/settings/views/Configuration/DeployFormFields/DeployFormFields.test.tsx
ui/src/app/settings/views/Configuration/DeployFormFields/DeployFormFields.tsx
ui/src/app/store/config/selectors.ts

- add default hardware sync interval option to settings
- refactor DeployFormFields.test.tsx to testing library
- Back-end has a default of `15m` but the design only allows specifying the interval in hours. expects a string value with appended `m` for minutes or `h` for hours, and we only allow.
- once we resolve this front-end implementation will be updated accordingly in https://github.com/canonical-web-and-design/app-tribe/issues/795
- Serving with …

[Hardware sync] settings - default hardware sync interval option

---

shared/src/components/StatusBar/StatusBar.test.tsx
shared/src/components/StatusBar/StatusBar.tsx
ui/src/app/base/components/StatusBar/StatusBar.test.tsx
ui/src/app/base/components/StatusBar/StatusBar.tsx
ui/src/app/base/types.ts
ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/StatusCard/StatusCard.test.tsx
ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/StatusCard/StatusCard.tsx
ui/src/app/settings/views/Configuration/DeployForm/DeployForm.tsx
ui/src/app/settings/views/Configuration/DeployForm/types.ts
ui/src/app/settings/views/Configuration/DeployFormFields/DeployFormFields.test.tsx
ui/src/app/settings/views/Configuration/DeployFormFields/DeployFormFields.tsx
ui/src/app/store/config/selectors.ts
ui/src/app/store/machine/types/base.ts
ui/src/testing/factories/nodes.ts
ui/src/testing/utils.tsx

- Feature branch for periodic hardware sync
- https://github.com/canonical-web-and-design/maas-ui/pull/3737
Fixes: # . …

feat: periodic hardware sync

---

ui/src/app/base/components/TagSelector/TagSelector.test.tsx
ui/src/app/base/components/TagSelector/TagSelector.tsx
ui/src/app/base/components/TagSelector/__snapshots__/TagSelector.test.tsx.snap
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/AddTagForm/AddTagForm.test.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/AddTagForm/AddTagForm.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/AddTagForm/index.ts
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagFormChanges/TagFormChanges.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagFormFields/TagFormFields.test.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagFormFields/TagFormFields.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/_index.scss
ui/src/app/tags/components/KernelOptionsField/KernelOptionsField.test.tsx
ui/src/app/tags/components/KernelOptionsField/KernelOptionsField.tsx
ui/src/scss/_utilities.scss

- Add a form to create new tags in the machine list tag form.
- Visit the machine list and tick some machines and open the tag form.
- Type a new tag name in the input and click "Create tag".
- Enter some details in the modal and submit.
- The new tag should appear as a green chip.
Fixes: canonical-web-and-design/app-tribe#690.

feat(ui): create tag form

---

ui/src/app/base/components/PowerTypeFields/BasePowerField/BasePowerField.test.tsx
ui/src/app/base/components/PowerTypeFields/BasePowerField/BasePowerField.tsx
ui/src/app/base/components/PowerTypeFields/IPMIPowerFields/IPMIPowerFields.tsx
ui/src/app/base/components/PowerTypeFields/LXDPowerFields/LXDPowerFields.test.tsx
ui/src/app/base/components/PowerTypeFields/LXDPowerFields/LXDPowerFields.tsx
ui/src/app/base/components/PowerTypeFields/LXDPowerFields/index.ts
ui/src/app/base/components/PowerTypeFields/PowerTypeFields.test.tsx
ui/src/app/base/components/PowerTypeFields/PowerTypeFields.tsx
ui/src/app/machines/views/MachineDetails/MachineConfiguration/PowerForm/PowerForm.test.tsx
ui/src/app/machines/views/MachineDetails/MachineConfiguration/PowerForm/PowerForm.tsx
ui/src/app/machines/views/MachineDetails/MachineConfiguration/PowerForm/PowerFormFields/PowerFormFields.test.tsx
ui/src/app/machines/views/MachineDetails/MachineConfiguration/PowerForm/PowerFormFields/PowerFormFields.tsx
ui/src/app/machines/views/MachineDetails/MachineConfiguration/PowerForm/PowerParameters/PowerParameterDefinition/PowerParameterDefinition.test.tsx
ui/src/app/machines/views/MachineDetails/MachineConfiguration/PowerForm/PowerParameters/PowerParameterDefinition/PowerParameterDefinition.tsx
ui/src/app/machines/views/MachineDetails/MachineConfiguration/PowerForm/PowerParameters/PowerParameterDefinition/index.ts
ui/src/app/machines/views/MachineDetails/MachineConfiguration/PowerForm/PowerParameters/PowerParameters.test.tsx
ui/src/app/machines/views/MachineDetails/MachineConfiguration/PowerForm/PowerParameters/PowerParameters.tsx
ui/src/app/machines/views/MachineDetails/MachineConfiguration/PowerForm/PowerParameters/index.ts
ui/src/app/store/machine/types/actions.ts
ui/src/app/store/machine/types/base.ts
ui/src/app/store/types/node.ts

- Built read-only machine power config section
- This replaces the old functionality of it always being a form, with form fields being enabled depending on whether the user was in edit mode.
- Added new components for the read-only section, with common utils being extracted from PowerTypeFields
- Removed "disabled" functionality for PowerTypeFields, since now this can't be done anywhere in the UI
- [Building in a …

feat(ui): build read-only machine power config section

---

ui/src/app/subnets/urls.ts

- fix: default value for subnets search query
- search query value on after deleting a fabric would read `q=undefined` prior to this change
Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/3723 …

fix: default value for subnets search query

---

ui/src/app/base/components/TagSelector/TagSelector.tsx
ui/src/app/base/components/TagSelector/__snapshots__/TagSelector.test.tsx.snap
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagForm.test.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagForm.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagFormChanges/TagFormChanges.test.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagFormChanges/TagFormChanges.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagFormFields/TagFormFields.test.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagFormFields/TagFormFields.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/hooks.test.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/hooks.ts
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/types.ts

- Display removed tags in the machine list tag form.
- Visit the machine list, tick some machines with tags and open the tag form.
- Click the "Remove" button for a tag and it should become a red tag in the "To be removed" section.
Note: the tags won't actually get removed from the machine when the form is submitted (support for that will be in …

feat(ui): remove existing tags

---

ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/DeployForm/DeployForm.test.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/DeployForm/DeployForm.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.test.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.tsx
ui/src/app/store/machine/types/actions.ts

- periodic sync checkbox redux & api integration
- refactor DeployFormFields.test.tsx to testing-library
Review https://github.com/canonical-web-and-design/maas-ui/pull/3745 first
- go to any machine that can be deployed, e.g. on bolla: `/MAAS/r/machine/7c7ya3/summary`
- verify that the checkbox is displayed properly and if …

[Hardware sync] periodic sync checkbox redux & api integration

---

ui/src/app/base/components/ActionForm/ActionForm.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/ActionFormWrapper.test.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/ActionFormWrapper.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagForm.test.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagForm.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagFormChanges/index.ts
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagFormFields/index.ts
ui/src/app/store/machine/actions.test.ts
ui/src/app/store/machine/reducers.test.ts
ui/src/app/store/machine/selectors.test.ts
ui/src/app/store/machine/selectors.ts
ui/src/app/store/machine/slice.ts
ui/src/app/store/machine/types/actions.ts
ui/src/app/store/machine/types/base.ts
ui/src/app/store/machine/types/index.ts
ui/src/app/store/types/node.ts

- Add support for "untag" machine action
- Handle untagging machines when submitting tag form
- Migrate a couple of tests to RTL
- Go to the machine list, select a few machines and select "Tag" from the action menu
- Add and remove some tags then submit the form
- Check that the form closes automatically
- Keep the same machines …

feat(ui): add support for untag machine action

---

ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagFormChanges/TagFormChanges.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/_index.scss

- Increased space for tag names in machine tag form
- Moved Automatic tags help text underneath the table, otherwise it gets super squished. @huwshimi the Zeplin wireframe shows this version as well as the version where it's in the table cell - not sure which one has the right text?
- Go to the machine list, select some machines …

feat(ui): increase space for tag names in machine tag form

---

ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagForm.test.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagForm.tsx

- Display a notification when tag changes have been saved in the machine list.
- Go to the machine list and tick some machines and open the tag form.
- Add or remove some tags and submit.
- When the tag form closes you should see a success notification.
Fixes: canonical-web-and-design/app-tribe#693

feat(ui): machine list tag notification

---

ui/src/app/base/components/ActionForm/ActionForm.test.tsx
ui/src/app/base/components/ActionForm/ActionForm.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagForm.test.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagForm.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagFormFields/TagFormFields.tsx
ui/src/app/machines/views/MachineDetails/MachineConfiguration/TagForm/TagForm.test.tsx
ui/src/app/machines/views/MachineDetails/MachineConfiguration/TagForm/TagForm.tsx

- Surface the tag action form in the machine configuration page
- Go to the Configuration page of a machine
- Click "Edit" in the Tags section
- Add and remove some tags and submit the form
- Check that the form closes and the tags are updated successfully
Fixes canonical-web-and-design/app-tribe#710
Fixes …

feat(ui): show tag action form in machine config page

---

ui/src/app/base/components/TagField/TagField.tsx
ui/src/app/base/components/ZoneSelect/ZoneSelect.tsx
ui/src/app/base/constants.ts
ui/src/app/devices/views/DeviceDetails/DeviceConfiguration/DeviceConfiguration.test.tsx
ui/src/app/devices/views/DeviceDetails/DeviceConfiguration/DeviceConfiguration.tsx
ui/src/app/devices/views/DeviceDetails/DeviceConfiguration/DeviceConfigurationFields/DeviceConfigurationFields.test.tsx
ui/src/app/devices/views/DeviceDetails/DeviceConfiguration/DeviceConfigurationFields/DeviceConfigurationFields.tsx
ui/src/app/devices/views/DeviceDetails/DeviceConfiguration/DeviceConfigurationFields/index.ts
ui/src/app/devices/views/DeviceDetails/DeviceConfiguration/types.ts
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/AddTagForm/AddTagForm.test.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/AddTagForm/AddTagForm.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagForm.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagFormChanges/TagFormChanges.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagFormFields/TagFormFields.tsx
ui/src/app/tags/components/AddTagForm/AddTagForm.test.tsx
ui/src/app/tags/components/AddTagForm/AddTagForm.tsx
ui/src/app/tags/components/AddTagForm/index.ts
ui/src/app/tags/components/KernelOptionsField/KernelOptionsField.tsx

- Made add tag form reusable.
- Add the ability to add new tags from the device config form.
- Go to the details page for a device.
- Click on the config tab and click 'Edit'.
- Type in a new tag form and click "Create...".
- The modal should appear.
- Fill out the details and submit.
- The new tag name should appear in the input.
- Submit the form and the …

feat(ui): add tags from the device config form

---

ui/src/app/base/components/EditableSection/EditableSection.test.tsx
ui/src/app/base/components/EditableSection/EditableSection.tsx
ui/src/app/base/components/EditableSection/index.ts
ui/src/app/base/components/TitledSection/TitledSection.test.tsx
ui/src/app/base/components/TitledSection/TitledSection.tsx
ui/src/app/base/components/TitledSection/index.ts
ui/src/app/machines/views/MachineDetails/MachineConfiguration/MachineConfiguration.tsx
ui/src/app/machines/views/MachineDetails/MachineConfiguration/MachineForm/MachineForm.test.tsx
ui/src/app/machines/views/MachineDetails/MachineConfiguration/MachineForm/MachineForm.tsx
ui/src/app/machines/views/MachineDetails/MachineConfiguration/PowerForm/PowerForm.test.tsx
ui/src/app/machines/views/MachineDetails/MachineConfiguration/PowerForm/PowerForm.tsx
ui/src/app/machines/views/MachineDetails/MachineConfiguration/TagForm/TagForm.test.tsx
ui/src/app/machines/views/MachineDetails/MachineConfiguration/TagForm/TagForm.tsx

- Updated `TitledSection` component to be able to have the title in a sidebar
- Built `EditableSection` component, that handles showing an edit button in a titled section
- Go to the Configuration tab of a machine
- Check that the config sections haven't changed (i.e. title is in sidebar, clicking Edit hides the button)
- Go to …

feat(ui): create common EditableSection component

---

ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/StatusCard/StatusCard.tsx
ui/src/scss/_patterns_links.scss

- use a standard (blue) link variant in hardware sync tooltip
- source: https://chat.canonical.com/canonical/pl/bk669n8wwfywudgtbmr11xtgph
Fixes: https://github.com/canonical-web-and-design/app-tribe/issues/799 …

use standard link variant in hardware sync tooltip

---

ui/src/app/tags/components/DefinitionField/DefinitionField.test.tsx
ui/src/app/tags/components/DefinitionField/DefinitionField.tsx
ui/src/app/tags/components/KernelOptionsField/KernelOptionsField.tsx
ui/src/app/tags/views/TagList/TagTable/TagTable.tsx
ui/src/app/tags/views/TagUpdate/TagUpdateFormFields/TagUpdateFormFields.tsx

- update tag management docs links
- Verify that links work correctly (their placement is described in issues linked to this PR)
Fixes: https://github.com/canonical-web-and-design/app-tribe/issues/739
Fixes: https://github.com/canonical-web-and-design/app-tribe/issues/748
In …

[tag management] update docs links

---

ui/src/app/tags/components/AppliedTo/AppliedTo.test.tsx
ui/src/app/tags/components/NodesTagsLink/NodesTagsLink.test.tsx
ui/src/app/tags/components/NodesTagsLink/NodesTagsLink.tsx
ui/src/app/tags/views/TagList/TagTable/TagTable.test.tsx

Use == for machine listing link to get an exact match
From Tags list, with a tag that applies to a machine or many machines, click the link to machines (or controllers, or devices).
Re: https://github.com/canonical-web-and-design/app-tribe/issues/801

fix(ui): use == in NodesTagsLink

---

legacy/src/app/controllers/node_details.js
legacy/src/app/controllers/tests/test_node_details.js
legacy/src/app/factories/tags.js
legacy/src/app/factories/tests/test_tags.js
legacy/src/app/partials/node-details.html

- Create tags and apply them to the controller in the config form.
This can't properly be QAed until controllers have permissions restored: https://bugs.launchpad.net/maas/+bug/1967704.
- Update the `canEdit` function to return true: https://github.com/canonical-web-and-design/maas-ui/blob/master/legacy/src/app/controllers/node_details.js#L775.
- Open the …

feat(legacy): create tags in the controller config form

---

ui/src/app/base/components/GroupCheckbox/GroupCheckbox.test.tsx
ui/src/app/base/components/GroupCheckbox/GroupCheckbox.tsx
ui/src/app/base/components/GroupCheckbox/__snapshots__/GroupCheckbox.test.tsx.snap
ui/src/app/machines/views/MachineList/MachineListTable/MachineListTable.test.tsx
ui/src/app/machines/views/MachineList/MachineListTable/MachineListTable.tsx
ui/src/scss/_patterns_forms.scss

- Use Vanilla `aria-checked` handling and remove local overrides
- Fixed logic for display mixed checkboxes in the grouped machine list
- Go to the machine list and select some, but not all, machines in a group
- Check that the group checkboxes show up as mixed
- Select all machines in a group
- The checkbox should show up as …

fix(ui): fix display of mixed selection checkboxes

---

ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagForm.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagFormChanges/TagFormChanges.test.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagFormChanges/TagFormChanges.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagFormFields/TagFormFields.test.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagFormFields/TagFormFields.tsx

- Show "NEW" prefix in tag chip for newly created tags
- Go to the machine list, select some machines and choose "Tag" from the action menu
- Select some existing tags and check that they don't show "NEW" in the chip
- Enter a new tag name in the input and click "Create tag ${name}"
- Submit the modal form
- Check that the new …

feat(ui): show "NEW" prefix for newly created tags in machine tag form

---

ui/src/app/base/validation.ts
ui/src/app/tags/components/TagsHeader/AddTagForm/AddTagForm.test.tsx
ui/src/app/tags/components/TagsHeader/AddTagForm/AddTagForm.tsx

- Added validation for tag name in add tag form (regex comes from the backend code)
- Go to the tag list and click "Create new tag"
- Enter an invalid tag name (e.g. with spaces) and blur the field
- Check that an error message shows

feat(ui): add validation to tag name in add tag form

---

ui/src/app/devices/views/DeviceDetails/DeviceConfiguration/DeviceConfiguration.test.tsx
ui/src/app/devices/views/DeviceDetails/DeviceConfiguration/DeviceConfiguration.tsx
ui/src/app/domains/views/DomainDetails/DomainSummary/DomainSummary.test.tsx
ui/src/app/domains/views/DomainDetails/DomainSummary/DomainSummary.tsx
ui/src/app/domains/views/DomainDetails/ResourceRecords/ResourceRecords.tsx
ui/src/app/subnets/views/FabricDetails/EditFabric/EditFabric.tsx
ui/src/app/subnets/views/FabricDetails/FabricSummary/FabricSummary.test.tsx
ui/src/app/subnets/views/FabricDetails/FabricSummary/FabricSummary.tsx
ui/src/app/subnets/views/SpaceDetails/SpaceSummary/SpaceSummary.test.tsx
ui/src/app/subnets/views/SpaceDetails/SpaceSummary/SpaceSummary.tsx
ui/src/app/subnets/views/SpaceDetails/SpaceSummary/SpaceSummaryForm/SpaceSummaryForm.tsx
ui/src/app/subnets/views/SubnetDetails/SubnetSummary/SubnetSummary.tsx
ui/src/app/subnets/views/VLANDetails/VLANSummary/VLANSummary.tsx
ui/src/app/zones/views/ZoneDetails/ZoneDetails.test.tsx
ui/src/app/zones/views/ZoneDetails/ZoneDetails.tsx
ui/src/app/zones/views/ZoneDetails/ZoneDetailsContent/ZoneDetailsContent.tsx
ui/src/app/zones/views/ZoneDetails/ZoneDetailsForm/ZoneDetailsForm.tsx

- Use `EditableSection` component wherever we use a section with an "Edit" button in the header strip
- Minor tidy up of some styling inconsistencies in these sections (using `Definition` component, including borders above buttons in forms, etc)
- Check that the editable sections look consistent and work across the following …

refactor(ui): standardise use of EditableSection component

---

ui/src/app/base/components/FabricSelect/FabricSelect.tsx
ui/src/app/base/components/LinkModeSelect/LinkModeSelect.tsx
ui/src/app/base/components/SubnetSelect/SubnetSelect.tsx
ui/src/app/base/components/VLANSelect/VLANSelect.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkFields/NetworkFields.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkFields/NetworkFields.tsx

- Fix unsetting an interface's IP mode when the subnet is set to unconfigured.
- Go to the network tab for a machine where the network is editable and has a subnet and a physical interface that is set to "Auto assign" (or update an interface to this state).
- Open the edit form for the interface.
- Open the Subnet select and change it to "Unconfigured".
- …

fix(ui): unset IP mode when removing subnet

---

ui/src/app/base/components/DHCPTable/DHCPTable.tsx
ui/src/app/base/components/SSHKeyForm/SSHKeyFormFields/SSHKeyFormFields.tsx
ui/src/app/controllers/components/ControllerHeaderForms/AddController/AddController.tsx
ui/src/app/controllers/views/ControllerList/ControllerListTable/StatusColumn/StatusColumn.tsx
ui/src/app/dashboard/views/DashboardHeader/ClearAllForm/ClearAllForm.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.tsx
ui/src/app/preferences/views/SSHKeys/SSHKeyList/SSHKeyList.tsx
ui/src/app/settings/views/Configuration/CommissioningFormFields/CommissioningFormFields.tsx
ui/src/app/settings/views/Configuration/GeneralForm/GeneralForm.tsx
ui/src/app/subnets/components/ReservedRanges/ReservedRanges.tsx
ui/src/app/subnets/views/VLANDetails/ConfigureDHCP/ConfigureDHCP.tsx
ui/src/app/subnets/views/VLANDetails/DHCPStatus/DHCPStatus.tsx
ui/src/app/tags/components/DefinitionField/DefinitionField.tsx
ui/src/app/tags/components/KernelOptionsField/KernelOptionsField.tsx
ui/src/app/tags/views/TagList/TagTable/TagTable.tsx
ui/src/app/tags/views/TagUpdate/TagUpdateFormFields/TagUpdateFormFields.tsx

- Open all external links in a new tab.
- Visit the tag list and open the create tag form.
- Click on the links in the help text open in new tabs.
- Go to the machine list, tick some machines and open the tag form.
- Type in a new tag name and open the create tag modal.
- Check that the help links open in a new tab.
Fixes: …

fix(ui): open links in new tab

---

ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagFormChanges/TagFormChanges.test.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagFormChanges/TagFormChanges.tsx

- Display a message in tag form if no machines have tags
- Go to the machine list and select one or more machines that do not have any tags
- Open the tag form and check there is a message

feat(ui): display a message in tag form if no machines have tags

---

ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/DeployForm/DeployForm.test.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/DeployForm/DeployForm.tsx

- Make sure OS info is loaded before initialising deploy form. I'm not fully convinced this will fix the original issue (that I could not reproduce), but the problem was that the form was not initialising values properly so I'm hoping this addresses it.
- N/A
Fixes #3558

fix(ui): make sure OS info is loaded before initialising deploy form

---

ui/src/app/machines/views/MachineDetails/MachineNetwork/EditAliasOrVlanForm/EditAliasOrVlanForm.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/EditAliasOrVlanForm/EditAliasOrVlanForm.tsx

- Fixed the "Edit VLAN" form inadvertently creating an alias
- Go to the Network tab for a machine
- Add a physical interface that's connected to a fabric with at least one unused VLAN and at least one subnet
- For the new interface, open the action menu and click "Add VLAN"
- Choose a VLAN and subnet and give it an Auto IP mode …

fix(ui): fix edit VLAN form inadvertently creating an alias

---

ui/src/app/base/components/FormikField/FormikField.test.tsx
ui/src/app/base/components/FormikField/FormikField.tsx
ui/src/app/base/components/FormikForm/FormikForm.tsx
ui/src/app/base/components/FormikFormContent/FormikFormContent.test.tsx
ui/src/app/base/components/FormikFormContent/FormikFormContent.tsx
ui/src/app/base/components/NodeName/NodeName.test.tsx
ui/src/app/base/components/NodeName/NodeName.tsx
ui/src/app/base/components/NodeName/NodeNameFields/NodeNameFields.test.tsx
ui/src/app/base/components/NodeName/NodeNameFields/NodeNameFields.tsx
ui/src/app/base/components/NodeName/NodeNameFields/__snapshots__/NodeNameFields.test.tsx.snap
ui/src/app/base/components/NodeName/__snapshots__/NodeName.test.tsx.snap
ui/src/app/base/components/NodeName/_index.scss
ui/src/app/base/components/SectionHeader/SectionHeader.test.tsx
ui/src/app/base/components/SectionHeader/SectionHeader.tsx
ui/src/app/base/components/SectionHeader/__snapshots__/SectionHeader.test.tsx.snap
ui/src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.tsx

- Fix broken machine name validation appearance.
- Improved responsive display.
- Go to a machine details page.
- Click on the machine's name in the header to open the form.
- Add an invalid character e.g. !@#$%^&*(). The validation error should appear below the form.
Fixes: #3337.

fix(ui): fix machine name validation

---

ui/src/app/base/components/NodeName/NodeNameFields/NodeNameFields.tsx
ui/src/app/base/components/NodeName/NodeNameFields/__snapshots__/NodeNameFields.test.tsx.snap
ui/src/app/base/components/NodeName/__snapshots__/NodeName.test.tsx.snap
ui/src/app/base/components/NodeName/_index.scss

- Improve the display of the auto-sizing machine name field so that the content doesn't get cut off
after clearing the field.
- Go to a machine details page.
- Click on the name to open the form.
- Clear the name and start typing.
- The input should nicely adjust to the size of the text as you type (and it shouldn't get cut off a the edges).
Fixes: #3341.

fix(ui): fix machine name after removing all content

---

integration/cypress/integration/machines/list.spec.ts

- disable that annoying eslint cypress/no-force warning for the single line where we use `click({ force})`
Fixes: # . …

disable eslint cypress/no-force warning

---

ui/package.json
ui/src/app/base/components/FormikField/__snapshots__/FormikField.test.tsx.snap
ui/src/app/base/components/FormikFormButtons/FormikFormButtons.test.tsx
ui/src/app/base/components/NodeName/NodeNameFields/__snapshots__/NodeNameFields.test.tsx.snap
ui/src/app/base/components/NodeName/__snapshots__/NodeName.test.tsx.snap
ui/src/app/base/components/TagSelector/__snapshots__/TagSelector.test.tsx.snap
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.test.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.tsx
ui/src/app/machines/views/MachineList/MachineListTable/CoresColumn/__snapshots__/CoresColumn.test.tsx.snap
ui/src/app/machines/views/MachineList/MachineListTable/NameColumn/__snapshots__/NameColumn.test.tsx.snap
ui/src/app/machines/views/MachineList/MachineListTable/PowerColumn/__snapshots__/PowerColumn.test.tsx.snap
yarn.lock

- update @canonical/react-components to v0.34.1
- this release includes the tooltip fix https://github.com/canonical-web-and-design/react-components/releases/tag/v0.34.1
- use help text prop in DeployFormFields
- select a machine that can be deployed (e.g. `/r/machine/c7mn8b/summary` on bolla) from the machines list and go to …

fix(deps): update dependency @canonical/react-components to v0.34.1

---

ui/src/app/base/components/ControllerLink/ControllerLink.tsx
ui/src/app/base/components/DeviceLink/DeviceLink.tsx
ui/src/app/base/components/FabricLink/FabricLink.tsx
ui/src/app/base/components/MachineLink/MachineLink.tsx
ui/src/app/base/components/SectionHeader/SectionHeader.tsx
ui/src/app/base/components/SpaceLink/SpaceLink.tsx
ui/src/app/base/components/SubnetLink/SubnetLink.tsx
ui/src/app/base/components/VLANLink/VLANLink.tsx

- add `aria-label` and `data-testid` directly to Spinner component
Fixes: https://github.com/canonical-web-and-design/app-tribe/issues/817
In general, please propose fixes against *master* rather than release branches (e.g. 2.7), unless the fix is only …

refactor: add aria-label directly to Spinner component

---

ui/src/app/base/components/StatusBar/StatusBar.test.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.test.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.tsx
ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/StatusCard/StatusCard.test.tsx
ui/src/app/store/machine/types/base.ts
ui/src/app/store/machine/utils/common.ts
ui/src/app/utils/timeSpan.test.ts
ui/src/app/utils/timeSpan.ts
ui/src/testing/factories/nodes.ts

- verify hardware sync back-end integration
- refactor timeSpan with date-fns
- add HardwareSyncFields type for better type safety, more info below.
```tsx
type HardwareSyncFields =
| {
enable_hw_sync: false;
}
| {
enable_hw_sync: true;
last_sync: string;
next_sync: string;
is_sync_healthy: boolean;
sync_interval: Seconds;
};
```
Now the code below will throw an error (and rightly so, as `is_sync_healthy` won't be added to the machine details object if the hardware sync is not enabled.
```javascript
export const getHasSyncFailed = (machine?: Machine | null): boolean => {
if (!isMachineDetails(machine)) {
return false;
}
return machine.is_sync_healthy === false;
};
```
This can be fixed by checking whether `machine.enable_hw_sync` is true and the rest of keys will exist on the machine …

[periodic hardware sync] verify back-end integration

---

ui/src/app/settings/components/Nav/Nav.tsx
ui/src/app/settings/components/Routes/Routes.tsx
ui/src/app/settings/urls.ts
ui/src/app/settings/views/Configuration/Security/Security.test.tsx
ui/src/app/settings/views/Configuration/Security/Security.tsx
ui/src/app/settings/views/Configuration/Security/TLSDisabled/TLSDisabled.tsx
ui/src/app/settings/views/Configuration/Security/TLSDisabled/index.ts
ui/src/app/settings/views/Configuration/Security/TLSEnabled/TLSEnabled.tsx
ui/src/app/settings/views/Configuration/Security/TLSEnabled/index.ts
ui/src/app/settings/views/Configuration/Security/index.ts
ui/src/app/store/general/utils/index.ts
ui/src/scss/index.scss

- Added Security tab to Settings page
- Built "TLS disabled" version of the page (though it's missing the correct docs link, will address in a follow up when it's ready)
- Go to the Settings page and check that there is a Security tab under Configuration
- Click on the Security tab and check that it looks like [the design for …

feat(ui): add Security tab to Settings page

---

ui/src/app/base/components/StatusBar/StatusBar.tsx
ui/src/app/machines/views/MachineDetails/MachineSummary/SummaryNotifications/SummaryNotifications.test.tsx
ui/src/app/machines/views/MachineDetails/MachineSummary/SummaryNotifications/SummaryNotifications.tsx
ui/src/app/store/machine/utils/common.test.ts
ui/src/app/store/machine/utils/common.ts
ui/src/app/utils/timeSpan.test.ts

- hide sync failure for deploying machines
- add shouldShowHardwareSyncStatus util
- deploy a machine with "periodic hardware sync" checkbox enabled
- Make sure "hardware sync failed" notification is not displayed for a machine that is in "deploying" state
Fixes: https://github.com/canonical-web-and-design/app-tribe/issues/814 …

[periodic hardware sync] - QA fixes

---

ui/src/app/base/types.ts
ui/src/app/preferences/views/APIAuthentication/TLSCertificate/TLSCertificate.test.tsx
ui/src/app/preferences/views/APIAuthentication/TLSCertificate/TLSCertificate.tsx
ui/src/app/settings/views/Configuration/Security/Security.test.tsx
ui/src/app/settings/views/Configuration/Security/Security.tsx
ui/src/app/store/config/selectors.test.ts
ui/src/app/store/config/selectors.ts
ui/src/app/store/general/types/base.ts
ui/src/app/store/general/utils/certificates.test.ts
ui/src/app/store/general/utils/certificates.ts
ui/src/app/store/general/utils/index.ts
ui/src/app/utils/timeSpan.ts

- Added selectors for TLS expiration notification config
- Updated API shape for `general.tls_certificate` to remove the empty object case and removed the util that handled that case
- N/A
Fixes canonical-web-and-design/app-tribe#819

feat(ui): add selectors for TLS expiration notification config

---

ui/src/app/settings/views/Configuration/Security/TLSEnabled/TLSEnabled.test.tsx
ui/src/app/settings/views/Configuration/Security/TLSEnabled/TLSEnabled.tsx
ui/src/app/settings/views/Configuration/Security/TLSEnabled/TLSEnabledFields/TLSEnabledFields.tsx
ui/src/app/settings/views/Configuration/Security/TLSEnabled/TLSEnabledFields/_index.scss
ui/src/app/settings/views/Configuration/Security/TLSEnabled/TLSEnabledFields/index.ts
ui/src/app/store/config/types/enum.ts
ui/src/app/store/config/types/index.ts
ui/src/scss/index.scss

- Built "TLS enabled" version of security settings
- To test the "TLS enabled" security settings you will need to either:
- Enable TLS for real using `sudo maas config-tls enable $path-to-key $path-to-cert` (if you use the snap the cert files will need to be located in `/var/snap/maas`), or;
- Fake a TLS certificate.
- Open …

feat(ui): build "TLS enabled" version of security settings

---

proxy/index.js
proxy/ui.js

- Fixed proxy server crashing when using a TLS-enabled MAAS (by stopping it from verifying certificates - shouldn't matter just for local development)
- Check that a MAAS without TLS still works (e.g. bolla) for both `yarn start` and `yarn ui` development servers. The Settings > Configuration > Security page should say "TLS …

fix(proxy): fix proxy server crashing when proxying to TLS-enabled MAAS

---

ui/src/app/base/components/ModelListSubtitle/ModelListSubtitle.tsx
ui/src/app/base/components/NotificationGroup/NotificationGroup.tsx
ui/src/app/base/components/NotificationGroup/__snapshots__/NotificationGroup.test.tsx.snap
ui/src/app/base/components/UserForm/UserForm.tsx
ui/src/app/base/components/node/NodeActionFormWrapper/NodeActionFormWrapper.tsx
ui/src/app/images/views/ImageList/SyncedImages/ChangeSource/FetchImagesForm/FetchImagesFormFields/FetchImagesFormFields.tsx
ui/src/app/machines/views/MachineDetails/MachineSummary/TestResults/TestResults.tsx

- Previously I removed the custom `p-button--link` class we used in favour of Vanilla's, assuming it was basically identical. It wasn't! The Vanilla version includes margin like a normal button, so I've removed the margin in places where we don't want it.
- Check there is no margin in link buttons:
- Machine list > Select some …

fix(ui): fix instances of link buttons having incorrect spacing

---

ui/src/app/preferences/views/APIAuthentication/TLSCertificate/TLSCertificate.test.tsx
ui/src/app/preferences/views/APIAuthentication/TLSCertificate/TLSCertificate.tsx
ui/src/app/settings/views/Configuration/Security/TLSEnabled/TLSEnabled.test.tsx
ui/src/app/settings/views/Configuration/Security/TLSEnabled/TLSEnabled.tsx
ui/src/app/store/config/types/enum.ts

- Removed download button from TLS enabled page.
- Hide TLS section in user preferences if TLS is not enabled.
- Change lower limit for TLS expiry notification from 0 days to 1 day.
- For a MAAS with TLS disabled:
- Check that there is no "TLS fingerprint" section in User preferences > API authentication
- For a MAAS with TLS …

fix(ui): update TLS sections based on latest changes

---

ui/src/app/kvm/components/KVMHeaderForms/ComposeForm/ComposeFormFields/ComposeFormFields.tsx
ui/src/app/kvm/components/KVMHeaderForms/ComposeForm/StorageTable/StorageTable.tsx
ui/src/app/kvm/components/LXDVMsTable/VMsActionBar/VMsActionBar.tsx
ui/src/app/kvm/views/KVMList/LxdTable/LxdKVMHostTable/LxdKVMHostTable.tsx
ui/src/app/kvm/views/KVMList/LxdTable/LxdTable.tsx
ui/src/app/kvm/views/KVMList/VirshTable/VirshTable.tsx
ui/src/app/kvm/views/LXDClusterDetails/LXDClusterHosts/LXDClusterHostsActionBar/LXDClusterHostsActionBar.tsx

- Removed infinitely nested rows in KVM list tables
- Minor styling fixes in KVM details
- Check that the LXD and Virsh KVM lists are unchanged visually
- Go to a LXD single host details page and check that the table action bar buttons are aligned properly
- Click "Add virtual machine"
- Check that there isn't a huge gap between …

fix(ui) fix minor styling bugs in KVM pages

---

ui/src/app/subnets/views/SubnetsList/SubnetsControls/SubnetsControls.tsx
ui/src/app/subnets/views/SubnetsList/_index.scss

- Fix the subnets page that was breaking the page layout at certain sizes.
- Click Subnets in the header.
- Resize your window and check that at about 1050 pixels wide the help icon next to the grouping select box does not disappear or break out of the frame (See the issue for reference: …

fix(ui): fix subnets icon breaking layout

---

ui/src/app/machines/views/MachineDetails/MachineNetwork/AddAliasOrVlan/AddAliasOrVlan.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/AddAliasOrVlan/AddAliasOrVlan.tsx

- Cherry-pick commit from https://github.com/canonical-web-and-design/maas-ui/pull/3796
- Go to the Network tab of a Ready or Allocated machine
- Add an interface with a configured IP mode (i.e. select a subnet and IP mode in the form)
- Click the action dropdown and select "Add alias"
- Check that the fabric and VLAN selects …

fix(ui): select correct fabric/VLAN when adding an alias or VLAN to nic (#3796)

---

ui/src/app/base/components/NodeName/NodeName.tsx
ui/src/app/base/components/NodeName/__snapshots__/NodeName.test.tsx.snap
ui/src/app/base/validation.test.ts
ui/src/app/base/validation.ts
ui/src/app/dashboard/views/DiscoveryAddForm/DiscoveryAddForm.tsx
ui/src/app/devices/components/DeviceHeaderForms/AddDeviceForm/AddDeviceForm.tsx
ui/src/app/kvm/components/KVMHeaderForms/ComposeForm/ComposeForm.tsx
ui/src/app/machines/components/MachineHeaderForms/AddMachine/AddMachineForm/AddMachineForm.tsx

- Update all node forms to use the same hostname validation.
- Check that the add machine, add device etc. forms validate the hostname length and characters.
Fixes: #3806.

feat(ui): add hostname validation for all node forms

---

.github/workflows/cypress.yml
integration/cypress.json
integration/cypress/integration/base/header.spec.ts
integration/cypress/support/commands.ts
integration/cypress/support/index.ts

- fix: cypress non admin header test for non-admin user (this only worked accidentally as we were logging in as an admin user)
- add test case for clicking on the logo as an admin
- add an ability to run tests when logged in as a non-admin user via `cy.loginNonAdmin()`
Note: Includes fixes from https://github.com/canonical-web-and-design/maas-ui/pull/3849, you may want to review it first 
- [Building in a …

fix: cypress non admin header test

---

ui/src/app/base/components/Definition/Definition.test.tsx
ui/src/app/base/components/Definition/Definition.tsx

- display alternative text for empty string as description
- Go to a space summary page with an empty description and verify that "-" is displayed.
Fixes: https://github.com/canonical-web-and-design/app-tribe/issues/868
In general, please propose fixes against *master* rather …

fix: display alternative text for empty string

---

legacy/src/app/partials/cards/tags.html

- fix: invalid links to tags on controllers page (tag id was being used instead of a tag name)
- Go to controller details page (e.g. http://bolla.internal:5240/MAAS/l/controller/knpge8) and click on a link to controller
- Controllers list should be displayed with a correct tag in the search input field and controllers 
Fixes: …

fix: invalid links to tags on controllers page

---

integration/cypress/integration/controllers/list.spec.ts
legacy/src/app/partials/cards/tags.html
legacy/src/app/partials/node-details.html
ui/src/app/controllers/views/ControllerList/ControllerListTable/ControllerListTable.tsx

- add e2e test for controllers tag management
- this currently fails as the configuration tab is broken but will work once that's fixed https://github.com/canonical-web-and-design/maas-ui/issues/3728
Fixes: https://github.com/canonical-web-and-design/app-tribe/issues/882 …

add e2e tests for controllers tag management 

---

ui/src/app/subnets/views/FabricDetails/FabricVLANs/FabricVLANs.tsx
ui/src/app/subnets/views/FabricDetails/FabricVLANs/_index.scss

- Fixed the mobile card styling of the "VLANs on this fabric" table. Vanilla 3 changed the mobile card breakpoint from medium to large which was no accounted for here.
- Go to the details page of a fabric that has a VLAN with at least 2 subnets (e.g. `/MAAS/r/fabric/249` on bolla).
- Resize the screen to <1035px to change the …

fix(ui): fix mobile styling of "VLANs on this fabric" table

---

ui/src/app/base/components/NodeSummaryNetworkCard/NetworkCardTable/NetworkCardTable.tsx
ui/src/app/kvm/components/KVMHeaderForms/ComposeForm/InterfacesTable/InterfacesTable.test.tsx
ui/src/app/kvm/components/KVMHeaderForms/ComposeForm/InterfacesTable/InterfacesTable.tsx
ui/src/app/kvm/components/KVMHeaderForms/ComposeForm/StorageTable/StorageTable.tsx

- Fixed mobile tables in node summary network card and KVM compose form.
- Resize the screen to mobile size
- Go to a machine's details page and check that the network card shows the table headers
- Go to a KVM's details page and click "Add machine"
- Check that the interfaces and storage tables show the table headers
Fixes …

fix(ui): fix table headings on small screens for non-MainTables

---

ui/src/app/base/components/DHCPTable/DHCPTable.tsx
ui/src/app/base/components/SSHKeyForm/SSHKeyFormFields/SSHKeyFormFields.tsx
ui/src/app/base/docsUrls.ts
ui/src/app/base/maasDocsUrls.ts
ui/src/app/controllers/components/ControllerHeaderForms/AddController/AddController.tsx
ui/src/app/dashboard/views/DashboardHeader/ClearAllForm/ClearAllForm.tsx
ui/src/app/intro/views/IncompleteCard/IncompleteCard.tsx
ui/src/app/intro/views/IncompleteCard/__snapshots__/IncompleteCard.test.tsx.snap
ui/src/app/intro/views/MaasIntro/NameCard/NameCard.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.tsx
ui/src/app/machines/components/MachineHeaderForms/AddChassis/AddChassisForm/AddChassisForm.tsx
ui/src/app/machines/components/MachineHeaderForms/AddMachine/AddMachineForm/AddMachineForm.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/MachineStorage.tsx
ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/StatusCard/StatusCard.test.tsx
ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/StatusCard/StatusCard.tsx
ui/src/app/preferences/views/SSHKeys/SSHKeyList/SSHKeyList.tsx
ui/src/app/settings/views/Configuration/CommissioningFormFields/CommissioningFormFields.tsx
ui/src/app/settings/views/Dhcp/DhcpList/DhcpList.tsx
ui/src/app/subnets/components/ReservedRanges/ReservedRanges.tsx
ui/src/app/subnets/views/VLANDetails/ConfigureDHCP/ConfigureDHCP.tsx
ui/src/app/subnets/views/VLANDetails/DHCPStatus/DHCPStatus.tsx
ui/src/app/tags/components/DefinitionField/DefinitionField.tsx
ui/src/app/tags/components/KernelOptionsField/KernelOptionsField.tsx
ui/src/app/tags/views/TagList/TagTable/TagTable.tsx
ui/src/app/tags/views/TagUpdate/TagUpdateFormFields/TagUpdateFormFields.tsx

- move all maas.io/docs links to docsUrls
Fixes: https://github.com/canonical-web-and-design/app-tribe/issues/879 …

fix(ui): update redirects & broken maas.io docs links

---

ui/src/app/settings/views/Configuration/Security/TLSEnabled/TLSEnabled.test.tsx
ui/src/app/settings/views/Configuration/Security/TLSEnabled/TLSEnabled.tsx

- Update the security settings form to wait for the data to be loaded before initialising the form. This fixes a race condition where the form could be initialising before the config values were loaded.
- Enable TLS for your MAAS (the first few steps in this issue: https://github.com/canonical-web-and-design/app-tribe/issues/847).
- Go to Settings -> Security …

fix(ui): fix security form not showing saved values

---

ui/src/app/settings/views/Configuration/Security/TLSEnabled/TLSEnabled.tsx

- Update the TLS notification checkbox wording to add "when".
- Enable TLS for your MAAS (the first few steps in this issue: https://github.com/canonical-web-and-design/app-tribe/issues/847).
- Go to Settings -> Security (/MAAS/r/settings/configuration/security).
- Check that the checkbox label includes the word "when".
Fixes: …

fix(ui): improve TLS checkbox wording

---

legacy/src/scss/_vanilla-overrides.scss
legacy/src/scss/build.scss
ui/src/scss/_vanilla-overrides.scss

- Fix the width of the logout button in the mobile menu.
- Run the full client (`yarn start`).
- Go to a react page and resize down to mobile width.
- Open the mobile navigation menu.
- Check that the logout button is full width.
- Go to a controller details page and resize down to mobile width.
- Open the mobile navigation menu.
- Check that the logout …

fix(ui): fix mobile logout button width

---

ui/src/app/subnets/views/FormActions/components/AddFabric.test.tsx
ui/src/app/subnets/views/FormActions/components/AddFabric.tsx
ui/src/app/subnets/views/FormActions/components/AddSpace.test.tsx
ui/src/app/subnets/views/FormActions/components/AddSpace.tsx
ui/src/app/subnets/views/FormActions/components/AddSubnet.test.tsx
ui/src/app/subnets/views/FormActions/components/AddSubnet.tsx
ui/src/app/subnets/views/FormActions/components/AddVlan.test.tsx
ui/src/app/subnets/views/FormActions/components/AddVlan.tsx

- Include store cleanup actions for fabric, VLAN, subnet and space add forms.
- Go to the subnets list and click "Add" > "Space"
- Enter the name of a space that already exists and submit. You should see an error.
- Close the form and open it again. The error should no longer be showing.
- Submit the form with the same name as …

fix(ui): add cleanup actions to add network model forms

---

ui/src/app/subnets/views/FabricDetails/FabricDetailsHeader/FabricDeleteForm/FabricDeleteForm.tsx
ui/src/app/subnets/views/SpaceDetails/SpaceDetailsHeader/SpaceDelete/SpaceDelete.tsx
ui/src/app/subnets/views/SpaceDetails/SpaceDetailsHeader/SpaceDetailsHeader.test.tsx
ui/src/app/subnets/views/SpaceDetails/SpaceDetailsHeader/SpaceDetailsHeader.tsx
ui/src/app/subnets/views/SubnetDetails/SubnetDetailsHeader/SubnetActionForms/components/DeleteSubnet/DeleteSubnet.tsx
ui/src/app/subnets/views/VLANDetails/VLANDetailsHeader/VLANDeleteForm/VLANDeleteForm.tsx

- Standardise how each of the network delete forms work, i.e. notifications, cleanup, styling.
- Go to the subnets list and delete one of each of a fabric, VLAN, subnet and space
- Check that they all function the same way
Fixes canonical-web-and-design/app-tribe#884

refactor(ui): use the same structure for each network model delete form

---

ui/src/app/machines/views/MachineDetails/MachineLogs/DownloadMenu/DownloadMenu.tsx
ui/src/app/machines/views/MachineDetails/MachineLogs/DownloadMenu/_index.scss
ui/src/app/machines/views/MachineDetails/MachineLogs/MachineLogs.tsx
ui/src/scss/_utilities.scss

- Fixed styling of machine logs download button
- Go to the "Logs" tab for a machine
- Check that the "Download" button looks normal on all screen sizes
Fixes canonical-web-and-design/app-tribe#874

fix(ui): fix styling of machine logs download button

---

ui/src/app/base/docsUrls.ts
ui/src/app/settings/views/Configuration/Security/TLSDisabled/TLSDisabled.tsx
ui/src/app/settings/views/Configuration/Security/TLSEnabled/TLSEnabledFields/TLSEnabledFields.tsx

- Added docs links to native TLS pages
- Go to the Settings > Security page of a MAAS with TLS disabled
- Check that the docs link takes you [here](https://maas.io/docs/how-to-enable-tls-encryption#heading--about-maas-native-tls)
- Go to the Settings > Security page of a MAAS with TLS enabled
- Check that the docs link takes you …

feat(ui): add docs links to native TLS pages

---

ui/src/app/base/components/TagSelector/TagSelector.test.tsx
ui/src/app/base/components/TagSelector/TagSelector.tsx

- fix: cursive highlighted text looks broken
Fixes: https://github.com/canonical-web-and-design/app-tribe/issues/890 …

fix: cursive highlighted text looks broken

---

ui/src/app/base/components/ActionForm/ActionForm.tsx
ui/src/app/base/components/NodeActionConfirmationText/NodeActionConfirmationText.test.tsx
ui/src/app/base/components/NodeActionConfirmationText/NodeActionConfirmationText.tsx
ui/src/app/base/components/NodeActionConfirmationText/index.ts
ui/src/app/base/components/node/DeleteForm/DeleteForm.tsx
ui/src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.tsx
ui/src/app/store/utils/index.ts
ui/src/app/store/utils/node/base.ts

- fix: delete machine is missing machine name
- add NodeActionConfirmationText component
- Try to delete a machine/multiple machines and verify that their names are displayed in the confirmation dialog.
Fixes: https://github.com/canonical-web-and-design/app-tribe/issues/887 …

fix: delete machine is missing machine name

---

integration/cypress/integration/with-users/devices/list.spec.ts

- add e2e test for device tagging
Fixes: # .
In general, please propose fixes against *master* rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. Please apply backport labels to the PR (e.g. "Backport 2.7") …

add e2e test for device tagging

---

ui/src/app/base/components/DHCPTable/DHCPTable.tsx
ui/src/app/base/components/DhcpSnippetType/DhcpSnippetType.test.tsx
ui/src/app/base/components/DhcpSnippetType/DhcpSnippetType.tsx
ui/src/app/base/components/DhcpSnippetType/DhcpType.test.tsx
ui/src/app/base/components/DhcpSnippetType/index.ts
ui/src/app/settings/hooks.ts
ui/src/app/settings/views/Dhcp/DhcpList/DhcpList.tsx

- display consistent dhcp snippet type
- Add a DHCP snippet for each type via settings - `MAAS/r/settings/dhcp` (machine, device, subnet and global) and apply to one of the items on the list
-  verify that a correct type is displayed on the details page (e.g. subnet details) page and in the settings
Fixes: …

fix: display consistent dhcp snippet type

---

legacy/src/scss/_patterns_status-bar.scss
shared/src/components/StatusBar/StatusBar.tsx
ui/src/app/base/components/StatusBar/StatusBar.test.tsx
ui/src/app/base/components/StatusBar/StatusBar.tsx
ui/src/app/store/machine/utils/index.ts
ui/src/scss/_patterns_status-bar.scss

- Improved status bar display on small viewports
- Changed machine commissioned status to function identically to hardware sync status
- Run the full app using `yarn start`
- Go to the details page of a machine that has been commissioned
- Check that the status looks good at all viewport sizes
- Go to the details page of a …

fix(shared): improve status bar display on small viewports

---

ui/src/app/base/components/node/SetZoneForm/SetZoneForm.test.tsx
ui/src/app/base/components/node/SetZoneForm/SetZoneForm.tsx

- initialise zone in node set zone form if one node provided
- For machines and devices, when opening the "Set zone" form:
- Check that the zone is initialised if on details page or 1 selected in list page
- Check that the zone is not initialised if more than 1 selected in list page
Fixes canonical-web-and-design/app-tribe#900

fix(ui): initialise zone in node set zone form

---

integration/cypress.json
integration/cypress/integration/with-users/controllers/list.spec.ts
integration/cypress/integration/with-users/devices/list.spec.ts
integration/cypress/integration/with-users/subnets/add.spec.ts

- test: fix cypress failures
- set global retries for run mode to 2 (Cypress will run a test a maximum 3 times before reporting a failure)
Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/3854 …

test: fix cypress failures
