canonical/maas-ui

ui/package.json
ui/src/bakery.ts
yarn.lock

- Set the correct macaroon protocol version when authenticating with candid.
- Ask me.
Fixes: #3884.

fix(ui): fix login via external auth

---

.github/ISSUE_TEMPLATE/accessibility-failure.md
.github/workflows/accessibility.yml
README.md
integration/cypress.json
integration/cypress/integration/accessibility/accessibility.spec.ts
integration/cypress/support/commands.ts

- enable accessibility tests error reporting
- log errors for WCAG 2.1 AA violations only
- add accessibility badge to README
- create separate accessibility GitHub Action
https://github.com/canonical-web-and-design/maas-ui/tree/accessibility-test-github-job
Fixes: …

test(ui): enable accessibility error reporting

---

ui/src/app/tags/views/TagList/TagTable/TagTable.tsx

- Add an aria label when displaying an automatic tag icon.
- Go to the tag list page.
- Find an automatic tag in the list.
- Check that the tick icon in the auto row has an aria label.
Fixes: canonical-web-and-design/app-tribe#889.

fix(ui): add auto icon aria label

---

ui/src/app/base/components/SideNav/SideNav.test.tsx
ui/src/app/base/components/SideNav/SideNav.tsx
ui/src/app/base/components/SideNav/__snapshots__/SideNav.test.tsx.snap
ui/src/app/preferences/components/Nav/Nav.tsx
ui/src/app/settings/components/Nav/Nav.tsx
ui/src/scss/_vanilla-overrides.scss

- Added Vanilla mobile drawer to the SideNav component
- Go to Settings or user prefs and check that the side nav looks the same as before
- Resize the viewport to small and check that the side nav is replaced with a "Toggle side navigation" button
- Check that you can open and close the drawer using the toggle buttons
- Check …

fix(ui): add Vanilla mobile drawer to SideNav component

---

shared/src/components/Header/Header.test.tsx
shared/src/components/Navigation/Navigation.test.tsx
shared/src/components/Navigation/Navigation.tsx

- fix: set aria attributes on the homepage anchor element
- add tests
- fix eslint-disable-next-line testing-library/no-node-access error
Fixes https://github.com/canonical-web-and-design/maas-ui/issues/3906 …

fix(ui): set aria attributes on the homepage anchor element

---

ui/src/app/base/docsUrls.ts

- fix: https://maas.io/docs/how-to-manage-ip-ranges redirect
https://github.com/canonical-web-and-design/maas-ui/runs/6351175723?check_suite_focus=true
Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/3914
In general, please propose fixes …

fix: https://maas.io/docs/how-to-manage-ip-ranges redirect

---

ui/src/app/base/hooks/node.test.tsx
ui/src/app/base/hooks/node.ts

- Add tests for actions performed in machine menus (the actions were fixed in: https://github.com/canonical-web-and-design/maas-ui/pull/3811).
N/A

test(ui): add tests for machine actions

---

ui/src/app/base/hooks.test.tsx
ui/src/app/base/hooks.ts
ui/src/app/store/machine/types/actions.ts

- Fix actions made from the machine list table menus.
- In the status column open the menu and make sure you can preform the following actions: abort, acquire, commission, deploy, exit rescue mode, lock, mark broken, mark fixed, override failed testing, release, rescue mode, test and unlock
Fixes: #3935.

fix(ui): fix actions from the machine list

---

.github/pull_request_template.md
.github/workflows/accessibility.yml
.github/workflows/cypress.yml
.github/workflows/test.yml
HACKING.md
RELEASE.md

- Update references to master to be main.
n/a
Fixes: #3952.

refactor(all): rename master to main

---

ui/src/app/Routes.tsx
ui/src/app/controllers/urls.ts
ui/src/app/controllers/views/ControllerDetails/ControllerCommissioning/ControllerCommissioning.tsx
ui/src/app/controllers/views/ControllerDetails/ControllerCommissioning/index.ts
ui/src/app/controllers/views/ControllerDetails/ControllerConfiguration/ControllerConfiguration.tsx
ui/src/app/controllers/views/ControllerDetails/ControllerConfiguration/index.ts
ui/src/app/controllers/views/ControllerDetails/ControllerDetails.test.tsx
ui/src/app/controllers/views/ControllerDetails/ControllerDetails.tsx
ui/src/app/controllers/views/ControllerDetails/ControllerDetailsHeader/ControllerDetailsHeader.test.tsx
ui/src/app/controllers/views/ControllerDetails/ControllerDetailsHeader/ControllerDetailsHeader.tsx
ui/src/app/controllers/views/ControllerDetails/ControllerDetailsHeader/index.ts
ui/src/app/controllers/views/ControllerDetails/ControllerLogs/ControllerLogs.tsx
ui/src/app/controllers/views/ControllerDetails/ControllerLogs/index.ts
ui/src/app/controllers/views/ControllerDetails/ControllerNetwork/ControllerNetwork.tsx
ui/src/app/controllers/views/ControllerDetails/ControllerNetwork/index.ts
ui/src/app/controllers/views/ControllerDetails/ControllerPCIDevices/ControllerPCIDevices.tsx
ui/src/app/controllers/views/ControllerDetails/ControllerPCIDevices/index.ts
ui/src/app/controllers/views/ControllerDetails/ControllerStorage/ControllerStorage.tsx
ui/src/app/controllers/views/ControllerDetails/ControllerStorage/index.ts
ui/src/app/controllers/views/ControllerDetails/ControllerSummary/ControllerSummary.tsx
ui/src/app/controllers/views/ControllerDetails/ControllerSummary/index.ts
ui/src/app/controllers/views/ControllerDetails/ControllerUSBDevices/ControllerUSBDevices.tsx
ui/src/app/controllers/views/ControllerDetails/ControllerUSBDevices/index.ts
ui/src/app/controllers/views/ControllerDetails/ControllerVLANs/ControllerVLANs.tsx
ui/src/app/controllers/views/ControllerDetails/ControllerVLANs/index.ts
ui/src/app/controllers/views/ControllerDetails/index.ts
ui/src/app/controllers/views/Controllers.tsx

- Added controller details routes
- Added scaffolding components for the controller details header and each of the tab components
- Go to `/MAAS/r/controller/<system_id>`
- Check that you can navigate to each tab and the window title updates accordingly
- Check that the controller has been set as active and the detailed version …

feat(ui): create scaffolding components for controller details

---

integration/cypress/integration/with-users/controllers/list.spec.ts
ui/src/app/controllers/views/ControllerDetails/ControllerDetails.tsx
ui/src/app/controllers/views/ControllerDetails/ControllerDetailsHeader/ControllerDetailsHeader.test.tsx
ui/src/app/controllers/views/ControllerDetails/ControllerDetailsHeader/ControllerDetailsHeader.tsx

- add controller take action menu
I wasn't able to actually perform any of the actions (neither in legacy nor react version). This _may_ require extra work.
- Go to Controller Details page, e.g. `/MAAS/r/controller/knpge8` on bolla
- Verify correct actions are displayed under the "Take action" menu
Fixes: …

refactor: add controller take action menu

---

ui/src/app/base/components/node/StorageTables/StorageTables.tsx
ui/src/app/base/components/node/StorageTables/UsedStorageTable/UsedStorageTable.test.tsx
ui/src/app/base/components/node/StorageTables/UsedStorageTable/UsedStorageTable.tsx
ui/src/app/controllers/views/ControllerDetails/ControllerStorage/ControllerStorage.test.tsx
ui/src/app/controllers/views/ControllerDetails/ControllerStorage/ControllerStorage.tsx

- Refactored machine used storage table to work with controllers
- Go to the React storage tab for a controller
- Check that the used storage tables shows the same data as the AngularJS version
- Check that clicking a storage tag link filters the controller list appropriately
Fixes canonical-web-and-design/app-tribe#995

refactor(ui): refactor used storage table to work with controllers

---

ui/src/app/base/components/node/StorageTables/FilesystemsTable/AddSpecialFilesystem/AddSpecialFilesystem.test.tsx
ui/src/app/base/components/node/StorageTables/FilesystemsTable/AddSpecialFilesystem/AddSpecialFilesystem.tsx
ui/src/app/base/components/node/StorageTables/FilesystemsTable/FilesystemsTable.test.tsx
ui/src/app/base/components/node/StorageTables/FilesystemsTable/FilesystemsTable.tsx
ui/src/app/base/components/node/StorageTables/StorageTables.tsx
ui/src/app/controllers/views/ControllerDetails/ControllerStorage/ControllerStorage.test.tsx
ui/src/app/controllers/views/ControllerDetails/ControllerStorage/ControllerStorage.tsx

- Refactored filesystems table to work with controllers
- Check that the filesystems table is unchanged for machine
- Test out running a few actions on a machine that is in Ready or Allocated state
- Go to the React storage tab of a controller and check that the filesystems table data matches the AngularJS version 
Fixes …

refactor(ui): refactor filesystems table to work with controllers

---

ui/src/app/base/components/node/StorageTables/CacheSetsTable/CacheSetsTable.test.tsx
ui/src/app/base/components/node/StorageTables/CacheSetsTable/CacheSetsTable.tsx
ui/src/app/base/components/node/StorageTables/StorageTables.tsx
ui/src/app/controllers/views/ControllerDetails/ControllerStorage/ControllerStorage.test.tsx
ui/src/app/controllers/views/ControllerDetails/ControllerStorage/ControllerStorage.tsx

- Refactored machine cache sets table to work with controllers
- Go to the React storage tab for a controller with cache sets
- Check that the cache sets tables shows the same data as the AngularJS version
Fixes canonical-web-and-design/app-tribe#998

refactor(ui): refactor cache sets table to work with controllers

---

ui/src/app/base/components/NodeNetworkTab/NodeNetworkTab.tsx
ui/src/app/controllers/views/ControllerDetails/ControllerNetwork/ControllerNetwork.test.tsx
ui/src/app/controllers/views/ControllerDetails/ControllerNetwork/ControllerNetwork.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/MachineNetwork.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/MachineNetwork.tsx

- Add the controller network tab component and DHCP snippets table.
- Either add a DHCP snippet to a controller or use "fake-controller" on Bolla.
- Go to the React network tab for the controller.
- You should see the DHCP snippet table.
Fixes: canonical-web-and-design/app-tribe#987.
Fixes: canonical-web-and-design/app-tribe#993.

feat(ui): set up controller network tab and DCHP snippets

---

ui/src/app/controllers/views/ControllerDetails/ControllerVLANs/ControllerVLANs.tsx
ui/src/app/controllers/views/ControllerDetails/ControllerVLANs/ControllerVLANsTable/ControllerVLANsTable.test.tsx
ui/src/app/controllers/views/ControllerDetails/ControllerVLANs/ControllerVLANsTable/ControllerVLANsTable.tsx
ui/src/app/controllers/views/ControllerDetails/ControllerVLANs/ControllerVLANsTable/_index.scss
ui/src/app/controllers/views/ControllerDetails/ControllerVLANs/ControllerVLANsTable/constants.ts
ui/src/app/controllers/views/ControllerDetails/ControllerVLANs/ControllerVLANsTable/hooks.ts
ui/src/app/controllers/views/ControllerDetails/ControllerVLANs/ControllerVLANsTable/index.ts
ui/src/app/controllers/views/ControllerDetails/ControllerVLANs/ControllerVLANsTable/types.ts
ui/src/scss/index.scss

- migrate VLANs tab to React
- Go to Controller VLANs tab (e.g. `MAAS/r/controller/knpge8/vlans`)
- Make sure everything works as expected
Fixes: https://github.com/canonical-web-and-design/app-tribe/issues/936
In general, please propose fixes against _main_ rather than …

refactor: build VLANs tab

---

ui/src/app/base/components/node/StorageTables/DatastoresTable/DatastoresTable.test.tsx
ui/src/app/base/components/node/StorageTables/DatastoresTable/DatastoresTable.tsx
ui/src/app/base/components/node/StorageTables/StorageTables.tsx

- Refactored machine datastores table to work with controllers
- This is hard to QA with controllers, but for now just check that the machine datastores table works as before
- Go to the storage tab of a Ready or Allocated machine and change the storage layout to VMFS6 if it isn't already
- Check that the data is unchanged and …

refactor(ui): refactor datastores table to work with controllers

---

ui/src/app/base/components/node/StorageTables/AvailableStorageTable/AddLogicalVolume/AddLogicalVolume.tsx
ui/src/app/base/components/node/StorageTables/AvailableStorageTable/AddPartition/AddPartition.tsx
ui/src/app/base/components/node/StorageTables/AvailableStorageTable/AvailableStorageTable.test.tsx
ui/src/app/base/components/node/StorageTables/AvailableStorageTable/AvailableStorageTable.tsx
ui/src/app/base/components/node/StorageTables/AvailableStorageTable/CreateBcache/CreateBcache.tsx
ui/src/app/base/components/node/StorageTables/AvailableStorageTable/EditDisk/EditDisk.tsx
ui/src/app/base/components/node/StorageTables/AvailableStorageTable/EditPartition/EditPartition.tsx
ui/src/app/base/components/node/StorageTables/StorageTables.tsx

- Refactored machine available storage table to work with controllers
- Go to the React storage tab of a controller and check that the data matches what you see in the AngularJS version
- Check that you can still edit the storage of a Ready or Allocated machine
Fixes canonical-web-and-design/app-tribe#999

refactor(ui): refactor available storage table to work with controllers

---

ui/src/app/base/components/StatusBar/StatusBar.test.tsx
ui/src/app/base/components/StatusBar/StatusBar.tsx

- Show last image sync timestamp in controller status bar
- Go to the React details page of a controller
- Check that the last image sync timestamp is shown in the status bar
Fixes canonical-web-and-design/app-tribe#983

feat(ui): show last image sync timestamp in controller status bar

---

ui/src/app/base/components/node/networking/NetworkTable/NetworkTable.test.tsx
ui/src/app/base/components/node/networking/NetworkTable/NetworkTable.tsx
ui/src/app/base/components/node/networking/NetworkTable/_index.scss
ui/src/app/controllers/views/ControllerDetails/ControllerNetwork/ControllerNetwork.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTableActions/NetworkTableActions.tsx

- Add the network interfaces table to controllers.
- Hide actions in the network table.
- Go to a react controllers network tab (fake-controller on bolla has a good set of interfaces).
- Check that the interfaces list has the same info as the legacy table.
- Go to a machine and check that the actions are still visible.
Fixes: …

feat(ui): display controller interfaces

---

ui/src/app/machines/views/MachineList/MachineListTable/NameColumn/__snapshots__/NameColumn.test.tsx.snap
ui/src/app/store/vlan/utils.test.ts
ui/src/app/subnets/views/FabricDetails/FabricSummary/FabricSummary.test.tsx
ui/src/app/subnets/views/SubnetsList/SubnetsTable/utils.test.tsx
ui/src/testing/factories/domain.ts
ui/src/testing/factories/fabric.ts
ui/src/testing/factories/general.ts
ui/src/testing/factories/nodes.ts
ui/src/testing/factories/packagerepository.ts
ui/src/testing/factories/resourcepool.ts
ui/src/testing/factories/script.ts
ui/src/testing/factories/scriptResult.ts
ui/src/testing/factories/service.ts
ui/src/testing/factories/space.ts
ui/src/testing/factories/sshkey.ts
ui/src/testing/factories/sslkey.ts
ui/src/testing/factories/subnet.ts
ui/src/testing/factories/tag.ts
ui/src/testing/factories/token.ts
ui/src/testing/factories/vlan.ts
ui/src/testing/factories/vmcluster.ts
ui/src/testing/factories/zone.ts

- increment test entity names by default
- we already do this in some cases, this brings more consistency
I wasted too much time than I'd like to admit today because I assumed the names of my test domains would be auto incremented (and they weren't).
In the real world you wouldn't usually have the same names for different items (and it makes things more difficult to test). When interacting with real UI in integration tests you need a way of differentiating between different options. This should be the default behaviour.
- [A local snap MAAS](/HACKING.md#snap-deployment) (this will not …

test: increment test entity names by default

---

ui/src/app/controllers/constants.ts
ui/src/app/controllers/views/ControllerDetails/ControllerDetailsHeader/ControllerDetailsHeader.tsx
ui/src/app/controllers/views/Controllers.test.tsx
ui/src/app/controllers/views/Controllers.tsx

- fix controller details calling setActive on every route change
- add integration test to `Controllers.test.tsx` verifying it gets and sets the controller as active only once when navigating within the same controller
Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/3994
Related Launchpad maas …

fix(ui): controller details calling setActive on every route change

---

ui/src/app/controllers/views/Controllers.tsx

- scroll to top on controller route changes with useScrollToTop hook
- Go to controller details page, scroll down and click a link to storage from the summary page.
- Verify the page scrolled to the top after navigating to the new route.
Fixes: 
In general, please propose …

feat(ui): scroll to top on controller route changes

---

ui/src/app/tags/views/TagDetails/TagDetails.tsx

- fix: tag edit button icon contrast
- Go to machines tags and edit a tag
- verify the edit button icon is using the dark variant for sufficient colour contrast
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless the fix is only …

fix: tag edit button icon contrast

---

ui/src/bakery.ts
ui/src/index.tsx
ui/src/redux-store.ts

- Move the store to its own file so that when it gets imported the main app doesn't get initialised.
- Run `yarn ui` and check that the app loads and the redux store gets filled with data.

Move store to own file

---

ui/src/app/base/components/StatusBar/StatusBar.test.tsx
ui/src/app/base/components/StatusBar/StatusBar.tsx
ui/src/app/base/components/node/OverviewCard/ControllerStatusCard/ControllerStatusCard.test.tsx
ui/src/app/base/components/node/OverviewCard/ControllerStatusCard/ControllerStatusCard.tsx
ui/src/app/base/components/node/OverviewCard/CpuCard/CpuCard.tsx
ui/src/app/store/controller/utils/common.test.ts
ui/src/app/store/controller/utils/common.ts
ui/src/app/store/controller/utils/index.ts

- Built status section in controller summary
- Go to the React summary tab of a controller and check that it matches the [design in the spec](https://docs.google.com/document/d/1H-GWCLx3aSRiJRo9h5Fz-6IFLQ3adsa63pRFGlBFuq0/edit#heading=h.gczn4qs17xmf).
Fixes canonical-web-and-design/app-tribe#1007

feat(ui): add status section to controller summary

---

ui/src/app/App.tsx
ui/src/app/base/components/Header/Header.test.tsx
ui/src/app/base/components/Header/Header.tsx

- Remove the url generators from the ui Header as they are no longer required.
- Load the client and check that the header still navigates correctly.

refactor(ui): remove header url generation

---

ui/src/app/base/components/NodeConfigurationFields/NodeConfigurationFields.test.tsx
ui/src/app/base/components/NodeConfigurationFields/NodeConfigurationFields.tsx

- fix: cannot save controller or device configuration with automatic tags
- Go to tags and add a new automatic tag (with a description)
- Go to device or controller configuration and verify that this tag does not show on the list of possible choices
Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/4027
Related …

fix: cannot save controller or device configuration with automatic tags

---

ui/src/app/base/components/Header/Header.test.tsx
ui/src/testing/utils.tsx

- add default rootState to test utils
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. Please apply backport labels to the PR (e.g. "Backport 2.7") for the appropriate …

test: add default state to test utils

---

ui/src/app/base/components/Header/Header.tsx
ui/src/app/base/urls.ts
ui/src/app/controllers/urls.ts
ui/src/app/devices/urls.ts
ui/src/app/domains/urls.ts
ui/src/app/images/urls.ts
ui/src/app/kvm/urls.ts
ui/src/app/machines/urls.ts
ui/src/app/settings/urls.ts
ui/src/app/subnets/urls.ts
ui/src/app/tags/urls.ts
ui/src/app/zones/urls.ts

- update header to use url definitions
- Verify each navigation item links to the correct page
Fixes: https://github.com/canonical-web-and-design/app-tribe/issues/1023
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless the fix is …

refactor: update header to use url definitions

---

src/app/App.tsx
src/app/base/components/Footer/Footer.test.tsx
src/app/base/components/Footer/Footer.tsx
src/app/base/components/Header/Header.test.tsx
src/app/base/components/Header/Header.tsx
src/app/base/hooks/analytics.ts
src/app/base/hooks/index.ts

- Connect `Header` and `Footer` components to the store
- Move analytics `useEffect`s to their own hooks
- Check that you can still log in and log out as before
- Check that all the links work as before (i.e. they go to the right place, highlights in sub-urls)
- Create a new user and log in as them
- Check that you get …

refactor: connect Header and Footer components to the store

---

.eslintrc.js
src/app/base/components/NodeConfigurationFields/NodeConfigurationFields.test.tsx
src/app/devices/views/DeviceDetails/DeviceConfiguration/DeviceConfiguration.test.tsx
src/app/devices/views/DeviceDetails/DeviceConfiguration/DeviceConfiguration.tsx
src/app/kvm/components/KVMConfigurationCard/KVMConfigurationCard.test.tsx
src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagFormFields/TagFormFields.test.tsx
src/app/machines/components/MachineHeaderForms/AddMachine/AddMachineForm/AddMachineForm.test.tsx
src/app/machines/views/MachineDetails/MachineConfiguration/PowerForm/PowerForm.test.tsx
src/app/machines/views/MachineDetails/MachineNetwork/NetworkFields/NetworkFields.test.tsx
src/app/subnets/components/ReservedRangeForm/ReservedRangeForm.test.tsx
src/app/subnets/components/ReservedRanges/ReservedRanges.test.tsx
src/app/subnets/views/SubnetDetails/SubnetDetailsHeader/SubnetActionForms/components/EditBootArchitectures/EditBootArchitectures.test.tsx
src/app/subnets/views/SubnetDetails/SubnetDetailsHeader/SubnetActionForms/components/MapSubnet/MapSubnet.test.tsx
src/app/subnets/views/SubnetDetails/SubnetSummary/SubnetSummaryForm/SubnetSummaryForm.test.tsx
src/app/subnets/views/SubnetDetails/SubnetSummary/SubnetSummaryForm/SubnetSummaryFormFields/SubnetSummaryFormFields.test.tsx
src/app/subnets/views/VLANDetails/ConfigureDHCP/DHCPReservedRanges/DHCPReservedRanges.test.tsx
src/app/subnets/views/VLANDetails/EditVLAN/EditVLAN.test.tsx
src/app/tags/components/AddTagForm/AddTagForm.test.tsx
src/app/tags/components/AddTagForm/AddTagForm.tsx
src/app/tags/components/TagsHeader/AddTagForm/AddTagForm.test.tsx
src/app/tags/components/TagsHeader/DeleteTagForm/DeleteTagForm.test.tsx
src/app/tags/views/TagUpdate/TagUpdate.test.tsx
src/app/tags/views/Tags.test.tsx

- Replaced most instances of `fireEvent` with `userEvent`
- Added a rule to our eslint config to only allow `fireEvent` for change methods (currently it's needed for changing sliders)
- N/A
Fixes #3934

refactor: replace instances of fireEvent with userEvent and enforce with linting

---

src/app/App.tsx
src/app/base/components/Header/Header.tsx
src/app/base/components/node/MachinesHeader/MachinesHeader.tsx

- refactor: replace remaining header url strings
- use matchPath util from react-router
- Verify menu items are highlighted as before
Fixes: https://github.com/canonical-web-and-design/app-tribe/issues/1031 …

refactor: replace remaining header url strings

---

.vscode/settings.json

- Fix eslint on save.
- Open vscode. Make a change that the linter complains about.
- Save the file.
- The eslint error should get fixed (if it knows how to).

Fix eslint on save

---

src/app/base/components/node/StorageTables/AvailableStorageTable/BulkActions/BulkActions.test.tsx
src/app/base/components/node/StorageTables/AvailableStorageTable/BulkActions/BulkActions.tsx

- Fixed bug where datastore actions only showed for VMFS6 layout and not VMFS7
- Go to the storage tab of a Ready/Allocated machine whose boot disk has more than 32GB (e.g. http://bolla.internal:5240/MAAS/r/machine/xxgpsf/storage)
- Click "Change storage layout" and choose "VMFS7"
- Check that there are actions to create and add …

fix: render datastore actions for VMFS7 layout

---

.github/workflows/upload.yml

- Update the publish action to push to the asset server.
- View a passing run (I previously modified the action to run on this PR instead of on merge): https://github.com/canonical-web-and-design/maas-ui/runs/6975639664?check_suite_focus=true
- Open the "Upload to assets server" step and find the url of the published asset.
- Visit the URL and it should download a .tar.gz
- Check that the .tar.gz contains the built maas-ui files.
Fixes: https://github.com/canonical-web-and-design/app-tribe/issues/1047.

Publish asset server action

---

src/app/controllers/components/ControllerHeaderForms/AddController/AddController.test.tsx
src/app/controllers/components/ControllerHeaderForms/AddController/AddController.tsx

- fix: rack controller instructions for installing the correct version
- add a dropdown for different instructions (snap/deb packages)
- Go to controllers
- Click "Add new rack controller"
- Verify following instructions installs the rack controller with the correct version (matching the main maas)
Fixes: …

fix: rack controller instructions for correct version

---

.github/workflows/upload.yml

- Don't specify the CI env var twice.

Fix the CI env var in the upload action

---

cypress/e2e/with-users/base/footer.spec.ts
cypress/e2e/with-users/devices/list.spec.ts
src/app/devices/views/DeviceDetails/DeviceConfiguration/DeviceConfiguration.tsx

- test: update failing cypress tests
Fixes: #4122 
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. Please apply backport labels to the PR (e.g. "Backport …

test: update cypress tests

---

src/app/base/validation.test.ts
src/app/base/validation.ts
src/app/intro/views/MaasIntro/MaasIntro.test.tsx
src/app/intro/views/MaasIntro/MaasIntro.tsx
src/app/settings/views/Network/ProxyForm/ProxyForm.tsx

- fix: initial config URL validation
- Open mass-ui using a fresh maas backend (with no configuration)
- test that input fields that accept a URL allow for entering URLs with without a TLD (e.g. `test.proxy`, `localhost:300`)
Fixes: #4129  
In general, please propose fixes …

fix: initial config URL validation

---

cypress/e2e/with-users/intro/intro.ts
src/app/base/validation.test.ts
src/app/base/validation.ts

- make url optional by default in `UrlSchema`
- add e2e tests to intro pages
- Yup `test` is inconsistent with `.matches` and doesn't allow empty values when not `.required()`
- The test needs to return true if a falsy value is passed to workaround this
https://github.com/jquense/yup/issues/1055
- Open with MAAS with no prior …

fix: proxy url required

---

cypress/e2e/with-users/machines/details.spec.ts
src/app/base/components/node/networking/NetworkTable/_index.scss
src/app/machines/views/MachineList/MachineListTable/MachineListTable.tsx

- fix: ip hidden instead of subnet
- add machine details e2e test
- Got o machine details page
- Resize the window and make sure the subnet column disappears instead of IP on medium screen size
Fixes: #1868  …

fix: ip hidden instead of subnet

---

.github/workflows/test.yml
package.json

- test: add run-dotrun github action
- this is to prevent merging code that breaks the build via dotrun
Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/4131
In general, please propose fixes against _main_ rather than release branches (e.g. …

test: add run-dotrun github action

---

cypress/e2e/utils.ts
cypress/e2e/with-users/machines/details.spec.ts
src/app/base/components/node/NodeTestsTable/NodeTestsTable.tsx
src/app/machines/views/MachineDetails/MachineDetails.test.tsx
src/app/machines/views/MachineDetails/MachineDetails.tsx

- fix machine details routes
- Go to machine commissioning details (e.g. `/MAAS/r/machine/pbpncx/commissioning/59674/details` on bolla) and verify the page is displayed correctly (and "Script result could not be found." is not shown)
Fixes: #4169
In general, please propose …

fix(ui): machine details routes

---

src/app/subnets/views/SubnetDetails/SubnetSummary/components/ActiveDiscoveryLabel/ActiveDiscoveryLabel.tsx
src/app/subnets/views/SubnetDetails/SubnetSummary/components/AllowDNSResolutionLabel/AllowDNSResolutionLabel.tsx
src/app/subnets/views/SubnetDetails/SubnetSummary/components/ManagedAllocationLabel/ManagedAllocationLabel.tsx
src/app/subnets/views/SubnetDetails/SubnetSummary/components/ProxyAccessLabel/ProxyAccessLabel.tsx

- fix: subnet icons misaligned
- Go to subnet details (e.g. `/MAAS/r/subnet/1` on bolla) and click edit, verify that tooltips are aligned correctly
Fixes: #4099  .
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless the fix is only …

fix: subnet icons misaligned

---

cypress/e2e/with-users/controllers/details.spec.ts
cypress/e2e/with-users/controllers/list.spec.ts
cypress/e2e/with-users/machines/details.spec.ts
src/app/controllers/views/ControllerDetails/ControllerDetails.test.tsx
src/app/controllers/views/ControllerDetails/ControllerDetails.tsx

- fix controller details scriptresult not found
- add controller comissioning e2e test
- move controller details tests to own file
- Verify that controller details subpages work correctly
Fixes: #4172  …

fix(ui): controller details scriptresult not found

---

.eslintrc.js

- add no-only eslint rule to cypress tests
Fixes: # .
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. Please apply backport labels to the PR (e.g. "Backport …

test: add no-only eslint rule to cypress tests

---

src/app/pools/components/PoolForm/PoolForm.tsx
src/app/pools/views/PoolAdd/PoolAdd.tsx
src/app/pools/views/PoolEdit/PoolEdit.tsx
src/app/pools/views/PoolList/PoolList.tsx
src/app/pools/views/Pools.test.tsx
src/app/pools/views/Pools.tsx

- Update pools routes to React Router v6.
- Go to Machines -> Resource pools tab.
- The list of pools should appear.
- Click "Add pool" in the header and the form should appear.
- Go back to the pool list and click the edit icon and the edit form should appear.
Fixes: #4193.

refactor(pools): update pools to RRv6

---

src/app/base/components/node/MachinesHeader/MachinesHeader.tsx
src/app/tags/views/Tags.test.tsx
src/app/tags/views/Tags.tsx

- Update the tag routes to React Router v6.
- Go to Machines -> Tags tab.
- The list of tags should appear.
- Click on "Create new tag" and the form should appear.
- Go back to the list and click on a tag and the details should appear.
- Go back to the list and find or create a tag that has kernel options (e.g. this one: …

refactor(tags): update tags to RRv6

---

src/scss/_patterns_status-bar.scss

- Changed the background colour of the status bar to the default for the vanilla dark theme ( `hsl(0deg, 0%, 15%)` or `#262626`)
- Changed the text colour on the status bar to white

Changed status bar colour to dark theme default

---

src/app/base/components/SideNav/SideNav.tsx
src/app/base/components/SideNav/__snapshots__/SideNav.test.tsx.snap

- fix: settings top-level item no longer bold
- Go to settings and verify that all top-level items are displayed with a bold font
Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/4184 …

fix(ui): settings top-level item no longer bold

---

src/app/Routes.tsx
src/app/machines/views/Machines.test.tsx
src/app/machines/views/Machines.tsx

- Remove unnecessary routing from machine list.
- Go to the machine list. It should appear.
Fixes: #4192.

refactor(machines): remove routing from machine list

---

.dockerignore
Dockerfile
konf/site.yaml
package.json
scripts/proxy.js

- enable PR demos with `polong.internal` MAAS 
- Make sure you can login (if I haven't sent you a message with password yet - contact me).
Fixes: # .
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless the fix is only applicable for …

feat: enable PR demos with polong

---

src/app/pools/views/PoolList/PoolList.test.tsx
src/app/pools/views/PoolList/PoolList.tsx

- Remove the call to fetch machines from the pools list as this is not required.
- Visit /MAAS/r/pools directly (or navigate to pools and refresh the page).
- The "x Machines" tab should show the count of machines.
Fixes: canonical-web-and-design/app-tribe#1113.

refactor(pools): remove machine fetching from pools

---

src/app/machines/components/MachineHeaderForms/ActionFormWrapper/CloneForm/CloneFormFields/CloneFormFields.tsx
src/app/machines/views/MachineDetails/MachineDetails.test.tsx
src/app/machines/views/MachineDetails/MachineDetails.tsx
src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.tsx
src/app/machines/views/MachineDetails/MachineSummary/MachineSummary.tsx
src/app/store/machine/utils/hooks.test.tsx
src/app/store/machine/utils/hooks.ts

- Move the dispatches for getting a machine to a hook.
- Go to the summary tab for a machine. The machine details should appear in the header and summary cards.
- Go to the machine list and tick some machines.
- Use the take action menu to open the clone form.
- Click on a machine to clone from. The machine's details should …

refactor(machine): add a hook for getting a machine

---

src/app/store/machine/actions.test.ts
src/app/store/machine/reducers.test.ts
src/app/store/machine/slice.ts
src/app/store/machine/types/base.ts

- Add an action for unsubscribing to machines over the API.
- Open the machine list in one tab and open a machine's details page in another tab.
- In the machine list tab open the redux dev tools.
- In the machine details page make a change to the machine e.g. add/remove a tag.
- In the redux dev tools in the list tab you should …

feat(machine): add machine unsubscribe action

---

src/app/settings/views/Storage/StorageForm/StorageForm.test.tsx
src/app/settings/views/Storage/StorageForm/StorageFormFields/StorageFormFields.test.tsx
src/app/settings/views/Storage/StorageForm/StorageFormFields/StorageFormFields.tsx

Migrated the following testes to RTL:
- [src/app/settings/views/Storage/StorageForm/StorageForm.test.tsx](https://github.com/canonical-web-and-design/maas-ui/compare/main...ndv99:rtlMigration-Storage?expand=1#diff-4213ebe73a83ae87ea2aef50de17f459655dea563facf31c41f01dd97682849e)
- [src/app/settings/views/Storage/StorageForm/StorageFormFields/StorageFormFields.test.tsx](https://github.com/canonical-web-and-design/maas-ui/compare/main...ndv99:rtlMigration-Storage?expand=1#diff-1ca365d0e38d3e285a3bc00713c0bdf197083a735ffed81abfc53b247e91a896)

Migrate Enzyme to RTL- app/settings/views/Storage

---

src/app/settings/views/LicenseKeys/LicenseKeyEdit/LicenseKeyEdit.test.tsx
src/app/settings/views/LicenseKeys/LicenseKeyEdit/LicenseKeyEdit.tsx
src/app/settings/views/LicenseKeys/LicenseKeyForm/LicenseKeyForm.test.tsx
src/app/settings/views/LicenseKeys/LicenseKeyForm/LicenseKeyForm.tsx
src/app/settings/views/LicenseKeys/LicenseKeyFormFields/LicenseKeyFormFields.test.tsx
src/app/settings/views/LicenseKeys/LicenseKeyFormFields/LicenseKeyFormFields.tsx
src/app/settings/views/LicenseKeys/LicenseKeyList/LicenseKeyList.test.tsx

- [src/app/settings/views/LicenseKeys/LicenseKeyEdit/LicenseKeyEdit.test.tsx](https://github.com/canonical-web-and-design/maas-ui/compare/main...ndv99:rtlMigration-settingsLicenseKeys?expand=1#diff-fbbb14a2cc211ba17d437acd008f58f6edd4844677e9de1357d4814be84891d3)
- [src/app/settings/views/LicenseKeys/LicenseKeyForm/LicenseKeyForm.test.tsx](https://github.com/canonical-web-and-design/maas-ui/compare/main...ndv99:rtlMigration-settingsLicenseKeys?expand=1#diff-86e099751c777da7d90ee6c6ee24e1408756f9530ba025291ad04cd91120aa2a)
- [src/app/settings/views/LicenseKeys/LicenseKeyFormFields/LicenseKeyFormFields.test.tsx](https://github.com/canonical-web-and-design/maas-ui/compare/main...ndv99:rtlMigration-settingsLicenseKeys?expand=1#diff-bf0710c825faaca0ab353192b …

Migrate Enzyme to RTL - app/settings/views/LicenseKeys

---

package.json
yarn.lock

- upgrade @canonical/macaroon-bakery to v1.2.2
- setup external authentication in your local MAAS using the guide: https://webteam.canonical.com/guides/maas-external-authentication-with-rbac
- make sure you can login to your local MAAS using RBAC
Fixes: # . …

upgrade @canonical/macaroon-bakery to v1.2.2

---

src/app/base/components/DhcpForm/DhcpForm.tsx
src/app/base/components/MachineLink/MachineLink.tsx
src/app/base/components/node/MachinesHeader/MachinesHeader.tsx
src/app/dashboard/views/DiscoveryAddForm/DiscoveryAddForm.tsx
src/app/kvm/components/KVMResourcesCard/KVMResourcesCard.test.tsx
src/app/kvm/components/KVMResourcesCard/KVMResourcesCard.tsx
src/app/kvm/components/LXDHostVMs/NumaResources/NumaResourcesCard/NumaResourcesCard.test.tsx
src/app/kvm/components/LXDHostVMs/NumaResources/NumaResourcesCard/NumaResourcesCard.tsx
src/app/kvm/components/LXDVMsTable/LXDVMsTable.test.tsx
src/app/kvm/components/LXDVMsTable/LXDVMsTable.tsx
src/app/machines/components/MachineHeaderForms/ActionFormWrapper/CloneForm/CloneFormFields/CloneFormFields.tsx
src/app/machines/views/MachineList/MachineListHeader/MachineListHeader.tsx
src/app/settings/hooks.ts
src/app/settings/views/Dhcp/DhcpList/DhcpList.tsx
src/app/store/machine/actions.test.ts
src/app/store/machine/slice.ts
src/app/store/machine/utils/hooks.test.tsx
src/app/store/machine/utils/hooks.ts
src/app/tags/views/TagMachines/TagMachines.test.tsx
src/app/tags/views/TagMachines/TagMachines.tsx

- Move the calls to fetch the machines to a reusable hook.
Brace yourself, this is a lot of places to check. Over time a number of these places will be replaced with calls to `machine.get` but right now this is all the places that fetch the list of machines.
- Go to the machine list and refresh the page. The machines should …

refactor(machines): move machine fetching to a hook

---

src/app/store/machine/reducers.test.ts
src/app/store/machine/slice.ts

- Get the machine list on main working with the new API shape.
Note: at the time of writing this isn't working with the demo service as the snap hasn't been updated to the version that breaks the machine list so this might need to be QAed locally.
- It should display the machines.
Fixes: #4284.

fix(ui): fix main machine list

---

src/app/base/hooks/analytics.ts

- fix(ui): subsequent Google Analytics `pageview` events
- Download https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna?hl=pl
- go to the demo URL in the comments below.
- login and make sure the initial page view has been sent with the correct path
- go to a different page and …

fix(ui): subsequent ga pageview events

---

ui/src/app/subnets/views/VLANDetails/ConfigureDHCP/ConfigureDHCP.test.tsx
ui/src/app/subnets/views/VLANDetails/ConfigureDHCP/ConfigureDHCP.tsx
ui/src/app/subnets/views/VLANDetails/ConfigureDHCP/ConfigureDHCPFields/ConfigureDHCPFields.tsx

- backport of fix: configure VLAN DHCP (#4246)
-  Go to VLAN details page (e.g. MAAS/r/vlan/5002 on karura.internal) and Click "Configure DHCP"
- Select a rack controller and a subnet
- Form submit button should be enabled
Fixes: #4246 .
lp#1980818
https://bugs.launchpad.net/bugs/1980818 …

fix: configure VLAN DHCP (#4246)

---

src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagFormChanges/TagFormChanges.tsx
src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagFormFields/TagFormFields.tsx

- add kernel option description 
- Go to a machine configuration and open tags configuration
- Make sure that kernel option has a text description by looking at the accessibility tree in developer tools
Fixes: https://github.com/canonical-web-and-design/app-tribe/issues/888 …

feat(ui): add kernel option description

---

src/app/base/sagas/websockets.test.ts
src/app/base/sagas/websockets.ts
src/app/store/machine/reducers.test.ts
src/app/store/machine/slice.ts
src/app/store/utils/slice.ts
src/testing/factories/index.ts
src/testing/factories/state.ts

- Store the result of machine.get requests using the new details store.
- Load a machine details page and open redux devtools.
- You should see dispatches for `machine/get`, `machine/getStart` and `machine/getSuccess`.
- In the redux state there should an entry for each get request in machine -> details and each one should have …

feat(machine): store result of machine.get

---

legacy/src/app/partials/cards/services.html

- Fix a bug when `reverse-proxy` service is displayed for `rack` or `region+rack`. Should be `region` or `region+rack`.
Fixes: #4292 .
lp#1982984 …

fix: show reverse proxy for region or region+rack

---

src/__snapshots__/root-reducer.test.ts.snap
src/app/store/machine/actions.test.ts
src/app/store/machine/reducers.test.ts
src/app/store/machine/slice.ts
src/app/store/machine/types/base.ts
src/app/store/utils/slice.ts
src/testing/factories/index.ts
src/testing/factories/state.ts

- Add handlers for the machine.count API to the machine slice.
- Open the redux devtools.
- Dispatch the following and the result should appear in the machine -> counts list:
```
{
type: "machine/count",
meta: {
model: "machine",
method: "count",
requestId: "123456",
},
payload: {
params: {filter: {owner: "admin"}},
},
}
``` …

feat(machines): add machine.count API support

---

src/app/base/components/MachineLink/MachineLink.test.tsx
src/app/base/components/MachineLink/MachineLink.tsx
src/app/machines/components/MachineHeaderForms/ActionFormWrapper/CloneForm/CloneFormFields/CloneFormFields.tsx
src/app/machines/views/MachineDetails/MachineDetails.tsx
src/app/store/machine/utils/hooks.test.tsx
src/app/store/machine/utils/hooks.ts

- update machine link 
- refactor `useGetMachine` to return status and machine (consistent with `useDhcpTarget`)
- using bolla back-end, go to /MAAS/r/subnet/3 
- in the Used IP addresses section verify machine links in the NODE column are displayed correctly 
- click on a link and verify a machine details page is displayed …

refactor(ui): update machine link

---

src/app/store/machine/slice.ts
src/app/store/machine/utils/hooks.test.tsx
src/app/store/machine/utils/hooks.ts

- clean up machine requests on unmount and id change
- add cleanupRequest action
- go to `/MAAS/r/subnet/3` using bolla back-end
- open redux devtools and ensure only latest machine details requests are in the store (for the page above that would be the total of 2)
- verify all machine details requests get removed from the store …

feat: clean up machine requests

---

src/app/store/machine/actions.test.ts
src/app/store/machine/reducers.test.ts
src/app/store/machine/slice.ts
src/app/store/machine/types/base.ts
src/app/store/machine/types/index.ts
src/testing/factories/nodes.ts

- Add support for fetching filter options.
- Open the redux dev tools and dispatch both of the following actions:
```
{
type: "machine/filterGroups",
meta: {
model: "machine",
method: "filter_groups",
},
payload: null,
}
```
```
{
type: "machine/filterOptions",
meta: {
model: "machine",
method: "filter_options",
},
payload: { …
```

feat(redux): add filter options

---

src/app/machines/views/MachineList/MachineListTable/NameColumn/NameColumn.test.tsx
src/app/machines/views/MachineList/MachineListTable/NameColumn/NameColumn.tsx
src/app/machines/views/MachineList/MachineListTable/NameColumn/__snapshots__/NameColumn.test.tsx.snap
src/scss/_patterns_double-row.scss

- fix IP address tooltip positioning
- Ensure each machine that has multiple IP addresses has a (+1) button displayed which opens a tooltip on click/hover.
- Ensure if IP strings are truncated the (+1) button is still visible
Fixes: #4221 
In general, …

fix: IP address tooltip 

---

src/app/settings/hooks.test.tsx
src/app/settings/hooks.ts
src/app/settings/views/Dhcp/DhcpList/DhcpList.tsx

- Update the useDhcpTarget hook to get the required machine.
- Go to Settings -> DHCP snippets.
- Add snippets that target a machine and a controller or device (if you don't don't already have some - I've added some on Bolla).
- Check that the table displays the node names.
- Click the links to the nodes and go to the network …

feat(dhcp): update dhcp hook to get machines

---

package.json
src/app/machines/views/MachineList/MachineList.test.tsx
src/app/machines/views/MachineList/MachineList.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListTable.test.tsx
src/app/store/machine/selectors.test.ts
src/app/store/machine/selectors.ts
src/app/store/machine/slice.ts
src/app/store/machine/utils/hooks.test.tsx
src/app/store/machine/utils/hooks.ts
src/app/utils/search/filter-items.ts
yarn.lock

- Update the machine list to search using the new API.
- Enter in a search term that machines some machines e.g. `hostname:abc` (free text won't work until the API supports it: followup here: https://github.com/canonical/app-tribe/issues/1149).
- The list should update with the matching machines.
- Tick …

feat(machines): search machines using the new API

---

src/app/store/machine/slice.ts

- Move the action/reducer objects to a function to generate the machine actions.
- Tick some machines.
- Check that you can perform actions via the take action menu.
Fixes: canonical/app-tribe#1253.

refactor(machines): generate action params

---

src/app/base/sagas/actions.ts
src/app/base/sagas/websockets.test.ts
src/app/base/sagas/websockets.ts
src/app/store/machine/actions.test.ts
src/app/store/machine/reducers.test.ts
src/app/store/machine/selectors.test.ts
src/app/store/machine/selectors.ts
src/app/store/machine/slice.ts
src/app/store/machine/utils/hooks.test.tsx
src/app/store/machine/utils/hooks.ts
src/websocket-client.ts

- Add support for unsubscribing to the websocket sagas.
- Add clean up and unsub to fetch and get hooks.
- Look in `machine` in the redux store and you should see the `lists` requests.
- Navigate away from the machine list, preferably to somewhere that doesn't have machines.
- You should see the …

Add unsubscribe hook and saga

---

src/app/base/components/MachineLink/MachineLink.tsx
src/app/machines/components/MachineHeaderForms/ActionFormWrapper/CloneForm/CloneFormFields/CloneFormFields.tsx
src/app/machines/views/MachineDetails/MachineDetails.tsx
src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.tsx
src/app/machines/views/MachineDetails/MachineSummary/MachineSummary.tsx
src/app/settings/hooks.ts
src/app/store/machine/utils/hooks.test.tsx
src/app/store/machine/utils/hooks.ts

- rename useGetMachine to useFetchMachine for consistency with related hooks (e.g. `useFetchMachines`)
- Ensure machine details page loads correctly
Fixes: https://github.com/canonical/app-tribe/issues/1255 …

refactor(machines): useFetchMachine

---

src/app/base/components/node/MachinesHeader/MachinesHeader.test.tsx
src/app/base/components/node/MachinesHeader/MachinesHeader.tsx
src/app/machines/views/MachineList/MachineListHeader/MachineListHeader.test.tsx
src/app/machines/views/MachineList/MachineListHeader/MachineListHeader.tsx
src/app/store/machine/selectors.test.ts
src/app/store/machine/selectors.ts
src/app/store/machine/slice.ts
src/app/store/machine/utils/hooks.test.tsx
src/app/store/machine/utils/hooks.ts
src/testing/factories/index.ts

- use machine count API on the machine listing page
- Go to machine listing page and ensure the machine count is correct
Fixes: https://github.com/canonical/app-tribe/issues/1110
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless …

feat(machines): machine listing count API

---

src/app/store/machine/actions.test.ts
src/app/store/machine/slice.ts
src/app/tags/components/TagsHeader/DeleteTagForm/DeleteTagForm.test.tsx
src/app/tags/components/TagsHeader/DeleteTagForm/DeleteTagFormWarnings/DeleteTagFormWarnings.test.tsx
src/app/tags/components/TagsHeader/DeleteTagForm/DeleteTagFormWarnings/DeleteTagFormWarnings.tsx

- use count API in tag delete form
- Go to the tags list
- Select automatic tags
- Click on delete icon
- Check the count websocket request with correct parameters has been made in the developer tools Network tab
- Verify the number of deployed machines with a selected tag is correct in the UI
Fixes: …

refactor(machines): use count API in tag delete form

---

src/app/machines/views/MachineList/ErrorsNotification/ErrorsNotification.test.tsx
src/app/machines/views/MachineList/ErrorsNotification/ErrorsNotification.tsx
src/app/machines/views/MachineList/ErrorsNotification/index.ts
src/app/machines/views/MachineList/MachineList.test.tsx
src/app/machines/views/MachineList/MachineList.tsx
src/app/store/machine/selectors.ts
src/app/store/machine/utils/hooks.ts

-  display fetch machines errors
- Enter invalid search constraint into the search field (e.g. `tag1:(test)`)
- verify an error message has been shown and can be dismissed on click
Fixes: https://github.com/canonical/app-tribe/issues/1247
In general, …

feat(machines): display fetch machines errors

---

src/app/base/components/LabelledList/LabelledList.tsx
src/app/base/components/MachineSelectTable/MachineSelectTable.test.tsx
src/app/base/components/MachineSelectTable/MachineSelectTable.tsx
src/app/base/components/MachineSelectTable/_index.scss
src/app/base/components/MachineSelectTable/index.ts
src/app/machines/components/MachineHeaderForms/ActionFormWrapper/CloneForm/CloneForm.test.tsx
src/app/machines/components/MachineHeaderForms/ActionFormWrapper/CloneForm/CloneFormFields/CloneFormFields.test.tsx
src/app/machines/components/MachineHeaderForms/ActionFormWrapper/CloneForm/CloneFormFields/SourceMachineSelect/SourceMachineDetails/SourceMachineDetails.tsx
src/app/machines/components/MachineHeaderForms/ActionFormWrapper/CloneForm/CloneFormFields/SourceMachineSelect/SourceMachineDetails/__snapshots__/SourceMachineDetails.test.tsx.snap
src/app/machines/components/MachineHeaderForms/ActionFormWrapper/CloneForm/CloneFormFields/SourceMachineSelect/SourceMachineSelect.test.tsx
src/app/machines/components/MachineHeaderForms/ActionFormWrapper/CloneForm/CloneFormFields/SourceMachineSelect/SourceMachineSelect.tsx
src/app/machines/components/MachineHeaderForms/ActionFormWrapper/CloneForm/CloneFormFields/SourceMachineSelect/_index.scss
src/scss/index.scss

- Make the machine selection table a reusable component.
- Migrate tests to RTL.
- Open [CloneFormFields.tsx](https://github.com/canonical/maas-ui/blob/3ea99f1d1202cd425eb5e59b2ad4d84e2c34b318/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/CloneForm/CloneFormFields/CloneFormFields.tsx#L41) and change `const …

refactor(machines): move machine select table to a reusable component

---

src/app/base/components/node/MachinesHeader/MachinesHeader.test.tsx
src/app/tags/components/KernelOptionsField/KernelOptionsField.test.tsx
src/app/tags/components/KernelOptionsField/KernelOptionsField.tsx

- update edit tag warning to use the count API
- Go to machine listing and select Tags
- Edit a tag that has kernel options
- Type in the kernel options field
- Make sure the number of machines in the warning message is correct
Fixes: https://github.com/canonical/app-tribe/issues/1118 …

refactor(machines): update edit tag warning

---

src/app/store/machine/reducers.test.ts
src/app/store/machine/slice.ts

- remove count request
- Verify there are counts in the machine redux slice via Redux Devtools
- Navigate to another page (e.g. Settings)
- make sure all counts requests were removed from the Redux store
Fixes: https://github.com/canonical/app-tribe/issues/1259 …

refactor(machines): remove count request

---

src/app/machines/views/MachineList/MachineList.tsx
src/app/machines/views/MachineList/MachineListControls/GroupSelect/GroupSelect.test.tsx
src/app/machines/views/MachineList/MachineListControls/GroupSelect/GroupSelect.tsx
src/app/machines/views/MachineList/MachineListControls/GroupSelect/__snapshots__/GroupSelect.test.tsx.snap
src/app/machines/views/MachineList/MachineListControls/MachineListControls.test.tsx
src/app/machines/views/MachineList/MachineListControls/MachineListControls.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListTable.test.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListTable.tsx
src/app/store/machine/types/actions.ts
src/app/store/machine/utils/hooks.test.tsx
src/app/store/machine/utils/hooks.ts

- Update the machine list group selector to pass the group with the API call.
- Go to the machine list and change the value of the "Group by..." select box (some values don't currently work: https://bugs.launchpad.net/maas/+bug/1984994).
- Open redux and look in machine -> list -> whichever call id is for the list -> groups
- …

feat(machines): add group to fetch calls

---

src/app/store/machine/reducers.test.ts
src/app/store/machine/slice.ts

- refactor(machines): ignore removed count requests
Fixes: https://github.com/canonical/app-tribe/issues/1264 …

refactor(machines): ignore removed count requests

---

.eslintrc.js
src/app/base/components/NodeName/NodeNameFields/NodeNameFields.tsx
src/app/base/components/SideNav/SideNav.tsx
src/app/base/components/TitledSection/TitledSection.tsx
src/app/controllers/views/ControllerDetails/ControllerVLANs/ControllerVLANsTable/ControllerVLANsTable.tsx
src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagFormChanges/TagFormChanges.tsx
src/app/preferences/views/SSLKeys/AddSSLKey/AddSSLKey.tsx
src/app/subnets/views/FormActions/components/AddSubnet.tsx
src/app/subnets/views/SubnetsList/SubnetsTable/components.tsx
src/testing/utils.tsx

- add react no-multi-comp rule
- (we already have a 1 component per file rule in MAAS but it wasn't enforced by eslint - https://github.com/canonical/maas-ui/pull/4333#discussion_r943008337)
Fixes: https://github.com/canonical/app-tribe/issues/1266
In general, please propose …

test: add react no-multi-comp rule

---

src/app/pools/components/PoolForm/PoolForm.test.tsx
src/app/pools/components/PoolForm/PoolForm.tsx
src/app/pools/views/PoolAdd/PoolAdd.test.tsx
src/app/pools/views/PoolList/PoolList.test.tsx
src/app/pools/views/PoolList/PoolList.tsx

- [src/app/pools/components/PoolForm/PoolForm.test.tsx](https://github.com/canonical/maas-ui/compare/main...ndv99:rtlMigration_pools?expand=1#diff-d6a591db18400d410511a4fff1a233e3ebf487df1f2b4cc0ba973e6519eaa737)
- [src/app/pools/views/PoolAdd/PoolAdd.test.tsx](https://github.com/canonical/maas-ui/compare/main...ndv99:rtlMigration_pools?expand=1#diff-c916501a4435731b1f1fa9668217502086439b0a9aa3d7b9ed20388a3c3ecf0a)
- [src/app/pools/views/PoolList/PoolList.test.tsx](https://github.com/canonical/maas-ui/compare/main...ndv99:rtlMigration_pools?expand=1#diff-31d15a73b940bc94d81dfb409ea6390f6b6a5831e2762dd93bd13441bf95bc91)
Fixes https://github.com/canonical/app-tribe/issues/1061

Migrate to RTL - app/pools

---

src/app/settings/views/Configuration/GeneralForm/ThemedRadioButton/_index.scss

- Changed the size of the box shadow (radio button dot) to 0.52rem. _Note: the size appears identical in the browser, but this ensures that the dot shows at all zoom levels._
1. Log in and navigate to settings/configuration/general
2. Zoom in and out to all available levels
3. Ensure that the white dot remains visible on the …

Fix vanishing radio button dot for theme selector

---

src/app/machines/views/MachineList/MachineList.tsx
src/app/store/machine/selectors.test.ts
src/app/store/machine/selectors.ts
src/app/store/machine/utils/hooks.ts

- Remove support for in:selected from the machines DSL as it's not possible with the server side
search API.
n/a
Fixes: canonical/app-tribe#1265.

refactor(machines): remove in:selected from machines DSL

---

src/app/machines/components/MachineHeaderForms/ActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.test.tsx
src/app/machines/components/MachineHeaderForms/ActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.tsx

- Handle deploying machines when the default kernel is not in the default release.
- Go to Settings ->  Commissioning and select a default release and minimum kernel and save.
- Go to Settings -> Deploy and choose a different release and save.
- Go to the Machine list and tick a deployable machine and open the deploy form via …

fix(machines): fix deploy with mismatched default release and kernel

---

src/app/kvm/components/VmResources/VmResources.tsx
src/app/machines/views/MachineList/MachineList.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListTable.test.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListTable.tsx
src/app/machines/views/MachineList/MachineListTable/index.ts
src/app/store/machine/actions.test.ts
src/app/store/machine/types/actions.ts
src/app/store/machine/utils/hooks.test.tsx
src/app/store/machine/utils/hooks.ts
src/app/tags/views/TagMachines/TagMachines.tsx

- Update the machine list to send the sort params to the API call.
- Click some of the table headers and the machines should be refetched.
Fixes: canonical/app-tribe#1262.

feat(machines): sort the machine list via the API

---

src/app/kvm/components/VmResources/VmResources.tsx
src/app/machines/views/MachineList/MachineList.test.tsx
src/app/machines/views/MachineList/MachineList.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListTable.test.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListTable.tsx
src/app/store/machine/selectors.test.ts
src/app/store/machine/selectors.ts
src/app/store/machine/utils/hooks.test.tsx
src/app/store/machine/utils/hooks.ts
src/app/tags/views/TagMachines/TagMachines.tsx

- Add pagination to the machine list using the new API.
To test this you either need more than one page of machines using [sampledata](https://github.com/canonical/maas-ui/blob/main/docs/HACKING.md#sample-data) or change [`const pageSize = DEFAULT_PAGE_SIZE;`](https://github.com/canonical/maas-ui/pull/4344/files#diff-2b86f4686bb7 …

feat(machines): paginate using the new API

---

src/app/store/machine/selectors.test.ts
src/app/store/machine/selectors.ts

- Add a selector for getting the selected machines state.
n/a
Fixes: canonical/app-tribe#1275

feat(redux): add selected machines selector

---

src/testing/utils.tsx

- Support passing the full store object to render utils. This is needed when testing dispatches (e.g. when using `store.getActions()`).
n/a
Fixes: canonical/app-tribe#1277.

feat(testing): support passing the store to render methods

---

src/app/machines/views/MachineList/MachineList.test.tsx
src/app/machines/views/MachineList/MachineList.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListTable.test.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListTable.tsx
src/app/store/machine/selectors.test.ts
src/app/store/machine/selectors.ts
src/app/store/machine/utils/hooks.ts
src/app/tags/views/TagMachines/TagMachines.test.tsx

- Display groups in the machine list as returned from the API.
- Visit the machine list.
- You should see grouped machines in the last.
- Change the grouping and the list should update with the new groups.
Fixes: canonical/app-tribe#1261.

feat(machines): display groups from API

---

src/app/machines/views/MachineList/MachineList.test.tsx
src/app/machines/views/MachineList/MachineList.tsx
src/app/machines/views/MachineList/MachineListHeader/MachineListHeader.test.tsx
src/app/machines/views/MachineList/MachineListHeader/MachineListHeader.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListTable.test.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListTable.tsx
src/app/store/machine/selectors.test.ts
src/app/store/machine/selectors.ts
src/app/store/machine/utils/hooks.test.tsx
src/app/store/machine/utils/hooks.ts

- Pass the loading state from the list request to the machine list header and table.
- You should see a spinner in the header and table while the list and counts load.
- Do a search (e.g. `owner:admin`). You should see a spinner in the table (this will be replaced by the loading skeleton in …

feat(machines): pass loading states to machine list

---

src/scss/_patterns_navigation.scss

- add a background-color transition to the navigation
Fixes: # . …

feat: add navigation background transition

---

src/app/machines/views/MachineList/MachineList.tsx
src/app/store/machine/utils/hooks.test.tsx
src/app/store/machine/utils/hooks.ts

- Pass the options as an object to the useFectchMachines hook.
- Change the sort order or do a search.
- The table should update with the new machines.
Fixes: canonical/app-tribe#1283.

refactor(machines): pass an options object to useFetchMachines

---

src/app/base/components/NodeActionMenu/NodeActionMenu.test.tsx
src/app/base/components/NodeActionMenu/NodeActionMenu.tsx
src/app/controllers/views/ControllerDetails/ControllerDetailsHeader/ControllerDetailsHeader.tsx
src/app/controllers/views/ControllerList/ControllerListHeader/ControllerListHeader.tsx
src/app/devices/views/DeviceDetails/DeviceDetailsHeader/DeviceDetailsHeader.tsx
src/app/devices/views/DeviceList/DeviceListHeader/DeviceListHeader.tsx
src/app/kvm/components/LXDVMsTable/VMsActionBar/VMsActionBar.tsx
src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.tsx
src/app/machines/views/MachineList/MachineListHeader/MachineListHeader.tsx

- Update the take action menu to not show counts and display all options on the machine list.
- The take action menu should be disabled.
- Tick some machines.
- Open the take action menu and there should not be any counts next to the actions and all should be visible and enabled.
- Got to the controller …

feat(actions): remove take action counts and show all options

---

src/app/base/components/Placeholder/Placeholder.tsx
src/app/base/components/Placeholder/__snapshots__/Placeholder.test.tsx.snap
src/app/machines/views/MachineList/MachineListTable/MachineListPagination/MachineListPagination.test.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListPagination/MachineListPagination.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListPagination/index.ts
src/app/machines/views/MachineList/MachineListTable/MachineListTable.test.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListTable.tsx
src/app/machines/views/MachineList/_index.scss

- Display the loading skeleton while the machine list is fetching machines.
- You should see the loading skeleton appear.
- Try changing the page, the sort order, do a search or change the grouping and you should see the skeleton.
Fixes: canonical/app-tribe#1100.

feat(machines): add skeleton while machines are loading

---

src/app/machines/components/MachineHeaderForms/ActionFormWrapper/ActionFormWrapper.test.tsx
src/app/machines/components/MachineHeaderForms/ActionFormWrapper/ActionFormWrapper.tsx
src/testing/utils.tsx

- Update the machine list action forms to not show an "update selection" link.
- Go to the machine list and select a few machines.
- Open the take action menu.
- Scroll down the page a little.
- Click on an action in the take action menu that not all machines can perform (while still scrolled).
- You should get scrolled to the …

feat(machines): remove "update selection" link

---

.eslintrc.js
src/app/machines/views/MachineList/MachineList.test.tsx
src/app/machines/views/MachineList/MachineList.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListTable.tsx
src/app/store/machine/types/actions.ts
src/app/store/machine/utils/index.ts
src/app/store/machine/utils/search.test.ts
src/app/store/machine/utils/search.ts

- Parse the search DSL string and send the filters to the API call.
- Type in some text that will match some param of a machine e.g. part of a hostname, a user's name etc. and the table should update with the results.
- Type in a search for a specific param e.g. status: new, tags:..., hostname:... etc. …

feat(machines): parse search DSL and send to new API

---

src/app/kvm/views/LXDClusterDetails/LXDClusterDetails.tsx
src/app/kvm/views/LXDClusterDetails/LXDClusterHostVMs/LXDClusterHostVMs.tsx

- fix(ui): lxd cluster route infinite loading
- using bolla as a back-end go to `/MAAS/r/kvm/lxd/cluster/29/vms/518` and verify the page loads in full
Fixes: https://github.com/canonical/app-tribe/issues/1331 …

fix(ui): lxd cluster route infinite loading

---

src/app/kvm/components/LXDVMsTable/LXDVMsTable.tsx
src/app/kvm/components/LXDVMsTable/VMsActionBar/VMsActionBar.test.tsx
src/app/kvm/components/LXDVMsTable/VMsActionBar/VMsActionBar.tsx
src/app/kvm/components/LXDVMsTable/VMsTable/NameColumn/NameColumn.tsx
src/app/kvm/components/LXDVMsTable/VMsTable/VMsTable.test.tsx
src/app/kvm/components/LXDVMsTable/VMsTable/VMsTable.tsx
src/app/machines/views/MachineList/MachineListHeader/MachineListHeader.test.tsx
src/app/machines/views/MachineList/MachineListHeader/MachineListHeader.tsx
src/app/store/machine/utils/hooks.test.tsx
src/app/store/machine/utils/hooks.ts

- Use the new selected state to check VMs in the KVM tables.
- The take action menu should be disabled and the add hardware button should be enabled.
- Tick some machines and the take action menu should get enabled and the add hardware button should get disabled.
- Go to KVM -> cluster -> Virtual …

feat(kvm): update KVM tables to use new selected state

---

README.md

replace non-existent MAAS UI link with discourse MAAS Tribe page
Fixes #4367
Fixes: # . …

Fix MAAS UI team 404 link in README

---

package.json

- add test-ui:debug command
- add a `debugger;` statement to one of your tests, e.g. `AddTagForm.test.tsx`
- run yarn run `test-ui:debug AddTagForm.test.tsx`
- open google chrome and go to chrome://inspect
- open remote target inspector
- test should run and the execution should be stopped at the debugger statement
Related …

test: add test debug command

---

src/app/dashboard/views/DiscoveryAddForm/DiscoveryAddForm.test.tsx
src/app/dashboard/views/DiscoveryAddForm/DiscoveryAddForm.tsx
src/app/dashboard/views/DiscoveryAddForm/DiscoveryAddFormFields/DiscoveryAddFormFields.tsx

- fix(ui): discovery add form
- Go to machine discovery and open add discovery form
- Make sure the form loads
Fixes #4387 .
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. …

fix(ui): discovery add form

---

src/app/base/components/NodeConfigurationFields/NodeConfigurationFields.test.tsx
src/app/base/components/node/NodeActionFormWrapper/NodeActionFormWrapper.test.tsx
src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagForm.test.tsx
src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagFormFields/TagFormFields.test.tsx
src/app/tags/components/AddTagForm/AddTagForm.test.tsx
src/app/tags/components/TagsHeader/AddTagForm/AddTagForm.test.tsx
src/app/tags/views/TagUpdate/TagUpdate.test.tsx
src/testing/mockFormikFormSaved.tsx

- add `mockFormikFormSaved` util to make simulating `FormikForm` save easier
Fixes: https://github.com/canonical/app-tribe/issues/1337
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless the fix is only applicable …

test: add mockFormikFormSaved util

---

src/app/base/components/TagSelector/TagSelector.tsx
src/app/store/machine/reducers.test.ts
src/app/store/machine/slice.ts

- Set the loading states once machines have been fetched.
- Check that in the header the spinner eventually disappears and the count of machines is shown.
- Go to Settings -> DHCP snippets -> Add snippet
- Change the 'type' to "Machine".
- The spinner should appear and then get replaced with a select …

fix(machines): fix the machines loading state

---

src/app/kvm/components/LXDVMsTable/LXDVMsTable.tsx
src/app/kvm/components/LXDVMsTable/VMsActionBar/VMsActionBar.tsx
src/app/kvm/components/LXDVMsTable/VMsTable/VMsTable.test.tsx
src/app/kvm/components/LXDVMsTable/VMsTable/VMsTable.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListPagination/MachineListPagination.tsx
src/app/store/machine/utils/hooks.ts
src/app/store/machine/utils/index.ts

- Display the skeleton rows when loading VMs in the LXD tables.
- Go to KVM -> click on cluster or single host -> virtual machines tab.
- As the table loads you should see the skeleton.
- Change the page or sort or search and you should see the skeleton.
Fixes: canonical/app-tribe#1323.

feat(kvm): display skeleton when loading VMs

---

src/app/machines/views/Machines.test.tsx
src/app/machines/views/Machines.tsx

- Remove the filtering of the machine list by those that are selected when the action forms open.
- Tick some machines.
- Use the take action menu to open a form.
- The search box should not have "in:selected" and the machine list should not get filtered.
Fixes: canonical/app-tribe#1334.

feat(machines): remove filtering by selected when opening action forms

---

src/app/machines/views/MachineList/MachineListHeader/MachineListHeader.test.tsx
src/app/machines/views/MachineList/MachineListHeader/MachineListHeader.tsx
src/app/machines/views/MachineList/MachineListTable/GroupCheckbox/GroupCheckbox.test.tsx
src/app/machines/views/MachineList/MachineListTable/GroupCheckbox/GroupCheckbox.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListTable.tsx
src/app/machines/views/Machines.tsx
src/app/store/machine/slice.ts
src/app/store/machine/types/actions.ts
src/app/store/machine/types/base.ts
src/app/store/machine/utils/common.test.ts
src/app/store/machine/utils/common.ts
src/app/store/machine/utils/hooks.ts
src/app/store/machine/utils/index.ts

- Display the count of machines that have been selected in the machine list.
- Tick some machines and you should see the count update instantly in the header.
- Untick all machines and tick a group (you'll need to be grouped by something other than status e.g. owner). You should see the count get loaded …

feat(machines): display the count of selected machines

---

src/app/kvm/components/LXDVMsTable/LXDVMsTable.tsx
src/app/kvm/components/VmResources/VmResources.tsx
src/app/machines/views/MachineList/MachineList.tsx
src/app/store/machine/utils/hooks.test.tsx
src/app/store/machine/utils/hooks.ts
src/app/tags/views/TagMachines/TagMachines.tsx

- reset useFetchMachines page on filters change
You may need to modify the default page size in order to see pagination depending on how many machines there are in the MAAS you test this with.
- Check out this branch locally
- Change the `pageSize` value to `2` in `src/app/machines/views/MachineList/MachineListTable/constants.ts` …

feat(machines): reset useFetchMachines page on filters change

---

src/app/machines/views/MachineList/MachineListHeader/MachineListHeader.test.tsx
src/app/machines/views/MachineList/MachineListHeader/MachineListHeader.tsx

- close action form when all machines are deselected
**Make sure you do not have Group by status selected** - it doesn't yet work with the new API. Any other grouping (e.g. by owner) should work.
- Select a few machines
- Open the action form by clicking Take action and selecting an action from the list
- …

feat(machines): close action form when deselected

---

src/app/base/components/node/NodeActionFormWrapper/NodeActionFormWrapper.tsx
src/app/machines/components/MachineHeaderForms/ActionFormWrapper/ActionFormWrapper.tsx
src/app/machines/components/MachineHeaderForms/MachineHeaderForms.tsx
src/app/machines/views/MachineList/MachineListHeader/MachineListHeader.test.tsx
src/app/machines/views/MachineList/MachineListHeader/MachineListHeader.tsx
src/app/store/machine/utils/hooks.test.tsx
src/app/store/machine/utils/hooks.ts

- make the new API work for all machine listing actions
- pass selected state to action forms - this maintains the current functionality and displays the counts of actionable machines and dispatches actions on them individually
- extract selected count logic to `useMachineSelectedCount` hook
- add isEnabled option to useFetchMachines to allow skipping API calls
- add `useFetchSelectedMachines` hook to make sure we have the data for all selected machines
_Note: This will be followed by work intended to use machine filters instead of individual machines as what's passed into actions first (potentially adopting progressive enhancement approach)._ https://github.com/canonical/app-tribe/issues/1373
- …

feat(machines): update action forms to use new API

---

cypress/e2e/with-users/settings/configuration/kernel-parameters.spec.ts
src/app/settings/views/Configuration/KernelParametersForm/KernelParametersForm.tsx

- fix kernel parameters resetting after save
- add e2e test for kernel parameters
- go to `MAAS/r/settings/configuration/kernel-parameters`
- change the text value and save
- text should remain unchanged once it's saved
- reload the page, form should show the saved value
- remove the text, save
- reload the page, form should …

fix: kernel parameters reset after save #4417

---

package.json

- increase test timeout for jest debug (we don't want tests to time out too quickly to allow prolonged interaction with the debugger whilst they're running)
Fixes: https://github.com/canonical/app-tribe/issues/1371 …

increase test timeout for jest debug

---

src/app/store/machine/types/actions.ts
src/app/store/machine/types/base.ts

- feat: add parent fetch filter
Fixes: https://github.com/canonical/app-tribe/issues/1367 …

feat: add parent fetch filter

---

cypress/e2e/with-users/settings/configuration/general.spec.ts
src/app/settings/views/Configuration/GeneralForm/GeneralForm.tsx

- fix: cancel does not reset general settings
- add e2e test for general settings cancel action
- Go to `MAAS/r/settings/configuration/general`
- Change any input value on the page (e.g. MAAS name)
- Click cancel
- Verify the input has been reverted to the original value
Fixes: #4411  . …

fix: cancel does not reset general settings

---

src/app/base/components/NodeActionMenu/NodeActionMenu.test.tsx
src/app/base/components/NodeActionMenu/NodeActionMenu.tsx
src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.tsx

- fix: machine details take action list not displaying all available items for a machine
- Select a machine from machine listing and go to machine details page
- Verify that all actions available for the machine are displayed
Fixes: https://github.com/canonical/app-tribe/issues/1389 …

fix: machine details take action list

---

src/app/base/sagas/websockets.test.ts
src/app/base/sagas/websockets.ts

- fix updating multiple settings fields
- wait for config success messages instead of notify
- Go to the Settings page and change the theme colour
- Click save
- Reload the page and make sure the setting have been persisted
This change can affect any page that uses `dispatchMultiple` option for the websocket API (Commissioning …

fix(settings): updating multiple fields

---

src/app/base/types.ts
src/app/store/machine/slice.ts
src/app/store/utils/slice.ts
src/testing/factories/state.ts

- add machine action result count
- move machine specific (machine.actions slice) logic to `src/app/store/machine/slice.ts`
- Perform an action on a machine (e.g. test)
- Verify that the count value in the store has been updated (in `machine.actions["random-call-id"].counts`)
Fixes: …

refactor(machines): add action result count to redux store

---

src/app/base/components/node/FieldlessForm/FieldlessForm.tsx
src/app/kvm/components/KVMHeaderForms/KVMHeaderForms.test.tsx
src/app/kvm/components/KVMHeaderForms/KVMHeaderForms.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/MachineActionFormWrapper.test.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/MachineActionFormWrapper.tsx
src/app/machines/types.ts
src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.tsx
src/app/store/machine/utils/hooks.test.tsx
src/app/store/machine/utils/hooks.ts
src/testing/factories/index.ts
src/testing/factories/state.ts

- pass selected state to machine details
- add `useMachineActionDispatch` for handling machine actions and their status in a single hook
- Go to machine details page
- Select an action from the "Take action" menu (e.g. test, abort)
- Verify that the action has been dispatched using a "filter", e.g. { filter: { id: …

feat: use filter key for machine details actions

---

src/app/base/components/ActionForm/ActionForm.tsx
src/app/base/components/node/FieldlessForm/FieldlessForm.tsx
src/app/base/components/node/TestForm/TestForm.tsx
src/app/base/components/node/types.ts
src/app/base/types.ts
src/app/kvm/components/KVMHeaderForms/KVMHeaderForms.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/CommissionForm/CommissionForm.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/DeployForm/DeployForm.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/MachineActionFormWrapper.test.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/MachineActionFormWrapper.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/MarkBrokenForm/MarkBrokenForm.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/OverrideTestForm/OverrideTestForm.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/ReleaseForm/ReleaseForm.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/SetPoolForm/SetPoolForm.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/TagForm/TagForm.test.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/TagForm/TagForm.tsx
src/app/machines/components/MachineHeaderForms/MachineHeaderForms.tsx
src/app/machines/types.ts
src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.tsx
src/app/machines/views/MachineList/MachineListHeader/MachineListHeader.tsx
src/app/store/machine/slice.ts
src/app/store/machine/types/base.ts
src/app/store/machine/utils/hooks.test.tsx
src/app/store/machine/utils/hooks.ts
src/app/store/pod/slice.ts
src/app/store/utils/slice.test.ts
src/app/store/utils/slice.ts
src/testing/factories/state.ts

- handle bulk machine actions results (failed system id count and success count)
- add `useSelectedMachinesActionsDispatch` hook for handling of multiple action dispatches when there are groups and items selected
- stricter type checking for machine slice reducer with `MachineActionStatus`
- refactor to use `selectedMachines` instead of selectedFilter (initially I wanted to simplify this, but because we need to handle multiple dispatches in case there are selected both groups and items this was not possible)
- [A local snap MAAS](/HACKING.md#snap-deployment) (this will not usually have …

feat(machines): handle bulk actions results

---

src/app/base/components/ErrorBoundary/ErrorBoundary.tsx

- Login as a non-admin user (credentials on lastpass for `user1`)
- Go to `/MAAS/r/kvm/lxd`
- Verify the updated notification style is used
Fixes: https://github.com/canonical/app-tribe/issues/1399
In general, please propose …

feat: update error boundary notification

---

src/app/machines/views/MachineList/MachineList.test.tsx
src/app/machines/views/MachineList/MachineList.tsx
src/app/machines/views/MachineList/MachineListTable/constants.ts
src/app/store/machine/types/actions.ts

- fix: cannot resolve none into field
- set the localStorage value for grouping as "none"
- refresh the page
- machine list grouping should be set to "status" both in the UI and in the machine.list websocket request
- verify you can select "None" as a value and it gets persisted when you refresh the page …

fix: cannot resolve none into field

---

src/app/base/components/DHCPTable/DHCPTable.tsx
src/app/base/components/DhcpForm/DhcpForm.tsx
src/app/base/components/DhcpForm/types.ts
src/app/base/components/DhcpFormFields/DhcpFormFields.test.tsx
src/app/base/components/DhcpFormFields/DhcpFormFields.tsx
src/app/base/components/DhcpSnippetType/DhcpSnippetType.tsx
src/app/settings/hooks.ts
src/app/settings/views/Dhcp/DhcpList/DhcpList.tsx
src/app/store/dhcpsnippet/types/actions.ts
src/app/store/dhcpsnippet/types/base.ts
src/app/store/iprange/utils.ts
src/app/subnets/components/DHCPSnippets/DHCPSnippets.tsx
src/testing/factories/dhcpsnippet.ts

- feat: allow setting IP Ranges DHCP Snippets type
- Set bolla as MAAS_URL
- Go to DHCP Settings page - MAAS/r/settings/dhcp
- Add a DHCP snippet of type "IP Range"
- Save the snippet
- Click on the subnet link for the snippet you just created
- Verify the IP Range is displayed on the Subnet details page in the IP Ranges section …

feat: DHCP Snippets IP Ranges inputs

---

src/__snapshots__/root-reducer.test.ts.snap
src/app/store/tag/actions.test.ts
src/app/store/tag/reducers.test.ts
src/app/store/tag/selectors.test.ts
src/app/store/tag/selectors.ts
src/app/store/tag/slice.ts
src/app/store/tag/types/base.ts
src/testing/factories/state.ts

- add logic for handling multiple tag lists with different filters
- Verify that tags are displayed for each machine and in machine details page as before
Fixes: https://github.com/canonical/app-tribe/issues/1404 …

refactor(machines): multiple tag lists handling

---

src/app/store/tag/actions.test.ts
src/app/store/tag/slice.ts

- rename tag filter param to node_filter
- related back-end change: https://code.launchpad.net/~alexsander-souza/maas/+git/maas/+merge/431450
- Go to machine list and verify tags are displayed correctly
- Go to machine details and verify tags are displayed correctly
Fixes: https://github.com/canonical/app-tribe/issues/1414 …

rename tag filter param to node_filter

---

src/app/settings/views/Images/VMWareForm/VMWareForm.test.tsx
src/app/settings/views/Images/VMWareForm/VMWareForm.tsx

- Change vCenter password field type to "password"
- Go to settings/images/vmware
- Type anything in the "VMware vCenter password" field
- Ensure the text you type is hidden with dots
Fixes #4427.
lp#1991106

fix: vCenter password field text is visible in settings #4427

---

src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/TagForm/AddTagForm/AddTagForm.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/TagForm/TagChip/TagChip.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/TagForm/TagForm.test.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/TagForm/TagForm.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/TagForm/TagFormChanges/TagFormChanges.test.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/TagForm/TagFormChanges/TagFormChanges.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/TagForm/TagFormFields/TagFormFields.test.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/TagForm/TagFormFields/TagFormFields.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/TagForm/hooks.test.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/TagForm/hooks.ts
src/app/machines/views/MachineDetails/MachineConfiguration/TagForm/TagForm.tsx
src/app/store/machine/slice.ts
src/app/store/tag/reducers.test.ts
src/app/store/tag/selectors.ts
src/app/store/tag/slice.ts
src/app/store/tag/utils.ts

- handle tag actions using the new API
- select a few individual machines
- Go to Take action -> Tag
- Verify that tag counts displayed are correct for the current tags
- Remove a tag and add a new one to the machines selected
- Save
- Ensure the websocket message has been sent with the correct payload …

feat(machines): tag actions using the new API

---

src/app/store/machine/reducers.test.ts
src/app/store/machine/slice.ts

- fix machines listing when using browser history navigation
- Click on machine details
- Go back, go forward, go back using browser navigation
- Machine listing should load
Fixes: https://github.com/canonical/app-tribe/issues/1421 …

fix(machines): browser history navigation between pages

---

cypress/e2e/with-users/machines/details.spec.ts
src/app/base/components/node/DeleteForm/DeleteForm.tsx

- Select a machine to delete
- Go to take action -> delete
- Make sure the delete form has been closed
- Go to machine details page
- Go to take action -> delete
- Make sure the delete form has been closed and you have been redirected to machine listing …

fix: machine delete success

---

src/app/subnets/views/SubnetDetails/SubnetSummary/SubnetSummary.tsx
src/app/subnets/views/SubnetDetails/SubnetSummary/SubnetSummaryForm/SubnetSummaryFormFields/SubnetSummaryFormFields.tsx
src/app/subnets/views/SubnetDetails/SubnetSummary/components/ActiveDiscoveryLabel/ActiveDiscoveryLabel.test.tsx
src/app/subnets/views/SubnetDetails/SubnetSummary/components/ActiveDiscoveryLabel/ActiveDiscoveryLabel.tsx
src/app/subnets/views/SubnetDetails/SubnetSummary/components/ManagedAllocationLabel/ManagedAllocationLabel.test.tsx
src/app/subnets/views/SubnetDetails/SubnetSummary/components/ManagedAllocationLabel/ManagedAllocationLabel.tsx

- fix: info icons disappearing on toggle
- Go to subnet details page
- Verify that the tooltip for "Managed allocation" and "Active discovery" is displayed regardless of the checkbox checked state
Fixes: https://github.com/canonical/maas-ui/issues/4464 …

fix: info icons disappearing on toggle

---

src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.tsx

- enable jammy kvm host option
- Select a machine to deploy
- Make sure you can select Ubuntu 22.04 and enable "Register as MAAS KVM host."
Fixes: https://github.com/canonical/maas-ui/issues/4463
In general, please propose fixes against _main_ rather than release branches …

fix: enable jammy kvm host option

---

src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/TagForm/AddTagForm/AddTagForm.test.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/TagForm/AddTagForm/AddTagForm.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/TagForm/TagFormFields/TagFormFields.tsx
src/app/store/machine/utils/common.ts
src/app/store/machine/utils/hooks.test.tsx
src/app/store/machine/utils/hooks.ts
src/app/tags/components/AddTagForm/AddTagForm.tsx
src/app/tags/components/KernelOptionsField/KernelOptionsField.test.tsx
src/app/tags/components/KernelOptionsField/KernelOptionsField.tsx

- fix warning message deployed machines count
- Go to machine list -> tags (`/MAAS/r/tags`)
- Select create a new tag
- Type in some kernel options
- Verify there is no warning message about the count of deployed machines
- Select a tag that has kernel options and some deployed machines from the list
- Click edit
- Edit the …

fix(machines): warning message for deployed machines

---

cypress/e2e/with-users/machines/actions.spec.ts

- test: create a machine before action tests
_Note: some of the action tests will still fail, but it's intentional - it's indicative of bugs that we need to fix in server-side filtering_
Fixes: # .
In general, please propose fixes against _main_ rather than …

test: create a machine before action tests

---

src/app/base/components/FilterAccordion/_index.scss

- fix misaligned filter items
- Open filters
- Verify filter items are aligned with the toggle button
Fixes: https://github.com/canonical/maas-ui/issues/4491 …

fix: misaligned filter items

---

src/__snapshots__/root-reducer.test.ts.snap
src/app/store/controller/selectors.test.ts
src/app/store/controller/selectors.ts
src/app/store/controller/types/base.ts
src/app/store/general/actions.test.ts
src/app/store/general/reducers.test.ts
src/app/store/general/selectors/index.ts
src/app/store/general/selectors/vaultEnabled.test.ts
src/app/store/general/selectors/vaultEnabled.ts
src/app/store/general/slice.ts
src/app/store/general/types/base.ts
src/app/store/general/types/index.ts
src/testing/factories/index.ts
src/testing/factories/nodes.ts
src/testing/factories/state.ts

- Create selector to get vaultEnabled status (true/false)
- Add vaultConfigured to base controller type
- Create selector to split region controllers by vault configuration status (true/false)
- Add vaultEnabledState to general base type
- Write appropriate tests for the above and update others where necessary
- Add vaultEnabledState and vaultConfigured to appropriate factories
Fixes https://github.com/canonical/app-tribe/issues/1405

feat(vault): add backend integration

---

src/app/base/components/MachineSelectTable/MachineSelectTable.test.tsx
src/app/base/components/MachineSelectTable/MachineSelectTable.tsx

- fix: clone form search regex
- Select a machine and press Take action -> "Clone from"
- Type in a partial filter text `id:(`
- Verify there are no errors thrown and the table is still visible
- Type in a search string that matches one of the machines displayed
- Verify the name has a highlight matching …

fix: clone form search regex

---

src/app/intro/views/MaasIntro/ConnectivityCard/ConnectivityCard.test.tsx
src/app/intro/views/MaasIntro/ConnectivityCard/ConnectivityCard.tsx

- fix: encoded amp character
- use unicode character instead of HTML entity
- refactor and add test case to `ConnectivityCard.test.tsx`
Fixes: https://github.com/canonical/maas-ui/issues/4494 …

fix: encoded amp character

---

cypress/e2e/with-users/machines/actions.spec.ts

- update machine action button regex
Fixes: # .
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. Please apply backport labels to the PR (e.g. "Backport 2.7") …

test: update machine action button regex

---

.github/workflows/sitespeed.yml

- update maasdb for the sitespeed job
Fixes: # .
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. Please apply backport labels to the PR (e.g. "Backport 2.7") …

test: update sitespeed maasdb

---

src/app/base/components/node/MachinesHeader/MachinesHeader.test.tsx
src/app/base/components/node/MachinesHeader/MachinesHeader.tsx
src/app/machines/views/MachineList/MachineListHeader/MachineListHeader.test.tsx
src/app/machines/views/MachineList/MachineListHeader/MachineListHeader.tsx
src/app/pools/views/Pools.tsx
src/app/store/machine/utils/hooks.test.tsx
src/app/store/machine/utils/hooks.ts
src/app/store/machine/utils/search.test.ts
src/app/store/machine/utils/search.ts
src/app/tags/components/TagsHeader/TagsHeader.tsx

- Verify that only 2 machine.count API calls are made when there are no search filters
- Select a filter
- Verify that a single additional single call has been made for the count of machines matching the selected filter
Fixes: …

fix(machines): repeated machine.count API calls

---

src/app/kvm/components/KVMDetailsHeader/KVMDetailsHeader.tsx
src/app/kvm/components/KVMHeaderForms/KVMHeaderForms.tsx
src/app/kvm/components/LXDVMsTable/LXDVMsTable.tsx
src/app/kvm/components/LXDVMsTable/VMsTable/VMsTable.test.tsx
src/app/kvm/components/LXDVMsTable/VMsTable/VMsTable.tsx

- feat(kvm): pass selected state to action forms
-  Go to virtual machines page (e.g. `/MAAS/r/kvm/lxd/2/vms`)
- Select all VMs on the list
- Dispatch an action (e.g. Abort)
- Verify the machine.action was dispatched with the right parameter (including a pod that limits the request to that particular pod) and response returned …

feat(kvm): pass selected state to action forms

---

.github/workflows/accessibility.yml
.github/workflows/cypress.yml
.github/workflows/lp-to-gh-issues.yml
.github/workflows/sitespeed.yml
.github/workflows/test.yml
.github/workflows/upload.yml

Upgrade GH actions to run on Ubuntu 22.04 for:
- Accessibility
- Cypress
- Sitespeed
- CI (Lint/Build/Test/Dotrun)
Fixes #4220

chore: Upgrade GitHub actions to Ubuntu 22.04

---

src/scss/_patterns_icons.scss

- Change Vault status icon colours to accessible grey `#666`
Requested by @lyubomir-popov

fix(vault): Change icon colours to accessible grey

---

package.json
src/index.tsx

expose maas-ui version info
- add git sha to the metadata in the index.html
- log the git sha in the browser console
This is using the full hash as it's consistent with the package name that's generated by the upload script:
https://github.com/canonical/maas-ui/runs/8159279483?check_suite_focus=true#step:8:5
https://github.com/canonical/maas-ui/blob/main/.github/workflows/upload.yml#L11 …

expose maas-ui version info

---

src/app/App.tsx

- add release info to sentry
Fixes: # . …

add release info to sentry

---

src/app/controllers/views/ControllerList/ControllerList.tsx

- Hide the "Incomplete Vault integration" warning in controller listing if Vault setup has not begun
- Ensure there are no Vault-related warning messages on the Controller list (bolla/polong)

fix(vault): Hide warning message in controller list before Vault setup

---

src/app/base/components/VaultNotification/VaultNotification.test.tsx
src/app/base/components/VaultNotification/VaultNotification.tsx
src/app/base/components/VaultNotification/index.ts
src/app/controllers/views/ControllerList/ControllerList.tsx
src/app/machines/views/MachineList/MachineList.tsx

- display vault notification only once the data has loaded (this fixes a flash of the vault notification on load)
- move vault notification into own component
- use react-router `Link` component with `to` prop
- Verify that vault notification is displayed under the same conditions as before.
Fixes: # .
Related Launchpad maas …

fix: display vault notification once loaded

---

src/app/App.tsx

- fix: render logged in routes on auth fully loaded
- this fixes a flash of logged routes that would cause components to briefly render (and in the case of machine listing request machines more than once after refresh/login).
- Verify that you can log in and log out
- Go to machine listing and verify that machines were requested …

fix: render routes on auth loaded

---

src/app/base/components/node/DeleteForm/DeleteForm.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/MachineActionFormWrapper.test.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/MachineActionFormWrapper.tsx

- fix: clear machine list selection on delete success
Repeat the steps below on the machine list and kvm page (`/MAAS/r/kvm/lxd/[id]/vms`):
- Delete a machine
- Verify the number of selected machines is 0 after deletion
In general, please propose fixes against _main_ rather …

fix: clear machine list selection on delete success

---

.github/workflows/sitespeed.yml
package.json
sitespeed.io/config.json
sitespeed.io/login.js
sitespeed.io/scripts/machines.js
sitespeed.io/utils.js

- add sitespeed workflow to 3.2
Fixes: # .
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. Please apply backport labels to the PR (e.g. "Backport 2.7") for …

add sitespeed workflow to 3.2

---

cypress/e2e/with-users/machines/list.spec.ts
src/app/kvm/components/KVMHeaderForms/DeleteForm/DeleteForm.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/MachineActionFormWrapper.test.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/MachineActionFormWrapper.tsx
src/app/store/machine/reducers.test.ts
src/app/store/machine/selectors.ts
src/app/store/machine/slice.ts
src/app/store/machine/types/base.ts
src/app/store/machine/utils/hooks.test.tsx
src/app/store/machine/utils/hooks.ts
src/testing/factories/state.ts

- refetch machines on after delete
- invalidate queries on after delete
- add stale status to machine requests
- Delete a machine
- Ensure the list of machines and machine counts in the header have been updated
Fixes: https://github.com/canonical/maas-ui/issues/4487
Related Launchpad maas issue in the …

fix: refetch machines on after delete

---

src/app/base/components/FilterAccordion/FilterAccordion.tsx
src/app/dashboard/views/DiscoveriesList/DiscoveriesFilterAccordion/DiscoveriesFilterAccordion.test.tsx
src/app/machines/views/MachineList/MachineListControls/MachinesFilterAccordion/MachinesFilterAccordion.tsx

- fix: remove colon from filters label
- Verify the machine filters label label has ben updated to `Filters`
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific …

fix: remove colon from filters label

---

src/app/App.tsx
src/app/base/components/Footer/Footer.tsx
src/scss/index.scss

- set background to white
Fixes: https://github.com/canonical/maas-ui/issues/4543
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. Please apply backport labels …

feat: set background to white

---

src/app/base/hooks/analytics.ts

- enable Google Analytics in production before release
- Verify that google analytics script (`https://www.googletagmanager.com/gtm.js?id=GTM-P4TGJR9`) has been loaded by checking the Network tab in developer tools
In general, please propose fixes …

enable GA in prod

---

src/app/machines/views/MachineList/MachineListHeader/MachineListHeader.test.tsx
src/app/machines/views/MachineList/MachineListHeader/MachineListHeader.tsx

fix: keep acton form open on additional group selection
- go to machine listing
- select group by status
- select a group of machines (e.g. "New")
- open take action form
- select additional group of machines (e.g. "Commissioning")
- ensure the action form remained open
- deselect all groups of machines
- ensure the form has …

fix(machines): keep acton form open on group addition

---

src/app/base/components/VaultNotification/VaultNotification.test.tsx
src/app/base/components/VaultNotification/VaultNotification.tsx

- Vault warning message should no longer display if Vault has not yet started being set up
- Log in to polong as a non-admin user
- Go to /machines
- Verify that there is no vault-related warning message
Fixes: #4562

fix(vault): Hide warning if Vault setup has not started

---

src/app/controllers/views/ControllerDetails/ControllerDetailsHeader/ControllerDetailsHeader.tsx
src/app/controllers/views/ControllerList/ControllerListHeader/ControllerListHeader.tsx
src/app/kvm/components/LXDVMsTable/VMsActionBar/VMsActionBar.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/ReleaseForm/ReleaseForm.tsx
src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.tsx
src/app/machines/views/MachineList/MachineListHeader/MachineListHeader.tsx

- Add machine list action analytics events
- use `useMatch` for machines path matching
- Install the google analytics extension https://chrome.google.com/webstore/detail/jnkmfdileelhofjcijamephohjechhna and enable it by clicking on the icon in the toolbar (make sure it's "ON")
- make sure you have any adblockers disabled so that …

Add machine actions analytics events

---

src/app/base/components/ActionForm/ActionForm.test.tsx
src/app/base/components/ActionForm/ActionForm.tsx
src/app/base/components/FormikFormContent/FormikFormContent.test.tsx
src/app/base/components/node/NodeActionFormWrapper/NodeActionFormWrapper.tsx
src/app/base/components/node/NodeActionWarning/NodeActionWarning.test.tsx
src/app/base/components/node/NodeActionWarning/NodeActionWarning.tsx
src/app/base/components/node/NodeActionWarning/index.ts
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/MachineActionFormWrapper.test.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/MachineActionFormWrapper.tsx
src/app/store/machine/reducers.test.ts
src/app/store/machine/slice.ts

- display error message for no machines 
- update selected machines on delete notify
- extract NodeActionWarning component
- Select all machines
- Open Delete action form via "take action" menu
- Make sure the delete count on the button is correct
- Open machine details for one of the machines in the list in a new tab
- Delete …

feat(machines): display error message for no machines

---

src/app/base/sagas/actions.test.ts
src/app/base/sagas/actions.ts
src/app/domains/views/DomainDetails/ResourceRecords/EditRecordForm/EditRecordForm.test.tsx
src/app/store/domain/slice.ts

- fix: renaming dns record #4556
- go to the DNS page
- create an A record in a domain with name "test"
- edit the entry and rename to "test-new"
- edit the entry and rename to "test" again
- entry should be renamed successfully
Fixes: https://github.com/canonical/maas-ui/issues/4556 …

fix: renaming dns record #4556

---

src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/ReleaseForm/ReleaseForm.test.tsx
src/app/machines/views/MachineDetails/MachineNetwork/AddBridgeForm/AddBridgeForm.test.tsx
src/app/machines/views/MachineDetails/MachineNetwork/AddInterface/AddInterface.test.tsx
src/app/machines/views/MachineDetails/MachineNetwork/EditBridgeForm/EditBridgeForm.test.tsx
src/app/machines/views/MachineList/MachineList.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListTable.test.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListTable.tsx
src/app/store/machine/selectors.test.ts
src/app/store/machine/selectors.ts

- refactor(machines): rename selected state - this removes the previous selected machines implementation
- Verify that machine list page loads and you can select machines
Fixes: #1256 …

refactor(machines): rename selectedMachines state

---

src/app/kvm/components/LXDVMsTable/LXDVMsTable.tsx
src/app/kvm/components/VmResources/VmResources.tsx
src/app/machines/views/MachineList/MachineList.tsx
src/app/store/machine/utils/common.test.ts
src/app/store/machine/utils/common.ts
src/app/store/machine/utils/hooks.ts
src/app/tags/views/TagMachines/TagMachines.tsx

- refactor(machines): move mapSortDirection into hook
- Go to machine listing and ensure that sorting works as before
- Go to KVM page and ensure that sorting works as before
Fixes: https://github.com/canonical/app-tribe/issues/1320 …

refactor(machines): move mapSortDirection into hook

---

src/app/controllers/views/ControllerList/ControllerListTable/ControllerListTable.tsx

- Icons now show next to controllers if they are configured to use Vault but secrets have not been migrated
- Either on your system or in a Multipass instance, ensure you've installed the latest MAAS snap with a test db:
- `sudo snap install maas --channel=latest/edge`
- `sudo snap install maas-test-db --channel=latest/edge`
- Initialise maas and create an admin user
- Install Vault: `sudo snap install vault` and jq: `sudo apt install jq`
- Run Vault: `vault server -dev -dev-root-token-id=root-token`
- In a separate terminal, run …

fix(vault): show icon in controller listing if all controllers are configured but secrets are not migrated

---

src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/OverrideTestForm/OverrideTestForm.test.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/OverrideTestForm/OverrideTestForm.tsx
src/app/store/machine/slice.ts
src/app/store/machine/types/base.ts
src/app/store/types/node.ts

- feat(machines): integrate suppress_failed_script_results action
Note: suppress_failed_script_results will currently fail [has not been yet merged to main in MAAS core](https://code.launchpad.net/~alexsander-souza/maas/+git/maas/+merge/433484) - this is expected
https://warthogs.atlassian.net/browse/WD-604 …

feat(machines): integrate suppress_failed_script_results action

---

src/app/base/sagas/websockets.ts

- log generic websocket errors to the console
- check out this branch locally
- check out the [maas-mock-server](https://github.com/canonical/maas-mock-server) locally and use `https://assets.ubuntu.com/v1/cfc9affb-responses.json` as the `MOCK_PATH` in .env file
- start the mock server
- update MAAS_URL in your .env.local to use …

log generic websocket errors to the console

---

src/app/App.test.tsx
src/app/App.tsx

- Render an error message instead of full page content if an error message for vault is received.
- Follow the setup instructions shown [here](https://docs.google.com/document/d/1ssfthB3g1kzELDaKgKdr4Mzt5n-eLQx11mnotvNbKJM/edit?disco=AAAAktcPosI)
- Migrate all secrets to Vault (instructions at /settings/configuration/security)
- Seal Vault: `vault operator seal`
- Refresh the page
- Ensure that an error message is displayed indicating that there was a Vault request error
- Unseal vault: `vault operator unseal` 
- Refresh the page
- …

feat(vault): render error message instead of content if vault is sealed

---

src/app/App.tsx
src/app/base/components/Section/Section.tsx

- Added a `hideNotifications` prop to the `Section` component which is false by default unless specified
- [Configure Vault fully](https://docs.google.com/document/d/1ssfthB3g1kzELDaKgKdr4Mzt5n-eLQx11mnotvNbKJM/edit?disco=AAAAktcPosI) (including migrating secrets)
- Seal vault: `vault operator seal`
- Ensure that only the "Vault request failed" notification is displayed and no others.

fix(vault): Hide additional notifications if a Vault error is displayed

---

src/app/machines/views/MachineList/MachineListHeader/MachineListHeader.test.tsx
src/app/machines/views/MachineList/MachineListHeader/MachineListHeader.tsx

- fix: incorrect machine count on clear filter 
- fallback to using allMachineCount when there is no active filter
1. Go to machine list page
2. Note the total number of machines in the subheading (`x machines available`)
3. Select a filter that will have some matching machines (e.g. `status:(deployed)`)
4. Note that the total …

fix: incorrect machine count on clear filter after selection #4583

---

src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/OverrideTestForm/OverrideTestForm.tsx
src/app/store/machine/actions.test.ts
src/app/store/machine/slice.ts
src/app/store/machine/types/base.ts
src/app/store/types/node.ts

- fix: machine suppress failed test results
- use `machine.suppress_failed_script_results` instead of `machine.action` method to suppress failed test results
- Select a machine
- Perform "Override failed tests action" having the "Suppress failed scripts" checked
- Make sure the …

fix: machine suppress failed test results

---

src/app/kvm/components/KVMDetailsHeader/KVMDetailsHeader.test.tsx
src/app/kvm/components/KVMHeaderForms/ComposeForm/ComposeForm.tsx
src/app/kvm/views/LXDClusterDetails/LXDClusterHosts/LXDClusterHosts.test.tsx
src/testing/utils.tsx

- test: migrate KVMDetailsHeader to RTL
- add getTestState util function
Fixes: # . …

test: migrate KVMDetailsHeader to RTL

---

src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/OverrideTestForm/OverrideTestForm.test.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/OverrideTestForm/OverrideTestForm.tsx
src/app/store/machine/actions.test.ts
src/app/store/machine/slice.ts
src/app/store/machine/types/actions.ts

- update override failed testing action to match changes in the API
Fixes: https://warthogs.atlassian.net/browse/MAASENG-1141
- Verify the implementation matches the specification as described in the document below:
https://docs.google.com/document/d/1B8CQXRxzapUq8dbSILzCZdrNzU49brVS8K5KQAZeQiw/edit#heading=h.4wbel41znmu5 …

update override failed testing action

---

src/app/store/tag/reducers.test.ts
src/app/store/tag/slice.ts

- fix: outdated tags on selection remove
- Follow steps form the bug attached and make sure you get the expected result
Fixes: #4600
https://warthogs.atlassian.net/browse/MAASENG-1156 …

fix(machines): outdated tags on selection remove

---

src/app/tags/components/NodesTagsLink/NodesTagsLink.tsx

- fix(machines): clicking on tag link does not update machines filter
- Complete steps as described in the linked issue and make sure you get the expected result.
Fixes #4602 
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless the …

fix: clicking on tag link does not update machines filter

---

.github/workflows/playwright.yml
.gitignore
package.json
playwright.config.ts
tests/machines.spec.ts
yarn.lock

- add e2e tests with playwright 
Fixes: # .
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. Please apply backport labels to the PR (e.g. "Backport 2.7") for …

add e2e tests with playwright

---

cypress.config.ts
cypress/constants.ts
cypress/e2e/with-users/analytics.ts
cypress/e2e/with-users/controllers/details.spec.ts
cypress/support/commands.ts

- test google analytics integration
- fix failing tests
- block analytics hosts in e2e tests
Fixes: # .
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. Please …

test: google analytics integration

---

.github/workflows/accessibility.yml
.github/workflows/cypress.yml

- use canonical/setup-maas GitHub action …

ci: use canonical/setup-maas GitHub action

---

.github/workflows/accessibility.yml
.github/workflows/cypress.yml
.github/workflows/playwright.yml
.github/workflows/sitespeed.yml
.github/workflows/test.yml

- update versions to 3.3 (following the release guide in https://github.com/canonical/maas-ui/blob/main/docs/RELEASE.md)
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. …

update versions to 3.3

---

.github/workflows/playwright.yml
playwright.config.ts
tests/machines.spec.ts

- test: websocket requests count on machine search
Fixes: # . …

test: websocket requests count on machine search

---

.github/workflows/upload.yml

- remove sourcemaps from UI build
- this reduces the `maas-ui.tar.gz` bundle size by half (from ~4MB to ~2MB)
Fixes: # .
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless the fix is only applicable for that …

remove sourcemaps from UI build

---

.github/workflows/upload.yml
scripts/upload-assets.py

- use python script for asset upload to workaround issues with [upload-assets](https://github.com/canonical/canonicalwebteam.upload-assets) snap
Fixes: # .
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless the fix …

use python script for asset upload

---

src/app/kvm/components/KVMHeaderForms/DeleteForm/DeleteForm.test.tsx
src/app/kvm/components/KVMHeaderForms/DeleteForm/DeleteForm.tsx

- fix: disabled kvm host delete button
- Go to KVM -> LXD 
- go to one of the hosts from the list
- Go to  KVM host settings (e.g. on bolla: http://bolla.internal:5240/MAAS/r/kvm/lxd/598/edit)
- Scroll down to find the Danger zone section
- Click "Remove this host" 
- Make sure the Remove KVM host button is enabled 
Fixes: …

fix: disabled kvm host delete button

---

src/app/kvm/components/KVMHeaderForms/DeleteForm/DeleteForm.test.tsx
src/app/kvm/components/KVMHeaderForms/DeleteForm/DeleteForm.tsx

- fix: disabled kvm host delete button (3.3 backport)
Fixes: https://github.com/canonical/maas-ui/issues/4643 …

fix: disabled kvm host delete button (#4642) 3.3

---

.github/workflows/upload.yml
scripts/upload-assets.py

- use python script for asset uploading (#4639)
Fixes: # . …

ci: use python script for asset uploading (#4639)

---

src/app/base/components/StatusBar/StatusBar.tsx
src/app/images/components/ImagesTable/ImagesTable.test.tsx
src/app/images/components/ImagesTable/ImagesTable.tsx
src/app/images/components/ImagesTable/_index.scss
src/app/settings/views/Scripts/ScriptsList/ScriptsList.tsx
src/app/store/bootresource/types/base.ts
src/app/utils/formatBytes.test.ts
src/app/utils/formatBytes.ts
src/app/utils/time.test.ts
src/app/utils/time.ts
src/testing/factories/bootresource.ts

- feat: add last deployed images fields
- Check out this PR locally (polong/bolla are unavailable due to disk failures at the moment)
- Go to `/MAAS/r/images`
- Verify that all image tables are displayed correctly
- Verify that sorting by machine count works correctly
- Verify that sorting by last deployed works correctly
- …

feat: add last deployed images fields

---

src/app/machines/views/MachineList/_index.scss

- update machine list focus states
- Hover a machine
- Machine row should have a light blue colour background
- Tab through input fields on a page until one of the inputs within a machine row is selected
- Machine row should have a light blue colour background
Fixes: MAASENG-1228
Related Launchpad maas issue …

feat(machines): update focus states

---

cypress/e2e/with-users/machines/list.spec.ts
src/app/machines/constants.ts
src/app/machines/views/MachineList/MachineList.tsx
src/app/machines/views/MachineList/MachineListControls/HiddenColumnsSelect/HiddenColumnsSelect.test.tsx
src/app/machines/views/MachineList/MachineListControls/HiddenColumnsSelect/HiddenColumnsSelect.tsx
src/app/machines/views/MachineList/MachineListControls/MachineListControls.test.tsx
src/app/machines/views/MachineList/MachineListControls/MachineListControls.tsx
src/app/machines/views/MachineList/_index.scss

- add the ability to hide columns on the machine list page
- Deselect a few columns
- Make sure they're hidden in the machine list table
- Refresh the page
- Selection should be persisted
Fixes: MAASENG-1227
In general, please propose fixes against _main_ …

feat(machines): add hidden columns

---

src/app/base/components/TagSelector/_index.scss

- fix: update tag fields color to match vanilla-framework
- Take action -> Commision
- Verify that Testing scripts field is displayed with  a consistent background colour
In general, please propose fixes against _main_ rather than release branches …

fix: update tag fields color to match vanilla-framework

---

scripts/upload-assets.py

Make the small python script for uploading assets raise errors on non-ok responses from the upload
- Fix scripts/upload-assets
N/A
- Note the upload fails due to being too big :/

fix(upload-assets): fail when upload fails

---

src/scss/_patterns_application.scss

- fix: set visibility to hidden on collapsed side panel
- this fixes accessibility test failure
Fixes: https://github.com/canonical/maas-ui/issues/4677
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless the fix is only applicable …

fix: set visibility to hidden on collapsed side panel

---

src/scss/_patterns_application.scss

- feat: add .l-aside visibility transition (this ensures panel collapse action is animated as well)
- Open take action menu and select an action
- Cancel the action
- Ensure that panel transition functions properly both on open and collapse
In general, …

feat: add .l-aside visibility transition

---

src/app/machines/views/MachineList/MachineListControls/HiddenColumnsSelect/HiddenColumnsSelect.tsx
src/app/machines/views/MachineList/_index.scss

- update machine list settings toggle icon
- Go to machine list and verify the columns toggle has a settings icon
- Check that it works on different screen sizes
Fixes: MAASENG-1230 …

feat(machines): update settings toggle

---

src/app/devices/components/DeviceHeaderForms/AddDeviceForm/AddDeviceForm.test.tsx
src/app/devices/components/DeviceHeaderForms/AddDeviceForm/AddDeviceInterfaces/AddDeviceInterfaces.test.tsx
src/app/devices/components/DeviceHeaderForms/AddDeviceForm/AddDeviceInterfaces/AddDeviceInterfaces.tsx
src/app/devices/views/DeviceList/DeviceListHeader/DeviceListHeader.tsx

- update device form to to fit in the narrow side panel
- Go to devices page
- Click Add device
- Complete the form and add 3 interfaces (with dynamic, static and external IP assignment options)
- Verify the form has been submitted with the correct information via websocket API `device.create` endpoint
Fixes: MAASENG-1251 …

feat: update device form narrow side panel

---

src/app/machines/constants.ts
src/app/machines/views/MachineList/MachineListTable/MachineListTable.test.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListTable.tsx
src/app/machines/views/MachineList/MachineListTable/OwnerColumn/OwnerColumn.test.tsx
src/app/machines/views/MachineList/MachineListTable/OwnerColumn/OwnerColumn.tsx
src/app/store/user/selectors.test.ts
src/app/store/user/selectors.ts

- add full username to machines table
- Make sure you have machines with owners that have a defined full name 
- Click on the "name" next to the owner table header
- Displayed owner usernames in the table should be replaced with full names
Fixes: #1531  …

feat(machines): add full username option to machines table

---

src/app/base/components/DhcpFormFields/MachineSelect/MachineSelectBox/MachineSelectBox.test.tsx
src/app/base/components/DhcpFormFields/MachineSelect/MachineSelectBox/MachineSelectBox.tsx
src/app/base/components/FormikForm/FormikForm.tsx
src/app/base/components/FormikFormButtons/FormikFormButtons.tsx
src/app/base/components/MachineSelectTable/MachineSelectTable.test.tsx
src/app/base/components/MachineSelectTable/MachineSelectTable.tsx
src/app/devices/components/DeviceHeaderForms/AddDeviceForm/AddDeviceInterfaces/AddDeviceInterfaces.test.tsx
src/app/devices/components/DeviceHeaderForms/AddDeviceForm/AddDeviceInterfaces/AddDeviceInterfaces.tsx
src/app/domains/components/RecordFields/RecordFields.tsx
src/app/domains/views/DomainDetails/DomainDetailsHeader/DomainDetailsHeader.tsx
src/app/machines/components/MachineHeaderForms/AddChassis/AddChassisForm/AddChassisForm.tsx
src/app/machines/components/MachineHeaderForms/AddMachine/AddMachineForm/AddMachineForm.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/CloneForm/CloneFormFields/SourceMachineSelect/SourceMachineSelect.test.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/CloneForm/CloneFormFields/SourceMachineSelect/SourceMachineSelect.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/CloneForm/CloneFormFields/SourceMachineSelect/_index.scss

- MAAS new layout QA review fixes
- fix an issue where loading skeleton rows had and cursor pointer and hover style
- update clone from form to display smaller number of items that fits in single page view
- display skeleton rows in a number equal to selected pageSize
- Open Clone from form and verify it's displayed correctly …

MAAS new layout QA review fixes

---

src/app/subnets/views/VLANDetails/ConfigureDHCP/ConfigureDHCP.tsx
src/app/subnets/views/VLANDetails/ConfigureDHCP/ConfigureDHCPFields/ConfigureDHCPFields.tsx

- Made "Rack controller" field required in DHCP form
- Added error message for DHCP configuration if "Provide DHCP from rack controller(s)" is selected but no controller is selected
- Navigate to `/MAAS/r/networks?by=fabric&q=` (or click "Subnets" in the nav)
- Click on a VLAN
- Click "Configure DHCP"
- Ensure an asterisk is …

fix(subnet): Visible error message when rack controller is not selected for DHCP MAASENG-1256

---

src/app/base/components/NodeActionMenu/NodeActionMenu.test.tsx
src/app/base/components/NodeActionMenu/NodeActionMenu.tsx
src/app/base/components/NodeActionMenuGroup/NodeActionMenuGroup.test.tsx
src/app/base/components/NodeActionMenuGroup/NodeActionMenuGroup.tsx
src/app/base/components/NodeActionMenuGroup/index.scss
src/app/base/components/NodeActionMenuGroup/index.ts
src/app/base/components/SectionHeader/SectionHeader.tsx
src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.test.tsx
src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.tsx
src/app/machines/views/MachineDetails/MachineHeader/index.scss
src/scss/_settings.scss
src/scss/index.scss

- Added group of contextual menus and buttons to replace "Take action" dropdown
- Implemented on machine details
- Hide group and replace with "Menu dropdown" on smaller screens
- Go to the details page for a machine
- Ensure the action group renders correctly
- Click on each available action
- Ensure it opens the correct form
- …

feat: Node action button group on MachineDetails MAASENG-1223

---

cypress/e2e/with-users/machines/actions.spec.ts
cypress/e2e/with-users/machines/list.spec.ts
src/app/base/components/MainContentSection/MainContentSection.test.tsx
src/app/base/components/MainContentSection/MainContentSection.tsx

- test: fix failing cypress tests
- replace header within main section with a div (this will need to be updated again once we complete maas new layout work and have the new navigation as this will affect semantic structure of the document)
Fixes: https://github.com/canonical/maas-ui/issues/4665
Related Launchpad …

test: fix cypress failed

---

src/app/images/components/ImagesTable/ImagesTable.test.tsx
src/app/images/components/ImagesTable/ImagesTable.tsx
src/app/store/bootresource/types/base.ts
src/testing/factories/bootresource.ts

- feat(images): update machineCount field
- this aligns the UI with a back-end change: https://code.launchpad.net/~lloydwaltersj/maas/+git/maas/+merge/436064
- Go to images page
- Make sure the page renders and no errors are thrown
Fixes: MAASENG-1264 …

feat(images): update machineCount field

---

docs/MAASUI.md

- Migrated MAAS UI onboarding to `docs`
Fixes: # .
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. Please apply backport labels to the PR (e.g. "Backport …

Doc: Added MAAS UI onboarding documentation

---

src/app/machines/views/MachineList/MachineList.test.tsx
src/app/machines/views/MachineList/MachineList.tsx

- feat: allow custom machine list page size
This is required for https://github.com/canonical/maas-ui/pull/4705
Note: This is not exposed anywhere in the UI (at least not yet).
- Open developer tools
- paste `localStorage.setItem("machineListPageSize", 10)` to the console and execute
- refresh the page
- you …

feat: allow custom machine list page size

---

src/app/settings/views/Security/SessionTimeout/SessionTimeout.tsx

- Allowed minutes as a time unit option for session timeout
- Navigate to `/settings/security/session-timeout`
- Enter a timeout length in minutes, e.g `12 minutes`
- Click "Save"
- Ensure the form saves without errors
- Refresh the page
- Ensure the value persists
- Enter a timeout length using a combination of units including …

feat: Allow minutes as a time unit for session timeout

---

src/app/kvm/components/VmResources/VmResources.tsx
src/app/machines/views/MachineList/MachineList.tsx
src/app/machines/views/MachineList/MachineListTable/GroupCheckbox/GroupCheckbox.test.tsx
src/app/machines/views/MachineList/MachineListTable/GroupCheckbox/GroupCheckbox.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListTable.test.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListTable.tsx
src/app/store/machine/selectors.ts
src/app/store/machine/slice.ts
src/app/store/machine/types/base.ts
src/app/store/machine/utils/common.ts
src/app/store/machine/utils/hooks.test.tsx
src/app/store/machine/utils/hooks.ts
src/app/tags/views/TagMachines/TagMachines.tsx
src/testing/factories/state.ts

- fix: update machine list grouping for active page of results
- expose groups directly from machine fetch hook
- Select a machine and perform an action that will affect it's grouping (e.g. with grouping by status test/abort, grouping by pool set a different pool)
- Ensure the list is updated and it's moved …

fix: machine list grouping #4709

---

src/app/kvm/components/VmResources/VmResources.tsx
src/app/machines/views/MachineList/MachineList.tsx
src/app/machines/views/MachineList/MachineListTable/GroupCheckbox/GroupCheckbox.test.tsx
src/app/machines/views/MachineList/MachineListTable/GroupCheckbox/GroupCheckbox.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListTable.test.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListTable.tsx
src/app/store/machine/selectors.ts
src/app/store/machine/slice.ts
src/app/store/machine/types/base.ts
src/app/store/machine/utils/common.ts
src/app/store/machine/utils/hooks.test.tsx
src/app/store/machine/utils/hooks.ts
src/app/tags/views/TagMachines/TagMachines.tsx
src/testing/factories/state.ts

- fix: machine list grouping (#4710)
backport of https://github.com/canonical/maas-ui/pull/4710
- check out this branch locally
- run `yarn clean`
- run `yarn && yarn start`
- Follow QA steps from https://github.com/canonical/maas-ui/pull/4710
Fixes: #4710 …

fix: machine list grouping (#4710)

---

src/scss/_vanilla-overrides.scss

- fix: contextual menu hidden behind side panel
_temporary workaround for until a bug in vanilla gets fixed_
- Go to KVM -> KVM Host
- Without scrolling further down the page, select a VM from the list and click "Take action"
Fixes: https://github.com/canonical/maas-ui/issues/4702 …

fix: contextual menu hidden

---

package.json
src/app/images/components/ImagesTable/ImagesTable.test.tsx
src/app/images/components/ImagesTable/ImagesTable.tsx
src/app/utils/time.test.ts
src/app/utils/time.ts
yarn.lock

- feat: show image last sync time
- update lastDeployed secondary row time offset
- Go to MAAS/r/images
- Add a new image (e.g. CentOS 7)
- Update selection
- Wait for the image to sync
- Change your system's time zone to GMT+1
- Make sure the last sync time is still displaying the correct time - indicating the last sync …

feat: show image last sync time #1166

---

cypress/e2e/with-users/machines/actions.spec.ts
src/app/base/components/node/SetZoneForm/SetZoneForm.tsx
src/app/base/hooks/node.ts
src/app/base/sagas/actions.test.ts
src/app/base/sagas/actions.ts
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/SetPoolForm/SetPoolForm.tsx
src/app/store/machine/slice.ts
src/app/store/machine/types/actions.ts
src/app/store/machine/utils/hooks.ts
src/app/store/resourcepool/types/actions.ts
src/app/utils/kebabToCamelCase.ts

- Backport of https://github.com/canonical/maas-ui/pull/4719
- No steps required …

fix: set pool with machine filter - 3.3 backport (#4719)

---

src/app/settings/views/Security/SecurityProtocols/TLSDisabled/TLSDisabled.tsx

- Added `sudo` to config-tls command to specify root permissions
- Visit MAAS site locally
- Navigate to `/settings/security/security-protocols`
Fixes: # .
[https://github.com/canonical/maas-ui/issues/4533](https://github.com/canonical/maas-ui/issues/4533) …

fix: add `sudo` to config command to enable root permissions

---

src/app/machines/views/MachineList/MachineList.test.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListTable.tsx

- fix: collapsing multi-word machine groups (e.g. failed commissioning)
- Select a machine
- Take action -> enter rescue mode
- group by status
- collapse entering rescue mode group
- machine list should be displayed correctly with no errors
Fixes: https://github.com/canonical/maas-ui/issues/4730
Related …

fix: collapsing multi-word machine groups #4730

---

cypress/e2e/with-users/machines/actions.spec.ts
cypress/e2e/with-users/machines/list.spec.ts
cypress/e2e/with-users/pools/list.spec.ts
cypress/e2e/with-users/settings/dhcp.spec.ts
cypress/support/commands.ts
cypress/support/e2e.ts

- test: fix cypress pools test
- add `deleteMachine` `deletePool` cypress util functions to help clean up after each test
Fixes: # .
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless the fix is only applicable for …

test: fix cypress pools test

---

src/app/base/components/AppSideNavigation/AppSideNavItem/AppSideNavItem.tsx
src/app/base/components/AppSideNavigation/AppSideNavItem/index.ts
src/app/base/components/AppSideNavigation/AppSideNavItems/AppSideNavItems.tsx
src/app/base/components/AppSideNavigation/AppSideNavItems/index.ts
src/app/base/components/AppSideNavigation/AppSideNavigation.test.tsx
src/app/base/components/AppSideNavigation/AppSideNavigation.tsx
src/app/base/components/AppSideNavigation/_index.scss

- Create AppSideNavItem
- Create AppSideNavItems
- Add useId for component IDs (used in aria-labelledby)
- Fix keys on nav item mapping
- Swap the contextual menu for discrete buttons for preferences and logging out
- Check that the nav renders normally
- Ensure clicking on your username directs you to preferences
- Click the …

fix(nav): Break out nav items into separate components and add discrete logout button MAASENG-1314

---

cypress/e2e/with-users/base/header.spec.ts
src/app/base/components/AppSideNavigation/AppSideNavigation.tsx
src/app/base/components/AppSideNavigation/NavigationBanner/NavigationBanner.tsx
src/app/base/components/AppSideNavigation/_index.scss

- fix: navigation toggle buttons
- use semantic button elements for buttons
- fix close button position
- fix `<hr />` element overflow
- bring back transform transition (was overwritten by `@include vf-animation("background-color");`)
- add cypress test for opening and closing the mobile navigation
- Open developer tools
- …

fix: navigation toggle buttons

---

src/app/settings/views/Scripts/ScriptDetails/ScriptDetails.test.tsx
src/app/settings/views/Scripts/ScriptDetails/ScriptDetails.tsx
src/app/settings/views/Scripts/ScriptDetails/_index.scss
src/app/settings/views/Scripts/ScriptsList/ScriptsList.tsx
src/scss/index.scss

- Added an optional collapse button to the commissioning scripts to hide the scripts
- Navigate to `/MAAS/r/settings/scripts/commissioning`
- Click on a script name to expand the script, you should notice a button at the bottom-right corner  of the script that reads `Close snippet`
Fixes #878
Fixes …

Fix: 1316 build button to collapse scripts

---

src/app/Routes.test.tsx
src/app/kvm/views/KVMList/KVMList.tsx
src/app/kvm/views/KVMList/KVMListHeader/KVMListHeader.test.tsx
src/app/kvm/views/KVMList/KVMListHeader/KVMListHeader.tsx

- Removed duplicated tab navigation items on KVM pages
- Updated KVM header to display "LXD" or "Virsh" instead of "KVM"
- Navigate to `/kvm/lxd`
- Ensure the title is "LXD" (window and page header)
- Ensure the old tab links are not rendered
- Navigate to `/kvm/virsh`
- Ensure the title is "Virsh" (window and page header)
- …

fix(MAASENG-1313): Remove duplicated tab navigation items

---

src/app/kvm/components/KVMDetailsHeader/KVMDetailsHeader.tsx

- Increased width of KVM details side panel forms to ensure storage pool table fits properly
- Click "LXD" in the nav
- Click on a host
- Scroll down and click "Add VM"
- Click "Add disk"
- Click the "Location" dropdown"
- Ensure the table headers do not wrap 
Fixes https://warthogs.atlassian.net/jira/software/c/projects/MAASENG/ …

fix(KVM): Increase width of KVM details side panel forms

---

src/app/base/components/AppSideNavigation/AppSideNavigation.tsx
src/app/base/components/AppSideNavigation/_index.scss
src/scss/_patterns_icons.scss

- Moved "Hardware" group to the top
- Split ungrouped items into "Organisation" and "Configuration"
- Added icons for new groups
- Added margin beneath nav banner
**Note: Conditionally displaying "Virsh" will be done in a follow-up PR https://warthogs.atlassian.net/jira/software/c/projects/MAASENG/boards/302?modal=detail&selectedIssue=MAASENG-1334** …

feat(nav): Re-order and re-group items in side navigation MAASENG-1333

---

src/app/base/components/AppSideNavigation/AppSideNavItems/AppSideNavItems.tsx
src/app/base/components/AppSideNavigation/AppSideNavigation.tsx
src/scss/_patterns_icons.scss
src/scss/index.scss

- Removed unnecessary icon classes for light versions of icons
- Added base icon imports to base SCSS file
- Ensure side nav icons load correctly
Fixes [MAASENG-1342](https://warthogs.atlassian.net/browse/MAASENG-1342)
[MAASENG-1342]: https://warthogs.atlassian.net/browse/MAASENG-1342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU …

chore(styles): Clean up icon patterns MAASENG-1342

---

cypress/e2e/with-users/machines/list.spec.ts
cypress/e2e/with-users/pools/list.spec.ts
src/app/base/components/node/MachinesHeader/MachinesHeader.test.tsx
src/app/base/components/node/MachinesHeader/MachinesHeader.tsx
src/app/machines/views/MachineList/MachineListHeader/MachineListHeader.test.tsx
src/app/machines/views/MachineList/MachineListHeader/MachineListHeader.tsx
src/app/pools/views/Pools.tsx
src/app/tags/components/TagsHeader/TagsHeader.test.tsx
src/app/tags/components/TagsHeader/TagsHeader.tsx

- Added machine/pool count in header title for machine list and pool list
- Removed tab navigation from machine list, pool list, and tag list.
- Ensure the number of machines/pools is displayed correctly in the machine list header
- Click on the link "(number) pools"
- Ensure you are navigated to the Pools …

feat: Add machine and pool count to header and remove tab nav MAASENG-1341

---

src/app/base/components/FormikFormButtons/_index.scss

- Stacked form buttons on smaller screens (< 1036px).
- Navigate to `/MAAS/r/devices`
- Click the `Add Device` button
- Examine the form buttons at the base on different screen sizes
Fixes: # .
closes #3334 
[https://warthogs.atlassian.net/browse/MAASENG-1332](https://warthogs.atlassian.net/browse/MAASENG-1332)
Related Launchpad …

Fix: MAASENG-1332 - stack form buttons on smaller screens

---

src/app/base/components/AppSideNavigation/AppSideNavigation.tsx
src/scss/_patterns_status-bar.scss
src/scss/index.scss

- update status bar style according to latest design
- hide MAAS info in the side bar
- display MAAS info in the status bar
Note: the footer that contains the status bar it extends to full width in the design but we're following the existing vanilla implementation for application layout here where it only takes the width of the main area).
Once we have a better idea of what should go in the footer we'll update: https://warthogs.atlassian.net/browse/MAASENG-1358
- Serving with …

feat: update status bar MAASENG-1340

---

cypress/e2e/with-users/machines/list.spec.ts
src/app/machines/views/MachineList/MachineListTable/MachineListDisplayCount/MachineListDisplayCount.test.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListDisplayCount/MachineListDisplayCount.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListDisplayCount/index.ts
src/app/machines/views/MachineList/MachineListTable/MachineListTable.tsx

- Add text showing machines shown on page out of total filtered machines
- Move pagination controls to top of page
- Add Cypress E2E test for showing correct filtered machine counts
- Ensure the "out of" number of machines is the same as the total at the top
- Ensure the "Showing" number of machines is …

feat(machines): Show filtered machine count and machines on page count MAASENG-1367 & MAASENG-1368

---

src/app/base/components/AppSideNavigation/AppSideNavItems/AppSideNavItems.tsx
src/app/base/components/AppSideNavigation/AppSideNavigation.test.tsx
src/app/base/components/AppSideNavigation/AppSideNavigation.tsx

- Hide "Virsh" in nav if user has no virsh kvms
- Ensure you have mock data with Virsh KVM hosts
- Go to the UI
- Ensure the Virsh tab is shown in the nav and you can click it
- If you have multipass or LXD, set up a new instance with a clean install of the maas snap (no mock data)
- Go to the UI (and skip through the intro)
- …

feat(nav): Only display "Virsh" if user has Virsh KVM hosts MAASENG-1334

---

src/app/base/components/AppSideNavigation/AppSideNavCollapseToggle/AppSideNavCollapseToggle.tsx
src/app/base/components/AppSideNavigation/AppSideNavigation.test.tsx
src/app/base/components/AppSideNavigation/AppSideNavigation.tsx
src/app/base/components/AppSideNavigation/_index.scss
src/scss/_settings.scss

- set grid max width to 1920px
- adjust sidenav toggle button position
- remove additional toggle button that was rendered outside of the nav
- persist collapsed state using localstorage
- Verify that the button is within the side nav when collapsed
- Verify that the side nav works as expected across all breakpoints
- Click the …

feat: update grid max width and adjust sidenav

---

cypress/e2e/with-users/base/navigation.spec.ts
cypress/e2e/with-users/controllers/list.spec.ts
cypress/e2e/with-users/devices/list.spec.ts
cypress/e2e/with-users/domains/list.spec.ts
cypress/e2e/with-users/images/list.spec.ts
cypress/e2e/with-users/kvm/list.spec.ts
cypress/e2e/with-users/machines/list.spec.ts
cypress/e2e/with-users/preferences/base.spec.ts
cypress/e2e/with-users/settings/base.spec.ts
cypress/e2e/with-users/settings/configuration/general.spec.ts
cypress/e2e/with-users/subnets/subnets.spec.ts
cypress/e2e/with-users/zones/list.spec.ts

- fix cypress tests related to navigation
- move navigation related assertions to `navigation.spec.ts`
Fixes: https://github.com/canonical/maas-ui/issues/4748
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless the …

test: update navigation cypress tests

---

.github/workflows/test.yml

- ci: remove redundant build job
We already test the build using run-dotrun: https://github.com/petermakowski/maas-ui/blob/103a2bd11db37070e97002603b7ae838a9f53ec3/.github/workflows/test.yml#L56
Fixes: # .
In general, please propose fixes against _main_ rather …

ci: remove redundant build job

---

.github/ISSUE_TEMPLATE/upload-failure.md
.github/workflows/upload.yml

- ci: use dotrun for build upload
- fix upload failure issue link
Fixes: https://github.com/canonical/maas-ui/issues/4781
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless the fix is only applicable for that …

ci: use dotrun for build upload

---

src/app/machines/views/MachineList/MachineList.test.tsx
src/app/machines/views/MachineList/MachineList.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListDisplayCount/MachineListDisplayCount.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListDisplayCount/_index.scss
src/app/machines/views/MachineList/MachineListTable/MachineListPagination/MachineListPagination.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListPagination/_index.scss
src/app/machines/views/MachineList/MachineListTable/MachineListTable.tsx
src/app/machines/views/MachineList/MachineListTable/PageSizeSelect/PageSizeSelect.test.tsx
src/app/machines/views/MachineList/MachineListTable/PageSizeSelect/PageSizeSelect.tsx
src/app/machines/views/MachineList/MachineListTable/PageSizeSelect/index.ts
src/scss/_utilities.scss
src/scss/index.scss

- Updated machine list pagination component to allow input for page number
- Added select for page size
- Go to machine list (ensure you have at least 100 machines)
- Ensure only 50 machines per page are displayed by default
- Click on the page counter and type a number between 1 and your page count (inclusive)
- Ensure the page …

feat(machines): New pagination and page size dropdown MAASENG-1369

---

src/app/settings/views/Configuration/GeneralForm/GeneralForm.tsx

- Updated MAAS name emoji examples in configuration to not be misleading
- Go to `/settings/configuration/general`
- Ensure emotes match the "after" screenshot below
Fixes #4785 
Will be backported to 3.3 once merged

fix(settings): Update MAAS name example emotes to not be misleading #4785

---

src/app/machines/views/MachineList/MachineListTable/MachineListPagination/MachineListPagination.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListTable.tsx
src/app/machines/views/MachineList/MachineListTable/PageSizeSelect/PageSizeSelect.test.tsx
src/app/machines/views/MachineList/MachineListTable/PageSizeSelect/PageSizeSelect.tsx

- Page is set to `1` if page size is changed
- Go to machine list (at least 100 machines in db)
- Set page size to 50
- Go to second page
- Set page size to 100
- Ensure you are returned to the first page
Fixes #4787

fix(machines): Reset current page to first page on change of page size #4787

---

src/app/machines/hooks.tsx
src/app/machines/types.ts
src/app/machines/views/MachineList/MachineListTable/MachineListTable.tsx
src/app/machines/views/MachineList/MachineListTable/OwnerColumn/OwnerColumn.tsx
src/app/machines/views/MachineList/MachineListTable/PoolColumn/PoolColumn.tsx
src/app/machines/views/MachineList/MachineListTable/PowerColumn/PowerColumn.tsx
src/app/machines/views/MachineList/MachineListTable/StatusColumn/StatusColumn.tsx
src/app/machines/views/MachineList/MachineListTable/ZoneColumn/ZoneColumn.tsx

- refactor(machines): remove active row state
(it was used to determine whether to apply an active row classname which is no longer used)
- perform an inline action on any of the listed machines
- verify the action has been performed correctly
- select a machine
- open bulk action menu (Take action)
- …

refactor(machines): remove active row state

---

src/app/base/hooks/node.ts

- refactor: replace machineActions Object entries method lookup with property accessor (TS Object.entries has weak typing by default for Object keys and uses a generic string)
- fixes maas upload failed #4807
Fixes: #4807
In general, please propose fixes against _main_ rather …

refactor(machines): use machineActions property accessor

---

cypress/e2e/with-users/base/navigation.spec.ts
cypress/e2e/with-users/kvm/list.spec.ts
cypress/e2e/with-users/login/login.spec.ts
cypress/e2e/with-users/machines/actions.spec.ts
cypress/e2e/with-users/machines/list.spec.ts
cypress/e2e/with-users/pools/list.spec.ts
cypress/e2e/with-users/settings/configuration/general.spec.ts
cypress/e2e/with-users/settings/dhcp.spec.ts
cypress/support/commands.ts
cypress/support/e2e.ts

- test: update cypress tests #4779
- this fixes 11 out of 12 failing tests, most failures were related to MAAS New layout, fix for the dhcp form will come in a separate PR
Fixes: #4779 …

test: update cypress tests #4779

---

src/app/base/components/node/DiskTestStatus/DiskTestStatus.test.tsx
src/app/base/components/node/DiskTestStatus/DiskTestStatus.tsx
src/app/base/components/node/NodeActionFormWrapper/NodeActionFormWrapper.test.tsx
src/app/base/components/node/networking/NameColumn/NameColumn.test.tsx
src/app/kvm/components/LXDHostToolbar/LXDHostToolbar.test.tsx
src/app/kvm/views/VirshDetails/VirshSettings/VirshSettings.test.tsx

- test: migrate DiskTestStatus, NameColumn to RTL
- add accessible labels to icons
Fixes: # . …

test: migrate DiskTestStatus, NameColumn, NodeActionFormWrapper, VirshSettings, LXDHostToolbar to RTL

---

cypress/e2e/with-users/login/login.spec.ts
src/app/App.tsx
src/app/base/components/Login/Login.tsx
src/app/utils/formatErrors.ts

- refactor: login errors mapping MAASENG-1489
- reduce number of components and simplify logic
- use formatErrors function to display errors
- add e2e test for invalid credentials on login
- update formatErrors types
- Ensure you can login and an error is still displayed when you enter invalid credentials.
Fixes: MAASENG-1489 …

refactor: login errors mapping MAASENG-1489

---

src/app/machines/views/MachineList/MachineListControls/MachinesFilterAccordion/MachinesFilterAccordion.test.tsx
src/app/machines/views/MachineList/MachineListControls/MachinesFilterAccordion/MachinesFilterAccordion.tsx

- fix: check filter groups loaded 
- Verify that filter groups are loaded correctly
Fixes: MAASENG-1522
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. …

fix: check filter groups loaded MAASENG-1522

---

.github/workflows/cypress.yml
.github/workflows/links-checker.yml
src/app/base/docsUrls.ts

- Move docs checker to separate workflow
- set to run on cron schedule  `0 14 * * 1-5` (At 14:00 every day-of-week from Monday through Friday)
- docs links tests are most often broken by changes to the docs themselves rather than any specific change to the maas-ui codebase therefore it makes sense for them to be run periodically …

ci: move docs checker to separate workflow

---

src/app/machines/views/MachineList/MachineListTable/MachineListPagination/MachineListPagination.test.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListPagination/MachineListPagination.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListPagination/_index.scss
src/app/machines/views/MachineList/MachineListTable/MachineListTable.tsx
src/app/machines/views/MachineList/_index.scss

- Error messages are displayed for invalid values
- Error messages are cleared on blur and value is reset to current page
- Adjusted styling of error message (approved by @amylily1011)
**Make sure you have enough machines (and a small enough page size) to need multiple pages.**
1. Go to machine list
2. Change the page number to …

fix(MachineList): Update pagination behaviour MAASENG-1490

---

src/app/store/machine/utils/hooks.test.tsx
src/app/store/machine/utils/hooks.ts

- fix: machine list flutter 
- select multiple machine groups: new, ready, failed testing on a single page
- select troubleshoot -> test
- wait for the machine list update
- select actions -> abort
- wait for the machine list update
- verify there is a smooth transition between machine states
lp#2013476 …

fix: machine list flutter

---

src/app/store/machine/utils/hooks.test.tsx
src/app/store/machine/utils/hooks.ts

- fix: machine list flutter #2013476 (#4857)
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. Please apply backport labels to the PR (e.g. "Backport 2.7") for the appropriate …

fix: machine list flutter #2013476 (#4857)

---

.github/workflows/upload.yml
scripts/upload-assets.py

- ci: fix main build upload failed #4853
- use python script for asset uploading
This fixes upload failure due to error in upload-assets snap https://snapcraft.io/upload-assets - more on this in the linked issue #4853
Fixes: #4853 …

ci: fix main build upload failed #4853

---

cypress/e2e/with-users/machines/actions.spec.ts
cypress/e2e/with-users/machines/list.spec.ts
cypress/support/commands.ts

- test: fix main Cypress run failed #4856
Fixes: #4856 …

test: fix main Cypress run failed #4856

---

.github/workflows/upload.yml
scripts/upload-assets.py

- Make the home-grown upload-assets script a bit more reliable see #4853 
N/A
N/A
- Run the action, watch it fail
N/A

fix: upload-assets should check the response status

---

src/app/machines/views/MachineList/MachineListTable/MachineListPagination/_index.scss
src/app/machines/views/MachineList/MachineListTable/MachineListTable.tsx
src/app/machines/views/MachineList/_index.scss

- update machine list pagination spacing to match designs
- verify it's displayed with the correct margin in the pagination section across all breakpoints
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless the …

fix: update machine list pagination spacing

---

src/app/kvm/components/KVMResourceMeter/KVMResourceMeter.tsx
src/app/store/pod/utils.ts

- Round off values of free and total CPU cores to (at most) 2 decimal places
- register LXD VM host
- set an overcommit ratio with a fractional value to have a factional value for available CPU cores
- goto /MAAS/r/kvm/lxd
- Hover over the CPU cores for that host and ensure the values are at most 2 decimal places
Fixes: # . …

round off values to 2 decimal places at most

---

src/app/base/components/SecondaryNavigation/SecondaryNavigation.tsx

- Added missing data-testid to secondary navigation title to fix failing a11y cypress test
Fixes #4877

fix: Add missing data-testid to secondary nav title #4877

---

src/app/machines/views/MachineDetails/MachineTests/MachineTests.test.tsx
src/app/machines/views/MachineDetails/MachineTests/MachineTests.tsx

- fix: tests tab not updating scripresults on mount
- refactor `MachineTests.test.tsx` to RTL
- Go to machine details page
- Go to Network tab
- Click "Validate network configuration" and submit the form
- Go to the Tests tab
- Verify that new tests are displayed
Fixes: https://bugs.launchpad.net/maas-ui/+bug/2017977
Related …

fix: tests tab not updating scripresults on mount

---

.github/workflows/playwright.yml

- ci: run playwright tests only after merge
- `playwright` tests are currently running against [full latest MAAS from snap](https://github.com/canonical/maas-ui/blob/main/.github/workflows/playwright.yml#L23).
- For that reason it doesn't make sense for it to be run on pull requests until we [make it build MAAS UI from a latest commit](https://warthogs.atlassian.net/browse/MAASENG-1605) …

ci: run playwright tests only on main

---

.github/workflows/cypress.yml
.github/workflows/playwright.yml
.github/workflows/test.yml
docs/RELEASE.md

prepare 3.4 release
- update github actions to use 3.4
- update RELEASE.md …

prepare 3.4 release

---

src/app/base/components/node/ActionConfirm/ActionConfirm.test.tsx
src/app/base/components/node/DeleteForm/DeleteForm.test.tsx
src/app/base/components/node/DiskBootStatus/DiskBootStatus.test.tsx
src/app/base/components/node/DiskBootStatus/DiskBootStatus.tsx
src/app/base/components/node/FieldlessForm/FieldlessForm.test.tsx
src/testing/utils.tsx

- src/app/base/components/node/ActionConfirm
- src/app/base/components/node/DeleteForm
- src/app/base/components/node/DiskBootStatus
- src/app/base/components/node/FieldlessForm

test: Migrate four base components to RTL

---

src/app/base/components/node/StorageTables/AvailableStorageTable/BulkActions/CreateRaid/CreateRaidFields/CreateRaidFields.test.tsx
src/app/base/components/node/StorageTables/AvailableStorageTable/BulkActions/CreateRaid/CreateRaidFields/CreateRaidFields.tsx

- migrate CreteRaidFields to RTL MAASENG-1626
Fixes: MAASENG-1626 …

migrate CreteRaidFields to RTL MAASENG-1626

---

src/app/machines/views/MachineList/MachineListHeader/MachineListHeader.test.tsx

- migrate MachineListHeader test to RTL
Fixes: https://warthogs.atlassian.net/browse/MAASENG-1617
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. Please apply backport labels …

migrate MachineListHeader test to RTL

---

src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTableActions/NetworkTableActions.test.tsx

- Migrated src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTableActions/NetworkTableActions.test.tsx to RTL
Fixes [MAASENG-1619](https://warthogs.atlassian.net/browse/MAASENG-1619)
[MAASENG-1619]: https://warthogs.atlassian.net/browse/MAASENG-1619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: Migrate NetworkTableActions.test to RTL MAASENG-1619

---

src/app/machines/views/MachineDetails/MachineNetwork/AddAliasOrVlan/AddAliasOrVlanFields/AddAliasOrVlanFields.tsx
src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTableConfirmation/NetworkTableConfirmation.test.tsx
src/testing/utils.tsx

- Migrated src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTableConfirmation/NetworkTableConfirmation.test.tsx to RTL
Fixes [MAASENG-1618](https://warthogs.atlassian.net/browse/MAASENG-1618)
[MAASENG-1618]: https://warthogs.atlassian.net/browse/MAASENG-1618?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: Migrate NetworkTableConfirmation.test to RTL MAASENG-1618

---

src/app/machines/views/MachineDetails/MachineNetwork/MachineNetworkActions/MachineNetworkActions.test.tsx

- Migrated MachineNetworkActions tests to RTL
- `yarn test src/app/machines/views/MachineDetails/MachineNetwork/MachineNetworkActions/MachineNetworkActions.test.tsx`
Fixes: # .
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless the …

migrate machineNetworkActions tests to RTL

---

src/app/base/components/PowerIcon/PowerIcon.tsx
src/app/kvm/components/LXDVMsTable/VMsTable/StatusColumn/StatusColumn.test.tsx
src/app/machines/views/MachineList/MachineListTable/PowerColumn/__snapshots__/PowerColumn.test.tsx.snap

- migrate StatusColumn test to RTL MAASENG-1708
Fixes: https://warthogs.atlassian.net/browse/MAASENG-1708 …

migrate StatusColumn test to RTL MAASENG-1708

---

src/app/machines/views/MachineDetails/MachineInstances/MachineInstances.test.tsx
src/app/machines/views/MachineDetails/MachineInstances/MachineInstances.tsx

- Refactored Machine Instances tests to RTL
- run `yarn test src/app/machines/views/MachineDetails/MachineInstances/MachineInstances.test.tsx`
Fixes: # .
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless the fix is only applicable …

1707 refactor machine instances test rtl

---

src/app/base/components/NodeActionMenuGroup/NodeActionMenuGroup.tsx
src/app/machines/views/MachineList/MachineList.test.tsx
src/app/machines/views/Machines.test.tsx

- test: fix long-running tests MAASENG-1712
- remove leftover comment
Fixes: # .
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. Please apply backport labels …

test: fix long-running tests MAASENG-1712

---

.eslintrc.js
package.json
yarn.lock

- add eslint-plugin-unused-imports
This will automatically remove unused imports on save or when running eslint with `--fix`
- Checkout this branch locally
- Go to `App.tsx`
- Add `import { actions } from "app/store/user";` at the top of the file
- If you have autofix enabled on save in your code editor:
- save the file and the …

test: add eslint-plugin-unused-imports

---

src/app/kvm/components/StorageResources/StorageResources.tsx
src/app/kvm/views/LXDClusterDetails/LXDClusterSummaryCard/LXDClusterSummaryCard.test.tsx
src/app/kvm/views/LXDClusterDetails/LXDClusterSummaryCard/LXDClusterSummaryCard.tsx
src/app/kvm/views/LXDSingleDetails/LXDSingleSettings/AuthenticationCard/AuthenticationCard.test.tsx
src/app/kvm/views/LXDSingleDetails/LXDSingleSettings/AuthenticationCard/UpdateCertificate/UpdateCertificate.tsx

- test: migrate kvm tests to RTL MAASENG-1742
Fixes: https://warthogs.atlassian.net/browse/MAASENG-1742 …

test: migrate kvm tests to RTL MAASENG-1742

---

src/app/base/components/AppSideNavigation/AppSideNavigation.test.tsx
src/app/base/components/DhcpFormFields/DhcpFormFields.test.tsx
src/app/base/components/SegmentedControl/SegmentedControl.test.tsx
src/app/base/components/TableActionsDropdown/TableActionsDropdown.test.tsx
src/app/base/components/TableHeader/TableHeader.test.tsx
src/app/base/components/TableHeader/TableHeader.tsx
src/app/base/components/node/networking/NetworkTable/NetworkTable.test.tsx
src/app/controllers/views/ControllerList/ControllerListTable/ControllerListTable.test.tsx
src/app/devices/views/DeviceList/DeviceListHeader/DeviceListHeader.test.tsx
src/app/devices/views/DeviceList/DeviceListTable/DeviceListTable.test.tsx
src/app/kvm/views/KVMList/KVMList.test.tsx
src/app/kvm/views/KVMList/KVMListHeader/KVMListHeader.test.tsx
src/app/kvm/views/KVMList/LxdTable/LxdKVMHostTable/LxdKVMHostTable.test.tsx
src/app/kvm/views/KVMList/VirshTable/VirshTable.test.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/CloneForm/CloneResults/CloneResults.test.tsx
src/app/subnets/views/SubnetDetails/SubnetDetailsHeader/SubnetActionForms/components/DeleteSubnet/DeleteSubnet.test.tsx
src/app/tags/views/TagList/TagListControls/TagListControls.test.tsx
src/app/tags/views/TagList/TagTable/TagTable.test.tsx

- migrate 3 kvm tests to RTL MAASENG-1738
- replace `.click()` calls with `userEvent.click()`
- add aria-label to table header sort direction indicator
Fixes: https://warthogs.atlassian.net/browse/MAASENG-1738
In general, please propose fixes against _main_ rather than …

migrate 3 kvm tests to RTL MAASENG-1738

---

src/app/App.tsx
src/app/base/components/SecondaryNavigation/_index.scss
src/scss/_patterns_application.scss

- fix: sidebar height lp#2021965
Using Firefox and Chrome:
- Change the window size to approx `1100px x550px`
- Login
- Go to settings
- Verify the settings navigation menu is displayed in full and not clipped and navigation items are accessible
- Open the dev tools and use a mobile screen size
- Verify the settings navigation …

fix: sidebar height lp#2021965

---

src/app/kvm/views/LXDClusterDetails/LXDClusterHosts/LXDClusterHostsTable/LXDClusterHostsTable.test.tsx
src/app/kvm/views/LXDClusterDetails/LXDClusterVMs/LXDClusterVMs.test.tsx
src/app/kvm/views/LXDSingleDetails/LXDSingleSettings/AuthenticationCard/UpdateCertificate/UpdateCertificate.test.tsx
src/app/kvm/views/VirshDetails/VirshDetailsHeader/VirshDetailsHeader.test.tsx

```
8.0K	./src/app/kvm/views/LXDClusterDetails/LXDClusterHosts/LXDClusterHostsTable/LXDClusterHostsTable.test.tsx
8.0K	./src/app/kvm/views/LXDClusterDetails/LXDClusterVMs/LXDClusterVMs.test.tsx
8.0K	./src/app/kvm/views/LXDSingleDetails/LXDSingleSettings/AuthenticationCard/UpdateCertificate/UpdateCertificate.test.tsx
8.0K	./src/app/kvm/views/VirshDetails/VirshDetailsHeader/VirshDetailsHeader.test.tsx
```
Fixes [MAASENG-1744](https://warthogs.atlassian.net/browse/MAASENG-1744)
[MAASENG-1744]: https://warthogs.atlassian.net/browse/MAASENG-1744?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: Migrate 4 KVM/views tests to RTL MAASENG-1744

---

src/app/base/components/Stepper/Stepper.tsx
src/app/kvm/components/KVMHeaderForms/AddLxd/AddLxd.test.tsx
src/app/kvm/components/KVMHeaderForms/AddLxd/AuthenticationForm/AuthenticationForm.tsx
src/app/kvm/components/KVMHeaderForms/AddLxd/CredentialsForm/CredentialsForm.tsx
src/app/kvm/components/KVMHeaderForms/AddLxd/SelectProjectForm/SelectProjectForm.test.tsx
src/app/kvm/components/KVMHeaderForms/AddLxd/SelectProjectForm/SelectProjectForm.tsx
src/app/kvm/components/KVMHeaderForms/AddLxd/SelectProjectForm/SelectProjectFormFields/SelectProjectFormFields.test.tsx
src/app/kvm/components/KVMHeaderForms/AddLxd/SelectProjectForm/SelectProjectFormFields/SelectProjectFormFields.tsx
src/app/kvm/components/KVMHeaderForms/AddVirsh/AddVirsh.test.tsx
src/app/kvm/components/KVMHeaderForms/ComposeForm/InterfacesTable/SubnetSelect/SubnetSelect.test.tsx
src/app/kvm/components/KVMHeaderForms/ComposeForm/StorageTable/PoolSelect/PoolSelect.test.tsx
src/app/kvm/components/KVMHeaderForms/ComposeForm/StorageTable/PoolSelect/PoolSelect.tsx
src/app/kvm/components/KVMHeaderForms/KVMHeaderForms.test.tsx

```
8.0K	./src/app/kvm/components/KVMHeaderForms/AddLxd/AddLxd.test.tsx
8.0K	./src/app/kvm/components/KVMHeaderForms/AddLxd/SelectProjectForm/SelectProjectForm.test.tsx
8.0K	./src/app/kvm/components/KVMHeaderForms/AddLxd/SelectProjectForm/SelectProjectFormFields/SelectProjectFormFields.test.tsx
8.0K	./src/app/kvm/components/KVMHeaderForms/AddVirsh/AddVirsh.test.tsx
8.0K	./src/app/kvm/components/KVMHeaderForms/ComposeForm/InterfacesTable/SubnetSelect/SubnetSelect.test.tsx
8.0K	./src/app/kvm/components/KVMHeaderForms/ComposeForm/StorageTable/PoolSelect/PoolSelect.test.tsx
8.0K	./src/app/kvm/components/KVMHeaderForms/KVMHeaderForms.test.tsx
```
Fixes [MAASENG-1731](https://warthogs.atlassian.net/browse/MAASENG-1731)
[MAASENG-1731]: …

test: Migrate 7 KVMHeaderForms to RTL MAASENG-1731

---

src/app/machines/components/MachineHeaderForms/AddChassis/AddChassisFormFields/AddChassisFormFields.test.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/CloneForm/CloneFormFields/CloneStorageTable/CloneStorageTable.test.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/CloneForm/CloneFormFields/CloneStorageTable/CloneStorageTable.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/CommissionForm/CommissionFormFields/CommissionFormFields.test.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/MarkBrokenForm/MarkBrokenForm.test.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/SetPoolForm/SetPoolFormFields/SetPoolFormFields.test.tsx

```
4.0K	./src/app/machines/components/MachineHeaderForms/AddChassis/AddChassisFormFields/AddChassisFormFields.test.tsx
4.0K	./src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/CloneForm/CloneFormFields/CloneStorageTable/CloneStorageTable.test.tsx
4.0K	./src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/CommissionForm/CommissionFormFields/CommissionFormFields.test.tsx
4.0K	./src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/MarkBrokenForm/MarkBrokenForm.test.tsx
4.0K	./src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/SetPoolForm/SetPoolFormFields/SetPoolFormFields.test.tsx
```
Fixes [MAASENG-1735](https://warthogs.atlassian.net/browse/MAASENG-1735)
[MAASENG-1735]: …

test: Migrate 5 MachineHeaderForms tests to RTL MAASENG-1735

---

src/app/machines/components/MachineHeaderForms/AddChassis/AddChassisForm/AddChassisForm.test.tsx
src/app/machines/components/MachineHeaderForms/AddMachine/AddMachineFormFields/AddMachineFormFields.test.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/CloneForm/CloneForm.test.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/CloneForm/CloneFormFields/CloneFormFields.test.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/CloneForm/CloneFormFields/CloneNetworkTable/CloneNetworkTable.test.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/CloneForm/CloneFormFields/CloneNetworkTable/CloneNetworkTable.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/CommissionForm/CommissionForm.test.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/CommissionForm/CommissionFormFields/CommissionFormFields.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/ReleaseForm/ReleaseForm.test.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/SetPoolForm/SetPoolForm.test.tsx

Migrated the following files to RTL:
```
8.0K	./src/app/machines/components/MachineHeaderForms/AddChassis/AddChassisForm/AddChassisForm.test.tsx
8.0K	./src/app/machines/components/MachineHeaderForms/AddMachine/AddMachineFormFields/AddMachineFormFields.test.tsx
8.0K	./src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/CloneForm/CloneForm.test.tsx
8.0K	./src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/CloneForm/CloneFormFields/CloneFormFields.test.tsx
8.0K	./src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/CloneForm/CloneFormFields/CloneNetworkTable/CloneNetworkTable.test.tsx
8.0K	./src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/CommissionForm/CommissionForm.test.tsx
8.0K …
```

test: Migrate 8 MachineHeaderForms test to RTL MAASENG-1730

---

docs/HACKING.md
package.json
src/app/machines/views/MachineList/MachineListTable/StatusColumn/StatusColumn.test.tsx
src/setupTests.ts
src/testing/utils.tsx
yarn.lock

- chore: remove enzyme MAASENG-1801
- migrate StatusColumn to RTL
Fixes: https://warthogs.atlassian.net/browse/MAASENG-1801
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. …

chore: remove enzyme MAASENG-1801

---

.github/workflows/test.yml
package.json

ci: update test scripts
- set runInBand for CI …

ci: update test scripts

---

sitespeed.io/login.js
sitespeed.io/scripts/machines.js

- fix sitespeed.io workflow
- update xpath selector
- Verify the fix has worked by checking workflow output from `test-sitespeed.io-fix` branch: https://github.com/canonical/maas-ui/actions/runs/5156251350 …

test: update sitespeed.io workflow

---

src/app/machines/views/MachineList/MachineListTable/MachineListDisplayCount/MachineListDisplayCount.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListSelectedCount/MachineListSelectedCount.test.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListSelectedCount/MachineListSelectedCount.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListSelectedCount/index.ts
src/app/machines/views/MachineList/MachineListTable/MachineListTable.tsx
src/app/machines/views/MachineList/_index.scss

- Added a notification to show the number of machines currently selected
- Created MachineListSelectedCount component
- Exported `getCurrentPageDisplayedMachineCount` function from `MachineListDisplayCount` to assist with [MAASENG-1688](https://warthogs.atlassian.net/browse/MAASENG-1688)
- Select a few …

feat(machines): Add notification to show number of selected machines MAASENG-1355

---

src/app/Routes.tsx
src/app/dashboard/views/Dashboard.tsx
src/app/dashboard/views/DashboardHeader/DashboardHeader.test.tsx
src/app/dashboard/views/DashboardHeader/DashboardHeader.tsx

- Refactored Dashboard and DashboardHeader to use PageContent
- Added test to DashboardHeader suite to ensure "Clear all" button opens the side panel
- Go to `/dashboard`
- Click "Clear all discoveries"
- Ensure the side panel is opened
Fixes [MAASENG-1809](https://warthogs.atlassian.net/browse/MAASENG-1809)
[MAASENG-1809]: …

chore: Refactor Dashboard to use PageContent MAASENG-1809

---

src/app/Routes.tsx
src/app/base/side-panel-context.tsx
src/app/domains/views/DomainDetails/DomainDetails.tsx
src/app/domains/views/DomainDetails/DomainDetailsHeader/DomainDetailsHeader.test.tsx
src/app/domains/views/DomainDetails/DomainDetailsHeader/DomainDetailsHeader.tsx
src/app/domains/views/DomainDetails/constants.ts

- Refactored DomainDetails to use PageContent
- Added tests to DomainDetailsHeader test suite to check that open side panel function has been called correctly
- Go to domains and click a domain
- Ensure the side panel opens correctly when "Add record" is clicked
- Ensure the side panel opens correctly when "Delete domain" is …

chore: Refactor DomainDetails to use PageContent MAASENG-1811

---

src/app/Routes.tsx
src/app/domains/views/DomainsList/DomainListHeader/DomainListHeader.test.tsx
src/app/domains/views/DomainsList/DomainListHeader/DomainListHeader.tsx
src/app/domains/views/DomainsList/DomainsList.test.tsx
src/app/domains/views/DomainsList/DomainsList.tsx

- Refactored DomainsList and DomainsListHeader to use PageContent
- Go to `/domains`
- Click "Add domain"
- Ensure side panel opens correctly
Fixes [MAASENG-1812](https://warthogs.atlassian.net/browse/MAASENG-1812)
[MAASENG-1812]: https://warthogs.atlassian.net/browse/MAASENG-1812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Z …

chore: Refactor DomainsList to use PageContent MAASENG-1812

---

src/app/base/components/NodeName/NodeName.test.tsx
src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.test.tsx
src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.tsx

- Remove dialog when locking/unlocking a machine on details page
- Proceed to the details page of any machine that's eligible for locking/unlocking
- Click on the Lock/Unlock button
- ENsure that the machine is locked / unlocked without any dialog being shown.
[MAASENG-1610](https://warthogs.atlassian.net/browse/MAASENG-1610) …

Fix: remove lock and unlock dialog on machine details page

---

src/app/Routes.tsx
src/app/subnets/views/FabricDetails/FabricDetails.test.tsx
src/app/subnets/views/FabricDetails/FabricDetails.tsx
src/app/subnets/views/FabricDetails/FabricDetailsHeader/FabricDetailsHeader.test.tsx
src/app/subnets/views/FabricDetails/FabricDetailsHeader/FabricDetailsHeader.tsx

- Refactored FabricDetails to use PageContent
- Go to subnets and click on a fabric
- Click "Delete fabric"
- Ensure the side panel is displayed correctly
Fixes [MAASENG-1824](https://warthogs.atlassian.net/browse/MAASENG-1824)
[MAASENG-1824]: https://warthogs.atlassian.net/browse/MAASENG-1824?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmND …

chore: Refactor FabricDetails to use PageContent MAASENG-1824

---

README.md
docs/MAASUI.md
src/app/base/sagas/websockets.ts

- docs: update readme
- expand section on redux saga and websockets
- add links to nested docs sections in `/docs`
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. Please …

docs: expand redux saga readme section

---

cypress/e2e/with-users/machines/list.spec.ts
src/app/machines/views/Machines.tsx

- fix: machine list in sync with URL MAASENG-1836
- Go to controller list page
- Click the machines navigation item to navigate to machine list page
- Select a filter
- Click "back" button in the browser
- you should be taken to the previous page (controller list in this case) and not one step back in filters history
Fixes: …

fix: machine list in sync with URL MAASENG-1836

---

src/app/subnets/views/SubnetsList/SubnetsList.tsx

- fix: subnets subtitle position
- Go to subnets list page
- Verify the subtitle is positioned correctly …

fix: subnets subtitle position

---

src/app/Routes.tsx
src/app/subnets/types.ts
src/app/subnets/views/SubnetDetails/SubnetDetails.tsx
src/app/subnets/views/SubnetDetails/SubnetDetailsHeader/SubnetDetailsHeader.tsx
src/app/subnets/views/SubnetsList/SubnetsList.tsx

- refactor: subnet details MAASENG-1826
Note: review after https://github.com/canonical/maas-ui/pull/5003
- Go to subnets list
- Click on a subnet link
- Click "take action" -> "map subnet"
- Verify that the side panel is displayed correctly
Fixes: https://warthogs.atlassian.net/browse/MAASENG-1826
Related Launchpad maas issue …

refactor: subnet details MAASENG-1826

---

package.json
yarn.lock

- chore: update typescript to 5.1.3
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. Please apply backport labels to the PR (e.g. "Backport 2.7") for the appropriate releases …

chore: update typescript to 5.1.3

---

src/app/store/machine/reducers.test.ts
src/app/store/machine/slice.ts

- fix: machine delete notify backport 3.4 
`lp#2023138`
https://bugs.launchpad.net/maas-ui/+bug/2023138 …

fix: machine delete notify backport 3.4 lp#2023138

---

src/app/store/machine/types/base.ts

- refactor: update base machine testing status type to skip keys that are not used
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. Please apply backport labels to the PR …

refactor: update base machine testing status type

---

.eslintrc.js
src/app/base/components/AppSideNavigation/AppSideNavItems/AppSideNavItems.tsx
src/app/base/components/Meter/Meter.tsx
src/app/base/components/NodeName/NodeNameFields/NodeNameFields.tsx
src/app/base/components/SecondaryNavigation/SecondaryNavigation.tsx
src/app/base/components/TitledSection/TitledSection.tsx
src/app/controllers/views/ControllerDetails/ControllerVLANs/ControllerVLANsTable/ControllerVLANsTable.tsx
src/app/machines/components/MachineForms/MachineActionFormWrapper/OverrideTestForm/OverrideTestForm.tsx
src/app/machines/components/MachineForms/MachineActionFormWrapper/TagForm/TagFormChanges/TagFormChanges.tsx
src/app/machines/views/MachineList/MachineListTable/StatusColumn/StatusColumn.tsx
src/app/preferences/views/SSLKeys/AddSSLKey/AddSSLKey.tsx
src/app/subnets/views/FormActions/components/AddSubnet.tsx
src/app/subnets/views/SubnetsList/SubnetsTable/components.tsx
src/app/subnets/views/VLANDetails/VLANDetailsHeader/VLANDetailsHeader.tsx
src/testing/utils.tsx

- disable no-multi-comp eslint rule
TLDR; Strict enforcement of this rule often leads to adopting anti-patterns and unnecessary complexity.
For instance, it promotes creating monolithic components to avoid breaking the rule, creating additional simple functions instead of React components so that they can be placed in the same file, or overusing custom hooks, even when a simple component could do the job. As a result, this leads to unnecessary complexity and makes code more difficult to parse.

test: disable no-multi-comp eslint rule

---

src/app/machines/views/MachineList/MachineList.test.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListGroupCount/MachineListGroupCount.test.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListGroupCount/MachineListGroupCount.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListGroupCount/index.ts
src/app/machines/views/MachineList/MachineListTable/MachineListTable.tsx
src/app/store/machine/reducers.test.ts
src/app/store/machine/slice.ts
src/app/store/machine/types/base.ts
src/testing/factories/state.ts

- fetch machine group counts MAASENG-1882
- test: fix duplicated key error due to invalid test data setup
Will be followed up by https://warthogs.atlassian.net/browse/MAASENG-1834 where parts of the implementation may change.
- open developer tools and network inspector
- go to machine list page
- select group by status
- select …

feat: fetch machine group counts MAASENG-1882

---

.eslintrc.js
src/app/store/utils/slice.ts

- test: disable explicit boundary types
Explicit boundary types come at a cost of having to manually define return types whilst they can be inferred by TypeScript. They are not really necessary unless you're dealing with a component library where you need to be very careful about changing the return types.

test: disable explicit boundary types

---

src/app/machines/views/MachineList/MachineList.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListPagination/MachineListPagination.test.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListPagination/MachineListPagination.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListTable.tsx
src/app/store/machine/selectors.ts
src/app/store/machine/utils/hooks.ts

- fix: machine list pagination
- Go to machine listing on a MAAS with multiple machines
- If needed, you can set the page size manually to a low value in developer tools console by typing `localStorage.setItem("machineListPageSize", "1")` and refreshing the page
- collapse a group of machines
- total number of pages should update
- expand a group of machines
- the total number of machines should update
https://bugs.launchpad.net/maas-ui/+bug/2025375
lp#2025375

fix: machine list pagination lp#2025375

---

src/app/store/machine/types/base.ts

- replace optional machine properties with null
Fixes: # . …

replace optional machine properties with null

---

src/app/base/components/DhcpFormFields/MachineSelect/MachineSelectBox/MachineSelectBox.tsx
src/app/base/components/Pagination/Pagination.test.tsx
src/app/base/components/Pagination/Pagination.tsx
src/app/base/components/Pagination/PaginationButton/PaginationButton.tsx
src/app/base/components/Pagination/PaginationButton/index.ts
src/app/base/components/Pagination/PaginationItem/PaginationItem.test.tsx
src/app/base/components/Pagination/PaginationItem/PaginationItem.tsx
src/app/base/components/Pagination/PaginationItem/__snapshots__/PaginationItem.test.tsx.snap
src/app/base/components/Pagination/PaginationItem/index.ts
src/app/base/components/Pagination/__snapshots__/Pagination.test.tsx.snap
src/app/base/components/Pagination/index.ts
src/app/kvm/components/VmResources/VmResources.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/CloneForm/CloneFormFields/SourceMachineSelect/SourceMachineSelect.tsx
src/app/machines/views/MachineList/MachineList.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListPagination/MachineListPagination.test.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListPagination/MachineListPagination.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListTable.test.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListTable.tsx
src/app/store/machine/selectors.ts
src/app/store/machine/utils/hooks.ts
src/app/tags/views/TagMachines/TagMachines.tsx

- fix: machine list pagination (#5029) 3.3 backport
- create a local copy of `Pagination` from `@canonical/react-components`
- allow custom `totalPages` for `Pagination`
- Go to machine listing on a MAAS with multiple machines
- If needed, you can set the page size manually to a low value in developer tools console by typing `localStorage.setItem("machineListPageSize", "1")` and refreshing the page
- collapse a group of machines and take note of the total number of pages
- expand a group of machines
- the total number of machines should update
https://bugs.launchpad.net/maas-ui/3.4/+bug/2025375
lp#2025375

fix: machine list pagination (#5029) 3.3 backport

---

src/app/base/sagas/websockets/websockets.test.ts
src/app/base/sagas/websockets/websockets.ts
src/websocket-client.ts

- fix: keep websocket connection alive by sending a ping message every 50 seconds
- setup heartbeat ping/pong message handlers
- Log in
- Open developer tools and inspect the websocket connection
- Ensure that every 50 seconds a websocket ping message is sent and replied to by the server
Fixes: lp#231930001 …

fix: keep websocket connection alive lp#231930001

---

src/app/kvm/components/KVMForms/KVMForms.tsx
src/app/machines/views/MachineList/MachineListTable/AllCheckbox/AllCheckbox.tsx
src/app/machines/views/MachineList/MachineListTable/AllCheckbox/AllDropdown/AllDropdown.test.tsx.tsx
src/app/machines/views/MachineList/MachineListTable/AllCheckbox/AllDropdown/AllDropdown.tsx
src/app/machines/views/MachineList/MachineListTable/AllCheckbox/AllDropdown/index.ts
src/app/machines/views/MachineList/MachineListTable/AllCheckbox/utils.ts
src/app/machines/views/MachineList/MachineListTable/MachineListTable.tsx
src/app/machines/views/MachineList/_index.scss
src/app/store/machine/utils/hooks.ts

- feat: machine list select all MAASENG-1688
- fix: pass filter to `useMachineSelectedCount` for a correct machine count
- make filter required
- Select group by status
- Add filter by owner
- Select a group of machines
- Ensure the number of machines is correct
- Click "Categorise" -> Tag
- add a new tag
- verify the action has been performed only on specified selected and filtered machines
https://warthogs.atlassian.net/browse/MAASENG-1688

feat: machine list select all MAASENG-1688

---

cypress/e2e/with-users/machines/list.spec.ts
src/app/kvm/components/VmResources/VmResources.test.tsx
src/app/machines/constants.ts
src/app/machines/views/MachineList/MachineListControls/GroupSelect/GroupSelect.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListTable.tsx
src/app/machines/views/Machines.test.tsx

- test: fix cypress machine list test #5041
- add grouping status to machine list table label
- cleanup stored machine list grouping after each test
- fix invalid test setup data resulting in duplicate keys
- move `groupOptions` to shared `constants.ts` file 
Fixes:  #5041

test: fix cypress machine list test #5041

---

src/app/machines/views/MachineList/MachineListTable/MachineListPagination/MachineListPagination.test.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListPagination/MachineListPagination.tsx

- fix: DHCP snippets machine pagination
- Go to DHCP snippets
- click "add snippet"
- select type machine
- ensure that pagination buttons work correctly and requested page is displayed

fix: DHCP snippets machine pagination

---

cypress/e2e/with-users/base/navigation.spec.ts
src/app/base/components/AppSideNavigation/AppSideNavigation.tsx
src/app/base/components/MainContentSection/MainContentSection.test.tsx
src/app/base/components/MainContentSection/MainContentSection.tsx
src/app/base/components/ModelNotFound/ModelNotFound.tsx
src/app/dashboard/views/Dashboard.tsx
src/app/intro/views/Intro.tsx

- update document semantics MAASENG-1263
- add labels to header elements 
- Go to dashboard
- verify it's displayed correctly
- In a new MAAS instance (alternatively you can remove redirects from components in order to force /intro routes to persist) that doesn't have user intro completed:
- Go through all user setup steps
- Verify each step is displayed correctly
Fixes: https://warthogs.atlassian.net/browse/MAASENG-1263

update document semantics MAASENG-1263

---

src/app/base/components/AppSideNavigation/AppSideNavItems/AppSideNavItems.tsx

- Non-admin usernames are now displayed correctly in the side navigation
- Log in as a non-admin user
- Ensure your name displays correctly in the navigation
Fixes [MAASENG-1987](https://warthogs.atlassian.net/browse/MAASENG-1987)
[MAASENG-1987]: https://warthogs.atlassian.net/browse/MAASENG-1987?atlOrigin=eyJpIjoiNWRkNTljNzYxNjV …

fix(navigation): Display usernames correctly for non-admins MAASENG-1987

---

src/app/base/components/PageContent/PageContent.test.tsx
src/app/base/components/PageContent/PageContent.tsx

- Prevent secondary navigation from displaying if user is not authenticated or connected
- Add tests to ensure secondary nav can display on /settings and /account routes
- Add tests to ensure secondary nav does not display without auth or connection
1. Go to /settings
2. Log out
3. Ensure navigation does not display
4. Log in
5. …

fix(navigation): Prevent secondary navigation from displaying without auth MAASENG-1986

---

src/app/base/components/AppSideNavigation/AppSideNavItems/AppSideNavItems.tsx

- Display non-admin usernames correctly in side nav
QA was completed as part of https://github.com/canonical/maas-ui/pull/5068

fix:(navigation): Display non-admin usernames correctly 3.4 backport

---

scripts/proxy.js
src/app/base/sagas/http.test.ts
src/app/base/sagas/http.ts
src/app/base/sagas/index.ts
src/app/store/zone/actions.test.ts
src/app/store/zone/slice.ts
src/root-saga.ts

- integrate zones list endpoint MAASENG-1975
- call `/MAAS/a/v1/zones` REST endpoint instead of `zone.list` websocket API whenever `zone/fetch` redux action is called
- reduce redundant tests nesting in `describe("http sagas", () => {`
- open developer tools and go to Network tab
- Go to machines list
- Verify that zones list has been fetched via REST API (should be in Fetch/XHR list) and there is no zone.list in websocket messages
Fixes: https://warthogs.atlassian.net/browse/MAASENG-1975

integrate zones list endpoint MAASENG-1975

---

src/app/utils/formatErrors.test.ts
src/app/utils/formatErrors.ts

fix: TypeError formatting

---

src/app/App.tsx

- Prevent side nav from displaying if user is not connected or authenticated
QA for this was completed in https://github.com/canonical/maas-ui/pull/5067

fix(navigation): prevent side nav display without auth 3.4 backport

---

src/app/base/sagas/http.ts
src/app/base/sagas/loaded-endpoints.test.ts
src/app/base/sagas/loaded-endpoints.ts

- fix: cache zones list requests
- replicate [existing logic for websocket messages](https://github.com/canonical/maas-ui/blob/8791189ade1660b822481cbe4cfaaca80082ab2d/src/app/base/sagas/websockets/websockets.ts#L331) for zones REST API endpoint
Cypress failures due to infinite loop of zones list API requests https://github.com/canonical/maas-ui/actions/runs/5620547616
1. Go to devices
2. Click Add device
3. Make sure zones list REST API endpoint has been called at least once and form displayed

fix: cache zones list requests

---

.github/workflows/cypress.yml

- test: set channel for cypress tests to 3.4 beta

test: set channel for cypress tests to 3.4 beta

---

.eslintrc.js
cypress/e2e/with-users/machines/actions.spec.ts
cypress/e2e/with-users/machines/list.spec.ts
cypress/support/commands.ts
src/app/base/components/AppSidePanel/AppSidePanel.test.tsx
src/app/base/components/AppSidePanel/AppSidePanel.tsx
src/app/base/components/AppSidePanel/index.ts
src/app/base/components/NodeActionMenu/NodeActionMenu.tsx
src/app/base/components/NodeActionMenuGroup/NodeActionMenuGroup.tsx
src/app/base/components/PageContent/PageContent.tsx
src/app/base/side-panel-context.test.tsx
src/app/base/side-panel-context.tsx
src/app/controllers/components/ControllerForms/ControllerForms.tsx
src/app/devices/components/DeviceHeaderForms/DeviceHeaderForms.tsx
src/app/kvm/components/KVMForms/KVMForms.tsx
src/app/machines/components/MachineForms/MachineActionFormWrapper/TagForm/AddTagForm/AddTagForm.tsx
src/app/machines/components/MachineForms/MachineActionFormWrapper/TagForm/TagForm.test.tsx
src/app/machines/components/MachineForms/MachineActionFormWrapper/TagForm/TagForm.tsx
src/app/machines/components/MachineForms/MachineActionFormWrapper/TagForm/TagFormChanges/TagFormChanges.test.tsx
src/app/machines/components/MachineForms/MachineActionFormWrapper/TagForm/TagFormChanges/TagFormChanges.tsx
src/app/machines/components/MachineForms/MachineActionFormWrapper/TagForm/TagFormFields/TagFormFields.test.tsx
src/app/machines/components/MachineForms/MachineActionFormWrapper/TagForm/TagFormFields/TagFormFields.tsx
src/app/machines/components/MachineForms/MachineForms.tsx
src/app/machines/views/MachineList/MachineListControls/MachineListControls.tsx
src/app/subnets/views/SpaceDetails/SpaceDetailsHeader/SpaceDetailsHeader.tsx
src/app/tags/components/TagsHeader/TagForms/TagForms.tsx
src/scss/_patterns_application.scss
src/testing/utils.tsx

- feat: tag management panel MAASENG-1427
- remove .l-aside visibility workaround 
- refactor AppSidePanel
- update node action menu dropdown styles
- remove eslint-disable-next-line cypress/no-force comments as we disable the rule globally due to vanillaframework implementation of form elements
Details on the design: https://warthogs.atlassian.net/browse/MAASENG-1422
- Go to machine list page
- Select a machine
- Click categorise -> tag
- type a name of a new tag in the search field
- add a new tag
- Click save
- Ensure the machine has been updated correctly
---
- go to machine details page
- Click categorise -> tag
- type a name of a new tag in the search field
- add a new tag
- Click save
- Ensure the machine has been updated correctly
- ---
- Go to devices page
- Press "Add"
- Click …

feat: tag management panel MAASENG-1427

---

cypress/e2e/with-users/base/side-panel.spec.ts
src/app/base/components/AppSidePanel/AppSidePanel.tsx
src/app/machines/views/Machines.test.tsx

- fix: AppSidePanel not closing on route change
- add more thorough e2e tests
- update side panel test id
- On the controller page, click add rack controller
- From the side navigation menu, go to 'LXD'
- Verify the side panel has been closed

fix: AppSidePanel not closing on route change

---

src/app/controllers/views/ControllerDetails/ControllerSummary/ServicesCard/ServicesCard.tsx
src/app/store/service/types/enum.ts

- This PR adds new services under Controller summary. Service `agent` runs on the Rack Controller (also in Region+Rack setup). Service `temporal` runs on the Region controller (also in Region+Rack setup).

feat: add temporal & agent services

---

src/app/base/components/FormikForm/FormikForm.tsx
src/app/base/components/FormikForm/index.ts
src/app/machines/views/MachineDetails/MachineConfiguration/PowerForm/PowerForm.tsx
src/app/settings/views/Images/ThirdPartyDriversForm/ThirdPartyDriversForm.tsx
src/app/settings/views/Images/VMWareForm/VMWareForm.tsx
src/app/settings/views/Network/NtpForm/NtpForm.tsx
src/app/subnets/views/VLANDetails/EditVLAN/EditVLAN.tsx

- fix: FormikField null values MAASENG-2099
- explicitly disallow null values in formik initialValues
- Open `src/app/machines/views/MachineDetails/MachineConfiguration/PowerForm/PowerForm.tsx`
- replace line 97 with: `              powerType: machine.power_type,` 
- Verify that a TypeError is thrown: "Type 'null' is not assignable to type 'InputFieldValue'."
Fixes: MAASENG-2099

fix: use valid default formik form values MAASENG-2099

---

src/app/base/components/ActionBar/ActionBar.tsx
src/app/base/components/DebounceSearchBox/DebounceSearchBox.tsx
src/app/base/components/SearchBox/SearchBox.test.tsx
src/app/base/components/SearchBox/SearchBox.tsx
src/app/base/components/SearchBox/index.ts
src/app/base/components/node/NodeLogs/EventLogs/EventLogs.tsx
src/app/base/constants.ts
src/app/dashboard/views/DiscoveriesList/DiscoveriesList.tsx
src/app/settings/components/SettingsTable/SettingsTable.tsx

- feat: global "/" search key shortcut
Repeat the steps below on pages: machine list, tags, controllers subnets, network discovery, settings/users
- Open the page
- Press "/"
- Verify that the search box has focus and you can start typing immediately
Fixes: https://warthogs.atlassian.net/browse/MAASENG-2106

feat: global "/" search key shortcut

---

cypress/e2e/with-users/machines/list.spec.ts
src/app/machines/views/MachineList/MachineList.tsx
src/app/machines/views/MachineList/MachineListControls/MachineListControls.tsx
src/app/machines/views/MachineList/MachineListHeader/MachineListHeader.tsx
src/app/machines/views/MachineList/_index.scss
src/app/machines/views/MachineList/hooks.ts
src/app/machines/views/Machines.tsx

- feat: responsive machine columns MAASENG-1505
- extract machine list table utils to hooks: `usePageSize`, `useGrouping`, `useResponsiveColumns`
- Open the columns dropdown
- Make sure you have all columns checked
- WIth the dropdown still open, start resizing the widow down and verify that columns are unchecked progressively as the window size decreases
- With the window size set to the smallest size, enable additional columns
- Without changing the window size, refresh the page
- Columns should remain the same
- Slowly start to increase the window size
- As you increase the window size the columns should reset to the default set for each breakpoint
Fixes:  https://warthogs.atlassian.net/browse/MAASENG-1505

feat: responsive machine columns MAASENG-1505

---

src/app/kvm/components/LXDVMsTable/VMsTable/_index.scss
src/app/kvm/components/StorageResources/StorageResources.tsx
src/app/kvm/components/StorageResources/_index.scss

- Extend storage card to full width
- Fix dropdown button position on VM table
- Goto `/kvm/lxd`
- Click on a host from the list to view the details page
- Ensure that the storage card info spans the whole card
- Scroll down to the table and ensure that the dropdown beside the checkbox is well positioned as in the screenshot below
[MAASENG-2102](https://warthogs.atlassian.net/browse/MAASENG-2102)
[MAASENG-2102]: https://warthogs.atlassian.net/browse/MAASENG-2102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Maaseng 2102 extend storage card fullwifth

---

src/app/settings/views/Configuration/GeneralForm/ThemedRadioButton/ThemedRadioButton.tsx

- fix: use `defaultChecked` in ThemedRadioButton
Removes the following warning:
```
Warning: You provided a `checked` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultChecked`. Otherwise, set either `onChange` or `readOnly`.
at input
at label
at ThemedRadioButton (/Users/makowski/Documents/GitHub/maas-ui/src/app/settings/views/Configuration/GeneralForm/ThemedRadioButton/ThemedRadioButton.tsx:28:3)
```
- Go to theme settings
- Verify that the current theme is set as active radio button and you can change the theme

fix: use defaultChecked in ThemedRadioButton

---

src/app/store/auth/slice.ts
src/app/store/scriptresult/slice.ts

- refactor: use builder callback MAASENG-1855
This removes redux toolkit deprecation warning for extraReducers.
https://redux-toolkit.js.org/api/createSlice#the-extrareducers-builder-callback-notation
1. Go to `MAAS/r/account/prefs/details`
2. Open developer tools and redux devtools
3. Edit Full name and submit
4. Verify that auth user `last_name` has been updated
Fixes: https://warthogs.atlassian.net/browse/MAASENG-1855

refactor: use builder callback MAASENG-1855

---

src/app/base/components/FormikField/FormikField.test.tsx
src/app/dashboard/views/DiscoveryAddForm/DiscoveryAddForm.test.tsx
src/app/machines/views/MachineDetails/MachineNetwork/BondForm/BondFormFields/BondFormFields.test.tsx
src/app/settings/views/Configuration/DeployForm/DeployForm.test.tsx
src/app/settings/views/Security/SecurityProtocols/TLSEnabled/TLSEnabled.test.tsx
src/app/tags/components/DefinitionField/DefinitionField.test.tsx
src/app/tags/components/TagsHeader/AddTagForm/AddTagForm.test.tsx

- test: set BondFormFields initialValues
- test: use toHaveAccessibleErrorMessage
Fixes the following error thrown when running `BondFormFields.test.tsx` test:
```
Warning: A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://reactjs.org/link/controlled-components
```
Fixes the following error across the codebase: 
```
Warning: toHaveErrorMessage has been deprecated and will be removed in future updates. Please use toHaveAccessibleErrorMessage.
```

test: set BondFormFields initialValues

---

.github/workflows/upload.yml

- ci: fix upload workflow sha
- use git push event for triggering upload workflow instead of pull_request
You can verify this method works correctly by looking at [test-upload-base](https://github.com/canonical/maas-ui/tree/test-upload-base) branch: https://github.com/canonical/maas-ui/actions/runs/5949044847 
Fixes: https://github.com/canonical/maas-ui/issues/5112

ci: fix upload workflow sha

---

src/app/base/components/FormikFormContent/FormikFormContent.test.tsx
src/app/base/components/FormikFormContent/FormikFormContent.tsx
src/app/base/hooks/forms.ts
src/app/base/types.ts
src/app/machines/components/ErrorDetails/ErrorDetails.test.tsx
src/app/machines/components/ErrorDetails/ErrorDetails.tsx
src/app/machines/components/ErrorDetails/index.ts
src/app/machines/components/MachineForms/MachineActionFormWrapper/MachineActionFormWrapper.test.tsx
src/app/machines/components/MachineHostname/MachineHostname.test.tsx
src/app/machines/components/MachineHostname/MachineHostname.tsx
src/app/machines/components/MachineHostname/index.ts
src/app/store/machine/slice.ts
src/app/store/machine/types/base.ts
src/app/store/machine/utils/hooks.test.tsx
src/app/store/machine/utils/hooks.tsx

- feat(machines) bulk failure reason MAASENG-1689
- add failureDetails to redux store machine slice
- create `ErrorDetails` component
- create `MachineHostname` component that takes systemId and fetches machine details
Using lab maas as back-end, follow steps below:
- Abort actions if any actions are in progress for "c-test-machine"
- Refresh the page
- Select "c-test-machine" and click `Actions` -> `Deploy` and perform the action
- Verify that the correct count (1) with error description has been displayed
Fixes: MAASENG-1689

feat(machines): bulk failure reason MAASENG-1689

---

.github/workflows/accessibility.yml
.github/workflows/cypress.yml

- ci: update install command for cypress 
- remove `--frozen-lockfile` from cypress install as it was triggering an error even though lockfile is up to date (and it's irrelevant to this test as we only care about and use cypress and not all other dependencies)
Verify that the test run passed in the commit below
[test run on current branch](https://github.com/canonical/maas-ui/pull/5125/commits/62037bcbc88b6d743973a87a8f8cb3644ba72902)
[62037bc](https://github.com/canonical/maas-ui/pull/5125/commits/62037bcbc88b6d743973a87a8f8cb3644ba72902)
Fixes: https://github.com/canonical/maas-ui/issues/5121 https://github.com/canonical/maas-ui/issues/5107

ci: update install command for cypress

---

package.json
yarn.lock

- remove cz-conventional-changelog MAASENG-1335
This fixes a critical security warning with `minimist` `1.2.5` which was a dependency of `cz-conventional-changelog`
https://github.com/canonical/maas-ui/security/dependabot/54
https://warthogs.atlassian.net/browse/MAASENG-1335

remove cz-conventional-changelog MAASENG-1335

---

src/app/App.test.tsx
src/app/App.tsx
src/app/base/sagas/websockets/websockets.test.ts
src/app/base/sagas/websockets/websockets.ts
src/app/store/status/reducers.test.ts
src/app/store/status/slice.ts
src/root-reducer.test.ts
src/root-reducer.ts
src/websocket-client.test.ts
src/websocket-client.ts

- fix: restore websocket on error lp#1930001
- keep current app state on lost websocket connection
- rename handleMessage, watchMessages to handleWebsocketEvent, watchWebsocketEvents
- rename socket to rws (reconnecting websocket)
- Checkout this branch locally, and run `yarn start`
- Open MAAS UI in the browser and login
- Go to machine listing, select to add a new machine, enter text into machine name
- go back to the terminal, close the local web server(e.g. by pressing ctrl+c)
- verify that "Trying to reconnect..." has been displayed in the browser
- Go back to the terminal and run `yarn start`
- Go to the browser and verify that "Trying to reconnect..." message has disappeared
- Verify that previously entered text is visible and you can interact with MAAS UI without issues
lp#1930001

fix: restore websocket connection on error lp#1930001

---

src/app/App.test.tsx
src/app/App.tsx
src/app/base/sagas/websockets.test.ts
src/app/base/sagas/websockets.ts
src/app/store/status/reducers.test.ts
src/app/store/status/slice.ts
src/root-reducer.test.ts
src/root-reducer.ts
src/websocket-client.test.ts
src/websocket-client.ts

- fix: restore websocket on error lp#1930001 (#5133)
- keep current app state on lost websocket connection
- rename handleMessage, watchMessages to handleWebsocketEvent, watchWebsocketEvents
- rename socket to rws (reconnecting websocket)
No steps necessary, tested in the original PR.

fix: restore websocket on error lp#1930001 (#5133)

---

.github/workflows/links-checker.yml

- fix: docs links test install command #5141
Updates the install command that was missed in a previous pull request: https://github.com/canonical/maas-ui/pull/5125

test: docs links test install command #5141

---

src/app/machines/views/MachineDetails/MachineStorage/MachineStorage.test.tsx
src/app/machines/views/MachineDetails/MachineStorage/StorageNotifications/StorageNotifications.test.tsx
src/app/machines/views/MachineDetails/MachineStorage/StorageNotifications/StorageNotifications.tsx
src/app/store/utils/node/storage.test.ts
src/app/store/utils/node/storage.ts

- fix: disallow storage layout update for allocated machines lp#1928623
Provided you have a machine with an "Allocated" status
- Go to machine details page for a machine with an "Allocated" status
- Press "Storage" (URL `/MAAS/r/machine/{systemId}/storage`)
- Verify that the "Change storage layout" dropdown is not visible
lp#1928623

fix: disallow storage layout update for allocated machines lp#1928623

---

src/app/machines/views/MachineList/MachineListControls/MachinesFilterAccordion/MachinesFilterOptions/MachinesFilterOptions.test.tsx
src/app/machines/views/MachineList/MachineListControls/MachinesFilterAccordion/MachinesFilterOptions/MachinesFilterOptions.tsx
src/app/machines/views/Machines.test.tsx
src/app/store/machine/selectors.ts

- Selecting a workload annotation filter will now fill the search box correctly to filter for that annotation key
- A checkbox is now shown next to selected workload annotation filters
Using a backend that has deployed machines with workload annotations:
1. Go to /machines
2. Open the filters dropdown
3. Open the "Workloads" …

fix(machines): Workload annotation filtering lp2023633

---

src/app/App.tsx
src/app/base/hooks/dataFetching.ts
src/app/base/sagas/websockets/websockets.test.ts
src/app/base/sagas/websockets/websockets.ts
src/app/store/machine/reducers.test.ts
src/app/store/machine/slice.ts
src/app/store/status/reducers.test.ts
src/app/store/status/selectors.ts
src/app/store/status/slice.ts
src/app/store/status/types/base.ts
src/testing/factories/state.ts

- fix(websockets): refetch all WS endpoints on reconnect
- add `useFetchActions` hook that runs a set of actions on mount and every time websocket reconnects
- replace all instances of `useEffect` with fetch actions on mount with `useFetchActions`
- add `connectedCount` to redux store to keep track of the number of times the websocket has connected successfully
- stop websocket ping on disconnect via `handlePingStop`
- run `invalidateQueries` on websocket disconnect to mark machine list and count requests as stale 
1. go to machine list
2. Open one of the machines visible in the list in another tab
3. restart MAAS
4. wait for front-end to reconnect
5. In the tab with machine details, make changes to the machine that will change its status (e.g. start testing)
6. Verify that the machine …

fix(websockets): refetch on reconnect MAASENG-2142

---

src/app/machines/views/MachineList/MachineListControls/MachinesFilterAccordion/MachinesFilterOptions/MachinesFilterOptions.test.tsx
src/app/machines/views/MachineList/MachineListControls/MachinesFilterAccordion/MachinesFilterOptions/MachinesFilterOptions.tsx
src/app/machines/views/Machines.test.tsx
src/app/store/machine/selectors.ts

- Selecting a workload annotation filter will now fill the search box correctly to filter for that annotation key
- A checkbox is now shown next to selected workload annotation filters
- Not needed.
lp#2023633
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless the fix is only …

fix(machines): Workload annotation filtering lp2023633 (#5131) 3.4 backport

---

.eslintrc.js
src/app/App.tsx
src/app/base/hooks/dataFetching.ts
src/app/base/sagas/websockets.test.ts
src/app/base/sagas/websockets.ts
src/app/preferences/views/Preferences.test.tsx
src/app/store/machine/reducers.test.ts
src/app/store/machine/slice.ts
src/app/store/status/reducers.test.ts
src/app/store/status/selectors.ts
src/app/store/status/slice.ts
src/app/store/status/types/base.ts
src/testing/factories/state.ts

- fix(websocket): refetch on reconnect MAASENG-2142 (#5146) 3.4 backport
- add `connectedCount` to redux store
- stop WebSocket ping on disconnect
- run invalidateQueries on disconnect
- run `useFetchActions` hook on reconnect
None required.

fix(websocket): refetch on reconnect MAASENG-2142 (#5146) 3.4 backport

---

src/app/machines/views/MachineList/MachineListTable/StatusColumn/StatusColumn.test.tsx
src/app/machines/views/MachineList/MachineListTable/StatusColumn/StatusColumn.tsx
src/app/store/machine/types/base.ts
src/app/utils/IsEphemerallyDeployed.ts
src/app/utils/index.ts
src/app/utils/isEphemerallyDeployed.test.ts
src/testing/factories/nodes.ts

- Added Ephemeral deployment indicator to machine list
- Go to `/machines`
- Filter by deployed machines
- The second row of the status cell should be blank, because there are no ephemeral deployments for now
- You can negate the condition that displays this indicator by negating line 132 of `src/app/machines/views/MachineList/MachineListTable/StatusColumn/StatusColumn.tsx`
- You should see the indicator display on the machine list as in the screenshot below
[MAASENG-2147](https://warthogs.atlassian.net/browse/MAASENG-2147)
[MAASENG-2147]: https://warthogs.atlassian.net/browse/MAASENG-2147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MAASENG-2147 add ephemeral indicator to machine list

---

src/app/base/components/node/OverviewCard/MachineStatusCard/MachineStatusCard.test.tsx
src/app/base/components/node/OverviewCard/MachineStatusCard/MachineStatusCard.tsx

- Add ephemeral deploy indicator to machine details page
- Go to the details page of any deployed machine
- If that machine is not deployed ephemerally, negate the condition in line 77 of `src/app/base/components/node/OverviewCard/MachineStatusCard/MachineStatusCard.tsx`
- You should see a heading that says 'Deployed in memory'
[MAASENG-2148](https://warthogs.atlassian.net/browse/MAASENG-2148)
[MAASENG-2148]: https://warthogs.atlassian.net/browse/MAASENG-2148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MAASENG-2148 machine details ephemeral indicator

---

src/app/machines/components/MachineForms/MachineActionFormWrapper/DeployForm/DeployForm.test.tsx
src/app/machines/components/MachineForms/MachineActionFormWrapper/DeployForm/DeployForm.tsx
src/app/machines/components/MachineForms/MachineActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.test.tsx
src/app/machines/components/MachineForms/MachineActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.tsx
src/app/store/machine/actions.test.ts
src/app/store/machine/types/actions.ts
src/app/store/utils/node/base.ts

- Added "Deployment target" section to deploy form
- Added `ephemeral_deploy` to node deployment action parameters
- Hide "Register as MAAS KVM host" if "Deploy in memory" is selected
- Changes submit button text from "Start deployment for `n` machines" to "Deploy `n` machines"
**Prerequisite**: Ensure you have dev tools open on …

feat(machines): Add "Deployment target" to deploy form MAASENG-2159

---

cypress/e2e/with-users/machines/actions.spec.ts
src/app/base/components/node/PowerOffForm/PowerOffForm.test.tsx
src/app/base/components/node/PowerOffForm/PowerOffForm.tsx
src/app/store/utils/node/base.ts

- Corrected soft stop button text
- Select a few machines and click on `Power Cycle` > `Soft Power off`
- Ensure the button in the dialog reads "Soft power off machine"

Fix soft power button text

---

.eslintrc.js
.storybook/maas-theme.ts
.storybook/main.ts
.storybook/manager.ts
.storybook/preview-head.html
.storybook/preview.tsx
docs/HACKING.md
package.json
src/app/base/components/AppSideNavigation/AppSideNavigation.stories.tsx
src/app/base/components/AppSideNavigation/AppSideNavigation.tsx
src/app/base/components/Meter/Meter.stories.tsx
src/app/base/components/TooltipButton/TooltipButton.stories.tsx
src/app/base/components/TooltipButton/TooltipButton.tsx
src/app/machines/components/MachineForms/MachineActionFormWrapper/MachineActionFormWrapper.stories.tsx
src/app/machines/components/MachineForms/MachineActionFormWrapper/MachineActionFormWrapper.tsx
src/app/machines/views/Machines.test.tsx
src/index.tsx
yarn.lock

- add storybook with example stories for `AppSideNavigation`, `Meter`, `TooltipButon`, `MachineActionFormWrapper`
- include `@storybook/addon-a11y` for easy accessibility testing
- refactor AppSideNavigation
- extend `HACKING.md` docs
- export context providers from `AppRoot` as `RootProviders` (so that they can be used in storybook)
This PR adds storybook to maas-ui to encourage [component-driven](https://www.componentdriven.org/) development and good component design.
It allows to quickly preview various states of components acting as an interactive documentation and speeding up the development.
It's not using extensive customisation options or specifying separate variants for each type of component to keep things simple and minimize the maintenance burden.
For example, …

docs: add storybook

---

cypress/e2e/with-users/machines/list.spec.ts
src/app/machines/views/MachineList/MachineListControls/MachinesFilterAccordion/MachinesFilterAccordion.tsx
src/app/store/machine/types/base.ts

- Add Deployment target to machine list filters
- Visit the machine list page
- Click on the `Filter` at the top of the list and ensure that `Deployment target` is among the list of filters
- Expand the deployment accordion and ensure that the filter options ("Deployed in memory" & "Deployed on disk") are visible
- Click on any of them and ensure that the list is filtered adequately and the search box is updated.
[Fixes: MAASENG-2150](https://warthogs.atlassian.net/jira/software/c/projects/MAASENG/issues/MAASENG-2150)
https://app.zeplin.io/project/64d256035eca5e52f01ee1ab/screen/64e72abaa08692236d2c54a6

MAASENG-2150 implement filtering by deployment target

---

src/app/machines/views/MachineList/MachineListControls/MachineActionMenu/MachineActionMenu.stories.tsx
src/app/machines/views/MachineList/MachineListControls/MachineActionMenu/MachineActionMenu.tsx
src/app/machines/views/MachineList/MachineListControls/MachineActionMenu/index.ts
src/app/machines/views/MachineList/MachineListControls/MachineListControls.tsx

- docs: add story for MachineActionMenu
- run `yarn storybook`
- go to http://localhost:6006/?path=/story/sections-machine-machineactionmenu--example
- verify the component is displayed

docs: add story for MachineActionMenu

---

.github/ISSUE_TEMPLATE/accessibility-failure.md
.github/ISSUE_TEMPLATE/ci-failure.md
.github/ISSUE_TEMPLATE/cypress-failure.md
.github/ISSUE_TEMPLATE/maas-io-docs-failed.md
.github/ISSUE_TEMPLATE/upload-failure.md
.github/workflows/accessibility.yml
.github/workflows/cypress.yml
.github/workflows/links-checker.yml
.github/workflows/sitespeed.yml
.github/workflows/upload.yml

- Added failure condition to sitespeed.io workflow
- Created universal CI failure issue template
- Directed all non-PR workflows to use template
Fixes [MAASENG-2176](https://warthogs.atlassian.net/browse/MAASENG-2176)
[MAASENG-2176]: https://warthogs.atlassian.net/browse/MAASENG-2176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(ci): Create issue on sitespeed failure MAASENG-2176

---

src/app/store/vlan/reducers.test.ts
src/app/store/vlan/slice.ts

- fix: update VLANs on subnet/createNotify
- Go to the subnets page
- make sort by Fabric is selected at the top
- Create a new subnet 
- Make sure the table has been updated with the new row
Fixes: https://bugs.launchpad.net/maas-ui/+bug/2037530

fix: update VLANs on subnet/createNotify

---

src/app/settings/views/Configuration/CommissioningForm/CommissioningForm.test.tsx
src/app/settings/views/Configuration/CommissioningForm/CommissioningForm.tsx
src/app/settings/views/Configuration/DeployForm/DeployForm.test.tsx
src/app/settings/views/Configuration/DeployForm/DeployForm.tsx
src/app/settings/views/Configuration/GeneralForm/GeneralForm.tsx
src/app/settings/views/Configuration/KernelParametersForm/KernelParametersForm.tsx
src/app/settings/views/Images/ThirdPartyDriversForm/ThirdPartyDriversForm.tsx
src/app/settings/views/Images/VMWareForm/VMWareForm.tsx
src/app/settings/views/Images/WindowsForm/WindowsForm.tsx
src/app/settings/views/Network/DnsForm/DnsForm.test.tsx
src/app/settings/views/Network/DnsForm/DnsForm.tsx
src/app/settings/views/Network/NetworkDiscoveryForm/NetworkDiscoveryForm.test.tsx
src/app/settings/views/Network/NetworkDiscoveryForm/NetworkDiscoveryForm.tsx
src/app/settings/views/Network/NtpForm/NtpForm.test.tsx
src/app/settings/views/Network/NtpForm/NtpForm.tsx
src/app/settings/views/Network/ProxyForm/ProxyForm.tsx
src/app/settings/views/Network/SyslogForm/SyslogForm.test.tsx
src/app/settings/views/Network/SyslogForm/SyslogForm.tsx
src/app/settings/views/Security/IpmiSettings/IpmiSettings.test.tsx
src/app/settings/views/Security/IpmiSettings/IpmiSettings.tsx
src/app/settings/views/Storage/StorageForm/StorageForm.test.tsx
src/app/settings/views/Storage/StorageForm/StorageForm.tsx
src/app/store/config/actions.test.ts
src/app/store/config/slice.ts

Refactor of the `config/slice.ts` to utilize the `bulk_update` method for updating configurations.
This improves the efficiency of updating multiple configuration values by reducing the number of websocket messages required.
- replace the "update" method with "bulk_update" in config slice
- pass config errors to child components along with cleaup prop to clear the error on component unmount
- go to one of the settings pages
- open developer tools and inspect websocket connection
- refresh the page
- make a change to the configuration
- ensure a websocket "bulk_update" message has been sent with correct parameters
- try to make an invalid configuration change (can be simulated locally by editing config/slice.ts and commenting out line 47 with `items: values`)
- submit the form and verify …

fix: use config bulk_update lp#1839788

---

.github/workflows/cypress.yml
cypress/e2e/with-users/base/footer.spec.ts
cypress/support/commands.ts

- Add script to ensure successful image sync before test run
- Update failing footer tests for legacy footer removal
[1967](https://warthogs.atlassian.net/jira/software/c/projects/MAASENG/issues/MAASENG-1967)
Fixes:

test: fix failing MAAS UI e2e tests

---

src/app/base/components/NodeActionMenu/NodeActionMenu.tsx
src/app/base/components/NodeActionMenuGroup/NodeActionMenuGroup.test.tsx
src/app/base/components/NodeActionMenuGroup/NodeActionMenuGroup.tsx
src/app/base/hooks/node.ts
src/app/machines/components/MachineForms/MachineActionFormWrapper/MachineActionFormWrapper.tsx
src/app/machines/constants.ts
src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.test.tsx
src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.tsx
src/app/machines/views/MachineList/MachineListControls/MachineActionMenu/MachineActionMenu.tsx
src/app/machines/views/MachineList/MachineListControls/MachineListControls.test.tsx
src/app/store/types/node.ts
src/app/store/utils/node/base.ts

- Renamed "Power cycle" to "Power"
- Added "Check power" to power actions for machine details*
- Removed dropdown next to power icon
Fixes [MAASENG-2125](https://warthogs.atlassian.net/browse/MAASENG-2125)
* "Check power" cannot be called for a selection of machines, it only takes a system ID. Therefore, "Check power" is not available in the action group in the machine list, and no changes will be seen here.
[MAASENG-2125]: https://warthogs.atlassian.net/browse/MAASENG-2125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(machines): Move "Check power" to power action dropdown MAASENG-2125

---

src/app/kvm/components/LXDVMsTable/LXDVMsTable.test.tsx
src/app/machines/views/MachineList/MachineListTable/constants.ts
src/app/tags/views/TagMachines/TagMachines.test.tsx

- set machine listing table to default to ascending sort direction
Fixes:  [lp#2042847](https://bugs.launchpad.net/maas/+bug/2042847)

fix(machines): default to ascending sort

---

package.json
yarn.lock

- use single testing-library/dom
- update testing-library/cypress
This resolves most act errors that are caused by incorrect testing-library/dom resolution.
Prior to this PR we had 2 versions installed
This can be verified by using `yarn why @testing-library/dom`
More information: https://github.com/testing-library/user-event/discussions/906#discussioncomment-2522468
```
=> Found "@testing-library/dom@9.3.0"
info Reasons this module exists
- "@testing-library#cypress" depends on it
- Hoisted from "@testing-library#cypress#@testing-library#dom"
- Hoisted from "@testing-library#react#@testing-library#dom"
```
Fixes:

test: use single testing-library/dom

---

package.json
renovate.json
yarn.lock

downgrade @sentry/browser to v5.30.0 (#4836)
- disable renovate for @sentry packages
- v5 is the last version fully compatible with self-hosted Sentry 9.1.2
Fixes:

fix: downgrade @sentry/browser to v5.30.0 (#4836) backport

---

cypress/e2e/with-users/base/navigation.spec.ts
src/app/base/components/AppSideNavigation/AppSideNavigation.test.tsx
src/app/base/components/AppSideNavigation/NavigationBanner/NavigationBanner.tsx

- Routed logo link to machine list page regardless of user type
Fixes: [MAASENG-2408](https://warthogs.atlassian.net/browse/MAASENG-2408)
[MAASENG-2408]: https://warthogs.atlassian.net/browse/MAASENG-2408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: route logo link to machine list page

---

src/app/base/components/SectionHeader/SectionHeader.tsx

- Updated tab instances to use bottom line
Fixes: [MAASENG-2406](https://warthogs.atlassian.net/browse/MAASENG-2406)
[MAASENG-2406]: https://warthogs.atlassian.net/browse/MAASENG-2406?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

style: update tab to use bottom line

---

src/app/kvm/components/KVMResourcesCard/KVMResourcesCard.test.tsx
src/app/kvm/components/KVMResourcesCard/KVMResourcesCard.tsx
src/app/kvm/components/KVMResourcesCard/_index.scss

- For LXD resources, replace machine table contextual menu with link to VMs tab
- Remove test checking for machine fetch on KVM resources
Using polong-ng as a backend:
Fixes [MAASENG-2412](https://warthogs.atlassian.net/browse/MAASENG-2412)
[MAASENG-2412]: https://warthogs.atlassian.net/browse/MAASENG-2412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(LXD): Link to VMs tab for single LXD hosts MAASENG-2412

---

src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.test.tsx
src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.tsx

- fix: machine status in the header lp#2044399
Fixes: lp#2044399
https://bugs.launchpad.net/maas/+bug/2044399

fix: machine status in the header lp#2044399

---

src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.test.tsx
src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.tsx

- fix: machine status in the header lp#2044399 (#5221)
Fixes:

fix: machine status in the header lp#2044399 (#5221) 3.4 backport

---

package.json
yarn.lock

- Upgraded @canonical/maas-react-components to v1.6.1

chore: bump @canonical/maas-react-components to v1.6.1

---

cypress/e2e/with-users/base/navigation.spec.ts
cypress/e2e/with-users/machines/actions.spec.ts
cypress/support/commands.ts

- test: fix cypress #5137
- update navigation selector
- update power menu selector
Fixes: https://github.com/canonical/maas-ui/issues/5137

test: fix cypress #5137

---

cypress/e2e/with-users/controllers/list.spec.ts
package.json
src/app/controllers/views/ControllerList/ControllerListHeader/ControllerListHeader.test.tsx
src/app/controllers/views/ControllerList/ControllerListHeader/ControllerListHeader.tsx
src/setupTests.ts
yarn.lock

- Upgraded `@canonical/maas-react-components` to v1.12.0
- Replaced `SectionHeader` with `MainToolbar` in `ControllerListHeader`
Fixes [MAASENG-2513](https://warthogs.atlassian.net/browse/MAASENG-2513)
[MAASENG-2513]: https://warthogs.atlassian.net/browse/MAASENG-2513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(controllers): use MainToolbar in ControllerListHeader MAASENG-2513

---

src/app/base/components/AppSidePanel/AppSidePanel.tsx
src/app/base/components/FormikFormContent/FormikFormContent.tsx

- fix: side panel fieldless forms spacing
- collapse content section when there's no content
Fixes:

fix: side panel fieldless forms spacing

---

.github/workflows/sitespeed.yml

This sets sitespeed.io action to be run on push to main/3.x branch instead of pull request close. This is consistent with how cypress tests are run.
- ci: run sitespeed on push
Fixes: https://github.com/canonical/maas-ui/issues/5235

ci: run sitespeed on push

---

src/app/kvm/views/KVMList/KVMList.test.tsx
src/app/kvm/views/KVMList/KVMListHeader/KVMListHeader.test.tsx
src/app/kvm/views/KVMList/KVMListHeader/KVMListHeader.tsx

- Replaced SectionHeader with MainToolbar in KVM list header
- Fixes [MAASENG-2516](https://warthogs.atlassian.net/browse/MAASENG-2516)
- Fixes [MAASENG-2517](https://warthogs.atlassian.net/browse/MAASENG-2517)
LXD
Virsh
LXD
Virsh
[MAASENG-2516]: https://warthogs.atlassian.net/browse/MAASENG-2516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MAASENG-2517]: https://warthogs.atlassian.net/browse/MAASENG-2517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(kvm): use MainToolbar on KVM list header MAASENG-2516

---

src/app/pools/views/Pools.tsx

- Replace MachineHeader with MainToolbar in pools list header
Fixes [MAASENG-2520](https://warthogs.atlassian.net/browse/MAASENG-2520)
[MAASENG-2520]: https://warthogs.atlassian.net/browse/MAASENG-2520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(pools): use MainToolbar on pools list header MAASENG-2520

---

src/app/subnets/views/SubnetsList/SubnetsControls/SubnetsControls.tsx
src/app/subnets/views/SubnetsList/SubnetsList.tsx
src/app/subnets/views/SubnetsList/SubnetsTable/SubnetsTable.test.tsx
src/app/subnets/views/SubnetsList/SubnetsTable/SubnetsTable.tsx

- Replaced SectionHeader with MainToolbar in subnets list
- Moved search bar from table to header
- Removed Row/Col wrapping on search bar
Fixes [MAASENG-2522](https://warthogs.atlassian.net/browse/MAASENG-2522)
[MAASENG-2522]: https://warthogs.atlassian.net/browse/MAASENG-2522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(subnets): use MainToolbar on subnets list header MAASENG-2522

---

src/app/zones/views/ZonesList/ZonesListHeader/ZonesListHeader.tsx

- Replaced SectionHeader with MainToolbar on Zones list
Fixes [MAASENG-2519](https://warthogs.atlassian.net/browse/MAASENG-2519)
[MAASENG-2519]: https://warthogs.atlassian.net/browse/MAASENG-2519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(zones): use MainToolbar on zones list header MAASENG-2519

---

src/scss/_vanilla-overrides.scss

- add bottom padding to the main toolbar
Fixes:

fix: main toolbar padding

---

src/app/images/views/ImageList/ImageListHeader/ImageListHeader.tsx

- Replaced SectionHeader in image list header with MainToolbar
Fixes [MAASENG-2521](https://warthogs.atlassian.net/browse/MAASENG-2521)
[MAASENG-2521]: https://warthogs.atlassian.net/browse/MAASENG-2521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(images): use MainToolbar on image list header MAASENG-2521

---

src/app/domains/views/DomainsList/DomainListHeader/DomainListHeader.tsx

- Replaced SectionHeader with MainToolbar on domains list header
Fixes [MAASENG-2523](https://warthogs.atlassian.net/browse/MAASENG-2523)
[MAASENG-2523]: https://warthogs.atlassian.net/browse/MAASENG-2523?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(domains): use MainToolbar on domains list header MAASENG-2523

---

src/app/base/components/SearchBox/SearchBox.tsx
src/app/machines/views/MachineList/MachineListControls/MachineListControls.tsx
src/app/machines/views/MachineList/MachineListHeader/MachineListHeader.test.tsx
src/app/machines/views/MachineList/MachineListHeader/MachineListHeader.tsx
src/app/machines/views/Machines.test.tsx

- Used MainToolbar to construct machine list controls
- Removed MachineHeader wrapping controls
- Added aria-label to SearchBox component
Fixes [MAASENG-2514](https://warthogs.atlassian.net/browse/MAASENG-2514)
[MAASENG-2514]: https://warthogs.atlassian.net/browse/MAASENG-2514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(machines): use MainToolbar in machine list header MAASENG-2514

---

cypress/constants.ts
src/app/intro/components/IntroCard/IntroCard.tsx

This improves a11y and fixes failures on intro pages by setting the intro card title as h1 (it's the main heading for each of these pages).
- fix: improve intro pages a11y
Fixes: https://github.com/canonical/maas-ui/issues/5271

fix: improve intro pages a11y

---

.github/workflows/playwright.yml

- ci: use node-version-file in playwright workflow
Fixes: https://github.com/canonical/maas-ui/actions/runs/7528576197/job/20491068356

ci: use node-version-file in playwright workflow

---

cypress/e2e/with-users/machines/details.spec.ts

- Added steps to add and delete a machine for subnet column visibility test
- Replaced label text assertion with role assertion for searchbox in commissioning details test

test: fix Cypress machine details tests

---

cypress/e2e/with-users/machines/list.spec.ts
cypress/support/commands.ts

- Fixed "can select a machine range" test
- Fixed button selector in machine add commands
This should also fix the machine actions test suite.

test: fix Cypress machine list tests

---

src/app/networkDiscovery/components/NetworkForm/NetworkForm.test.tsx
src/app/networkDiscovery/components/NetworkForm/NetworkForm.tsx
src/app/networkDiscovery/components/NetworkForm/index.ts
src/app/networkDiscovery/views/DiscoveriesList/DiscoveriesList.test.tsx
src/app/networkDiscovery/views/DiscoveriesList/DiscoveriesList.tsx
src/app/networkDiscovery/views/DiscoveryAddForm/DiscoveryAddFormFields/DiscoveryAddFormFields.tsx
src/app/networkDiscovery/views/DiscoveryDeleteForm/DiscoveryDeleteForm.test.tsx
src/app/networkDiscovery/views/DiscoveryDeleteForm/DiscoveryDeleteForm.tsx
src/app/networkDiscovery/views/DiscoveryDeleteForm/index.ts
src/app/networkDiscovery/views/NetworkDiscovery.tsx
src/app/networkDiscovery/views/NetworkDiscoveryHeader/ClearAllForm/ClearAllForm.tsx
src/app/networkDiscovery/views/constants.ts
src/app/store/utils/node/base.ts

- Moved add/delete discovery forms to sidepanel
Fixes: [Move Network Discovery forms to side panel](https://warthogs.atlassian.net/browse/MAASENG-2572)
###. Before

feat: move network discovery forms to sidepanel

---

src/app/tags/components/TagsHeader/DeleteTagForm/DeleteTagForm.test.tsx
src/app/tags/components/TagsHeader/DeleteTagForm/DeleteTagForm.tsx

- Updated message font size for tag deletion sidepanel

fix: update tag delete sidepanel font size

---

src/app/base/components/SSHKeyList/SSHKeyList.test.tsx
src/app/base/components/SSHKeyList/SSHKeyList.tsx
src/app/base/side-panel-context.tsx
src/app/intro/views/UserIntro/UserIntro.tsx
src/app/preferences/components/Routes/Routes.tsx
src/app/preferences/constants.ts
src/app/preferences/types.ts
src/app/preferences/urls.ts
src/app/preferences/views/SSHKeys/DeleteSSHKey/DeleteSSHKey.test.tsx
src/app/preferences/views/SSHKeys/DeleteSSHKey/DeleteSSHKey.tsx
src/app/preferences/views/SSHKeys/DeleteSSHKey/index.ts

- moved SSH Key delete form to sidepanel
Fixes: [MAASENG-2576](https://warthogs.atlassian.net/browse/MAASENG-2576)
[MAASENG-2576]: https://warthogs.atlassian.net/browse/MAASENG-2576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: move SSH Key delete form to sidepanel

---

.github/workflows/cypress.yml

This will allow testing changes to cypress workflow outside of main branches by using *cypress* branch name.
- ci: set cypress to run *cypress* branches
Fixes:

ci: run tests on *cypress* branches

---

src/app/base/sagas/http.ts
vite.config.ts

This moves external login to separate module.
It reduces the bundle size for users that use local authentication by ` 505.47 kB` 
`build/assets/canonicalMacaroonBakery-yGIenEOq.js                             505.47 kB │ gzip: 159.98 kB`
- build: optimize js bundle
- use dynamic import for @canonical/macaroon-bakery
```
state.externalAuthURL = "http://localhost:5240/login";
state.externalAuthURL = "http://localhost:5240/login";
```
Fixes: 
```
build/index.html                                                               2.63 kB │ gzip:   0.88 kB
build/assets/d5fc1819-UbuntuMono[wght]-latin-v0.869-dm70xBn2.woff2            31.24 kB
build/asset-manifest.json                                                     53.65 kB │ gzip:   4.77 kB …
```

build: optimize js bundle

---

src/app/tags/components/TagsHeader/TagsHeader.test.tsx
src/app/tags/components/TagsHeader/TagsHeader.tsx
src/app/tags/types.ts
src/app/tags/urls.ts
src/app/tags/views/Tags.test.tsx
src/app/tags/views/Tags.tsx

- fix: tags header update action button
- remove redundant tag view state logic
Fixes:

fix: tags header update action

---

src/app/base/components/MainContentSection/MainContentSection.test.tsx
src/app/base/components/MainContentSection/MainContentSection.tsx
src/app/base/components/NotificationList/NotificationList.test.tsx
src/app/base/components/NotificationList/NotificationList.tsx
src/app/base/components/PageContent/PageContent.tsx
src/app/store/message/selectors.test.ts
src/app/store/message/selectors.ts

- fix: settings preferences pages top padding
- refactor: remove redundant sidebar, isNotificationListHidden props
- refactor NotificationList
- add count selector to messages
Fixes:

fix: settings top padding

---

src/app/machines/components/MachineForms/MachineActionFormWrapper/DeployForm/DeployForm.tsx
src/app/machines/components/MachineForms/MachineActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.tsx

- Made sidepanel header sticky
- Removed unwanted `hr` and processing text from deploy form
Fixes: [MAASENG-2756](https://warthogs.atlassian.net/browse/MAASENG-2756)
[Screencast from 02-22-2024 10:14:12 AM.webm](https://github.com/canonical/maas-ui/assets/47540149/c18c74ad-b06d-4ab3-ac1f-0e815fdc1c5d)
[Screencast from 02-22-2024 10:16:54 AM.webm](https://github.com/canonical/maas-ui/assets/47540149/478a4e1b-a91f-4d0b-b6af-1e463774b81a)
[MAASENG-2756]: https://warthogs.atlassian.net/browse/MAASENG-2756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: update machine deploy form UI behavior

---

src/app/base/components/CertificateDownload/CertificateDownload.tsx

- fix: backport #5151 lxd certificate code block
Fixes: # . …

fix: backport #5151 lxd certificate code block

---

renovate.json

This PR configures renovate to group updates into categories, reducing the number of pull requests and making updates more manageable.
- chore: update renovate configuration with groups
Fixes:

chore: update renovate configuration with groups

---

src/app/machines/components/MachineForms/MachineActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.test.tsx
src/app/machines/components/MachineForms/MachineActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.tsx

- fix: kvm support message for virsh only lp#2053096
Fixes: https://bugs.launchpad.net/maas-ui/+bug/2053096
Fixes: https://bugs.launchpad.net/maas-ui/+bug/2054561

fix: kvm support message for virsh only lp#2053096

---

src/app/kvm/components/KVMForms/ComposeForm/ComposeForm.tsx
src/app/store/machine/reducers.test.ts
src/app/store/machine/slice.ts

This ensures we refetch machine list on compose success via `dispatch(machineActions.invalidateQueries());` and update the list immediately. It also adds `stale: false` to success actions to ensure consistent behaviour.
- fix: composing machine does not update list
Fixes: lp#1842524

fix: composing machine does not update list lp#1842524

---

run

- build(dotrun): remove start_django_db
- this is no longer relevant and code unused (no python files in the repository)
Fixes: 
https://code.launchpad.net/~javier-fs/maas/+git/maas/+merge/461382

build(dotrun): remove start_django_db

---

src/app/preferences/views/APIKeys/APIKeyDeleteForm/APIKeyDeleteForm.tsx
src/app/preferences/views/APIKeys/APIKeyList/APIKeyList.tsx

- Removed line showing "Deleted" notification every time an API key update was saved
- Added line to API key delete form to show "Deleted" notification on save
Fixes [MAASENG-2812](https://warthogs.atlassian.net/browse/MAASENG-2812)
[MAASENG-2812]: https://warthogs.atlassian.net/browse/MAASENG-2812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(prefs): Adding/editing API key no longer shows "Deleted" message MAASENG-2812

---

src/app/machines/components/MachineForms/MachineForms.tsx
src/app/machines/constants.ts
src/app/machines/views/MachineDetails/MachineStorage/ChangeStorageLayout/ChangeStorageLayout.test.tsx
src/app/machines/views/MachineDetails/MachineStorage/ChangeStorageLayout/ChangeStorageLayout.tsx
src/app/machines/views/MachineDetails/MachineStorage/ChangeStorageLayoutMenu/ChangeStorageLayoutMenu.tsx
src/app/store/utils/node/base.ts

- fix: change storage layout sidepanel MAASENG-2798
- close side panel on success
- set correct panel title
- refactor: rename constants to reflect node action
Fixes: MAASENG-2798

fix: change storage layout sidepanel MAASENG-2798

---

src/app/settings/views/Users/UserDelete/UserDelete.test.tsx
src/app/settings/views/Users/UserDeleteForm/UserDeleteForm.tsx
src/app/settings/views/Users/UsersList/UsersList.test.tsx
src/app/settings/views/Users/UsersList/UsersList.tsx

- Removed `useAddMessage` call in user list
- Changed deletion message in UserDeleteForm
Fixes [MAASENG-2797](https://warthogs.atlassian.net/browse/MAASENG-2797)
[MAASENG-2797]: https://warthogs.atlassian.net/browse/MAASENG-2797?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(users): Adding/editing user no longer shows "Deleted" message MAASENG-2797

---

src/app/preferences/views/SSLKeys/SSLKeyList/SSLKeyList.tsx

- Added condition for displaying message to ensure that it is only displayed when deleting
Fixes [MAASENG-2813](https://warthogs.atlassian.net/browse/MAASENG-2813)
[MAASENG-2813]: https://warthogs.atlassian.net/browse/MAASENG-2813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(prefs): Adding SSL key no longer shows "Removed" message MAASENG-2813

---

src/app/base/components/ModelActionForm/ModelActionForm.tsx
src/app/base/components/node/networking/NetworkTable/NetworkTable.test.tsx
src/app/base/components/node/networking/NetworkTable/NetworkTable.tsx
src/app/machines/components/MachineForms/MachineForms.tsx
src/app/machines/constants.ts
src/app/machines/types.ts
src/app/machines/views/MachineDetails/MachineNetwork/AddAliasOrVlan/AddAliasOrVlanFields/AddAliasOrVlanFields.tsx
src/app/machines/views/MachineDetails/MachineNetwork/EditAliasOrVlanForm/EditAliasOrVlanForm.tsx
src/app/machines/views/MachineDetails/MachineNetwork/EditBridgeForm/EditBridgeForm.tsx
src/app/machines/views/MachineDetails/MachineNetwork/EditInterface/EditInterface.test.tsx
src/app/machines/views/MachineDetails/MachineNetwork/EditInterface/EditInterface.tsx
src/app/machines/views/MachineDetails/MachineNetwork/EditPhysicalForm/EditPhysicalFields/EditPhysicalFields.tsx
src/app/machines/views/MachineDetails/MachineNetwork/EditPhysicalForm/EditPhysicalForm.tsx
src/app/machines/views/MachineDetails/MachineNetwork/MachineNetwork.tsx
src/app/machines/views/MachineDetails/MachineNetwork/MarkConnectedForm/MarkConnectedForm.test.tsx
src/app/machines/views/MachineDetails/MachineNetwork/MarkConnectedForm/MarkConnectedForm.tsx
src/app/machines/views/MachineDetails/MachineNetwork/MarkConnectedForm/index.ts
src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTableActions/NetworkTableActions.test.tsx
src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTableActions/NetworkTableActions.tsx
src/app/machines/views/MachineDetails/MachineNetwork/RemovePhysicalForm/RemovePhysicalForm.test.tsx
src/app/machines/views/MachineDetails/MachineNetwork/RemovePhysicalForm/RemovePhysicalForm.tsx
src/app/machines/views/MachineDetails/MachineNetwork/RemovePhysicalForm/index.ts
src/app/store/utils/node/base.ts

- Mark connected
- Edit Physical
- Add VLAN
- Remove Physical
Have all been moved to side panels
Fixes: [Dev: Display Edit physical, Remove bridge forms in a side panel](https://warthogs.atlassian.net/browse/MAASENG-2796)

feat: move machine details forms to side panel

---

src/app/base/components/node/StorageTables/AvailableStorageTable/AvailableStorageTable.test.tsx
src/app/base/components/node/StorageTables/AvailableStorageTable/AvailableStorageTable.tsx
src/app/base/components/node/StorageTables/AvailableStorageTable/BulkActions/BulkActions.test.tsx
src/app/base/components/node/StorageTables/AvailableStorageTable/BulkActions/BulkActions.tsx

- Enable name column on partitions table on side panel close
Fixes: [Dev: Enable name column after side panel is closed](https://warthogs.atlassian.net/browse/MAASENG-2799)

fix: enable name column on partitions table on side panel close

---

cypress/e2e/with-users/base/navigation.spec.ts
src/app/base/components/AppSideNavigation/AppSideNavItem/AppSideNavItem.tsx
src/app/base/components/AppSideNavigation/AppSideNavItems/AppSideNavItems.tsx
src/app/base/components/AppSideNavigation/AppSideNavigation.tsx
src/app/constants.ts

- Navigation will now collapse automatically when a link is clicked (on mobile)
- Added a cypress test to ensure this functionality
With a **desktop** viewport size:
With a **mobile** viewport size:
Fixes [MAASENG-2384](https://warthogs.atlassian.net/browse/MAASENG-2384)
[MAASENG-2384]: https://warthogs.atlassian.net/browse/MAASENG-2384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(nav): Nav collapses when links are clicked on mobile MAASENG-2384

---

.github/workflows/sitespeed.yml
sitespeed.io/login.js
sitespeed.io/scripts/machines.js

- ci: fix sitespeed workflow MAASENG-2671
- Replaced the manual MAAS installation and database setup steps with the canonical/setup-maas action
- Added steps to log in the MAAS admin user and wait for MAAS boot resources to finish importing.
- Removed the manual database dump download and restoration steps, as the setup-maas action handles this automatically.
- Updated the initial navigation URL from `/network-discovery` to `/`.
- Updated the selector used to check for the presence of 1000 machines in the machine list. The new selector ([data-testid="main-toolbar-heading"]) is likely a more robust way to locate the machine count element.
On top of this, [maas-ui-testing db-dumps](https://github.com/canonical/maas-ui-testing/tree/main) have been updated from maas-sampledata-dumper.
Fixes: …

ci: fix sitespeed workflow MAASENG-2671

---

src/app/kvm/components/CoreResources/_index.scss

- Fixed positioning of "CPU Cores" text in KVM resources cards
Fixes [MAASENG-2381](https://warthogs.atlassian.net/browse/MAASENG-2381)
[MAASENG-2381]: https://warthogs.atlassian.net/browse/MAASENG-2381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(kvm): KVM CPU resources label positioning MAASENG-2381

---

src/app/base/components/TableActionsDropdown/TableActionsDropdown.test.tsx
src/app/base/components/TableActionsDropdown/TableActionsDropdown.tsx
src/app/base/components/node/StorageTables/AvailableStorageTable/AddPartition/AddPartitionFields/AddPartitionFields.tsx
src/app/base/components/node/StorageTables/AvailableStorageTable/AvailableStorageTable.test.tsx
src/app/base/components/node/StorageTables/AvailableStorageTable/AvailableStorageTable.tsx
src/app/base/components/node/StorageTables/AvailableStorageTable/CreateCacheSet/CreateCacheSet.test.tsx
src/app/base/components/node/StorageTables/AvailableStorageTable/CreateCacheSet/CreateCacheSet.tsx
src/app/base/components/node/StorageTables/AvailableStorageTable/CreateCacheSet/index.ts
src/app/base/components/node/StorageTables/AvailableStorageTable/DeleteDisk/DeleteDisk.test.tsx
src/app/base/components/node/StorageTables/AvailableStorageTable/DeleteDisk/DeleteDisk.tsx
src/app/base/components/node/StorageTables/AvailableStorageTable/DeleteDisk/index.ts
src/app/base/components/node/StorageTables/AvailableStorageTable/EditDisk/EditDiskFields/EditDiskFields.tsx
src/app/base/components/node/StorageTables/AvailableStorageTable/SetBootDisk/SetBootDisk.test.tsx
src/app/base/components/node/StorageTables/AvailableStorageTable/SetBootDisk/SetBootDisk.tsx
src/app/base/components/node/StorageTables/AvailableStorageTable/SetBootDisk/index.ts
src/app/base/components/node/StorageTables/AvailableStorageTable/StorageDeviceActions/StorageDeviceActions.tsx
src/app/machines/components/MachineForms/MachineForms.tsx
src/app/machines/constants.ts
src/app/machines/types.ts
src/app/store/utils/node/base.ts

- Add Partition
- Create cache set
- Set boot disk
- Edit physical disk
- Remove physical disk
All moved to side panels
Fixes: [MAASENG-2856](https://warthogs.atlassian.net/browse/MAASENG-2856)
Inline forms that carry out operations on partitions instead of disks will be handled in a separate PR
[MAASENG-2856]: https://warthogs.atlassian.net/browse/MAASENG-2856?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: move non-partition collapsible forms to side panel

---

src/app/images/components/ImagesTable/ImagesTable.test.tsx
src/app/images/components/ImagesTable/ImagesTable.tsx

- fix: cannot delete image while downloading MAASENG-2863
- refactor ImagesTable.test.tsx and remove `describe`
Fixes: [lp#232057935](https://bugs.launchpad.net/maas-ui/+bug/2057935) MAASENG-2863

fix: cannot delete image while downloading MAASENG-2863

---

src/app/base/components/FormikForm/FormikForm.tsx
src/app/base/components/FormikFormButtons/FormikFormButtons.tsx
src/app/base/components/FormikFormContent/FormikFormContent.tsx
src/app/images/components/ImagesTable/ImagesTable.test.tsx
src/app/images/components/ImagesTable/ImagesTable.tsx
src/app/images/views/ImageList/SyncedImages/OtherImages/OtherImages.test.tsx
src/app/images/views/ImageList/SyncedImages/OtherImages/OtherImages.tsx
src/app/images/views/ImageList/SyncedImages/UbuntuCoreImages/UbuntuCoreImages.test.tsx
src/app/images/views/ImageList/SyncedImages/UbuntuCoreImages/UbuntuCoreImages.tsx
src/app/images/views/ImageList/SyncedImages/UbuntuImages/UbuntuImages.test.tsx
src/app/images/views/ImageList/SyncedImages/UbuntuImages/UbuntuImages.tsx

This PR fixes the issue where users cannot stop the importing of images. It also adds the buttonsBehavior prop to FormikForm and FormikFormButtons.
- fix: cannot stop importing images MAASENG-2864
- add buttonsBehavior to FormikForm and FormikFormButtons
- selected for download variant displayed with a correct number of columns
The buttonsBehavior prop determines the behavior of the primary and secondary submit buttons:
- "coupled" (default): The secondary submit button is disabled if the primary submit button is disabled.
- "independent": The secondary submit button's disabled state is controlled independently.
Fixes: MAASENG-2864 https://bugs.launchpad.net/maas/+bug/2057689
Button enabled as soon as request is made
Button is disabled when cancellation is in progress
correct number of …

fix: cannot stop importing images MAASENG-2864

---

src/app/images/views/ImageList/SyncedImages/ChangeSource/FetchImagesForm/FetchImagesFormFields/FetchImagesFormFields.tsx

- In the boot source page, the user has to base64 encode the content of the keyring data and submit the string. This PR aims to improve the placeholder text for that field. 
Fixes:

fix: improve boot source keyring data placeholder

---

src/app/App.tsx
src/app/base/components/Login/Login.test.tsx
src/app/base/components/Login/Login.tsx
src/testing/utils.tsx

fix: login error message spacing
- test: add login error message test
- test: refactor Login.test.tsx to use renderWithBrowserRouter
Fixes: MAASENG-2885

fix: login error message spacing MAASENG-2885

---

src/app/base/components/node/networking/NetworkTable/NetworkTable.tsx

- Changed "availaable" to "available" on empty machine network table
Fixes [MAASENG-2889](https://warthogs.atlassian.net/browse/MAASENG-2889)
[MAASENG-2889]: https://warthogs.atlassian.net/browse/MAASENG-2889?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(machines): Remove typo on empty network table MAASENG-2889

---

src/app/utils/formatErrors.test.ts
src/app/utils/formatErrors.ts

- fix: errors appear as json strings
- refactor error format functions for better clarity and conciseness
Fixes: MAASENG-2888 https://bugs.launchpad.net/maas-ui/+bug/1819628

fix: errors appear as json strings MAASENG-2888 lp#1819628

---

cypress/e2e/with-users/controllers/details.spec.ts
src/app/base/components/FormikFormContent/FormikFormContent.test.tsx
src/app/base/components/FormikFormContent/FormikFormContent.tsx
src/app/base/components/NodeActionMenuGroup/index.scss
src/app/base/components/SectionHeader/SectionHeader.test.tsx
src/app/base/components/SectionHeader/SectionHeader.tsx
src/app/base/components/SectionHeader/_index.scss
src/app/kvm/components/KVMDetailsHeader/_index.scss
src/app/kvm/components/LXDHostToolbar/_index.scss
src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.tsx
src/app/zones/views/ZoneDetails/ZoneDetailsHeader/ZoneDetailsHeader.test.tsx

- fix: layout header
- refactor SectionHeader to use MainToolbar internally
- fix: inline forms layout
- fixes node name edit forms layout when displayed in the title
Fixes: https://warthogs.atlassian.net/browse/MAASENG-2892

fix: header spacing and forms layout MAASENG-2892

---

src/app/base/components/node/StorageTables/FilesystemsTable/DeleteFilesystem/DeleteFilesystem.test.tsx
src/app/base/components/node/StorageTables/FilesystemsTable/DeleteFilesystem/DeleteFilesystem.tsx
src/app/base/components/node/StorageTables/FilesystemsTable/DeleteFilesystem/index.ts
src/app/base/components/node/StorageTables/FilesystemsTable/DeleteSpecialFilesystem/DeleteSpecialFilesystem.test.tsx
src/app/base/components/node/StorageTables/FilesystemsTable/DeleteSpecialFilesystem/DeleteSpecialFilesystem.tsx
src/app/base/components/node/StorageTables/FilesystemsTable/DeleteSpecialFilesystem/index.ts
src/app/base/components/node/StorageTables/FilesystemsTable/FilesystemsTable.test.tsx
src/app/base/components/node/StorageTables/FilesystemsTable/FilesystemsTable.tsx
src/app/base/components/node/StorageTables/FilesystemsTable/UnmountFilesystem/UnmountFilesystem.test.tsx
src/app/base/components/node/StorageTables/FilesystemsTable/UnmountFilesystem/UnmountFilesystem.tsx
src/app/base/components/node/StorageTables/FilesystemsTable/UnmountFilesystem/index.ts
src/app/machines/components/MachineForms/MachineForms.tsx
src/app/machines/constants.ts
src/app/machines/types.ts
src/app/store/utils/node/base.ts

Moved File system table forms to side panel
- Delete Filesystem
- Unmount Filesystem
- Delete special filesystem
Fixes: [MAASENG-2874](https://warthogs.atlassian.net/browse/MAASENG-2874)
[MAASENG-2874]: https://warthogs.atlassian.net/browse/MAASENG-2874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: move file system forms to side panel

---

src/app/controllers/views/ControllerList/ControllerListTable/ControllerListTable.tsx
src/app/controllers/views/ControllerList/ControllerListTable/_index.scss

- Remove Last Image Sync & Image status Column from controller list
Fixes: [lp#2058007](https://bugs.launchpad.net/maas-ui/+bug/2058007), [MAASENG-2896](https://warthogs.atlassian.net/browse/MAASENG-2896)
[MAASENG-2896]: https://warthogs.atlassian.net/browse/MAASENG-2896?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: remove synchronization status from controller list

---

src/app/base/components/node/PowerOffForm/PowerOffForm.test.tsx
src/app/store/machine/reducers.test.ts
src/app/store/machine/slice.ts

- fix: soft power off
```javascript
{
method: "machine.action"
params: {action: "off", extra: {stop_mode: "soft"}, filter: {id: ["[id]"], ... },}
}
```
Fixes: https://warthogs.atlassian.net/browse/MAASENG-2913
lp#2058662

fix: soft power off lp#2058662

---

src/app/images/components/ImagesTable/ImagesTable.test.tsx
src/app/images/components/ImagesTable/ImagesTable.tsx

- Enabled the delete button for queued for download
Fixes: [MAASENG-2909](https://warthogs.atlassian.net/browse/MAASENG-2909)
[MAASENG-2909]: https://warthogs.atlassian.net/browse/MAASENG-2909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: enable deletion of images queued for download

---

src/app/images/views/ImageList/SyncedImages/ChangeSource/FetchImagesForm/FetchImagesFormFields/FetchImagesFormFields.tsx
src/app/images/views/ImageList/SyncedImages/ChangeSource/FetchedImages/FetchedImages.tsx
src/scss/_patterns_application.scss

- fix: change source side panel lp#2058340
- wrap application layout overrides in l-application for higher specificity
Fixes:

fix: change source side panel lp#2058340

---

src/app/base/components/node/NodeLogs/NodeLogs.test.tsx
src/app/base/components/node/NodeLogs/NodeLogs.tsx
src/app/controllers/views/ControllerDetails/ControllerDetails.tsx
src/app/controllers/views/ControllerDetails/ControllerLogs/ControllerLogs.test.tsx
src/app/machines/views/MachineDetails/MachineLogs/MachineLogs.test.tsx

- Fixed broken routes for event logs and installation outputs in machine details
Machines
Controllers
Fixes [lp2060133](https://bugs.launchpad.net/maas/+bug/2060133)

fix(machines): Broken routes for machine and controller logs lp2060133

---

cypress/e2e/with-users/subnets/staticroutes.spec.ts

- test: update staticroutes.spec.ts
Fixes: https://github.com/canonical/maas-ui/issues/5386

test: update staticroutes.spec.ts

---

src/app/base/components/NodeSummaryNetworkCard/NodeSummaryNetworkCard.test.tsx
src/app/base/components/NodeSummaryNetworkCard/NodeSummaryNetworkCard.tsx

- fix: device details subnet on load
Fixes: https://warthogs.atlassian.net/browse/MAASENG-3036

fix: device details subnet on load MAASENG-3036

---

src/app/networkDiscovery/views/DiscoveriesList/DiscoveriesList.tsx

- fix: network discovery date truncation
This means that date might be displayed in 2 lines, but that works on this page as we are already displaying double rows (e.g. in the MAC address).
Fixes: https://warthogs.atlassian.net/browse/MAASENG-2991

fix: network discovery date truncation MAASENG-2991

---

src/app/subnets/views/VLANDetails/ConfigureDHCP/ConfigureDHCP.test.tsx
src/app/subnets/views/VLANDetails/ConfigureDHCP/ConfigureDHCP.tsx
src/app/subnets/views/VLANDetails/ConfigureDHCP/ConfigureDHCPFields/ConfigureDHCPFields.tsx
src/app/subnets/views/VLANDetails/DHCPStatus/DHCPStatus.test.tsx
src/app/subnets/views/VLANDetails/DHCPStatus/DHCPStatus.tsx
src/app/subnets/views/VLANDetails/EditVLAN/EditVLAN.tsx
src/app/subnets/views/VLANDetails/VLANActionForms/VLANActionForms.tsx
src/app/subnets/views/VLANDetails/VLANDetails.tsx
src/app/subnets/views/VLANDetails/VLANSummary/VLANSummary.test.tsx
src/app/subnets/views/VLANDetails/VLANSummary/VLANSummary.tsx
src/app/subnets/views/VLANDetails/constants.ts

Moved VLAN inline forms to side panel
- Edit VLAN
- Configure DHCP
Fixes: [MAASENG-2985](https://warthogs.atlassian.net/browse/MAASENG-2985)
[MAASENG-2985]: https://warthogs.atlassian.net/browse/MAASENG-2985?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: move VLAN inline forms to side panel

---

src/app/utils/formatErrors.test.ts
src/app/utils/formatErrors.ts

In some rare scenarios HTML content might be returned as a response. This change makes sure that we display text only and not entire raw HTML string.
- fix: html error formatting MAASENG-2935
HTML formatting is hard QA without simulating an actual nginx error and also already covered by tests. Focus on verifying that other errors are displayed as before.
- Attempt to login using incorrect credentials
- Ensure that login validation error is displayed correctly
Fixes: MAASENG-2935

fix: html error formatting MAASENG-2935

---

src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.tsx

- Fixed tab link highlighting for machine summary
Fixes [MAASENG-3035](https://warthogs.atlassian.net/browse/MAASENG-3035)

fix(machines): tab link highlighting on machine summary MAASENG-3035

---

src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.tsx

fix(machines): tab link highlighting on machine summary 3.5 backport

---

cypress/e2e/with-users/subnets/staticroutes.spec.ts
src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.tsx
src/app/subnets/components/DHCPSnippets/DHCPSnippets.tsx
src/app/subnets/components/ReservedRanges/ReservedRanges.tsx
src/app/subnets/urls.ts
src/app/subnets/views/SubnetDetails/StaticRoutes/StaticRoutes.tsx
src/app/subnets/views/SubnetDetails/SubnetDetails.test.tsx
src/app/subnets/views/SubnetDetails/SubnetDetails.tsx
src/app/subnets/views/SubnetDetails/SubnetDetailsHeader/SubnetDetailsHeader.tsx
src/app/subnets/views/SubnetDetails/SubnetSummary/SubnetSummary.tsx
src/app/subnets/views/SubnetDetails/SubnetUsedIPs/SubnetUsedIPs.tsx

- split up subnet details into separate routes
- added tab links for each route
- added urls for:
- summary
- static routes
- reserved ips
- dhcp snippets
- used ips
- ~~(drive-by fix) fixed summary tab highlighting on machine details~~
Fixes [MAASENG-2973](https://warthogs.atlassian.net/browse/MAASENG-2973)
[MAASENG-2973]: https://warthogs.atlassian.net/browse/MAASENG-2973?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(subnets): refactor subnet details into tabs MAASENG-2973

---

package.json
src/app/store/subnet/types/base.ts
src/app/subnets/views/SubnetDetails/StaticDHCPLease/StaticDHCPLease.tsx
src/app/subnets/views/SubnetDetails/StaticDHCPLease/StaticDHCPTable/StaticDHCPTable.test.tsx
src/app/subnets/views/SubnetDetails/StaticDHCPLease/StaticDHCPTable/StaticDHCPTable.tsx
src/app/subnets/views/SubnetDetails/StaticDHCPLease/StaticDHCPTable/index.ts
src/testing/factories/nodes.ts
src/testing/factories/subnet.ts
yarn.lock

- Added Static DHCP Lease table
A flag has been added to prevent this from showing in production (per the acceptance criteria). as a result, this should be tested in `dev`
Fixes: [MAASENG-2974](https://warthogs.atlassian.net/browse/MAASENG-2974)
The table height needs to be adjusted on MRC to take off excess white space between the tables as seen in the screenshot
[MAASENG-2974]: https://warthogs.atlassian.net/browse/MAASENG-2974?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add static dhcp table

---

src/app/store/subnet/hooks.ts
src/app/store/subnet/types/base.ts
src/app/subnets/views/SubnetDetails/StaticDHCPLease/StaticDHCPLease.test.tsx
src/app/subnets/views/SubnetDetails/StaticDHCPLease/StaticDHCPLease.tsx
src/app/subnets/views/SubnetDetails/SubnetDetails.tsx

- fix: reserved ips tree shaking
- update `StaticDHCPLease` type
- add required `subnetId` prop to `StaticDHCPLease`
This fixes Reserved IPs modules tree shaking and reduces the resulting production bundle size by 21KB (gzipped). 
| Before | After | Diff
| --- | --- | --- |
| `3267KB` | `3246KB` | `-21KB`
Fixes:

fix: reserved ips treeshaking

---

src/app/store/controller/slice.ts
src/app/store/device/slice.ts
src/app/store/domain/reducers.test.ts
src/app/store/domain/slice.ts
src/app/store/fabric/slice.ts
src/app/store/iprange/slice.ts
src/app/store/pod/slice.ts
src/app/store/space/slice.ts
src/app/store/subnet/slice.ts
src/app/store/utils/slice.ts
src/app/store/vlan/slice.ts

- refactor: add generateGetReducers util
- remove workarounds for error return type https://bugs.launchpad.net/maas/+bug/1931654
- refactor controller, device, iprange, pod, subnet, vlan, domain, iprange, space reducers
Fixes: MAASENG-3132
Error for domain that does not exist is still displayed correctly.

refactor: add generateGetReducers util MAASENG-3132 WIP

---

src/app/store/reservedip/reducers.test.ts
src/app/store/reservedip/slice.ts
src/app/subnets/views/SubnetDetails/StaticDHCPLease/ReserveDHCPLease/ReserveDHCPLease.test.tsx
src/app/subnets/views/SubnetDetails/StaticDHCPLease/ReserveDHCPLease/ReserveDHCPLease.tsx
src/app/subnets/views/SubnetDetails/StaticDHCPLease/StaticDHCPTable/StaticDHCPTable.test.tsx
src/app/subnets/views/SubnetDetails/StaticDHCPLease/StaticDHCPTable/StaticDHCPTable.tsx
src/app/subnets/views/SubnetDetails/SubnetActionForms/SubnetActionForms.tsx
src/scss/_utilities.scss

- Enabled "Edit" button on static dhcp lease table
- Added `updateSuccess` reducer
- Added `reservedIpId` prop to `ReserveDHCPLease` form
- `ReserveDHCPLease` form now pre-fills data when the above prop is provided
- Added a character counter and character limit to the add/edit form
Add the following lines to your `.env.local`:*
```
MAAS_URL = "http://nick-dv.ddns.net:5240/"
VITE_APP_STATIC_IPS_ENABLED = true
```
- Fixes [MAASENG-2976](https://warthogs.atlassian.net/browse/MAASENG-2976)
- Fixes [MAASENG-2984](https://warthogs.atlassian.net/browse/MAASENG-2984)
*Ping me when you're QAing so I can open the firewall port for you.
[MAASENG-2976]: https://warthogs.atlassian.net/browse/MAASENG-2976?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

feat(subnets): Edit reserved IPs MAASENG-2976 & MAASENG-2984

---

src/app/machines/views/MachineDetails/MachineConfiguration/TagForm/TagForm.tsx
src/app/store/subnet/selectors.ts
src/app/subnets/views/VLANDetails/DHCPStatus/DHCPStatus.tsx

- refactor: fix selector memoization warning
```
stderr | src/app/subnets/views/VLANDetails/DHCPStatus/DHCPStatus.test.tsx > shows a spinner if data is loading
Selector unknown returned a different result when called with the same parameters. This can lead to unnecessary rerenders.
Selectors that return a new reference (such as an object or an array) should be memoized: https://redux.js.org/usage/deriving-data-selectors#optimizing-selectors-with-memoization
```
Fixes:

refactor: fix selector memoization warning

---

src/app/base/components/AppSideNavigation/AppSideNavigation.test.tsx
src/app/store/pod/selectors.ts

- refactor: pod selectors caching

refactor: pod selectors caching

---

src/app/base/components/DHCPTable/DHCPTable.tsx
src/app/machines/views/MachineDetails/MachineConfiguration/TagForm/TagForm.tsx
src/app/subnets/views/VLANDetails/VLANDetails.tsx

- fix: DHCPTable, TagForm, VLANDetails selectors
This pull request fixes the selectors in the DHCPTable, TagForm, and VLANDetails components.
In VLANDetails.tsx, the call to subnetSelectors.getByIds has been updated to pass null instead of an empty array when vlan?.subnet_ids is falsy.
In TagForm.tsx, the events array is now prevented from being re-created on every render.
Fixes:

fix: DHCPTable, TagForm, VLANDetails selectors

---

.eslintrc.cjs
package.json
src/app/base/components/ActionForm/ActionForm.tsx
src/app/base/components/node/networking/NetworkTable/NetworkTable.tsx
src/app/kvm/utils.ts
src/app/machines/components/MachineForms/MachineForms.tsx
src/app/store/pod/types/base.ts
src/app/store/utils/node/base.ts
yarn.lock

- refactor: decrease complexity of ActionForm, NetworkTable, MachineForms
- add eslint-plugin-complexity
- add complexity lint rule with max of 25
This is related to TICS checks and intends to improve the overall score for maas-ui.

refactor: decrease complexity of ActionForm, NetworkTable, MachineForms

---

.github/workflows/test.yml

- test: add coverage report upload step
I mistakenly removed this step before making final changes to the workflow; unfortunately testing workflows before merge is not straightforward.

test: add coverage report upload step

---

.github/workflows/links-checker.yml

- ci: fix links checker
This adds `push` instead of `branches` directly under `on`

ci: fix links checker workflow

---

src/app/controllers/components/ControllerForms/ControllerActionFormWrapper/ControllerActionFormWrapper.tsx
src/app/store/controller/selectors.ts

- refactor: controller statusSelectors)
- cache controllerSystemIds
Fixes:

refactor: controller statusSelectors

---

src/__snapshots__/root-reducer.test.ts.snap
src/app/base/components/StatusBar/StatusBar.test.tsx
src/app/base/components/StatusBar/StatusBar.tsx
src/app/store/msm/index.ts
src/app/store/msm/selectors.ts
src/app/store/msm/slice.ts
src/app/store/msm/types/base.ts
src/app/store/msm/types/enum.ts
src/app/store/root/types.ts
src/app/store/utils/slice.ts
src/root-reducer.ts
src/testing/factories/index.ts
src/testing/factories/msm.ts
src/testing/factories/state.ts
src/testing/utils.tsx
yarn.lock

- feat: show msm connection info
- update strip-literal to 2.1.0 - fixes https://github.com/vitest-dev/vitest/issues/5387#issuecomment-2027845454
- add rerender with state updates in renderWithMockStore using immer `produce`.
- add `immer` as a dev dependency
https://www.figma.com/design/R4sX8oUJp1NWDg1t8o6YDr/Image-provisioning?node-id=519-27497&t=ywqadFRRtX1d9D8I-0
```tsx
{
type: 'msm/fetchSuccess',
payload: {
'sm-url': null,
'start-time': null,
running: 'connected'
}
}
```
Fixes: [MAASENG-2897](https://github.com/petermakowski/maas-ui/tree/feat-show-msm-connection-info-MAASENG-2897)
[MAASENG-2897]: https://warthogs.atlassian.net/browse/MAASENG-2897?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: show msm connection info

---

.github/workflows/test.yml
.github/workflows/upload.yml

- chore: update upload workflow top match `main`
- replace dotrun with build in the test workflow
Verified that the upload build workflow works on a separate branch (without actual upload step): https://github.com/canonical/maas-ui/actions/runs/9567406570

chore: update upload workflow

---

src/app/settings/views/Repositories/RepositoryForm/RepositoryForm.test.tsx
src/app/settings/views/Repositories/RepositoryForm/RepositoryForm.tsx
src/app/utils/index.ts
src/app/utils/parseCommaSeparatedValues.test.ts
src/app/utils/parseCommaSeparatedValues.ts

- Fix values spacing when adding a package repository
- update the parsing logic to correctly split the values and remove any leading or trailing spaces
This fixes an issue where the MAAS UI incorrectly parses comma-separated distributions and components when adding a new package repository.
Fixes: #5464
1. Go to Settings->Package Repos->Add Repository
2. For both the Distributions and Components sections, enter any values separated with commas (e.g. `focal, jammy, noble` or `focal,jammy,noble`)
3. Click Save Repository
4. Inspecting the WS request sent to MAAS and ensure the list  is `["focal", "jammy", "noble"]`

fix(settings): fix list spacing #5464

---

.github/workflows/pr-lint.yml

- chore: Add scopes to PR lint workflow
Fixes: https://warthogs.atlassian.net/browse/MAASENG-3414
- Verify that PR lint failed for `chore(invalid-scope)` https://github.com/canonical/maas-ui/actions/runs/9593881088/job/26455264222?pr=5473
[MA201 - Conventional commits](https://docs.google.com/document/d/1_bX6y_XnZHw0p5QgPZV-_lm-6wr-LyM2Vd_DO4V2IsI/edit#heading=h.833o1m6v1nlg)

chore: Add scopes to PR lint workflow MAASENG-3414

---

src/websocket-client.ts

- Updated WebSocket reconnection logic to limit message backlog
Fixes: https://bugs.launchpad.net/maas/+bug/2070304
https://warthogs.atlassian.net/browse/MAASENG-3433
N/A
This change introduces a `maxEnqueuedMessages` limit to prevent overwhelming the server with a backlog of messages upon WebSocket reconnection. The limit is set to 30, which accommodates the typical 5-25 messages generated on page load plus some buffer for additional user actions.

fix: limit WebSocket message backlog on reconnection

---

src/app/api/base.test.ts

- Added test case for invalid CSRF token scenario in `base.test.ts`

test: add invalid CSRF token test case

---

src/websocket-client.ts

Backport of https://github.com/canonical/maas-ui/pull/5487

fix: limit WebSocket message backlog on reconnection 3.5 backport

---

src/websocket-client.ts

Backport of https://github.com/canonical/maas-ui/pull/5487

fix: limit WebSocket message backlog on reconnection 3.4 backport

---

src/app/base/components/PrefixedIpInput/index.ts
src/app/base/components/PrefixedIpInput/utils.test.ts
src/app/base/components/PrefixedIpInput/utils.ts
src/app/devices/components/DeviceHeaderForms/AddDeviceForm/AddDeviceForm.test.tsx
src/app/devices/components/DeviceHeaderForms/AddDeviceForm/AddDeviceForm.tsx
src/app/devices/components/DeviceHeaderForms/AddDeviceForm/AddDeviceInterfaces/AddDeviceInterfaces.test.tsx
src/app/devices/components/DeviceHeaderForms/AddDeviceForm/AddDeviceInterfaces/AddDeviceInterfaces.tsx
src/app/devices/components/DeviceHeaderForms/AddDeviceForm/types.ts
src/app/subnets/views/SubnetDetails/StaticDHCPLease/ReserveDHCPLease/ReserveDHCPLease.tsx

- Created `formatIpAddress` util
- Moved `AddDeviceInterface` form fields to its own component
- Integrated `PrefixedIpInput` field when "Static" IP assignment is selected
- Only show IP field when a subnet has been selected (static only)
- Added validation for IPv4 and IPv6 addresses
Fixes [MAASENG-2982](https://warthogs.atlassian.net/browse/MAASENG-2982)
- Pre-filling the form based on MAC address has been de-scoped, since one MAC can theoretically have multiple assigned IPs across subnets
- Showing an error if an entered IP is reserved has been de-scoped, since multiple subnets with the same CIDR can exist on separate VLANs (the same IP could be reserved on one, but available on the other).
[MAASENG-2982]: https://warthogs.atlassian.net/browse/MAASENG-2982?atlOrigin=eyJpIjoiNWRkNTljNzYx …

feat(devices): Integrate dynamic IP validation with "Add Device" form MAASENG-2982

---

package.json
src/app/api/base.test.ts
src/app/api/base.ts
src/app/api/endpoints.ts
src/app/api/query/zones.test.ts
src/testing/utils.tsx
yarn.lock

- test: add msw library for mocking API requests
Fixes: https://warthogs.atlassian.net/browse/MAASENG-3402

test: add msw library for mocking API requests

---

src/app/subnets/views/SubnetDetails/StaticDHCPLease/StaticDHCPTable/StaticDHCPTable.tsx

- Added tooltips to the "comments" column of the static DHCP leases table
You'll need a backend that has the websocket model for reserved IPs - I have one up and running, ping me if you want to use it
Fixes [MAASENG-3517](https://warthogs.atlassian.net/browse/MAASENG-3517)
[MAASENG-3517]: https://warthogs.atlassian.net/browse/MAASENG-3517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(subnets): add tooltips for reserved IP comments MAASENG-3517

---

src/app/base/components/MacAddressField/MacAddressField.tsx
src/app/machines/components/MachineForms/AddMachine/AddMachineFormFields/AddMachineFormFields.tsx
src/app/utils/formatMacAddress.test.ts
src/app/utils/formatMacAddress.ts

- Removed length limit for MAC address inputs
(With a backend that supports reserved IPs)
Fixes [MAASENG-3518](https://warthogs.atlassian.net/browse/MAASENG-3518)
[MAASENG-3518]: https://warthogs.atlassian.net/browse/MAASENG-3518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: remove length limit for MAC address fields MAASENG-3518

---

src/app/subnets/views/SubnetDetails/StaticDHCPLease/ReserveDHCPLease/ReserveDHCPLease.tsx

- "Reserve static DHCP lease" form will now check if an IP is:
- Already reserved
- In use by another node
Make sure you have a backend that supports reserved IPs (ping me if you need one)
Fixes [MAASENG-3516](https://warthogs.atlassian.net/browse/MAASENG-3516)
[Design](https://www.figma.com/design/bX9XqdURp0pOX3ujuD5WpB/Reserved-IPs?node-id=197-141403&t=JuvoXjFcfGGAsRhK-4)
[MAASENG-3516]: https://warthogs.atlassian.net/browse/MAASENG-3516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(subnets): show error message if IP is already reserved/used MAASENG-3516

---

src/app/base/components/FormikFormContent/FormikFormContent.test.tsx
src/app/base/components/FormikFormContent/FormikFormContent.tsx
src/setupTests.ts

- When a non-field (i.e. backend) error is received after submitting a form, the error message will now automatically be scrolled into view
Fixes [MAASENG-3515](https://warthogs.atlassian.net/browse/MAASENG-3515)
[MAASENG-3515]: https://warthogs.atlassian.net/browse/MAASENG-3515?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: scroll to top of form when non-field errors are present MAASENG-3515

---

src/app/base/components/NetworkActionRow/NetworkActionRow.tsx
src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTableActions/NetworkTableActions.tsx

- Increased side panel width for:
- "Create bond" form
- "Create bridge" form
- "Edit bond" form
Fixes [lp2073575](https://bugs.launchpad.net/maas-ui/+bug/2073575)

fix(machines): Increase width of bond and bridge forms in Network tab

---

docs/HACKING.md

- remove old setup instructions with dotenv
- add setup instructions for yarn/vite
- add test running instruction
- move site speed test running to fitting section
- link to maas-dev-setup repo instead of manual instructions how to setup a dev env
- go through the instructions under `# Development setup` and see if you can use them to setup a MAAS UI
- test if the updated TOC still works in the rendered (html) version of `HACKING.md` here in github
Not needed, see the file here: https://github.com/tmerten/maas-ui/blob/71fe0627eedf9e4bd5cfc79388c6e7fc296e2efe/docs/HACKING.md#set-up-a-development-container
This file needs more updating but this update should already help new users to set up and running more quickly.

docs: update HACKING.md with current descriptions

---

src/app/subnets/components/ReservedRangeForm/ReservedRangeForm.test.tsx
src/app/subnets/components/ReservedRangeForm/ReservedRangeForm.tsx

- Integrated `PrefixedIpInput` into the "Reserve Range" and "Reserve Dynamic Range" forms
Fixes [MAASENG-3524](https://warthogs.atlassian.net/browse/MAASENG-3524)
[MAASENG-3524]: https://warthogs.atlassian.net/browse/MAASENG-3524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(subnets): Use PrefixedIpInput in Reserve Range form MAASENG-3524

---

docs/LXD.md

- Created a tutorial for setting up MAAS in a LXD container
- This includes setting up the host machine to be a KVM host in MAAS
Fixes [MAASENG-3601](https://warthogs.atlassian.net/browse/MAASENG-3601)
[MAASENG-3601]: https://warthogs.atlassian.net/browse/MAASENG-3601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: Add tutorial for setting up MAAS in a LXD container MAASENG-3601

---

.env
docs/HACKING.md

- Removed references to `bolla.internal` (RIP) and updated default MAAS backend to `maas-ui-demo.internal`
Fixes [MAASENG-3597](https://warthogs.atlassian.net/browse/MAASENG-3597)
*At the time of writing, `maas-ui-demo.internal` is not running fully, it appears to be in the midst of updating.
[MAASENG-3597]: https://warthogs.atlassian.net/browse/MAASENG-3597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: update default MAAS backend in .env MAASENG-3597

---

src/app/api/query/base.test.ts
src/app/api/query/base.ts
src/app/api/query/zones.ts
src/testing/utils.tsx

- fix(zones): unnecessary query invalidations and API calls
- refactor: invalidate queries only when connectedCount changes
- refactor: add zoneKeys
Fixes:

fix(zones): unnecessary query invalidations and API calls

---

.github/ISSUE_TEMPLATE/ci-failure.md

The "about" (i.e. the description property, see
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms#top-level-syntax) cannot be blank.
- fix issue template
- needs to be run in CI
Fixes: 
The issue template but does not fix the timeout issue we're having in CI (see e.g. [this run](https://github.com/tmerten/maas-ui/actions/runs/10217065720/job/28270004040)). 
(FYI: The timeout is set to 60 seconds, so the problem seems to be unrelated to the timeout.)

ci: fix issue template

---

src/app/machines/views/MachineDetails/MachineNetwork/EditPhysicalForm/EditPhysicalForm.test.tsx
src/app/machines/views/MachineDetails/MachineNetwork/EditPhysicalForm/EditPhysicalForm.tsx
src/app/machines/views/MachineDetails/MachineNetwork/NetworkFields/NetworkFields.tsx

- Added `PrefixedIpInput` to the "Edit Physical" form
- Added subnet-based IP validation to the form schema
Resolves [MAASENG-3453](https://warthogs.atlassian.net/browse/MAASENG-3453)
[MAASENG-3453]: https://warthogs.atlassian.net/browse/MAASENG-3453?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(machines): Add new IP address field to Edit Physical form MAASENG-3453

---

.github/workflows/test.yml

This pull request introduces a new CI workflow that adds TICS GitHub Action. This will execute TICS analysis on push to main and upload the generated artifacts to our TICS Dashboard: https://canonical.tiobe.com/tiobeweb/TICS/
-  add TICS workflow with artifact upload
Fixes: https://warthogs.atlassian.net/browse/MAASENG-3399
This currently fails with "Error: There was an error retrieving last QServer run date: HTTP request failed with status 400. Requested project not found: maas-ui".

ci: add TICS workflow with artifact upload MAASENG-3276

---

.github/workflows/test.yml

- ci: set tics full report artifact path
Fixes:

ci: set tics full report artifact path

---

package.json
yarn.lock

- Upgraded playwright to v1.45
This is needed in order for Playwight to be able to install its dependencies on 24.04. See issue thread [here](https://github.com/microsoft/playwright/issues/30368)

chore(deps): Upgrade @playwright/test to 1.45

---

src/app/machines/views/MachineList/MachineListTable/GroupCheckbox/GroupCheckbox.test.tsx
src/app/machines/views/MachineList/MachineListTable/GroupCheckbox/GroupCheckbox.tsx

- Selecting a group of machines:
- adds the system IDs of (visible) machines in that group to the selection state, instead of the group key
- does NOT select every machine in that group, only the ones on screen
- Machines in a selected group can now be unselected
_I recommend doing this using a MAAS instance with a good amount of sample data._
Resolves [MAASENG-3720](https://warthogs.atlassian.net/browse/MAASENG-3720)
Resolves [LP:2056157](https://bugs.launchpad.net/maas-ui/+bug/2056157)
[MAASENG-3720]: https://warthogs.atlassian.net/browse/MAASENG-3720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(machines): Allow deselection of machines in a selected group MAASENG-3720

---

src/app/base/components/node/OverviewCard/DetailsCard/DetailsCard.test.tsx
src/app/base/components/node/OverviewCard/DetailsCard/DetailsCard.tsx

- Added kernel crash dump state indicator to machine details
```env
VITE_APP_KERNEL_CRASH_DUMP_ENABLED = true
```
Fixes [MAASENG-3760](https://warthogs.atlassian.net/browse/MAASENG-3760)
[MAASENG-3760]: https://warthogs.atlassian.net/browse/MAASENG-3760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(machines): Add kernel crash dump indicator to details page MAASENG-3760

---

src/app/machines/components/MachineForms/MachineActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.test.tsx
src/app/machines/components/MachineForms/MachineActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.tsx

- Added kernel crash dump checkbox to machine deploy form
```env
VITE_APP_KERNEL_CRASH_DUMP_ENABLED = true
```
Resolves [MAASENG-3759](https://warthogs.atlassian.net/browse/MAASENG-3759)
*This is because these tests are set to skip if the feature flag is not present, which is the case in CI.
[MAASENG-3759]: https://warthogs.atlassian.net/browse/MAASENG-3759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(machines): Add kernel crash dump checkbox to deploy form MAASENG-3759

---

src/app/store/reservedip/types/base.ts
src/app/subnets/views/SubnetDetails/StaticDHCPLease/ReserveDHCPLease/ReserveDHCPLease.test.tsx
src/app/subnets/views/SubnetDetails/StaticDHCPLease/ReserveDHCPLease/ReserveDHCPLease.tsx

- make the MAC address of a reserved IP required and immutable
- create a reserved IP -> ensure that the MAC address is required
- modify the reserved IP -> ensure the text box of the MAC address is disabled

feat(subnets): make the MAC address of a reserved IP required and immutable MAASENG-3914

---

src/app/base/components/IpAssignmentSelect/IpAssignmentSelect.tsx
src/app/machines/views/MachineDetails/MachineNetwork/NetworkFields/NetworkFields.tsx

- Added help text about reserving IP addresses to the IP mode field in:
- Add device
- Add network discovery
- Add/Edit device interface
- Add/Edit machine interface
Help text: _"To manage static DHCP leases for a [machine/device], go to the address reservation tab of a subnet."_
Fixes:

feat: Add help text for reserving static IPs to IP mode fields MAASENG-3911

---

src/app/images/views/ImageList/SyncedImages/ChangeSource/FetchImagesForm/FetchImagesFormFields/FetchImagesFormFields.tsx

- Edited the placeholder text, changing it from "e.g. /usr/share/keyrings/ubuntu-clooudimage-keyring.gpg" to "e.g. /usr/share/keyrings/ubuntu-cloudimage-keyring.gpg"
- navigate to the Change Source dialogue for custom images
- click on "advanced"
- verify the placeholder text is correct
Fixes: 
https://bugs.launchpad.net/maas-ui/+bug/2085803

style: Fixed trivial spelling error in keyring placeholder text

---

src/app/machines/components/MachineForms/MachineActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.test.tsx
src/app/machines/components/MachineForms/MachineActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.tsx
src/app/settings/views/Configuration/KernelParametersForm/KernelParametersForm.test.tsx
src/app/settings/views/Configuration/KernelParametersForm/KernelParametersForm.tsx

- Tooltips showing the minimum Ubuntu version for enabling kernel crash dumps now say "Tested with" before the version number.

fix: Add "Tested with" before Ubuntu version in kernel crash dump OS requirement tooltips

---

src/app/machines/views/MachineDetails/MachineConfiguration/PowerForm/PowerForm.test.tsx
src/app/store/general/utils/powerTypes.ts
src/app/utils/index.ts
src/app/utils/isValidPortNumber.test.ts
src/app/utils/isValidPortNumber.ts

- Added extra validation steps to IP address power field to account for ports
- Removed IP validation from LXD and Virsh address fields as these can be hostnames or other non-IP-address things.
Fixes [LP#2087965](https://bugs.launchpad.net/maas/+bug/2087965)
Fixes [MAASENG-4172](https://warthogs.atlassian.net/browse/MAASENG-4172)
[MAASENG-4172]: https://warthogs.atlassian.net/browse/MAASENG-4172?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(machines): Allow ports at the end of IPMI addresses LP#2087965

---

README.md

- Regenerated badges for GH actions
- Actual status of action should be reflected
- Badges should now all link to the appropriate job
- driveby: add badge for docs link checker
Cypress and docs links checker are failing for real, unfortunately.

docs: Update badge links in readme to reflect true action status

---

src/app/api/query-client.ts

- Removed some placeholder comments that accidentally got merged
Fixes:

chore: clean up comments around react query code

---

src/app/store/bootresource/utils.test.ts
src/app/store/bootresource/utils.ts

- Set "custom" as the fallback for images that do not have the "os/release" naming format

fix(images): Fallback as custom image when splitting OS from resource name

---

src/app/zones/views/ZonesList/ZonesList.tsx

- Re-introduced the force refetch to invalidate the zones list properly

fix(zones): re-added force refetch to refresh the tables on form action

---

src/app/base/docsUrls.ts
tests/docs-links.spec.ts

- Updated docs link for IP ranges
- Added verbose error message for redirects

fix: update docs link for IP ranges

---

.github/workflows/coverage.yaml

- Removed `ci-tics-main` from coverage workflow trigger

ci: remove tics debug branch from workflow trigger

---

.github/workflows/links-checker.yml
src/app/base/docsUrls.ts

- Updated link for IP ranges
- Updated link for network discovery
- Changed links checker schedule to run at 5am UTC instead of 2pm UTC (so it's up to date before we all log on)
- Run links checker on push to branches that begin with `fix-docs-links-`

fix: update docs links for ip ranges and network discovery

---

.github/workflows/coverage.yaml

- Changed runner to `ubuntu-22.04` from `ubuntu-latest`
- Removed branch specification 
Fixes: 
-  `ubuntu-latest` recently changed to 24.04, which currently as a bug causing runs to be aborted for no apparent reason
- specifying branch to `main` causes a branch named 'main' not found error in TiCS analysis step

ci: fix tics analysis action

---

package.json
src/app/images/components/ImagesForms/SelectUpstreamImagesForm/SelectUpstreamImagesSelect/SelectUpstreamImagesSelect.test.tsx
src/app/images/components/ImagesForms/SelectUpstreamImagesForm/SelectUpstreamImagesSelect/_index.scss
yarn.lock

- Upgraded `@canonical/react-components` to `2.1.0`
- `MultiSelect` component changes were resolved to maintain the same look and test functionality
- Migrated `SelectUpstreamImagesSelect` tests to `renderWithProviders`
Resolves: 
[MAASENG-4478](https://warthogs.atlassian.net/browse/MAASENG-4478)
[MAASENG-4478]: https://warthogs.atlassian.net/browse/MAASENG-4478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(deps): Update MAAS UI react-components v2 MAASENG-4478

---

src/app/api/query/sshKeys.ts
src/app/api/query/zones.ts
src/app/base/components/FormikFormContent/FormikFormContent.tsx
src/app/base/components/SSHKeyForm/SSHKeyForm.test.tsx
src/app/base/components/SSHKeyForm/SSHKeyForm.tsx
src/app/base/components/SSHKeyForm/SSHKeyFormFields/SSHKeyFormFields.test.tsx
src/app/preferences/views/SSHKeys/AddSSHKey/AddSSHKey.test.tsx
src/testing/resolvers/sshKeys.ts

- Created hooks for adding + importing SSH keys
- Created mock resolvers for adding + importing SSH keys
- Use query hooks instead of redux actions in SSH key form
- (drive-by) Removed unnecessary `Partial` of options types in zones mutation hooks
Resolves [MAASENG-4448](https://warthogs.atlassian.net/browse/MAASENG-4448)
[MAASENG-4448]: https://warthogs.atlassian.net/browse/MAASENG-4448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(preferences): Migrate SSH key form to API v3 MAASENG-4448

---

src/app/api/query/sshKeys.test.ts
src/app/api/query/sshKeys.ts
src/app/base/components/ModelActionForm/ModelActionForm.tsx
src/app/base/components/SSHKeyForm/SSHKeyForm.tsx
src/app/base/components/SSHKeyForm/types.ts
src/app/preferences/types.ts
src/app/preferences/views/SSHKeys/DeleteSSHKey/DeleteSSHKey.test.tsx
src/app/preferences/views/SSHKeys/DeleteSSHKey/DeleteSSHKey.tsx
src/testing/resolvers/sshKeys.ts

- Migrated SSH key delete form to API v3
- Added missing tests for ssh key query hooks
- Delete form now fetches IDs from side panel context instead of URL parameters
- Created mock resolver for SSH key deletion
- Added generic type props to ModelActionForm to support v3 API errors
Resolves [MAASENG-4449](https://warthogs.atlassian.net/browse/MAASENG-4449)
[MAASENG-4449]: https://warthogs.atlassian.net/browse/MAASENG-4449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(preferences): Migrate SSH key deletion to API v3 MAASENG-4449

---

src/app/base/components/GenericTable/GenericTable.tsx
src/app/base/components/GenericTable/_index.scss
src/app/images/components/ImagesTable/useImageTableColumns/useImageTableColumns.tsx

- Added tooltip for delete icon in Images Table
- Aligned header text starting from "Release title" to the text "Ubuntu" in header belowe
Resolves [MAASENG-4360](https://warthogs.atlassian.net/browse/MAASENG-4360)
[MAASENG-4360]: https://warthogs.atlassian.net/browse/MAASENG-4360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(images): Implement design for image table MAASENG-4360

---

package.json
src/app/App.tsx
yarn.lock

- Bumped `@sentry/browser` to 7.119.1
- Replaced the deprecated `Sentry.Severity.Warning` enum with hardcoded string `"warning"` (https://github.com/getsentry/sentry-javascript/issues/7700)
Resolves: 
[MAASENG-4533](https://warthogs.atlassian.net/browse/MAASENG-4533)
Closes:
https://github.com/canonical/maas-ui/pull/5545
[MAASENG-4533]: https://warthogs.atlassian.net/browse/MAASENG-4533?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(deps): Bump @sentry/browser to 7.119.1

---

src/app/zones/views/ZonesList/ZonesListTable/AddZone/AddZone.test.tsx
src/app/zones/views/ZonesList/ZonesListTable/AddZone/AddZone.tsx
src/app/zones/views/ZonesList/ZonesListTable/DeleteZone/DeleteZone.test.tsx
src/app/zones/views/ZonesList/ZonesListTable/DeleteZone/DeleteZone.tsx
src/app/zones/views/ZonesList/ZonesListTable/EditZone/EditZone.test.tsx
src/app/zones/views/ZonesList/ZonesListTable/EditZone/EditZone.tsx
src/testing/resolvers/zones.ts

- Passed errors to form components in:
- AddZone
- DeleteZone
- EditZone
- Added error resolvers for all zone mutations
Resolves [MAASENG-4541](https://warthogs.atlassian.net/browse/MAASENG-4541)
[MAASENG-4541]: https://warthogs.atlassian.net/browse/MAASENG-4541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(zones): Show error messages for zone mutations MAASENG-4541

---

src/app/images/components/ImagesForms/SelectUpstreamImagesForm/SelectUpstreamImagesForm.test.tsx
src/app/images/components/ImagesForms/SelectUpstreamImagesForm/SelectUpstreamImagesSelect/SelectUpstreamImagesSelect.test.tsx
src/app/images/components/ImagesForms/SelectUpstreamImagesForm/SelectUpstreamImagesSelect/SelectUpstreamImagesSelect.tsx
src/app/settings/views/Images/ChangeSource/ChangeSourceFields/ChangeSourceFields.tsx
vitest.config.ts

- Switched the `SelectUpstreamImagesSelect` OS accordions to Vanilla.js `Accordion` for standard styling
- Moved "Automatically sync images" checkbox to the left of the label in `ChangeSourceFields`
- Fixed broken tests, added cases for improved coverage
- Added `lcov` reporter and had `cobertura` output reports to the gitignored coverage directory
Resolves: 
[MAASENG-4536](https://warthogs.atlassian.net/browse/MAASENG-4536)
Addresses:
[Images QA design](https://www.figma.com/design/VKK278yUxba3xGGxigTsrY/MAAS-Image-provisioning-QA?node-id=109-550&t=mdQFKM49Nzrh7tfd-4)
[MAASENG-4536]: https://warthogs.atlassian.net/browse/MAASENG-4536?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(images): Images QA MAASENG-4536

---

sitespeed.io/scripts/machines.js

- Fixed import for `utils.js` in `machines.js`
Fixes:

fix: use correct relative import for utils in sitespeed machine test

---

.github/workflows/coverage.yaml
vitest.config.ts
yarn.lock

- Reverted TiCS cobertura coverage report output directory to .coverage/
- (drive-by) yarn.lock update for the playwright downgrade (https://github.com/canonical/maas-ui/pull/5650)

ci: set correct TiCS coverage directory

---

.github/workflows/pr-lint.yml
package.json
src/hey-api.ts

- Changed `baseUrl` of API client to `/` 
- Changed `PROXY_PORT` to 8400 in static demo serve
- (drive-by) Allowed "api" as a commit message scope

fix(api): use '/' as the baseUrl for the API client

---

docs/MAASUI.md

- Added TanStack Query section to explain the current implementation
- Updated the diagram to include TanStack Query
- Added a note stating the intending deprecation of web sockets and migration to TanStack Query
Resolves: 
[MAASENG-3598](https://warthogs.atlassian.net/browse/MAASENG-3598)
[MAASENG-3599](https://warthogs.atlassian.net/browse/MAASENG-3599)
[MAASENG-3598]: https://warthogs.atlassian.net/browse/MAASENG-3598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MAASENG-3599]: https://warthogs.atlassian.net/browse/MAASENG-3599?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: Explain React Query implementation in MAASUI.md MAASENG-3598

---

src/app/base/components/DebounceSearchBox/_index.scss
src/app/base/components/FilterAccordion/_index.scss
src/app/base/components/NotificationGroup/_index.scss
src/app/base/components/TableMenu/_index.scss
src/app/base/components/node/OverviewCard/_index.scss
src/app/base/components/node/networking/NetworkTable/_index.scss
src/app/devices/views/DeviceDetails/DeviceNetwork/DeviceNetworkTable/_index.scss
src/app/kvm/components/VmResources/_index.scss
src/app/machines/views/MachineDetails/MachineSummary/NumaCard/_index.scss
src/app/settings/components/SettingsTable/_index.scss
src/app/subnets/views/SubnetDetails/SubnetActionForms/components/EditBootArchitectures/BootArchitecturesTable/_index.scss
src/scss/_patterns_double-row.scss
src/scss/_patterns_forms.scss
src/scss/_patterns_grids.scss
src/scss/_patterns_typography.scss
src/scss/_pseudo-border.scss
src/scss/_settings.scss
src/scss/_utilities.scss
vite.config.ts

- Silenced SASS deprecation warnings coming from dependencies in `vite.config.ts`
- Resolved in-project deprecation warnings
- Silenced all import warnings as per the [Vanilla JS Discourse post](https://discourse.canonical.com/t/how-to-deal-with-sass-deprecation-warnings-with-vanilla/5243)
Resolves: 
[MAASENG-4549](https://warthogs.atlassian.net/browse/MAASENG-4549)
[MAASENG-4549]: https://warthogs.atlassian.net/browse/MAASENG-4549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Disable SASS errors for dependencies MAASENG-4549

---

src/app/api/query/pools.test.ts
src/app/api/query/pools.ts
src/app/api/query/zones.test.ts
src/app/api/query/zones.ts
src/app/base/components/GenericTable/ColumnHeader/ColumnHeader.tsx
src/app/base/components/GenericTable/ColumnHeader/index.ts
src/app/base/components/GenericTable/GenericTable.test.tsx
src/app/base/components/GenericTable/GenericTable.tsx
src/app/base/components/GenericTable/PaginationBar/ControlsBar/ControlsBar.tsx
src/app/base/components/GenericTable/PaginationBar/PaginationBar.tsx
src/app/base/components/GenericTable/TableCheckbox/TableCheckbox.test.tsx
src/app/base/components/GenericTable/TableCheckbox/TableCheckbox.tsx
src/app/base/components/GenericTable/TableHeader/index.ts
src/app/base/components/GenericTable/_index.scss
src/app/base/constants.ts
src/app/base/hooks/useDebouncedValue/useDebouncedValue.ts
src/app/base/hooks/usePagination/usePagination.ts
src/app/images/components/ImagesTable/ImagesTable.tsx
src/app/pools/components/PoolsTable/PoolsTable.tsx
src/app/pools/components/PoolsTable/usePoolsTableColumns/usePoolsTableColumns.test.tsx
src/app/pools/components/PoolsTable/usePoolsTableColumns/usePoolsTableColumns.tsx
src/app/zones/views/ZonesList/ZonesListTable/ZonesListTable.tsx
src/app/zones/views/ZonesList/ZonesListTable/useZonesTableColumns/useZonesTableColumns.tsx

- Added pagination support to `GenericTable`
- Implemented pagination for `PoolsTable`
- Fixed unique key and validateDOM warnings for `GenericTable`
- Fixed the mixed select bug for `TableCheckbox.All`
- Fixed `usePoolCount` and `useZoneCount` hooks to use `data.total`, instead of the paginated `data.items.length`
Resolves: 
[MAASENG-4588](https://warthogs.atlassian.net/browse/MAASENG-4588)
[MAASENG-4588]: https://warthogs.atlassian.net/browse/MAASENG-4588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(base): Add pagination to GenericTable MAASENG-4588

---

src/app/images/components/ImagesForms/SelectUpstreamImagesForm/SelectUpstreamImagesSelect/_index.scss

- fix image table placeholder so that is has max width (so that adding more architectures wouldn't push it outside of frame)
Fixes: [MAASENG-4628](https://warthogs.atlassian.net/jira/software/c/projects/MAASENG/boards/1423?selectedIssue=MAASENG-4628)
[MAASENG-4628](https://warthogs.atlassian.net/jira/software/c/projects/MAASENG/boards/1423?selectedIssue=MAASENG-4628)
[MAASENG-4628]: https://warthogs.atlassian.net/browse/MAASENG-4628?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MAASENG-4628]: https://warthogs.atlassian.net/browse/MAASENG-4628?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: fix image table placeholder to have max width

---

.github/workflows/accessibility.yml
.github/workflows/cypress.yml
.github/workflows/links-checker.yml
.github/workflows/playwright.yml

- Added step to most actions to tell it to use the NodeJS version from .nvmrc
- This should fix the accessibility action, as that now requires NodeJS >= v20 (previously using v18)

ci: use nodejs version from nvmrc in all actions that require node

---

src/app/api/query/sslKeys.test.ts
src/app/api/query/sslKeys.ts
src/app/preferences/views/SSLKeys/DeleteSSLKey/DeleteSSLKey.test.tsx
src/app/preferences/views/SSLKeys/DeleteSSLKey/DeleteSSLKey.tsx
src/testing/resolvers/sslKeys.ts

- updated DeleteSSLKey, DeleteSSLKey.test to use API v3 with creating and updating pools
- updated sslKeys.ts  and sslKeys.test.ts in app/api/query
- updated sslKeys.ts in resolvers
Resolves [MAASENG-4623](https://warthogs.atlassian.net/browse/MAASENG-4623)
[MAASENG-4623](https://warthogs.atlassian.net/browse/MAASENG-4623)
[MAASENG-4623]: https://warthogs.atlassian.net/browse/MAASENG-4623?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MAASENG-4623]: https://warthogs.atlassian.net/browse/MAASENG-4623?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(preferences): migrate delete ssl keys to API v3 MAASENG 4623

---

src/app/base/components/GenericTable/GenericTable.test.tsx
src/app/base/components/GenericTable/GenericTable.tsx
src/app/base/components/GenericTable/_index.scss
src/app/images/components/ImagesTable/ImagesTable.tsx
src/app/images/components/ImagesTable/useImageTableColumns/useImageTableColumns.tsx
src/app/pools/components/PoolsTable/PoolsTable.tsx
src/app/zones/views/ZonesList/ZonesList.test.tsx
src/app/zones/views/ZonesList/ZonesListTable/ZonesListTable.tsx

- Made table body scrollable
- Removed `DynamicTable` import, incorporated fully
- Added dynamic height sizing
- Added loading state and skeleton rows
- Refactored code, added accessibility attributes
Resolves: 
[MAASENG-4718](https://warthogs.atlassian.net/browse/MAASENG-4718)
With this PR, GenericTable can be evaluated for upstreaming to https://github.com/canonical/maas-react-components
[MAASENG-4718]: https://warthogs.atlassian.net/browse/MAASENG-4718?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(base): Add sticky header to GenericTable MAASENG-4718

---

src/app/machines/components/MachineForms/AddMachine/AddMachineForm/AddMachineForm.test.tsx
src/app/machines/components/MachineForms/AddMachine/AddMachineFormFields/AddMachineFormFields.tsx
src/app/machines/views/MachineDetails/MachineConfiguration/MachineForm/MachineForm.test.tsx
src/app/machines/views/MachineDetails/MachineConfiguration/MachineForm/MachineForm.tsx

- added help tooltip for DPU field in "Add Machine" form
- improved display of `is_dpu` value in machine configuration
[Design](https://www.figma.com/design/48QccxasITNNR6OsFOANXz/MAAS-DPU-deployment?node-id=11-30281&t=TBqBHei8c6etFY4M-0)

fix: DPU QA fixes

---

src/app/base/components/NodeActionMenuGroup/NodeActionMenuGroup.test.tsx
src/app/base/components/NodeActionMenuGroup/NodeActionMenuGroup.tsx
src/app/machines/views/MachineList/MachineListControls/MachineListControls.test.tsx

- added condition that if machine is DPU don't show Power on/off button
- changed tests accordingly to new condition
Fixes: [MAASENG-3947](https://warthogs.atlassian.net/browse/MAASENG-3947)
[MAASENG-3947]: https://warthogs.atlassian.net/browse/MAASENG-3947?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: remove power on/off if DPU MAASENG-3947

---

src/app/base/hooks/base.test.tsx
src/app/base/hooks/base.ts

- Ignored keyboard events from textarea elements in `useGlobalKeyShortcut`
- Added tests for `useGlobalKeyShortcut` and `useOnKeyPressed`

fix(base): prevent keypress from focusing searchbox if a textarea is focused

---

.gitignore
src/app/api/query/packageRepositories.test.ts
src/app/api/query/packageRepositories.ts
src/app/settings/views/Repositories/components/AddRepository/AddRepository.test.tsx
src/app/settings/views/Repositories/components/AddRepository/AddRepository.tsx
src/app/settings/views/Repositories/components/DeleteRepository/DeleteRepository.test.tsx
src/app/settings/views/Repositories/components/DeleteRepository/DeleteRepository.tsx
src/app/settings/views/Repositories/components/DeleteRepository/index.ts
src/app/settings/views/Repositories/components/EditRepository/EditRepository.test.tsx
src/app/settings/views/Repositories/components/EditRepository/EditRepository.tsx
src/app/settings/views/Repositories/components/EditRepository/index.ts
src/app/settings/views/Repositories/components/RepositoryFormFields/RepositoryFormFields.test.tsx
src/app/settings/views/Repositories/components/RepositoryTable/index.ts
src/app/settings/views/Repositories/components/RepositoryTable/useRepositoriesTableColumns.tsx
src/app/settings/views/Repositories/components/index.ts
src/app/settings/views/Repositories/utils.ts
src/app/settings/views/Repositories/views/RepositoriesList.tsx
src/testing/resolvers/packageRepositories.ts
src/testing/utils.tsx

- Created mutation hook for repo delete
- Created mock resolver for repo delete
- Migrated repo delete form to API v3
Resolves [MAASENG-4959](https://warthogs.atlassian/net/browse/MAASENG-4959)
[MAASENG-4959]: https://warthogs.atlassian.net/browse/MAASENG-4959?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(settings): Migrate package repo delete to API v3 MAASENG-4959

---

README.md

- fixed status link for CI chip in readme

fix: add missing 'l' to link in CI chip in readme

---

src/app/images/components/ImagesForms/SelectUpstreamImagesForm/SelectUpstreamImagesForm.tsx

- Added a filter-out empty return when parsing selected images

fix(images): Filter out empty selections in SelectUpstreamImagesForm onSubmit

---

src/app/devices/views/DeviceDetails/DeviceNetwork/DeviceNetwork.test.tsx
src/app/devices/views/DeviceDetails/DeviceNetwork/DeviceNetworkTable/DeviceNetworkTable.test.tsx
src/app/devices/views/DeviceDetails/DeviceNetwork/DeviceNetworkTable/DeviceNetworkTable.tsx
src/app/devices/views/DeviceDetails/DeviceNetwork/DeviceNetworkTable/useDeviceNetworkTableColumns/useDeviceNetworkTableColumns.tsx

- Converted DeviceNetworkTable to GenericTable
- Migrated tests to use `renderWithProviders`
Resolves [MAASENG-5211](https://warthogs.atlassian.net/browse/MAASENG-5211)
*the descending order is interpreted differently by tanstack table compared to our internal functions - tanstack puts letters first, internally we put numbers first. I think we should follow the tanstack convention here for simplicity.
[MAASENG-5211]: https://warthogs.atlassian.net/browse/MAASENG-5211?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(devices): Convert DeviceNetworkTable to GenericTable MAASENG-5211

---

.github/workflows/coverage.yaml
src/app/base/components/AppSidePanel/AppSidePanel.tsx
src/app/base/components/PageContent/PageContent.tsx
src/app/base/components/SidePanel/SidePanel.tsx
src/app/base/components/SidePanel/index.ts
src/app/base/side-panel-context-new.tsx
src/app/base/side-panel-context.tsx
src/app/preferences/views/SSHKeys/components/AddSSHKey/AddSSHKey.test.tsx
src/app/preferences/views/SSHKeys/components/AddSSHKey/AddSSHKey.tsx
src/app/preferences/views/SSHKeys/components/DeleteSSHKey/DeleteSSHKey.test.tsx
src/app/preferences/views/SSHKeys/components/DeleteSSHKey/DeleteSSHKey.tsx
src/app/preferences/views/SSHKeys/components/SSHKeysTable/SSHKeysTable.test.tsx
src/app/preferences/views/SSHKeys/components/SSHKeysTable/SSHKeysTable.tsx
src/app/preferences/views/SSHKeys/components/SSHKeysTable/useSSHKeysTableColumns/useSSHKeysTableColumns.tsx
src/app/preferences/views/SSHKeys/views/SSHKeysList.test.tsx
src/app/preferences/views/SSHKeys/views/SSHKeysList.tsx
src/app/preferences/views/SSLKeys/components/AddSSLKey/AddSSLKey.test.tsx
src/app/preferences/views/SSLKeys/components/AddSSLKey/AddSSLKey.tsx
src/app/preferences/views/SSLKeys/components/DeleteSSLKey/DeleteSSLKey.test.tsx
src/app/preferences/views/SSLKeys/components/DeleteSSLKey/DeleteSSLKey.tsx
src/app/preferences/views/SSLKeys/components/SSLKeysTable/SSLKeysTable.test.tsx
src/app/preferences/views/SSLKeys/components/SSLKeysTable/SSLKeysTable.tsx
src/app/preferences/views/SSLKeys/components/SSLKeysTable/useSSLKeysTableColumns/useSSLKeysTableColumns.tsx
src/app/preferences/views/SSLKeys/views/SSLKeysList.test.tsx
src/app/preferences/views/SSLKeys/views/SSLKeysList.tsx
src/index.tsx
src/testing/utils.tsx

- Created 'side-panel-context-new.tsx*
- Migrated SSH and SSL key tables
- Added new provider to 'renderWithProviders'
- Removed no longer applicable tests
Resolves:
[MAASENG-5227](https://warthogs.atlassian.net/browse/MAASENG-5227)
[MAASENG-5227]: https://warthogs.atlassian.net/browse/MAASENG-5227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Generic side panel context MAASENG-5227

---

.github/pull_request_template.md
src/app/intro/views/UserIntro/UserIntro.tsx

- Fixed `inProgress` button state in user intro skip confirmation
- The button should now be enabled and clickable when the confirmation is first shown, instead of showing a spinner
Resolves [MAASENG-5201](https://warthogs.atlassian.net/browse/MAASENG-5201)
[MAASENG-5201]: https://warthogs.atlassian.net/browse/MAASENG-5201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(intro): User intro cannot be skipped MAASENG-5201

---

src/app/subnets/components/ReservedRanges/ReservedRanges.test.tsx
src/app/subnets/components/ReservedRanges/ReservedRanges.tsx
src/app/subnets/components/ReservedRanges/useReservedRangesColumns/useReservedRangesColumns.tsx

- Refactored the original ```MainTable``` in ```ReservedRanges.tsx``` to ```GenericTable```.
- Created a custom hook (```useReservedRangesColumns```) for generating table columns.
- Updated ```ReservedRanges.test.tsx``` to reflect the component refactoring:
- Some tests were incorrectly querying elements by their accessible name (e.g. using column headers like ```Labels.Type```, ```Labels.Owner``` etc.). The accessible name of a ```<td>``` should only reflect its content (e.g. for ```<td>Value here</td>``` the accessible name should be "Value here"), so the tests now assert against the cell’s actual value instead. [Read more here](https://developer.mozilla.org/en-US/docs/Glossary/Accessible_name).
- Changed ```render(...)``` to ```renderWithProviders(...)```.
For subnets, first navigate …

refactor(subnets): use GenericTable for ReservedRanges Table MAASENG-5280

---

src/app/images/components/SelectUpstreamImagesForm/SelectUpstreamImagesForm.tsx

- Excluded unsupported archs from image form options
Resolves [MAASENG-5391](https://warthogs.atlassian.net/browse/MAASENG-5391)
[MAASENG-5391]: https://warthogs.atlassian.net/browse/MAASENG-5391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(images): Filtered out unsupported archs per image MAASENG-5391

---

src/app/base/components/node/StorageTables/FilesystemsTable/FilesystemsTable.test.tsx
src/app/base/components/node/StorageTables/FilesystemsTable/FilesystemsTable.tsx
src/app/base/components/node/StorageTables/FilesystemsTable/useFilesystemsTableColumns/useFileSystemsTableColumns.tsx
src/app/zones/components/ZonesTable/ZonesTable.test.tsx

- Refactored FilesystemsTable to use GenericTable
- Added table row representation type for joined fields
- Fixed tests
Resolves [MAASENG-5261](https://warthogs.atlassian.net/browse/MAASENG-5261)
[MAASENG-5261]: https://warthogs.atlassian.net/browse/MAASENG-5261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(base): FilesystemsTable to GenericTable MAASENG-5261

---

src/app/App.tsx

- Made the AppStatus render conditional depending on the authentication status
Resolves [MAASENG-5419](https://warthogs.atlassian.net/browse/MAASENG-5419)
[MAASENG-5419]: https://warthogs.atlassian.net/browse/MAASENG-5419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(base): Make AppStatus render conditional on authentication MAASENG-5419
