canonical/maas-ui

ui/package.json
ui/src/App.test.js
ui/src/setupTests.js

Add Enzyme and configure with Jest.
QA: none, CI should pass.
Fixes: https://github.com/canonical-web-and-design/maas-squad/issues/1229

Set up Enzyme

---

package.json
ui/package.json
ui/src/scss/base.scss
yarn.lock

QA:
- load the demo, the text should be the Ubuntu font.
Fixes: https://github.com/canonical-web-and-design/MAAS-squad/issues/1207

Add Vanilla

---

ui/package.json
ui/src/index.js
ui/src/root-reducer.js

Done:
- Connect the router to redux state.
QA:
- load the app and check that the router state exists in the redux store.

Connect router

---

ui/.env.development
ui/.env.production

These commas shouldn't be here!

Fix erroneous env commas.

---

ui/src/app/base/components/Button/Button.js
ui/src/app/base/components/Col/Col.js
ui/src/app/base/components/Col/Col.test.js
ui/src/app/base/components/Col/__snapshots__/Col.test.js.snap
ui/src/app/base/components/Col/index.js
ui/src/app/base/components/Field/Field.js
ui/src/app/base/components/Field/Field.test.js
ui/src/app/base/components/Row/Row.js
ui/src/app/base/components/Row/Row.test.js
ui/src/app/base/components/Row/__snapshots__/Row.test.js.snap
ui/src/app/base/components/Row/index.js
ui/src/app/base/components/Section/Section.js
ui/src/app/base/components/Section/__snapshots__/Section.test.js.snap
ui/src/app/settings/components/Nav/Nav.js
ui/src/app/settings/components/UserForm/UserForm.js
ui/src/app/settings/components/UserForm/__snapshots__/UserForm.test.js.snap
ui/src/app/settings/containers/Users/Users.js

Done:
- Add an add user button.
- Make cancel go back.
- Add Row and Col components.
Fixes: #46.
QA:
- Visit /users.
- Click "Add user", you should go to the user form.
- Click "Cancel", you should go back.

Add user navigation

---

ui/src/app/base/components/Col/Col.js
ui/src/app/base/components/Col/index.js
ui/src/app/base/components/List/List.js
ui/src/app/base/components/List/List.test.js
ui/src/app/base/components/List/__snapshots__/List.test.js.snap
ui/src/app/base/components/List/index.js
ui/src/app/base/components/Section/Section.js
ui/src/app/base/components/Section/__snapshots__/Section.test.js.snap
ui/src/app/base/components/Strip/Strip.js
ui/src/app/base/components/Strip/Strip.test.js
ui/src/app/base/components/Strip/__snapshots__/Strip.test.js.snap
ui/src/app/base/components/Strip/index.js
ui/src/app/base/hooks.js
ui/src/app/settings/components/Routes/Routes.js
ui/src/app/settings/containers/User/User.js
ui/src/app/settings/containers/User/User.test.js
ui/src/app/settings/containers/User/__snapshots__/User.test.js.snap
ui/src/app/settings/containers/User/index.js
ui/src/app/settings/containers/Users/Users.js
ui/src/app/settings/selectors/users.js
ui/src/app/settings/selectors/users.test.js

Done:
- Added user details. Fixes: https://github.com/canonical-web-and-design/maas-squad/issues/1351.
- Added strip and list components.
QA:
- open /users
- click on a user
- you should see some details

Add user details

---

ui/src/app/base/components/FormikField/FormikField.js
ui/src/app/base/components/FormikField/__snapshots__/FormikField.test.js.snap
ui/src/app/settings/components/ProxyFormFields/ProxyFormFields.js
ui/src/app/settings/components/ProxyFormFields/ProxyFormFields.test.js
ui/src/app/settings/components/ProxyFormFields/__snapshots__/ProxyFormFields.test.js.snap
ui/src/app/settings/components/ProxyFormFields/index.js
ui/src/app/settings/containers/Network/Network.js
ui/src/app/settings/containers/Network/Network.test.js
ui/src/app/settings/containers/Network/__snapshots__/Network.test.js.snap
ui/src/app/settings/containers/ProxyForm/ProxyForm.js
ui/src/app/settings/containers/ProxyForm/ProxyForm.test.js
ui/src/app/settings/containers/ProxyForm/index.js
ui/src/app/settings/selectors/config.js
ui/src/app/settings/selectors/config.test.js
yarn.lock

- Created Network and ProxyForm components
- Added config selectors for proxy-related things
- Added url validation to proxy url
- Go to /MAAS/settings/network
- Check that the proxy form loads in
- Check that clicking "External" or "Peer" displays a text input below
- Check that validation for the proxy url works (i.e. error message shows if url invalid or empty, save button doesn't work)
- Check that the save button shows an alert with the correct values
Fixes canonical-web-and-design/MAAS-squad#1394

Create Network component with Proxy section

---

ui/src/app/base/components/Loader/Loader.scss
ui/src/app/base/components/Section/Section.scss
ui/src/app/settings/components/Nav/Nav.scss
ui/src/app/settings/components/UserForm/UserForm.scss
ui/src/app/settings/containers/Users/Users.js
ui/src/app/settings/containers/Users/Users.scss
ui/src/app/settings/containers/Users/Users.test.js
ui/src/scss/_patterns_table.scss
ui/src/scss/base.scss

Done:
- Show a delete confirmation when deleting user from the user list. Fixes: https://github.com/canonical-web-and-design/maas-squad/issues/1354. Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/53.
QA:
- View the list of users.
- Click the delete icon next to a user.
- A confirmation should appear.
- Click cancel, it should disappear.

Add a delete confirm to the user list

---

ui/src/app/base/components/MainTable/MainTable.js
ui/src/app/base/components/MainTable/MainTable.test.js
ui/src/app/base/components/SearchBox/SearchBox.js
ui/src/app/base/components/SearchBox/SearchBox.test.js
ui/src/app/base/components/SearchBox/__snapshots__/SearchBox.test.js.snap
ui/src/app/base/components/SearchBox/index.js
ui/src/app/settings/containers/Users/Users.js
ui/src/app/settings/containers/Users/Users.test.js
ui/src/app/settings/selectors/users.js
ui/src/app/settings/selectors/users.test.js
ui/src/scss/_patterns_table-actions.scss
ui/src/scss/_patterns_table.scss
ui/src/scss/base.scss

Done:
- Add search filtering to the user table. Fixes: https://github.com/canonical-web-and-design/MAAS-squad/issues/1368.
QA:
- Open the list of users.
- Type a username or email address into the searchbox.
- The user list should get filtered.

Search users

---

ui/README.md

Update the setup instructions in the README based on feedback from people that have been using it
Read through and see that it makes sense

update setting up instructions based on feedback

---

ui/src/app/settings/components/Routes/Routes.js
ui/src/app/settings/containers/Configuration/KernelParameters/KernelParameters.js
ui/src/app/settings/containers/Configuration/KernelParameters/KernelParameters.test.js
ui/src/app/settings/containers/Configuration/KernelParameters/index.js
ui/src/app/settings/containers/Configuration/KernelParametersForm/KernelParametersForm.js
ui/src/app/settings/containers/Configuration/KernelParametersForm/KernelParametersForm.test.js
ui/src/app/settings/containers/Configuration/KernelParametersForm/index.js
ui/src/app/settings/containers/Configuration/KernelParametersFormFields/KernelParametersFormFields.js
ui/src/app/settings/containers/Configuration/KernelParametersFormFields/KernelParametersFormFields.test.js
ui/src/app/settings/containers/Configuration/KernelParametersFormFields/index.js
ui/src/app/settings/selectors/config.js
ui/src/app/settings/selectors/config.test.js

Created kernel parameters form
- Go to /settings/configuration/kernel-parameters
- Change the value of the form field and submit the form
- See that the value persists

Create kernel parameters component

---

ui/src/app/base/components/Select/Select.js
ui/src/app/settings/containers/Network/DnsForm/DnsForm.js
ui/src/app/settings/containers/Network/DnsForm/DnsForm.test.js
ui/src/app/settings/containers/Network/DnsFormFields/DnsFormFields.js
ui/src/app/settings/containers/Network/DnsFormFields/DnsFormFields.test.js
ui/src/app/settings/containers/Network/DnsFormFields/index.js
ui/src/app/settings/containers/Network/NetworkDiscoveryForm/NetworkDiscoveryForm.js
ui/src/app/settings/containers/Network/NetworkDiscoveryFormFields/NetworkDiscoveryFormFields.js
ui/src/app/settings/containers/Network/NetworkDiscoveryFormFields/NetworkDiscoveryFormFields.test.js
ui/src/app/settings/containers/Network/NetworkDiscoveryFormFields/index.js
ui/src/app/settings/containers/Network/NtpForm/NtpForm.js
ui/src/app/settings/containers/Network/NtpForm/NtpForm.test.js
ui/src/app/settings/containers/Network/NtpFormFields/NtpFormFields.js
ui/src/app/settings/containers/Network/NtpFormFields/NtpFormFields.test.js
ui/src/app/settings/containers/Network/NtpFormFields/index.js
ui/src/app/settings/containers/Network/ProxyFormFields/ProxyFormFields.js
ui/src/app/settings/containers/Network/ProxyFormFields/__snapshots__/ProxyFormFields.test.js.snap
ui/src/app/settings/containers/Network/SyslogForm/SyslogForm.js
ui/src/app/settings/containers/Network/SyslogForm/SyslogForm.test.js
ui/src/app/settings/containers/Network/SyslogFormFields/SyslogFormFields.js
ui/src/app/settings/containers/Network/SyslogFormFields/SyslogFormFields.test.js
ui/src/app/settings/containers/Network/SyslogFormFields/index.js
ui/src/app/settings/selectors/config.js

- Added DNS, NTP, Syslog and Network Discovery forms to Network section
- Check that clicking on the Network subsections takes you to the correct form
- Check that saving works for each form

Add DNS, NTP, Syslog and Network Discovery sections to Network

---

ui/src/app/settings/actions/users.js
ui/src/app/settings/actions/users.test.js
ui/src/app/settings/reducers/user.js
ui/src/app/settings/reducers/user.test.js
ui/src/app/settings/views/Users/UsersList/UsersList.js
ui/src/app/settings/views/Users/UsersList/UsersList.test.js

Done:
- Implemented actions and reducers for deleting a user.
- Update the user list to delete the users. Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/109.
QA:
- Open the user list.
- Click the trash icon and then Delete for a user.
- The user should be removed from the list.
Note: A notification should be displayed, see: https://github.com/canonical-web-and-design/maas-ui/issues/108.

Delete users over the API

---

ui/src/app/settings/views/Users/UserFormFields/UserFormFields.js

Done:
- Include all dependencies when setting user errors. Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/117.
- Store and check the diff of errors for when the status should update.
QA:
- Edit a user.
- Change the username to an existing one (e.g. "admin").
- Click Save.
- You should get a username error.
- Change the username.
- The error should disappear.

Complete form errors dependencies

---

ui/CHANGELOG.md
ui/README.md

* Add a changelog and document how it should be updated.
No QA

Add a changelog.

---

ui/.gitignore
ui/package.json

* Build a tarball for release when invoking `yarn build`.
* run `yarn build`, ensure a `maas-ui-${version}.tar.gz` is created.

Add postbuild script to tarball production build.

---

ui/src/app/settings/components/Nav/Nav.js
ui/src/app/settings/components/Nav/__snapshots__/Nav.test.js.snap
ui/src/app/settings/components/Routes/Routes.js
ui/src/app/settings/selectors/config.js
ui/src/app/settings/selectors/config.test.js
ui/src/app/settings/views/Images/Images.js
ui/src/app/settings/views/Images/Images.test.js
ui/src/app/settings/views/Images/Windows/Windows.js
ui/src/app/settings/views/Images/Windows/Windows.test.js
ui/src/app/settings/views/Images/Windows/index.js
ui/src/app/settings/views/Images/WindowsForm/WindowsForm.js
ui/src/app/settings/views/Images/WindowsForm/WindowsForm.test.js
ui/src/app/settings/views/Images/WindowsForm/__snapshots__/WindowsForm.test.js.snap
ui/src/app/settings/views/Images/WindowsForm/index.js
ui/src/app/settings/views/Images/WindowsFormFields/WindowsFormFields.js
ui/src/app/settings/views/Images/WindowsFormFields/WindowsFormFields.test.js
ui/src/app/settings/views/Images/WindowsFormFields/index.js
ui/src/app/settings/views/Images/__snapshots__/Images.test.js.snap
ui/src/app/settings/views/Images/index.js

Created the form for images/windows
- Go to `/settings/images/windows`
- Change the value of the form and save
- Refresh and see that it persists
- Also check the same form at `:5240/MAAS/settings/general/` and see that the value is the same

Create images windows form component

---

ui/src/app/settings/views/Images/WindowsForm/WindowsForm.js

Fixes from https://github.com/canonical-web-and-design/maas-ui/pull/134/files that should have been added but I hadn't pushed so self-approving as the previous PR had been approved.

Fixes from #134

---

README.md
package.json
ui/package.json
ui/src/app/base/components/ActionButton/ActionButton.md
ui/src/app/base/components/Button/Button.md
ui/src/app/base/components/Card/Card.md
ui/src/app/base/components/Col/Col.md
ui/src/app/base/components/Form/Form.md
ui/src/app/base/components/Input/Input.md
ui/src/app/base/components/Link/Link.md
ui/src/app/base/components/List/List.md
ui/src/app/base/components/MainTable/MainTable.md
ui/src/app/base/components/Modal/Modal.md
ui/src/app/base/components/Pagination/Pagination.md
ui/src/app/base/components/Row/Row.md
ui/src/app/base/components/SearchBox/SearchBox.md
ui/src/app/base/components/Select/Select.md
ui/src/app/base/components/Strip/Strip.md
ui/src/app/base/components/Textarea/Textarea.md
ui/styleguide.config.js
yarn.lock

Done:
- Add styleguidist and basic generic component docs.
QA:
- Run `./run exec --expose-port 6060 yarn docs`.
- You should see docs for components.

Add component docs

---

ui/src/app/settings/components/Routes/Routes.js
ui/src/app/settings/selectors/config.js
ui/src/app/settings/selectors/config.test.js
ui/src/app/settings/views/Images/VMWare/VMWare.js
ui/src/app/settings/views/Images/VMWare/VMWare.test.js
ui/src/app/settings/views/Images/VMWare/index.js
ui/src/app/settings/views/Images/VMWareForm/VMWareForm.js
ui/src/app/settings/views/Images/VMWareForm/VMWareForm.test.js
ui/src/app/settings/views/Images/VMWareForm/__snapshots__/VMWareForm.test.js.snap
ui/src/app/settings/views/Images/VMWareForm/index.js
ui/src/app/settings/views/Images/VMWareFormFields/VMWareFormFields.js
ui/src/app/settings/views/Images/VMWareFormFields/VMWareFormFields.test.js
ui/src/app/settings/views/Images/VMWareFormFields/index.js

Built VMWare vCenter form. Fixes [#1400](https://github.com/canonical-web-and-design/MAAS-squad/issues/1400)
- Go `/settings/images/vmware`
- Change the values in the form, save, refresh and see that they persist
- Visit the same for in the old MAAS (:5240/MAAS/settings/general/ under the **VMWare vCenter** heading) and see that the data matches what you changed

Build VMWare form

---

.github/release-drafter.yml

See [README](https://github.com/toolmantim/release-drafter#readme) for details.

Add release drafter config.

---

ui/src/app/App.test.js
ui/src/app/base/actions.js
ui/src/app/base/actions.test.js
ui/src/app/base/components/ActionButton/ActionButton.scss
ui/src/app/base/components/Main/Main.test.js
ui/src/app/base/components/Notification/Notification.js
ui/src/app/base/components/Notification/Notification.md
ui/src/app/base/components/Notification/Notification.test.js
ui/src/app/base/components/Notification/__snapshots__/Notification.test.js.snap
ui/src/app/base/components/Notification/index.js
ui/src/app/base/components/NotificationList/NotificationList.js
ui/src/app/base/components/NotificationList/NotificationList.test.js
ui/src/app/base/components/NotificationList/__snapshots__/NotificationList.test.js.snap
ui/src/app/base/components/NotificationList/index.js
ui/src/app/base/components/Section/Section.js
ui/src/app/base/components/Section/Section.test.js
ui/src/app/base/components/Section/__snapshots__/Section.test.js.snap
ui/src/app/base/reducers.js
ui/src/app/base/reducers.test.js
ui/src/app/base/selectors.js
ui/src/app/base/selectors.test.js
ui/src/app/settings/views/Settings.test.js
ui/src/app/settings/views/Users/UserForm/UserForm.js
ui/src/app/settings/views/Users/UserForm/UserForm.test.js
ui/src/app/settings/views/Users/UsersList/UsersList.js
ui/src/app/settings/views/Users/UsersList/UsersList.test.js
ui/src/root-reducer.js
ui/src/scss/_vanilla-overrides.scss

Done:
- Added global messages actions/reducers.
- Added a Notification component.
- Updated users form/list to show a message when users are created, updated or deleted. Fixes: https://github.com/canonical-web-and-design/maas-squad/issues/1410. Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/108.
QA:
- Add, update or delete a user.
- You should get a message.

Display a message when adding/updating/removing users

---

ui/src/app/base/components/ActionButton/ActionButton.js
ui/src/app/base/components/Input/Input.js
ui/src/app/settings/components/Routes/Routes.js
ui/src/app/settings/proptypes.js
ui/src/app/settings/views/Repositories/RepositoriesList/RepositoriesList.js
ui/src/app/settings/views/Repositories/RepositoryAdd/RepositoryAdd.js
ui/src/app/settings/views/Repositories/RepositoryAdd/RepositoryAdd.test.js
ui/src/app/settings/views/Repositories/RepositoryEdit/RepositoryEdit.js
ui/src/app/settings/views/Repositories/RepositoryEdit/RepositoryEdit.test.js
ui/src/app/settings/views/Repositories/RepositoryForm/RepositoryForm.js
ui/src/app/settings/views/Repositories/RepositoryForm/RepositoryForm.test.js
ui/src/app/settings/views/Repositories/RepositoryFormFields/RepositoryFormFields.js
ui/src/app/settings/views/Repositories/RepositoryFormFields/RepositoryFormFields.scss
ui/src/app/settings/views/Repositories/RepositoryFormFields/RepositoryFormFields.test.js
ui/src/app/settings/views/Repositories/RepositoryFormFields/index.js
ui/src/scss/_vanilla-overrides.scss

- Populated RepositoryAdd and RepositoryEdit forms with packagerepository and general data
- Go to `:8000/MAAS/settings/repositories` and click "Add PPA".
- Check that the url field is already prefixed with `ppa:`, there is no section for "Distributions" or "Components", the title is "Add PPA" and the save button says "Save PPA"
- Click on "Add repository"
- Check that there is a section for "Distributions" and "Components", the title is "Add repository" and the save button says "Save repository"
- Add some repos at `:5240/MAAS/#/settings/repositories`
- Go to `:8000/MAAS/settings/repositories`, click the edit icon and check that the repo data is correct
- Click the edit button for the first repo (default one)
- Check that there are checkboxes for "Disabled pockets" and "Disabled …

Populate repository add/edit fields with websocket data

---

ui/src/app/base/hooks.js
ui/src/app/settings/actions/repositories.js
ui/src/app/settings/actions/repositories.test.js
ui/src/app/settings/reducers/packagerepository.js
ui/src/app/settings/reducers/packagerepository.test.js
ui/src/app/settings/views/Repositories/RepositoriesList/RepositoriesList.js
ui/src/app/settings/views/Repositories/RepositoriesList/RepositoriesList.test.js
ui/src/app/settings/views/Repositories/RepositoryForm/RepositoryForm.js
ui/src/app/settings/views/Repositories/RepositoryForm/RepositoryForm.test.js
ui/src/app/settings/views/Repositories/RepositoryFormFields/RepositoryFormFields.js
ui/src/app/settings/views/Repositories/RepositoryFormFields/RepositoryFormFields.test.js
ui/src/app/settings/views/Repositories/utils.js
ui/src/app/settings/views/Users/UserForm/UserForm.test.js
ui/src/app/settings/views/Users/UserFormFields/UserFormFields.js
ui/src/app/settings/views/Users/UserFormFields/UserFormFields.test.js

- Implemented adding and editing repositories
- Click "Add repository", fill in the forms correctly and click "Save repository". Check that you are redirected to the repo list and the new repo is there with a notification.
- Click the edit button for the repo and edit some fields. Click "Save repository" and check that you are redirected to the repo list with a notification.
- Click "Add repository" and use the same name you used before. Click "Save repository" and check that a server error shows underneath the Name field.
- Delete a repo and see there is a notification.
- In another browser tab, make some changes to repos from the old maas settings and check that the details are updated in real-time.
- Do the same with users because I've used a couple of custom hooks there too

Implement adding and editing repositories

---

ui/src/app/base/components/Notification/Notification.js
ui/src/app/base/components/Notification/index.js
ui/src/app/base/hooks.js
ui/src/app/settings/views/Dhcp/DhcpForm/DhcpForm.js
ui/src/app/settings/views/Dhcp/DhcpList/DhcpList.js
ui/src/app/settings/views/Repositories/RepositoriesList/RepositoriesList.js
ui/src/app/settings/views/Repositories/RepositoryForm/RepositoryForm.js
ui/src/app/settings/views/Scripts/ScriptsList.js
ui/src/app/settings/views/Users/UserForm/UserForm.js
ui/src/app/settings/views/Users/UsersList/UsersList.js

QA:
- Set the notification types as constants. Fixes: #181.
- Add a hook for adding messages based on a state change.
QA:
- check a few lists and forms and adding, updating a deleting should all display messages.

Add a hook for adding messages

---

ui/src/app/base/components/FormCard/FormCard.js
ui/src/app/base/components/FormCard/FormCard.scss
ui/src/app/base/components/FormCard/__snapshots__/FormCard.test.js.snap
ui/src/app/settings/views/Dhcp/DhcpForm/DhcpForm.js
ui/src/app/settings/views/Dhcp/DhcpForm/DhcpForm.test.js
ui/src/app/settings/views/Users/UserAdd/UserAdd.js
ui/src/app/settings/views/Users/UserAdd/__snapshots__/UserAdd.test.js.snap
ui/src/app/settings/views/Users/UserEdit/UserEdit.js
ui/src/app/settings/views/Users/UserForm/UserForm.js
ui/src/app/settings/views/Users/UserForm/UserForm.test.js

Done:
- Display the username in the form title when editing a user. Fixes: #202.
QA:
- View an edit user form
- The username should in the title and should change when the username input changes.

Display username in title when editing

---

ui/src/app/base/components/MainTable/MainTable.js
ui/src/app/base/components/Pagination/Pagination.js
ui/src/app/machines/views/MachineList/MachineList.js

Done:
- Add basic machine table.
- Add support for custom sort function for the table.
- Add support for scrolling to the top on paginate.
QA:
- Visit the machine list.
- You should see a list of machine names.

Add basic machine table.

---

ui/package.json
ui/src/app/base/components/Button/Button.js
ui/src/app/base/components/Header/__snapshots__/Header.test.js.snap
ui/src/app/base/components/SideNav/__snapshots__/SideNav.test.js.snap
yarn.lock

Done:
- Upgrade react-router-dom to 5.1.0.
QA:
- Check that routing works as before.

Upgrade react-router-dom to 5.1.0

---

ui/src/app/base/components/TableDeleteConfirm/TableDeleteConfirm.js
ui/src/app/base/components/TableDeleteConfirm/__snapshots__/TableDeleteConfirm.test.js.snap
ui/src/app/preferences/actions/sshkey/sshkey.js
ui/src/app/preferences/actions/sshkey/sshkey.test.js
ui/src/app/preferences/reducers/sshkey/sshkey.js
ui/src/app/preferences/reducers/sshkey/sshkey.test.js
ui/src/app/preferences/views/SSHKeys/SSHKeyList/SSHKeyList.js
ui/src/app/preferences/views/SSHKeys/SSHKeyList/SSHKeyList.test.js

Done:
- Enable deleting SSH keys from the list. Fixes: https://github.com/canonical-web-and-design/maas-squad/issues/1507.
QA:
- View the list of SSH keys in your preferences.
- Click delete and confirm.
- The key(s) should be removed.

Delete SSH keys from the list.

---

ui/src/app/preferences/components/Routes/Routes.js
ui/src/app/preferences/views/APIKeys/APIKeyList/APIKeyList.js
ui/src/app/preferences/views/APIKeys/APIKeyList/APIKeyList.scss
ui/src/app/preferences/views/APIKeys/APIKeyList/APIKeyList.test.js
ui/src/app/preferences/views/APIKeys/APIKeyList/index.js

Done:
- Add the UI for displaying a list of API keys. Fixes: #244.
QA:
- Visit /account/prefs/api-keys.
- You should see a (fake) list of API keys.

Add API key list

---

ui/package.json
ui/src/app/base/components/ActionButton/ActionButton.scss
ui/src/app/base/components/Header/Header.js
ui/src/app/base/components/Header/__snapshots__/Header.test.js.snap
ui/src/app/base/components/Section/Section.scss
ui/src/app/base/components/SideNav/SideNav.scss
ui/src/app/settings/views/Users/UsersList/UsersList.scss
ui/src/scss/_patterns_button.scss
ui/src/scss/_patterns_table.scss
ui/src/scss/_settings.scss
ui/src/scss/_vanilla-overrides.scss
ui/src/scss/base.scss
yarn.lock

Done:
- Upgrade Vanilla to 2.4.0.
- Change imports to new locations.
- Remove some overrides.
QA:
- Check that nothing looks out of places, especially forms.

Upgrade Vanilla to 2.4.0

---

ui/src/app/base/actions/licensekeys/licensekeys.js
ui/src/app/base/actions/licensekeys/licensekeys.test.js
ui/src/app/base/reducers/licensekeys/licensekeys.js
ui/src/app/base/reducers/licensekeys/licensekeys.test.js
ui/src/app/base/sagas/http.js
ui/src/app/base/sagas/http.test.js
ui/src/app/base/sagas/index.js
ui/src/app/base/selectors/licensekeys/licensekeys.js
ui/src/app/base/selectors/licensekeys/licensekeys.test.js
ui/src/app/settings/views/LicenseKeys/LicenseKeyList/LicenseKeyList.js
ui/src/root-saga.js

Allow license keys to be deleted.
*Note* based on https://github.com/canonical-web-and-design/maas-ui/pull/257 (review that first and this can be rebased).
1. Add a license key ([instructions](https://github.com/canonical-web-and-design/maas-ui/pull/253)).
2. Visit /MAAS/settings/license-keys
3. Delete the key, it should vamoose.

Delete license keys

---

ui/src/app/Routes.js
ui/src/app/base/views/NotFound/NotFound.js
ui/src/app/base/views/NotFound/NotFound.test.js
ui/src/app/base/views/NotFound/__snapshots__/NotFound.test.js.snap
ui/src/app/base/views/NotFound/index.js
ui/src/app/machines/components/Routes/Routes.js
ui/src/app/preferences/components/Routes/Routes.js
ui/src/app/settings/components/Routes/Routes.js

Done:
- Add a 404 page. Fixes: #215.
QA:
- Visit a URL that doesn't exist, it should show you a not found page.

Add a 404 page

---

ui/src/app/base/reducers/status/status.js
ui/src/app/base/reducers/status/status.test.js
ui/src/app/base/sagas/websockets.js
ui/src/app/base/sagas/websockets.test.js

Done:
- Notify the user if the websocket disconnects. Fixes: #193.
QA:
- Load the UI.
- Stop your MAAS, the UI should update.
- Restart your MAAS, the UI should eventually return.

WS disconnect notification

---

ui/src/app/preferences/views/APIKeys/APIKeyList/APIKeyList.js
ui/src/app/preferences/views/SSHKeys/SSHKeyList/SSHKeyList.js
ui/src/app/preferences/views/SSLKeys/SSLKeyList/SSLKeyList.js
ui/src/app/settings/components/SettingsTable/SettingsTable.js
ui/src/app/settings/components/SettingsTable/SettingsTable.scss
ui/src/app/settings/components/SettingsTable/SettingsTable.test.js
ui/src/app/settings/components/SettingsTable/__snapshots__/SettingsTable.test.js.snap
ui/src/app/settings/components/SettingsTable/index.js
ui/src/app/settings/views/Dhcp/DhcpList/DhcpList.js
ui/src/app/settings/views/Dhcp/DhcpList/DhcpList.test.js
ui/src/app/settings/views/LicenseKeys/LicenseKeyList/LicenseKeyList.js
ui/src/app/settings/views/LicenseKeys/LicenseKeyList/LicenseKeyList.test.js
ui/src/app/settings/views/Repositories/RepositoriesList/RepositoriesList.js
ui/src/app/settings/views/Scripts/ScriptsList.js
ui/src/app/settings/views/Scripts/ScriptsList.test.js
ui/src/app/settings/views/Users/UsersList/UsersList.js
ui/src/app/settings/views/Users/UsersList/UsersList.test.js

Done:
- Update settings and preferences lists to use a shared table component.
- Add new loading state. Fixes: #159.
QA:
- Click through all the lists in settings and preferences.
- There should be a new loading state (see: #159).
- Everything else should function as it did before.

Table loading state

---

ui/src/app/base/actions/status/status.js
ui/src/app/base/actions/status/status.test.js
ui/src/app/base/components/Header/Header.js
ui/src/app/base/components/Header/Header.test.js
ui/src/app/base/components/Header/__snapshots__/Header.test.js.snap
ui/src/app/base/reducers/status/status.js
ui/src/app/base/reducers/status/status.test.js
ui/src/app/base/sagas/http.js
ui/src/app/base/sagas/http.test.js
ui/src/app/base/sagas/index.js
ui/src/app/base/sagas/websockets.js
ui/src/app/base/sagas/websockets.test.js
ui/src/root-saga.js
ui/src/setupProxy.js

Done:
- Enable logging the user out. Fixes: https://github.com/canonical-web-and-design/maas-squad/issues/1526
QA:
- Log into the UI.
- Click Logout in the top right.
- You should see the login form.
- Log in again, you should be correctly logged in again.

Enable logging out

---

.circleci/config.yml

Add legacy to config.

---

legacy/.eslintrc.js
legacy/src/app/controllers/node_details.js
legacy/src/app/controllers/tests/test_node_details.js
legacy/src/app/directives/dbl_click_overlay.js
legacy/src/app/directives/tests/test_action_button.js
legacy/src/app/directives/tests/test_call_to_action.js
legacy/src/app/directives/tests/test_maas_obj_form.js
legacy/src/app/directives/tests/test_machines_table.js
legacy/src/app/directives/tests/test_proxy_settings.js
legacy/src/app/directives/tests/test_ssh_keys.js
legacy/src/app/partials/ssh-keys.html
legacy/src/app/routes.js
legacy/src/app/services/pollingmanager.js
legacy/src/app/services/region.js
legacy/src/app/services/tests/test_pollingmanager.js
legacy/src/app/testing/setup-jest.js

Misc test fixes as a result of directory structure changes and upgrading to the Angularjs LTS.
Run `yarn test`. Tests should pass.

Fix legacy tests

---

legacy/src/app/entry.js

Remove unused config values
None, this is dead code.

Remove unused MAAS config values.

---

legacy/package.json
legacy/src/app/entry.js
legacy/src/app/testing/setup.js
legacy/src/index.html
legacy/src/scss/_maas.scss
yarn.lock

Configure maas-ui with VERSION and COMPLETED_INTRO using [angular-deferred-bootstrap](https://github.com/philippd/angular-deferred-bootstrap).
Load the app, it should load and if completed previously, you should not be redirected to intro.

Configure maas-ui with VERSION and COMPLETED_INTRO.

---

legacy/.eslintrc.js
legacy/package.json
legacy/src/app/bootstrap.js
legacy/src/app/controllers/dashboard.js
legacy/src/app/controllers/intro.js
legacy/src/app/controllers/intro_user.js
legacy/src/app/controllers/node_details.js
legacy/src/app/controllers/nodes_list.js
legacy/src/app/controllers/tests/test_intro.js
legacy/src/app/controllers/tests/test_intro_user.js
legacy/src/app/controllers/tests/test_nodes_list.js
legacy/src/app/directives/loading.js
legacy/src/app/directives/version_reloader.js
legacy/src/app/entry.js
legacy/src/app/services/manager.js
legacy/src/app/testing/setup.js
legacy/src/index.html
yarn.lock

* Configure app via websocket API, and manually bootstrap (removes *angular-deferred-bootstrap*).
* Added basic loading component to display before app bootstraps.
Load app, navigate about. There should be no console errors. Data set from config like version/app name should display correctly.

Configure app from websocket API.

---

legacy/package.json
legacy/src/app/entry.js
legacy/src/app/testing/setup-jest.js
proxy/index.js
ui/src/app/Routes.js
yarn.lock

Done:
- Redirect to the React login page from the AngularJS client. Fixes: https://github.com/canonical-web-and-design/maas-squad/issues/1616.
- Drive-by fixes to deps.

Redirect login

---

legacy/src/app/bootstrap.js
legacy/src/app/entry.js

* Add maas_uuid to maas CONFIG.
* Refactor a bit of code.
Not aware of a way to QA this unfortunately other than to drop a `console.log` after `window.CONFIG = CONFIG;` after bootstrap.js:106

Add maas_uuid to CONFIG.

---

ui/src/app/base/components/Login/Login.js
ui/src/app/base/reducers/status/status.js
ui/src/app/base/reducers/status/status.test.js
ui/src/app/base/sagas/http.js
ui/src/app/base/sagas/http.test.js

Done:
- Handle errors when authenticating. Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/277
QA:
- Update your MAAS to master.
- Load the ui and log out.
- Try and log in with credentials that don't exist.
- You should get a login error.
- Try logging in as your user, it should still work.

Handle login errors

---

ui/src/app/base/reducers/auth/auth.js
ui/src/app/base/reducers/auth/auth.test.js

Done:
- Update the stored auth user if the user changes. Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/330.
QA:
- Visit your preferences and change your username.
- Your username should update in the header.

Sync changes to the auth user.

---

legacy/src/app/bootstrap.js
legacy/src/app/entry.js

MAAS was using an incorrect key for maas_uuid (fixed here https://code.launchpad.net/~blake-rouse/maas/+git/maas/+merge/374934), so update the client to reflect this.
Start the app, in the console inspect `window.CONFIG`, it should have a valid uuid instead of an empty string.

Update config key for maas_uuid.

---

legacy/src/app/entry.js
ui/src/app/base/sagas/http.js

Done:
- Use a more reliable API endpoint for testing if the user is logged in. Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/367.
QA:
- Login and click back and forward between angular and react urls, you should not get logged out.

Fix authentication test

---

ui/package.json
ui/src/app/settings/views/Scripts/ScriptsUpload.scss
ui/src/scss/_vanilla-overrides.scss
yarn.lock

Done:
- Upgrade Vanilla to 2.4.1. Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/368.
- Remove some redundant overrides.
QA:
- Load the ui and compare the header when viewing a react and angular route, the dark grey colour should be the same.
- Have a poke around the React app, nothing should be out of place.

Upgrade Vanilla to 2.4.1

---

legacy/package.json
package.json
proxy/package.json
ui/package.json

Done:
- Add a package name and version for the mono repo. Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/431.
- Update the workspace names.

Add top level package name

---

ui/src/app/base/components/FormikField/FormikField.test.js
ui/src/app/base/components/FormikForm/FormikForm.test.js
ui/src/app/base/components/FormikFormContent/FormikFormContent.test.js
ui/src/app/base/components/Login/Login.test.js
ui/src/app/base/components/UserForm/UserForm.test.js
ui/src/app/preferences/views/Details/Details.test.js
ui/src/app/preferences/views/SSHKeys/AddSSHKey/AddSSHKey.test.js
ui/src/app/preferences/views/SSHKeys/SSHKeyFormFields/SSHKeyFormFields.test.js
ui/src/app/preferences/views/SSLKeys/AddSSLKey/AddSSLKey.test.js
ui/src/app/settings/views/Configuration/DeployFormFields/DeployFormFields.test.js
ui/src/app/settings/views/Dhcp/DhcpForm/DhcpForm.test.js
ui/src/app/settings/views/Dhcp/DhcpFormFields/DhcpFormFields.test.js
ui/src/app/settings/views/Users/UserForm/UserForm.test.js
ui/src/setupTests.js

- Mock the uuid/v4 module for all tests. Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/421.

Mock uuid for all tests

---

legacy/src/app/controllers/dashboard.js
legacy/src/app/controllers/node_details.js
legacy/src/app/controllers/nodes_list.js
legacy/src/app/controllers/pod_details.js
legacy/src/app/directives/machines_table.js
legacy/src/app/directives/nodelist/nodes_list_filter.js
legacy/src/app/entry.js
legacy/src/app/factories/machines.js
legacy/src/app/factories/tests/test_machines.js
legacy/src/app/filters/send_analytics_event.js
legacy/src/app/filters/tests/test_send_analytics_data.js
legacy/src/app/partials/cards/machine-overview.html
legacy/src/app/partials/cards/network.html
legacy/src/app/partials/dashboard.html
legacy/src/app/partials/machines-table.html
legacy/src/app/partials/node-details.html
legacy/src/app/partials/nodedetails/storage/datastores.html
legacy/src/app/partials/nodedetails/storage/disks-partitions.html
legacy/src/app/partials/nodedetails/storage/filesystems.html
legacy/src/app/partials/nodelist/nodes-list-filter.html
legacy/src/app/partials/nodes-list.html
legacy/src/app/partials/pod-details.html
legacy/src/app/partials/subnet-details.html

Backported the following three commits into the legacy app:
- https://git.launchpad.net/maas/commit/?id=e5c49174c00da13058b997ae4479e80fecb9b3cd
- https://git.launchpad.net/maas/commit/?id=57df4a43aa9d73f1f50904a5bf640a7300cabcf2
- https://git.launchpad.net/maas/diff/?id=48ecbab211c40720ba4d42d683b56f44390a2a4d
- Check the link speed filters work on the machines list page
- Check the subnets IP table looks the same as the launchpad master
- Click around and see that links and buttons still work

Backport network filters, IP table and analytics

---

ui/src/app/preferences/views/APIKeys/APIKeyList/APIKeyList.scss
ui/src/app/preferences/views/SSHKeys/SSHKeyList/SSHKeyList.js
ui/src/app/preferences/views/SSHKeys/SSHKeyList/SSHKeyList.scss
ui/src/app/preferences/views/SSLKeys/SSLKeyList/SSLKeyList.scss
ui/src/app/settings/views/Dhcp/DhcpList/DhcpList.scss
ui/src/app/settings/views/LicenseKeys/LicenseKeyList/LicenseKeyList.js
ui/src/app/settings/views/LicenseKeys/LicenseKeyList/LicenseKeyList.scss
ui/src/app/settings/views/Repositories/RepositoriesList/RepositoriesList.scss
ui/src/app/settings/views/Scripts/ScriptsList.scss
ui/src/app/settings/views/Users/UsersList/UsersList.scss
ui/src/scss/_patterns_table-actions.scss

Done:
- Hide some fields to prevent content breaking over lines. Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/449.
- Prevent headers from wrapping. Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/399. Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/393.
QA:
- Go through each table in settings and preferences and reduce the size of your browser.
- The tables should hide and wrap content as needed at each size.

Improve responsiveness of tables

---

.circleci/config.yml
run

Done:
- Update to the latest docker image.
QA:
- CI should pass.

Upgrade the docker image

---

ui/src/app/base/reducers/status/status.js
ui/src/app/base/reducers/status/status.test.js
ui/src/app/base/sagas/http.js
ui/src/app/base/sagas/http.test.js

Done:
- Use the login endpoint to check if authenticated. Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/515.
QA:
- Update your MAAS master.
- Logout out and in via the UI. This should work.
- Refresh your window. You should remain logged in.

Check authentication from login endpoint

---

ui/src/app/preferences/views/APIKeys/APIKeyForm/APIKeyForm.js
ui/src/app/preferences/views/APIKeys/APIKeyList/APIKeyList.js

* Correct labels and text on API key UI.
None needed.

Preferences fixes from Design QA

---

RELEASE.md

Add `RELEASE.md`, documenting the release process.
fixes #549

Document release process.

---

legacy/package.json
proxy/index.js
ui/package.json
ui/src/app/App.js
ui/src/app/base/components/CopyButton/CopyButton.js
ui/src/app/base/components/CopyButton/__snapshots__/CopyButton.test.js.snap
ui/src/app/base/components/FormCardButtons/__snapshots__/FormCardButtons.test.js.snap
ui/src/app/base/components/Section/Section.scss
ui/src/app/preferences/views/APIKeys/APIKeyList/APIKeyList.js
ui/src/app/preferences/views/SSHKeys/SSHKeyList/SSHKeyList.js
ui/src/app/preferences/views/SSHKeys/SSHKeyList/SSHKeyList.scss
ui/src/app/preferences/views/SSLKeys/SSLKeyList/SSLKeyList.js
ui/src/app/preferences/views/SSLKeys/SSLKeyList/SSLKeyList.scss
ui/src/app/settings/components/Routes/Routes.js
ui/src/app/settings/views/Dhcp/DhcpList/DhcpList.js
ui/src/app/settings/views/LicenseKeys/LicenseKeyList/LicenseKeyList.js
ui/src/app/settings/views/Repositories/RepositoriesList/RepositoriesList.js
ui/src/app/settings/views/Scripts/ScriptsList.js
ui/src/app/settings/views/Users/UserAdd/UserAdd.js
ui/src/app/settings/views/Users/UserAdd/UserAdd.test.js
ui/src/app/settings/views/Users/UserAdd/__snapshots__/UserAdd.test.js.snap
ui/src/app/settings/views/Users/UserEdit/UserEdit.js
ui/src/app/settings/views/Users/UsersList/UsersList.js
ui/src/scss/_patterns_table.scss
ui/src/scss/_vanilla-overrides.scss
yarn.lock

- Upgraded Vanilla to 2.5.0.
- Upgrade react-components to 0.3.0.
- Replaced overrides with utilities.
- Fixed the loading position. Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/524
- Load the react ui, check that the loading spinners are aligned with the header logo.
- View the settings and preferences and check that the icon buttons are unchanged in the lists (e.g. users, api keys).
- Check that all the settings pages now load.

Upgrade vanilla 2.5.0

---

ui/src/app/settings/views/Repositories/RepositoryForm/RepositoryForm.js
ui/src/app/settings/views/Repositories/RepositoryFormFields/RepositoryFormFields.js

* Allow the default repo url to be edited.
* Go to /MAAS/r/settings/repositories, edit the default repo url, and save. The new url should be reflected in the list.
lp#1855320

Allow the default repo url to be edited (lp#1855320).

---

legacy/src/app/partials/node-details.html

This pull request will elaborate bmc behavior more to reduce confusion like this bug report https://bugs.launchpad.net/maas/+bug/1810796

More explicit messages when changing bmc node config

---

ui/package.json
ui/src/app/base/hooks.js
yarn.lock

- Correctly mark field errors. Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/544.
- Upgrade Formik to 2.0.7.
- Go to Settings -> Users -> Add user.
- Try to add a user with the same username as an existing user.
- Click Save and you should see an error under the username field.

Correctly mark field errors.

---

legacy/src/app/entry.js
shared/src/components/Header/Header.js
ui/src/app/App.js
ui/src/app/settings/selectors/config/config.js

- Correctly inject GA script.
- Handle dimensions and url tracking for both Angular and React. Fixes: https://github.com/canonical-web-and-design/maas-squad/issues/1495.
- Load the React client with debug off (you might have to change `const debug = process.env.NODE_ENV === "development";` to something else in App.js).
- check that the script is executed (in your console check that window.dataLayer is set).
- Repeat for the Angular client (the debug option is in entry.js).

Correctly include Google Analytics

---

ui/package.json

* number higher
* number higher? yes = good

Release v0.2.1

---

legacy/src/index.html.ejs

Make loading messages consistent. Previously we had both "Loading MAAS..." followed by "Loading..." which was a bit distracting.
None

Consistent loading messages

---

ui/src/app/machines/views/MachineList/MachineList.js
ui/src/app/machines/views/MachineList/MachineList.test.js
ui/src/app/machines/views/MachineList/ZoneColumn/ZoneColumn.js
ui/src/app/machines/views/MachineList/ZoneColumn/ZoneColumn.test.js
ui/src/app/machines/views/MachineList/ZoneColumn/__snapshots__/ZoneColumn.test.js.snap
ui/src/app/machines/views/MachineList/ZoneColumn/index.js

Add zones/spaces column to new machine listing.
Ensure zones/spaces displayed correctly on machine listing.

Add zone/spaces column to new machine listing.

---

ui/src/app/machines/views/MachineList/MachineList.js
ui/src/app/machines/views/MachineList/PoolColumn/PoolColumn.js
ui/src/app/machines/views/MachineList/PoolColumn/PoolColumn.test.js
ui/src/app/machines/views/MachineList/PoolColumn/__snapshots__/PoolColumn.test.js.snap
ui/src/app/machines/views/MachineList/PoolColumn/index.js
ui/src/app/machines/views/MachineList/PowerColumn/PowerColumn.js

* Add pool column to new machine listing.
* Ensure poll name and machine note are displayed correctly in new machine listing.

Add pool column to new machine listing.

---

legacy/src/app/partials/node-details.html
yarn.lock

Fixed the typo in the send analytics function on the Network tab.
- Run this branch
- Go into a machine
- Select Network
- Check there is no console error
Fixes https://github.com/canonical-web-and-design/maas-ui/issues/655
LP: #1859622

LP: #1859622 - Fix the console error on networking tab

---

ui/src/app/machines/views/MachineList/FabricColumn/FabricColumn.js
ui/src/app/machines/views/MachineList/FabricColumn/FabricColumn.test.js
ui/src/app/machines/views/MachineList/FabricColumn/__snapshots__/FabricColumn.test.js.snap
ui/src/app/machines/views/MachineList/FabricColumn/index.js
ui/src/app/machines/views/MachineList/MachineList.js

Add fabric and vlan column to new machine listing.
Ensure fabric and vlan are displayed correctly on machine list.

Add fabric and vlan column to new machine listing.

---

ui/src/app/machines/views/MachineList/CoresColumn/CoresColumn.js
ui/src/app/machines/views/MachineList/CoresColumn/CoresColumn.test.js
ui/src/app/machines/views/MachineList/CoresColumn/__snapshots__/CoresColumn.test.js.snap
ui/src/app/machines/views/MachineList/CoresColumn/index.js
ui/src/app/machines/views/MachineList/MachineList.js
ui/src/app/machines/views/MachineList/MachineList.test.js

Add cores/arch to new machine listing.
* Ensure cores/arch display correctly.
* Ensure tooltip displays full arch value.
This PR does *not* include test status, which will land in a followup branch.

Add cores/arch to new machine listing.

---

legacy/src/app/factories/bootresources.js
legacy/src/app/partials/cards/cpu.html
legacy/src/app/partials/cards/memory.html
legacy/src/app/partials/cards/storage.html
legacy/src/app/services/region.js

Globally fix typos for "received" and "nonexistant" 
N/A, not a functional change
Fixes #672 .

chore: Fix typos for recieved and nonexistant [sic]

---

ui/src/app/base/components/ScriptStatus/ScriptStatus.js
ui/src/app/base/components/ScriptStatus/ScriptStatus.test.js
ui/src/app/machines/views/MachineList/CoresColumn/CoresColumn.js
ui/src/app/machines/views/MachineList/CoresColumn/CoresColumn.test.js
ui/src/app/machines/views/MachineList/CoresColumn/__snapshots__/CoresColumn.test.js.snap
ui/src/app/machines/views/MachineList/MachineList.test.js

Add test status for core column.
Run some CPU tests, you should see an icon representing the testing status (pending etc.)

Add test status for core column.

---

ui/src/app/base/components/ScriptStatus/ScriptStatus.js
ui/src/app/base/components/ScriptStatus/ScriptStatus.test.js
ui/src/app/machines/views/MachineList/FabricColumn/FabricColumn.js
ui/src/app/machines/views/MachineList/FabricColumn/FabricColumn.test.js
ui/src/app/machines/views/MachineList/FabricColumn/__snapshots__/FabricColumn.test.js.snap
ui/src/app/machines/views/MachineList/MachineList.test.js

Add fabric test status.
Run some network tests and ensure test state is reflected with icon.

Add fabric test status.

---

ui/src/app/machines/views/MachineList/MachineList.scss
ui/src/app/machines/views/MachineList/NameColumn/NameColumn.js
ui/src/app/machines/views/MachineList/NameColumn/__snapshots__/NameColumn.test.js.snap
ui/src/app/machines/views/MachineList/_machine-list-breakpoint-widths.scss

- Copied over the breakpoint-widths code from legacy and applied them here.
- Check that the machine list is relatively responsive, i.e. it drops columns, changes widths and is generally readable at all viewport widths.
Fixes #690

Add explicit widths and breakpoints to new machine list.

---

ui/src/app/Routes.js
ui/src/app/base/components/Section/Section.js
ui/src/app/base/components/Tabs/Tabs.js
ui/src/app/base/components/Tabs/Tabs.scss
ui/src/app/base/components/Tabs/Tabs.test.js
ui/src/app/base/components/Tabs/__snapshots__/Tabs.test.js.snap
ui/src/app/base/components/Tabs/index.js
ui/src/app/machines/components/Routes/Routes.js
ui/src/app/machines/views/Machines.js
ui/src/app/machines/views/Machines.test.js
ui/src/app/pools/views/Pools.js

- Added Tabs component and used in machine list for machines/pools tabs
- Added blank Pools component
- Check that the machine and pools count are correct in the tabs
- Check that clicking the machines tab takes you to /r/machines (machine list) and clicking the resource pools tab takes you to /r/pools (empty)
Fixes canonical-web-and-design/MAAS-squad#1726

Add machines and resource pools tabs to machines list.

---

ui/src/app/base/actions/machine/machine.js
ui/src/app/base/actions/machine/machine.test.js
ui/src/app/base/components/ContextualMenu/ContextualMenu.js
ui/src/app/base/components/ContextualMenu/ContextualMenu.test.js
ui/src/app/base/reducers/machine/machine.js
ui/src/app/base/reducers/machine/machine.test.js
ui/src/app/machines/views/MachineList/MachineList.test.js
ui/src/app/machines/views/MachineList/PoolColumn/PoolColumn.js
ui/src/app/machines/views/MachineList/PoolColumn/PoolColumn.test.js
ui/src/app/machines/views/MachineList/PoolColumn/__snapshots__/PoolColumn.test.js.snap

- Added the pool actions menu.
- If you click on the menu icon next to a pool and have no pools and you should see a message.
- If you do have pools (you might need to add some) you should be able to select a pool in the menu and (after quite a pause for me) you should see the row update.
Fixes https://github.com/canonical-web-and-design/maas-squad/issues/1720.

Pool actions

---

ui/src/app/base/components/DoubleRow/DoubleRow.js
ui/src/app/machines/views/MachineList/MachineList.js
ui/src/app/machines/views/MachineList/MachineList.scss
ui/src/app/machines/views/MachineList/MachineList.test.js
ui/src/app/machines/views/MachineList/NameColumn/NameColumn.js
ui/src/app/machines/views/MachineList/NameColumn/NameColumn.scss
ui/src/app/machines/views/MachineList/NameColumn/NameColumn.test.js
ui/src/app/machines/views/MachineList/NameColumn/__snapshots__/NameColumn.test.js.snap
ui/src/app/machines/views/MachineList/_machine-list-breakpoint-widths.scss
ui/src/app/machines/views/MachineList/_settings.scss
ui/src/app/machines/views/Machines.test.js
ui/src/scss/_vanilla-overrides.scss

- Added checkboxes for individual machines in machine list. Selected state is handled by the MachineList component.
- Log in as an admin.
- Go to the machine list and check there are checkboxes that you can select and unselect.
- Log in as a user.
- Go to the machine list and check that the checkboxes are disabled with a tooltip.
Fixes canonical-web-and-design/MAAS-squad#1741

Add checkboxes for individual machines.

---

legacy/src/app/partials/nodes-list.html

- Fixed some incorrect markup in legacy nodes.html

Fix incorrect markup in legacy nodes list

---

ui/src/app/machines/views/MachineList/PoolColumn/PoolColumn.js
ui/src/app/machines/views/MachineList/PoolColumn/PoolColumn.test.js
ui/src/app/machines/views/MachineList/PoolColumn/__snapshots__/PoolColumn.test.js.snap

- Display a spinner when an action is in progress.
- Load /r/machines.
- Change the pool for a machine.
- You should see a spinner while the pool is waiting to change.
Fixes https://github.com/canonical-web-and-design/maas-ui/issues/735.

Action spinner

---

ui/src/app/machines/views/MachineList/MachineList.js
ui/src/app/machines/views/MachineList/MachineList.scss
ui/src/app/machines/views/MachineList/MachineList.test.js
ui/src/app/machines/views/MachineList/NameColumn/NameColumn.js
ui/src/app/machines/views/MachineList/NameColumn/__snapshots__/NameColumn.test.js.snap
ui/src/scss/_vanilla-overrides.scss

- Added checkboxes for groups in the machine list
- Check that clicking a group checkbox selects every machine in that list, unless all of them are selected, in which case it unselects them all
Fixes canonical-web-and-design/MAAS-squad#1740

Add checkboxes for machine groups.

---

ui/src/app/base/sagas/http.js

- Encode credentials when making fetch login request
- Create a user with special characters (+ - _ etc) in their name and confirm you can log in as them
- Create a user with special characters in their password and confirm you can log in as them
Fixes #751 
LP: #1861952

LP: #1861952 - Allow special characters in usernames and passwords.

---

legacy/src/app/entry.js

- Check you redirect to the react login page when logging out of angular pages
Fixes #759

Redirect to react login form when logging out of angular pages.

---

ui/src/app/base/actions/resourcepool/resourcepool.js
ui/src/app/base/actions/resourcepool/resourcepool.test.js
ui/src/app/base/reducers/resourcepool/resourcepool.js
ui/src/app/base/reducers/resourcepool/resourcepool.test.js
ui/src/app/machines/components/Routes/Routes.js
ui/src/app/machines/views/Machines.js
ui/src/app/pools/views/PoolAdd/PoolAdd.js
ui/src/app/pools/views/PoolAdd/PoolAdd.test.js
ui/src/app/pools/views/PoolAdd/index.js
ui/src/app/pools/views/PoolForm/PoolForm.js
ui/src/app/pools/views/PoolForm/PoolForm.test.js
ui/src/app/pools/views/PoolForm/index.js

* Add form for creating new resource pools
* Visit /pools/add
* Add a pool, it should save with an appropriate success message.

Add pool form.

---

ui/src/app/base/actions/resourcepool/resourcepool.js
ui/src/app/base/actions/resourcepool/resourcepool.test.js
ui/src/app/base/reducers/resourcepool/resourcepool.js
ui/src/app/base/reducers/resourcepool/resourcepool.test.js
ui/src/app/base/selectors/resourcepool/resourcepool.js
ui/src/app/base/selectors/resourcepool/resourcepool.test.js
ui/src/app/machines/components/Routes/Routes.js
ui/src/app/pools/views/PoolEdit/PoolEdit.js
ui/src/app/pools/views/PoolEdit/index.js
ui/src/app/pools/views/PoolForm/PoolForm.js
ui/src/app/pools/views/PoolForm/PoolForm.test.js

* Add edit resource pool form.
* Visit /pools/, click the edit button, change the description and name. These should update with a success message.

Edit resource pools.

---

ui/src/index.js

Replace `createStore` from redux with `configureStore` from redux-toolkit, simplifying store configuration.
App should work, redux devtools should work.

Simplify store configuration with redux-toolkit.

---

legacy/src/app/partials/node-details.html

Fixes #822
* Remove the stray text
* Follow steps in bug
Fixes #822

Remove buggy duplicated button>

---

ui/src/app/base/components/ContextualMenu/ContextualMenu.js
ui/src/app/base/components/DoubleRow/DoubleRow.js
ui/src/app/base/components/TableMenu/TableMenu.js
ui/src/app/base/components/TableMenu/TableMenu.scss
ui/src/app/base/components/TableMenu/__snapshots__/TableMenu.test.js.snap
ui/src/app/machines/views/MachineList/OwnerColumn/__snapshots__/OwnerColumn.test.js.snap
ui/src/app/machines/views/MachineList/PoolColumn/__snapshots__/PoolColumn.test.js.snap
ui/src/app/machines/views/MachineList/PowerColumn/PowerColumn.js
ui/src/app/machines/views/MachineList/PowerColumn/__snapshots__/PowerColumn.test.js.snap
ui/src/app/machines/views/MachineList/StatusColumn/__snapshots__/StatusColumn.test.js.snap
ui/src/app/machines/views/MachineList/ZoneColumn/__snapshots__/ZoneColumn.test.js.snap

- Align the action menus to match the angular client.
- Visit /r/machines and open the action menus. They text in the menu should align with the text in the column, also the power column should have aligned icons.
Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/810.
Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/812.

Correct positioning of the action menus

---

ui/src/app/machines/views/MachineList/PowerColumn/__snapshots__/PowerColumn.test.js.snap

Update power state snapshot test.
* None, tests should pass.

Update power state snapshot.

---

.github/workflows/test.yml

Add Github Actions workflow for running tests.
Not QA'able afaict.
Fixes #831

Add initial GH Actions test workflow.

---

.github/workflows/test.yml

Fix syntax of test workflow file.
None, tests should pass

Fix test.yml workflow.

---

.github/workflows/test.yml

Run the CI workflow on `pull_request`.
CI workflow should run, tests should pass.

Run CI on PR.

---

legacy/src/app/filters/send_analytics_event.js
legacy/src/app/filters/tests/test_send_analytics_data.js

- Added some conditionals before firing GA event function

Prevent GA events without category + label + event

---

legacy/src/app/partials/cards/machine-overview.html

Sentry error: https://sentry.is.canonical.com/canonical/maas-ui/issues/7188/?query=is%3Aunresolved
bracket in wrong place - move to right place

Fix parsing of GA event handler.

---

package.json
ui/package.json
yarn.lock

Release v1.1.0.

---

ui/src/app/base/actions/machine/machine.js
ui/src/app/base/actions/machine/machine.test.js
ui/src/app/base/components/TagSelector/TagSelector.js
ui/src/app/base/components/TagSelector/TagSelector.test.js
ui/src/app/base/components/TagSelector/__snapshots__/TagSelector.test.js.snap
ui/src/app/base/components/TagSelector/_index.scss
ui/src/app/base/components/TagSelector/index.js
ui/src/app/base/reducers/machine/machine.js
ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/ActionFormWrapper.js
ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/TagForm/TagForm.js
ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/TagForm/TagForm.test.js
ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/TagForm/TagFormFields/TagFormFields.js
ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/TagForm/TagFormFields/TagFormFields.test.js
ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/TagForm/TagFormFields/index.js
ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/TagForm/index.js
ui/src/scss/index.scss

- Built `TagSelector` component which allows selecting existing tags and creating new tags.
- Built `TagForm` component.
- Select some machines and choose "Tag" from action dropdown
- Check that you can do the following things:
Fixes canonical-web-and-design/MAAS-squad#1786
Fixes canonical-web-and-design/MAAS-squad#1832

Build tag form and tag selector components.

---

legacy/src/app/entry.js

* Backport fix for performance regression in new header code.

Only setup routeChangeSuccess handler once.

---

package.json
ui/package.json

Release v0.2.8.

---

package.json
ui/package.json

Release v1.1.1.

---

ui/src/app/base/actions/machine/machine.js
ui/src/app/base/actions/machine/machine.test.js
ui/src/app/base/components/TagSelector/TagSelector.js
ui/src/app/base/components/TagSelector/TagSelector.test.js
ui/src/app/base/components/TagSelector/__snapshots__/TagSelector.test.js.snap
ui/src/app/base/components/TagSelector/_index.scss
ui/src/app/base/selectors/scripts/scripts.js
ui/src/app/base/selectors/scripts/scripts.test.js
ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/ActionFormWrapper.js
ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/TagForm/TagForm.js
ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/TagForm/TagForm.test.js
ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/TagForm/TagFormFields/TagFormFields.js
ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/TestForm/TestForm.js
ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/TestForm/TestForm.test.js
ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/TestForm/TestFormFields/TestFormFields.js
ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/TestForm/TestFormFields/TestFormFields.test.js
ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/TestForm/TestFormFields/index.js
ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/TestForm/index.js

- Built TestForm component
- Allow TagSelector to include descriptions
- Select some machines that can be tested and choose "Test" from the action dropdown
- Check that you can select from all the testing scripts in the maas db
- Choose a script that requires a URL (by default the only one is `internet-connectivity`) and check that an extra field shows up for entering the URL
- Submit the form and check that the selected machines run the selected tests (go to Machine details > Hardware tests and the selected tests should be either pending or running)
Fixes canonical-web-and-design/MAAS-squad#1785

Build test form in action menu dropdown.

---

legacy/package.json
legacy/src/app/entry.js
legacy/webpack.common.js
legacy/webpack.dev.js
legacy/webpack.prod.js
ui/src/app/machines/views/MachineList/_index.scss

* Add distinct production and development config for legacy.
* Only send sentry events in production.
* Ensure both dev and production build correctly, from legacy:
`yarn build`
`yarn build-dev`
* Ensure dev server runs correctly (`yarn start` from proxy)
Fixes canonical-web-and-design/MAAS-squad#1837

Add distinct production and development config.

---

ui/package.json
ui/src/app/base/reducers/auth/auth.js
ui/src/app/base/reducers/general/general.js
ui/src/app/base/reducers/licensekeys/licensekeys.js
ui/src/app/base/reducers/machine/machine.js
ui/src/app/base/reducers/packagerepository/packagerepository.js
ui/src/app/base/reducers/scripts/scripts.js
ui/src/app/preferences/reducers/sshkey/sshkey.js
ui/src/app/preferences/reducers/sslkey/sslkey.js
ui/src/app/preferences/reducers/token/token.js
ui/src/app/settings/reducers/config/config.js
yarn.lock

* Replace immer's `produce` with `createNextState` from @reduxjs/toolkit.
* None, tests should pass.
Fixes #946.

Replace produce from immer with createNextState from redux-toolkit.

---

.github/workflows/test.yml
package.json

- Run the tests before build-all in CI so it fails sooner (build-all takes multiple minutes).
None, CI should pass.

Run tests before build in CI

---

ui/package.json
ui/src/index.js

* Add git hash to ui version string. This will allow us to more accurately understand what is currently deployed to staging servers.
* Run the app and visit a react route (settings, machine listing). You should see the last commit's hash reflected in the version string.

Add git hash to ui version string.

---

.github/ISSUE_TEMPLATE/bug_report.md

Ask for maas-ui version on issue template.

---

ui/src/app/machines/views/MachineList/FabricColumn/FabricColumn.js
ui/src/app/machines/views/MachineList/FabricColumn/__snapshots__/FabricColumn.test.js.snap
ui/src/app/machines/views/MachineList/PoolColumn/PoolColumn.js
ui/src/app/machines/views/MachineList/PoolColumn/__snapshots__/PoolColumn.test.js.snap
ui/src/app/machines/views/MachineList/ZoneColumn/ZoneColumn.js
ui/src/app/machines/views/MachineList/ZoneColumn/__snapshots__/ZoneColumn.test.js.snap
ui/src/app/utils/generateLegacyURL.js
ui/src/app/utils/index.js

- Added links for pool, fabric and zone in machine list rows.
- Go to the machine list and check that clicking on cells for pool, fabric and zone takes you to the right places.
Fixes #973

Add links for pool, fabric and zone in machine list rows.

---

ui/src/__snapshots__/root-reducer.test.js.snap
ui/src/app/base/reducers/machine/machine.js
ui/src/app/base/reducers/machine/machine.test.js
ui/src/app/base/sagas/websockets.js
ui/src/app/base/sagas/websockets.test.js
ui/src/app/base/selectors/general/machineActions.js
ui/src/app/base/selectors/general/machineActions.test.js
ui/src/app/base/selectors/machine/machine.js
ui/src/app/base/selectors/machine/machine.test.js
ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/MachinesProcessing/MachinesProcessing.js
ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/MachinesProcessing/MachinesProcessing.test.js
ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/MachinesProcessing/__snapshots__/MachinesProcessing.test.js.snap
ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/MachinesProcessing/index.js
ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/SetPoolForm/SetPoolForm.js
ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/SetPoolForm/SetPoolForm.test.js
ui/src/app/machines/components/HeaderStrip/ActionFormWrapper/SetPoolForm/SetPoolFormFields/SetPoolFormFields.test.js
ui/src/websocket-client.js

- Enabled status to be shown in the action menu form.
- Update the pool menu to use the status.
- Open the machine list.
- Select some machines.
- In the Action menu select the option to set the pool.
- Either choose a pool or create a new one in the form.
- Save the form.
- You should see (maybe very quickly) the count of machines increase until they're all processed.
- The form should then close.
Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/881.

Action menu progress

---

renovate.json

Use proper maintenance emoji for labelling renovate PRs.

Use proper maintenance emoji.

---

ui/src/app/machines/views/MachineList/MachineListTable/MachineListTable.js
ui/src/app/pools/views/Pools.js

Set pagination limit at 50 machines.
* 50 machines should display on the machine list.

Set pagination limit at 50 machines.

---

ui/src/app/machines/views/MachineList/MachineList.test.js
ui/src/app/machines/views/MachineList/MachineListTable/MachineListTable.js
ui/src/app/machines/views/MachineList/MachineListTable/MachineListTable.test.js

Use `React.memo` with `MachineListTable`.
With 105 machines, this saves ~500ms of rendering time in development mode.
`MachineListTable` should not render twice when switching from Pools to Machines.

Memoise MachineListTable

---

LICENSE
legacy/package.json
ui/package.json

* Add MAAS AGPLv3 license.
* Update project metadata.
None

Add MAAS license.

---

ui/.eslintrc.json
ui/src/app/settings/views/Repositories/RepositoryFormFields/RepositoryFormFields.js

- Raise an error for unused variables.
- Re-enable accessibility lint. Replace labels that have no form inputs.

Raise an error for unused variables.

---

legacy/package.json
shared/package.json
ui/package.json

Release maas ui shared 0.1.1

---

legacy/src/app/services/region.js
root/package.json
root/src/root-application.js
shared/src/components/Header/Header.js
ui/config-overrides.js
ui/package.json
ui/src/index.js
ui/src/single-spa-entry.js
yarn.lock

- Configure the UI app to run with single-spa.

Get the ui workspace running with single-spa.

---

ui/package.json

* Disables production profiling
* `yarn build` should work.

Disable production profiling.

---

legacy/package.json
proxy/package.json
root/package.json
root/src/root-application.js
root/webpack.config.js
shared/src/components/Header/__snapshots__/Header.test.js.snap
yarn.lock

- Fix Cypress tests
- Update outdated Header snapshot
- Check that there is a green tick next to the `test-cypress` CircleCI job
Fixes #1120

Fix cypress tests

---

README.md

Update link to https in README
- Read the code and check its ok

Update link to https in README

---

README.md

Add single-spa details to readme.
none

Add single-spa details to readme.

---

root/package.json
root/src/root-application.js
root/webpack.common.js
ui/package.json
ui/src/index.js

* Add GIT_SHA envvar to root app, and only log version once on `single-spa:first-mount`.
* Run app from either a react or angular route, ensure app version is only logged once.
Fixes #1162

Only log maas-ui version once.

---

RELEASE.md
legacy/package.json
package.json
root/package.json
ui/package.json

- Release v1.2.0
- Update RELEASE.md to reflect changes with single-spa

Release v1.2.0

---

ui/src/app/base/components/TableDeleteConfirm/TableDeleteConfirm.js
ui/src/app/base/components/TableDeleteConfirm/__snapshots__/TableDeleteConfirm.test.js.snap
ui/src/app/settings/views/Scripts/ScriptsUpload/ScriptsUpload.js
ui/src/app/settings/views/Scripts/ScriptsUpload/ScriptsUpload.test.js

2.8 backport of https://github.com/canonical-web-and-design/maas-ui/pull/1223 (already reviewed/QA'd)

Add application/x-shellscript mimetype to fileupload accept.

---

legacy/package.json
package.json
proxy/package.json
root/package.json
shared/package.json
ui/package.json

- Release maas-ui v1.3.0 which will be the release intended for MAAS v2.8.0.

Release v1.3.0

---

legacy/package.json
legacy/src/app/directives/boot_images.js
legacy/src/app/directives/tests/test_boot_images.js
legacy/src/app/partials/boot-images.html
package.json
proxy/package.json
root/package.json
root/src/index.ejs
root/src/root-application.js
shared/package.json
shared/src/components/Header/Header.js
shared/src/components/Header/Header.test.js
ui/package.json

- Cherry-picked commits from #1243, #1244 and #1245 
- Update package.json versions

Release v1.3.2

---

legacy/package.json
package.json
proxy/package.json
root/package.json
shared/package.json
ui/package.json

Release v1.3.3.

---

.github/pull_request_template.md
HACKING.md
legacy/HACKING.md

- Updated the instructions for setting up and developing maas-ui.
- Improved the PR template instructions.
Fixes https://github.com/canonical-web-and-design/MAAS-squad/issues/1991.

Improve hacking doc and pr template

---

legacy/package.json
package.json
proxy/package.json
root/package.json
shared/package.json
ui/package.json

- Update package.json versions to 1.3.4
- N/A

Release v1.3.4

---

ui/package.json
yarn.lock

- Add types for classnames.
- None

Add types for classnames.

---

legacy/src/app/services/region.js
legacy/src/app/services/tests/test_region.js
legacy/src/app/testing/websocket.js

- Backport https://github.com/canonical-web-and-design/maas-ui/pull/1251 and https://github.com/canonical-web-and-design/maas-ui/pull/1253

Backport ws fixes

---

.github/pull_request_template.md

This may need some discussion.
- Add section to PR template explaining backport process.

Add section to PR template explaining backports

---

ui/.betterer.results
ui/src/app/base/selectors/auth/auth.test.js
ui/src/app/base/selectors/user/user.test.js
ui/src/testing/factories/index.ts
ui/src/testing/factories/model.ts
ui/src/testing/factories/nodes.ts
ui/src/testing/factories/state.ts
ui/src/testing/factories/user.ts

- Added factories for user and auth types.
- Updated selector tests to use the user state factory
Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/1357.

Create factories for user and auth models

---

ui/.betterer.results
ui/src/app/base/selectors/auth/auth.test.js
ui/src/app/base/selectors/messages/messages.test.js
ui/src/app/base/selectors/notification/notification.test.js
ui/src/app/base/selectors/user/user.test.js
ui/src/app/store/message/types.ts
ui/src/app/store/notification/types.ts
ui/src/testing/factories/index.ts
ui/src/testing/factories/message.ts
ui/src/testing/factories/notification.ts
ui/src/testing/factories/state.ts

- Added types and factories for notification and message.## Fixes
Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/1359.

Notification and message types

---

ui/src/app/base/selectors/general/architectures.test.js
ui/src/app/base/selectors/general/componentsToDisable.test.js
ui/src/app/base/selectors/general/defaultMinHweKernel.test.js
ui/src/app/base/selectors/general/hweKernels.test.js
ui/src/app/base/selectors/general/knownArchitectures.test.js
ui/src/app/base/selectors/general/machineActions.test.js
ui/src/app/base/selectors/general/navigationOptions.test.js
ui/src/app/base/selectors/general/osInfo.test.js
ui/src/app/base/selectors/general/pocketsToDisable.test.js
ui/src/app/base/selectors/general/powerTypes.test.js
ui/src/app/base/selectors/general/version.test.js
ui/src/app/machines/views/MachineList/MachineListHeader/ActionFormWrapper/ActionFormWrapper.tsx
ui/src/app/machines/views/MachineList/MachineListHeader/ActionFormWrapper/DeployForm/DeployForm.tsx
ui/src/app/machines/views/MachineList/MachineListHeader/MachineListActionMenu/MachineListActionMenu.tsx
ui/src/app/machines/views/MachineList/MachineListHeader/MachineListHeader.tsx
ui/src/app/store/general/types.ts
ui/src/app/store/machine/types.ts
ui/src/testing/factories/general.ts
ui/src/testing/factories/index.ts
ui/src/testing/factories/state.ts

- Add types and factories for all general API data.
Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/1356.

Add types and factories for general.

---

legacy/src/app/controllers/node_details.js

- Don't try and load the action for a node until it is fully loaded.
- Visit a machine e.g. /MAAS/l/machine/76pa3f
- Stop the server
- Wait a few seconds and start it again
- When the ws reconnects again you should not see the error
Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/1399.

Fix: Unknown data: undefined

---

legacy/src/app/controllers/node_details_networking.js
legacy/src/app/partials/node-details.html

- Forward port #1434 from 2.7 branch

add vlan check to displaying disconnected-icon

---

.github/labeler.yml
.github/workflows/labeler.yaml

- Add "Review: Code needed" and "Review: QA needed" labels by default.
- Add "Maintenance" label for dependency changes.
- Add "Legacy" label for changes to the legacy app.
Fixes: # . …

chore(CI): Add github labeler action.

---

.github/workflows/lp-to-gh-issues.yml
scripts/lp-bugs-to-gh-issues.py

- Remove "Python set up" step from LP to GH issue mitigator action
- Import os for environment variables 
Check the code. The action is likely to fail due to a lack of an LP bot account which I will request.

Import os migrate script

---

.github/workflows/lp-to-gh-issues.yml

- Add "Python set up" step from LP to GH issue mitigator action
Check the code.

Add Python action to set up with version 3.8

---

ui/src/__snapshots__/root-reducer.test.js.snap
ui/src/app/base/components/ActionForm/ActionForm.tsx
ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/ComposeForm.tsx
ui/src/app/store/pod/actions.test.ts
ui/src/app/store/pod/reducers.test.ts
ui/src/app/store/pod/slice.ts
ui/src/app/store/pod/types.ts
ui/src/app/store/types/state.ts
ui/src/app/store/utils/index.ts
ui/src/app/store/utils/selectors.ts
ui/src/app/store/utils/slice.test.ts
ui/src/app/store/utils/slice.ts
ui/src/testing/factories/state.ts

- Create a generic slice util.
- Migrate the Pod slice to use the util.
- Have a poke around the /r/kvm area, all should function as before.
Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/1402.

Generic slice util

---

README.md
package.json
yarn.lock

- Add commitizen, a utility for making commits using the conventional commit format, via "yarn
commit".
- Update the Contributing section of README with relevant information for formatting commits.
- n/a
Fixes: # .
In general, please propose fixes against *master* rather than …

feat(workspace): Add commitizen.

---

ui/src/app/store/pod/slice.ts
ui/src/app/store/utils/index.ts
ui/src/app/store/utils/slice.test.ts
ui/src/app/store/utils/slice.ts

- Define the Slice types and overrides for the inferred types.

Define return types for slices

---

scripts/lp-bugs-to-gh-issues.py

- Updated the status filter from the bug search to include all bugs with the status New, Confirmed and Triaged.
- Check the code.

fix(scripts): Find all "ui" bugs in all statuses

---

ui/src/app/base/components/DoughnutChart/DoughnutChart.test.tsx
ui/src/app/base/components/DoughnutChart/DoughnutChart.tsx
ui/src/app/base/components/DoughnutChart/__snapshots__/DoughnutChart.test.tsx.snap
ui/src/app/base/components/DoughnutChart/_index.scss
ui/src/app/base/components/DoughnutChart/index.ts
ui/src/app/base/constants.ts
ui/src/app/kvm/components/KVMResourcesCard/KVMResourcesCard.test.tsx
ui/src/app/kvm/components/KVMResourcesCard/KVMResourcesCard.tsx
ui/src/app/kvm/components/KVMResourcesCard/__snapshots__/KVMResourcesCard.test.tsx.snap
ui/src/app/kvm/components/KVMResourcesCard/_index.scss
ui/src/scss/index.scss

- Create a doughnut chart for the KVM pages.
- Visit a kvm details page.
- You should see a doughnut chart.
- Hovering the doughnut should raise a section and show a tooltip.
Fixes: canonical-web-and-design/maas-squad#2073

feat(ui): build a doughnut chart component

---

ui/src/app/base/sagas/websockets.js

- Correctly check for params when dispatching fetches.
- Load the machine list.
- In the redux devtools check that there are no fetchError events immediately after fetch or fetchStart.
Fixes: canonical-web-and-design/maas-ui#1679

fix(ui): fix dispatching errors when fetching

---

ui/.eslintrc.js

- Raise the level for unused variables to an error.
- Add an unused variable in a js file and a ts file.
- Run `lint-ui`.
- You should see an error for both files.

ci(ui): fail lint for unused variables

---

ui/package.json
ui/src/app/base/sagas/http.test.js
ui/src/setupTests.js
yarn.lock

- Test that the login api method encodes special chars.
No QA. Tests should pass.
Fixes: canonical-web-and-design/maas-ui#753

test(ui): add a test for login with special chars

---

integration/cypress/integration/legacy/auth.spec.ts
integration/cypress/integration/login/login.spec.ts
integration/cypress/integration/machines/add.spec.ts
integration/cypress/integration/machines/list.spec.ts
integration/cypress/integration/settings/users/add.spec.ts
integration/cypress/integration/settings/users/list.spec.ts
integration/cypress/integration/utils.ts
yarn.lock

- Add Cypress tests for logging in and authentication from legacy.
No QA, CI should pass.
Fixes: canonical-web-and-design/maas-ui#992.
Fixes: canonical-web-and-design/maas-ui#429.

test(cypress): add authentication tests

---

legacy/src/app/partials/boot-images.html
legacy/src/app/partials/cards/images.html
legacy/src/app/partials/cards/machine-overview.html
legacy/src/app/partials/cards/memory.html
legacy/src/app/partials/dashboard.html
legacy/src/app/partials/directives/cta.html
legacy/src/app/partials/directives/os-select.html
legacy/src/app/partials/directives/power-parameters.html
legacy/src/app/partials/domain-details.html
legacy/src/app/partials/domains-list.html
legacy/src/app/partials/error.html
legacy/src/app/partials/intro-user.html
legacy/src/app/partials/node-result.html
legacy/src/app/partials/nodedetails/storage/disks-partitions.html
legacy/src/app/partials/nodedetails/storage/filesystems.html
legacy/src/app/partials/nodes-list.html
legacy/src/app/partials/ssh-keys.html
legacy/src/app/partials/subnet-details.html

- Fix broken markup in angularjs partials. 
- n/a
Fixes: # .
In general, please propose fixes against *master* rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. Please apply backport labels to the PR (e.g. "Backport 2.7") …

fix(legacy): fix broken markup in angularjs templates

---

yarn.lock

- Rebuilt the yarn lock file (just rm `yarn.lock && yarn install`).

build(yarn): rebuild yarn.lock

---

renovate.json

- Add the config option to have a dependency dashboard for Renovate: https://docs.renovatebot.com/configuration-options/#dependencydashboard.

build(yarn): add Renovate Dependency dashboard

---

ui/.betterer.results
ui/src/app/base/hooks.ts
ui/src/app/kvm/views/KVMList/AddKVMForm/AddKVMForm.tsx
ui/src/app/kvm/views/KVMList/KVMListTable/KVMListTable.test.tsx
ui/src/app/kvm/views/KVMList/KVMListTable/KVMListTable.tsx
ui/src/app/machines/views/AddChassis/AddChassisForm/AddChassisForm.js
ui/src/app/machines/views/AddMachine/AddMachineForm/AddMachineForm.js
ui/src/app/machines/views/AddRSD/AddRSDForm/AddRSDForm.js
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTable.tsx
ui/src/app/pools/views/PoolForm/PoolForm.js
ui/src/app/pools/views/Pools.js
ui/src/app/rsd/views/RSDList/AddRSDForm/AddRSDForm.tsx
ui/src/app/rsd/views/RSDList/RSDListTable/RSDListTable.test.tsx
ui/src/app/rsd/views/RSDList/RSDListTable/RSDListTable.tsx
ui/src/app/settings/views/Dhcp/DhcpForm/DhcpForm.js
ui/src/app/settings/views/Dhcp/DhcpList/DhcpList.js
ui/src/app/settings/views/LicenseKeys/LicenseKeyForm/LicenseKeyForm.js
ui/src/app/settings/views/LicenseKeys/LicenseKeyList/LicenseKeyList.js
ui/src/app/settings/views/Repositories/RepositoriesList/RepositoriesList.js
ui/src/app/settings/views/Repositories/RepositoryForm/RepositoryForm.js
ui/src/app/settings/views/Scripts/ScriptsList/ScriptsList.tsx
ui/src/app/settings/views/Users/UserForm/UserForm.tsx
ui/src/app/settings/views/Users/UsersList/UsersList.js

- Update the base hooks to use TypeScript.
n/a
Fixes: canonical-web-and-design/maas-ui#1869.

refactor(ui): convert base hooks to typescript

---

ui/.betterer.results
ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AvailableStorageTable.test.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AvailableStorageTable.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/EditPhysicalDisk/EditPhysicalDisk.test.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/EditPhysicalDisk/EditPhysicalDisk.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/EditPhysicalDisk/EditPhysicalDiskFields/EditPhysicalDiskFields.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/EditPhysicalDisk/EditPhysicalDiskFields/index.ts
ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/EditPhysicalDisk/index.ts

- Built edit physical disk form
- Open the action dropdown for a physical disk and select "Edit physical disk"
- Change the tags and submit the form
- Check that the tags are updated correctly
Fixes canonical-web-and-design/MAAS-squad#2294

feat(ui): build edit physical disk form

---

legacy/package.json
proxy/package.json
root/package.json
ui/package.json

Release 2.0.1
Fixes: # .
In general, please propose fixes against *master* rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. Please apply backport labels to the PR (e.g. "Backport 2.7") for the appropriate …

Release 2.0.1

---

ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AvailableStorageTable.tsx

- Added free disk space to storage table
- Go to the storage tab of a machine in Ready or Allocated state
- Check that the disk shows the amount of free space
- Partition the disk and check that the free space changes accordingly
Fixes canonical-web-and-design/MAAS-squad#2323

feat(ui): add free disk space to storage table

---

.github/workflows/upload.yml

Run upload on pr closed

---

.github/workflows/upload.yml

ci: use github context for upload workflow

---

ui/src/app/machines/components/TagLinks/TagLinks.tsx
ui/src/app/machines/filter-nodes.test.ts
ui/src/app/machines/filter-nodes.ts
ui/src/app/machines/search.test.ts
ui/src/app/machines/search.ts
ui/src/app/machines/views/MachineDetails/MachineSummary/WorkloadCard/WorkloadCard.tsx
ui/src/app/pools/views/Pools.js
ui/src/app/store/machine/selectors.ts

- Convert the search utilities to TypeScript.
n/a tests should pass.

refactor(ui): convert search utilities to typescript

---

.github/workflows/lp-to-gh-issues.yml

Update the cadence of the LP to GH script run to hourly
- Check the code update is correct

Update the LP to GH to be hourly

---

ui/src/app/store/machine/utils/index.ts
ui/src/app/store/machine/utils/networking.test.ts
ui/src/app/store/machine/utils/networking.ts

- Add a util to generate the next available interface name.
N/A
Fixes: #2183.

feat(ui): add interface name generator

---

ui/src/app/store/machine/actions.test.ts
ui/src/app/store/machine/selectors.test.ts
ui/src/app/store/machine/selectors.ts
ui/src/app/store/machine/slice.ts
ui/src/app/store/machine/types.ts
ui/src/app/store/subnet/types.ts
ui/src/testing/factories/state.ts

- Add support for creating physical interfaces via the api.
- Add selector for fetching the creating interface status.
N/A
Fixes: #2181.

feat(ui): add action for creating a physical interface

---

ui/src/app/machines/views/MachineDetails/MachineTests/MachineTestsTable/MachineTestsTable.tsx
ui/src/app/machines/views/MachineDetails/MachineTests/MachineTestsTable/__snapshots__/MachineTestsTable.test.tsx.snap
ui/src/app/machines/views/MachineDetails/MachineTests/MachineTestsTable/index.scss
ui/src/scss/index.scss

Align the machine test table columns
- Go to a machine details
- Go to Tests and see the tests table columns are better spaced
Fixes: https://github.com/canonical-web-and-design/MAAS-squad/issues/2196

fix(ui) align the machine test table columns

---

ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTableConfirmation/NetworkTableConfirmation.tsx
ui/src/app/store/machine/actions.test.ts
ui/src/app/store/machine/slice.ts

- Update the actions for creating and updating interfaces to be consistent.
- Go to a machine with editable network.
- Add an interface. It should be created correctly.
- Edit the interface. It should save your changes.
Fixes: #2197.

refactor(ui): make adding and updating interface actions consistent

---

ui/src/app/store/machine/slice.ts
ui/src/app/store/machine/types.ts
ui/src/testing/factories/state.ts

- Add support for creating a bridge via the API.
N/A
Fixes: #2219.

feat(ui): add api action for creating a bridge

---

ui/src/app/store/machine/actions.test.ts
ui/src/app/store/machine/slice.ts
ui/src/app/store/machine/types.ts
ui/src/testing/factories/state.ts

- Add the action to be able to create a bond via the API.
N/A
Fixes: #2218.

feat(ui): add api support for creating a bond

---

ui/src/app/store/machine/actions.test.ts
ui/src/app/store/machine/types.ts

- Remove duplicate bond types.
N/A
Fixes: #2351.

refactor(ui): dedupe bond types

---

ui/.betterer.results
ui/src/app/machines/views/MachineDetails/MachineNetwork/BondForm/BondModeSelect/BondModeSelect.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/BondForm/BondModeSelect/BondModeSelect.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/BondForm/BondModeSelect/index.ts
ui/src/app/machines/views/MachineDetails/MachineNetwork/BondForm/HashPolicySelect/HashPolicySelect.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/BondForm/HashPolicySelect/HashPolicySelect.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/BondForm/HashPolicySelect/index.ts
ui/src/app/machines/views/MachineDetails/MachineNetwork/BondForm/LACPRateSelect/LACPRateSelect.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/BondForm/LACPRateSelect/LACPRateSelect.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/BondForm/LACPRateSelect/index.ts
ui/src/app/store/general/selectors/bondOptions.ts

- Add select fields for bond options.
N/A
Fixes: #2355.

feat(ui): add bond option fields

---

ui/src/app/machines/views/MachineDetails/MachineTests/MachineTestsDetails/MachineTestsDetailsLogs.test.tsx
ui/src/app/store/scriptresult/selectors.test.tsx
ui/src/app/store/scriptresult/selectors.ts
ui/src/testing/factories/index.ts
ui/src/testing/factories/scriptResult.ts

- Add selectors for fetching installation logs.
N/A
Fixes: canonical-web-and-design/maas-squad#2365.

feat(ui): add installation log selectors

---

ui/src/__snapshots__/root-reducer.test.js.snap
ui/src/app/machines/views/MachineDetails/MachineSummary/SummaryNotifications/SummaryNotifications.tsx
ui/src/app/store/event/actions.test.ts
ui/src/app/store/event/index.ts
ui/src/app/store/event/reducers.test.ts
ui/src/app/store/event/selectors.test.ts
ui/src/app/store/event/selectors.ts
ui/src/app/store/event/slice.ts
ui/src/app/store/event/types.ts
ui/src/app/store/machine/types.ts
ui/src/app/store/root/types.ts
ui/src/root-reducer.js
ui/src/testing/factories/event.ts
ui/src/testing/factories/index.ts
ui/src/testing/factories/nodes.ts
ui/src/testing/factories/state.ts

- Add the slice and selectors for the events model.
N/A
Fixes: canonical-web-and-design/maas-squad#2366.

feat(ui): add event slice

---

integration/package.json
legacy/package.json
package.json
proxy/package.json
root/package.json
shared/package.json
ui/package.json

- Update the version numbers for the 2.1.0 [2.9.3] release.
N/A
Fixes: canonical-web-and-design/MAAS-squad#2376.

build(all): prepare 2.1.0 [2.9.3] release

---

yarn.lock

- Rebuild the yarn lock to get Betterer working again.
N/A CI should pass.
Fixes: #2442.

build(all): rebuild yarn lock

---

legacy/src/app/controllers/nodes_list.js
legacy/src/app/controllers/tests/test_nodes_list.js
legacy/src/app/partials/nodes-list.html
legacy/src/scss/_maas.scss

- Remove machine and pools code from the nodes list. 
- Fix updating the selected controllers. 
- Fix the script selector for controllers.
You might need sampledata to get more controllers for these tests.
- Visit the controllers list.
- Select all controllers.
- Open the take action menu and select an action that no all controllers can do.
- It should show …

refactor(legacy): clean up nodes list code

---

legacy/src/app/partials/node-details.html

- Remove legacy machine details tabs.
- View the controller and device details. The tabs should not have changed.
Fixes: #2539.

refactor(legacy): remove machine tab

---

legacy/src/app/controllers/node_details.js
legacy/src/app/controllers/tests/test_node_details.js
legacy/src/app/partials/node-details.html

- Remove the options for configuring machines from legacy details.
- Go to Controllers/Devices details configuration tab and make sure you can change the zone or tags.
Fixes: #2540.

refactor(legacy): remove legacy machine config

---

legacy/src/app/partials/cards/controller.html
legacy/src/app/partials/nodes-list.html
ui/src/app/store/controller/types.ts
ui/src/testing/factories/nodes.ts

- Use the new format for controller versions.
- Visit the controller list, you should see the version in the version column.
- Click on a controller.
- In the overview card you should see the controller version.
Fixes: #2547.

fix(all): update controller versions

---

shared/src/components/Header/Header.tsx
ui/src/app/machines/components/ActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.test.tsx
ui/src/app/machines/components/ActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.tsx
ui/src/app/machines/views/MachineDetails/MachineSummary/NumaCard/__snapshots__/NumaCard.test.tsx.snap
ui/src/app/store/auth/reducers.test.ts
ui/src/app/store/auth/selectors.test.ts
ui/src/app/store/auth/selectors.ts
ui/src/app/store/user/types.ts
ui/src/testing/factories/state.ts

- Enable and fix up auth tests.
N/A
Fixes: #2556.

refactor(ui): fix auth tests

---

legacy/src/app/partials/nodelist/notifications.html
legacy/src/scss/_patterns_notification.scss

- Handle upgrade notifications in the Angular client.
- SSH to bolla.
- Log in to the MAAS CLI (`maas login [PROFILE_NAME] http://localhost:5240/MAAS/`).
- To make the following commands easer run `export PROFILE_NAME=[PROFILE_NAME_FROM_LOGIN]`.
- Run:
```
maas $PROFILE_NAME notifications create ident='upgrade_version_issue' category='warning' users=true admins=true dismissable=false message='MAAS 2.9.3 is available but multiple controller versions are detected. <a href="/MAAS/l/controllers">Review controllers.</a>.'
```
- Then run:
```
maas $PROFILE_NAME notifications create …
```

feat(legacy): add legacy upgrade notifications

---

ui/src/app/base/components/FormCardButtons/FormCardButtons.tsx
ui/src/app/machines/components/ActionFormWrapper/ReleaseForm/ReleaseForm.tsx
ui/src/app/machines/components/ActionFormWrapper/SetPoolForm/SetPoolForm.js
ui/src/app/machines/components/ActionFormWrapper/SetPoolForm/SetPoolForm.test.js
ui/src/app/machines/views/MachineList/MachineListTable/OwnerColumn/OwnerColumn.js
ui/src/app/machines/views/MachineList/MachineListTable/PoolColumn/PoolColumn.js
ui/src/app/machines/views/MachineList/MachineListTable/ZoneColumn/ZoneColumn.js
ui/src/scss/_patterns_buttons.scss

- Fixed issues that came up when doing the [machine list QA](https://github.com/canonical-web-and-design/maas-squad/issues/2402) 
- Check that the following issues have been fixed:
Fixes canonical-web-and-design/MAAS-squad#2402

fix(ui): machine list QA fixes

---

legacy/src/app/controllers/nodes_list.js
legacy/src/app/controllers/tests/test_nodes_list.js
legacy/src/app/partials/nodes-list.html
legacy/src/scss/tables/_patterns_table-controllers.scss

- Add the available upgrade column to the controller list.
- Point your UI to Bolla and go to the controllers list.
- You should see an "Available versions" column and an upgrade should show up (if not let me know and I might need to update the backend again).
Fixes: #2491.

feat(legacy): add available upgrade column

---

legacy/src/app/controllers/nodes_list.js
legacy/src/app/controllers/tests/test_nodes_list.js
legacy/src/app/partials/nodes-list.html
ui/src/app/store/controller/types.ts

- Display the snap channel and cohort key in the controller list.
- Update the version types.
- Point your UI to Bolla.
- View the controller list.
- You should see the channel and cohort key in the version column.
Fixes: #2490.
Fixes: #2517.

feat(legacy): display snap channel

---

ui/src/app/machines/views/MachineDetails/MachineSummary/WorkloadCard/WorkloadCard.tsx
ui/src/app/machines/views/MachineDetails/NodeDevices/NodeDevicesWarning/NodeDevicesWarning.tsx

- Change the wording from "unavailable" to something that doesn't sound as temporary.
N/A
Fixes: #2648.

feat(ui): change use of "unavailable"

---

ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/InterfacesTable/InterfacesTable.test.tsx
ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/InterfacesTable/InterfacesTable.tsx
ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/InterfacesTable/SubnetSelect/SubnetSelect.test.tsx
ui/src/app/store/subnet/selectors.test.ts
ui/src/app/store/subnet/selectors.ts

fix(ui): preselect first PXE network when defining composed VM interface (backport 3.0)

---

renovate.json

- Add prettier to list of dependencies that get their own renovate PR
- N/A

chore(deps): add prettier to list of dependencies that get their own renovate PR

---

.github/workflows/cypress.yml
.github/workflows/test.yml

- Run CI against the 2.9 branch.

ci(ci): run actions against the 2.9 branch

---

.github/workflows/test.yml
legacy/src/app/controllers/node_details.js
legacy/src/app/directives/pod-details/kvm_storage_dropdown.js
legacy/src/app/factories/nodes.js

- Run CI against the 2.8 branch.

Run actions against the 2.8 branch.

---

ui/src/app/store/machine/actions.test.ts
ui/src/app/store/machine/slice.ts

- Update the machine slice to use the util for optional params.
N/A
Fixes: #2377.

refactor(ui): use util for optional params

---

ui/src/app/machines/components/ActionFormWrapper/CommissionForm/CommissionForm.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/AddAliasOrVlan/AddAliasOrVlan.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/EditBondForm/EditBondForm.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTableConfirmation/NetworkTableConfirmation.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/CreateBcache/CreateBcache.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/ChangeStorageLayout/ChangeStorageLayout.tsx
ui/src/app/store/machine/actions.test.ts
ui/src/app/store/machine/slice.ts
ui/src/app/store/pod/actions.test.ts
ui/src/app/store/pod/slice.ts
ui/src/app/store/utils/slice.test.ts
ui/src/app/store/utils/slice.ts
ui/tsconfig.json

- Replace the initial status reducers with a normal provide functions.
- Perform some actions from the machine list and kvm list and they should work without errors.
Fixes: #2701.

refactor(ui): improve status reducers

---

ui/.betterer.results
ui/src/app/machines/components/ActionFormWrapper/OverrideTestForm/OverrideTestForm.test.tsx
ui/src/app/machines/components/ActionFormWrapper/SetPoolForm/SetPoolForm.test.tsx
ui/src/app/machines/components/ActionFormWrapper/SetZoneForm/SetZoneForm.test.tsx
ui/src/app/machines/components/ActionFormWrapper/TagForm/TagForm.test.tsx
ui/src/app/machines/views/MachineList/MachineList.test.tsx
ui/src/app/machines/views/MachineList/MachineListHeader/MachineListHeader.test.tsx
ui/src/app/machines/views/Machines.test.tsx

- Migrate the test files for some machine list components to typescript.
N/A
Fixes: #2717.

refactor(ui): migrate machine list tests to typescript

---

ui/src/app/Routes.tsx
ui/src/app/dashboard/urls.ts
ui/src/app/dashboard/views/Dashboard.tsx

Created initial dashboard view
- Go to http://0.0.0.0:8400/MAAS/r/dashboard
- Check you see a view that matches the screenshot below
Fixes: https://github.com/canonical-web-and-design/app-squad/issues/62

Add initial dashboard view

---

ui/src/app/Routes.tsx
ui/src/app/zones/urls.ts
ui/src/app/zones/views/Zones.tsx

- Add route for zones list at `/zones`
- Run `yarn ui` and go to http://0.0.0.0:8400/MAAS/r/zones
- Check you can see the Availability zones header

Add zones-list route and view

---

ui/src/app/dashboard/views/Dashboard.tsx
ui/src/app/dashboard/views/DiscoveriesList/DiscoveriesList.tsx
ui/src/app/dashboard/views/DiscoveriesList/index.ts
ui/src/app/dashboard/views/DiscoveriesListHeader/DiscoveriesListHeader.tsx
ui/src/app/dashboard/views/DiscoveriesListHeader/index.ts

Created dashboard header
- Go to http://0.0.0.0:8400/MAAS/r/dashboard
- Check there is a standard header with the title "Network discovery"
Fixes https://github.com/canonical-web-and-design/app-squad/issues/63

Add basic dashboard header

---

ui/.betterer.results
ui/src/app/base/components/FormikFormContent/FormikFormContent.test.tsx
ui/src/app/base/urls.ts
ui/src/app/base/validation.ts
ui/src/app/domains/views/DomainDetails/DomainsDetails.test.tsx
ui/src/app/domains/views/DomainsList/DomainListHeader/DomainListHeader.test.tsx
ui/src/app/domains/views/DomainsList/DomainListHeaderForm/DomainListHeaderForm.test.tsx
ui/src/app/domains/views/DomainsList/DomainListHeaderForm/DomainListHeaderForm.tsx
ui/src/app/domains/views/DomainsList/DomainsTable/DomainsTable.tsx
ui/src/app/zones/views/ZonesListForm/ZonesListForm.test.tsx
ui/src/app/zones/views/ZonesListForm/ZonesListForm.tsx
ui/src/app/zones/views/ZonesListHeader/ZonesListHeader.test.tsx
ui/src/app/zones/views/ZonesListTable/ZonesListTable.tsx

- Fixed up some minor issues in the domain and zone components
- Go to /MAAS/r/zones
- Check that you can add a zone with a description
- Check that trying to add another zone with the same name results in error
- Check that closing and opening the form again removes the error
- Go to /MAAS/r/domains
- Check that you can add a …

fix(ui): sprint cleanup Jun 10

---

ui/src/app/Routes.tsx
ui/src/app/zones/urls.ts
ui/src/app/zones/views/ZoneDetails/ZoneDetails.tsx
ui/src/app/zones/views/ZoneDetails/index.ts
ui/src/app/zones/views/Zones.tsx

- Add route and basic view for zone details
- run `yarn start` and go to 
- Check you can see the zone details header

Add zone detail route and basic component

---

ui/src/app/dashboard/urls.ts
ui/src/app/dashboard/views/Dashboard.tsx
ui/src/app/dashboard/views/DashboardConfigurationForm/DashboardConfigurationForm.tsx
ui/src/app/dashboard/views/DashboardConfigurationForm/index.ts
ui/src/app/dashboard/views/DiscoveriesListHeader/DiscoveriesListHeader.tsx

- Created network discovery form in configuration view
- Go to the [configuration page](http://0.0.0.0:8400/MAAS/r/dashboard/configuration)
- Check that the selection boxes work and update appropriately.

Add dashboard configuration view

---

ui/.betterer.results
ui/src/app/zones/views/ZoneDetails/ZoneDetails.tsx
ui/src/app/zones/views/ZoneDetails/ZoneDetailsContent/ZoneDetailsContent.tsx
ui/src/app/zones/views/ZoneDetails/ZoneDetailsContent/index.ts
ui/src/app/zones/views/ZoneDetails/ZoneDetailsForm/ZoneDetailsForm.test.tsx
ui/src/app/zones/views/ZoneDetails/ZoneDetailsForm/ZoneDetailsForm.tsx
ui/src/app/zones/views/ZoneDetails/ZoneDetailsForm/index.ts
ui/src/app/zones/views/ZoneDetails/ZoneDetailsHeader/ZoneDetailsHeader.tsx
ui/src/app/zones/views/ZoneDetails/ZoneDetailsHeader/ZonesDetailsHeader.test.tsx

- Added zone details content
- Added edit form
- Added form tests
- Visit http://0.0.0.0:8400/MAAS/r/zones
- Click any of the zones
- See that the details of the zone are listed there
- Click "Edit AZ"
- Update the form with whatever values you like, then click "Edit AZ", see that the changes are reflected in the details content page
- See that CI tests pass

Add zone details page

---

ui/src/app/base/components/FormikFormContent/FormikFormContent.tsx
ui/src/app/zones/views/ZoneDetails/ZoneDetails.tsx
ui/src/app/zones/views/ZoneDetails/ZoneDetailsHeader/DeleteConfirm/DeleteConfirm.test.tsx
ui/src/app/zones/views/ZoneDetails/ZoneDetailsHeader/DeleteConfirm/DeleteConfirm.tsx
ui/src/app/zones/views/ZoneDetails/ZoneDetailsHeader/DeleteConfirm/index.ts
ui/src/app/zones/views/ZoneDetails/ZoneDetailsHeader/ZoneDetailsHeader.tsx
ui/src/app/zones/views/ZonesList/ZonesListHeader/ZonesListHeader.tsx

- Add delete zone action
- Add tests
- Visit http://0.0.0.0:8400/MAAS/r/zones
- Create a zone
- Click its name in the list
- Click "Delete AZ" and confirm when prompted
- See that the zone is not in the list

Add zone delete action

---

ui/src/app/domains/views/DomainDetails/DomainDetails.tsx
ui/src/app/domains/views/DomainDetails/DomainSummary/DomainSummary.tsx
ui/src/app/domains/views/DomainDetails/DomainSummary/index.ts
ui/src/app/domains/views/DomainDetails/ResourceRecords/ResourceRecords.tsx
ui/src/app/domains/views/DomainDetails/ResourceRecords/index.ts
ui/src/app/store/domain/types/base.ts

- Added domain summary and basic resource records table to domain details page
- Added basic domain resource type
- `yarn start`
- Go to http://localhost:8400/MAAS/r/domains
- click on available domains, check if their detail display as expected
- please note, details are not editable yet
Fixes: …

Add basic domain details

---

ui/src/app/dashboard/views/DiscoveriesList/DiscoveriesList.tsx

Added basic discoveries table
- Go to http://0.0.0.0:8400/MAAS/r/dashboard
- Check that there is a table that matches the legacy one http://bolla.internal:5240/MAAS/l/dashboard
- **NOTE: There are no actions**
Fixes https://github.com/canonical-web-and-design/app-squad/issues/66

Add discovery list table

---

integration/cypress/integration/zones/list.spec.ts

- Friendship ended with LEGACY AZS, now NEW ZONES is my best friend 
- N/A - Cypress should pass

test(cypress): fix zones Cypress tests but for real this time

---

ui/src/app/store/device/actions.test.ts
ui/src/app/store/device/reducers.test.ts
ui/src/app/store/device/slice.ts
ui/src/app/store/device/types/actions.ts
ui/src/app/store/device/types/index.ts

- Add an action to create a device interface.
N/A
Fixes: canonical-web-and-design/app-squad#133.

feat(ui): add device create interface action

---

.github/workflows/cypress.yml
.github/workflows/test.yml

- Run CI against the 3.0 branch.

ci(ci): run actions against the 3.0 branch

---

legacy/src/app/controllers/subnet_details.js
legacy/src/app/controllers/tests/test_subnet_details.js
legacy/src/app/factories/general.js
legacy/src/app/factories/subnets.js
legacy/src/app/factories/tests/test_general.js
legacy/src/app/factories/tests/test_subnets.js
legacy/src/app/partials/subnet-details.html
legacy/src/scss/tables/_base_tables.scss

- Backport of https://github.com/canonical-web-and-design/maas-ui/pull/2677

feat(legacy): allow disabling boot architectures in subnet details

---

ui/src/app/store/domain/selectors.test.ts
ui/src/app/store/domain/selectors.ts
ui/src/app/store/machine/selectors.test.ts
ui/src/app/store/machine/selectors.ts
ui/src/app/store/subnet/selectors.test.ts
ui/src/app/store/subnet/selectors.ts

- Add selectors required by the add discovery form.
N/A
Fixes: canonical-web-and-design/app-squad#139.

feat(ui): add selectors for the add discovery form

---

ui/.betterer.results
ui/src/app/dashboard/views/DashboardHeader/ClearAllForm/ClearAllForm.test.tsx
ui/src/app/dashboard/views/DashboardHeader/ClearAllForm/ClearAllForm.tsx
ui/src/app/dashboard/views/DashboardHeader/ClearAllForm/index.ts
ui/src/app/dashboard/views/DashboardHeader/DashboardHeader.test.tsx
ui/src/app/dashboard/views/DashboardHeader/DashboardHeader.tsx
ui/src/app/store/discovery/actions.test.ts
ui/src/app/store/discovery/slice.ts

- Add the clear all form to the dashboard header.
- Click the clear all button in the header.
- Submit and the list should get cleared.
Fixes: canonical-web-and-design/app-squad#65.

feat(ui): clear all form

---

ui/.betterer.results
ui/src/app/base/components/FormikFormContent/FormikFormContent.test.tsx
ui/src/app/base/components/FormikFormContent/FormikFormContent.tsx
ui/src/app/base/hooks.test.ts
ui/src/app/base/hooks.ts
ui/src/app/dashboard/views/DiscoveryAddForm/DiscoveryAddForm.test.tsx
ui/src/app/dashboard/views/DiscoveryAddForm/DiscoveryAddForm.tsx
ui/src/app/images/views/ImageList/ImageListHeader/ImageListHeader.tsx

- Show a message when a device has been added.
- Open a row menu and click "Add discovery" and click the green button.
- You should see a success message at the top of the list.
Fixes: canonical-web-and-design/app-squad#132.

feat(ui): add discovery success message

---

integration/cypress/integration/base/header.spec.ts
integration/cypress/integration/dashboard/dashboard.spec.ts

- Update integration test to React dashboard URL.
N/A

fix(ui): update integration test to React dashboard URL

---

legacy/package.json
legacy/src/scss/_patterns_tabs.scss
root/package.json
ui/package.json
ui/src/scss/_vanilla-overrides.scss
yarn.lock

- Upgrade to Vanilla 2.31.0.
- Open the machine list and check that the tabs don't cover the border above it.
- Load the controller details and check that the tabs don't cover the border above it.
- Have a look around and make sure nothing else is broken.

build(all): upgrade to Vanilla 2.31.0

---

ui/src/app/base/components/DynamicSelect/DynamicSelect.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/AddBondForm/AddBondForm.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/AddBondForm/AddBondForm.tsx

Backport: https://github.com/canonical-web-and-design/maas-ui/pull/2882.

fix(ui): select the VLAN when creating a bond

---

integration/cypress/integration/base/header.spec.ts
integration/cypress/integration/images/list.spec.ts
integration/cypress/integration/login/login.spec.ts
ui/src/app/App.tsx
ui/src/app/intro/views/Intro.tsx

- Updated intro and images cypress tests to point to the react versions
- Updated intro pages to take cookies into account when redirecting
- N/A - tests should pass

fix(cypress): fix images and intro Cypress tests

---

integration/cypress/integration/base/footer.spec.ts
integration/cypress/integration/base/header.spec.ts
integration/cypress/integration/dashboard/dashboard.spec.ts
integration/cypress/integration/domains/list.spec.ts
integration/cypress/integration/images/list.spec.ts
integration/cypress/integration/kvm/list.spec.ts
integration/cypress/integration/legacy/controllers.spec.ts
integration/cypress/integration/legacy/devices.spec.ts
integration/cypress/integration/legacy/subnets.spec.ts
integration/cypress/integration/login/login.spec.ts
integration/cypress/integration/machines/add.spec.ts
integration/cypress/integration/machines/list.spec.ts
integration/cypress/integration/pools/list.spec.ts
integration/cypress/integration/preferences/base.spec.ts
integration/cypress/integration/settings/base.spec.ts
integration/cypress/integration/settings/users/add.spec.ts
integration/cypress/integration/settings/users/list.spec.ts
integration/cypress/integration/utils.ts
integration/cypress/integration/zones/list.spec.ts
ui/.betterer.results
ui/src/app/App.tsx
ui/src/app/base/hooks.test.tsx
ui/src/app/base/hooks.ts
ui/src/app/intro/views/Intro.tsx
ui/src/app/intro/views/UserIntro/UserIntro.tsx
ui/src/app/store/auth/selectors.test.ts
ui/src/app/store/auth/selectors.ts
ui/src/app/store/config/selectors.test.ts
ui/src/app/store/config/selectors.ts
ui/src/app/store/status/slice.ts

- Properly set and clear cookies in Cypress tests. Originally it was only setting one of the cookies.
- Moved cookie-handling to custom hooks rather than in each individual component.
- N/A - Cypress tests should pass

fix(cypress): fix cookies being set in cypress tests

---

ui/src/app/base/components/Login/Login.test.tsx
ui/src/app/base/components/Login/Login.tsx
ui/src/app/store/status/selectors.ts

- migrate login component to TypeScript.
N/A

refactor(ui): migrate login component to TypeScript

---

ui/src/app/base/components/TableHeader/TableHeader.test.tsx
ui/src/app/base/components/TableHeader/TableHeader.tsx
ui/src/app/base/hooks.ts
ui/src/app/base/types.ts
ui/src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsTable/VMsTable.tsx
ui/src/app/kvm/views/KVMList/LxdTable/LxdTable.tsx
ui/src/app/kvm/views/KVMList/VirshTable/VirshTable.test.tsx
ui/src/app/kvm/views/KVMList/VirshTable/VirshTable.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/NetworkTable.tsx
ui/src/app/machines/views/MachineList/MachineListTable/MachineListTable.js
ui/src/app/settings/views/Users/UsersList/UsersList.js

- migrate TableHeader to TypeScript
N/A

refactor(ui): migrate TableHeader to TypeScript

---

ui/src/app/base/sagas/http.test.ts
ui/src/app/base/sagas/http.ts
ui/src/app/utils/getCookie.test.ts
ui/src/app/utils/getCookie.ts

- convert HTTP sagas to TypeScript
N/A

refactor(ui): convert HTTP sagas to TypeScript

---

ui/src/app/pools/views/PoolAdd/PoolAdd.test.tsx
ui/src/app/pools/views/PoolAdd/PoolAdd.tsx
ui/src/app/pools/views/PoolEdit/PoolEdit.tsx
ui/src/app/pools/views/PoolForm/PoolForm.test.tsx
ui/src/app/pools/views/PoolForm/PoolForm.tsx
ui/src/app/pools/views/Pools.test.tsx
ui/src/app/pools/views/Pools.tsx

- migrate pool components to TypeScript
N/A

refactor(ui): migrate pool components to TypeScript

---

ui/src/app/machines/components/ActionFormWrapper/CommissionForm/CommissionForm.tsx
ui/src/app/machines/components/ActionFormWrapper/CommissionForm/CommissionFormFields/CommissionFormFields.test.tsx
ui/src/app/machines/components/ActionFormWrapper/CommissionForm/CommissionFormFields/CommissionFormFields.tsx
ui/src/app/machines/components/ActionFormWrapper/CommissionForm/types.ts
ui/src/app/machines/components/ActionFormWrapper/SetPoolForm/SetPoolForm.tsx
ui/src/app/machines/components/ActionFormWrapper/SetPoolForm/SetPoolFormFields/SetPoolFormFields.test.tsx
ui/src/app/machines/components/ActionFormWrapper/SetPoolForm/SetPoolFormFields/SetPoolFormFields.tsx
ui/src/app/machines/components/ActionFormWrapper/SetPoolForm/types.ts
ui/src/app/machines/components/ActionFormWrapper/TagForm/TagFormFields/TagFormFields.test.tsx
ui/src/app/machines/components/ActionFormWrapper/TagForm/TagFormFields/TagFormFields.tsx

- migrate action form field components to TypeScript
N/A

refactor(ui): migrate action form field components to TypeScript

---

ui/src/app/machines/views/AddChassis/AddChassisForm/AddChassisForm.test.tsx
ui/src/app/machines/views/AddChassis/AddChassisForm/AddChassisForm.tsx
ui/src/app/machines/views/AddChassis/AddChassisFormFields/AddChassisFormFields.test.tsx
ui/src/app/machines/views/AddMachine/AddMachineForm/AddMachineForm.test.tsx
ui/src/app/machines/views/AddMachine/AddMachineForm/AddMachineForm.tsx
ui/src/app/machines/views/AddMachine/AddMachineFormFields/AddMachineFormFields.test.tsx
ui/src/app/machines/views/AddMachine/AddMachineFormFields/AddMachineFormFields.tsx
ui/src/app/machines/views/AddMachine/types.ts
ui/src/app/machines/views/MachineDetails/MachineConfiguration/PowerForm/PowerForm.tsx
ui/src/app/store/general/utils/powerTypes.ts

- migrate add machine and chassis forms to TypeScript
N/A

refactor(ui): migrate add machine and chassis forms to TypeScript

---

ui/src/app/settings/views/Network/DnsForm/DnsForm.test.tsx
ui/src/app/settings/views/Network/DnsForm/DnsForm.tsx
ui/src/app/settings/views/Network/NtpForm/NtpForm.test.tsx
ui/src/app/settings/views/Network/NtpForm/NtpForm.tsx
ui/src/app/settings/views/Network/ProxyForm/ProxyForm.test.tsx
ui/src/app/settings/views/Network/ProxyForm/ProxyForm.tsx
ui/src/app/settings/views/Network/ProxyForm/types.ts
ui/src/app/settings/views/Network/ProxyFormFields/ProxyFormFields.test.tsx
ui/src/app/settings/views/Network/ProxyFormFields/ProxyFormFields.tsx
ui/src/app/settings/views/Network/SyslogForm/SyslogForm.test.tsx
ui/src/app/settings/views/Network/SyslogForm/SyslogForm.tsx

- migrate network settings components to TypeScript
N/A

refactor(ui): migrate network settings components to TypeScript

---

ui/src/app/settings/views/Configuration/Commissioning/Commissioning.test.tsx
ui/src/app/settings/views/Configuration/Commissioning/Commissioning.tsx
ui/src/app/settings/views/Configuration/Deploy/Deploy.test.tsx
ui/src/app/settings/views/Configuration/Deploy/Deploy.tsx
ui/src/app/settings/views/Configuration/DeployForm/DeployForm.tsx
ui/src/app/settings/views/Configuration/DeployForm/types.ts
ui/src/app/settings/views/Configuration/DeployFormFields/DeployFormFields.test.tsx
ui/src/app/settings/views/Configuration/DeployFormFields/DeployFormFields.tsx
ui/src/app/settings/views/Configuration/General/General.test.tsx
ui/src/app/settings/views/Configuration/General/General.tsx

- migrate Configuration settings components to TypeScript
N/A

refactor(ui): migrate Configuration settings components to TypeScript

---

ui/src/app/settings/views/Storage/StorageForm/StorageForm.test.tsx
ui/src/app/settings/views/Storage/StorageForm/StorageForm.tsx
ui/src/app/settings/views/Storage/StorageForm/types.ts
ui/src/app/settings/views/Storage/StorageFormFields/StorageFormFields.test.tsx
ui/src/app/settings/views/Storage/StorageFormFields/StorageFormFields.tsx

- migrate Storage settings components to TypeScript
N/A

refactor(ui): migrate Storage settings components to TypeScript

---

ui/src/app/settings/views/Users/UsersList/UsersList.test.tsx
ui/src/app/settings/views/Users/UsersList/UsersList.tsx

- migrate User settings components to TypeScript.
N/A

refactor(ui): migrate User settings components to TypeScript

---

ui/.betterer.results
ui/src/app/base/components/SectionHeader/SectionHeader.tsx
ui/src/app/base/components/TableActionsDropdown/TableActionsDropdown.tsx
ui/src/app/base/types.ts
ui/src/app/kvm/views/KVMList/AddKVM/AddVirsh/AddVirsh.tsx
ui/src/app/machines/components/ActionFormWrapper/CommissionForm/CommissionForm.tsx
ui/src/app/machines/components/ActionFormWrapper/CommissionForm/CommissionFormFields/CommissionFormFields.tsx
ui/src/app/machines/components/ActionFormWrapper/DeployForm/DeployFormFields/UserDataField/UserDataField.test.tsx
ui/src/app/machines/components/ActionFormWrapper/TestForm/TestForm.tsx
ui/src/app/machines/components/ActionFormWrapper/TestForm/TestFormFields/TestFormFields.tsx
ui/src/app/machines/components/TakeActionMenu/TakeActionMenu.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AvailableStorageTable.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/CacheSetsTable/CacheSetsTable.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/DatastoresTable/DatastoresTable.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/FilesystemsTable/FilesystemsTable.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/UsedStorageTable/UsedStorageTable.tsx
ui/src/app/machines/views/MachineDetails/MachineTests/MachineTestsTable/MachineTestsTable.tsx
ui/src/app/machines/views/MachineDetails/MachineTests/MachineTestsTable/TestActions/TestActions.tsx
ui/src/app/settings/views/Configuration/CommissioningFormFields/CommissioningFormFields.tsx
ui/src/app/store/script/types/base.ts
ui/src/app/store/script/utils.test.ts
ui/src/app/store/script/utils.ts

- remove TSFixMes and replace with correct types.
N/A

refactor(ui): remove TSFixMes and replace with correct types

---

ui/.betterer.results
ui/src/app/base/components/DhcpFormFields/DhcpFormFields.test.tsx
ui/src/app/base/components/FormikFormContent/FormikFormContent.test.tsx
ui/src/app/base/components/SSHKeyForm/SSHKeyFormFields/SSHKeyFormFields.test.tsx
ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/InterfacesTable/SubnetSelect/SubnetSelect.test.tsx
ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/StorageTable/PoolSelect/PoolSelect.test.tsx
ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/StorageTable/StorageTable.test.tsx
ui/src/app/machines/views/MachineDetails/MachineLogs/EventLogs/EventLogs.test.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AddLogicalVolume/AddLogicalVolume.test.tsx
ui/src/app/machines/views/MachineDetails/MachineStorage/AvailableStorageTable/AddPartition/AddPartition.test.tsx
ui/src/app/machines/views/MachineList/MachineListControls/MachineListControls.test.tsx

- Use the simulate function for change events.

refactor(ui): use the simulate function for change events

---

ui/.betterer.results
ui/package.json
ui/src/app/base/components/DynamicSelect/DynamicSelect.tsx
ui/src/app/base/components/FabricSelect/FabricSelect.test.tsx
ui/src/app/base/components/LinkModeSelect/LinkModeSelect.test.tsx
ui/src/app/base/components/VLANSelect/VLANSelect.test.tsx
ui/src/app/base/views/NotFound/__snapshots__/NotFound.test.tsx.snap
ui/src/app/intro/views/Intro.test.tsx
ui/src/app/kvm/components/KVMActionFormWrapper/ComposeForm/InterfacesTable/InterfacesTable.test.tsx
ui/src/app/machines/views/MachineDetails/MachineLogs/DownloadMenu/DownloadMenu.test.tsx
ui/src/app/machines/views/MachineDetails/MachineLogs/InstallationOutput/InstallationOutput.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/BondForm/BondModeSelect/BondModeSelect.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/BondForm/HashPolicySelect/HashPolicySelect.test.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/BondForm/HashPolicySelect/HashPolicySelect.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/BondForm/LACPRateSelect/LACPRateSelect.test.tsx
ui/src/app/preferences/views/SSLKeys/SSLKeyList/SSLKeyList.test.tsx
ui/src/app/preferences/views/SSLKeys/SSLKeyList/SSLKeyList.tsx
ui/src/app/settings/views/Scripts/ScriptsList/ScriptsList.test.tsx
ui/src/app/settings/views/Scripts/ScriptsList/ScriptsList.tsx

… inferred
- Update tests to find components so that their props are inferred.

refactor(ui): update tests to find components so that their props are inferred

---

ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneResults/CloneResults.test.tsx
ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneResults/CloneResults.tsx

- Added `system_id`s to formatted clone errors, and used for determining what failed and how.
- It will be easier to QA this on bolla, which already has 3 Ready machines that have compatible networking. Otherwise set up 3 machines with compatible networking/storage.
- Go to the machine list and select `test1` and `test2` and …

feat(ui): use correct counts for grouped clone errors

---

ui/src/app/machines/components/ActionFormWrapper/CloneForm/CloneResults/CloneResults.tsx

- Updated clone error message for when an `item_invalid` error occurs
- Unnecessary

fix(ui): update clone error message for invalid items

---

ui/src/app/kvm/views/KVMDetails/KVMDetailsHeader/KVMDetailsHeader.tsx
ui/src/app/kvm/views/KVMList/KVMListHeader/KVMListHeader.tsx

- Rename the "Project" tab to "Virtual machines".
- Rename the "Add kvm" button to "Add kvm host".
N/A -  a code review is probably enough for these simple text changes.
Fixes: canonical-web-and-design/app-squad#285.
Fixes: canonical-web-and-design/app-squad#303.

feat(ui): rename project tab and add kvm button

---

ui/src/app/store/vmcluster/types/base.ts
ui/src/app/store/vmcluster/types/index.ts
ui/src/testing/factories/state.ts
ui/src/testing/factories/vmcluster.ts

- Add the types and factories for the vmcluster model.
N/A
Fixes: canonical-web-and-design/app-squad#343.

feat(ui): add vmcluster types and factories

---

ui/src/__snapshots__/root-reducer.test.ts.snap
ui/src/app/store/root/types.ts
ui/src/app/store/utils/slice.ts
ui/src/app/store/vmcluster/actions.test.ts
ui/src/app/store/vmcluster/index.ts
ui/src/app/store/vmcluster/reducers.test.ts
ui/src/app/store/vmcluster/slice.ts
ui/src/app/store/vmcluster/types/base.ts
ui/src/app/store/vmcluster/types/enum.ts
ui/src/app/store/vmcluster/types/index.ts
ui/src/root-reducer.ts
ui/src/testing/factories/index.ts
ui/src/testing/factories/state.ts
ui/src/testing/factories/vmcluster.ts

- Add a slice for the vmcluster model.
N/A
Fixes: canonical-web-and-design/app-squad#366.

feat(ui): add vmcluster slice

---

ui/src/app/base/components/Stepper/_index.scss

- Make the add-lxd active stepper more prominent.
- Click KVM in the header.
- Click 'Add LXD host'.
- The step you're on should have a dark background.
Fixes: #3225.

feat(ui): Update the add-lxd stepper colour

---

.github/workflows/cypress.yml

- Run CI against the 3.1 branch.

ci(intergration): update the Cypress CI to run against the 3.1 branch

---

ui/src/app/Routes.tsx
ui/src/app/devices/urls.ts
ui/src/app/devices/views/Devices.tsx

- Add device URLs and basic routing.
- Visit /MAAS/r/devices
- You should see "Devices"
- Visit /MAAS/r/device/1
- You should see "Device"
Fixes: canonical-web-and-design/app-tribe#516

feat(ui): add device URL and routing

---

ui/src/app/dashboard/views/DiscoveryAddForm/types.ts
ui/src/app/store/device/types/actions.ts
ui/src/app/store/device/types/base.ts
ui/src/app/store/device/types/enum.ts
ui/src/app/store/device/types/index.ts

- Fixed slightly incorrect device types
- Exported missing types
- N/A
Fixes canonical-web-and-design/app-tribe#514

fix(ui): fix device types

---

ui/src/app/store/device/selectors.test.ts
ui/src/app/store/device/selectors.ts

- Add selectors for getting the active and selected devices.
Fixes: canonical-web-and-design/app-tribe#519.

feat(ui): add selectors for getting the active and selected devices

---

ui/src/app/machines/views/MachineDetails/MachineNetwork/EditAliasOrVlanForm/EditAliasOrVlanForm.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/EditBondForm/EditBondForm.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/EditBridgeForm/EditBridgeForm.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/EditPhysicalForm/EditPhysicalForm.tsx
ui/src/app/store/machine/slice.ts
ui/src/app/store/machine/types/actions.ts
ui/src/app/store/machine/types/index.ts
ui/src/app/store/types/node.ts

- Move link and update interface types to the nodes types.
N/A

Move link and update interface types to the nodes types.

---

ui/src/app/store/device/actions.test.ts
ui/src/app/store/device/reducers.test.ts
ui/src/app/store/device/slice.ts
ui/src/app/store/device/types/actions.ts
ui/src/app/store/device/types/base.ts
ui/src/testing/factories/state.ts

- Add support for the device websocket API methods to the device slice.
Fixes: canonical-web-and-design/app-tribe#520.

feat(ui): add device actions to the slice

---

shared/src/components/StatusBar/StatusBar.test.tsx

- refactor StatusBar with testing library
Fixes #3407

refactor StatusBar with testing library

---

ui/src/app/machines/views/MachineDetails/MachineNetwork/BondForm/BondFormFields/BondFormFields.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/BondForm/utils.ts
ui/src/app/machines/views/MachineDetails/MachineNetwork/InterfaceFormTable/InterfaceFormTable.tsx
ui/src/app/machines/views/MachineDetails/MachineNetwork/MachineNetworkActions/MachineNetworkActions.tsx
ui/src/app/store/device/selectors.test.ts
ui/src/app/store/device/selectors.ts
ui/src/app/store/machine/selectors.ts
ui/src/app/store/utils/node/networking.ts

- Update the util for getting an interface by id to handle all node types.
- Add a selector for getting a device interface by id.
Fixes: canonical-web-and-design/app-tribe#602.

feat(ui): add a selector for getting a device interface

---

ui/src/app/devices/views/DeviceDetails/DeviceNetwork/DeviceNetwork.tsx
ui/src/app/devices/views/DeviceDetails/DeviceNetwork/DeviceNetworkTable/DeviceNetworkTable.tsx
ui/src/app/devices/views/DeviceDetails/DeviceNetwork/EditInterface/EditInterface.test.tsx
ui/src/app/devices/views/DeviceDetails/DeviceNetwork/EditInterface/EditInterface.tsx
ui/src/app/devices/views/DeviceDetails/DeviceNetwork/EditInterface/index.ts

- Add a form for editing a device's physical interfaces.
- Go to /r/devices.
- Click on a device and then go to the network tab.
- Open the action menu for one of the devices and click "Edit physical".
- Make some changes and save.
- Your changes should get reflected in the table.
Fixes: canonical-web-and-design/app-tribe#572.

feat(ui): edit device interface form

---

ui/src/app/Routes.tsx
ui/src/app/devices/views/DeviceList/DeviceList.test.tsx
ui/src/app/machines/views/Machines.test.tsx
ui/src/app/settings/components/Routes/Routes.tsx
ui/src/app/settings/views/Scripts/ScriptsUpload/ScriptsUpload.test.tsx

- Update routes to pass the component as a child of the route.
Fixes: #3465.

refactor(ui): update routes to pass the component as a child

---

ui/src/app/store/controller/actions.test.ts
ui/src/app/store/controller/selectors.test.ts
ui/src/app/store/controller/selectors.ts
ui/src/app/store/controller/slice.ts
ui/src/app/store/controller/types/actions.ts
ui/src/app/store/controller/types/base.ts
ui/src/app/store/controller/types/index.ts
ui/src/app/store/machine/selectors.ts

**Note: This is pretty much all copy and paste from the machine slice.**
- Add the controller actions to the slice
Fixes: canonical-web-and-design/app-tribe#609.

feat(ui): add controller actions

---

integration/cypress/support/commands.ts
integration/cypress/tsconfig.json
integration/package.json
yarn.lock

- add @testing-library/cypress allowing easy user-centric queries
- e.g. `cy.findByRole("link", { name: "Subnets" }).click()`)

add @testing-library/cypress

---

ui/src/app/controllers/views/ControllerList/ControllerList.tsx
ui/src/app/controllers/views/ControllerList/ControllerListTable/ControllerListTable.test.tsx
ui/src/app/controllers/views/ControllerList/ControllerListTable/ControllerListTable.tsx
ui/src/app/controllers/views/ControllerList/ControllerListTable/VLANsColumn/VLANsColumn.test.tsx
ui/src/app/controllers/views/ControllerList/ControllerListTable/VLANsColumn/VLANsColumn.tsx
ui/src/app/controllers/views/ControllerList/ControllerListTable/VLANsColumn/index.ts
ui/src/app/controllers/views/ControllerList/ControllerListTable/VersionColumn/VersionColumn.test.tsx
ui/src/app/controllers/views/ControllerList/ControllerListTable/VersionColumn/VersionColumn.tsx
ui/src/app/controllers/views/ControllerList/ControllerListTable/VersionColumn/index.ts
ui/src/app/controllers/views/ControllerList/ControllerListTable/_index.scss
ui/src/app/controllers/views/ControllerList/ControllerListTable/index.ts
ui/src/scss/index.scss
ui/src/testing/factories/index.ts
ui/src/testing/factories/nodes.ts

- Add the table of controllers.
- Visit /r/controllers.
- You should see a list of controllers that matches the legacy table, except for the status column and image status (second row of the image col).
Fixes: canonical-web-and-design/app-tribe#610.

Controller table

---

integration/cypress/integration/accessibility/accessibility.spec.ts
integration/cypress/integration/base/header.spec.ts
integration/cypress/integration/controllers/list.spec.ts
legacy/src/app/controllers/node_details.js
legacy/src/app/controllers/tests/test_node_details.js
legacy/src/app/routes.js
shared/src/components/Header/Header.tsx
ui/src/app/base/urls.ts
ui/src/app/zones/views/ZonesList/ZonesListTable/ZonesListTable.tsx

- Update references to the controllers list to point to the React list.
- Run the full client with `yarn start`
- Check that clicking Controllers in the header takes you to /r/controllers.
- Check that visiting /l/controllers redirects to /r/controllers.
Fixes: https://github.com/canonical-web-and-design/app-tribe/issues/619.

Controllers header link

---

ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/OverrideTestForm/OverrideTestForm.test.tsx
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/OverrideTestForm/OverrideTestForm.tsx
ui/src/app/machines/views/MachineDetails/MachineCommissioning/MachineCommissioning.test.tsx
ui/src/app/machines/views/MachineDetails/MachineCommissioning/MachineCommissioning.tsx
ui/src/app/machines/views/MachineDetails/MachineLogs/DownloadMenu/DownloadMenu.tsx
ui/src/app/machines/views/MachineDetails/MachineLogs/hooks.ts
ui/src/app/machines/views/MachineDetails/MachineNetwork/NetworkTable/IPColumn/IPColumn.tsx
ui/src/app/machines/views/MachineDetails/MachineTests/MachineTests.test.tsx
ui/src/app/machines/views/MachineDetails/MachineTests/MachineTests.tsx
ui/src/app/store/nodescriptresult/reducers.test.ts
ui/src/app/store/nodescriptresult/slice.ts
ui/src/app/store/scriptresult/reducers.test.ts
ui/src/app/store/scriptresult/selectors.test.tsx
ui/src/app/store/scriptresult/selectors.ts
ui/src/app/store/scriptresult/slice.ts

- Update the script result slice to work with all node types.
- View the tests tab in machine details. It should appear without errors.
Fixes: canonical-web-and-design/app-tribe#621.

refactor(ui): update script results for all nodes

---

legacy/src/app/controllers/node_details.js
legacy/src/app/controllers/tests/test_node_details.js
legacy/src/app/factories/tags.js
legacy/src/app/factories/tests/test_tags.js
legacy/src/app/partials/node-details.html

- Update the tag field in the controller edit form to handle ids.
- Run `yarn start`.
- Visit the config tab for a controller with tags.
- You should see a list the tag names and they should link to the list page.
- Click Edit.
- You should be able to add/remove tags.
- Click Save and the tags should update.
Fixes: #3513.

fix(legacy): fix updating tags on a controller

---

ui/src/app/Routes.test.tsx
ui/src/app/controllers/views/Controllers.test.tsx
ui/src/app/dashboard/views/Dashboard.test.tsx
ui/src/app/devices/views/DeviceDetails/DeviceDetails.test.tsx
ui/src/app/devices/views/Devices.test.tsx
ui/src/app/domains/views/Domains.test.tsx
ui/src/app/domains/views/DomainsList/DomainsList.test.tsx
ui/src/app/images/views/ImageList/ImageList.tsx
ui/src/app/images/views/Images.test.tsx
ui/src/app/intro/views/Intro.test.tsx
ui/src/app/kvm/views/KVM.test.tsx
ui/src/app/kvm/views/LXDClusterDetails/LXDClusterDetails.test.tsx
ui/src/app/kvm/views/VirshDetails/VirshDetails.test.tsx
ui/src/app/kvm/views/VirshDetails/VirshDetails.tsx
ui/src/app/machines/views/MachineDetails/MachineDetails.test.tsx
ui/src/app/machines/views/MachineDetails/MachineDetails.tsx
ui/src/app/machines/views/MachineDetails/MachineLogs/MachineLogs.test.tsx
ui/src/app/machines/views/MachineDetails/MachineLogs/MachineLogs.tsx
ui/src/app/machines/views/Machines.test.tsx
ui/src/app/preferences/components/Routes.test.tsx
ui/src/app/preferences/components/Routes/Routes.tsx
ui/src/app/settings/components/Routes/Routes.test.tsx
ui/src/app/settings/components/Routes/Routes.tsx
ui/src/app/settings/views/Repositories/RepositoriesList/RepositoriesList.tsx
ui/src/app/settings/views/Users/UsersList/UsersList.tsx
ui/src/app/subnets/views/Subnets.test.tsx
ui/src/app/subnets/views/Subnets.tsx
ui/src/app/zones/views/Zones.test.tsx

- Fix an issue where routes were causing hook errors.
- Add tests for all routes.
- Visit settings, preferences and /r/networks?by=fabric.
- They should all load and there shouldn't be any errors about invalid hooks.
Fixes: #3537.

fix(ui): fix route errors and add tests

---

ui/src/__snapshots__/root-reducer.test.ts.snap
ui/src/app/store/iprange/action.test.ts
ui/src/app/store/iprange/index.ts
ui/src/app/store/iprange/reducers.test.ts
ui/src/app/store/iprange/selectors.test.ts
ui/src/app/store/iprange/selectors.ts
ui/src/app/store/iprange/slice.ts
ui/src/app/store/iprange/types/actions.ts
ui/src/app/store/iprange/types/base.ts
ui/src/app/store/iprange/types/enum.ts
ui/src/app/store/iprange/types/index.ts
ui/src/app/store/root/types.ts
ui/src/root-reducer.ts
ui/src/testing/factories/index.ts
ui/src/testing/factories/iprange.ts
ui/src/testing/factories/state.ts

- Add a slice to handle reducers, actions, types etc. for the iprange model.
Fixes: canonical-web-and-design/app-tribe#674.

feat(ui): add iprange slice

---

ui/src/app/subnets/views/SubnetDetails/SubnetDetails.tsx
ui/src/app/subnets/views/SubnetDetails/SubnetSummary/SubnetSummary.test.tsx
ui/src/app/subnets/views/SubnetDetails/SubnetSummary/SubnetSummary.tsx

Built the subnets summary section on the subnet details page
- Go to /MAAS/r/subnet/11
- Compare the summary section to the equivalent on http://bolla.internal:5240/MAAS/l/subnet/11
Fixes https://github.com/canonical-web-and-design/app-tribe/issues/654

Build subnet summary section

---

ui/src/app/subnets/components/ReservedRanges/ReservedRanges.test.tsx
ui/src/app/subnets/components/ReservedRanges/ReservedRanges.tsx

- Add the ability to delete reserved ranges.
- Visit the react details page for a subnet or VLAN with reserved ranges (or add some).
- Click the delete icon and the confirmation should appear.
- Confirm and the reserved range should get removed.
Fixes: canonical-web-and-design/app-tribe#721.

feat(ui): delete reserved ranges

---

ui/src/app/subnets/views/SubnetDetails/StaticRoutes/StaticRoutes.tsx

- Made static route destination a link to the appropriate subnet
- Fixed sorting
- Go to the details page of a subnet that has static routes (or add some in legacy)
- Check that the static routes are sorted by "Gateway IP", and changing sort works correctly
- Check that the "Destination" cells are links to the destination …

fix(ui): minor fixes in Subnet Static Routes section

---

ui/src/app/subnets/views/SubnetDetails/SubnetDetailsHeader/SubnetActionForms/components/EditBootArchitectures/BootArchitecturesTable/BootArchitecturesTable.test.tsx
ui/src/app/subnets/views/SubnetDetails/SubnetDetailsHeader/SubnetActionForms/components/EditBootArchitectures/BootArchitecturesTable/BootArchitecturesTable.tsx
ui/src/app/subnets/views/SubnetDetails/SubnetDetailsHeader/SubnetActionForms/components/EditBootArchitectures/BootArchitecturesTable/_index.scss
ui/src/app/subnets/views/SubnetDetails/SubnetDetailsHeader/SubnetActionForms/components/EditBootArchitectures/BootArchitecturesTable/index.ts
ui/src/app/subnets/views/SubnetDetails/SubnetDetailsHeader/SubnetActionForms/components/EditBootArchitectures/EditBootArchitectures.test.tsx
ui/src/app/subnets/views/SubnetDetails/SubnetDetailsHeader/SubnetActionForms/components/EditBootArchitectures/EditBootArchitectures.tsx
ui/src/scss/index.scss

- Built "Edit boot architectures" form in subnet details
- Go to a subnet's details page and click "Take action" then "Edit boot architectures"
- Change some of the checkboxes and submit the form
- Open the form again and check that the changes have persisted
Fixes canonical-web-and-design/app-tribe#652

feat(ui): build "Edit boot architectures" form in subnet details

---

ui/src/app/base/components/VLANSelect/VLANSelect.test.tsx
ui/src/app/base/components/VLANSelect/VLANSelect.tsx
ui/src/app/subnets/views/SubnetDetails/SubnetSummary/SubnetSummary.tsx
ui/src/app/subnets/views/SubnetDetails/SubnetSummary/SubnetSummaryForm/SubnetSummaryForm.test.tsx
ui/src/app/subnets/views/SubnetDetails/SubnetSummary/SubnetSummaryForm/SubnetSummaryForm.tsx
ui/src/app/subnets/views/SubnetDetails/SubnetSummary/SubnetSummaryForm/SubnetSummaryFormFields/SubnetSummaryFormFields.tsx
ui/src/app/subnets/views/SubnetDetails/SubnetSummary/SubnetSummaryForm/SubnetSummaryFormFields/index.ts
ui/src/app/subnets/views/SubnetDetails/SubnetSummary/SubnetSummaryForm/index.ts
ui/src/app/subnets/views/SubnetDetails/SubnetSummary/SubnetSummaryForm/types.ts

Build subnet summary edit form

---

ui/src/app/base/components/SubnetSelect/SubnetSelect.test.tsx
ui/src/app/base/components/SubnetSelect/SubnetSelect.tsx
ui/src/app/store/user/selectors.ts
ui/src/app/subnets/views/SubnetDetails/StaticRoutes/AddStaticRouteForm/AddStaticRouteForm.tsx
ui/src/app/subnets/views/SubnetDetails/StaticRoutes/StaticRoutes.tsx

- Add static route form improvements
- Go to a subnet details page.
- Scroll down to the static routes table and click "Add static route".
- Enter some valid details and submit.
- There's a bug at the moment that might require you to refresh the page to see the new static route: https://bugs.launchpad.net/maas/+bug/1960462.

fix(ui): add static route form improvements

---

ui/src/app/base/components/TagSelector/TagSelector.test.tsx
ui/src/app/base/components/TagSelector/TagSelector.tsx
ui/src/app/base/components/TagSelector/_index.scss
ui/src/app/machines/components/MachineHeaderForms/ActionFormWrapper/TagForm/TagFormFields/TagFormFields.tsx
ui/src/app/store/tag/selectors.test.ts
ui/src/app/store/tag/selectors.ts

- Update the tag selector in the machine list tag form to display kernel options.
- Go to the machine list and select some machines.
- Use the take action menu to open the tag form.
- Click on the tag field and the dropdown should open.
- The dropdown should have a name and kernel options header and any tags with kernel options should have a tick.
Fixes: …

feat(ui): update tag selector

---

ui/src/app/tags/components/TagsHeader/DeleteTagForm/DeleteTagForm.test.tsx
ui/src/app/tags/components/TagsHeader/DeleteTagForm/DeleteTagForm.tsx
ui/src/app/tags/components/TagsHeader/DeleteTagForm/DeleteTagFormWarnings/DeleteTagFormWarnings.test.tsx
ui/src/app/tags/components/TagsHeader/DeleteTagForm/DeleteTagFormWarnings/DeleteTagFormWarnings.tsx
ui/src/app/tags/components/TagsHeader/DeleteTagForm/DeleteTagFormWarnings/_index.scss
ui/src/app/tags/components/TagsHeader/DeleteTagForm/DeleteTagFormWarnings/index.ts
ui/src/app/tags/components/TagsHeader/DeleteTagForm/index.ts
ui/src/app/tags/components/TagsHeader/TagHeaderForms/TagHeaderForms.test.tsx
ui/src/app/tags/components/TagsHeader/TagHeaderForms/TagHeaderForms.tsx
ui/src/app/tags/components/TagsHeader/TagsHeader.test.tsx
ui/src/app/tags/components/TagsHeader/TagsHeader.tsx
ui/src/app/tags/constants.ts
ui/src/app/tags/types.ts
ui/src/app/tags/views/TagDetails/TagDetails.test.tsx
ui/src/app/tags/views/TagDetails/TagDetails.tsx
ui/src/app/tags/views/TagList/TagList.test.tsx
ui/src/app/tags/views/TagList/TagList.tsx
ui/src/app/tags/views/TagList/TagTable/TagTable.test.tsx
ui/src/app/tags/views/TagList/TagTable/TagTable.tsx
ui/src/app/tags/views/Tags.tsx
ui/src/scss/index.scss

- Delete tags from the tag list or tag details.
- Visit the tag list.
- Click delete on one of the tag rows.
- The delete form should appear in the header.
- There should be warnings if it has kernel options or if it is applied to any nodes.
- Confirm and the tag should be removed.
- Go to the details page for a tag.
- Click delete and the form should appear. …

feat(ui): delete tags

---

ui/src/app/store/machine/selectors.ts
ui/src/app/tags/components/AppliedTo/AppliedTo.test.tsx
ui/src/app/tags/components/AppliedTo/AppliedTo.tsx
ui/src/app/tags/components/DefinitionField/DefinitionField.test.tsx
ui/src/app/tags/components/DefinitionField/DefinitionField.tsx
ui/src/app/tags/components/KernelOptionsField/KernelOptionsField.test.tsx
ui/src/app/tags/components/KernelOptionsField/KernelOptionsField.tsx
ui/src/app/tags/urls.ts
ui/src/app/tags/views/TagDetails/TagDetails.test.tsx
ui/src/app/tags/views/TagDetails/TagDetails.tsx
ui/src/app/tags/views/TagDetails/index.ts
ui/src/app/tags/views/TagList/TagTable/TagTable.test.tsx
ui/src/app/tags/views/TagList/TagTable/TagTable.tsx
ui/src/app/tags/views/TagUpdate/TagUpdate.test.tsx
ui/src/app/tags/views/TagUpdate/TagUpdate.tsx
ui/src/app/tags/views/TagUpdate/TagUpdateFormFields/TagUpdateFormFields.test.tsx
ui/src/app/tags/views/TagUpdate/TagUpdateFormFields/TagUpdateFormFields.tsx
ui/src/app/tags/views/TagUpdate/TagUpdateFormFields/index.ts
ui/src/app/tags/views/TagUpdate/index.ts
ui/src/app/tags/views/Tags.test.tsx
ui/src/app/tags/views/Tags.tsx

- Add a form to update a tag.
- Go to the tag list and click one of the edit buttons. You should see the edit tag form.
- Click cancel and you should go back to the tag list.
- Go to the details page for a tag and click the edit button, you should see the form.
- Click cancel and you should go back to the details page.
- Go to the edit form and copy the URL …

feat(ui): update tag form

---

ui/src/app/base/components/FormikForm/FormikForm.test.tsx

- Migrate formik form test to testing library
Fixes: #3714 …

Migrate formik form test to testing library

---

ui/src/app/tags/views/TagUpdate/TagUpdate.test.tsx
ui/src/app/tags/views/TagUpdate/TagUpdate.tsx

- Show a confirmation notification when changing tag definition
- Open the edit form for an automatic tag
- Change any values except definition and save the form.
- Check that there is no notification
- Open the edit form again and this time change the definition, then submit
- Check that a confirmation appears
Fixes …

feat(ui): show a confirmation notification when changing tag definition

---

ui/src/app/base/components/ActionBar/ActionBar.test.tsx
ui/src/app/settings/views/Settings.test.tsx

- migrate ActionBar, Settings to testing-library
Fixes: # . …

migrate ActionBar, Settings to testing-library

---

ui/src/__snapshots__/root-reducer.test.ts.snap
ui/src/app/store/general/actions.test.ts
ui/src/app/store/general/reducers.test.ts
ui/src/app/store/general/selectors/index.ts
ui/src/app/store/general/selectors/tlsCertificate.test.ts
ui/src/app/store/general/selectors/tlsCertificate.ts
ui/src/app/store/general/slice.ts
ui/src/app/store/general/types/base.ts
ui/src/app/store/general/types/index.ts
ui/src/app/store/general/utils/certificates.test.ts
ui/src/app/store/general/utils/certificates.ts
ui/src/testing/factories/general.ts
ui/src/testing/factories/index.ts
ui/src/testing/factories/state.ts

- Connect `general.tls_certificate` endpoint to the store
- N/A
Fixes canonical-web-and-design/app-tribe#818

feat(ui): add tls_certificate to general slice

---

legacy/src/app/partials/cards/services.html

Add reverse-proxy service to the list of services of regiond.
This service acts as a HTTP/HTTPS reverse proxy.
- Add reverse-proxy service to the list of services of regiond.
Fixes: # . …

feat(tls): add reverse-proxy service

---

ui/src/app/utils/timeSpan.test.ts

- refactor: remove timespan date mock
Fixes: # .
In general, please propose fixes against *master* rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. Please apply backport labels to the PR (e.g. "Backport …

refactor: remove timespan date mock

---

ui/src/app/base/components/ColumnToggle/ColumnToggle.tsx
ui/src/app/base/components/ColumnToggle/__snapshots__/ColumnToggle.test.tsx.snap
ui/src/app/base/components/ColumnToggle/_index.scss

- Fixed styling of script column toggles
- Go to Settings > Commissioning scripts and check that the name column buttons don't look broken
Fixes #3846

fix(ui): fix styling of script column toggles

---

ui/src/app/subnets/views/SubnetsList/SubnetsTable/SubnetsTable.test.tsx

- refactor: use current page selector
Fixes: https://github.com/canonical-web-and-design/app-tribe/issues/764 …

refactor: use current page selector

---

integration/cypress/integration/login/login.spec.ts

- fix cypress failures (login.spec.ts)
Fixes: #3764
In general, please propose fixes against *master* rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. Please apply backport labels to the PR (e.g. "Backport …

fix: cypress failures

---

ui/src/app/base/docsUrls.ts

- update customisingDeployedMachines docs url
https://github.com/canonical-web-and-design/app-tribe/issues/834#issuecomment-1113118434
Fixes: # .
In general, please propose fixes against *master* rather than release branches (e.g. 2.7), unless the fix is only …

update customisingDeployedMachines docs url

---

ui/src/app/machines/views/MachineDetails/MachineTests/MachineTestsTable/MachineTestsTable.tsx

- Fixed alignment of machine test suppress checkbox
- Go to the tests tab of a machine that has run tests
- Check that the "Suppress" checkbox is inline with the rest of the text
Fixes canonical-web-and-design/app-tribe#873

fix(ui): fix alignment of machine test suppress checkbox

---

.github/workflows/cypress.yml

ci(ci): use the 2.9 snap

---

.github/workflows/cypress.yml

ci(ci): use the 3.0 snap

---

RELEASE.md
integration/package.json
legacy/package.json
package.json
proxy/package.json
root/package.json
shared/package.json
ui/package.json

- Update version to 3.3.
- Update release instructions.
N/A

feat(all): update version to 3.3

---

.github/workflows/accessibility.yml
.github/workflows/cypress.yml
.github/workflows/test.yml
HACKING.md
RELEASE.md

- Update versions to 3.2.
- Update release instructions.
N/A
Fixes: canonical-web-and-design/app-tribe/issues/924.

feat(all): update versions to 3.2

---

ui/src/app/base/docsUrls.ts

- Fixed DHCP docs link redirect
- Docs link test should pass
Fixes #3937
Fixes #3943

fix(ui): fix DHCP docs link redirect

---

ui/src/app/base/components/NodeName/NodeName.tsx
ui/src/app/base/components/NodeName/NodeNameFields/NodeNameFields.test.tsx
ui/src/app/base/components/NodeName/NodeNameFields/NodeNameFields.tsx
ui/src/app/base/components/NodeName/NodeNameFields/__snapshots__/NodeNameFields.test.tsx.snap
ui/src/app/base/components/NodeName/__snapshots__/NodeName.test.tsx.snap
ui/src/app/base/components/NodeName/_index.scss
ui/src/app/controllers/views/ControllerDetails/ControllerDetailsHeader/ControllerDetailsHeader.tsx
ui/src/app/controllers/views/ControllerDetails/ControllerDetailsHeader/ControllerName/ControllerName.test.tsx
ui/src/app/controllers/views/ControllerDetails/ControllerDetailsHeader/ControllerName/ControllerName.tsx
ui/src/app/controllers/views/ControllerDetails/ControllerDetailsHeader/ControllerName/index.ts

- build controller details header
- Go to the Controller details page
- Click on the Controller's name and verify the hostname cannot be changed
- Change the domain using the dropdown and verify it's been saved correctly
Fixes: https://github.com/canonical-web-and-design/app-tribe/issues/932
Related Launchpad maas issue in the …

refactor: controller details header

---

.github/workflows/accessibility.yml
.github/workflows/cypress.yml

- Fix the paths to the cypress tests.
n/a
Fixes: #4016.

fix(cypress): fix workflow cypress path

---

ui/src/app/controllers/views/ControllerDetails/ControllerSummary/ServicesCard/ServiceStatus/ServiceStatus.test.tsx
ui/src/app/controllers/views/ControllerDetails/ControllerSummary/ServicesCard/ServiceStatus/ServiceStatus.tsx
ui/src/app/controllers/views/ControllerDetails/ControllerSummary/ServicesCard/ServiceStatus/index.ts
ui/src/app/controllers/views/ControllerDetails/ControllerSummary/ServicesCard/ServicesCard.test.tsx
ui/src/app/controllers/views/ControllerDetails/ControllerSummary/ServicesCard/ServicesCard.tsx
ui/src/app/store/service/types/base.ts
ui/src/app/store/service/types/enum.ts
ui/src/app/store/service/types/index.ts
ui/src/app/store/service/utils.ts
ui/src/scss/_patterns_list-trees.scss
ui/src/scss/index.scss
ui/src/testing/factories/service.ts

- Built controller services card
- Go to the React summary tab of a controller
- Check that the content matches what's in the AngularJS version of the services card
Fixes canonical-web-and-design/app-tribe#1009

feat(ui): build controller services card

---

proxy/index.js
proxy/ui.js

- Use the basenames defined in the env vars for the proxy.
- Run `yarn start` and `yarn ui` and check that the clients load.
Fixes: canonical-web-and-design/app-tribe#1018.

refactor(proxy): use env vars for the proxy basenames

---

ui/src/app/App.tsx
ui/src/app/base/components/Footer/Footer.test.tsx
ui/src/app/base/components/Footer/Footer.tsx
ui/src/app/base/components/Footer/index.ts
ui/src/app/base/components/Header/Header.test.tsx
ui/src/app/base/components/Header/Header.tsx
ui/src/app/base/components/Header/index.ts
ui/src/app/base/components/StatusBar/StatusBar.tsx
ui/src/app/base/types.ts
ui/src/app/settings/views/Configuration/GeneralForm/GeneralForm.tsx

- Copy the Header, Footer and StatusBar components to the ui workspace.
- Run the react client and check that the header footer and status bar all work.
Fixes: canonical-web-and-design/app-tribe#954.

refactor(ui): add shared components to the ui workspace

---

cypress/integration/with-users/controllers/list.spec.ts
ui/src/app/base/components/TagSelector/TagSelector.tsx

- Fix the cypress tests for controllers.
n/a
Fixes: #4036.

fix(cypress): fix controller cypress tests

---

README.md
docs/HACKING.md
docs/INTEGRATION.md
docs/RELEASE.md

- Remove references to the old workspaces.
- Update docs to refer to working with snaps.
Fixes: canonical-web-and-design/app-tribe#978.

docs(docs): update docs to reflect new codebase

---

nodemon.json
scripts/proxy-ready.js
scripts/proxy.js

- Use the correct path to watch the proxy files.
- Run `yarn start`.
- Once the react server has started you should see a message the the client is ready.
- Make a change to proxy.js or proxy-start.js and it should reload on save.
Fixes: canonical-web-and-design/app-tribe#1033.

fix(proxy): fix watching proxy files

---

.github/workflows/upload.yml

- Attempt to run on commit using the secure action.

Use pull_request_target

---

src/app/zones/views/ZonesList/ZonesList.test.tsx
src/app/zones/views/ZonesList/ZonesListForm/ZonesListForm.test.tsx
src/app/zones/views/ZonesList/ZonesListForm/ZonesListForm.tsx
src/app/zones/views/ZonesList/ZonesListHeader/ZonesListHeader.test.tsx
src/app/zones/views/ZonesList/ZonesListHeader/ZonesListHeader.tsx
src/app/zones/views/ZonesList/ZonesListTable/ZonesListTable.tsx

Migrated the following test components to RTL:
- `app/zones/views/ZonesList/ZonesListForm/ZonesList.test.tsx`
- `app/zones/views/ZonesList/ZonesListForm/ZonesListForm.test.tsx`
- `app/zones/views/ZonesList/ZonesListForm/ZonesListHeader.test.tsx`

Migrate zones components to RTL part 1

---

.github/workflows/sitespeed.yml
.gitignore
docs/HACKING.md
package.json
sitespeed.io/config.json
sitespeed.io/login.js
sitespeed.io/scripts/machines.js
sitespeed.io/utils.js

- Add a GitHub action to run sitespeed on merge.
- Check that the action artefact has the sitespeed results. Here's a passing run (I temporarily changed the action to run on this PR): https://github.com/canonical-web-and-design/maas-ui/actions/runs/2567167138
Fixes: https://github.com/canonical-web-and-design/app-tribe/issues/1076.

Set up sitespeed.io CI job.

---

docs/HACKING.md
src/app/settings/components/Routes/Routes.test.tsx
src/app/settings/components/Routes/Routes.tsx
src/app/settings/views/LicenseKeys/LicenseKeyEdit/LicenseKeyEdit.test.tsx
src/app/settings/views/LicenseKeys/LicenseKeyEdit/LicenseKeyEdit.tsx
src/app/settings/views/Repositories/RepositoryAdd/RepositoryAdd.test.tsx
src/app/settings/views/Repositories/RepositoryAdd/RepositoryAdd.tsx

- Fix param capturing for settings sub routes.
- Go to settings.
- Check that you can open the edit form for users, license keys, DHCP snippets and package repos.
- Check that other settings routes function as they did before.
Fixes: #4183.

fix(settings): fix settings sub routes

---

src/app/settings/views/Configuration/GeneralForm/GeneralForm.tsx

- Wrote help about how to use emojis in the MAAS name field with examples.
You can see these changes by navigating to the Settings page, then Configuration --> General

Site identity - MAAS name emoji help

---

src/app/dashboard/views/Dashboard.test.tsx
src/app/dashboard/views/Dashboard.tsx
src/app/dashboard/views/DashboardConfigurationForm/DashboardConfigurationForm.tsx
src/app/dashboard/views/DiscoveriesList/DiscoveriesList.tsx

- Update dashboard components to React Router v6.
- Click on the header logo. You should see the dashboard.
- Click on the Configuration tab and you should see the form.
Fixes: #4186.

refactor(dashboard): update dashboard to RRv6

---

src/app/devices/views/DeviceDetails/DeviceConfiguration/DeviceConfiguration.tsx
src/app/devices/views/DeviceDetails/DeviceDetails.test.tsx
src/app/devices/views/DeviceDetails/DeviceDetails.tsx
src/app/devices/views/DeviceDetails/DeviceNetwork/DeviceNetwork.tsx
src/app/devices/views/DeviceDetails/DeviceSummary/DeviceSummary.tsx

- Update device details to React Router v6.
- Go to the details page for a device.
- Check that each tab displays.
Fixes: #4188.

refactor(device): update device details to RRv6

---

src/app/store/machine/reducers.test.ts
src/app/store/machine/slice.ts

- Remove the reducer for handling created machine notifications.
n/a
Fixes: canonical-web-and-design/app-tribe#1150.

refactor(machine): remove created machine handling

---

cypress/e2e/with-users/controllers/details.spec.ts

- fix cypress failure
Fixes: #4174  …

fix cypress test failure

---

src/app/machines/components/MachineHeaderForms/ActionFormWrapper/DeployForm/DeployForm.tsx

- Remove the call to fetch machines that isn't used in the deploy form.
- Go to the machine list and tick a machine that can be deployed.
- Use the take action menu to open the deploy form.
- Submit the form and it should start the deploy.
Fixes: canonical-web-and-design/app-tribe#1129.

refactor(machine list): remove machine fetching from deploy form

---

src/__snapshots__/root-reducer.test.ts.snap
src/app/base/sagas/websockets.test.ts
src/app/base/sagas/websockets.ts
src/app/machines/components/MachineHeaderForms/ActionFormWrapper/CloneForm/CloneFormFields/CloneFormFields.test.tsx
src/app/store/machine/actions.test.ts
src/app/store/machine/reducers.test.ts
src/app/store/machine/slice.ts
src/app/store/machine/types/base.ts
src/app/store/machine/utils/hooks.test.tsx
src/app/store/machine/utils/hooks.ts
src/testing/factories/state.ts
src/websocket-client.ts

- Add the details shape to the machine store in redux.
N/a.
Fixes: canonical-web-and-design/app-tribe#1159.

feat(machine): add details to machine store

---

package.json
yarn.lock

- add analyze script allowing to [analyze the bundle size](https://create-react-app.dev/docs/analyzing-the-bundle-size/)
Fixes: https://github.com/canonical-web-and-design/app-tribe/issues/1183
In general, please propose fixes against _main_ rather than …

feat: add analyze bundle size script

---

src/app/subnets/views/VLANDetails/ConfigureDHCP/ConfigureDHCP.test.tsx
src/app/subnets/views/VLANDetails/ConfigureDHCP/ConfigureDHCP.tsx
src/app/subnets/views/VLANDetails/ConfigureDHCP/ConfigureDHCPFields/ConfigureDHCPFields.tsx

- fix VLAN DHCP configuration form
- Go to https://maas-ui-4246.demos.haus/MAAS/r/vlan/5004 and Click "Configure DHCP"
- Select a subnet
- Form submit button should be enabled
Fixes: #4212
lp#1980818
https://bugs.launchpad.net/bugs/1980818 …

fix: configure VLAN DHCP

---

src/app/settings/views/Images/ThirdPartyDrivers/ThirdPartyDrivers.test.tsx
src/app/settings/views/Images/ThirdPartyDrivers/ThirdPartyDrivers.tsx
src/app/settings/views/Images/ThirdPartyDriversForm/ThirdPartyDriversForm.test.tsx
src/app/settings/views/Images/ThirdPartyDriversForm/ThirdPartyDriversForm.tsx
src/app/settings/views/Images/VMWare/VMWare.test.tsx
src/app/settings/views/Images/VMWare/VMWare.tsx
src/app/settings/views/Images/VMWareForm/VMWareForm.test.tsx
src/app/settings/views/Images/VMWareForm/VMWareForm.tsx
src/app/settings/views/Images/Windows/Windows.test.tsx
src/app/settings/views/Images/Windows/Windows.tsx
src/app/settings/views/Images/WindowsForm/WindowsForm.test.tsx
src/app/settings/views/Images/WindowsForm/WindowsForm.tsx

- [src/app/settings/views/Images/ThirdPartyDrivers/ThirdPartyDrivers.test.tsx](https://github.com/canonical-web-and-design/maas-ui/compare/main...ndv99:rtlMigration-settingsImages?expand=1#diff-07c953bff78d5ebec7e05ee3f41370d3e8b3c088e33094bba231fbbf7419f88a)
- [src/app/settings/views/Images/ThirdPartyDriversForm/ThirdPartyDriversForm.test.tsx](https://github.com/canonical-web-and-design/maas-ui/compare/main...ndv99:rtlMigration-settingsImages?expand=1#diff-1f4dd70e4ae3e33e0564cad65f14e3828e4ed49ef8b37429bff4585458a61e79)
- [src/app/settings/views/Images/VMWare/VMWare.test.tsx](https://github.com/canonical-web-and-design/maas-ui/compare/main...ndv99:rtlMigration-settingsImages?expand=1#diff-96fc59a000496146290b43cebdc20161692541a590048f2f5dfdb5a6d2d6f74 …

Migrate Enzyme to RTL - src/app/settings/views/Images

---

src/app/base/components/FormikFormButtons/FormikFormButtons.tsx
src/app/settings/views/Configuration/Commissioning/Commissioning.test.tsx
src/app/settings/views/Configuration/Commissioning/Commissioning.tsx
src/app/settings/views/Configuration/CommissioningForm/CommissioningForm.test.tsx
src/app/settings/views/Configuration/CommissioningForm/CommissioningForm.tsx
src/app/settings/views/Configuration/CommissioningFormFields/CommissioningFormFields.test.tsx
src/app/settings/views/Configuration/CommissioningFormFields/CommissioningFormFields.tsx
src/app/settings/views/Configuration/General/General.test.tsx
src/app/settings/views/Configuration/General/General.tsx
src/app/settings/views/Configuration/GeneralForm/GeneralForm.tsx
src/app/settings/views/Configuration/KernelParameters/KernelParameters.test.tsx
src/app/settings/views/Configuration/KernelParameters/KernelParameters.tsx
src/app/settings/views/Configuration/KernelParametersForm/KernelParametersForm.test.tsx
src/app/settings/views/Configuration/KernelParametersForm/KernelParametersForm.tsx

Migrated the following files to RTL:
- [src/app/settings/views/Configuration/Commissioning/Commissioning.test.tsx](https://github.com/canonical-web-and-design/maas-ui/compare/main...ndv99:rtlMigration-settingsConfiguration?expand=1#diff-6d3cd50c495313b1d0cd7ef63ef076341188ca4c954c1a2476204dd50df58b1c)
- [src/app/settings/views/Configuration/CommissioningForm/CommissioningForm.test.tsx](https://github.com/canonical-web-and-design/maas-ui/compare/main...ndv99:rtlMigration-settingsConfiguration?expand=1#diff-c8e494427b1ee602684bf78ccdf30d2a1b08384f67e62d693b9d2c378b8e5179)
- [src/app/settings/views/Configuration/CommissioningFormFields/CommissioningFormFields.test.tsx](https://github.com/canonical-web-and-design/maas-ui/compare/main...ndv99:rtlMigration-settingsConfiguration?expand=1#diff-0e7 …

Migrate Enzyme to RTL - app/settings/views/Configuration

---

src/app/machines/components/MachineHeaderForms/ActionFormWrapper/CloneForm/CloneFormFields/CloneFormFields.tsx
src/app/machines/views/MachineDetails/MachineDetails.tsx
src/app/store/machine/selectors.ts
src/app/store/machine/utils/hooks.ts

- Add selectors to get the machine details loaded/loading states.
- Update components to use new loading states.
- Go to the details page for a machine.
- It should load as it did before.
- Go to the machine list and select some machines that can be cloned from (it might be easier to select all and then click "update …

refactor(machines): update details loading states

---

src/app/base/sagas/websockets.test.ts
src/app/base/sagas/websockets.ts
src/app/store/machine/actions.test.ts
src/app/store/machine/slice.ts
src/app/store/machine/utils/hooks.ts
src/app/store/utils/slice.ts
src/websocket-client.ts

- Rename requestId to not be confused with the request_id used by the API.
Fixes: canonical/app-tribe#1226.

refactor(redux): rename requestId

---

konf/site.yaml
src/app/kvm/components/VfResources/VfResources.tsx
src/app/kvm/components/VfResources/__snapshots__/VfResources.test.tsx.snap

- Added heading for card: "Virtual Functions"
- Added an "interfaces" table column header
Fixes: https://github.com/canonical/maas-ui/issues/3923
Use [this](https://imgur.com/a/my3tWnH) album to ensure that the header displays correctly in all affected locations

Clarify header for Virtual Functions table in LXD VM hosts

---

src/app/settings/views/Network/DnsForm/DnsForm.test.tsx
src/app/settings/views/Network/NetworkDiscoveryForm/NetworkDiscoveryForm.test.tsx
src/app/settings/views/Network/NetworkDiscoveryForm/NetworkDiscoveryFormFields/NetworkDiscoveryFormFields.test.tsx
src/app/settings/views/Network/NtpForm/NtpForm.test.tsx
src/app/settings/views/Network/ProxyForm/ProxyForm.test.tsx
src/app/settings/views/Network/ProxyFormFields/ProxyFormFields.test.tsx
src/app/settings/views/Network/SyslogForm/SyslogForm.test.tsx

- [src/app/settings/views/Network/DnsForm/DnsForm.test.tsx](https://github.com/canonical/maas-ui/compare/main...ndv99:rtlMigration_settingsNetwork?expand=1#diff-1297efba3404de3ca92188f11d5a592486d67d0aced3db4b531c9e8451185142)
- [src/app/settings/views/Network/NetworkDiscoveryForm/NetworkDiscoveryForm.test.tsx](https://github.com/canonical/maas-ui/compare/main...ndv99:rtlMigration_settingsNetwork?expand=1#diff-7e0c9c39e4b1e76882345c46b8d72ea84befca89aa55927c5e9067e8938f3972)
- [src/app/settings/views/Network/NetworkDiscoveryForm/NetworkDiscoveryFormFields/NetworkDiscoveryFormFields.test.tsx](https://github.com/canonical/maas-ui/compare/main...ndv99:rtlMigration_settingsNetwork?expand=1#diff-7858c47b484a6a72bf7e7277d662ceb1e1701935399ad500027237437142b1b …

Migrate Enzyme to RTL - settings/views/Network

---

src/app/base/components/UserForm/UserForm.tsx
src/app/settings/views/Users/UserAdd/UserAdd.test.tsx
src/app/settings/views/Users/UserEdit/UserEdit.test.tsx
src/app/settings/views/Users/UserForm/UserForm.test.tsx
src/app/settings/views/Users/UserForm/UserForm.tsx
src/app/settings/views/Users/UsersList/UsersList.test.tsx

- [src/app/settings/views/Users/UserAdd/UserAdd.test.tsx](https://github.com/canonical/maas-ui/compare/main...ndv99:rtlMigration_settingsUsers?expand=1#diff-5b1ffd1b12647d2d40ebc6f13e1e30705ba37a4188b345b67962b8f521059973)
- [src/app/settings/views/Users/UserEdit/UserEdit.test.tsx](https://github.com/canonical/maas-ui/compare/main...ndv99:rtlMigration_settingsUsers?expand=1#diff-c8283da41e9d38bed90f4a5ab5b7247098a9943f1a5a12af7939fb06ddb0484a)
- [src/app/settings/views/Users/UserForm/UserForm.test.tsx](https://github.com/canonical/maas-ui/compare/main...ndv99:rtlMigration_settingsUsers?expand=1#diff-d7565f6c9ac467feb4ff10e84582e19a2e6bc4c3fb1b94d031c1ba4a24f0483d)
- [src/app/settings/views/Users/UsersList/UsersList.test.tsx](https://github.com/canonical …

Migrate Enzyme to RTL - src/app/settings/views/Users

---

src/app/settings/views/Repositories/RepositoriesList/RepositoriesList.test.tsx
src/app/settings/views/Repositories/RepositoriesList/RepositoriesList.tsx
src/app/settings/views/Repositories/RepositoryAdd/RepositoryAdd.test.tsx
src/app/settings/views/Repositories/RepositoryEdit/RepositoryEdit.test.tsx
src/app/settings/views/Repositories/RepositoryForm/RepositoryForm.test.tsx
src/app/settings/views/Repositories/RepositoryForm/RepositoryForm.tsx
src/app/settings/views/Repositories/RepositoryFormFields/RepositoryFormFields.test.tsx
src/app/settings/views/Repositories/RepositoryFormFields/RepositoryFormFields.tsx

- [src/app/settings/views/Repositories/RepositoriesList/RepositoriesList.test.tsx](https://github.com/canonical/maas-ui/compare/main...ndv99:rtlMigration_settingsRepositories?expand=1#diff-e5ac03d46e56921272833fa3ced7491c5338324548b55b4f74d804c22d32495b)
- [src/app/settings/views/Repositories/RepositoryAdd/RepositoryAdd.test.tsx](https://github.com/canonical/maas-ui/compare/main...ndv99:rtlMigration_settingsRepositories?expand=1#diff-46efd7aaf0d85faf6d0221ec060bd50f0f023dd9c7ac74cbb95884a7fe8d7634)
- [src/app/settings/views/Repositories/RepositoryEdit/RepositoryEdit.test.tsx](https://github.com/canonical/maas-ui/compare/main...ndv99:rtlMigration_settingsRepositories?expand=1#diff-c5a2e1cbc3ee64f6843d3202d95e630961e607ef0c17721866cc233036f667a6)
- …

Migrate Enzyme to RTL - src/app/settings/views/Repositories

---

src/app/settings/views/Configuration/General/General.tsx
src/app/settings/views/Configuration/GeneralForm/_index.scss

- Changed the column size on the General form in the Configuration page to 9
- Navigate to settings/configuration/general
- Ensure that content stays on the page with different window sizes

Change column size on General form to 9

---

src/__snapshots__/root-reducer.test.ts.snap
src/app/store/machine/reducers.test.ts
src/app/store/machine/slice.ts
src/app/store/machine/types/base.ts
src/app/store/machine/types/index.ts
src/testing/factories/state.ts

- Add temporary selectedMachines state to support selected filters and groups.
N/A - this is just a tiny PR to set up the new state.
Fixes: canonical/app-tribe#1139.

feat(redux): add selectedMachines state

---

src/app/store/machine/reducers.test.ts
src/app/store/machine/slice.ts
src/app/store/machine/types/base.ts

- Update the filter groups to match the new types returned by the API.
n/a
Fixes: canonical/app-tribe#1260.

fix(machines): update filter group types

---

src/app/settings/views/Scripts/ScriptDetails/ScriptDetails.test.tsx
src/app/settings/views/Scripts/ScriptsList/ScriptsList.test.tsx
src/app/settings/views/Scripts/ScriptsList/ScriptsList.tsx
src/app/settings/views/Scripts/ScriptsUpload/ScriptsUpload.test.tsx
src/app/settings/views/Scripts/ScriptsUpload/ScriptsUpload.tsx

- [src/app/settings/views/Scripts/ScriptDetails/ScriptDetails.test.tsx](https://github.com/canonical/maas-ui/compare/main...ndv99:rtlMigration_settingsScripts?expand=1#diff-2806b5ade0fadd0a184c96173ba56d70b258a68386c95ee52b590487a39b025a)
- [src/app/settings/views/Scripts/ScriptsList/ScriptsList.test.tsx](https://github.com/canonical/maas-ui/compare/main...ndv99:rtlMigration_settingsScripts?expand=1#diff-c86c355c79ed83a6724240776d590867ee55607e2ce2102799a58630b273a26f)
- [src/app/settings/views/Scripts/ScriptsUpload/ScriptsUpload.test.tsx](https://github.com/canonical/maas-ui/compare/main...ndv99:rtlMigration_settingsScripts?expand=1#diff-f4424a26d30c60e80aefdb00a339e0bd59d79acd2947997c6bcd7c29d58d1f1e)
Fixes …

Migrate Enzyme to RTL - app/settings/views/Scripts

---

src/app/preferences/components/Nav/Nav.test.tsx
src/app/preferences/views/APIKeys/APIKeyAdd/APIKeyAdd.test.tsx
src/app/preferences/views/APIKeys/APIKeyEdit/APIKeyEdit.test.tsx
src/app/preferences/views/APIKeys/APIKeyEdit/APIKeyEdit.tsx
src/app/preferences/views/APIKeys/APIKeyForm/APIKeyForm.test.tsx
src/app/preferences/views/APIKeys/APIKeyForm/APIKeyForm.tsx
src/app/preferences/views/APIKeys/APIKeyList/APIKeyList.test.tsx
src/app/preferences/views/Details/Details.test.tsx
src/app/preferences/views/Preferences.test.tsx
src/app/preferences/views/Preferences.tsx
src/app/preferences/views/SSHKeys/AddSSHKey/AddSSHKey.test.tsx
src/app/preferences/views/SSHKeys/AddSSHKey/AddSSHKey.tsx
src/app/preferences/views/SSHKeys/SSHKeyList/SSHKeyList.test.tsx
src/app/preferences/views/SSLKeys/AddSSLKey/AddSSLKey.test.tsx
src/app/preferences/views/SSLKeys/AddSSLKey/AddSSLKey.tsx
src/app/preferences/views/SSLKeys/SSLKeyList/SSLKeyList.test.tsx
src/app/preferences/views/SSLKeys/SSLKeyList/SSLKeyList.tsx

- [src/app/preferences/components/Nav/Nav.test.tsx](https://github.com/canonical/maas-ui/compare/main...ndv99:rtlMigration_preferences?expand=1#diff-b054625de3677e569ed520c2879a2cb66239a461f9eb2e5654ba0e682a12be5e)
- [src/app/preferences/views/APIKeys/APIKeyAdd/APIKeyAdd.test.tsx](https://github.com/canonical/maas-ui/compare/main...ndv99:rtlMigration_preferences?expand=1#diff-25e05a7f96eef9532c0bcfe5ff30aaa83bbcc74e0d1a4a72f17b52ce1d631774)
- [src/app/preferences/views/APIKeys/APIKeyEdit/APIKeyEdit.test.tsx](https://github.com/canonical/maas-ui/compare/main...ndv99:rtlMigration_preferences?expand=1#diff-f61619581613d263bceefa467bff3da0df19bf00fb8c6451885c43791aedd595)
- [src/app/preferences/views/APIKeys/APIKeyForm/APIKeyForm.test.tsx](https://github.co …

Migrate Enzyme to RTL - app/preferences

---

src/app/domains/components/RecordFields/RecordFields.test.tsx
src/app/domains/components/RecordFields/RecordFields.tsx
src/app/domains/views/DomainDetails/DomainDetails.test.tsx
src/app/domains/views/DomainDetails/DomainDetailsHeader/AddRecordForm/AddRecordForm.test.tsx
src/app/domains/views/DomainDetails/DomainDetailsHeader/AddRecordForm/AddRecordForm.tsx
src/app/domains/views/DomainDetails/DomainDetailsHeader/DeleteDomainForm/DeleteDomainForm.test.tsx
src/app/domains/views/DomainDetails/DomainDetailsHeader/DeleteDomainForm/DeleteDomainForm.tsx
src/app/domains/views/DomainDetails/DomainDetailsHeader/DomainDetailsHeader.test.tsx
src/app/domains/views/DomainDetails/DomainDetailsHeader/DomainDetailsHeader.tsx
src/app/domains/views/DomainDetails/DomainSummary/DomainSummary.test.tsx
src/app/domains/views/DomainDetails/DomainSummary/DomainSummary.tsx
src/app/domains/views/DomainDetails/ResourceRecords/DeleteRecordForm/DeleteRecordForm.test.tsx
src/app/domains/views/DomainDetails/ResourceRecords/DeleteRecordForm/DeleteRecordForm.tsx
src/app/domains/views/DomainDetails/ResourceRecords/EditRecordForm/EditRecordForm.test.tsx
src/app/domains/views/DomainDetails/ResourceRecords/EditRecordForm/EditRecordForm.tsx
src/app/domains/views/DomainDetails/ResourceRecords/ResourceRecords.test.tsx
src/app/domains/views/DomainDetails/ResourceRecords/ResourceRecords.tsx
src/app/domains/views/DomainsList/DomainListHeader/DomainListHeader.test.tsx
src/app/domains/views/DomainsList/DomainListHeader/DomainListHeader.tsx
src/app/domains/views/DomainsList/DomainListHeaderForm/DomainListHeaderForm.test.tsx
src/app/domains/views/DomainsList/DomainListHeaderForm/DomainListHeaderForm.tsx
src/app/domains/views/DomainsList/DomainsList.test.tsx
src/app/domains/views/DomainsList/DomainsTable/DomainsTable.test.tsx
src/app/domains/views/DomainsList/DomainsTable/DomainsTable.tsx

Migrated the following files to RTL:
- [src/app/domains/components/RecordFields/RecordFields.test.tsx](https://github.com/canonical/maas-ui/compare/main...ndv99:rtlMigration_domains?expand=1#diff-8b7ae5ab642023cbddb236a308a18d2d6d1c67051408acb892f451f66b93dd0b)
- [src/app/domains/views/DomainDetails/DomainDetails.test.tsx](https://github.com/canonical/maas-ui/compare/main...ndv99:rtlMigration_domains?expand=1#diff-f0519d8b625d73e297ce8621fb109db521176cd3c731a1c5b65e1dae4cc5d16d)
- [src/app/domains/views/DomainDetails/DomainDetailsHeader/AddRecordForm/AddRecordForm.test.tsx](https://github.com/canonical/maas-ui/compare/main...ndv99:rtlMigration_domains?expand=1#diff-4636e6070bc20d3c5e3d1f6d0fa4022c53733ff0c294e7f141c7a297a6b6e40d)
- …

Migrate Enzyme to RTL - /domains

---

src/app/store/machine/actions.test.ts
src/app/store/machine/reducers.test.ts
src/app/store/machine/slice.ts
src/app/store/machine/types/base.ts
src/app/store/machine/types/index.ts

- Add support for setting the selected machine state.
n/a
Fixes: canonical/app-tribe#1274.

feat(machines): add set selected action/reducer

---

src/app/store/machine/selectors.test.ts
src/app/store/machine/selectors.ts

- Add a selector for getting a group in a list request.
n/a
Fixes: canonical/app-tribe#1276.

feat(redux): add list group selector

---

src/app/settings/views/Settings.test.tsx
src/testing/utils.tsx

- Fix the missing store param when rendering in tests.
Fixes: #4371.

fix(testing): correctly pass the store to the testing utils

---

src/app/Routes.test.tsx

- Migrated Routes.test.tsx to RTL
Fixes https://github.com/canonical/app-tribe/issues/1310

Migrate Enzyme to RTL - src/app/Routes.test.tsx

---

cypress/support/commands.ts

- Fixed machine name generation in Cypress

test(cypress): fix machine name generation

---

src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/OverrideTestForm/OverrideTestForm.test.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/OverrideTestForm/OverrideTestForm.tsx

- feat: update override failed test form with new api
- Select a few machines
- Verify you can submit the Override failed testing form (and get an error message if machines did not have failed tests)
- Go to machine details page for a machine with failed tests
- Verify you can submit the Override failed …

feat: update override failed test form with new api

---

src/app/base/components/VaultNotification/VaultNotification.tsx
src/app/machines/views/MachineList/MachineList.test.tsx

- Make notification text for incomplete vault integration more clear

fix(vault): Make notification more clear for incomplete migration status

---

src/app/devices/components/DeviceHeaderForms/AddDeviceForm/AddDeviceForm.test.tsx
src/app/devices/components/DeviceHeaderForms/AddDeviceForm/AddDeviceForm.tsx
src/app/devices/components/DeviceHeaderForms/AddDeviceForm/AddDeviceInterfaces/AddDeviceInterfaces.test.tsx
src/app/devices/components/DeviceHeaderForms/AddDeviceForm/types.ts
src/app/devices/components/DeviceHeaderForms/DeviceActionFormWrapper/DeviceActionFormWrapper.test.tsx
src/app/devices/components/DeviceHeaderForms/DeviceHeaderForms.test.tsx

- Migrate all tests in src/app/devices/components to RTL

test: Migrate src/app/devices/components to RTL

---

README.md

- Add Playwright Tests badge
Fixes: # . …

docs: Add Playwright Tests badge

---

src/app/controllers/components/ControllerHeaderForms/ControllerActionFormWrapper/ControllerActionFormWrapper.test.tsx
src/app/controllers/components/ControllerHeaderForms/ControllerHeaderForms.test.tsx
src/app/controllers/components/ControllerStatus/ControllerStatus.test.tsx
src/app/controllers/components/ControllerStatus/ControllerStatus.tsx
src/app/controllers/components/ImageStatus/ImageStatus.test.tsx
src/app/controllers/components/ImageStatus/ImageStatus.tsx

- Migrated all tests in src/app/controllers/components to RTL

test: Migrate remaining tests in controllers/components to RTL

---

package.json

- update versions to 3.4
Fixes: # . …

update versions to 3.4

---

src/app/base/docsUrls.ts

- Updated docs URLs to reflect new URLs
Fixes #4624   .

fix(docs): Update docs URLs to new URLs

---

src/app/base/docsUrls.ts

- Fixed link to Vault docs
- Navigate to /settings/configuration/security
- Ensure the "More about Vault integration" link leads to https://maas.io/docs/how-to-enable-vault

fix: vault link

---

src/app/base/docsUrls.ts

- fixed link to Vault documentation
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. Please apply backport labels to the PR (e.g. "Backport 2.7") for the appropriate releases to target.
Only bug and security fixes should be backported, new features should only land in main.

fix: vault link 3.3

---

README.md

- docs: Update MAAS UI screenshot in the README.md
Fixes:  MAASENG-1231
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. Please apply backport labels to the PR …

docs: update MAAS UI screenshot

---

cypress/e2e/with-users/machines/details.spec.ts

- Fixed Cypress machine details spec
- Clone this branch
- Start MAAS UI
- In a separate terminal: `yarn cypress open`
- Run the machine details spec
- Ensure it passes
Fixes #4703

fix(test): Cypress machine details spec #4703

---

cypress/e2e/with-users/base/header.spec.ts
cypress/e2e/with-users/controllers/list.spec.ts
cypress/e2e/with-users/devices/list.spec.ts
cypress/e2e/with-users/domains/list.spec.ts
cypress/e2e/with-users/images/list.spec.ts
cypress/e2e/with-users/kvm/list.spec.ts
cypress/e2e/with-users/login/login.spec.ts
cypress/e2e/with-users/machines/list.spec.ts
cypress/e2e/with-users/preferences/base.spec.ts
cypress/e2e/with-users/settings/base.spec.ts
cypress/e2e/with-users/settings/configuration/general.spec.ts
cypress/e2e/with-users/subnets/subnets.spec.ts
cypress/e2e/with-users/zones/list.spec.ts

- Updated Cypress tests to account for the new side navigation
Fixes #4721

fix(test): Updated Cypress tests for new side navigation

---

cypress/e2e/with-users/base/header.spec.ts
cypress/e2e/with-users/controllers/list.spec.ts
cypress/e2e/with-users/devices/list.spec.ts
cypress/e2e/with-users/domains/list.spec.ts
cypress/e2e/with-users/images/list.spec.ts
cypress/e2e/with-users/kvm/list.spec.ts
cypress/e2e/with-users/machines/list.spec.ts
cypress/e2e/with-users/preferences/base.spec.ts
cypress/e2e/with-users/settings/base.spec.ts
cypress/e2e/with-users/subnets/subnets.spec.ts
cypress/e2e/with-users/zones/list.spec.ts
src/app/base/components/AppSideNavigation/AppSideNavCollapseToggle/AppSideNavCollapseToggle.tsx
src/app/base/components/AppSideNavigation/AppSideNavCollapseToggle/index.ts
src/app/base/components/AppSideNavigation/AppSideNavItem/AppSideNavItem.tsx
src/app/base/components/AppSideNavigation/AppSideNavItems/AppSideNavItems.tsx
src/app/base/components/AppSideNavigation/AppSideNavigation.tsx
src/app/base/components/AppSideNavigation/NavigationBanner/NavigationBanner.tsx
src/app/base/components/AppSideNavigation/_index.scss
src/app/base/components/AppSideNavigation/constants.ts
src/app/base/constants.ts
src/app/base/hooks/base.ts
src/app/settings/views/Configuration/GeneralForm/ThemedRadioButton/ThemedRadioButton.tsx
src/app/settings/views/Configuration/GeneralForm/ThemedRadioButton/_index.scss
src/scss/_patterns_icons.scss
src/scss/_patterns_typography.scss
src/scss/_settings.scss
src/scss/_utilities.scss
src/scss/_vanilla-overrides.scss

- Implement collapsible side navigation
- restructure the navigation to use vanilla classes
- highlight parent when any of its children are active
- remove hidden items when collapsed
- reorganise `l-navigation--` color modifier classes and rename to `is-maas-`
- use `is-maas-` color className in `ThemedRadioButton`
- add global `[`  keyboard shortcut for expanding and collapsing the navigation
this will be followed up by https://warthogs.atlassian.net/browse/MAASENG-1356 to look into allowing for collapsibility across all breakpoints
- [A local snap MAAS](/HACKING.md#snap-deployment) (this …

feat: collapsible side navigation MAASENG-1282

---

tests/machines.spec.ts

- test: update machine list playwright test to reflect latest changes
Fixes: # .
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. Please apply backport labels …

test: update machine list playwright test

---

cypress/constants.ts

- test: update cypress a11y test
Fixes: https://github.com/canonical/maas-ui/issues/4754 …

test: update cypress a11y test

---

.eslintrc.js

- add console warning via eslint 
Fixes: # .
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. Please apply backport labels to the PR (e.g. "Backport 2.7") for …

 test: eslint add console warning

---

README.md

- Update MAAS UI screenshot in README.md
[MAASENG-1598](https://warthogs.atlassian.net/browse/MAASENG-1598) …

Update MAAS UI screenshot in README.md

---

src/app/kvm/components/KVMHeaderForms/AddLxd/CredentialsForm/CredentialsForm.test.tsx

- Migrated src/app/kvm/components/KVMHeaderForms/AddLxd/CredentialsForm/CredentialsForm.test.tsx to RTL
Fixes [MAASENG-1625](https://warthogs.atlassian.net/browse/MAASENG-1615)
[MAASENG-1625]: https://warthogs.atlassian.net/browse/MAASENG-1625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: Migrate KVM CredentialsForm.test to RTL MAASENG-1625

---

src/app/kvm/components/KVMHeaderForms/ComposeForm/ComposeFormFields/ComposeFormFields.test.tsx
src/app/kvm/components/KVMHeaderForms/ComposeForm/ComposeFormFields/ComposeFormFields.tsx

- Migrated src/app/kvm/components/KVMHeaderForms/ComposeForm/ComposeFormFields/ComposeFormFields.test.tsx to RTL
Fixes [MAASENG-1615](https://warthogs.atlassian.net/browse/MAASENG-1615)
[MAASENG-1615]: https://warthogs.atlassian.net/browse/MAASENG-1615?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: Migrate KVM ComposeFormFields.test to RTL MAASENG-1615

---

src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/DeployForm/DeployForm.test.tsx
src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.tsx

- Migrated src/app/machines/components/MachineHeaderForms/MachineActionFormWrapper/DeployForm/DeployForm.test.tsx to RTL
Fixes [MAASENG-1622](https://warthogs.atlassian.net/browse/MAASENG-1622)
[MAASENG-1622]: https://warthogs.atlassian.net/browse/MAASENG-1622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: Migrate DeployForm.test to RTL MAASENG-1622

---

src/app/machines/views/MachineDetails/MachineNetwork/EditBondForm/EditBondForm.test.tsx
src/app/machines/views/MachineDetails/MachineNetwork/EditBondForm/EditBondForm.tsx

- Migrated src/app/machines/views/MachineDetails/MachineNetwork/EditBondForm/EditBondForm.test.tsx to RTL
Fixes [MAASENG-1621](https://warthogs.atlassian.net/browse/MAASENG-1621)
[MAASENG-1621]: https://warthogs.atlassian.net/browse/MAASENG-1621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: Migrate EditBondForm to RTL MAASENG-1621

---

src/app/machines/views/Machines.test.tsx

- Migrated src/app/machines/views/Machines.test.tsx to RTL
Fixes [MAASENG-1616](https://warthogs.atlassian.net/browse/MAASENG-1616)
[MAASENG-1616]: https://warthogs.atlassian.net/browse/MAASENG-1616?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: Migrate remaining tests in Machines.test to RTL MAASENG-1616

---

src/app/machines/views/MachineList/MachineList.test.tsx

- Migrated src/app/machines/views/MachineList/MachineList.test.tsx to RTL
Fixes [MAASENG-1614](https://warthogs.atlassian.net/browse/MAASENG-1614)
[MAASENG-1614]: https://warthogs.atlassian.net/browse/MAASENG-1614?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: Migrate remaining test in MachineList.test to RTL MAASENG-1614

---

src/app/base/components/node/NodeDevices/NodeDevices.test.tsx

- Migrated src/app/base/components/node/NodeDevices/NodeDevices.test.tsx to RTL
Fixes [MAASENG-1698](https://warthogs.atlassian.net/browse/MAASENG-1698)
[MAASENG-1698]: https://warthogs.atlassian.net/browse/MAASENG-1698?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: Migrate NodeDevices.test to RTL MAASENG-1698

---

src/app/base/components/PowerTypeFields/PowerTypeFields.test.tsx

- Migrated src/app/base/components/PowerTypeFields/PowerTypeFields.test.tsx to RTL
Fixes [MAASENG-1694](https://warthogs.atlassian.net/browse/MAASENG-1694)
[MAASENG-1694]: https://warthogs.atlassian.net/browse/MAASENG-1694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: Migrate PowerTypeFields.test to RTL MAASENG-1694

---

src/app/base/components/node/NodeTestDetails/NodeTestDetails.test.tsx

- Migrated src/app/base/components/node/NodeTestDetails/NodeTestDetails.test.tsx to RTL
Fixes [MAASENG-1699](https://warthogs.atlassian.net/browse/MAASENG-1699)
[MAASENG-1699]: https://warthogs.atlassian.net/browse/MAASENG-1699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: Migrate NodeTestDetails.test to RTL MAASENG-1699

---

src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.test.tsx
src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.tsx

- refactor MachineHeader test to RTL
- run `yarn test src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.test.tsx`
[Fixes: MAASENG-1706](https://warthogs.atlassian.net/browse/MAASENG-1706)

1706 refactor machine header test rtl

---

src/app/kvm/components/KVMHeaderForms/ComposeForm/ComposeForm.test.tsx

- Migrated src/app/kvm/components/KVMHeaderForms/ComposeForm/ComposeForm.test.tsx to RTL
Fixes [MAASENG-1723](https://warthogs.atlassian.net/browse/MAASENG-1723)
[MAASENG-1723]: https://warthogs.atlassian.net/browse/MAASENG-1723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: Migrate ComposeForm.test to RTL MAASENG-1723

---

src/app/App.test.tsx

- Migrated src/app/App.test.tsx to RTL
Fixes [MAASENG-1749](https://warthogs.atlassian.net/browse/MAASENG-1749)
[MAASENG-1749]: https://warthogs.atlassian.net/browse/MAASENG-1749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: Migrate App.test to RTL MAASENG-1749

---

src/app/devices/views/DeviceList/DeviceListTable/DeviceListTable.test.tsx

- Migrated src/app/devices/views/DeviceList/DeviceListTable/DeviceListTable.test.tsx to RTL
Fixes [MAASENG-1721](https://warthogs.atlassian.net/browse/MAASENG-1721)
[MAASENG-1721]: https://warthogs.atlassian.net/browse/MAASENG-1721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: Migrate DeviceListTable to RTL MAASENG-1721

---

src/app/base/components/node/StorageTables/AvailableStorageTable/BulkActions/BulkActions.test.tsx
src/app/base/components/node/StorageTables/AvailableStorageTable/BulkActions/CreateDatastore/CreateDatastore.tsx
src/app/base/components/node/StorageTables/AvailableStorageTable/BulkActions/CreateRaid/CreateRaidFields/CreateRaidFields.tsx
src/app/base/components/node/StorageTables/AvailableStorageTable/BulkActions/CreateVolumeGroup/CreateVolumeGroup.tsx
src/app/base/components/node/StorageTables/AvailableStorageTable/BulkActions/UpdateDatastore/UpdateDatastoreFields/UpdateDatastoreFields.tsx

- Migrated src/app/base/components/node/StorageTables/AvailableStorageTable/BulkActions/BulkActions.test.tsx to RTL
Fixes [MAASENG-1720](https://warthogs.atlassian.net/browse/MAASENG-1720)
[MAASENG-1720]: https://warthogs.atlassian.net/browse/MAASENG-1720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: Migrate BulkActions.test to RTL MAASENG-1720

---

src/app/kvm/components/KVMHeaderForms/AddLxd/AuthenticationForm/AuthenticationForm.test.tsx
src/app/kvm/components/KVMHeaderForms/AddLxd/AuthenticationForm/AuthenticationFormFields/AuthenticationFormFields.tsx

- Migrated src/app/kvm/components/KVMHeaderForms/AddLxd/AuthenticationForm/AuthenticationForm.test.tsx to RLT
Fixes [MAASENG-1722](https://warthogs.atlassian.net/browse/MAASENG-1722)
[MAASENG-1722]: https://warthogs.atlassian.net/browse/MAASENG-1722?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: Migrate AuthenticationForm to RTL MAASENG-1722

---

src/app/base/components/node/StorageTables/StorageTables.test.tsx
src/app/kvm/components/KVMHeaderForms/ComposeForm/StorageTable/StorageTable.test.tsx
src/app/kvm/components/KVMHeaderForms/ComposeForm/StorageTable/StorageTable.tsx

- Update render method for StorageTableTests
- run `yarn test src/app/base/components/node/StorageTables/StorageTables.test.tsx`
[MAASENG-1724](https://warthogs.atlassian.net/jira/software/c/projects/MAASENG/issues/MAASENG-1724)
[MAASENG-1724]: https://warthogs.atlassian.net/browse/MAASENG-1724?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Test: Update render method for StorageTableTests

---

src/app/base/components/node/NodeTestsTable/TestActions/TestActions.test.tsx
src/app/base/components/node/NodeTestsTable/TestHistory/TestHistory.test.tsx
src/app/base/components/node/StorageTables/AvailableStorageTable/AddLogicalVolume/AddLogicalVolume.test.tsx
src/app/base/components/node/StorageTables/AvailableStorageTable/AddPartition/AddPartition.test.tsx
src/app/base/components/node/StorageTables/AvailableStorageTable/AddPartition/AddPartitionFields/AddPartitionFields.tsx
src/app/base/components/node/StorageTables/AvailableStorageTable/BulkActions/CreateDatastore/CreateDatastore.test.tsx
src/app/base/components/node/StorageTables/AvailableStorageTable/BulkActions/CreateVolumeGroup/CreateVolumeGroup.test.tsx
src/app/base/components/node/TestForm/TestForm.test.tsx
src/app/base/components/node/networking/SubnetColumn/SubnetColumn.test.tsx

Migrated the following test files to RTL:
```
8.0K	./src/app/base/components/node/NodeTestsTable/TestActions/TestActions.test.tsx
8.0K	./src/app/base/components/node/NodeTestsTable/TestHistory/TestHistory.test.tsx
8.0K	./src/app/base/components/node/StorageTables/AvailableStorageTable/AddLogicalVolume/AddLogicalVolume.test.tsx
8.0K	./src/app/base/components/node/StorageTables/AvailableStorageTable/AddPartition/AddPartition.test.tsx
8.0K	./src/app/base/components/node/StorageTables/AvailableStorageTable/BulkActions/CreateDatastore/CreateDatastore.test.tsx
8.0K	./src/app/base/components/node/StorageTables/AvailableStorageTable/BulkActions/CreateVolumeGroup/CreateVolumeGroup.test.tsx
8.0K	./src/app/base/components/node/TestForm/TestForm.test.tsx
8.0K …
```

test: Migrate 8 nodes tests to RTL MAASENG-1732

---

src/app/kvm/components/StorageColumn/StoragePopover/StoragePopover.test.tsx
src/app/kvm/components/StorageResources/StorageCards/StorageCards.test.tsx
src/app/kvm/components/StorageResources/StorageCards/StorageCards.tsx
src/app/kvm/components/StorageResources/StorageMeter/StorageMeter.tsx
src/app/kvm/components/StorageResources/StorageResources.test.tsx

```
4.0K	./src/app/kvm/components/StorageColumn/StoragePopover/StoragePopover.test.tsx
4.0K	./src/app/kvm/components/StorageResources/StorageCards/StorageCards.test.tsx
4.0K	./src/app/kvm/components/StorageResources/StorageResources.test.tsx
```
`yarn test`
[MAASENG-1747](https://warthogs.atlassian.net/browse/MAASENG-1747)
[MAASENG-1747]: https://warthogs.atlassian.net/browse/MAASENG-1747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

1747 migrate storage tests rtl

---

src/app/devices/views/DeviceList/DeviceList.test.tsx
src/app/devices/views/DeviceList/DeviceListControls/DeviceFilterAccordion/DeviceFilterAccordion.test.tsx
src/app/devices/views/DeviceList/DeviceListControls/DeviceListControls.test.tsx

```
4.0K	./src/app/devices/views/DeviceList/DeviceList.test.tsx
4.0K	./src/app/devices/views/DeviceList/DeviceListControls/DeviceFilterAccordion/DeviceFilterAccordion.test.tsx
4.0K	./src/app/devices/views/DeviceList/DeviceListControls/DeviceListControls.test.tsx
```
Fixes [MAASENG-1740](https://warthogs.atlassian.net/browse/MAASENG-1740)
[MAASENG-1612]: https://warthogs.atlassian.net/browse/MAASENG-1612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MAASENG-1740]: https://warthogs.atlassian.net/browse/MAASENG-1740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: Migrate 3 small Devices tests to RTL MAASENG-1740

---

src/app/kvm/components/KVMConfigurationCard/KVMConfigurationCardFields/KVMConfigurationCardFields.test.tsx
src/app/kvm/components/KVMConfigurationCard/KVMConfigurationCardFields/KVMConfigurationCardFields.tsx
src/app/kvm/components/KVMStorageCards/KVMStorageCards.test.tsx
src/app/kvm/components/LXDHostVMs/LXDHostVMs.test.tsx
src/app/kvm/components/LXDHostVMs/NumaResources/NumaResourcesCard/NumaResourcesCard.test.tsx
src/app/kvm/components/RAMColumn/RAMColumn.test.tsx

Migrated the following files to RTL:
```
8.0K	./src/app/kvm/components/KVMConfigurationCard/KVMConfigurationCardFields/KVMConfigurationCardFields.test.tsx
8.0K	./src/app/kvm/components/KVMStorageCards/KVMStorageCards.test.tsx
8.0K	./src/app/kvm/components/LXDHostVMs/LXDHostVMs.test.tsx
8.0K	./src/app/kvm/components/LXDHostVMs/NumaResources/NumaResourcesCard/NumaResourcesCard.test.tsx
8.0K	./src/app/kvm/components/RAMColumn/RAMColumn.test.tsx
```
Fixes [MAASENG-1739](https://warthogs.atlassian.net/browse/MAASENG-1739)
[MAASENG-1739]: https://warthogs.atlassian.net/browse/MAASENG-1739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: Migrate 5 KVM components to RTL MAASENG-1739

---

src/app/kvm/components/KVMHeaderForms/AddVirsh/AddVirshFields/AddVirshFields.test.tsx
src/app/kvm/components/KVMHeaderForms/RefreshForm/RefreshForm.test.tsx

Migrate to RTL
```
4.0K	./src/app/kvm/components/KVMHeaderForms/AddVirsh/AddVirshFields/AddVirshFields.test.tsx
4.0K	./src/app/kvm/components/KVMHeaderForms/RefreshForm/RefreshForm.test.tsx
```
`yarn test`
[MAASENG-1746](https://warthogs.atlassian.net/browse/MAASENG-1746)
[MAASENG-1746]: https://warthogs.atlassian.net/browse/MAASENG-1746?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

1746 migrate kvm header forms rtl

---

src/app/base/side-panel-context.tsx

- fix: sidepanel closing prematurely
- Go to controller details page
- Open side panel by clicking "Add a new controller"
- Verify a side panel remained open
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless the fix is only …

fix: sidepanel closing prematurely

---

src/app/Routes.tsx
src/app/zones/views/ZoneDetails/ZoneDetails.tsx

- Refactored ZoneDetails to use PageContent instead of MainContentSection
Fixes [MAASENG-1830](https://warthogs.atlassian.net/browse/MAASENG-1830)
[MAASENG-1830]: https://warthogs.atlassian.net/browse/MAASENG-1830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Refactor ZoneDetails to use PageContent MAASENG-1830

---

src/app/Routes.tsx
src/app/zones/constants.ts
src/app/zones/views/ZonesList/ZonesList.test.tsx
src/app/zones/views/ZonesList/ZonesList.tsx
src/app/zones/views/ZonesList/ZonesListHeader/ZonesListHeader.test.tsx
src/app/zones/views/ZonesList/ZonesListHeader/ZonesListHeader.tsx

- Refactored ZonesList and ZonesListHeader to use PageContent
Fixes [MAASENG-1831](https://warthogs.atlassian.net/browse/MAASENG-1831)
[MAASENG-1831]: https://warthogs.atlassian.net/browse/MAASENG-1831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Refactor ZonesList to use PageContent MAASENG-1831

---

.github/workflows/playwright.yml
.github/workflows/test.yml

- release v3.4.0
In general, please propose fixes against _main_ rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. Please apply backport labels to the PR (e.g. "Backport 2.7") for the appropriate releases to target.
Only bug …

release v3.4.0

---

src/app/Routes.tsx
src/app/controllers/views/ControllerList/ControllerList.tsx
src/app/controllers/views/ControllerList/ControllerListHeader/ControllerListHeader.test.tsx
src/app/controllers/views/ControllerList/ControllerListHeader/ControllerListHeader.tsx

- Refactor ControllerList page to use PageComponent
[MAASENG-1807](https://warthogs.atlassian.net/jira/software/c/projects/MAASENG/issues/MAASENG-1807)
[MAASENG-1807]: https://warthogs.atlassian.net/browse/MAASENG-1807?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Chore: MAASENG 1807 controller list page component refactor

---

src/app/kvm/components/KVMDetailsHeader/KVMDetailsHeader.test.tsx
src/app/kvm/components/KVMDetailsHeader/KVMDetailsHeader.tsx
src/app/kvm/views/VirshDetails/VirshDetails.tsx
src/app/kvm/views/VirshDetails/VirshDetailsHeader/VirshDetailsHeader.tsx

- refactor VirshDetails to use PageComponent
[MAASENG-1819](https://warthogs.atlassian.net/browse/MAASENG-1819)
[MAASENG-1819]: https://warthogs.atlassian.net/browse/MAASENG-1819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Chore: MAASENG 1819 refactor virsh details page component

---

src/app/kvm/views/LXDSingleDetails/LXDSingleDetails.tsx
src/app/kvm/views/LXDSingleDetails/LXDSingleDetailsHeader/LXDSingleDetailsHeader.test.tsx
src/app/kvm/views/LXDSingleDetails/LXDSingleDetailsHeader/LXDSingleDetailsHeader.tsx

- Refactor LXDSingle details PageComponent
[MAASENG-1818](https://warthogs.atlassian.net/browse/MAASENG-1818)
[MAASENG-1818]: https://warthogs.atlassian.net/browse/MAASENG-1818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: MAASENG 1818 refactor lxd single details page component

---

src/app/machines/views/MachineList/MachineList.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListPagination/MachineListPagination.test.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListPagination/MachineListPagination.tsx
src/app/machines/views/MachineList/MachineListTable/MachineListTable.tsx
src/app/store/machine/selectors.ts
src/app/store/machine/utils/hooks.ts

- fix: machine list pagination (#5029) 
lp#2025375
https://bugs.launchpad.net/maas-ui/+bug/2025375

fix: machine list pagination (#5029) lp#2025375 3.4 backport

---

cypress/e2e/with-users/machines/actions.spec.ts

- test: fix cypress machine actions test

test: fix cypress machine actions test

---

src/app/store/machine/reducers.test.ts
src/app/store/machine/slice.ts

fix: machine editing details #5072 backport 3.4
Done as part of #5072

fix: machine editing details #5072 backport 3.4

---

.eslintrc.js
package.json
tests/machines.spec.ts
yarn.lock

- test: add eslint-plugin-playwright
- add missing await
- add comment explaining no-force override

test: add eslint-plugin-playwright

---

cypress/e2e/with-users/subnets/add.spec.ts

test: update subnets add spec
https://github.com/canonical/maas-ui/issues/5080 https://github.com/canonical/maas-ui/issues/4995

test: update subnets add spec

---

src/app/settings/views/Images/WindowsForm/WindowsForm.tsx

- fix: nullable field error lp#2030095
- Go through steps as defined in the related bug report https://bugs.launchpad.net/maas-ui/+bug/2030095
- Make sure no error is thrown either in the browser console or form validation on blur
Fixes: lp#2030095

fix: nullable field error lp#2030095

---

.github/workflows/upload.yml

ci: fix upload workflow sha

---

cypress/support/e2e.ts
src/app/base/docsUrls.ts
src/app/machines/views/MachineDetails/MachineStorage/MachineStorage.tsx

- Update docurls on app
- Handled uncaught exceptions
- Ensure `docs-links.spec.ts` is passing
Fixes: #5111

5111 fix docs link tests

---

src/app/base/components/SSHKeyForm/SSHKeyForm.test.tsx

- test(SSHKeyForm): add waitFor store actions
https://github.com/canonical/maas-ui/actions/runs/6035652508/job/16408233869

test(SSHKeyForm): add waitFor store actions

---

cypress/e2e/no-users/local-docs.spec.ts
scripts/proxy.js

- feat(docs): proxy local docs do MAAS
- Click on Local documentation link at the bottom of the page
- Local documentation should be displayed

feat(docs): proxy local docs do MAAS

---

src/app/base/components/CertificateDownload/CertificateDownload.tsx

- Fixed horizontal scrollbar on the Authentication section of the "Add LXD" form
- Go to /kvm/lxd
- Click "Add LXD host"
- Fill in details and submit (should go to "Authentication" form)
- Click "Add trust to LXD via command line"
- Ensure the certificate is displayed in a code block
- Ensure the scroll bars render properly …

fix(lxd): Code snippet horizontal scrolling in certificate MAASENG-2145

---

docs/HACKING.md

- Add info on JSDoc to `HACKING.md`

docs: Update HACKING.md

---

README.md

- docs: Add sitespeed.io badge to README.md

docs: Add sitespeed.io badge to README.md

---

.github/ISSUE_TEMPLATE/accessibility-failure.md
.github/ISSUE_TEMPLATE/ci-failure.md
.github/ISSUE_TEMPLATE/cypress-failure.md
.github/ISSUE_TEMPLATE/maas-io-docs-failed.md
.github/ISSUE_TEMPLATE/upload-failure.md
.github/workflows/accessibility.yml
.github/workflows/cypress.yml
.github/workflows/links-checker.yml
.github/workflows/sitespeed.yml
.github/workflows/upload.yml

- Added failure condition to sitespeed.io workflow
- Created universal CI failure issue template
- Directed all non-PR workflows to use template
Fixes [MAASENG-2176](https://warthogs.atlassian.net/browse/MAASENG-2176)
[MAASENG-2176]: https://warthogs.atlassian.net/browse/MAASENG-2176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(ci): Create issue on sitespeed failure MAASENG-2176

---

cypress/support/e2e.ts

- Add cpNs so list of unloaded scripts
closes #5175

fix MAAS docs link checker tests

---

docs/MAASUI.md

- docs: machine list requests 
- Go to MAAS UI and open redux devtools
- Compare the state slices against the documentation
- Verify that the documentation is clear and is up to date in regards to the state slices it describes
Fixes: MAASENG-1906

docs: machine list requests MAASENG-1906

---

konf/site.yaml

- ci: update demo MAAS_URL
- Go to the demo URL and make sure MAAS UI loads correctly

ci: update demo MAAS_URL

---

cypress/e2e/with-users/machines/actions.spec.ts
cypress/support/commands.ts

- fix failing machine actions cypress tests
Fixes: [MAASEENG-2182](https://warthogs.atlassian.net/browse/MAASENG-2182)

MAASENG-2182 address cypress intermittent failures

---

package.json
src/app/base/components/CertificateDetails/CertificateDetails.tsx
src/app/base/components/DHCPTable/DHCPTable.tsx
src/app/base/components/SSHKeyForm/SSHKeyFormFields/SSHKeyFormFields.tsx
src/app/base/components/node/OverviewCard/MachineStatusCard/MachineStatusCard.tsx
src/app/controllers/components/ControllerForms/AddController/AddController.tsx
src/app/controllers/views/ControllerList/ControllerListTable/ControllerListTable.tsx
src/app/controllers/views/ControllerList/ControllerListTable/StatusColumn/StatusColumn.tsx
src/app/dashboard/views/DashboardHeader/ClearAllForm/ClearAllForm.tsx
src/app/kvm/components/KVMForms/AddLxd/AuthenticationForm/AuthenticationForm.tsx
src/app/machines/components/MachineForms/AddChassis/AddChassisForm/AddChassisForm.tsx
src/app/machines/components/MachineForms/AddMachine/AddMachineForm/AddMachineForm.tsx
src/app/machines/components/MachineForms/MachineActionFormWrapper/CloneForm/CloneForm.tsx
src/app/machines/components/MachineForms/MachineActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.tsx
src/app/machines/views/MachineDetails/MachineStorage/MachineStorage.tsx
src/app/machines/views/MachineDetails/MachineSummary/WorkloadCard/WorkloadCard.tsx
src/app/preferences/views/SSHKeys/SSHKeyList/SSHKeyList.tsx
src/app/settings/views/Configuration/GeneralForm/GeneralForm.tsx
src/app/settings/views/Security/IpmiSettings/IpmiFormFields/IpmiFormFields.tsx
src/app/settings/views/Security/SecretStorage/VaultSettings/VaultSettings.tsx
src/app/settings/views/Security/SecurityProtocols/TLSDisabled/TLSDisabled.tsx
src/app/settings/views/Security/SecurityProtocols/TLSEnabled/TLSEnabledFields/TLSEnabledFields.tsx
src/app/subnets/components/ReservedRanges/ReservedRanges.tsx
src/app/subnets/views/VLANDetails/ConfigureDHCP/ConfigureDHCP.tsx
src/app/subnets/views/VLANDetails/DHCPStatus/DHCPStatus.tsx
src/app/tags/components/DefinitionField/DefinitionField.tsx
src/app/tags/components/KernelOptionsField/KernelOptionsField.tsx
src/app/tags/views/TagList/TagTable/TagTable.tsx
src/app/tags/views/TagUpdate/TagUpdateFormFields/TagUpdateFormFields.tsx
yarn.lock

- Replace all anchor tags and `<Link />` components with `<ExternalLink />` from `@canonical/maas-react-components`

refactor: use external link

---

src/app/base/components/ActionForm/ActionForm.test.tsx
src/app/base/components/ActionForm/ActionForm.tsx
src/app/base/components/ActionForm/index.ts

- fix: import images lp#2031614
Fixes: [lp#2031614](https://bugs.launchpad.net/maas-ui/+bug/2031614)

fix: import images lp#2031614

---

src/app/base/components/ActionForm/ActionForm.test.tsx
src/app/base/components/ActionForm/ActionForm.tsx
src/app/base/components/ActionForm/index.ts

- fix: import images lp#2031614 (#5200)

fix: import images lp#2031614 (#5200) 

---

src/app/base/types.ts
src/app/store/machine/types/actions.ts

- This adds a TypeScript Prettify tool that allows for more helpful type annotations
https://www.totaltypescript.com/concepts/the-prettify-helper

chore: add ts prettify

---

package.json
src/app/kvm/components/KVMForms/ComposeForm/StorageTable/PoolSelect/PoolSelect.tsx
src/app/kvm/components/KVMResourceMeter/KVMResourceMeter.tsx
src/app/kvm/components/StorageColumn/StoragePopover/StoragePopover.tsx
yarn.lock

- update to latest meter component from maas-react-components 
Fixes:

refactor: update meter component

---

src/app/base/sagas/http.ts

- Move fastapi endpoint from v1 to v2

fix(zones): Update fastapi endpoint v1 to v2

---

src/app/controllers/views/ControllerList/ControllerListHeader/ControllerListHeader.tsx

- test: add testid to controllers header
Fixes: https://github.com/canonical/maas-ui/issues/5243

test: add testid to controllers header

---

cypress/constants.ts
cypress/e2e/accessibility/accessibility.spec.ts
cypress/support/commands.ts
src/app/intro/components/IntroCard/IntroCard.tsx
src/app/preferences/views/Details/Details.tsx

- test: update e2e headings queries
- add missing preferences heading
Fixes: https://github.com/canonical/maas-ui/issues/5260

test: update e2e headings queries

---

tests/machines.spec.ts

- test: update playwright selectors
Fixes:

test: update playwright selectors

---

cypress/e2e/with-users/domains/list.spec.ts

- Updated test id for finding header on domains list
This is one PR in what will be a series of PRs to fix our failing Cypress runs.

test: fix Cypress domains list test

---

cypress/e2e/with-users/images/list.spec.ts
cypress/e2e/with-users/kvm/list.spec.ts
cypress/e2e/with-users/zones/list.spec.ts

- Fix test id selectors in image list, kvm list, and zones list E2E tests

test: fix remaining cypress tests looking for "section-header-title"

---

cypress/e2e/with-users/subnets/add.spec.ts
src/app/subnets/views/SubnetsList/SubnetsTable/components.tsx
src/app/subnets/views/SubnetsList/SubnetsTable/types.ts
src/app/subnets/views/SubnetsList/SubnetsTable/utils.tsx

- Added aria-label to subnet table rows, equivalent to fabric name
- Removed old assertions that do not apply to the new layout

test: fix Cypress subnet add tests

---

src/app/App.tsx
src/app/Routes.test.tsx
src/app/Routes.tsx
src/app/base/hooks/base.test.tsx
src/app/machines/views/MachineDetails/MachineDetails.test.tsx
src/testing/constants.ts
yarn.lock

- feat: add lazy loading of base routes
- add LONG_TEST_TIMEOUT
- add tests for useWindowTitle hook
Fixes: 
Loading indicator displayed as a fallback for lazily loaded route

feat: add lazy loading of base routes

---

cypress/e2e/with-users/controllers/details.spec.ts
cypress/e2e/with-users/machines/list.spec.ts
cypress/support/commands.ts

- test: fix cypress failures #5281
Fixes:

test: fix cypress failures #5281 WIP

---

.github/workflows/cypress.yml

- ci: run cypress on pr
- group cypress tests by priority and run in parallel

ci: run cypress on pr

---

.github/workflows/cypress.yml

- ci(cypress): create issue only on main branches
Fixes:

ci(cypress): create issue only on main branches

---

.gitignore
.vscode/settings.json

- chore: remove .vscode settings
- update vscode gitignore
Fixes:

chore: remove .vscode settings

---

.github/workflows/sitespeed.yml

- ci: refactor sitespeed login retry

ci: refactor sitespeed login retry

---

src/app/images/views/ImageList/ImageListHeader/ImageListHeader.tsx

- Update image sync information
Fixes:

feat: update image sync (tooltip) information

---

src/app/subnets/components/ReservedRangeForm/ReservedRangeForm.test.tsx
src/app/subnets/components/ReservedRangeForm/ReservedRangeForm.tsx

- fix: reserve range error state
Fixes: https://warthogs.atlassian.net/browse/MAASENG-2882

fix: reserve range error state

---

src/app/base/components/AppSidePanel/AppSidePanel.tsx

- fix: side panel content section
Fixes:

fix: align side panel content section header

---

cypress/e2e/with-users/analytics.ts
package.json
src/app/base/hooks/analytics.ts
yarn.lock

- chore: update to Google Analytics 4 MAASENG-2910
- add @types/google.analytics
- replace custom setup with `react-ga4`
Fixes:

chore: update to Google Analytics 4 MAASENG-2910

---

cypress/e2e/with-users/subnets/add.spec.ts
cypress/e2e/with-users/subnets/staticroutes.spec.ts
cypress/support/commands.ts
cypress/support/e2e.ts
src/app/subnets/views/SubnetDetails/StaticRoutes/DeleteStaticRouteform/DeleteStaticRouteForm.test.tsx
src/app/subnets/views/SubnetDetails/StaticRoutes/DeleteStaticRouteform/DeleteStaticRouteForm.tsx
src/app/subnets/views/SubnetDetails/StaticRoutes/EditStaticRouteForm/EditStaticRouteForm.test.tsx
src/app/subnets/views/SubnetDetails/StaticRoutes/EditStaticRouteForm/EditStaticRouteForm.tsx
src/app/subnets/views/SubnetDetails/StaticRoutes/StaticRoutes.tsx
src/app/subnets/views/SubnetDetails/SubnetDetails.tsx
src/app/subnets/views/SubnetDetails/SubnetDetailsHeader/SubnetActionForms/SubnetActionForms.tsx
src/app/subnets/views/SubnetDetails/constants.ts
src/app/subnets/views/SubnetDetails/types.ts

- fix: static routes edit and delete 
- add e2e test for static routes
- add addSubnet cypress helper function
Fixes: lp#2060176 lp#2060177

fix: static routes edit and delete lp#2060176 lp#2060177 MAASENG-2966

---

.github/workflows/links-checker.yml

- ci: set docs link checker branches
Fixes:

ci: set docs link checker branches

---

src/app/utils/subnetIpRange.test.ts
src/app/utils/subnetIpRange.ts

- Created `getIpRangeFromCIDR`
- Created `isIpInSubnet`
Fixes [MAASENG-2980](https://warthogs.atlassian.net/browse/MAASENG-2980)
[MAASENG-2980]: https://warthogs.atlassian.net/browse/MAASENG-2980?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(utils): add util functions for IP address validation MAASENG-2980

---

src/app/base/components/SSHKeyList/SSHKeyList.test.tsx
src/app/base/components/SSHKeyList/SSHKeyList.tsx
src/app/base/components/SSHKeyList/_index.scss
src/app/preferences/views/APIKeys/APIKeyList/APIKeyList.tsx
src/app/preferences/views/SSLKeys/SSLKeyList/SSLKeyList.tsx

- fix: ssh key display lp#2064920
- display the entire ssh key comment text
- show the full SSH key value on hover
Fixes:

fix: ssh key display lp#2064920

---

cypress/e2e/with-users/subnets/staticroutes.spec.ts

- fixed failing cypress static routes test
Fixes #5393

fix(cypress): failing static routes test

---

README.md

- docs: add code coverage link to README.md
- Ensure that the link opens the code coverage report for maas-ui.

docs: add code coverage link to README.md

---

README.md

- docs: Update code coverage URL in README.md

docs: Update code coverage URL in README.md

---

cypress/e2e/docs-links/docs-links.spec.ts
package.json
src/app/base/docsUrls.ts

- fix: update docs links
- refactor docs links tests for easier debugging
Fixes: https://github.com/canonical/maas-ui/issues/5276
https://github.com/canonical/maas-ui/actions/runs/9484998728
Custom error message making URL updates easier.

fix: update docs links #5276

---

src/setupTests.ts
src/testing/customMatchers.test.ts
src/testing/customMatchers.ts

- test: add toBeAriaDisabled matcher

test: add toBeAriaDisabled matcher

---

src/testing/utils.tsx

- test: use vi.waitFor by default

test: use vi.waitFor by default

---

cypress/e2e/docs-links/docs-links.spec.ts
src/app/base/docsUrls.ts

- docs: update docs link
- test: remove heading docs test
After this change we only ensure that the page itself displays as expected and don't test specific heading id.
Ever since we display a heading for MAAS variant (UI/CLI) headings change very often and it's not feasible to keep these links updated.
Fixes:

docs: update docs link

---

src/app/base/components/LinkModeSelect/LinkModeSelect.tsx
src/app/base/components/node/networking/NetworkTable/IPColumn/IPColumn.test.tsx
src/app/devices/views/DeviceDetails/DeviceNetwork/DeviceNetworkTable/DeviceNetworkTable.tsx
src/app/networkDiscovery/views/DiscoveryAddForm/DiscoveryAddFormFields/DiscoveryAddFormFields.test.tsx
src/app/store/device/utils/common.test.ts
src/app/store/device/utils/common.ts
src/app/store/utils/node/networking.test.ts
src/app/store/utils/node/networking.ts

- Rename "Static" to "Static (Client configured)
- Rename "External" to "Static (Externally managed)
- Rename "IP mode" to "IP assignment"
- Rename "DHCP" to "Dynamic"
- Rename "Auto assign" to "Automatic"
Fixes [MAASENG-3519](https://warthogs.atlassian.net/browse/MAASENG-3519)
[MAASENG-3519]: https://warthogs.atlassian.net/browse/MAASENG-3519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: Use names 'Static DHCP lease' and 'IP assignment' MAASENG-3519

---

.gitignore
docs/MAASUI.md

- Explained the roles of Vitest and React Testing Library
- Explained important testing utility functions
- (drive-by) Added `.swp` (Vim temporary buffer) files to `.gitignore`
Fixes [MAASENG-3600](https://warthogs.atlassian.net/browse/MAASENG-3600)
[MAASENG-3600]: https://warthogs.atlassian.net/browse/MAASENG-3600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: Add explanation of Vitest, testing-library and util functions to MAASUI.md MAASENG-3600

---

README.md

- Added "Build upload" status to README

feat: Add 'Build upload' status to readme

---

package.json
yarn.lock

- Upgraded vanilla to v4.16.0
- Added list tree fix from @jmuzina (https://github.com/canonical/vanilla-framework/pull/5336)*
*We use the list tree component only in one place - the controller status card.

chore(deps): Upgrade vanilla-framework to 4.16.0

---

src/app/machines/components/MachineForms/MachineActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.tsx

- Enable noble as KVM host 
- ensure a machine can be deployed with noble and can be registered as kvm host

fix: enable noble as kvm host

---

src/app/api/base.ts
src/app/api/endpoints.ts
src/app/api/query-client.ts
src/app/api/query/base.ts
src/app/api/query/zones.ts

- Added comments and docstrings to helper functions surrounding react-query implementation
Resolves [MAAASENG-4252](https://warthogs.atlassian.net/browse/MAAASENG-4252)

chore(base): Add comments and docstrings to initial react-query code MAAASENG-4252

---

.github/workflows/pr-lint.yml

- Added "deps-dev" as a valid commit scope to help out dependabot

ci: add 'deps-dev' as a valid commit scope

---

sitespeed.io/login.js
sitespeed.io/scripts/machines.js

- Converted sitespeed files back to commonJS

fix: convert sitespeed back to commonjs

---

cypress/support/commands.ts

- fix cypress test maas ui failure
Fixes: [MAASENG-4542](https://warthogs.atlassian.net/browse/MAASENG-4542)
[MAASENG-4542](https://warthogs.atlassian.net/browse/MAASENG-4542)
[MAASENG-4542]: https://warthogs.atlassian.net/browse/MAASENG-4542?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MAASENG-4542]: https://warthogs.atlassian.net/browse/MAASENG-4542?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: cypress test maas ui failure

---

src/app/base/components/node/OverviewCard/MachineStatusCard/MachineStatusCard.test.tsx
src/app/base/components/node/OverviewCard/MachineStatusCard/MachineStatusCard.tsx
src/app/base/docsUrls.ts
src/app/machines/components/MachineForms/MachineActionFormWrapper/DeployForm/DeployFormFields/DeployFormFields.tsx

- Updated docs links for:
- Add machines
- Add chassis
- Cloud init
- Hardware sync
- Kernel options
Fixes:

docs: update links for machine add, hardware sync, cloud init and kernel options

---

src/app/base/docsUrls.ts

- Redirect links replaced with direct links

fix: MAAS UI docs links

---

package.json

- Changed version to `3.7.0` in package.json

chore: bump package version to 3.7.0

---

docs/RELEASE.md

- Added instructions for running UI sync job
- Added instructions for generating change log for new versions
- Removed outdated information and practices
Resolves [MAASENG-3604](https://warthogs.atlassian.net/browse/MAASENG-3604)
-->
[MAASENG-3604]: https://warthogs.atlassian.net/browse/MAASENG-3604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: update RELEASE.md with instructions for UI sync job and changelog generation MAASENG-3604

---

.github/workflows/accessibility.yml
.github/workflows/cypress.yml
.github/workflows/links-checker.yml
.github/workflows/playwright.yml
docs/RELEASE.md
package.json
src/app/api/query/sslKeys.test.ts
src/app/api/query/sslKeys.ts
src/app/preferences/views/SSLKeys/AddSSLKey/AddSSLKey.test.tsx
src/app/preferences/views/SSLKeys/AddSSLKey/AddSSLKey.tsx
src/app/preferences/views/SSLKeys/SSLKeyList/SSLKeyList.test.tsx
src/app/preferences/views/SSLKeys/SSLKeyList/SSLKeyList.tsx
src/testing/resolvers/sslKeys.ts

- updated AddSSLKey, AddSSLKey.test  and SSLKeyList, SSLKeyList.test to use API v3 with creating and updating pools
- created sslKeys.ts  and sslKeys.test.ts in app/api/query
- created sslKeys.ts in resolvers
<details>
<summary>
if you need a fake one click here 
</summary>
-----BEGIN CERTIFICATE-----
MIIFxzCCA6+gAwIBAgIUaVnUrXAAZxPhFyRVyJvJLOCjnRowDQYJKoZIhvcNAQEL
BQAwczELMAkGA1UEBhMCZ2IxDzANBgNVBAgMBmR1bmRlZTEPMA0GA1UEBwwGZHVu
ZGVlMSEwHwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQxHzAdBgkqhkiG
9w0BCQEWEGZha2VAZXhhbXBsZS5jb20wHhcNMjUwNDEwMTM0OTAzWhcNMjYwNDEw
MTM0OTAzWjBzMQswCQYDVQQGEwJnYjEPMA0GA1UECAwGZHVuZGVlMQ8wDQYDVQQH
DAZkdW5kZWUxITAfBgNVBAoMGEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDEfMB0G
CSqGSIb3DQEJARYQZmFrZUBleGFtcGxlLmNvbTCCAiIwDQYJKoZIhvcNAQEBBQAD …

feat(preferences): migrate ssl keys get and post to API v3 MAASENG 4621, 4622

---

.github/workflows/playwright.yml

- fixed yaml for playwright job

fix: correct yaml for playwright job

---

src/app/base/docsUrls.ts

- Updated links to redirect URLs

fix: Updated doc links after maas.io migration

---

src/app/api/query/notifications.ts

- implemented refetching backend notifications every 30 seconds
- implemented that only new notifications are added to the context 
Resolves: [MAASENG-5025](https://warthogs.atlassian.net/browse/MAASENG-5205)
[MAASENG-5025](https://warthogs.atlassian.net/browse/MAASENG-5205)
[MAASENG-5025]: https://warthogs.atlassian.net/browse/MAASENG-5025?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MAASENG-5025]: https://warthogs.atlassian.net/browse/MAASENG-5025?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Implement refetching for notifications MAASENG-5205

---

.github/workflows/test.yml
src/testing/utils.tsx

- Added unit test performance captures to setupMockServer and renderWithProviders
- Added upload log step to CI / Test job
Resolves [MAASENG-5362](https://warthogs.atlassian.net/browse/MAASENG-5362)
Measuring unit test performance was suggested recently. Feel free to provide feedback to improve this feature.
[MAASENG-5362]: https://warthogs.atlassian.net/browse/MAASENG-5362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: Unit test performance MAASENG-5362
